### ISSUE TITLE
Client version checking support for API

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#100]
We should implement some form of verification in the API to ensure that requests from our first-party client tooling (namely sensu-cli and dashboard) are compatible with the running API version. Using semantic versioning, we can determine that differences between versions. Major version differences should be rejected and an error should be returned. Minor, patch, and release version differences should be passed along but we can pass a "recommended" version via HTTP headers so that the clients can optionally display a "You might wanna upgrade, dude" message.

From the perspective of clients, each request to the Sensu API will be sent with a User-Agent which includes the tool name (sensu-cli, dashboard) and the version. We can do some User-Agent verification on the API side to ensure that we only verify versions with first-party tools. This could potentially be extended to "approved" or well known third-party tools.

This feature can also be used to let users know they need to force refresh / reload the dashboard (via a little JS notification, or such) after upgrades to the backend. This may help with issues that arise due to strict caching in client web browsers.

**Comment by annaplotkin** [comment]
Not really an issue since we now have a versioned API.
