### ISSUE TITLE
Agent RBAC role missing from role list and list-rules

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1003]
Cannot view and manage the built-in "agent" RBAC role.

<img width="813" alt="screen shot 2018-02-11 at 11 53 49 am" src="https://user-images.githubusercontent.com/149630/36077669-92586ce2-0f22-11e8-9f02-aef78bba68a1.png">

**Comment by palourde** [comment]
Closing this issue in favour of https://github.com/sensu/sensu-go/issues/1078
