### ISSUE TITLE
Implement etcd discovery

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1010]
When configuring a cluster in a dynamic environment such as Kubernetes, you can't predetermine IP addresses used by each pods, therefore etcd flags such as `--initial-cluster` or `--listen-peer-urls` are useless in this situation.

Therefore, we need to implement etcd discovery mechanism in sensu-backend: https://coreos.com/etcd/docs/latest/op-guide/clustering.html#discovery

**Comment by annaplotkin** [comment]
We are doing this in an appropriate way now. closing.
