### ISSUE TITLE
Automatically create a "default" environment when creating a new organization

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1027]
After some investigation it seems that creating a new organization does not automatically create a new environment. I'd like to see an environment called, "default" created when a new organization is made.

**Comment by zbintliff** [comment]
This is my lack of overall design knowledge of this project comes in.  The ticket makes it seem like `organization` contain `environments` but its seems the exact opposite (especially with the links going only from environments to organizations).  So then I got into a :rabbit: :hole:  trying to figure out if environments were global/unique, if organizations can live in multiple envs, should there be a reverse link from orgs to their envs, etc. 

From my digging it seems the "default" env should already exist and the  ticket is really just asking to register the org to the default env upon the org's creation. Is that a correct reduction?

**Comment by grepory** [comment]
Each organization has one or more environment, and those environments are unique to that organization. The issue we have is that it’s currently possible to create an organization with no environment. Doing this causes us to hit a few edge cases where we built in the assumption that there is always an environment within an org.
