### ISSUE TITLE
Agents can connect to backends with namespaces that don't exist

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1028]
We currently have no way of letting an agent know there was a problem. For example, an agent can specify an organization and/or environment that doesn't exist and is blind to whether or not it's registered in the backend.

I'd like to see a way for the backend to pass errors back to an agent so that the agent can print the error out via its logs. The agent should not stop trying to send keepalives or subscribing to topics. This will give users a bit more insight into why their agent may not be functioning as expected.

**Comment by palourde** [comment]
Summary of our discussion:

We should do that during the agent's authentication. However, the agent should not crash and we should take advantage of the fact that the agent will try to reconnect with backoff.

**Comment by annaplotkin** [comment]
Agent should crash and then output why.

**Comment by annaplotkin** [comment]
If this is related to backend issues being surfaced to the agent, this is relevant to our offline scheduling work.

**Comment by calebhailey** [comment]
There has been a number of improvements to agent / backend connectivity to the point where I wonder if this is still needed (or potentially already implemented)? 

Related: 
- https://github.com/sensu/sensu-go/pull/1057
- https://github.com/sensu/sensu-go/pull/3138
- https://github.com/sensu/sensu-go/pull/3310 

Flagging this as inactive. We'll close this during the next backlog review barring any objections.

**Comment by echlebek** [comment]
The issue appears to be valid still. Agents can connect to backends even though their namespace does not exist. It seems reasonable that the backend should reject requests for namespaces that don't exist.

**Comment by echlebek** [comment]
@calebhailey I've re-tagged this issue as a bug based on some cursory investigation.
