### ISSUE TITLE
Rethink organization creation

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1029]
Piggybacking off of https://github.com/sensu/sensu-go/issues/1027, we do not want to be in a state where an organization does not have an environment. We should investigate adding the ability to create one or more environments during the process of creating an organization.

e.g. `required: org, optional: []environments`

If no environments are specified, create a "default" environment.

**Comment by echlebek** [comment]
This was fixed at some point in the past. Organizations now have a default environment on creation.
