### ISSUE TITLE
Implement event occurrences

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1033]
Add an occurrence field to events which will represent the number of times an event has been created for a client/check pair with the same state (check status). Occurrences should not be tracked for client/check pairs with an exit status of 0.

Implementation of occurrences in Sensu 1.x can be found here: https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L571-L575

**Comment by grepory** [comment]
@amdprophet We've moved LastOK into event.Check--I think occurrences belongs there as well.
