### ISSUE TITLE
Implement last ok in events

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1034]
Add a last_ok field to events that will get updated with a timestamp every time an event with an exit status of 0 is received by a backend.

Sensu 1.x implementation: https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L584-L586

**Comment by palourde** [comment]
Hi @zbintliff,

That's definitively the right place! If you have any question or need assistance with this, don't hesitate to join us in our [Community Slack](http://bit.ly/sensucommunityslack) #sensu2 channel.

Thanks, this could really be an awesome functionality to add!
