### ISSUE TITLE
Update autocompaction retention setting 

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1069]
Issue [9337](https://github.com/coreos/etcd/issues/9337) has been resolved, and that fix has been backported to 3.3. We should update the config to be 1 instead of 1ns: https://github.com/sensu/sensu-go/blob/master/backend/etcd/etcd.go#L200

**Comment by grepory** [comment]
I think we may have to unvendor and revendor etcd to get this change if they didn't do a proper release / new tag for the 3.3 line of etcd.

**Comment by palourde** [comment]
Looks like it will be fixed with 3.3.2, which is not yet released but from what I can understand, it should be done in the next few days: https://github.com/coreos/etcd/issues/9411.

**Comment by grepory** [comment]
https://github.com/coreos/etcd/releases/tag/v3.3.2

Let's do this.
