### ISSUE TITLE
RBAC role rule object specific permissions

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1072]
Allow an RBAC role rule to declare permissions for a specific Sensu object (e.g. check "foo"). This improves RBAC granularity (beyond a resource type).

This could be accomplished by exposing the internally composed Sensu object SRNs, for example, `sensu.io:org:env:type:id`. The RBAC role rule can then apply permissions to the specific object via SRN, for example, `SRN: sensu.io:acme:demo:check:foo`.

User -> Role -> Role Rule -> Object

**Comment by jamesdphillips** [comment]
If we end up going in the SRN direction, the GraphQL service's globalid package implements something similar to what you described. May be able to repurpose, see: https://github.com/sensu/sensu-go/blob/master/backend/apid/graphql/globalid/components.go#L8-L25.

**Comment by palourde** [comment]
Closing that in favour of https://github.com/sensu/sensu-go/issues/535
