### ISSUE TITLE
Move hooks and silenced out of Event into event.Check

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1076]
The Event data structure needs only have 3 fields:
- Check
- Entity
- Metrics

Move both hooks and silenced out of event into Check. I believe we can do this lazily without a migration by simply starting to publish events that conform to the new data model.

There may be events that are no longer being updated, however (e.g. clients that have gone away, but check results are still persisted).

If we keep the fields in Event for now, and add them to Check, we can provide the migration path, and then deprecate the fields at the end of the alpha. (breaking change, delete the fields, supply something that migrates offline for users).

This will be one of our last chances to change the data format without providing long-lasting migrations or versioned APIs. So, let's make sure we get it right.

**Comment by echlebek** [comment]
This is going to break hooks and silenceds for existing installs. We should probably let people know somehow.

**Comment by grepory** [comment]
We have no way of communicating this.

**Comment by grepory** [comment]
Can we take a stab at writing some kind of blocking, db locking migration?
