### ISSUE TITLE
Backend REST API HEAD

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1091]
As a Chef user, I would like to manage Sensu 2.0 object configuration via the Backend REST API. Chef is my source of truth, my Sensu 2.0 installation has only one RBAC user with write permissions, "chef". Chef needs to be able to efficiently compare it's Sensu object configuration with the running configuration in Sensu 2.0. Fetching every Sensu object under Chef's management in order to compare configuration is not ideal and should not be necessary. Supporting Backend REST API HEAD request/responses for Sensu objects, for metadata, such as object etag, would provide a lightweight method of comparison.

**Comment by portertech** [comment]
I really like the idea of Sensu object resource etags. If Chef can either calculate the etags (anti-pattern?) or do a "scorched earth" run to create/re-create the objects and then record the etags as node data, it should be able to reliably detect divergence.

**Comment by echlebek** [comment]
We should add Etag to all requests returning resources, and possibly Last-Modified, since that information is also available to us.

**Comment by echlebek** [comment]
@portertech shall we add this to the GA milestone?

**Comment by echlebek** [comment]
We should still add Etag and LastModified to response headers. I'm putting this in the 5.1.0 milestone to make sure we revisit this.

**Comment by annaplotkin** [comment]
Closing for now, will reopen if it becomes a priority.
