### ISSUE TITLE
Check abilities before hitting store in apid/actions

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1095]
We have a number of places in the api actions where we're looking up something in the store before we check that the user has the ability to do so. The abilities check should be moved earlier in the function, so we can return without hitting the store if a user doesn't have that ability. For example:
```
func (a AssetController) Find(ctx context.Context, name string) (*types.Asset, error) {
	// Fetch from store
	result, serr := a.Store.GetAssetByName(ctx, name)
	if serr != nil {
		return nil, NewError(InternalErr, serr)
	}

	// Verify user has permission to view
	abilities := a.Policy.WithContext(ctx)
	if result != nil && abilities.CanRead(result) {
		return result, nil
	}
}
```
The abilities block just needs to be moved above the store call.

**Comment by grepory** [comment]
my $.02 - is it possible that we can move access control out of the controllers entirely?

**Comment by grepory** [comment]
If we know the HTTP verb and route, we should be able to resolve that to an access requirement and see if the user’s permissions satisfy that req.

**Comment by mercul3s** [comment]
Oh that's not a bad idea - we can probably move it to the routers because we know all the info there that is needed for an abilities check.

**Comment by jamesdphillips** [comment]
> If we know the HTTP verb and route, we should be able to resolve that to an access requirement and see if the user’s permissions satisfy that req.

This is tricky for routes like `POST /assets` where we do not know the organization and environment until the resource has been unmarshaled. Would also be a non-starter for the GraphQL service.

**Comment by grepory** [comment]
Sorry, but where did POST / come from?

I do think that GraphQL being a limiting factor here is unfortunate. But there’s nothing to stop us from figuring out how to do this relatively cleanly in the controllers.

Just unfortunate that we have to tightly couple these two things.

**Comment by palourde** [comment]
No longer relevant with our new RBAC implementation!
