### ISSUE TITLE
Add sensuctl entity create

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1099]
In order to use proxy checks, we'll want to create entities with the API/CLI beforehand.

This is somewhat complicated by the fact that doing so introduces the idea that we can _update_ entities--which for agents can be problematic because agents themselves are updating their entities and so what's the source of truth: that which exists in the store or that which the agent is telling us?

Regardless, we need to be able to create and update entities for proxy checks. I believe we already have the notion of a proxy entity type.

Would it be feasible for now to only allow the creation and updating of entities where type == proxy?

**Comment by echlebek** [comment]
This was done in #1495
