### ISSUE TITLE
Keepalived needs coordination

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1102]
Keepalived monitors are in-memory maps local to a single backend. If an agent is restarted, and connects to a new backend, its entity will get a new monitor. The old monitor will expire, and will then fire alerts even though the agent is connected to a new backend and sending keepalives. In some instances, if the agent connects and fails repeatedly, multiple alerts can be fired as each monitor expires. 
Some potential options are: 

- Use leader election to coordinate keepalives to a single backend; all entities will have a monitor constrained to this single backend.
- Entity monitors would be added to an in memory map of monitors shared between multiple backends.

**Comment by mercul3s** [comment]
@echlebek suggested we might be able to use a ring to store the agents the backend would be responsible for. Each agent's keepalive would be checked on every ring trip. New agents should be added to the ring on initial connect to the backend. When a backend dies, agents should connect to new backends and be added to new rings. We will need to also think about adding something like gossip so that an agent can get a pool of backend IPs to connect to on retry in case the connected backend disappears.

**Comment by echlebek** [comment]
Mercedes is going to file a proposal for this issue.
