### ISSUE TITLE
Rewrite e2e tests to work with clustered backend

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1104]
We don't currently have a good way of testing how sensu behaves in a cluster. Currently, we spin up a new backend per test. To start, we should spin up one clustered backend and run our test suite against that.

- [ ] Create a cluster by calling etcd.NewEtcd, passing it a config with clustering settings for each backend
- [ ] Implement an event listener via tcp to check that we get the number of messages we expect (ie if we expect one keepalive alert, we get only one alert)

We may need to do this piecemeal alongside other clustering work, as it may cause test failures. We want to avoid failing tests in master or long lived branches to fix _all_ of the e2e tests to work with clusters.

**Comment by echlebek** [comment]
We decided to remove e2e tests, so this can be closed. (Instead, we'll be creating a staging environment for holistic testing.)
