### ISSUE TITLE
megacheck is running out of memory

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1108]
Looks like megacheck sometimes gets killed, most likely because it's [running out of memory](https://github.com/travis-ci/travis-ci/issues/4192):

```
./build.sh: line 154: 13415 Killed                  megacheck $(go list ./... | grep -v dashboardd | grep -v agent/assetmanager | grep -v scripts)
The command "./build.sh $TEST_SUITE" exited with 137.
```

We should probably try to split this command into multiple smaller commands:
https://github.com/sensu/sensu-go/blob/a39f11a7820d16d16245ced0eaafb90d680062cc/build.sh#L163

**Comment by portertech** [comment]
MEGACHECK DEMANDS MEGA MEMORY!

![groans](https://user-images.githubusercontent.com/149630/36915946-53477a18-1e07-11e8-9f51-0238c6152db1.gif)

**Comment by echlebek** [comment]
Is there some way we can get a higher ulimit?

**Comment by palourde** [comment]
I saw that suggestion, we should probably test that: https://github.com/travis-ci/travis-ci/issues/4192#issuecomment-161800452
