### ISSUE TITLE
Configure Sensu-Go using a Terraform Provider for Sensu

### ISSUE THREAD

**Issue by thomasriley** [sensu/sensu-go#1129]
As a Terraform user I would like to configure the sensu-backend using a Terraform provider for Sensu.

This is specifically around configuring Sensu and not deploying Sensu. CM such as Chef, Puppet etc & deploying to Kubernetes with Helm etc would still be required. However, once the environment is online the Restful API would be configured via Terraform.

Terraform is effectively just another CM tool however I can see benefit for Terraform users. Terraform is designed toward configuring Restful APIs so feels like a suitable tool for managing the Sensu API. As an example, if I build an infrastructure stack in AWS using Terraform, I can include the Terraform code that configures the checks for monitoring services in that infrastructure stack, in the same codebase. When Terraform runs it will launch the AWS infrastructure and configure the required Sensu checks, handlers, etc at the same time. Any changes to that infrastructure code will subsequently be applied to the environment as Terraform manages the state of the environment. 

A check in Terraform may look like:
```
resource "sensu_go_check" "my_sensu_check" {
  name        = "my_sensu_check"
  subscribers = ["my_sub", "${var.my_sub_from_environment}"]
  command     = "/bin/run_this_script.rb"
}

```

In a previous environment I managed, the Sensu configuration was centrally configured in a single Chef cookbook. This works, however with the Terrafrom approach the configuration infrastructure code can reside with the codebase for the infrastructure to be monitored and therefore it is easier for project owners/contributors to take ownership of their monitoring. 

I am not in any way suggesting this replaces traditional CM tools, however it would be really great to have this as an option that works alongside other CM tools. Hybrid-CM :) 

I started [playing around](https://github.com/thomasriley/terraform-provider-sensu) writing a provider a while back, however sadly I have limited GoLang skills so it did not progress very far. I want to look at the Go client the CLI uses in the Sensu-Go codebase, however as I say the limiting factor is my lack of GoLang skills!

Myself and @barryorourke discussed the idea of using Terraform for configuring Sensu with @portertech on the Community chat this week (06/03/2018) and I'm raising this issue just to start a conversation on the idea.

Cheers,
Tom

**Comment by portertech** [comment]
Thanks @thomasriley 👍

**Comment by jtopjian** [comment]
Hello,

We've used Sensu 1 at `$work` for years. I'm quite familiar with Terraform, so in anticipation of Sensu 2, I thought the best way to get familiar with it (at least from a client-side) was to write a Terraform provider:

https://github.com/jtopjian/terraform-provider-sensu

It's heavily modeled off of the CLI interface and currently support basic CRUD functionality for most/all Sensu resources.

No doubt there are bugs, and I haven't used this for anything close to a production workflow, but it's available for anyone who wants to try it out :smile:

**Comment by thomasriley** [comment]
Awesome, thanks @jtopjian!

**Comment by grepory** [comment]
@jtopjian This is amazing. We just discovered this in one of our epic backlog grooming sessions. I'd love to hear about your use of this, and would like to catch you up on our API changes that we've been making. This really is fantastic.

**Comment by jtopjian** [comment]
@grepory Thanks!

I made the appropriate changes for the Namespace stuff shortly after it was committed, but haven't yet pushed them. I'll try to do that soon. Let me know if there's anything else I should be aware of.

I still haven't used this for anything of substance yet, though. It was really just my way of learning how Sensu 2 works. :)

**Comment by grepory** [comment]
That's so cool! We have two pretty big changes coming up. One is a reimplementation of RBAC:

https://github.com/sensu/sensu-go/issues/2243

Another is that we're getting ready to change all of our API routes to version the API and signal stability:

https://github.com/sensu/sensu-go/issues/2252

The latter shouldn't make a huge difference in sensuctl, but it's worth noting.

**Comment by jtopjian** [comment]
@grepory Cool - I'll check out the new RBAC when I get a chance, too. Thank you for the heads up :)

As a side note, considering the early stages of Sensu 2, I think the API docs are very well written. When doing something like this, I use the client library code as the source of truth and docs as secondary. For this provider, the docs matched up _really_ well with the code.

**Comment by jtopjian** [comment]
Quick update on this: https://github.com/jtopjian/terraform-provider-sensu has been updated to work with the Sensu Go 5.0.0 release. 

Namespaces are in place with the ability to set a namespace per resource as well as globally during authentication.

Roles were refactored and a new `sensu_role_binding` resource was created.

It's possible I missed a few other changes as I didn't review every type/resource in detail, but it compiles and all acceptance tests are passing :smile:
