### ISSUE TITLE
Add new issue github template

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1135]
New issues in GitHub should default to a template that describes how to file a good bug report.

Things we absolutely need:

Version information for sensuctl, sensu-backend, and/or sensu-agent.

If this was installed by a package.

Operating system and version.

A stack trace, if they have one.

Any relevant logs they can find.

What they expected to happen.

what actually happened.

The Sensu 1.x repo already has one of these, we can probably adapt it with good success.

**Comment by portertech** [comment]
The Sensu 1.x issue template https://github.com/sensu/sensu/blob/master/.github/ISSUE_TEMPLATE.md
