### ISSUE TITLE
Verify integrity of individual files after asset explosion

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1157]
As an asset maintainer, I want to be able to specify the SHA512s of individual files within the asset so that they can be verified after installed in the local package hierarchy.

If I add a checksums.json (we can just support JSON first, and more formats later) to the root of my asset, then sensu-agent will be able to verify the integrity of individual files post-install or at the very least ad-hoc.

I would suggest an out-of-band mechanism for doing this at first, so that we're not interrupting check execution and so that people could essentially cron this at first. Something along the lines of `sensu-agent verify-assets`. This would iterate through all installed assets and check the SHA512s of all files listed in the checksums.json file for that asset.

**Comment by echlebek** [comment]
If we intend to pursue this, let's add a proposal. :)

**Comment by annaplotkin** [comment]
Closing this for now, will reopen in future if it becomes a priority.
