### ISSUE TITLE
Per Agent Keepalive Event Handlers

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1160]
Sensu 1.x allows sensu-clients to declare Event Handlers for their Keepalive Events. The 1.x client configuration documentation for this feature can be found at https://docs.sensu.io/sensu-core/1.8/reference/clients/#keepalive-attributes.

Users should be able to specify Keepalive Event Handlers per Sensu 2.x Agent. Configurable via ENV variables, CLI arguments, and the Agent configuration file. If an Agent does not specify its Keepalive Event Handlers, the [default is used](https://github.com/sensu/sensu-go/blob/076be6c8c28baebe5a57ba9f02ff914358e5f572/backend/keepalived/keepalived.go#L29).

**Comment by palourde** [comment]
Just realized this feature is still not implemented from what I can see here: https://github.com/sensu/sensu-go/blob/33fbc584feb7bdddfe3a3df3b7fe46213a289c93/backend/keepalived/keepalived.go#L265

**Comment by palourde** [comment]
Implemented via https://github.com/sensu/sensu-go/pull/3507
