### ISSUE TITLE
ring.Remove should revoke leases

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1172]
After we fixed revoking client ring entries in the session upon shutdown, we moved leases out of the session into the ring. Now we don't revoke leases upon removal of items in the ring.

## Expected Behavior
The ring should revoke leases whenever an item is removed.

## Current Behavior
The ring does not revoke leases.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by echlebek** [comment]
Leases are per-ring, so ring.Remove should not revoke leases. Rings persist across backends, so their leases should be kept alive for the duration of the lifetime of the backends that hold them.
