### ISSUE TITLE
Improve display of scheduled silenced entries

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1176]
## Expected Behavior
When I create a silenced entry that only starts in the future, I expect to see the starting date when displaying the entry:

```
$ sensuctl silenced info 'entity:i-424242:*'
=== entity:i-424242:*
Begin:           Mar 18 2018 1:00AM
Expire:          1h
ExpireOnResolve: false
Creator:         admin
Check:
Reason:          Server upgrade
Subscription:    entity:i-424242
Organization:    default
Environment:     default
```

## Current Behavior
Right now, the silenced entry is displayed just like it's already been applied, which is confusing:

```
$ sensuctl silenced info 'entity:i-424242:*'
=== entity:i-424242:*
Expire:          41h32m2s
ExpireOnResolve: false
Creator:         admin
Check:
Reason:          Server upgrade
Subscription:    entity:i-424242
Organization:    default
Environment:     default
```

## Possible Solution

Add the `Begin` field when it starts in the future and correct the expiration.

## Steps to Reproduce (for bugs)

1. Create the following silenced entry:

```
sensuctl silenced create \
--subscription 'entity:i-424242' \
--begin 'Mar 18 2018 1:00AM' \
--expire 3600 \
--reason 'Server upgrade'
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): Master (https://github.com/sensu/sensu-go/commit/ee858323a6c85d0d166bf7b9362565fe08855c5b)
* Installation method (packages, binaries, docker etc.): Manually built
* Operating System and version (e.g. Ubuntu 14.04): macOS High Sierra 10.13.3

**Comment by echlebek** [comment]
We are doing this: https://github.com/sensu/sensu-go/blob/master/backend/store/etcd/silenced_store.go#L189

which makes implementing what you're asking for a bit tricky.

Should we do something else in the store, perhaps?

**Comment by palourde** [comment]
@echlebek If I recall correctly, we store the silenced entry with a `begin` timestamp. We could simply compare it to the current time when determining if a silenced entry is currently active. And we should probably ensure that pipelined also ignores silenced entries that have not started yet!

**Comment by echlebek** [comment]
@palourde yes we do store the `Begin` timestamp. The issue is that what we return for `Expire` is based on the TTL of a watcher that we kick off when we create the silenced entry, so there is no way to consistently compute the value you're asking for, because it relies on the current time.

We could change the store to return the original Expire value. Should we do that?

**Comment by palourde** [comment]
@echlebek I'm not 100% aware of all details around the 2.x implementation, but in summary:

- When creating a silenced entry, if `Begin` is not provided, set it to `time.Now().Unix()`. Also set the TTL to `Expire`
	- If `Begin` was provided, set the key TTL to something like `Begin - time.Now().Unix() + Expire`
- When evaluating if a resource if silenced, retrieve the key and if we do have one, make sure `time.Now().Unix() >= Begin`.

Makes any sense?

**Comment by echlebek** [comment]
It makes sense :)

Just had to fiddle with things a bit to get it right.
