### ISSUE TITLE
fileb0x broken during package builds

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1177]
## Expected Behavior
Packaging the dashboard succeeds without errors.

## Current Behavior
When running the packaging dockerfile, the following fileb0x error occurs:

```
/go/src/github.com/sensu/sensu-go
panic: bufio.Scanner: token too long

goroutine 1 [running]:
main.main()
        /go/src/github.com/UnnoTed/fileb0x/main.go:127 +0x24ea
Makefile:159: recipe for target 'build_backend' failed
make[2]: *** [build_backend] Error 2
make[2]: Leaving directory '/go/src/github.com/sensu/sensu-go'
Makefile:121: recipe for target 'sensu' failed
make[1]: *** [sensu] Error 2
make[1]: Leaving directory '/go/src/github.com/sensu/sensu-go'
Makefile:103: recipe for target 'linux' failed
make: *** [linux] Error 2
```

## Possible Solution
This could be due to a newer version of fileb0x being pulled in. If we can find a way to pin system-level Golang deps we may be able to solve this by using an older version of fileb0x.

## Steps to Reproduce (for bugs)
1. `docker build -t sensuapp/sensu-go-build -f Dockerfile.packaging .`
2. `docker run -it -v `pwd`:/go/src/github.com/sensu/sensu-go sensuapp/sensu-go-build`

## Context
Trying to test new packaging work, I've had to disable dashboard builds for now.

## Your Environment
N/A

**Comment by jamesdphillips** [comment]
😒 We should prioritize #910. Two birds with one stone.

**Comment by sureshsubramaniam** [comment]
facing same issues 
Done in 70.33s.
/opt/goproject/src/github.com/sensu/sensu-go
panic: bufio.Scanner: token too long

goroutine 1 [running]:
main.main()
        /opt/goproject/src/github.com/UnnoTed/**fileb0x/main.go:127 +0x24ea**
make[2]: *** [build_backend] Error 2
make[2]: Leaving directory `/opt/goproject/src/github.com/sensu/sensu-go'
make[1]: *** [sensu] Error 2
make[1]: Leaving directory `/opt/goproject/src/github.com/sensu/sensu-go'
make: *** [linux] Error 2
