### ISSUE TITLE
Hardware recommendations

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1183]
While load testing, after critical bugs have been fixed like #1182, identify hardware profiles required to reach different scales of load:

Based on # of messages processed per second and # of agents connected.

E.g. 5000 agents and 50 checks per agent is at most a little more than 4500 reqs/sec. At that rate, if it's possible, how much CPU, RAM, and disk throughput (in IOPS) do we need? (Hint that's about 4500 iops). So in google cloud, a single instance with a standard disk should be able to handle that read/write workload (standard disk has 15,000 iops).

For more information on storage performance in google cloud see: 
https://cloud.google.com/compute/docs/disks/performance

For information on storage performance in aws see:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-io-characteristics.html

And storage optimized instances in azure:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-storage

In general, we will likely need storage optimized instances in Azure and AWS.

For physical hardware recommendations, do it in terms of pure performance requirements: X cores/cpus, Y RAM, Z IOPS. And recommend SSD storage.

**Comment by echlebek** [comment]
See https://github.com/sensu/sensu-go/issues/1276 for some load testing notes.

**Comment by grepory** [comment]
I think this is actually a sensu-docs ticket, but let's just keep it here.

In the docs repo, in the 2.0 docs, in the getting started section add a hardware recommendations section/page.

**Comment by palourde** [comment]
Closed by https://github.com/sensu/sensu-docs/pull/372
