### ISSUE TITLE
Create "deep-merge" import tool

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1188]
Sensu 1.x has the ability to "deep-merge" objects in a very specific way.

See https://github.com/sensu/sensu/blob/44dc4263021782728c0d12b24f57c4cefd8e9360/lib/sensu/utilities.rb#L39 for the Ruby implementation

See https://github.com/sensu/sensu/blob/db1c6c1943ba0c0977ab1085f944f3546412c263/spec/utilities_spec.rb#L27-L64 for the Ruby specs.

We need to support this somehow, so that existing Sensu 1.x config can be imported into Sensu 2.x.

It will be up to the issue implementer to determine exactly how to do this. In discussions in the #core-dev slack channel, we identified two possible approaches:

**A Go utility that emulates the Ruby functionality to generate Sensu 2.x resource specs.**
Pros:
- Can easily ship with sensu-go.

Cons:
- Difficult to reproduce Ruby's logic, would require large amount of reflection and testing.

**A tool based on the existing Ruby logic that generates Sensu 2.x resource specs.**
Pros:
- Easy to reproduce the behaviour of the existing implementation.

Cons:
- Hard to ship a new Ruby tool. Might need to ship with the existing Sensu.

The tool needs to be able to iterate a directory of JSON fragments and reconstruct a set of Sensu resources the same way that the existing Sensu does. The output should be compatible with `sensuctl create`.

**Comment by portertech** [comment]
- We are going to include https://github.com/sensu/sensu-translator in Sensu Core 1.4.0 https://github.com/sensu/sensu/issues/1851

- We are going to remove `sensuctl import` https://github.com/sensu/sensu-go/issues/1355
