### ISSUE TITLE
Don't special-case assets in auth logic

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1192]
Assets apply to all environments within an organization. This makes them an exception to the other resources in terms of RBAC. See: https://github.com/sensu/sensu-go/blob/master/backend/authorization/authorization.go#L46

We should be able to remove the special case by hard-coding asset environments to be `*`. At this time it's unclear to me if that would have broader implications.

**Comment by portertech** [comment]
As long as it's not possible create and manage an environment named "*"

![200](https://user-images.githubusercontent.com/149630/37668033-b8b5204a-2c20-11e8-94b8-c535fd07c092.gif)

**Comment by echlebek** [comment]
I just checked - it's not, because environments cannot contain special characters.

**Comment by grepory** [comment]
This is no longer applicable.
