### ISSUE TITLE
Command timeout is not always working (checks, hooks)

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1194]
## Expected Behavior
If I create a hook that uses `sudo` in its command, but somehow it prompts for the password, the hook command should be killed after the specified timeout.

## Current Behavior

The hook command runs indefinitely, waiting on the password prompt. 

## Steps to Reproduce (for bugs)

1. Create a hook which uses `sudo`:
```
$ sensuctl hook create nginx-restart  \
--command 'sudo systemctl restart nginx' \
--timeout 10
```
2. Assign that hook to a check:
```
sensuctl check set-hooks nginx_process  \
--type critical \
--hooks nginx-restart
```
3. Run an agent that's subscribed to this previous check
4. Verify the agent logs:
```
{"component":"agent","error":"check execution still in progress: nginx_process","level":"error","msg":"error handling message","time":"2018-03-20T14:28:50-04:00"}
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): Master (https://github.com/sensu/sensu-go/commit/ee858323a6c85d0d166bf7b9362565fe08855c5b)
* Installation method (packages, binaries, docker etc.): Manually built
* Operating System and version (e.g. Ubuntu 14.04): macOS High Sierra 10.13.3

**Comment by nikkiattea** [comment]
Is this behavior seen on checks as well? Or just hooks? Curious because I think they use a lot of the same logic!

**Comment by palourde** [comment]
Oh good question, I'll test that right away

**Comment by grepory** [comment]
It just needs to correctly adhere to the hook execution or general timeout.

**Comment by grepory** [comment]
I can't remember if we investigated it previously, but we should look into using CommandContext instead of exec.Command and include a timeout.

**Comment by nikkiattea** [comment]
Sensu 1.x is unable to kill `sudo` processes which eventually result in zombies. Sensu 2.x will have that same behavior. We'll also want to document our recommendation to users to avoid using `sudo` in execution commands for that reason. We can however, still escape the zombies so checks and hooks are not blocked from executing.
- https://github.com/sensu/sensu/issues/1831
- https://github.com/sensu/sensu/pull/1849
