### ISSUE TITLE
"proxy_requests" flag not available in sensuctl

### ISSUE THREAD

**Issue by bukiadeniji** [sensu/sensu-go#1204]
"proxy_requests" are documented in the Sensu2 docs, but sensuctl does not contain a flag to configure "proxy_requests" (or "entity_attributes") when creating a proxy check. 

## Expected Behavior
There should be a flag to configure "proxy_requests" and  "entity_attributes" when creating proxy checks.

## Current Behavior
Cannot configure checks with proxy_requests

## Possible Solution
`sensuctl check create check_proxy_foo -c "check-foo.rb -h :::address:::" --handlers email -i 60 --ttl 120 -s MON --proxy_requests true --entity_attributes "entity.Class == 'agent'"`

## Steps to Reproduce (for bugs)
N/A

## Context
Use case: I want an external central agent to do a ping check (or ssh check) to all 500+ (and growing) servers in my network. 
Currently unable to create a proxy requests with attributes that match multiple entities. Alternative is to create 500+ checks for just one parameter - which  is not feasible

## Your Environment
* ```
sensu-backend version
sensu-backend version 2.0.0-nightly#150c23b, build 150c23b72eb7c2be78773294a2da3397bb781cf7, built 2018-03-09T01:43:45+0000
```
* Installation method (packages, binaries, docker etc.): **Packages**
* Operating System and version (e.g. Ubuntu 14.04): **CentOS Linux release 7.4.1708**
* Entities: **500+**

**Comment by bukiadeniji** [comment]
Related to: #1205

**Comment by majormoses** [comment]
Agreed this makes sense and it will be included before GA. I can't speak of where this will fall on the teams priorities.

Have some thoughts that might help you out:

> Alternative is to create 500+ checks for just one parameter - which is not feasible

This is very much doable with any CM or orchestration tools.

> I want an external central agent to do a ping check (or ssh check) to all 500+ (and growing) servers in my network.

You might want to consider using a robin subscription so if you hit bottlenecks you can scale out by adding more nodes to the subscription.

**Comment by palourde** [comment]
Hi @bukiadeniji,

Because the `proxy_requests` attribute contains a more complex data structure, we decided to move it to its own subcommand: `sensuctl check set-proxy-requests`. It can be used like this:

```
$ cat <<EOF | sensuctl check set-proxy-requests {check_name}
{
   "entity_attributes":[
      "entity.Class == 'agent'"
   ]
}
EOF
```

We are currently actively working on the 2.0 documentation and sensuctl, so we will definitively work on improving the user experience around proxy check requests.

Thank you for reporting this issue and do not hesitate to let us know if there's anything else!
