### ISSUE TITLE
Implement etcd auth

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1214]
As part of the work necessary to implement clustered Sensu, we'll need to add authentication for etcd, using its auth package. https://godoc.org/github.com/coreos/etcd/auth

Currently, with etcd being bound to localhost, this is not really necessary, but will become necessary when moving to a clustered environment.

Thanks @majormoses for pointing this out.

**Comment by palourde** [comment]
@echlebek Are we talking about client authentication (which the auth package provides) or peer (server-to-server) authentication?

Regarding client authentication, while we don't need to expose the port for clustering, it might still be a good practice to enable authentication even if we listen on localhost. The next question is whether it should automatically done by Sensu (I can see few challenges with that) or we should let users deal with that by exposing the right flags.

Concerning the peer authentication/encryption, it could be relatively easily done by exposing the right flags (`--peer-client-cert-auth` etc.) but I don't see an easy way for automating that in Sensu without the use of CM or the operator.

**Comment by grepory** [comment]
We should expose the right flags instead of trying to automate authentication (at least, for now).

This does include server-to-server / peer authentication.

**Comment by cyphus** [comment]
The client auth is related to #1963. Essentially, doing client auth when listening on localhost requires our users to create/manage their own CA. I don't think we could reasonable automate something like that, especially for organizations that specifically disallow custom CAs.

**Comment by cyphus** [comment]
In the current sensu-go, if you configure sensu-backend to use TLS, it uses it for the dashboard, etcd client, and API services, but not for etcd peer auth.

**Comment by echlebek** [comment]
What Greg said :)

**Comment by grepory** [comment]
Having these things be individually customized is something we can discuss at a later date, but let's just reuse the same cert everywhere for now.

**Comment by grepory** [comment]
ACTUALLY.

We should try to avoid allowing agents/users of the dashboard etc. that can authenticate with peer verification authenticate to the etcd peer listener.

If someone connects to the peer listener and injects themselves into raft, they have the ability to hose the etcd cluster.

I'm inclined to say use separate certs "for etcd".
