### ISSUE TITLE
Produce JSON resources compatible with sensuctl create subcommand

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1221]
Related to https://github.com/sensu/sensu-go/pull/1187

Now that we are adding the ability to create resources with `sensuctl create`, using a new `Wrapper` struct, we should make sure that JSON resources printed by sensuctl are compatible, so users don't have to modify the JSON structure or don't have to start from scratch when creating a new resource. For example:

```bash
$ sensuctl check info check-cpu --format json > check-cpu.json
$ vim check-cpu.json # modify some attributes etc.
$ sensuctl create -f check-cpu.json
```

As per [Eric suggestion](https://github.com/sensu/sensu-go/pull/1187/files#r176783752), a possible solution:

> the API would wrap all of its responses?

**Comment by grepory** [comment]
sensuctl would wrap the api response(s) -- leading to no breaking change in the api.

**Comment by echlebek** [comment]
Let's create a new output format called "Sensu Wrapped JSON". Users can select that format when configuring sensuctl. When the format is selected, all types will be wrapped before serialization.

**Comment by nikkiki** [comment]
@echlebek I was actually thinking of having the new output format to be assigned by the `--format` flag. That way, a user can change between `json` and `wrappedJson` without having to reconfigure sensuctl. What do you think?

**Comment by echlebek** [comment]
@nikkiki same thing basically - it should work for both modes. Perhaps the `wrappedJson` name would be more appropriate since we want to pass it to a command-line flag.

How about `wrapped-json`?

We should take pains to describe its purpose in the interactive configure mode as well.

**Comment by nikkiki** [comment]
@echlebek If this will just be a new command line `--format` type, what is its purpose in `sensuctl configure`? Are you suggesting that we should provide the user an option to configure the default format, but also be able to override the configured format using a flag?

And yes, `wrapped-json` is more appropriate, I'm not sure why my brain defaulted to camel case.

**Comment by echlebek** [comment]
The `--format` flag corresponds to the format the user can select in `sensuctl configure`. It's just a way to override it.

**Comment by nikkiki** [comment]
@echlebek I'd love to show you what I have so far. It has the desired effect, but I want your feedback on the approach I took. Free to pair whenever you are!

```
nattea@Nikkis-MacBook-Pro.sensu-go (master)$ bin/sensuctl check info tester --format wrapped-json
{
  "type": "Check",
  "spec": {
    "command": "echo test",
    "environment": "default",
    "handlers": [],
    "high_flap_threshold": 0,
    "interval": 10,
    "low_flap_threshold": 0,
    "name": "tester",
    "organization": "default",
    "publish": true,
    "runtime_assets": [],
    "subscriptions": [
      "system"
    ],
    "proxy_entity_id": "",
    "check_hooks": null,
    "subdue": null,
    "ttl": 0,
    "timeout": 0,
    "executed": 0,
    "history": null,
    "issued": 0,
    "status": 0,
    "total_state-change": 0,
    "last_ok": 0,
    "occurrences": 0,
    "occurrences_watermark": 0,
    "output_metric_format": "",
    "output_metric_handlers": []
  }
}
```
