### ISSUE TITLE
Check subscriptions & handlers can be null

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1234]
When creating a check via `sensuctl create -f`, the subscriptions field can be null.

## Expected Behavior
Subscriptions & handlers should be an empty array if not defined.

## Current Behavior
Subscriptions & handlers can be null.

## Possible Solution
Determine if subscriptions/handlers are set, if not create an empty array.

## Steps to Reproduce (for bugs)
1. `sensuctl create -f` with a check that does not have any subscriptions defined.
2. `sensuctl check info check_name`

## Context
N/A

## Your Environment
N/A

**Comment by grepory** [comment]
Implement the defaults in the API.
