### ISSUE TITLE
Event validation surrounding the presence of metrics and/or checks

### ISSUE THREAD

**Issue by nikkiattea** [sensu/sensu-go#1247]
Solve the issue presented in #1126 
>Metric events are sent to the backend. (The backend will probably discard that event since it doesn't contain a check, which is fine for now.)

## Expected Behavior
Event containing metrics (but no check) is properly handled.

## Current Behavior
Error handling event:
https://github.com/sensu/sensu-go/blob/a27ab4b9a5b3f6c4edcb625ec8f69fef50efa626/backend/agentd/session.go#L137-L139
Caused by event validation:
https://github.com/sensu/sensu-go/blob/a27ab4b9a5b3f6c4edcb625ec8f69fef50efa626/types/event.go#L74-L76
Log:
```
{"component":"agentd","error":"malformed event","level":"error","message":{"Type":"event","Payload":"eyJ0aW1lc..."},"msg":"error handling message","time":"2018-03-28T11:21:36-05:00"}
```

## Possible Solution
1. Change event validation so that it requires either a check or metric `(entity && (check || metric))`. We'll also have to check for mutual exclusivity whenever invoking `event.check` and `event.metric`.
2. Spoof a check to be added to a metrics event - perhaps we could use it to provide additional context to the metrics.

**Comment by echlebek** [comment]
I think the right thing to do here is to make `Event` an interface. We'll split the current Event type into multiple types, `CheckEvent` and `MetricsEvent`. We already have an outstanding issue to make breaking changes for the Event type (by removing Hooks and Silenced), so we may as well go all-in.

(n.b. Hooks and Silenced were moved into Check a while ago and are deprecated for Event now.)

```
type Event interface {
    // Time returns the time the event was emitted at.
    Time() time.Time

    // GetName returns the name of the event
    GetName() string

    // GetEntity() gets the entity associated with the event.
    GetEntity() *types.Entity

    // GetHandlers gets the handlers the event is associated with
    GetHandlers() []string

    Validator
    Resource
}
```

In places where we need to handle check-specific or metrics-specific information, we can use type assertions.

**Comment by nikkiattea** [comment]
@echlebek I am on board for this for a few reasons. Firstly, I already had an unsuccessful attempt at decoupling checks and events without breaking changes. At the time, I considered a proposal to store metrics in a different scope than an event, but interfacing the event did not even cross my mind. Secondly, I think this method will be a much cleaner approach than having to manage `check || metrics` in any given  event.

My largest concern is not that it's a breaking change, rather it's the size of the refactor required. I'd love to hop on a call sometime next week to try to plan and spec out this work. Call is open to anyone else that would like to take part in the discussion!

**Comment by echlebek** [comment]
I thought about this some more last night and meant to make a comment.

I think at this stage in the game, refactoring this type would be pretty detrimental. It's just used in too many places, including our new RPC. So let's not do that. Suggestion withdrawn. :)

**Comment by nikkiattea** [comment]
Oh it certainly is in many places, which is why we need a more robust approach. I'll do some research into alternative solutions, but in this case we should definitely open up the discussion to more opinions. We should discuss in sprint planning when to schedule a call for this issue.

**Comment by nikkiattea** [comment]
So reiterating some key points from a quick discussion, thankfully we do not need a large redesign here:
1. An event may contain a check, metrics, or both.
2. If an event contains a check, it should be stored (by eventd).
3. If an event does not contain a check (it must contain metrics), it should skip eventd and be passed to pipelined.
4. If an event contains both a check and metrics, the handlers of each type are invoked.
5. https://github.com/sensu/sensu-go/issues/1310
