### ISSUE TITLE
Create a default read-only user

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1252]
When sensu-backend is first initialized, during the db seeding stage, create a read-only user with username/password sensu/sensu.

**Comment by cyphus** [comment]
I should have asked this awhile ago, but what is the purpose of the default read-only user?

**Comment by grepory** [comment]
Many customers manage Sensu with configuration management currently, and we are pretty sure many will want to continue with Sensu 2. The current default user is an administrator with global write access. Users can use this for CM and get everything they want—except a read-only user that they can hand out to their users/consumers of sensu to login w/ for sensuctl and the web ui.

**Comment by grepory** [comment]
It is a compliment to and a complement of the default admin user.
