### ISSUE TITLE
Use square brackets to indicate optional positional arguments and flags

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1269]
Currently, in most sensuctl sub-commands, we use square brackets to indicate positional arguments.

example:

```
Usage:	sensuctl check create [NAME] [flags]
```

Here, `[NAME]` is not optional but `[FLAGS]` are.

We are not really consistent about this throughout the UI. For instance,
```
Usage:	sensuctl check COMMAND
```
is returned for `sensuctl check -h`.

In most unix commands, square brackets indicate an optional portion of a command. We should use that convention in sensuctl, to be consistent with the principle of least surprise.

**Comment by ccressent** [comment]
For whoever picking this issue up:

[This chapter of the POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) should be followed to try to standardize these synopses. Additionally, `man 7 man-pages` mentions:
> SYNOPSIS
>
> briefly describes the command or function's interface. For commands, this shows the syntax of the command and its arguments (including options); boldface is used for as-is text and italics are used to indicate replaceable arguments. Brackets ([]) surround optional arguments, vertical bars (|) separate choices, and ellipses (...) can be repeated.

Finally, [this comp.unix.programmer thread](https://groups.google.com/forum/#!topic/comp.unix.programmer/XOr31SgvvS8) also has a good summary!
