### ISSUE TITLE
[Web UI] Explore switch to Apollo from Relay

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1278]
Explore switch to Apollo from Relay.

- As time has proceeded Apollo has continued to become better supported by the community
- Apollo continues to be simpler, easier to configure and more malleable.
- While not strictly true simplifies; usage maps better to react-router v4's declarative routing approach.
- more...

**Comment by 10xjs** [comment]
Current progress in https://github.com/sensu/sensu-go/tree/web/apollo

**Comment by 10xjs** [comment]
PR: #1289
