### ISSUE TITLE
Use constants instead of hardcoded strings for all rules, all orgs, all envs

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1285]
Inspired by this TODO https://github.com/sensu/sensu-go/blob/master/backend/authorization/authorization.go#L19-L23

Let's make the concept of `"*"` more explicit and manageable by turning all hardcoded string values for all rules, all organizations, and all environments into constants, and updating all references in the codebase/tests.

For example:
`rule := *FixtureRule("*", "*")` would become `rule := *FixtureRule(types.OranizationAll, types.EnvironmentAll)`

**Comment by annaplotkin** [comment]
This is done.
