### ISSUE TITLE
Don't reference vendored proto files

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1304]
Recently, someone tried to compile our `rpc/extension.proto` but was unable to, because they did not have the `vendor` directory. We depend on protos in a vendored Go project, and so if that directory is not present our protos can't build.

Getting this directory depends on `go and dep`, but to build our proto files, you should not need go at all.

Investigate to see if we can change the way this works. Can we have the protos elsewhere? It would improve ergonomics for those authoring extensions considerably.

**Comment by grepory** [comment]
We check-in compiled extension.pb.go now.
