### ISSUE TITLE
sensuctl uses configuration directory that is not intuitive when not on macos

### ISSUE THREAD

**Issue by ghoneycutt** [sensu/sensu-go#1323]
sensuctl uses a  configuration directory that is not intuitive on *nix systems other than macos. Mac's use `~/.config/foo` though it on other *nix systems the common place for configs would be in `~/.foo` for an application named Foo.

## Expected Behavior
sensuctl keeps information in `~/.sensu` on unix systems other than macos.

## Current Behavior
sensuctl keeps information in `~/.config/sensu`.

## Possible Solution
Use `~/.sensu` on posix systems and `~/.config/sensu` on macos.

## Your Environment
2.0.0 nightly build

**Comment by amdprophet** [comment]
Hi @ghoneycutt,

We're following the XDG spec for *nix platforms as detailed https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html. The XDG directories can be overridden using environment variables, see: https://github.com/sensu/sensu-go/blob/master/util/path/path.go.

We are also planning on enabling overriding of paths with environment variables on a per-tool basis. E.g. `SENSUCTL_CONFIG_PATH` but it looks like this is only partially implemented at this time.

**Comment by portertech** [comment]
Given we are following a standard that is consistent across all *nix platforms, I am going to close.

@ghoneycutt thanks for creating the ticket 👍
