### ISSUE TITLE
[Web UI] Polling on events page is very disruptive

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1328]
## ✏️ Notes

- List is continually reordered making it difficult to click entries
- If selected, state is lost when a record is updated
- Jarring.

## ✨ Expected

- When new entries are available add banner with link to explicitly add/remove entries.
- Entries in the list are updated but not re-orded.
- Selection state should never be lost

**Comment by 10xjs** [comment]
I'm thinking that an approach that conditionally enables polling would be good solution.

By default, if the user hasn't interacted with the selection state and the sort is latest desc, auto loading new results at the top would not be disrupted.

Once the user makes a selection or changes the sort method, a banner could alert them that there are new results are available, allowing them to manually refresh the list state if they want.

We could handle this all at the component level within the query, leaving the outer `pollInterval` (or potentially the GraphQL subscription) intact. The child list component could enter a "locked" state, with the current list of result moved to component state. It would continue to accept new results through props and would itself prompt the user to accept new results. This could be achieved nicely as a HOC.

**Comment by portertech** [comment]
Curious to know how we are addressing this in the Sensu Enterprise Dashboard (and Uchiwa).

**Comment by portertech** [comment]
As discussed, an immediate "solution" would be to disable polling and add a refresh button to all views.

**Comment by portertech** [comment]
@jamesdphillips could you please create a separate issue for this immediate solution?
