### ISSUE TITLE
[Web UI] Redirect to next available environment if 'Environment not found' occurs after deletion.

### ISSUE THREAD

**Issue by 10xjs** [sensu/sensu-go#1329]
Create an `EnvironmentNotFoundContent` component to be used within each `EnvironmentView` content component when the requested environment does not exist  (in place of currently used `NotFoundView`).

It should show an environment switcher UI (like in the `Drawer` component) to give the user a quick way to visit an environment that exists.

**Comment by annaplotkin** [comment]
As a user, I would like a seamless transition back to the UI after deleting the default environment. 

Acceptance criteria: 

- After deletion of the default environment, if there is another available environment, bypass the 404 and take the user back to Home with the next available environment loaded. 
- If there is NOT another available environment we will show a 404.
