### ISSUE TITLE
[Web UI] AppLayout component

### ISSUE THREAD

**Issue by 10xjs** [sensu/sensu-go#1372]
Create a new `AppLayout` component to takeover the responsibility of `AppFrame` and `AppContent`.

`/src/component/layout/AppLayout` will implement the outermost layout of the page, taking `topBar`, `content`, and `quickNav` as props.

`/src/component/layout/` will serve as a location for other "layout" components to live (`SidebarLayout`, `FullPageLayout` etc.)

**Comment by annaplotkin** [comment]
Our general layout and pages should help inform this.
