### ISSUE TITLE
Store events in a boltdb on each backend

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1397]
Sensu events are relatively ephemeral. They come into the system, hang around for a bit, and are eventually pushed out by other events. This stream of events generates a history, capped in length.

This makes etcd a remarkably poor choice for storing events, as it leads to etcd needing to perform compaction very regularly. Etcd never throws anything away, unless it's specifically told to do so via compaction. So, every store in etcd for a given key means that a GC cycle will need to pick up the old bits of data later on.

For much of the information in Sensu, this cost is well worth it. All backend nodes can get access to a single consistent database that can tolerate failure. However, since events are ephemeral, storing them in etcd is a worse value proposition than the other datatypes we store.

I propose that we off-load event storage to a BoltDB file on every backend, since events are scoped to backends. BoltDB is the storage engine that etcd uses, and is well known for being performant and reliable.

With this scheme, we will need to merge events from all backends on API requests to `/events`, so that work needs to be done as part of this issue. This will save us from having to do any coordination around events at the expense of the response time for the `/events` API.

**Comment by calebhailey** [comment]
Nice!

**Comment by echlebek** [comment]
This will be happening after GA.

**Comment by grepory** [comment]
I'm going to close this for now. We can revisit potential solutions when we get to the point of needing to optimize event storage
