### ISSUE TITLE
Add request timeout and retries to etcd queue

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1403]
As a follow up to #1280, the backend queue implemented on top of etcd should have a default timeout for requests, complete with retries on failed requests.

## Context
Currently, the etcd queue allows caller code to specify a timeout by passing in a context with a timeout when calling queue operations. Request timeouts are a standard part of etcd usage, and a reasonable default timeout/retry behavior will work for all known etcd queue use cases. 

Implementations should continue to allow for context to be passed in so that callers can further customize request behavior if desired.

**Comment by palourde** [comment]
I believe a lot of refactoring has been done around queues since this issue was opened. I'll close it for now and we can re-open something if required.
