### ISSUE TITLE
statsd feature causing e2e tests to fail

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1411]
In a recent e2e test run, the following is logged repeatedly, forever, to the console:

```
{"level":"warning","msg":"Error reading from socket: read udp 127.0.0.1:8125: raw-read udp 127.0.0.1:8125: not implemented","time":"2018-04-30T17:54:19Z"}
```

It seems we should disable statsd for the e2e tests?

**Comment by nikkiattea** [comment]
@echlebek what e2e test is failing here? I'm curious why the agent in the test is unable to start up that port. And yes, we should probably should disable statsd for e2e tests.

**Comment by nikkiattea** [comment]
I have a hunch that this is related to #1402

**Comment by echlebek** [comment]
@nikkiattea unfortunately I couldn't get a sensible log from the test, because the test was continually writing new log output. The test just ran forever and never failed. I eventually manually killed it. :(

**Comment by echlebek** [comment]
Looks like that log message is a red herring.
