### ISSUE TITLE
sensu-agent crashes when sensu-backend is killed

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1414]
## Expected Behavior
The `sensu-agent` process should continue running and retry connection to backend when backend connection fails (e.g. due to the `sensu-backend` process being killed).

## Current Behavior
The `sensu-agent` process panics with the following trace:

```
{"component":"agent","level":"info","msg":"scheduling check execution: test","time":"2018-04-30T13:19:49-07:00"}
{"component":"agent","level":"debug","msg":"check execution completed for test","time":"2018-04-30T13:19:49-07:00"}
{"component":"agent","level":"info","msg":"sending keepalive","time":"2018-04-30T13:19:57-07:00"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x15a368c]

goroutine 4 [running]:
github.com/sensu/sensu-go/agent.(*Agent).receiveMessages(0xc4201ad220, 0xc420042060)
    /Users/mercedes/dev/go/src/github.com/sensu/sensu-go/agent/agent.go:232 +0x10c
created by github.com/sensu/sensu-go/agent.(*Agent).receivePump
    /Users/mercedes/dev/go/src/github.com/sensu/sensu-go/agent/agent.go:279 +0x10d
```

## Possible Solution
Probably missing a `nil` check somewhere..

## Steps to Reproduce (for bugs)

1. Start `sensu-backend` and `sensu-agent`
2. Kill `sensu-backend` with interrupt.

## Context
Discovered while looking into #1407

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): latest master at time of writing (commit a78431e205573a)
* Installation method (packages, binaries, docker etc.): ./build.sh
* Operating System and version (e.g. Ubuntu 14.04): macOS High Sierra

**Comment by amdprophet** [comment]
This may be related to https://github.com/sensu/sensu-go/issues/1159.

**Comment by echlebek** [comment]
@cyphus are you still able to reproduce this?

**Comment by cyphus** [comment]
Unfortunately, no. Not on the latest master. I'm going to close this, but we can reopen if it pops up again.
