### ISSUE TITLE
Be able to import checks using JSON

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1415]
It would be handy if a check and other commands supported `create` via a JSON import.  Maybe something like this:

```
sensuctl check create --file /path/to.json
```

Testing sensuctl for automation in Puppet with @ghoneycutt

Version: `sensu-ctl version dev-nightly#f7a7790, build f7a7790556ab7f398b25a30977a29bf5172b5e49, built 2018-04-28T09:23:42+0000`

Based on other issues seems the `import` command will be going away and wasn't intended for this purpose which is also supported when trying to import v2 checks:

```
# cat /tmp/check.json | sensuctl import -v
ERROR Only importing of legacy settings are supported at this time.
```

**Comment by palourde** [comment]
Hi @treydock,

As you noticed, the `import` command is indeed going away (see https://github.com/sensu/sensu-go/issues/1355), in favour of https://github.com/sensu/sensu-translator, which will be shipped with Sensu Core in a future version.

That being said, we do have the capability of importing resources via their JSON definition, using the `sensuctl create` command:

```
$ sensuctl create -h
create new resources from file or STDIN

Usage:	sensuctl create [-f FILE] [flags]
```

Please note that the resource itself needs to be wrapped with the [`Wrapper` struct](https://github.com/sensu/sensu-go/blob/a78431e205573a347f985fbe55b96a4888f71019/types/wrapper.go#L10), which would look like this:

```
{
  "type": "Check",
  "spec": {
    "name": "foo",
    "command": "echo 0",
    "interval": 60,
    "subscriptions": ["linux"],
    "environment": "default",
    "organization": "default"
  }
}
```

This command is relatively new so we still need to adapt the `info` subcommands so the JSON produced is compatible with `sensuctl create` (https://github.com/sensu/sensu-go/issues/1221) and document that functionality (https://github.com/sensu/sensu-docs/issues/386).

Let us know if there's anything else!
