### ISSUE TITLE
sensuctl check update seems incomplete

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1416]
Possibly related to #1415 

It appears that the `sensuctl check update` command is missing the ability to actually modify a check.  For the purposes of automation it would be handy if one could update multiple properties of a check with a single command instead of executing many `set-` and `remove-` commands.

@ghoneycutt

Version: `sensu-ctl version dev-nightly#f7a7790, build f7a7790556ab7f398b25a30977a29bf5172b5e49, built 2018-04-28T09:23:42+0000`

**Comment by palourde** [comment]
Hi @treydock,

The `sensuctl create` command does have the ability to modify an existing check using a JSON definition. See https://github.com/sensu/sensu-go/issues/1415 for more information.

Thanks!
