### ISSUE TITLE
Add support for CheckConfig in sensuctl create command

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1418]
Right now the `CheckConfig` type can't be created with `sensuctl create`, because it lacks a `URIPath` method:

```
$ cat check.json
{
  "type": "CheckConfig",
  "spec": {
    "name": "foo",
    "command": "echo 0",
    "interval": 60,
    "subscriptions": ["linux"]
  }
}
$ sensuctl create -f check.json
error parsing spec: "CheckConfig" is not a Resource
Error: some resources couldn't be parsed
```

We should also double check that all resources that can be created through the API/CLI also have this method.

**Comment by echlebek** [comment]
This got fixed at some point in the past. Working now. :)
