### ISSUE TITLE
Update go to 1.10.2

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1420]
Update project to golang's new minor release: https://golang.org/doc/devel/release.html#go1.10.minor

**Comment by echlebek** [comment]
Let's do this soon, no reason to lag behind on Go releases.

**Comment by nikkiki** [comment]
travis.yml already accounts for minor releases:
```
go:
- 1.10.x
```
I think we just have to do the same for appveyor.yml
```
environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10.x
```
