### ISSUE TITLE
Come up with a way to pin protobuf plugin dependencies

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1432]
We need a way to pin protoc dependencies (`github.com/golang/protobuf` and `github.com/gogo/protobuf`) so that when developers generate our protos, they get the same results.

It seems like the vendor directory and dep won't work for this, so we'll need another way.

The solution should be simple, straight-forward, and work reliably in a cross-platform manner.

**Comment by grepory** [comment]
This is done with a combination of go generate and vendoring gogo/protobuf and golang/protobuf.
