### ISSUE TITLE
Build and package on FreeBSD

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1433]
Sensu 1.x provides and supports the monitoring agent on FreeBSD.

- [ ] Test and build 2.x on FreeBSD
- [ ] Create a 2.x FreeBSD Universal .txz file

**Comment by 1992kk** [comment]
Any plans for sensu-go-client to be available for FreeBSD?

**Comment by hgfranco** [comment]
@annaplotkin why was this closed?

**Comment by nikkixdev** [comment]
@hgfranco FreeBSD binaries can be found in our officially supported [downloads](https://sensu.io/downloads)!
