### ISSUE TITLE
Timezones are not properly handled when creating a silenced entry

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1448]
## Expected Behavior
When specifying a beginning date with a specific timezone, I expect this timezone to be used.

## Current Behavior
The timezone is ignored and we don't throw any error. In this example, I expect the entry to start at `May 04 2018 5:30PM EST` but when displaying it, I have `04 May 18 23:30 EDT` instead!

```
$ date
Fri May  4 17:18:58 EDT 2018
$ sensuctl silenced create \
--subscription 'entity:i-424242' \
--begin 'May 04 2018 5:30PM EST' \
--expire 3600 \
--reason 'Testing'
OK
$ sensuctl silenced list
         ID            Subscription     Check          Begin          Expire   ExpireOnResolve   Creator   Reason    Organization   Environment
 ─────────────────── ───────────────── ─────── ───────────────────── ──────── ───────────────── ───────── ───────── ────────────── ─────────────
  entity:i-424242:*   entity:i-424242           04 May 18 23:30 EDT   59m59s   false             admin     Testing   default        default
```

## Steps to Reproduce (for bugs)

1. Create a silencing entry, with a date in the future:
```
sensuctl silenced create \
--subscription 'entity:i-424242' \
--begin 'May 04 2018 5:30PM EST' \
--expire 3600 \
--reason 'Testing
```
2. List the silenced entries:
```
sensuctl silenced list
```
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `master`
* Installation method (packages, binaries, docker etc.): manually
* Operating System and version (e.g. Ubuntu 14.04): macOS 10.13.4

**Comment by jamesdphillips** [comment]
What is the timestamp on the entry? In other words, is the issue on create or when we format the date?

**Comment by palourde** [comment]
@jamesdphillips It's stored with the wrong date. For example, using `--begin 'May 04 2018 5:30PM EST'`, it gives the following:

```
$ sensuctl silenced list --format json
[
  {
    "id": "entity:i-424242:*",
    "expire": 24310,
    "creator": "admin",
    "reason": "Testing",
    "subscription": "entity:i-424242",
    "organization": "default",
    "environment": "default",
    "begin": 1525491000
  }
]
```

Where `1525491000` is:
![screen shot 2018-05-04 at 5 45 12 pm](https://user-images.githubusercontent.com/4105580/39654487-062a258a-4fc3-11e8-8a37-6c4ae323c71d.png)

**Comment by echlebek** [comment]
@palourde just an observation, `04 May 18 5:30 PM EST` should be `EDT` since daylight savings occurs in March.

**Comment by palourde** [comment]
@echlebek See below

```
$ sensuctl silenced create \
--subscription 'entity:i-424242' \
--begin 'May 04 2018 5:00PM EDT' \
--expire 3600 \
--reason 'Testing'
Error: cannot find EDT in zip file /usr/local/Cellar/go/1.10.2/libexec/lib/time/zoneinfo.zip
```

**Comment by echlebek** [comment]
:confused:
