### ISSUE TITLE
Creating handler from JSON does not support custom keys

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1451]
## Expected Behavior

I'd expect a custom key in JSON spec for `sensuctl create -f` to be added to a handler and possibly other types.

## Current Behavior

Current behavior is custom key `"foo": "bar"` is not added to a handler.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat /tmp/handler.json
{
"type": "Handler",
"spec":
{
  "name": "test",
  "type": "pipe",
  "command": "test",
  "environment": "default",
  "organization": "default",
  "foo": "bar"
}
}

[root@sensu-backend ~]# sensuctl create -f /tmp/handler.json
[root@sensu-backend ~]# sensuctl handler info test --format json
{
  "name": "test",
  "type": "pipe",
  "command": "test",
  "timeout": 0,
  "handlers": null,
  "filters": null,
  "env_vars": null,
  "environment": "default",
  "organization": "default"
}
```
## Context

I am attempting to automate `sensuctl` with Puppet and wanted to support adding custom properties to any type.  This works with `check` type.  I've only tested this failing behavior with `handler`.  @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version dev-nightly#9bba4cf, build 9bba4cf6af864bbabf0a3120ec2ad6d187552a8b, built 2018-05-06T09:24:10+0000`
* Installation method (packages, binaries, docker etc.): RPM packages
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by treydock** [comment]
Just found `asset` type has this same issue.

**Comment by ghoneycutt** [comment]
It was not clear that only checks and entities supported custom data. We don't have a need to add functionality, just to understand where custom data is allowed.

**Comment by echlebek** [comment]
Custom attributes are only mentioned in the Check documentation AFAIK. Perhaps we need add a note for custom attributes in general, since they are more widely supported in 1.x.

**Comment by grepory** [comment]
Custom attributes have been deprecated. That being said, all top-level API objects now have object metadata including labels and annotations.
