### ISSUE TITLE
OpenTSDB metrics extraction not working

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1462]
OpenTSDB metrics extraction appears to be broken.

## Expected Behavior
OpenTSDB metrics are extracted.

## Current Behavior
OpenTSDB metrics are not extracted.

## Steps to Reproduce (for bugs)
1. Create a check that outputs: `sys.cpu.user host=webserver01,cpu=0  1356998400  1\n` and has a metric format of `opentsdb_line`
2. Observe event, which should contain metric values but does not.

## Context
Found during beta QA.

## Your Environment

* Sensu version used: e91bfb3194d6be72e1b74a7a9500afe0a765f0c7
* Installation method: `build.sh docker`
* Operating System and version: Fedora 26

**Comment by nikkiki** [comment]
Addressed in https://github.com/sensu/sensu-go/pull/1458

**Comment by echlebek** [comment]
@nikkiki the logs show:

```
{"component":"agent","error":"invalid opentsdb metric timestamp, must be an integer: host=webserver01,cpu=0","level":"error","msg":"unable to extract metric from check output","time":"2018-05-07T20:58:45Z"}
```

Are you sure trimming the whitespace addresses this?

**Comment by nikkiki** [comment]
@echlebek Oh, well that error log is much more informative! See https://docs.sensu.io/sensu-core/2.0/guides/extract-metrics-with-checks/#supported-metric-formats for an example on a properly formatted opentsdb metric: `sys.cpu.user 1356998400 42.5 host=webserver01 cpu=0`. The timestamp should be the second value.

**Comment by nikkiki** [comment]
I think you might be looking at an example query, not an example format. I'll let @palourde weigh in on this as well, I think he has more experience with the opentsdb transformer implementation.

<img width="999" alt="screen shot 2018-05-07 at 5 27 22 pm" src="https://user-images.githubusercontent.com/10634078/39726134-0e2c0072-521c-11e8-9e46-da475123f9bc.png">

**Comment by echlebek** [comment]
@nikkiki ah you are correct. I was using the wrong format.
