### ISSUE TITLE
[Build stability] intermittent failure in TestRoundRobinScheduling e2e

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1463]
Investigate intermittent failure in e2e TestRoundRobinScheduling:

```
--- FAIL: TestRoundRobinScheduling (47.62s)
        Error Trace:    round_robin_scheduling_test.go:99
        Error:          Not equal:
                        expected: 15
                        actual: 14
```

**Comment by grepory** [comment]
If someone runs into this, please to be +1ing this.

**Comment by grepory** [comment]
We need some more context on how/when this fails. Under what conditions did it fail? Is it related to overall slowness in the test execution (since e2e tests are all parallel)

**Comment by echlebek** [comment]
I think that now that we've improved the overall stability of e2e tests, and also decided to eventually remove these tests, that this can be closed. Re-open if failure occurs again.
