### ISSUE TITLE
Set deprecated flag on deprecated event proto fields

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1478]
Event proto fields are deprecated, but we didn't set the deprecated flag.

Set the flag so that people don't start relying on them.

Fields to be deprecated:
* silenced
* hooks

**Comment by mercul3s** [comment]
What is the desired behavior for a deprecated field? It's pretty straightforward to add `deprecated=true` to the proto file, but it doesn't look like it's being marked in the generated file as deprecated.

**Comment by echlebek** [comment]
@mercul3s it is informational only I believe.
