### ISSUE TITLE
Document and diagram the inbound event flow in 2.x

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1481]
If you need access to Lucid Chart, let @grepory know

**Comment by mercul3s** [comment]
Link to draft in Lucid chart. If this looks good, I'll add it to the engineering wiki. 
https://www.lucidchart.com/invitations/accept/3f4b48d2-7a5a-4243-8a9d-c6c5e05c9e1b

**Comment by mercul3s** [comment]
This diagram now lives in the [Sensu Engineering Wiki](https://github.com/sensu/engineering/wiki/Sensu-Architecture).
