### ISSUE TITLE
Document and diagram check execution flow in 2.x

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1482]
If you need LucidChart let @grepory know

**Comment by cyphus** [comment]
I followed the code in agentd and schedulerd and came up with the following: https://www.lucidchart.com/invitations/accept/79bd9102-04d3-4b1e-ae21-1f57cab2f25e

After reviewing in Slack, I'll add this to the engineering wiki: https://github.com/sensu/engineering/wiki/Sensu-Architecture

**Comment by cyphus** [comment]
Reviewed and added to the engineering wiki: https://github.com/sensu/engineering/wiki/Sensu-Architecture
