### ISSUE TITLE
Document and diagram daemons in 2.x

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1483]
If you need LucidChart access ask @grepory

**Comment by grepory** [comment]
This includes exposing information like ports that things listen on, what talks to each daemon, and how they interact via the message bus.

**Comment by cyphus** [comment]
This is too big a task for someone who's going to be at a convention this sprint. It's open to anyone else who wants to take it.

**Comment by cyphus** [comment]
The daemon diagram has been reviewed on Slack and can be viewed here: https://www.lucidchart.com/invitations/accept/e5866eed-a84d-4471-b79e-856e60b9dfba

**Comment by cyphus** [comment]
I've exported the svg and put it in the [engineering wiki](https://github.com/sensu/engineering/wiki/Sensu-Architecture)

Closing as complete!
