### ISSUE TITLE
Deleting and creating a check with the same key does not work

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1487]
## Expected Behavior
A check is deleted, and then created again. The newly created check gets scheduled.

## Current Behavior
The check does not get scheduled.

## Steps to Reproduce (for bugs)
1. Create a check with a given name, org and env.
2. Delete the check.
3. Create the check again with the same name, org and env.

**Comment by grepory** [comment]
This is subsumed by #1573.
