### ISSUE TITLE
Add optional timezone to `when` attribute in event filters

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1489]
While testing filters for the Sensu 2.0 Beta, I discovered the [`when` attribute](https://docs.sensu.io/sensu-core/2.0/reference/filters/#when-attributes). I wrote my first filter with a `when` clause of 9am-6pm weekdays, and applied it to an event.

Despite being within the accepted time, the event was being filtered. I discovered that `when` attributes are applied using UTC and not local time (see 
[filter.go](https://github.com/sensu/sensu-go/blob/master/backend/pipelined/filter.go#L29) for the source).

It's important to use a consistent time zone for `when` attributes, because we want filtering to be consistent across timezones. However, using UTC is surprising to new users, and forces them to have to convert the times in their `when` attributes to UTC, which is an error prone and somewhat painful process. I suggest adding an optional `timezone` attribute to the `when` attribute, like so:

```json
{
  "when": {
    "days": {
      "all": [
        {
          "begin": "5:00PM",
          "end": "8:00AM"
        }
      ]
    },
    "timezone": "America/Vancouver"
  }
}
```

Now, timezone offset can be applied automatically by Sensu, instead of manually. If `timezone` is omitted, UTC can be assumed.

Don't forget to update the filter docs with this new info once it's implemented.

**Comment by grepory** [comment]
Time/range specification is being completely reworked.
