### ISSUE TITLE
[Discussion] Move Web UI into it's own repository

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1494]
## Problem

* Building the frontend pollutes our build process
  * Requires that a recent version of node and yarn are installed
  * Each frontend build takes ~ 30-90 seconds; regardless of whether any changes were made
  * Frontend build scripts have failed during release process for reasons that remain unclear   
* The entire CI test suite is ran for changes to the frontend

## Proposed

* Move the frontend into it's own repository
* Create releases like any other semver'd project 
* Attach bundled application as tarball to release in GitHub 
* Either;
  * Release process of backend pulls latest release and creates a boxed asset file
  * Manually pull latest frontend release and create boxed file on occasion. (`go generate`)

### Pros

* Simpler; frontend application and backend are decoupled
* Github and tooling in the it's halo are not really geared toward mono repositories. 
* CI can be tuned specifically for frontend application
* Frontend isn't buried in sensu-go repository
* Familiar

### Cons

* Mono repositories are nice.
  * An engineer / a group of engineers can build a feature from stem to stern in one repository; potentially entirely in one pull request.
  * There is never any confusion where to create a GH issue. We never have to politely ask a user to re-open their issue in a different repo.
  * E2E suite can live in the same place as everything else, and it is always run against both latest front and backend code.
  * Adds indirection, it may not always be clear to a engineer where a component lives.
* Not much value to a separately versioned frontend application. Only adds extra process.
* Extra coordination is required to make service or frontend changes. Frontend cannot ship until backend is ready; backend cannot ship changes that break frontend.
  * Eg. recent breaking changes to pagination were made simple by being able to bundle required changes across the product in one patch.

## Other Potential Solutions

Remove generation of boxed frontend from build pipeline. Only Generate frontend on occasion either manually or through automated system.

**Comment by grepory** [comment]
I don't think we have any intent of doing this. If we do, we can reopen this issue later.
