### ISSUE TITLE
Use retry library for e2e tests

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1501]
In our e2e tests, many tests depend on waiting for a length of time to "ensure" that the operation we apply will be scheduled or otherwise executed.

This leads to our tests taking longer to run than they need to in the common case, and failing because they didn't run long enough in the odd case.

Use the retry library to retry getting and checking results, instead of waiting for a set period of time. Retry up to 1 minute for each case, using exponential backoff.

**Comment by nikkiki** [comment]
@echlebek do you think this is still necessary after https://github.com/sensu/sensu-go/pull/1553 or the planned changes to our e2e tests?

**Comment by echlebek** [comment]
This is actually done already :)
