### ISSUE TITLE
Agent Check command allow list

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1507]
## Background

A Sensu Backend can instruct an Agent to run Checks, which execute commands on the Agent's host. In Sensu 1.x, the Sensu Client has a "safe_mode" feature, which stops the Client from executing Checks when it does not have local configuration for them (including the commands to execute). As all configuration in Sensu 2.x is done centrally via the Backend API (w/ RBAC), a "safe_mode" feature has not yet been implemented. This functionality is desired by some organizations, e.g. financial.

## Feature Request

Support optional Agent configuration to specify a list of allowed Check commands. If configured, the Agent compares received Check commands with its allow list. If a Check command is not in the allow list, the Agent does not execute the command and responds with an Event declaring this fact (with Check status of 3).

**Spec/Implementation details:** [Agent 'Allow' List spec](https://docs.google.com/document/d/1ZaOhpG0J2SHhX-MZmDgRrFDWFME3FV6LTScv_10ssYE)

**Comment by portertech** [comment]
@jspaleta we can probably start w/ full command string matching.

**Comment by echlebek** [comment]
I see the motivations for using the command or the command executable name in an allow-list, but I have to disagree about implementing the feature this way.

*Alternate proposal*:
Allow a list of checks by name, with optional Etag.

*Rationale*
The check name is the only unique identifier for a check, and it is ultimately the only key we want to provide in check management. With the addition of the Etag, the assertion becomes even stronger, verifying that the check is the same as it was at the time it was added to the allow list.

**Comment by jspaleta** [comment]
i think check name plus etag covers the underlying issue.  if someone changes the check definition (either by accident or malicious intent) the etag prevents running the check until agent undates the etag.

Could this also spawn a sensu event if a list check is out of check-etag compliance? 
Maybe make it possible to define a handler for check-etag compliance violation?  Similar to how statsd metric event has a defined handler without being a check result.

**Comment by portertech** [comment]
@echlebek @jspaleta etag would need to be consistent across installations. I should be able to rebuild an installation and my allow list should still be correct. Using only the command was intentional, allowing me to change handlers etc w/o having to update the 10k+ allow lists 😬

**Comment by echlebek** [comment]
@portertech consistent etags are achieved easily enough with hashing, but maybe I'm missing something?

Due to the existence of check environment variables, the check command alone is probably not enough to achieve safety. (Suppose `PATH=/path/to/evil` or any other number of tricks you can perform with environment variables)

**Comment by jspaleta** [comment]
@portertech, @echlebek  
Picking this discussion up again... the resource name + etag  mechanism has additional benefits...providing a "safe mode" for assets as well.

resource name + etag whitelist would support users who want to disable asset usage entirely, which maybe desirable for some users.  Users who want to lock down the checks, will probably want to disable assets entirely.

**Comment by majormoses** [comment]
@jspaleta @echlebek I just found this issue and I am gonna have to disagree that we should be checking based on the check name. The whole point is to prevent the server from instructing a client to run code it is not aware of. While what you propose is closer to the implementation previously in 1.x there are several reasons why this does not cover the main concern. The main concern is that there is implicit trust between the server and the client with this approach as the client has no control, if we are concerned about what the client executes based on the server then the bad actor can simply change the contents of the command server side bypassing the primary objective. Maybe I am missing something and not thinking it through but I don't think that is the best solution. I would prefer to do some kind of fuzzy matching on the command string. perhaps we do not evaluate any command line options when specifying it. For example I would want to ensure that no sensu check is executing `dd`, `rm`, etc as I can't think of a good reason why a good actor would need that. Another example would be wanting to ensure that checks do not contain `||`, `&`, or `&&` in their command string.
