### ISSUE TITLE
Agent disable Check Assets

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1508]
## Background

Some Sensu users use configuration management to manage all Check runtime dependencies and would like to disable Check Assets for specific (or all) Agents.

## Feature Request

Support optional Agent configuration to disable Check Assets. If configured (disabled), when the Agent receives a Check request that includes Runtime Assets, the Agent does fetch the Assets and does not execute the the Check command and responds with an Event declaring this fact (with Check status of 3).

**Comment by portertech** [comment]
Do we support only specifying the binary in addition to full command match?

**Comment by annaplotkin** [comment]
We have an updated version of this ticket we are going to use.
