### ISSUE TITLE
[Web UI] Upgrade to babel 7

### ISSUE THREAD

**Issue by 10xjs** [sensu/sensu-go#1509]
## What

Update babel (and sibling dependencies) to v7. (`babel-core@6` -> `@babel/core@7`)

## Why

Babel offers support for JSX fragments. (Using the empty tag syntax `<>...</>` instead of `<React.Fragment>`)

We don't want to depend on babel v6 once it is no longer the latest major version.

## Considerations

For the time being this is a relatively low priority. Babel v7 is currently in beta, we should wait for the stable release.

**Comment by 10xjs** [comment]
https://babeljs.io/docs/en/v7-migration

**Comment by jamesdphillips** [comment]
Closed by #2824
