### ISSUE TITLE
Commit vendor directory, remove dep from build pipeline

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1511]
We often have build errors because dep fails to pull all vendored packages. If we want reproducible builds we need to commit our vendor directory and stop running dep as part of the build.

I also think it would be a good idea to add a git hook that would run before pushing to a remote, that runs dep and checks for any changes to `vendor`. The hook should cause failure if any changes are detected.

**Comment by amdprophet** [comment]
Implemented in #1530.
