### ISSUE TITLE
Token evaluation on extended attributes can cause non-intuitive error

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1512]
## Expected Behavior
If a proxy check request evaluates an extended attribute (i.e. `entity.Team == "ops"`) and one entity does not have this attribute, a debug statement should be added, informing the user why this entity was discarded.

## Current Behavior
An non-intuitive error is currently presented to the user, using the `error` log level, e.g.:

```
{"component":"schedulerd","error":"failed to evaluate the expression: input is empty, get [team] from invalid","level":"error","msg":"expression 'entity.Team == \"ops\"' is invalid","time":"2018-05-11T14:33:01-07:00"}
```

## Possible Solution
We need to better handle that condition, by only adding a debug log entry, while making sure an invalid expression (i.e. `foo &&`) is still logged as a proper error.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Reported by `@Buki A` on #core-dev.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): dev-nightly#15dc116, build 15dc1161f2df631d4fc6b72de95b2d38037fb22a, built 2018-05-09T09:23:45+0000
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by nikkiki** [comment]
Improve logging statements here..

**Comment by mercul3s** [comment]
We should be validating any govaluate expressions when resources are created (pass fixture event to the govaluate expression) and return an error if it is not valid. That way, we error earlier instead of at process time.

**Comment by echlebek** [comment]
Funny enough it looks like we already do that, I guess Simon already thought of that when he implemented it before. :)

So I guess this ticket is simpler than I thought.
