### ISSUE TITLE
Unable to create hook with sensuctl create

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1520]
## Expected Behavior
I'd expect `sensuctl create -f` to be capable of creating a hook without validation errors when name is specified.

## Current Behavior
`sensuctl create -f` fails to pick up the name specified.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat /tmp/hook.json
{
"type": "Hook",
"spec":
{
  "name": "process_tree",
  "command": "ps aux",
  "timeout": 60,
  "environment": "default",
  "organization": "default"
}
}

[root@sensu-backend ~]# sensuctl create -f /tmp/hook.json
error validating resource 0 (/hooks/): hook name must not be empty
Error: resource validation failed
```

The validation failure does not occur with `sensuctl hook create process_tree --command "ps aux"`.

## Context

I am working with @ghoneycutt to automate sensu v2 and am using `sensuctl create -f` to manage resources.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version dev-nightly#2b0fd48, build 2b0fd48ffb8b00950d158a72d0854c2d44e1169c, built 2018-05-12T09:27:26+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by echlebek** [comment]
This bug is due to a json tag being set for the HookConfig, an embedded type of Hook. When this tag is set, embedding is not treated in the same way by the json encoder and decoder.

The solution is to modify the embedded HookConfig in hook.proto, with:
```
(gogoproto.jsontag) = ""
```
