### ISSUE TITLE
Unable to create role with sensuctl create -f

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1522]
## Expected Behavior

I would expect a `role` to be able to be created using `sensuctl create -f` like other types.

## Current Behavior

Currently the error is `error parsing spec: "Role" is not a Resource`

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat /tmp/role.json
{
  "type": "Role",
  "spec": {
    "name": "test",
    "rules": [
      {
        "type": "*",
        "environment": "*",
        "organization": "*",
        "permissions": [
          "read"
        ]
      }
    ]
  }
}
[root@sensu-backend ~]# sensuctl create -f /tmp/role.json
error parsing spec: "Role" is not a Resource
Error: some resources couldn't be parsed
```

## Context

I am working with @ghoneycutt to automate sensu v2 with Puppet.  We are using `sensuctl create -f` as a standard way to manage resources.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version dev-nightly#2b0fd48, build 2b0fd48ffb8b00950d158a72d0854c2d44e1169c, built 2018-05-12T09:27:26+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by echlebek** [comment]
Role needs a URIPath method to be defined on it, like the other resources.
