### ISSUE TITLE
Unable to create silencing with sensuctl create -f

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1523]
## Expected Behavior

I'd expect `sensuctl create -f` to be capable of adding a silencing.

## Current Behavior

Seems the API call being made is a `PUT` rather than a `POST` but that's just a guess.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat /tmp/silencing.json
{
"type": "Silenced",
"spec": {
  "expire_on_resolve": true,
  "check": "test",
  "subscription": "entity:sensu-backend.example.com"
}
}
[root@sensu-backend ~]# sensuctl create -f /tmp/silencing.json
Error: PUT "/silenced/": {"code":2,"error":"not found"}
```

## Context

I am working with @ghoneycutt to automate sensu v2 using Puppet and all types are standardized around managing their resources using `sensuctl create -f`.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version dev-nightly#2b0fd48, build 2b0fd48ffb8b00950d158a72d0854c2d44e1169c, built 2018-05-12T09:27:26+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by echlebek** [comment]
The URIPath method on the Silenced type is likely wrong, so start investigating there.
