### ISSUE TITLE
Sensuctl check round robin interactive default

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1536]
## Expected Behavior
When creating a check using sensuctl interactive mode, I should be able to leave non-required fields blank.

## Current Behavior
The round robin field attempts to parse the empty string as a boolean (also, the field is missing a `:` after the field name).
```
✘ Sorry, your reply was invalid: strconv.ParseBool: parsing "": invalid syntax
? Round Robin [? for help] 
```

## Possible Solution
The round robin default option might not be set properly.

## Steps to Reproduce (for bugs)
1. `sensuctl check create --interactive`
2. Fill in only the required fields, press enter for non-required fields
3. Round robin prompts you to answer either `true` or `false`

## Context
Its a slight inconvenience and inconsistency. There are other non-required boolean fields that behave properly.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): master @ https://github.com/sensu/sensu-go/commit/5999049927a8b70c71156eed888552cb60456351
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS High Sierra 10.13.4

**Comment by mercul3s** [comment]
Maybe not related, but I also noticed there is no default interval setting; I think it should default to 60 seconds if no time or cron is provided.
