### ISSUE TITLE
[Build stability] - integration test phantom failure

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1550]
Integration tests failed on both Appveyor and Travis. Interestingly, there were no actual test failures, but a lot of keepalived update failure messages. The tests seemed to succeed, but the build script exited with 1, which failed the build. The build succeeded after a retry. The logs were lengthy, so I added them as gists.
[Travis build log](https://gist.github.com/mercul3s/0e632ffd4f0d0d6b7c441248794437b5)
[Appveyor build log](https://gist.github.com/mercul3s/e638a51710a8c9de432689695cb2a0ba)

**Comment by nikkiki** [comment]
Hit this on a recent appveyor build: [log.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a00d6eb9a65e90012552ede/125516c66e82c728ace21e0d46e49b9d61cec1b99de6b546a749b2ce6b137f707957a67c2687e27cba112b585a5f4fad120a5f15afeb9539e4e76224d50152a7842f4d7ed43c18a6b9871db907bd218b4f82b5b5825e8d.txt)

**Comment by nikkiki** [comment]
Reopening.. the phantom failure is back https://ci.appveyor.com/project/sensu/sensu-go/build/1.0.3018/job/3rdik0p1cuhpr3ps

**Comment by annaplotkin** [comment]
Closing this one, we will open another issue with more details if we encounter this again.
