### ISSUE TITLE
Check with an asset on a windows agent breaks events page on dashboard

### ISSUE THREAD

**Issue by andrewalkema** [sensu/sensu-go#1556]
I am testing using assets with the windows agent.  I set up an asset and set up a check to use that asset.  After the check fires, the events page no longer loads.  

## Expected Behavior
This is intertwined with another issue I'm having with the Windows agent - it doesn't seem to have access to the PATH.  I expect to see an error saying something like `The argument 'check-site.ps1' to the -File parameter does not exist`.

## Current Behavior
What I see currently is a white page.  I see the following error in sensu-backend.log:
```
{"component":"apid.routers","errors":[{"message":"interface conversion: interface {} is nil, not int","locations":[]}],"level":"error","msg":"error(s) occurred while executing GraphQL operation","time":"2018-05-17T12:42:57Z"}
```

## Steps to Reproduce (for bugs)
1.  Create an asset (threw a little ps1 script up on nofile):
```
Sensuctl asset create check-site.tar -u https://nofile.io/g/Y2YlEd8RBGs96KdSMX83GX8HQ0BbPi2usy8nHtD729Zqf1fCs60v8LFwiim8Az92/checksite.tar/ --sha512 98890ae970a2fcfa95f2023ef65bdf224f2e72c49e7f824e6790c4b9229212f54cf28c3e383ade85327385c1dd73741e3c34efffa49bce7b1b136a01bbd53ea8
```
2.  Create a check that uses that asset:
```
sensuctl check create check-google --command "C:\Windows\System32\WindowsPowerShell\v1.0\Powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo -f check-site.ps1 https://google.ca" --subscriptions "GoogleProxyAgent" --interval 60 --runtime-assets check-site.tar --proxy-entity-id google
```
Note: I do see the agent having downloaded this asset.
3.  Load events page - white screen.

## Context
We'll be using windows agents quite a bit, and assets seem like a great feature, so I'd like to get them working.

## Your Environment
* sensuctl version: sensu-ctl version #f70b9f8, build f70b9f8a14ea926e4ce85467beecfe5cf731513d, built 2018-05-08T03:51:45+0000
* sensu-backend version: sensu-backend version dev-nightly#9bba4cf, build 9bba4cf6af864bbabf0a3120ec2ad6d187552a8b, built 2018-05-06T09:22:49+0000
* sensu-agent version: sensu-agent version #f70b9f8, build f70b9f8a14ea926e4ce85467beecfe5cf731513d, built 2018-05-08T04:01:02+0000
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): agent: Windows 10, backend: Amazon Linux

**Comment by andrewalkema** [comment]
Updated backend to: `sensu-backend version 2.0.0-nightly#44fc6fd, build 44fc6fd582d928ee6474539a498da7529a0a244c, built 2018-05-17T01:02:59+0000` and the issue persists.

**Comment by echlebek** [comment]
@jamesdphillips do you have any insight on this issue?
