### ISSUE TITLE
Sensuctl create -f only creates last resource in file

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1565]
I think something funky is happening with the pointers in `parseResources`. Sensuctl only creates the last resource in a file with multiple resources of the same type when using `sensuctl create -f`.

## Expected Behavior
All resources in the file get created.

## Current Behavior
Only the last resource of the file gets created.

## Possible Solution
Investigate `parseResources` and `resources` which it returns:
https://github.com/sensu/sensu-go/blob/c33d2bce6330d0253db6eaddf7d940a73028ffd5/cli/commands/create/create.go#L94-L109

## Steps to Reproduce (for bugs)
1. Create a file `handlers.json`
```
{
	"type": "Handler",
	"spec": {
		"command": "hi",
		"name": "handler1",
		"type": "pipe",
		"environment": "default",
		"organization": "default"
	}
}
{
	"type": "Handler",
	"spec": {
		"command": "hi",
		"name": "handler2",
		"type": "pipe",
		"environment": "default",
		"organization": "default"
	}
}
{
	"type": "Handler",
	"spec": {
		"command": "hi",
		"name": "handler3",
		"type": "pipe",
		"environment": "default",
		"organization": "default"
	}
}
```
2. `sensuctl create -f handlers.json`
3. `sensuctl handler list --format json`
4. Observe only the last handler of the file gets created
```
[
  {
    "name": "handler3",
    "type": "pipe",
    "command": "hi",
    "timeout": 0,
    "handlers": null,
    "filters": null,
    "env_vars": null,
    "environment": "default",
    "organization": "default"
  }
]
```

## Context
I think we're getting trolled by a pointer. We're not creating all the resources in a file.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): master @ https://github.com/sensu/sensu-go/commit/c33d2bce6330d0253db6eaddf7d940a73028ffd5
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS High Sierra

**Comment by echlebek** [comment]
Oh this is a fun bug. And completely my fault. :)
