### ISSUE TITLE
extraneous shell auto-completion suggestions 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#1568]
## Expected Behavior

Suggestions provided by shell auto-completion should be scoped to the context of the current command

## Current Behavior

Suggestions provided by shell auto-completion include extraneous flags and arguments (e.g. `-f`, `FILE`) 

![2018-05-18 at 1 17 pm](https://user-images.githubusercontent.com/148017/40319305-f034f582-5ce4-11e8-890a-6df77778966c.png)

## Possible Solution

Only suggest valid subcommands when tab-completing from `sensuctl `

## Steps to Reproduce (for bugs)

1. Configure [shell auto-completion](https://docs.sensu.io/sensu-core/2.0/getting-started/configuring-sensuctl/#shell-auto-completion)
2. Type `sensuctl ` and press tab twice 
3. Observe extraneous suggestions (see above screenshot)

## Context

The suggested `-f` and `FILE` flags/arguments are only valid when used in conjunction with subcommands, so this might cause some confusion.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-cli  2.0.0-beta.1~1-2
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04

**Comment by ccressent** [comment]
Still an issue as of 5.14:

```
$ sensuctl
...                   cluster-role-binding  edit                  filter                mutator               tessen
]                     completion            entity                handler               namespace             TYPE]
asset                 config                env                   hook                  [-r]                  TYPE]...
auth                  configure             event                 [KEY]...              [RESOURCE             TYPE],[RESOURCE
check                 create                [-f                   license               role                  URL]
cluster               delete                [[-f                  login                 role-binding          user
cluster-role          dump                  FILE]                 logout                silenced              version
```

**Comment by portertech** [comment]
Still an issue as of 5.19.1:

![Screenshot from 2020-04-15 14-45-16](https://user-images.githubusercontent.com/149630/79392323-14a50580-7f28-11ea-874f-d00a678cd2f6.png)

**Comment by amdprophet** [comment]
The bug came up when testing

**Comment by fguimond** [comment]
Correct, I just validated the problem is still there in sensu-enterprise-go.

**Comment by fguimond** [comment]
Fixed applied to sensu-enterprise-go.
https://github.com/sensu/sensu-enterprise-go/pull/1595
