### ISSUE TITLE
Test RBAC thoroughly with integration and unit tests, delete rbac e2e test

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1599]
RBAC should be thoroughly tested with unit and integration tests. Aim for 100% coverage of RBAC-related code.

Make sure all of the core RBAC libraries are unit tested. Make sure that all of the rbac endpoint methods are integration tested.

Make sure that all resources respect RBAC rules with integration tests.

This will be a difficult and time consuming issue.

**Comment by oferrigni** [comment]
Deferring this till later. Will reopen the issue when we come back to it.
