### ISSUE TITLE
Mock out the time package in unit and integration tests

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1611]
In some of our integration tests, for example, cron tests, we need to wait until a particular time elapses for cron checks to be scheduled.

If we inject time as a dependency, instead of referring to it explicitly, then it can be mocked out, and we can time-travel as desired in order to speed up integration testing of use-cases like this.

Getting integration tests down to sub-second execution levels should improve our velocity for future feature work.

**Comment by echlebek** [comment]
I've realized that we also need to do this wherever we use time in order to have truly reproducible builds.

**Comment by nikkiki** [comment]
This should be done after all other e2e -> integration work has been done.

**Comment by echlebek** [comment]
I think this should have been pointed as a 5. It will likely require API redesign in certain places.

**Comment by echlebek** [comment]
This has been done in a couple places now, and I think we can close this issue. There aren't any major areas of concern left that I could find.
