### ISSUE TITLE
Check TTL should work with round-robin if proxy_entity_id set

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1620]
Check TTL should work when using round-robin subscription(s) and Check proxy_entity_id is set.

## Expected Behavior
As an operator, I should be able to create a Check with a TTL when using a round-robin subscription if I also specify a proxy_entity_id.

## Current Behavior
Check TTL is currently disabled when round-robin is used, see:

https://github.com/sensu/sensu-go/blob/fe473a9ee28b25e106b8004a404f6e3522485ec1/backend/eventd/eventd.go#L208-L212

Requires #1674

**Comment by mercul3s** [comment]
If this ticket requires a lot of refactoring to make ttls work, we should wait and do clustering work before tackling this one.

**Comment by mercul3s** [comment]
After taking a look at eventd and the monitor code and talking through it with Eric,  it looks like it would be pretty complicated to get this working with the current uncoordinated monitor state. We did come up with an idea for how to coordinate the monitors, and we should wait until we have monitor coordination to add this feature.

**Comment by mercul3s** [comment]
Requires #1674

**Comment by echlebek** [comment]
I think I bit off a little more than I was supposed to with this PR. It also closes #1102 and #1103.
