### ISSUE TITLE
Agent authentication is not exposed

### ISSUE THREAD

**Issue by aalkema** [sensu/sensu-go#1621]
Currently agents don't support any auth method with the backend, meaning if we want to make the backend available, anyone in the world could send results in.  To use this, we would require some sort of agent auth.

## Expected Behavior
We want to make the backend available over the internet so agents in all our datacenters can send results in.  Without auth we can't leave the backend open to the world.  We would like agents to require authentication to send results to the backend.

## Current Behavior
The sample agent config currently has a user/pass config available, but it doesn't seem to map to anything on the backend.

## Possible Solution
Add a feature to require agents to authenticate with the backend.

## Your Environment
* sensu-agent version #f70b9f8, build f70b9f8a14ea926e4ce85467beecfe5cf731513d, built 2018-05-08T04:01:02+0000
* sensu-backend version 2.0.0-nightly#44fc6fd, build 44fc6fd582d928ee6474539a498da7529a0a244c, built 2018-05-17T01:02:59+0000
* Multiple datacentres around the world, so agents need to send results over the internet.

**Comment by portertech** [comment]
I was able to verify changing the built-in "agent" user's password causes Agents to receive a 401 (failing to connect to the websocket transport). I did the following steps:

1. Set up a fresh sensu-backend deployment
2. Used sensuctl to change the built-in "agent" user password
    `sensuctl user change-password agent --new-password testtest`
3. Started a sensu-agent without configuring the password (using default)

```
{"component":"cmd","level":"fatal","msg":"handshake failed with status 401","time":"2018-06-13T15:23:02-07:00"}
```

**Comment by portertech** [comment]
Follow-up, running the agent with the new password (`--password testtest`) allows it to connect successfully:

```
./bin/sensu-agent start --subscriptions test --backend-url "ws://127.0.0.1:8081" --log-level debug --password testtest
```

```
{"component":"agent","level":"info","msg":"connected - starting sendPump","time":"2018-06-13T15:44:46-07:00"}
```

**Comment by portertech** [comment]
Another follow-up, I am able to create a separate user with a different password and run an Agent with them:

```
./bin/sensu-agent start --subscriptions test --backend-url "ws://127.0.0.1:8081" --log-level debug --user foobar --password secretpassword
```

```
{"component":"agent","level":"info","msg":"connected - starting sendPump","time":"2018-06-13T15:47:32-07:00"}
```

**Comment by portertech** [comment]
@aalkema I have verified the sensu-backend is capable of providing TLS termination and Agent RBAC user authentication (but not authorization, e.g. access to which Environment?). Are you able to put my test snippets above to use and give it a whirl? Curious to hear how you came to your findings.

**Comment by aalkema** [comment]
Yup - that all works great, I can replicate the 401, then updating the password and have it connect.  Thanks!
