### ISSUE TITLE
Custom Entities created with "sensuctl create -f" do not execute checks they are subscribed to

### ISSUE THREAD

**Issue by bukiadeniji** [sensu/sensu-go#1628]
Custom Entities created with `sensuctl create -f <file_name>` do not appear to subscribe to their subscription topics and do not execute checks with subscriptions they are subscribed to. 

## Expected Behavior
A custom entity with, say, `subscription: foo` should subscribe to the configured subscription topic `foo` and `entity:foo...`; and execute any checks that have the same subscription topic.
```
cat foo_entity.json
{
  "type": "Entity",
  "spec": {
    "id": "foo.nextbestinc.com",
    "class": "proxy",
    "subscriptions": ["foo", "entity:foo.nextbestinc.com"],
    "role": "bar",
    "team":"ops",
    "environment": "default",
    "organization": "default"
  }
}
```

## Current Behavior
The custom entities do not subscribe to their subscription topics and do not execute the checks they are subscribed to. There are no log entries for the subscription or check execution in the logs. Also, there are no events generated or displayed with `sensuctl event list`

However, proxy checks with `proxy_requests` set and `entity_attributes` configured that match the custom entities are executed and events are generated and displayed with `sensuctl event list`
```
snippet of a proxy check:
{
  "command": "check_ssh -4 -p 22 {{ .ID }}",
  ...
  ...
  "name": "check_ssh_proxy",
 
  "subscriptions": [
    "MON"
  ],
  ...
  ...
  "proxy_requests": {
    "entity_attributes": [
      "entity.team == \"ops\""
    ],
  ...
  ...
}
```
This check above matches the custom entity attribute `team: ops`, and executes the check.

## Possible Solution
...

## Steps to Reproduce (for bugs)
1.   Create basic checks. ex use Nagios plugin `check_ssh` , with say `subscription:foo`
2.  Create a custom entity, also with `subscription:foo`
3.  List the events `sensuctl event list`

## Context
I am trying to create custom entities (without agents installed) and have existing checks execute against the entities.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
`sensu-backend version 2.0.0-nightly#82c3128, build 82c31284eb9a378c60869544d95a2cc889a0d686, built 2018-05-23T09:22:02+0000`
`sensu-ctl version 2.0.0-nightly#82c3128, build 82c31284eb9a378c60869544d95a2cc889a0d686, built 2018-05-23T09:23:32+0000`
* Installation method (packages, binaries, docker etc.): **packages**
* Operating System and version (e.g. Ubuntu 14.04): **Centos 7.5.1804**

**Comment by grepory** [comment]
@bukiadeniji It looks like your check definition is lacking a `proxy_entity_id`:

https://docs.sensu.io/sensu-core/2.0/guides/monitor-external-resources/

Specifying a `proxy_entity_id` should associate the resulting events with the entity you created.

If that doesn't work, let us know.

**Comment by bukiadeniji** [comment]
Hi @grepory - thanks for the feedback. 

The issue I am having is more related to understanding if custom entities are expected to behave similar to entities created by agents installed on hosts.

1. Are custom entities expected to subscribe to the topics in their subscription similar to entities created by agent registration?

1. Are custom entities expected to execute checks that match their subscription topics as entities created by agent registration?

Thanks.

**Comment by grepory** [comment]
Custom entities exist purely for proxy check requests. In a proxy check request, the backend searches for agents that match the proxy entity attributes, and then dispatches check execution requests to those agents or publishes the execution requests to all agents subscribing to the subscriptions associated with the proxy check.

Upon receiving them, the agents execute the checks and return events with a proxy entity's id. When the backend receives the checks, it substitutes the custom entity for the proxy entity--so when you list events you would see events "coming from" the proxy entity.

To answer your questions more directly, custom entities don't directly subscribe to or execute checks. Agents execute them on their behalf.

**Comment by bukiadeniji** [comment]
Excellent! Thanks @grepory. You answered my question that custom entities are only for proxy check requests. 

One more thing, is it safe to assume then that the subscription in the custom entities configuration are not being used?

**Comment by bukiadeniji** [comment]
Thanks @calebhailey - yes, that makes complete sense.

The subscription specification is not required or used, and probably, can/should be removed from Custom Entity configuration.

FYI - I tested and was able to successfully create a custom entity without the subscription attribute.

Thanks again!

**Comment by nikkiki** [comment]
Thanks for filing this! We're going to go ahead and close this out!
