### ISSUE TITLE
[Build Stability] TestSendLoop integration failure

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1636]
Appveyor:
```
--- FAIL: TestSendLoop (3.28s)
	assertions.go:239: 
                          
	Error Trace:	agent_test.go:34
		
	            	
			server.go:1947
		
	            	
			server.go:2694
		
	            	
			server.go:1830
		
	            	
			asm_amd64.s:2361
		
	Error:      	Should NOT be empty, but was 
FAIL
FAIL	github.com/sensu/sensu-go/agent	16.798s
ok  	github.com/sensu/sensu-go/agent/assetmanager	0.822s
```

**Comment by nikkiki** [comment]
This might be irrelevant eventually if we are removing amd64..

**Comment by nikkiki** [comment]
https://github.com/golang/go/issues/24701 suggests that `os.Hostname()` can fail prior to go version 1.10.1. Hopefully this will be solved with https://github.com/sensu/sensu-go/issues/1420.

**Comment by nikkiki** [comment]
Looks like updating to 1.10.2 doesn't solve it: https://github.com/sensu/sensu-go/pull/1643.

**Comment by echlebek** [comment]
Hopefully we don't have any plans to remove amd64

**Comment by nikkiki** [comment]
If `os.Hostname()` (invoked in [system.go](https://github.com/sensu/sensu-go/blob/0cc16f11ff7d717ec9f2b266d9b603d1596e0769/system/system.go#L17)) fails to retrieve a hostname on a Windows machine (which for whatever reason has been happening on amd64 appveyor builds) an error is not returned and the hostname remains empty: [host_windows.go](https://github.com/shirou/gopsutil/blob/8dd42707e2221e26bdb87c095aeaab4e7d3a8487/host/host_windows.go#L44-L47). I suggest we create a default hostname, for example `hostname-not-found`, that we assign to the entity's system information `entity.System.Hostname` in the event one cannot be retrieved. Otherwise, we cannot/should not rely on the presence of the hostname: [agent_test.go](https://github.com/sensu/sensu-go/blob/93b4c0d2f98c0bf51cddac77501f2fd095cda948/agent/agent_test.go#L34).

**Comment by nikkiki** [comment]
It's worth noting, we updated the `gopsutil` dependency recently in https://github.com/sensu/sensu-go/commit/822a07a6353a74fcbe35880fea1d469e4bafe1a5. However, the diff doesn't _appear_ like it would cause this.
