### ISSUE TITLE
Segfault in check watcher

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1640]
Looks like the new check watcher has a condition that can segfault under rare circumstances.

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x14a89e9]
goroutine 219 [running]:
github.com/sensu/sensu-go/backend/schedulerd.(*CheckWatcher).handleWatchEvent(0xc420ab1180, 0x0, 0x0)
	/home/travis/gopath/src/github.com/sensu/sensu-go/backend/schedulerd/check_watcher.go:104 +0x89
github.com/sensu/sensu-go/backend/schedulerd.(*CheckWatcher).startWatcher(0xc420ab1180)
	/home/travis/gopath/src/github.com/sensu/sensu-go/backend/schedulerd/check_watcher.go:88 +0xd2
created by github.com/sensu/sensu-go/backend/schedulerd.(*CheckWatcher).Start
	/home/travis/gopath/src/github.com/sensu/sensu-go/backend/schedulerd/check_watcher.go:78 +0x191
FAIL	github.com/sensu/sensu-go/backend/schedulerd	3.323s
```

**Comment by nikkiki** [comment]
I hit this once or twice on unit tests in travis.

**Comment by echlebek** [comment]
I haven't been able to figure out what's going wrong here yet. Haven't given up though. :)

**Comment by nikkiki** [comment]
Gave this a shot for about half a day and have been unable to reproduce in test or live. My only lead or suspicion after trying to investigate this lies at the test level in `TestCheckWatcherSmoke` where we mock `GetCheckConfigWatcher`. https://github.com/sensu/sensu-go/blob/cd23cfd25cd8707d67ae9ef55f212db11f5a127a/backend/schedulerd/check_watcher_test.go#L38-#L39. Many 🐰 🕳 's.

**Comment by echlebek** [comment]
If you look at the stack trace, it shows:

```
github.com/sensu/sensu-go/backend/schedulerd.(*CheckWatcher).handleWatchEvent(0xc420ab1180, 0x0, 0x0)
```

This shows that the `handleWatchEvent` method is receiving a nil parameter.

The first argument (0xc420ab1180) is the pointer to the CheckWatcher, which is the method receiver. It is non-nil since it is not 0x0, and therefore not the cause of the panic.

The next two parameters, 0x0 and 0x0 represent a struct with two fields, but they are both zeroed. The struct is a WatchEventCheckConfig. The fields are a pointer to a CheckConfig and an integer that represents the type of the watch event.

When `handleWatchEvent` tries to access fields of the CheckConfig, it causes a segmentation violation, because the runtime tries to dereference a pointer to 0x0, which is not a valid memory location.

So, the method is receiving a zero-valued WatchEventCheckConfig. But the problem is, I haven't been able to figure out how that's happening.

Now that I look at the code again, it could occur here: https://github.com/sensu/sensu-go/blob/master/backend/schedulerd/check_watcher.go#L87

If the channel was closed, it would start delivering zero-valued results. The question is, why would it get closed?
