### ISSUE TITLE
[GraphQL] Explore subscriptions for realtime updates

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1644]
Introduce subscriptions into the GraphQL endpoint for realtime updates of specified records. See GraphQL [subscriptions RFC](https://github.com/facebook/graphql/blob/master/rfcs/Subscriptions.md).

- Websockets? Long-polling?
- How do we pool connections?
- Do we use an etcd watcher for updates? Or rely on the pipeline?
- Do we track changes on a field level?

Blocks #1300

**Comment by palourde** [comment]
@jamesdphillips Do we still want/need this?
