### ISSUE TITLE
Unable to delete RBAC Organization

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1645]
I am unable to delete an RBAC Organization, "acme", even after deleting every RBAC Environment within. Please see:

<img width="979" alt="screen shot 2018-06-04 at 4 05 32 pm" src="https://user-images.githubusercontent.com/149630/40946223-3a4e90ec-6811-11e8-8c1c-dc15931387cb.png">

**Comment by portertech** [comment]
NVM, I just caught my issue. PEBKAC!

**Comment by echlebek** [comment]
:lollipop:
