### ISSUE TITLE
Cannot execute a check even though I can query it

### ISSUE THREAD

**Issue by wari** [sensu/sensu-go#1646]
Given the following:

```
$ sensuctl check info uptime --environment office --organization wari.org
=== uptime
Name:            uptime
Interval:        60
Command:         uptime
Cron:
Timeout:         0
TTL:             0
Subscriptions:   linux, darwin
Handlers:
Runtime Assets:
Hooks:
Publish?:        true
Stdin?:          false
Proxy Entity ID:
Organization:    wari.org
Environment:     office
Metric Format:
Metric Handlers:
```

I cannot seem to execute the check

```
sensuctl check execute uptime --environment office --organization wari.org --reason raisins
Error: not found
```

Logs:

```
{"component":"apid","duration":"2.690ms","level":"info","method":"POST","msg":"request completed","path":"/checks/uptime/execute","size":30,"status":404,
"time":"2018-06-05T01:11:07Z"}
```

## Expected Behavior

Should be able to work, like the old sensu

## Current Behavior

Error: Not found

## Steps to Reproduce (for bugs)
1. Not sure if necessary, do not use default org and environment
2. sensuctl check create uptime --command uptime --subscriptions baz --organization foo --environment bar
3. Run the check like above

## Context

We are supposed to be able to execute a check either to ensure systems are working or to test if everything is still broken

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): master
* Installation method (packages, binaries, docker etc.): ./build.sh build
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

**Comment by jamesdphillips** [comment]
From a quick investigation:

- The CLI's client doesn't set the org and env query params when the request is [POST, PUT, or PATH](https://github.com/sensu/sensu-go/blob/master/cli/client/client.go#L45-L56). The adhoc endpoint is `POST /checks/{name}/execute`.
- The controller appears to expect that the context [has already been populated](https://github.com/sensu/sensu-go/blob/master/backend/apid/actions/checks.go#L314-L317). Presumably by the query params. 
- `AdhocRequest` record does not have [organization or environment fields](https://github.com/sensu/sensu-go/blob/master/types/adhoc.proto#L15-L27) and as such the end-user cannot specify the environment this way either.

Either the the CLI command needs to make an exception and sets the env & org query params /or/ maybe even better add `Organization` and `Environment` fields to the adhoc request type and have them populated by the command.

**Comment by oferrigni** [comment]
Add query parameters to the CLI request.
