### ISSUE TITLE
sensuctl create -f does not support users

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1663]
## Expected Behavior

I'd expect to be able to create and update users through `sensuctl create -f` like all other resources.

## Current Behavior

```
error parsing spec: "User" is not a Resource
Error: some resources couldn't be parsed
```

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat /tmp/user.json
{
  "type": "User",
  "spec":
  {
    "username": "agent",
    "roles": [
      "agent",
      "read-only"
    ],
    "disabled": false
  }
}

[root@sensu-backend ~]# sensuctl create -f /tmp/user.json
error parsing spec: "User" is not a Resource
Error: some resources couldn't be parsed
```

## Context

I am working with @ghoneycutt on Puppet automation and rely on `sensuctl create -f` to manage resource creation and updates.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version 2.0.0-nightly#874ca71, build 874ca71efd38125e7c172b90d15a698cd249721d, built 2018-06-09T09:21:14+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by treydock** [comment]
I don't know if this warrants separate issue but for automation having to know previous/current password in order to change the password may be problematic.  I was envisioning being able to send JSON as admin to `sensuctl create -f` that updates password for admin then run `sensuctl configure` to re-configure sensuctl.

Basically use this pattern where `user.json` contains the new admin password.

```
sensuctl configure -n --url http://localhost:8080 --username admin --password 'P@ssw0rd!'
sensuctl create -f /tmp/user.json
sensuctl configure -n --url http://localhost:8080 --username admin --pasword '<new password>'
```

This pattern would allow for the last 2 commands to be re-run in the event of admin password change and first command would only be run during first run of automation tools.

**Comment by benbailess** [comment]
This feature would be very attractive indeed, since it would allow a declarative definition of users and groups. Is there any intent to support `User` as a valid resource type for `sensuctl create -f`?

**Comment by palourde** [comment]
For reference, users can now be created using `sensuctl create`!
