### ISSUE TITLE
Automate deployment to the staging environment

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1672]
In AWS, there exists 4 instances (1 backend, 3 agents) as part of the manual sensu-staging environment. Using one of the many tools available (chef, puppet, aws code deploy etc.), we should automate the deployment process for a staging environment for each release (nightly, minor, major?).

Requires https://github.com/sensu/sensu-staging/issues/12

**Comment by mercul3s** [comment]
We should take advantage of community config management cookbooks/playbooks/etc depending on what tool we go with. Drinking our own 🍾!

**Comment by oferrigni** [comment]
Break out smaller tickets as a result of this ticket.

**Comment by nikkiki** [comment]
@oferrigni did some awesome terraform work in https://github.com/sensu/sensu-staging to automate the single backend staging environment.. and @mercul3s on the clustered backends!

We'll probably want to do a few more things in sensu-go:
- remove staging templates and resources from testing/config
- configure aws iam role for staging
- trigger terraform in our nightly deploys

**Comment by nikkiki** [comment]
Prioritizing this to the top of the backlog.

**Comment by oferrigni** [comment]
Please remove any data duplicated with sensu-staging?

**Comment by nikkiki** [comment]
Let's wait to remove the resources and configurations in sensu-go until we verify the staging resources have properly been ported over!
