### ISSUE TITLE
Replace monitor.go with a leased key and watcher

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1674]
The current [monitor](https://github.com/sensu/sensu-go/blob/master/backend/monitor/monitor.go) is incompatible with a clustered sensu backend as the monitors are implemented in an in-memory map. We should instead use a key in etcd with a lease for each monitor, and a watcher for that key's expiration/deletion. We'll need to update the monitor implementation (replace the in-memory map) in keepalived and eventd once this work is done.

**Comment by grepory** [comment]
While we are at it, can we make this work with clustered backends?

**Comment by mercul3s** [comment]
@grepory that's the intent!
