### ISSUE TITLE
Allow multiple silenced entries for a subscription + check pair

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1675]
Allow multiple silenced entries for a subscription and check pair.

## Expected Behavior

As a user, I can create a silenced entry for a particular subscription and check pair, to silence events during a future maintenance window. Before that maintenance window, I can create a silenced entry for the same subscription and check pair to immediately silence events (incident response) without destroying/updating the silenced entry for the maintenance window.

## Current Behavior

There can only be one silenced entry for a subscription and check pair.

## Possible Solution

Add "uniqueness" to the silenced entry generated IDs. It's important to note that anything added to the generated IDs will be included in Event data, Check `"silenced_by"`.

## Context

This issue arose while discussing UI silencing UX. There have been cases where users have expressed frustration, however, we need to find the evidence (issues, docs, tickets).

**Comment by portertech** [comment]
Important note: it's currently possible to have overlapping silenced entries for an event, the entries may just apply to different relevant subscriptions.

**Comment by oferrigni** [comment]
Who owns building the case for this feature (finding issues, docs, tickets)?

**Comment by obfuscurity** [comment]
This appears to be the backend-specific bits, correct? @portertech LMK if you need me to hash out the user story, etc., but I think you currently have a much more focused notion of what this will look like than I do.

**Comment by oferrigni** [comment]
Please write up a proposal for the user experience before starting work. Add size once proposal is reviewed and roughly agreed upon.

**Comment by echlebek** [comment]
We won't be able to do this until we release the v3 API.
