### ISSUE TITLE
Subdued check does not get subdued

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1676]
Check subdue feature is not behaving as expected.

## Expected Behavior
Check does not get scheduled or executed.

## Current Behavior
Check gets scheduled and executed.

## Possible Solution
Investigate time conversions and subdue logic in check scheduler.

## Steps to Reproduce (for bugs)
1. `sensu-backend`
2. Create a check `subdued-check` with the configuration below. The time window is intended to subdue the check always: `sensuctl create -f`
```
{
  "type": "CheckConfig",
  "spec": {
    "command": "echo subdued",
    "environment": "default",
    "handlers": [],
    "high_flap_threshold": 0,
    "interval": 10,
    "low_flap_threshold": 0,
    "name": "subdued-check",
    "organization": "default",
    "publish": true,
    "runtime_assets": [],
    "subscriptions": [
      "misc"
    ],
    "proxy_entity_id": "",
    "check_hooks": null,
    "stdin": false,
    "subdue": {
      "days": {
        "all": [
          {
            "begin": "12:00AM",
            "end": "11:59PM"
          },
          {
            "begin": "11:00PM",
            "end": "1:00AM"
          }
        ]
      }
    },
    "ttl": 0,
    "timeout": 0,
    "round_robin": false,
    "output_metric_format": "",
    "output_metric_handlers": []
  }
}
```
3. `sensu-agent --subscriptions misc`
4. `sensuctl event list` shows `subdued-check` has been executed

## Context
Cannot subdue checks.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/56f7dddd464a02b4b77ddd2f41747fbb7fa33fa1
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS High Sierra 10.13.5

**Comment by palourde** [comment]
@nikkiki I couldn't reproduce this issue, currently running master (https://github.com/sensu/sensu-go/commit/05fe442645e7d34eed5e1e00e9cde99bc244df8c)

```
{"component":"schedulerd","env":"default","level":"debug","msg":"check is subdued","name":"subdued-check","org":"default","time":"2018-06-21T15:20:57-04:00"}
```

Also, the subdue timezones seem to have been properly created:

```
$ sensuctl check info subdued-check --format json
{
  [...]
  "name": "subdued-check",
  [...]
  "subdue": {
    "days": {
      "all": [
        {
          "begin": "12:00AM",
          "end": "11:59PM"
        },
        {
          "begin": "11:00PM",
          "end": "1:00AM"
        }
      ]
    }
  },
[...]
```

Could you try to see if you are able to reproduce the described behaviour? If so, let's pair on that!

**Comment by nikkiki** [comment]
@palourde Hm, I wonder if there was something just off on my local env. The staging environment shows no event for `subdued-check` with the same configuration!
```
sensuctl event info staging-agent-0 subdued-check
Error: not found
```
I'll go ahead and close this out.. thanks for looking into it!
