### ISSUE TITLE
Cluster Epic

### ISSUE THREAD

**Issue by oferrigni** [sensu/sensu-go#1689]
Parent of #1214
Parent of #1102
Parent of #1103
Parent of #1674
Parent of #1716
Parent of #1717
Parent of #1718
Parent of #1719
Parent of #1720
Parent of #1721
Parent of #1722
Parent of #1723
Parent of #1724
Parent of #1620
Parent of #1878
Parent of https://github.com/sensu/sensu-enterprise-go/issues/73

**Comment by oferrigni** [comment]
For any added tickets, please make sure to go through a grooming process first.

**Comment by echlebek** [comment]
Parent of #1397
Parent of #1214
Parent of #1102
Parent of #1103
Parent of #540
Parent of #413
Parent of #1674
