### ISSUE TITLE
Support specifying password hash directly in user json

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1697]
## Expected Behavior

In order to support creation of users through `sensuctl create -f` (see #1663), we need the ability to specify a user's password as a hash to avoid storing passwords in plaintext.

## Current Behavior
Sensuctl's interactive user creation passes the plaintext password in a TLS encrypted tunnel to the sensu backend where the password is hashed. We should keep this functionality for interactive user creation.

## Possible Solution
_Only_ allow the password to be specified via hash in user json. `sensuctl` should provide functionality to produce a hash from the given password so that users can manually create user json files.

## Context
Required by #1663, which deals with creating users via config management.

**Comment by ghoneycutt** [comment]
We would need sensuctl to be able to create a hash so we do not have to implement bcrypt. The bcrypt library for ruby needs gcc and forcing a compiler to be on all agents will harm adoption. We also want it to be simple for other config management software and automation tools so they do not also have bundle in bcrypt.

Perhaps something like

`sensuctl bcrypt foo`

which would return the following to STDOUT.

`$2a$04$hcu1uRCWZVF4n6OZSTTP1OqE5a/idwP49eR91IBR6/D8jpXkGeYBG`


This would allow automation tools to do a simple string comparison to see if the hash they have is equivalent to the hash returned by sensuctl. It would also allow them to take passwords as input and transform them to the bcrypt hash and use that with sensuctl to manipulate user settings.

**Comment by ghoneycutt** [comment]
CC @treydock

**Comment by annaplotkin** [comment]
- Need to update API to allow you to submit a hash for a user
- Need to update API to determine whether a submission resulted in a modification or not [modifying a user resource]
- Provide a bcrypt util in sensuctl
