### ISSUE TITLE
Remove e2e tests from build scripts and CI

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1702]
Once all e2e tests have been removed from testing/e2e, we should remove references to them in our build scripts and CI config. This includes the `testing/e2e` directory, `main_test.go`, `process_test.go`, and `doc.go`.

Requires #1588 
Requires #1594 
Requires #1591 
Requires #1592 
Requires #1587 
Requires #1595 
Requires #1593 
Requires #1589 
Requires #1600 
Requires #1598
Requires #1590
Requires #1599

**Comment by oferrigni** [comment]
Revisit when we reopen rbac.
