### ISSUE TITLE
Option to list events by entity

### ISSUE THREAD

**Issue by bukiadeniji** [sensu/sensu-go#1703]
We have a use case where we are rolling out Sensu agents to 500+ servers. We would like the ability to be able to list events for a specific entity, instead of the entire list of events in the system.

## Expected Behavior
We can run a command like `sensuctl entity list foo.example.com` and get the events for the entity `foo.example.com`.

## Current Behavior
Not yet available

## Possible Solution
Add option that accepts  `host ID` to list the events for.

## Steps to Reproduce (for bugs)
N/A

## Context
For our use case, running `sensuctl event list` will display a couple of thousand events. We would like to be able to specify a specific entity to list the events for.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): ```sensu-backend version
sensu-backend version 2.0.0-nightly#8a73065, build 8a73065eee1e385122b67835327e59bfcd578fe7, built 2018-06-18T09:20:46+0000```
* Installation method (packages, binaries, docker etc.): `packages`
* Operating System and version (e.g. Ubuntu 14.04): `Centos 7`

**Comment by echlebek** [comment]
It's possible we need to discuss a more general way of dealing with the events API, since events can be extremely numerous.

**Comment by agm650** [comment]
It may not be exactly related, but a general way to filter the output of the command would be nice. 
It would even be better if it was possible to do the same in the API

**Comment by palourde** [comment]
For reference, filtering is now part of Sensu Enterprise: https://docs.sensu.io/sensu-go/5.8/api/overview/#filtering. Otherwise, it's always possible to use something like `jq` in conjunction with [API pagination](https://docs.sensu.io/sensu-go/5.8/api/overview/#pagination) to filter JSON formatted results!
