### ISSUE TITLE
Investigate the etcd alarms API

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1724]
Etcd provides an alarms API. It is basically undocumented. Find out what it does, and figure out if we can use it to provide some information to the sensu backend.

**Comment by mercul3s** [comment]
@cyphus I summarized a couple bullet points from our earlier conversation and the research I did - feel free to add comments if you've got 'em.

**Comment by cyphus** [comment]
I think that the presence of any alarms is valuable info in the sensuctl health response, and that dead man's switch would make a great catch-all for any unexpected error we encounter. @mercul3s if you're happy with the level you've investigated etcd alarms, I'd suggest closing this and making issues for what you want to see implemented.

**Comment by mercul3s** [comment]
@cyphus I've added #1978 and #1979 for these enhancements.
