### ISSUE TITLE
Collect+publish CircleCI artifacts

### ISSUE THREAD

**Issue by preed** [sensu/sensu-go#1730]
We need to collect and publish the artifacts CircleCI produces, so that we can store them off (as necessary) and also allow access to them even if you don't have CircleCI access.

Per a conversation this week with @amdprophet and @echlebek, we will likely use S3 as the datastore for this. We will then consume those artifacts into package repositories or other infrastructure, as necessary.

**Comment by amdprophet** [comment]
1. :+1: I'll hook you up with some credentials tomorrow.
2. If encrypting the data is easy, we can store the credentials in 1password.
3. I think we can probably ƒree up the sensu-build repo name by renaming it to something else.
4. 👍 
5. 👍

**Comment by preed** [comment]
re: number 2, 1password would be great; re: number 3, I don't have a _huge_ preference either way, but perhaps sensu-release _would_ actually be a good name, given that we want all build stuff to really go with the code (I mean... you should still be able to build it, right? ;-) and the repo really will be for software-release related stuff, which only-we have use for?
