### ISSUE TITLE
Support changing of log level during runtime

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1742]
Add the ability to change the log level for the agent & backend during runtime. This can be very useful for debugging the daemons when they're in a bad state or an unexpected condition is occurring.

## Expected Behavior
As a user I should be able to either toggle debug logging or set a specific log level for an already running daemon.

## Current Behavior
Changing the log level requires a restart of the daemon.

## Possible Solution
Sensu Enterprise (1.x) supports toggling debug mode by sending `kill -TRAP` to the pid of the daemon. In my personal opinion, it would be nice to have a more versatile approach that allows us to set a specific log level rather than just toggling debug logging.

## Steps to Reproduce (for bugs)
N/A

## Context
During preparation for a release, we noticed that keepalives were not functioning as expected. The daemons were not running with the debug log level and we were worried that restarting the daemon would resolve the issue (temporarily).

## Your Environment
N/A

**Comment by palourde** [comment]
For reference, logrus log level can be modified at runtime: https://github.com/sirupsen/logrus/issues/425.

**Comment by annaplotkin** [comment]
We would like to do what Classic does which when the process is restarted, the log level goes back to the original configuration.
