### ISSUE TITLE
Add keepalived status to backend status func

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1744]
Keepalived status information isn't represented here:
https://github.com/sensu/sensu-go/blob/6996d8ccb36ba9a9b6750da016ce3b5ea118bcfd/backend/backend.go#L386-L395

**Comment by palourde** [comment]
Statuses were deprecated: https://github.com/sensu/sensu-go/commit/6661f64756b0d42ffe02e15e9d33e35d4a41b300
