### ISSUE TITLE
Add logging to pipelined filters

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1745]
Add logging to `pipelined/filters.go` so that we know when filters, silencing, etc. are accepting / rejecting an event.

## Expected Behavior
Log messages for filtering.

## Current Behavior
No log messages.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
N/A

**Comment by annaplotkin** [comment]
We only do one permutation currently. We could do 4.
