### ISSUE TITLE
Extensions can cause the backend to lock up

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#1750]
The use of extensions and extension handlers can sometimes cause the backend to lock up. No new events will be written.

## Expected Behavior
Extensions and extension handlers work properly. The [example gRPC server](https://github.com/sensu/sensu-go/blob/master/rpc/extension/example/main.go) filters and logs the checks defined in [resources.json](https://github.com/sensu/sensu-go/blob/master/testing/config/resources.json).

## Current Behavior
After ~1hr, events and keepalives stop registering with the backend (although they are still being sent from the agents): [dump.txt](https://github.com/sensu/sensu-go/files/2141970/dump.txt). The extension appears to hang and no longer logs the expected messages.

## Possible Solution
Investigate the attached profile.

## Steps to Reproduce (for bugs)
See "2.x Manual Staging Environment" under "Extensions" with [example gRPC server](https://github.com/sensu/sensu-go/blob/master/rpc/extension/example/main.go) and resources in https://github.com/sensu/sensu-go/pull/1735.

## Context
The system locks up and there are no failing events to indicate such behavior.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6996d8ccb36ba9a9b6750da016ce3b5ea118bcfd
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): ubuntu-xenial-16.04-amd64

**Comment by oferrigni** [comment]
Remediation: disable extensions in the api until we can come back to fully implement.

**Comment by nikkiki** [comment]
Will be addressed in https://github.com/sensu/sensu-go/issues/1893 and https://github.com/sensu/sensu-go/pull/1892
