### ISSUE TITLE
Suggest changing README.md to point to instructions on the Docs site

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#1751]
It seems that the Docs site has much more in terms of options for installing and configuring 2.0 and referring users to the docs site would be better for us.

**Comment by grepory** [comment]
Redirecting people to the docs site toward the top of the readme could work, and then instead of installation instructions we could have a like... getting started developing sensu thing?

**Comment by grepory** [comment]
We actually do this now.
