### ISSUE TITLE
Example agent.yml is misleading for changing agent ID

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1764]
## Expected Behavior

I'd expect example `agent.yml` to have valid keys, like the one used to change entity ID.

## Current Behavior

Currently the example uses the key `agent-id`.

## Possible Solution

Update example `agent.yml` to use `id` and not `agent-id`.

## Steps to Reproduce (for bugs)

1. Install fresh agent and backend
2. Configure example `agent.yml` with `agent-id: "test"` and restart agent
3. The entity still uses hostname for entity ID
4. Change `agent.yml` to use `id: "test"` , restart , success

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): Latest nightly
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL6 and EL7

**Comment by treydock** [comment]
CC @ghoneycutt

**Comment by nikkiki** [comment]
Hey @treydock thanks for filing this issue! Could you attach the SHA of the latest nightly where you encountered this problem? I believe this issue _may_ have already been addressed.

**Comment by treydock** [comment]
@nikkiki  `sensu-agent version 2.0.0-nightly#874ca71, build 874ca71efd38125e7c172b90d15a698cd249721d, built 2018-06-09T09:20:54+0000`

I just updated to latest nightly and example is correct, closing this issue, thanks.
