### ISSUE TITLE
Rework check occurrences

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1766]
A recent issue (https://github.com/sensu/sensu-go/issues/1624) brought to light the fact that check occurrences have some deficiences, and surprising characteristics.

@portertech, @palourde and I took some time to describe the differences between 1.x and 2.x occurrences as currently implemented, user stories around occurrences, and how we need to change occurrences to address those stories.

In short:
* increment occurrences for all statuses, including passing statuses
* remove OccurrencesWatermark and add IncidentOccurrencesWatermark, or something equivalently named.

Design and background information is here: https://docs.google.com/document/d/1jc90QCxqjekscjrRe3rwJZKJJGH5xxRdLbGJQNoKxFU/edit?usp=sharing

edit: We may not wish to remove OccurrencesWatermark, as it would break compatibility for anyone relying on this value.

**Comment by cimere** [comment]
Any chance this will be implemented soon?

thanks!

**Comment by portertech** [comment]
Newly proposed behaviour:

1. Occurrences should always be incremented if the current Check status is the same as the previous status (this includes events with the Check status of OK)
2. Occurrences should always reset to 1 if the current Check status is different than the previous status
3. OccurrencesWatermark only resets on the a first non OK Check status (it does not get reset going between warning, critical, unknown)

Scenario:
1. Event with OK Check status - Occurrences: 1, OccurrencesWatermark: 1
2. Event with OK Check status - Occurrences: 2, OccurrencesWatermark: 2
3. Event with WARN Check status - Occurrences: 1, OccurrencesWatermark: 1
4. Event with WARN Check status - Occurrences: 2, OccurrencesWatermark: 2
5. Event with WARN Check status - Occurrences: 3, OccurrencesWatermark: 3
6. Event with CRIT Check status - Occurrences: 1, OccurrencesWatermark: 3
7. Event with CRIT Check status - Occurrences: 2, OccurrencesWatermark: 3
8. Event with CRIT Check status - Occurrences: 3, OccurrencesWatermark: 3
9. Event with CRIT Check status - Occurrences: 4, OccurrencesWatermark: 4
10. Event with OK Check status - Occurrences: 1, OccurrencesWatermark: 4
11. Event with CRIT Check status - Occurrences: 1, OccurrencesWatermark: 1

**Comment by portertech** [comment]
The Sensu-Plugin documentation around "occurrences" and "refresh" may help shed some light on the associated filtering logic. https://docs.sensu.io/plugins/1.0/reference/#check-definition-attributes

**Comment by nikkiki** [comment]
![giphy](https://user-images.githubusercontent.com/10634078/57548039-da44e880-7314-11e9-90b7-445737508655.gif)
