### ISSUE TITLE
Add `sensuctl hashpass` command

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1768]
Add a command sensuctl that hashes passwords the same way the backend does, so that users can hash passwords instead of sending plaintext passwords over the wire.

Make sure that the method is exactly the same as what the backend does (currently bcrypt).

See #1437 for background.

Requires #1697.

The command can work entirely locally if we accept the premise that encryption algorithms and parameters will not be configurable. Otherwise, it will need to coordinate with the backend to discover the configuration.

Acceptance criteria:

- [ ] `sensuctl hashpass $PASSWD` will output a password hash when called.
- [ ] After a user is created with the hashed password generated by `sensuctl hashpass`, authentication for that user succeeds when the password is provided.

**Comment by ghoneycutt** [comment]
CC @treydock @ghoneycutt

**Comment by annaplotkin** [comment]
Related to #1697
