### ISSUE TITLE
Unit tests on CircleCI failing: agent/check_handler_internal_test.go

### ISSUE THREAD

**Issue by preed** [sensu/sensu-go#1783]
While landing #1782, I noticed that unit tests on CircleCI seem to be failing, and have been for awhile:

Successful: https://circleci.com/gh/sensu/sensu-go/275
Failed: https://circleci.com/gh/sensu/sensu-go/281
Failed: https://circleci.com/gh/sensu/sensu-go/283
Failed: https://circleci.com/gh/sensu/sensu-go/285
Failed: https://circleci.com/gh/sensu/sensu-go/299
Failed: https://circleci.com/gh/sensu/sensu-go/315

## Expected Behavior

Unit tests should pass. :smiley:

Interestingly, #1782 split out the build and unit tests, and the unit tests failure after the split are different than the previous 4. So this very well could be a CircleCI environment issue? If so, I'm happy to help debug the environmental issue side of it if we can define what's lacking in the environment (or what's required).

## Current Behavior

From https://circleci.com/gh/sensu/sensu-go/315:

```
-- FAIL: TestExecuteCheck (0.47s)
	Error Trace:	check_handler_internal_test.go:74
	Error:      	Not equal: 
	            	expected: int32(0)
	            	actual: uint32(0x7f)
	Error Trace:	check_handler_internal_test.go:87
	Error:      	Not equal: 
	            	expected: int32(1)
	            	actual: uint32(0x7f)
	Error Trace:	check_handler_internal_test.go:101
	Error:      	Not equal: 
	            	expected: int32(2)
	            	actual: uint32(0x7f)
	Error Trace:	check_handler_internal_test.go:134
	Error:      	Not equal: 
	            	expected: 2
	            	actual: 0
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 99 [running]:
testing.tRunner.func1(0xc42032e870)
	/usr/local/go/src/testing/testing.go:742 +0x567
panic(0xec4c80, 0x14af1b0)
	/usr/local/go/src/runtime/panic.go:502 +0x24a
github.com/sensu/sensu-go/agent.TestExecuteCheck(0xc42032e870)
	/go/src/github.com/sensu/sensu-go/agent/check_handler_internal_test.go:135 +0x1bae
testing.tRunner(0xc42032e870, 0xfd0c38)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
FAIL	github.com/sensu/sensu-go/agent	1.919s
```

**Comment by grepory** [comment]
Going to replace this issue with #1797.
