### ISSUE TITLE
Replace sensuctl "json" format value with "wrapped-json"

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1786]
## Expected Behavior

The `json` format used in sensuctl should be compatible with `sensuctl create`.

## Current Behavior

Users will instinctively use the `json` format with sensuctl and then try to use `sensuctl create` with the resulting JSON, which is incompatible. 

## Possible Solution

We should probably rename the `wrapped-json` format as `json` and if required, create something like `unwrapped-json` instead for the current `json` format.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by treydock** [comment]
Currently the wrapped-json output isn't something that can be loaded directly by JSON libraries (#1817).

Personally the current json format seems more logical as it's valid json and can be parsed by json libraries, my $0.02.

Can current wrapped-json from list commands be passed directly into `sensuctl create`?

**Comment by palourde** [comment]
@treydock Yes, output from wrapped-json can be passed directly into `sensuctl create`.
