### ISSUE TITLE
sensuctl check list should be able to list only configurable attributes

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1788]
## Expected Behavior

I'd expect a way to query checks via sensuctl and only get attributes in JSON that can be configured.

## Current Behavior

Currently numerous read-only attributes are returned by `sensuctl check list --format json`.

## Possible Solution

Add an option to `sensuctl check list` that filters out read-only attributes and only lists those that can be configured.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# sensuctl create -f /root/check.json
[root@sensu-backend ~]# cat /root/check.json
{
  "type": "Check",
  "spec": {
    "foo": "bar",
    "name": "test",
    "command": "check-http.rb",
    "subscriptions": [
      "demo"
    ],
    "handlers": [
      "email"
    ],
    "interval": 60,
    "organization": "default",
    "environment": "default"
  }
}
[root@sensu-backend ~]# sensuctl check list --format json
[
  {
    "check_hooks": null,
    "command": "check-http.rb",
    "env_vars": null,
    "environment": "default",
    "handlers": [
      "email"
    ],
    "high_flap_threshold": 0,
    "interval": 60,
    "low_flap_threshold": 0,
    "name": "test",
    "organization": "default",
    "output_metric_format": "",
    "output_metric_handlers": null,
    "proxy_entity_id": "",
    "publish": false,
    "round_robin": false,
    "runtime_assets": null,
    "stdin": false,
    "subdue": null,
    "subscriptions": [
      "demo"
    ],
    "timeout": 0,
    "ttl": 0,
    "duration": 0,
    "executed": 0,
    "foo": "bar",
    "history": null,
    "issued": 0,
    "last_ok": 0,
    "occurrences": 0,
    "occurrences_watermark": 0,
    "status": 0,
    "total_state-change": 0
  }
]
```

## Context

I am working with @ghoneycutt to automate with Puppet and in order to supported extended_attributes for checks we have to map every key returned by `sensuctl check list` to either a Puppet resource property, ignore or assign to extended_attributes.  Currently we have to ignore read-only properties which makes the Puppet code very fragile to breakage as sensu-go evolves.

https://github.com/sensu/sensu-puppet/blob/sensu2/lib/puppet/provider/sensu_check/sensuctl.rb#L8-L13

It's worth noting the output I get from `sensuctl check list` is different when I create a check with `sensuctl check create`.  This is mentioned in #1443

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version 2.0.0-nightly#2b06350, build 2b0635068aef4f9e4c6fef5739b522718fd573ac, built 2018-06-30T09:20:32+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by treydock** [comment]
CC @portertech

**Comment by grepory** [comment]
With the deprecation of extended attributes this is no longer an issue.
