### ISSUE TITLE
Amazon 2.0 should use systemd unit files for services

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1791]
## Expected Behavior

I'd expect Amazon 2.0 install to use systemd unit files.

## Current Behavior

Currently repo bootstrap script will install the EL6 repo which doesn't use systemd for services.

## Possible Solution

The packagecloud boostrap script should probably look at something like /etc/os-release for detection of Amazon and if 2.0 should set dist to 7 not 6.  I also worked around issue by installing `systemd-sysv` which allows the sysVinit scripts to be launched via systemd.

## Steps to Reproduce (for bugs)

1. `curl -s https://packagecloud.io/install/repositories/sensu/nightly/script.rpm.sh | bash`
2. `yum install sensu-backend`
3. 
```
systemctl start sensu-backend
Failed to start sensu-backend.service: Unit not found.
```

## Context

Was adding support to sensu-puppet for Amazon Linux and noticed Amazon Linux 2.0 now supports systemd.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): latest nightly
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): Amazon Linux 2.0

**Comment by treydock** [comment]
One solution I use in sensu-puppet is sourcing `/etc/os-release` and checking if `$VERSION` is `2`.  If someone points me at git location of package cloud bootstrap script I'd be happy to patch.

**Comment by grepory** [comment]
Our packages will include both systemd and sysv-init startup scripts.

**Comment by treydock** [comment]
@grepory Just for my own curiosity and to dig should become necessary, where does spec for RPMs live and where does the script used by packagecloud to bootstrap sensu come from?  Thanks.

**Comment by grepory** [comment]
@treydock we have moved all of our build and release stuff into a private repo to make it easier to manage, since it's all building from closed source and includes a number of secrets for packagecloud, aws, etc.
