### ISSUE TITLE
wrapped-json format is not valid JSON

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1817]
## Expected Behavior

I'd expect to be able to parse JSON from `wrapped-json` format.

## Current Behavior

Currently the `json` format produces an array of hashes while `wrapped-json` just provides hashes in a way that isn't valid json.

## Possible Solution

Have `wrapped-json` output elements in an array or some format that is valid JSON.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# sensuctl environment list --format json
[
  {
    "description": "Default environment",
    "name": "default",
    "organization": "default"
  },
  {
    "description": "",
    "name": "test",
    "organization": "default"
  }
]

[root@sensu-backend ~]# sensuctl environment list --format json | python -m json.tool
[
    {
        "description": "Default environment",
        "name": "default",
        "organization": "default"
    },
    {
        "description": "",
        "name": "test",
        "organization": "default"
    }
]
[root@sensu-backend ~]# sensuctl environment list --format wrapped-json
{
  "type": "Environment",
  "spec": {
    "description": "Default environment",
    "name": "default",
    "organization": "default"
  }
}
{
  "type": "Environment",
  "spec": {
    "description": "",
    "name": "test",
    "organization": "default"
  }
}
[root@sensu-backend ~]# sensuctl environment list --format wrapped-json | python -m json.tool
Extra data: line 9 column 1 - line 17 column 1 (char 140 - 258)
```

## Context

This isn't impacting anything I'm working on, just an observation I've made while testing sensu-go.  I am working to automate with Puppet and only rely on `--format json` but I do add resources using the `wrapped-json` format through `sensuctl create -f` but the json passed to `sensuctl create -f` is generated by Puppet code.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-ctl version 2.0.0-nightly#5b5d7b2, build 5b5d7b240ad24c7a3fd6676c8578f52643c82813, built 2018-07-10T09:22:46+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by nikkiki** [comment]
Hey @treydock, thanks for filing this issue! I can definitely understand it being frustrating not being able to use the `wrapped-json` output in your python tool. This change, although fairly simple, would be a breaking change to users that are dependent on the `wrapped-json` format as is. Before we move forward to schedule this, we'll have to wait for some more user feedback regarding the feature, so we can better gauge its impact.

**Comment by calebhailey** [comment]
@treydock Is this still a valid issue?

**Comment by treydock** [comment]
I am going to close. As long as things support `--format json` or `--format yaml` there is no need for me to have wrapped-json behavior changed.
