### ISSUE TITLE
Asset runtime not loaded - ruby check failed

### ISSUE THREAD

**Issue by robertcoder18** [sensu/sensu-go#1830]
I have a check in Sensu 2.0 (nightly build running in Docker) - the check's command executes a ruby script. A runtime asset is supplied in the check definition - that asset defines a url to fetch the ruby tar. 

## Expected Behavior

The check command should be able to execute the ruby script successfully after fetching the ruby tar described in the check's runtime asset. 

## Current Behavior

Check execution results in the following output: "env: can't execute 'ruby': No such file or directory"

## Possible Solution

Provide logs to indicate success or failure when fetching the tar for runtime assets (does Sensu already do this?) as well as logs to indicate success or failure for setting up runtime environments/dependencies that allow the check to execute. This would help debug the issue. 

## Steps to Reproduce (for bugs)

1. Create an asset and set the url as "https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.1.tar.gz" using the directions from here: https://docs.sensu.io/sensu-core/2.0/guides/install-check-executables-with-assets/
2. Create a check that executes a ruby script on some agent (be sure an agent subscribes to the check) and supply the check with the runtime asset created above. 
3. Wait for check to execute and see output in Sensu dashboard or logs

## Context

All of my checks are ruby scripts so simply looking for the correct way to get ruby into my Docker container running the Sensu agent so that the checks can execute. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensuctl: sensu-ctl version 2.0.0-nightly#7cb4b9d, build 7cb4b9da29522b7e54d18ea219d5ed8159320ea5, built 2018-07-08T09:19:34+0000, using sensuapp/sensu-go:2.0.0-nightly-nightly
* Installation method (packages, binaries, docker etc.): Docker 

* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04

**Comment by echlebek** [comment]
Hi @robertcoder18,

The tarball you posted is the source code for Ruby. It would need to be compiled with a C compiler before it would be of any use. You'd need the tarball to contain the binary runtime for Ruby for this approach to work.

We don't currently have any guides to doing this. You might want to install Ruby onto your agents instead of using assets. Maybe have a look at https://hub.docker.com/_/ruby/ for inspiration.
