### ISSUE TITLE
Agent config is incorrectly parsed in some cases

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1832]
## Expected Behavior
I should be able to add a comma separated string, with our without spaces, to the agent's yaml config and have the agent connect to one of them.work -->

## Current Behavior
The agent fails to start when multiple backends are provided. Parsing fails in the following cases:
A backend-urls string does not have commas:
`backend-url: "ws://54.85.6.164:8081,ws://54.174.38.152:8081,ws://54.237.213.204:8081"`
A backend-url string is preceded by org and env settings:
```
organization: "ops"                                                         environment: "prod"                                                          subscriptions: "test"                                                            
backend-url: "ws://54.85.6.164:8081, ws://54.174.38.152:8081, ws://54.237.213.204:8081"
```
Yaml list syntax is used:
```
backend-url:
	- "ws://54.85.6.164:8081"
	- "ws://54.174.38.152:8081"
	- "ws://54.237.213.204:8081"
```
We'll need to create some test configs and figure out where the parser is breaking (I think it's breaking on the org/env and backend url definitions but I'm not 100% sure).

**Comment by echlebek** [comment]
I couldn't reproduce the issue with the yaml list syntax.

Use list syntax for yaml config, and comma-separated syntax for command line arguments.

I spoke with @mercul3s about this issue, and she confirmed that list syntax was working for her.
