### ISSUE TITLE
Handle HTTP errors in the "routers" package

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1833]
The way we handle HTTP errors makes it difficult to return good errors from the routers package. Instead, we return HTTP errors from the actions package.

This makes it difficult to return good (fits with http semantics well) errors. The actions (or controllers, as they are otherwise known) are not always in a position to know what error to write. On the other side, if an error is encountered before a controller method is called, the router has little choice in how to control error writing.

Part of the problem is that router methods are not http.HandlerFuncs - they should be.

Refactor all of the router methods to be http.HandlerFuncs. Write errors explicitly in each router HandlerFunc. Remove generic error writing middleware, and the actions.Error type.

**Comment by echlebek** [comment]
Correction: actions.Error type should remain as it facilitates JSON-formatted errors. We should move the data type to the apid package.

**Comment by oferrigni** [comment]
Add a checklist to the description for work to do.

**Comment by calebhailey** [comment]
@echlebek is this still a valid issue?

**Comment by echlebek** [comment]
This is still an issue but unlikely to ever be prioritized.
