### ISSUE TITLE
Feature Request: Log agent connections by default

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-go#1838]
By default, I would like to see the `sensu-backend` service log when an agent connects and disconnects. 

## Expected Behavior
On agent disconnect, something like:
```
{"component":"agentd","id":"host01.example.com","level": "info","msg":"agent disconnected","session":"e44d5070-53e6-4e2e-835c-ac679496b8a6","time":"2018-07-17T09:08:01-04:00"}
```
On agent connect, something like:
```
{"component":"agentd","id":"host01.example.com","level":"info","msg":"agent connected","subscriptions":["","entity:host01.example.com"],"time":"2018-07-17T09:08:07-04:00"}
```

## Current Behavior
Currently, it appears there's very little information getting logged around when hosts connect and disconnect. Setting `log-level: "debug"` get's me the following.

On agent disconnect:
```
{"component":"agentd","level":"warning","msg":"stopping session","recv error":"Connection closed: websocket: close 1001 (going away): bye","session":"e44d5070-53e6-4e2e-835c-ac679496b8a6","time":"2018-07-17T09:08:01-04:00"}
{"component":"agentd","level":"info","msg":"session disconnected - stopping recvPump","time":"2018-07-17T09:08:01-04:00"}
{"component":"agentd","level":"info","msg":"shutting down - stopping subPump","time":"2018-07-17T09:08:01-04:00"}
{"component":"agentd","level":"info","msg":"shutting down - stopping sendPump","time":"2018-07-17T09:08:01-04:00"}

```
On agent connect:
```
{"component":"agentd","id":"host01.example.com","level":"info","msg":"agent connected","subscriptions":["","entity:host01.example.com"],"time":"2018-07-17T09:08:07-04:00"}
{"component":"agentd","level":"debug","msg":"subscribing to topic","time":"2018-07-17T09:08:07-04:00","topic":"sensu:check:default:default:"}
{"component":"agentd","level":"debug","msg":"subscribing to topic","time":"2018-07-17T09:08:07-04:00","topic":"sensu:check:default:default:entity:host01.example.com"}
```

## Context
Currently, with Sensu 1.x, I leverage RabbitMQ to audit the agents who connect and disconnect. While debug logs appear to get some of this information, it's not currently consistent and debug level logging isn't ideal for the long term. The issue I'm trying to solve is to provide engineers and our INFOSEC team 'audit' log like settings that show who is connecting and disconnecting from the `sensu-backend` service.

A stretch idea would be to also log 'attempted' connections as well. Currently, if I do something like `telnet` to `8081`, it connects and nothing is logged about that. Ideally, if someone is poking around at the `sensu-backend` it logs something to indicate this is happening. 

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `2.0.0-nightly#46fed19, build 46fed198d9f311676dcc22c46bf9cfcd5b09cd34, built 2018-07-14T09:21:13+0000`
* Installation method (packages, binaries, docker etc.): PackageCloud.io APT 
* Operating System and version (e.g. Ubuntu 14.04): Debian 9

**Comment by cyphus** [comment]
Thanks for taking the time to create an issue!

The existing log messages for connecting and disconnecting are as specific as they can get for the sensu backend. When an agent disconnects, it does so by closing the socket. Therefore, the sensu-backend cannot tell the difference between an agent disconnecting and the socket closing for other reasons (i.e. network issue). The log messages are made to reflect the actual event as closely as possible.

I'm going to close this, but feel free to reopen if the issue was not addressed.

**Comment by jaredledvina** [comment]
Hey @cyphus,

Thanks for the context. I'll admit that's it's disappointing to hear that Sensu 2 won't be able to log clear messages on which clients are disconnecting. However, is it possible for the existing log messages to be improved? Currently, on disconnect we see:
```
sensu-backend[25402]: {"component":"agentd","level":"warning","msg":"stopping session","recv error":"Connection closed: websocket: close 1001 (going away): bye","session":"a709799a-3ec4-4b61-bd3f-b858b7b90a81","time":"2018-08-02T20:04:05-04:00"}
```

Is there a technical blocker as to why that can't log the client name? Could it potentially log the IP address of the disconnecting client? 

I've looked closer and noticed that the agent connect messages are simply logged at the `info` level which I didn't notice original and additionally missed that the default log level is `warn`. 

Let me know what you think!

**Comment by cyphus** [comment]
@jaredledvina I was under the impression that the issue with the logs had to do with information about the disconnection event itself, rather than which agent is disconnecting. I can definitely add that information to the logs. I'll look into logging attempted connections as well.

**Comment by jaredledvina** [comment]
Ah sweet, thanks!

**Comment by richburroughs** [comment]
@cyphus Thank you! :)
