### ISSUE TITLE
Improve backend status map

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1854]
backend.go contains a [status map](https://github.com/sensu/sensu-go/blob/master/backend/backend.go#L326-L337) that contains info about the status of each daemon. Each daemon has a Status() func, but those funcs do not appear to be implemented: https://github.com/sensu/sensu-go/blob/master/backend/apid/apid.go#L144-L147
Determine if the status map is still useful/what it should be used for, and if so, ensure that each daemon's Status() func returns accurate health/status information.

**Comment by oferrigni** [comment]
Deprecate and remove
