### ISSUE TITLE
Hook up CircleCI status reporting 

### ISSUE THREAD

**Issue by preed** [sensu/sensu-go#1856]
This is a tracking issue to enable build status reporting from CircleCI; two tasks will be done as part of this issue:

* GitHub status badges
* Slack reporting to sensu.slack.com

**Comment by preed** [comment]
I do see Github status badges, which is :+1:

I don't see Slack reports to #engineering in sensu.slack.com; I'll check in with @grepory about this.

**Comment by grepory** [comment]
@preed We discussed how the reporting works. If we want to do more granular reporting, we'll need to have something that does what we want built to receive CircleCI webhooks and act accordingly. I think, for now, let's just stick to the master build failures in #engineering. Can we close this?

**Comment by preed** [comment]
Yup! Sorry about that... I meant to close this up after our conversation!
