### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#186]
**As an operator, I can emit API keys that have no expiration so they can be used by third-party services**

- [ ] The API keys are in fact JWT
- [ ] The tokens have no expiration
- [ ] The API keys can be revoked

**Comment by echlebek** [comment]
@palourde is this still valid?

**Comment by grepory** [comment]
@echlebek I think the implementation could use further discussion.

**Comment by palourde** [comment]
Closed in favor of https://github.com/sensu/sensu-go/issues/2534
