### ISSUE TITLE
Pass errors from etcd watcher functions

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1862]
Discussion around a [PR in sensu-enterprise-go](https://github.com/sensu/sensu-enterprise-go/pull/49#discussion_r204523551) brought up the point that errors are being logged but not propagated from sensu-go's [etcd watcher functions](
https://github.com/sensu/sensu-go/blob/master/backend/store/etcd/watchers.go).

`WatchUnknown` action type errors end up being passed to the channel because the action type is always included in the watch event. Plus, they can only happen if etcd adds an event type beyond `PUT` and `DELETE`, and I highly doubt etcd would make such a breaking change to an existing version.

Json unmarshalling errors are not easy to detect because no error is returned and the resulting struct will be non-nil (but zero valued).

My suggestion is to add an error to all watch events and make sure that all packages that use watch events are updated to handle said error.

**Comment by oferrigni** [comment]
panic if WatchUnknown

**Comment by oferrigni** [comment]
Spike: Determine the conditions under which this can occur. Document in this ticket.

**Comment by palourde** [comment]
Significant changes were made to etcd watchers, I believe errors are now properly logged.
