### ISSUE TITLE
Can't add cluster member to cluster after it's been removed

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1866]
## Expected Behavior
Adding a cluster member to a cluster succeeds

## Current Behavior
Adding the cluster member succeeds, but the member cannot connect

## Steps to Reproduce (for bugs)
sensuctl cluster member-remove $MEMBERID
sensuctl cluster member-add $NAME $PEERURLS

## Context
Testing with docker-compose. The behaviour is the same regardless of the --initial-cluster-state setting.

**Comment by grepory** [comment]
I think the removed cluster member has to be reinitialized. I don’t believe you can reuse member IDs once removed.

**Comment by echlebek** [comment]
Note that the ID is not being used again in the example. I suspect the problem is in the way we retry to connect after failure. The backend is not crashing and is stuck in a retry loop it can never recover from.

**Comment by echlebek** [comment]
Note, we decided to remove this from the clustering milestone.

**Comment by echlebek** [comment]
It seems that removed cluster members should shut down, and not continue to operate. This issue will focus on shutting down backends that have been removed from etcd.

**Comment by echlebek** [comment]
@palourde found that it was necessary to destroy the etcd local state before adding the member back.
