### ISSUE TITLE
InfluxDB timestamp should be optional

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1882]
The [InfluxDB docs](https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/#timestamp) stat e

> The timestamp is optional in Line Protocol. If you do not specify a timestamp for your data point InfluxDB uses the server’s local nanosecond timestamp in UTC.

However, sensu-go's InfluxDB integration errors out if a timestamp is not specified.

## Expected Behavior
Adding an InfluxDB handler to a check without a timestamp should work.

## Current Behavior
Adding an InfluxDB handler to a check without a timestamp errors out with error "influxdb line format requires exactly 3 arguments"

## Possible Solution
Fix parsing in https://github.com/sensu/sensu-go/blob/6f132c0cff5eac0b033fa331087cae002dc41401/agent/transformers/influx_db.go#L41

## Context
Discovered while QAing a beta release on staging.

**Comment by nikkiki** [comment]
![giphy](https://user-images.githubusercontent.com/10634078/43415356-3536b288-93ea-11e8-9a96-02e159b057a1.gif)

**Comment by cyphus** [comment]
No worries @nikkiki! I'm sure it won't be long before you have a bug report on something I wrote haha.
