### ISSUE TITLE
Object attribute value redaction (for secrets etc)

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1886]
Entities and other configuration objects may contain sensitive attributes/values, such as passwords. Do we want/need the ability to redact these values? When logging? When querying the API? Is this a API query param flag (e.g. `&redact_sensitive=false`)? Do some users have the ability to see the values?

**Comment by portertech** [comment]
This issue and questions were prompted by discussion around https://github.com/sensu/sensu/issues/1869

**Comment by palourde** [comment]
@portertech Entities are automatically redacted when encoding to JSON: https://github.com/sensu/sensu-go/blob/bb5921fe01f6c1fb3674da46f04530dc6790d506/types/entity.go#L57-L66.

One way of making redaction optional could be to add a field (e.g. `redactSensitive bool`) that does not get encoded (e.g. `json:"-"`) and inspect its value in the `MarshalJSON` method.

**Comment by oferrigni** [comment]
Apply same fix from classic.

**Comment by annaplotkin** [comment]
This is done.
