### ISSUE TITLE
cluster member ID differs between formats

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#1887]
## Expected Behavior

I'd expect to get the same ID value with `sensuctl cluster member-list` and `sensuctl cluster member-list --format json`.

## Current Behavior

Currently the ID returned by `--format json` is not the actual ID.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# sensuctl cluster member-list
         ID            Name             Peer URLs               Client URLs
 ────────────────── ────────── ─────────────────────────── ─────────────────────
  c7723b754183fa17   backend1   http://192.168.52.10:2380   http://0.0.0.0:2379
  e9aba17aa9930cc0   backend2   http://192.168.52.11:2380   http://0.0.0.0:2379
  ea61e4f1c346c52a              http://192.168.52.12:2380
[root@sensu-backend ~]# sensuctl cluster member-list --format json
{
  "header": {
    "cluster_id": 11650855304899070793,
    "member_id": 14371614735689054743,
    "raft_term": 30
  },
  "members": [
    {
      "ID": 14371614735689054743,
      "name": "backend1",
      "peerURLs": [
        "http://192.168.52.10:2380"
      ],
      "clientURLs": [
        "http://0.0.0.0:2379"
      ]
    },
    {
      "ID": 16837729180057799872,
      "name": "backend2",
      "peerURLs": [
        "http://192.168.52.11:2380"
      ],
      "clientURLs": [
        "http://0.0.0.0:2379"
      ]
    },
    {
      "ID": 16889031804630517034,
      "peerURLs": [
        "http://192.168.52.12:2380"
      ]
    }
  ]
}
[root@sensu-backend ~]# sensuctl cluster member-remove 16889031804630517034
Error: invalid id: strconv.ParseUint: parsing "16889031804630517034": value out of range
[root@sensu-backend ~]# sensuctl cluster member-remove ea61e4f1c346c52a
Removed member ea61e4f1c346c52a from cluster
```

## Context

I am working with @ghoneycutt to do Puppet automation and wanted to support cluster membership through recent sensuctl changes.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensuctl version 2.0.0-nightly#cf3305e, build cf3305eecc6cbd62ef9641ca6a5923d18615100c, built 2018-07-29T09:21:53+0000`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): EL7

**Comment by echlebek** [comment]
The member IDs are hex encoded in the etcd API, but the response type specifies a raw uint64 value.

We're serializing the response type generated by etcd. We could embed that type in our own instead, and specify custom JSON marshaling logic.

**Comment by echlebek** [comment]
@treydock you can work around this by hex-encoding the result you get back from the JSON.

**Comment by treydock** [comment]
@echlebek That work around should work

In case anyone stumbles on this and needs Ruby work around

```
irb(main):002:0> 16889031804630517034.to_s(16)
=> "ea61e4f1c346c52a"
```

**Comment by oferrigni** [comment]
Decided to move forward with @echlebek's suggestion.

**Comment by gtarnaras** [comment]
Hey guys, i am trying to do the same using a bash script but i am getting wrong results. It might be the precision but i am not sure yet. I am using the API to get the numeric ID (here 4046857861428381000). I am then using printf to convert it

```
printf '%02x\n' 4046857861428381000
and i am getting: 382953c8a6ef8548
```

However the sensu cluster current result is 382953c8a6ef85df. i.e. the last two digits are wrong! has anyone faced a similar issue?

**Comment by echlebek** [comment]
@gtarnaras you are likely running into a floating point precision/conversion error.

We've long since added the "MemberIDHex" field to the health output, so this can be closed.
