### ISSUE TITLE
Handlers, Filters and Mutators should display extension entries when listed

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1899]
When users list handlers, filters, and mutators, they should see entries for extensions they have created.

## Expected Behavior
Users register an extension, and can then see the associated handler, filter, and mutator when they list them.

## Current Behavior
The handler, filter and mutator are not shown.

## Possible Solution
Look up extensions when listing handlers, filter and mutators in the store.

## Steps to Reproduce (for bugs)
1. Register an extension.
2. List all handlers. Note that the handler for the extension is not present.

**Comment by annaplotkin** [comment]
Discussion set for 9/5.

**Comment by palourde** [comment]
Extensions are no longer a thing since November 2018, so I'm gonna close this issue because I don't believe we have any short-term plan to re-introduce them.
