### ISSUE TITLE
Entity deletion does not work

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1905]
When deleting an entity via sensuctl, sensuctl reports that the entity was deleted but the entity still shows up when using `sensuctl entity list`. The agent is stopped so reregistration is not a factor.

## Expected Behavior
When using `sensuctl entity delete <entity-id>`, an entity should be deleted and no longer show in `sensuctl entity list`.

## Current Behavior
Entities that are "deleted" still show in `sensuctl entity list`.

## Steps to Reproduce (for bugs)
1. `sensuctl entity delete <entity-id-here>`
2. `sensuctl entity list`

**Comment by amdprophet** [comment]
I was not able to reproduce this a second time. One thing to note is that this was under a clustered environment.

**Comment by palourde** [comment]
@amdprophet I could not reproduce that behaviour on a cluster:

```
$ sensuctl cluster member-list
         ID            Name           Peer URLs              Client URLs
 ────────────────── ────────── ─────────────────────── ───────────────────────
  8927110dc66458af   backend1   http://127.0.0.1:2380   http://127.0.0.1:2379
  a23843c228b27241   backend3   http://127.0.0.1:4380   http://127.0.0.1:4379
  bb75bf8de77581cc   backend2   http://127.0.0.1:3380   http://127.0.0.1:3379

$ sensuctl entity list
       ID        Class     OS           Subscriptions                   Last Seen
 ────────────── ─────── ──────── ─────────────────────────── ───────────────────────────────
  scotch.local   agent   darwin   linux,entity:scotch.local   2018-08-02 13:32:42 -0400 EDT

$ sensuctl entity delete --skip-confirm scotch.local
OK

$ sensuctl entity list
  ID   Class   OS   Subscriptions   Last Seen
 ──── ─────── ──── ─────────────── ───────────
```

Could it be possible that systemd restarted the agent? If you are able to reproduce that problem, please re-open this issue!

**Comment by Alexc0007** [comment]
Hi everyone , 
im having the same issue constantly.
the environment that sending events to sensu is scalable and hosts are being replaced constantly so they are being deleted constantly...
in many cases the api call goes through -  in the logs i can see that request completed but the entity is not deleted....
mostly when i run the api again , it deletes the entity..

**Comment by amdprophet** [comment]
@Alexc0007 we only saw this once in a pre-release version of Sensu Go. If you're seeing this with the latest version - can you please open a new issue?
