### ISSUE TITLE
Don't display LastSeen for proxy entities in the API

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1918]
The LastSeen value for proxy entities is currently wrong; currently, it will display "49 years ago".

We need to tackle https://github.com/sensu/sensu-go/issues/1434 before this will be resolved.

Until it's resolved, let's not display the LastSeen value at all.

**Comment by palourde** [comment]
For reference, we are doing the following in sensuctl:

https://github.com/sensu/sensu-go/blob/419faa2872823f0ca273b96e70d17523366b44b6/cli/commands/timeutil/time.go#L70-L73

**Comment by echlebek** [comment]
Perhaps this is best solved in the dashboard?

**Comment by amdprophet** [comment]
I think implementing the same logic in the dashboard makes the most sense. cc @jamesdphillips

**Comment by jamesdphillips** [comment]
Sounds like a fair solution.
