### ISSUE TITLE
Non-incident events and entities are displayed by default in the dashboard

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1919]
During QA, we discovered that the dashboard now displays non-incident events and entities by default. Additionally, there does not seem to be a way to hide them.

**Comment by jamesdphillips** [comment]
This was a recent and intentional change, [see this comment](https://github.com/sensu/sensu-go/pull/1868#pullrequestreview-140502694). However, this is by no means set in stone. As a user, what subset of events and entities would you expect to see in the list by default?

**Comment by echlebek** [comment]
Haha. So I take it this issue is closed then.
