### ISSUE TITLE
Enhancement Request: Build DEB/RPM's w/ FPM's changelog support

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-go#1921]
Currently, the deb and rpm packages have a super generic changelog, can we include more specific changes in the future?

## Expected Behavior
During upgrade, the deb and rpm package changelog is populate with the changes. 

## Current Behavior
We see:
```
apt-listchanges: Changelogs
---------------------------

sensu-agent (2.0.0~nightly+20180802-1) whatever; urgency=medium

  * Package created with FPM.

 -- Sensu Support <support@sensu.io>  Thu, 02 Aug 2018 09:24:40 +0000

sensu-backend (2.0.0~nightly+20180802-1) whatever; urgency=medium

  * Package created with FPM.

 -- Sensu Support <support@sensu.io>  Thu, 02 Aug 2018 09:24:05 +0000

sensu-cli (2.0.0~nightly+20180802-1) whatever; urgency=medium

  * Package created with FPM.

 -- Sensu Support <support@sensu.io>  Thu, 02 Aug 2018 09:25:07 +0000
```

## Possible Solution
`fpm` supports the args `--deb-changelog` and `--rpm-changelog`. Using these makes package upgrades and the related changes much more clear to operaters as to what's going on. It's also easier to flag any potential issues/breaking changes directly to operators as well. 

## Context
Debian Changelog Policy: https://www.debian.org/doc/debian-policy/ch-source.html#debian-changelog-debian-changelog
https://rpm-packaging-guide.github.io/#working-with-spec-files has some info on the RPM changelog format which I've copied below

The last section, %changelog, is a list of datestamped entries for each Version-Release of the package. They log packaging changes, not software changes. Examples of packaging changes: adding a patch, changing the build procedure in %build.

> Follow this format for the first line:
> 
> * Day-of-Week Month Day Year Name Surname <email> - Version-Release
> 
> Follow this format for the actual change entry:
> 
> Each change entry can contain multiple items - one for each change
> 
> Each item starts on a new line.
> 
> Each item begins with a - character.
> 
> An example datestamped entry:
> 
> %changelog
> * Tue May 31 2016 Adam Miller <maxamillion@fedoraproject.org> - 0.1-1
> - First bello package
> - Example second item in the changelog for version-release 0.1-1

**Comment by jaredledvina** [comment]
Additionally, for debian, the `whatever` should be the distribution that the DEB was built for/supporter. :)

**Comment by grepory** [comment]
We're moving away from fpm.
