### ISSUE TITLE
Rework keepalives to support history

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1924]
Keepalive events do not currently support `CheckHistory` but probably should.

## Expected Behavior
Keepalive events should show their history of received / not received keepalive messages.

## Current Behavior
As keepalive events are not stored, there is no way of fetching the event's history. We do store `KeepaliveFailures` but the type does not support history.

**Comment by nikkiki** [comment]
This issue requires the implementation of a keepalive store. Sending this back until we can spec out some subtasks.

**Comment by annaplotkin** [comment]
Discussion set for 9/4.
