### ISSUE TITLE
[Web UI] Introduce ephemeral toast notifications

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1932]
Some general issues were discovered during QA and VQA process with regards to poor feedback when an action was completed. In particular:

- A lack of proper feedback meant users did not realize that a silence had been created after submitting the form. While we have a umbrella task to explore solutions to this issue ([tracked here](https://github.com/sensu/sensu-go/issues/1920)) in the short term introducing a toast notification should go a long way toward mitigating the issue.
  - Copy of toast should be framed such that _future_ events will be silenced. (eg. "Successfully created. Future events will be silenced.")
- There is no feedback as to whether ad-hoc check request successfully queued. This is very confusing.

**Comment by annaplotkin** [comment]
Related to 1367
