### ISSUE TITLE
[Web UI] Check details page improvements

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1934]
Targeted page improvements for issues discovered during QA and VQA process.

- [ ] The command value does not wrap, meaning large values can render past the edge of the row and underneath content to it's right.
- [ ] Environment variables also do no wrap and are clipped by the container, meaning the entire value cannot viably be viewed.
- [ ] Actions are missing for silencing or un-silencing a check. Especially important if we decide to remove checkboxes on narrower viewports.

**Comment by dabria** [comment]
- [ ] [Un]Publishing has been implemented and can likely be added to this page

**Comment by dabria** [comment]
Notes/Progress:
LAST UPDATED: Tues, 2 October

- [x] The command value does not wrap, meaning large values can render past the edge of the row and underneath content to it's right.
- [] Environment variables also do no wrap and are clipped by the container, meaning the entire value cannot viably be viewed.
- [] ~Actions are missing for silencing or un-silencing a check. Especially important if we decide to remove checkboxes on narrower viewports.~ #1937
- []  [Un]Publishing has been implemented and can likely be added to this page
