### ISSUE TITLE
[Web UI] Checks page improvements

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1935]
Targeted page improvements for issues discovered during QA and VQA process.

- [ ] Filter checks by subscription. (Would mirror entities page, as a user I would be somewhat conditioned to expect this.)
- [ ] If a check has been unpublished this state should be reflected in the list.
  - in particular "executed every X" should be omitted from copy to reduce any confusion.
- [ ] Add option to publish / unpublish checks.
  - Additionally it would be nice to collapse the delete action by default. We should be guiding users toward soft deletion when possible.

**Comment by dabria** [comment]
A seperate PR for adding a fragment to the CheckListHeader should be created
