### ISSUE TITLE
[Web UI] Each details page should contain actions for [un]silencing

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1937]
Each details page (events, checks & entities) should contain actions for both creating and clearing silences associated with the record.

Discovered during QA and VQA process.

**Comment by annaplotkin** [comment]
James to check if this is done or not.

**Comment by dabria** [comment]
@jamesdphillips Do you have any traction on this? I'm working on #1934 and it involves adding silencing, but I'm curious if this issue has addressed that already

**Comment by jamesdphillips** [comment]
@dabria with regards to the check's page this was addressed in #2056

**Comment by annaplotkin** [comment]
This is still missing on the event details page.
