### ISSUE TITLE
Separate system info collection from getAgentEntity()

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#1947]
## Expected Behavior
The collection of system info should not affect an agent's ability to send keepalives.

## Current Behavior
It is possible for system info collection to take up to 3 seconds, or outright fail, which has a direct effect on how long a keepalive takes to send or whether it is sent at all.

## Possible Solution
Move system info collection into a new goroutine that starts up with an agent that will cache the latest fetched system info. Update `getAgentEntity()` to retrieve system info from the cache.

The asset manager will also need to be updated to retrieve system info from this cache but should be handled under another issue.

**Comment by oferrigni** [comment]
Not a release blocker
