### ISSUE TITLE
Can't build sensu with the provided docs

### ISSUE THREAD

**Issue by XenGi** [sensu/sensu-go#1950]
## Expected Behavior

I'm trying to build sensu but it seems like something is missing in documentation that is needed for the build script to work. I would expect after executing the steps in the readme I would end up with binaries that I can use.

## Current Behavior

Instead the build doesn't succeed and complains about some missing things in the repository.

## Possible Solution

Provide necessary information on how to build sensu including the missing things on a fresh system.

## Steps to Reproduce (for bugs)

```
$ git clone --branch 2.0.0-beta.3-1 https://github.com/sensu/sensu-go.git
$ cd sensu-go
$ ./build.sh deps
$ ./build.sh build
Build all commands...
Building agent for linux-amd64
version/cmd/version/version.go:11:2: cannot find package "github.com/sensu/sensu-go/version" in any of:
	/usr/lib/go/src/github.com/sensu/sensu-go/version (from $GOROOT)
	/home/xengi/.go/src/github.com/sensu/sensu-go/version (from $GOPATH)
version/cmd/version/version.go:11:2: cannot find package "github.com/sensu/sensu-go/version" in any of:
	/usr/lib/go/src/github.com/sensu/sensu-go/version (from $GOROOT)
	/home/xengi/.go/src/github.com/sensu/sensu-go/version (from $GOPATH)
warning: "github.com/sensu/sensu-go/agent/cmd/..." matched no packages
warning: "github.com/sensu/sensu-go/agent/cmd/..." matched no packages
no packages to build
cp: cannot stat 'target/linux-amd64/sensu-agent': No such file or directory
```

## Context

I'm trying to build a package for archlinux.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 2.0.0-beta.3-1
* Installation method (packages, binaries, docker etc.): source
* Operating System and version (e.g. Ubuntu 14.04): Archlinux, 4.17.14-arch1-1-ARCH

**Comment by echlebek** [comment]
The repository needs to be stored in `$GOPATH/src/github.com/sensu/sensu-go`. This is a limitation of the Go compiler toolchain (although it won't be in later releases of Go).

We should update the documentation to mention this fact.

**Comment by XenGi** [comment]
I'll fix the path and try again. Thx for hint. I'm not a go expert. :)

**Comment by echlebek** [comment]
Looking at this again, we do link the Go installation instructions in README.md, which covers setting GOPATH. Users are expected to have a working Go installation before proceeding past to the next step, so I think this issue can be closed.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/go-path-issues-installing-sensu-go-from-source/1869/1
