### ISSUE TITLE
Allow to set client auth token w/o writes to disk

### ISSUE THREAD

**Issue by schu** [sensu/sensu-go#1956]
This issue is a follow-up from a short discussion on Slack (#sensu2)

To access the Sensu 2 API programmatically I currently initialize a Sensu client as follows:

```
func NewSensuClient(apiURL string) (*client.RestClient, error) {
        sensuClientConfig := &basic.Config{
                Cluster: basic.Cluster{
                        APIUrl: apiURL,
                },
                Profile: basic.Profile{
                        Environment:  "default",
                        Format:       "none",
                        Organization: "default",
                },
        }
        sensuClient := client.New(sensuClientConfig)
        tokens, _, err := sensuClient.CreateAccessToken(apiURL, "admin", "P@ssw0rd!")
        if err != nil {
                return nil, err
        }

        if sensuClientConfig.SaveTokens(tokens); err != nil {
                return nil, err
        }

        return sensuClient, nil
}
```

The only way to set the newly acquired access token appears to be `SaveTokens`, where `SaveTokens` also write a token file to disk, which is not always desired. The `*resty.Client` instance used by the Sensu client is private and its `SetAuthToken` method not accessible.

Currently, there's also the `OnBeforeRequest` hook func that renews tokens and thus writes to disk by default.

cc @grepory

**Comment by palourde** [comment]
The current API client used by sensuctl wasn't meant to be used by external libraries. That would require some major refactoring. I believe [API keys](https://github.com/sensu/sensu-go/issues/2535) would be a simpler solution for most needs.
