### ISSUE TITLE
Cannot set handler for keepalive check

### ISSUE THREAD

**Issue by brieken** [sensu/sensu-go#1960]
I want to be able to get notified when a server is down. Currently i have a slack handler. But i cannot set it for the keepalive check. Is there a reason for this?

**Comment by echlebek** [comment]
Hi @brieken, keepalives are a special case. They have a static handler assigned to them called "keepalive". If you create a handler with this name, keepalive events will be handled by it.

So given that you probably have a handler called "slack", you can create a set handler called "keepalive", and then include the "slack" handler in it.

Hope this helps. :)

**Comment by brieken** [comment]
wow that's a fast respone. thanks!
