### ISSUE TITLE
Sensu TLS configuration requires custom CA

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1963]
The sensu-backend connects to its own embedded etcd via a localhost TCP connection. [Existing code](https://github.com/sensu/sensu-go/blob/d43643add913f31201af6e37c1ec78398cfe2ccc/backend/etcd/etcd.go#L151-L180) in etcd startup ensures that the embedded etcd always listens on localhost so that this connection always succeeds.

In order for a TLS enabled sensu-backend to work, it must be provided with a TLS certificate that is valid for localhost. No trusted Certificate Authority will let you create a TLS certificate with localhost, which forces the user to create their own CA in order to enable TLS in sensu. This adds configuration complexity, and for some organizations may be impossible due to security policy.

## Possible solution

Make embedded etcd listen over http on localhost, even in TLS enabled configurations.

**Comment by absolutejam** [comment]
Since I'm clueless about etcd and have only recently begun to test sensu2 over the old RabbitMQ with TLS setup - Does sensu2 not require explicit TLS settings?
