### ISSUE TITLE
Add initial-advertise-client-urls configuration option to sensu-backend

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1964]
Etcd has a configuration option, `initial-advertise-client-urls`, that specifies one or more client urls that get advertised to other etcd members. The current implementation advertises `listen-client-urls` to other members, but this is incorrect, as the listening address may be different than the address used by other members to connect.

## Context
This issue was discovered while testing the health endpoint in a clustered environment. Checking etcd health requires sending client requests to all other etcd members, which is done by connecting to the other members' advertised client urls. In the case of sensu-staging, the advertised client url is the listening address, which is a non-routable `0.0.0.0`.

**Comment by annaplotkin** [comment]
Citi came across an issue with clustering w/ ssl and after further investigation it was deemed that this was the culprit. Nominating this to be resolved in Beta 9.
