### ISSUE TITLE
Deleted checks still create events

### ISSUE THREAD

**Issue by brieken** [sensu/sensu-go#1966]
Using sensu-backend beta 3 on linux and sensu-agent beta 2 on windows.

When I delete a check. I don't see it anymore in the WebGUI and also not with sensuctl.

But events generated by these checks still show up. And fire handlers and in my case create slack alerts.

**Comment by grepory** [comment]
@brieken Thanks for filing an issue. This is a bit of a thorny one. 

We know that events can persist after a check is renamed/deleted. We're working on a [potential solution](https://github.com/sensu/sensu/issues/1893) for this problem in 1.x, but for 2.x we're taking a step back to re-think what the check/event lifecycle really looks like.

That being said, I want to make sure there isn't a bug here. Are checks continuing to be scheduled after the check is deleted? Do you have multiple sensu-backends in a cluster? You should be able to see check execution / scheduling in logs if they're still be scheduled. If you do, please provide relevant log lines.

**Comment by brieken** [comment]
yes i can see checks still being scheduled. I have a single sensu backend running.

```
Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"test","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:Test"}
Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"test","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:Test"}
Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"test","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:Test"}



Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"ServerHardwareCheck","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:entity:***************************"}
Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"ServerHardwareCheck","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:entity:***************************"}
Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"ServerHardwareCheck","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:Server"}
Aug 19 07:39:07 monitor.xxxxx.net sensu-backend[5479]: {"check":"ServerHardwareCheck","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-08-19T07:39:07+02:00","topic":"sensu:check:default:default:Windows"}

**Comment by absolutejam** [comment]
In the same vein, is there a way to purge old events? I have some checks which I've removed but `sensuctl event list` is pretty cluttered with old ones. It would be nice to auto-expire/purge old check results after a defined period.

Or alternatively, perhaps allow a query, eg.
```bash
sensuctl event delete --query="{{ .Timestamp < '2018-09-11' }}"
# or
sensuctl event delete --query="{{ .Age > 2d }}"
```
 *(Disclaimer: I have been using a lot of InfluxDB lately)*

**Comment by palourde** [comment]
This has definitely been fixed since then, just confirmed locally!
