### ISSUE TITLE
Round robin check scheduling with proxy entities does not work as expected

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1969]
## Expected Behavior
Round robin checks with proxy entities work as expected

## Current Behavior
Round robin checks execute once and then stop executing for proxy entities

## Steps to Reproduce (for bugs)
1. Create a proxy entity
2. Create a round robin check and set the proxy entity ID to the proxy entity

## Context
QA Staging environment

**Comment by annaplotkin** [comment]
Let's see if this is still an issue.

**Comment by nikkiki** [comment]
I cannot reproduce this issue as of https://github.com/sensu/sensu-go/commit/efd4a59879684c0d986dd297a06ae6ea1ac7363c. Closing this out for now 👍
