### ISSUE TITLE
Check update CLI does not remember state for round robin (true/false)

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1971]
## Expected Behavior
On update, the interactive CLI will display the current values for things.

## Current Behavior
Round robin always appears as false.

## Possible Solution
Use the current state of the round robin field to inform the CLI.

## Steps to Reproduce (for bugs)
1. Create a round robin check
2. Update the round robin check, observe the round robin default is false

## Context
Staging

**Comment by annaplotkin** [comment]
Let's see if this is still an issue.
