### ISSUE TITLE
Ejected cluster members can still function as backends leading to denial of service

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1972]
## Expected Behavior
When removing a member from a sensu cluster, I expect agents to reconnect to another backend.

## Current Behavior
Agent connections are not interrupted, but no meaningful service can occur.

## Possible Solution
TBD

## Steps to Reproduce (for bugs)
1. Create a clustered sensu installation with many agents.
2. Remove one of the cluster members with `sensuctl cluster member-remove`
3. Observe that the agents connected to that backend are no longer able to function correctly.

## Context
Staging

**Comment by portertech** [comment]
@echlebek so if an Agent is connected to a Backend that is removed as a member of a cluster, the Backend does not terminate all Agent connections?

**Comment by portertech** [comment]
I imagine this is not a regression and applies to our previous beta release. Am I correct?

**Comment by echlebek** [comment]
Yes, this applies to all previous releases that support cluster member removal. The issue can be worked around by stopping the backend that was removed.

**Comment by palourde** [comment]
I just tried to reproduce this issue with the latest changes around agent sessions management and websocket ping/pong and it appears the agents now reconnect to another backend as soon as the member is removed, e.g.:

```
{"component":"agent","level":"info","msg":"sending keepalive","time":"2020-01-23T11:04:46-05:00"}
{"component":"agent","error":"Connection error: websocket: close 1006 (abnormal closure): unexpected EOF","level":"error","msg":"transport receive error","time":"2020-01-23T11:04:51-05:00"}
{"component":"agent","level":"info","msg":"connecting to backend URL \"ws://127.0.0.1:9081\"","time":"2020-01-23T11:04:51-05:00"}
{"component":"agent","level":"info","msg":"successfully connected","time":"2020-01-23T11:04:51-05:00"}
{"component":"agent","level":"info","msg":"sending keepalive","time":"2020-01-23T11:04:51-05:00"}
```

Therefore I'm gonna go ahead and close this issue!
