### ISSUE TITLE
Round robin checks execute more often than expected when multiple subscriptions are specified

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1973]
## Expected Behavior
Round robin checks will only execute 1/N times on a given agent, even in the presence of multiple subscriptions.

## Current Behavior
When a set of agents matches multiple round robin subscriptions, the round robin check will execute (1/N)*NUM_SUBSCRIPTIONS per agent.

## Possible Solution
Deduplicate subscriptions? We need to do some design work around this, about what should happen. What if the sets of agents are disjoint in terms of their subscriptions, etc. Difficult use case.

## Steps to Reproduce (for bugs)
1. Create a round robin check that targets multiple subscriptions.
2. Create a set of agents that have all of those subscriptions.
3. Observe greater than expected round robin check execution.

## Context
Staging

**Comment by portertech** [comment]
I believe this is a behaviour we would see in 1.x. In 1.x it is up to the client to de-dup the concurrent check executions (key is check name).
