### ISSUE TITLE
Implement "dead man's switch" on etcd alarms

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1979]
Add a watcher for a PUT on alarms keys (alarms have their own store) and fire a handler on an event. This might be similar to a keepalive handler, but for sensu-backend, and can act as a dead man's switch in case of any etcd alarms (indicating trouble with an etcd cluster).

**Comment by echlebek** [comment]
One thing we could potentially do is fire events, that are not persisted, when etcd alarms occur. This could allow users to handle alarm events like other events.

**Comment by annaplotkin** [comment]
This requires pipelined to function without etcd.

**Comment by echlebek** [comment]
It doesn't seem likely that Sensu will be able to function when etcd is not. Going forward, a "monitor Sensu with Sensu" approach, requiring two etcd installations, seems much more resilient.

> This requires pipelined to function without etcd.

We would have no way of looking up handlers without etcd, and this is core to the design of Sensu, so I'm going to close this issue.
