### ISSUE TITLE
Make Authentication more congruent w/ OAuth 2 spec

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#199]
Copied from https://github.com/sensu/sensu-go/pull/198#discussion_r119904802

> Possibly for a separate discussion but we could (very loosely) follow oauth spec. One up side would be that it may be a bit simpler for existing OAuth clients in other languages to consume the API.
> 
> eg.
> 
> ### Authentication w/ Userinfo
> 
> ```golang
> POST /oauth/token
> {
>   grant_type: "password",
>   username: "bob@sensu.io",
>   password: "mysecurepassword123",
>   scope: "" // maybe at some point ¯\_(ツ)_/¯
> }
> 
> // response:
> {
>   token_type: "bearer",
>   expires_in: 1231231,
>   access_token: ...,
>   refresh_token,
> }
> ```
> 
> ### Refresh
> 
> ```golang
> POST /oauth/token
> {
>  grant_type: "refresh_token",
>   refresh_token: "xxx",
> }
> 
> // response:
> {
>   token_type: "bearer",
>   expires_in: 1231231,
>   access_token: ...,
>   refresh_token,
> }
> ```

**Comment by palourde** [comment]
Closed in favor of https://github.com/sensu/sensu-go/issues/2534.
