### ISSUE TITLE
[Web UI] Keepalive details should be present on details page

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#1990]
## Expected Behavior

Keepalive details (interval and timeout) should be reflected on the details page.

## Current Behavior

Omitted.

## Possible Solution

Display them!

## Steps to Reproduce (for bugs)

1. Navigate to the entity details page.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `2506fa18`
* Installation method (packages, binaries, docker etc.): nightly.
* Operating System and version (e.g. Ubuntu 14.04): ew-boon-too

**Comment by jamesdphillips** [comment]
Blocked by #1988

**Comment by annaplotkin** [comment]
This can be closed.
