### ISSUE TITLE
Proposal: Pipeline Interfaces

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1991]
Introduction
----------------
The core business logic of Sensu is its event pipeline. Events occur in the system, and are filtered, mutated and handled, in that order.

The pipeline concept is nicely generic. A filter is a function that receives an event, and returns a boolean value. A mutator is a function that receives an event, and returns another event. A handler is a function that receives an event, and executes a program.

Proposal
------------
Replace the existing concrete implementations of filters, mutators and handlers with ones that are named after their specific implementation. This means renaming or refactoring the existing datatypes. Create new Filter, Mutator and Handler interface types. The renamed and refactored datatypes will implement these interfaces.

Rationale
-------------
The design of the filter, mutator and handler datatypes is somewhat restrictive, and makes assumptions about the implementation details of these things. The EventFilter datatype assumes that all event filters will be govaluate expressions. The mutator datatype assumes that all mutators will be external processes. The handler datatype is somewhat generic, but only because it acts as the union of several types.

By creating a set of interfaces that define a pipeline, we can add or remove pipeline components without affecting the rest of the system. For instance, several filter types could coexist: GovaluateFilter, JavascriptFilter, and GRPCFilter. The pipeline executing these filters would not need to be aware of their implementation details.

Design
----------
The sensu pipeline interfaces are trivial to express:
```go
type Filter interface {
    Filter(*types.Event) (bool, error)
}

type Mutator interface {
    Mutate(*types.Event) ([]byte, error)
}

type Handler interface {
    Handle([]byte) error
}
```

Implementation Requirements
----------------------------------------
* EventFilter becomes GovaluateFilter, and implements the Filter interface.
* Mutator becomes SubprocessMutator (it launches an external process), and implements the Mutator interface.
* Handler becomes three things: PipeHandler, SocketHandler, and SubprocessHandler. They all implement the Handler interface.
* piplined will be aware of only the Filter, Mutator and Handler interfaces. The store for filters, mutators and handlers becomes polymorphic, and can load various types of filters, mutators and handlers. Hint: use `types.Wrapper` to support this polymorphism.
* The API is modified to support generic filters, mutators and handlers, probably with `types.Wrapper` as well.

Future Opportunities
----------------------------
With this work completed, developers can experiment with adding new filter, mutator and handler components to the system as desired, without worrying about disrupting core pipeline functionality. New types of filters like Javascript and Lua can be added and tested in relative safety.

**Comment by grepory** [comment]
The interfaces for Mutators and Handlers won't work with existing plugins and should be changed.

Mutator plugins expect an event and return a byte array with arbitrary data.

Handlers expect a byte array.

**Comment by cyphus** [comment]
I went over the proposal and related source in https://github.com/sensu/sensu-go/tree/master/backend/pipelined. Because this proposal deals with refactoring existing code, there are no substantial unknowns to deal with. Eric has already addressed Greg's interface concerns in an edit to the proposal. 

@annaplotkin care to give this a second review?

**Comment by cyphus** [comment]
As far as implementing these changes, I'd recommend splitting up the work into three tasks, one each for Filters, Mutators, and Handlers.

**Comment by annaplotkin** [comment]
@cyphus I am supportive of these changes and would back your suggestion of making 3 tickets. I would also suggest we turn this ticket into an Epic to house those. 

@grepory Can you review as well and see if this all looks good to you?

**Comment by annaplotkin** [comment]
@grepory Does this proposal look okay to you? If so, we'll break out those 3 tickets and get started on those this week.

**Comment by grepory** [comment]
We might be making some changes to the type system and API in general, so let's hold off on this for now. I'm looking into a way to make types.Wrapper a bit more generally useful and to standardize and encode a lot more metadata about objects.
