### ISSUE TITLE
Reconcile check hook documentation with check hook feature

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1993]
In https://github.com/sensu/sensu-docs/issues/678, the hook feature is described differently from how the feature appears to actually work.

Investigate whether we want the doc UX, or the one we currently have. Depending on the outcome, correct either the feature, or the documentation.

**Comment by treydock** [comment]
I would just add that the docs currently provide no way to set hook type with JSON.  The array of hook names doesn't allow specifying `critical` or `warning`, for example.  The current behavior allows JSON objects to define checks as if someone ran `sensuctl check set-hooks`.  The documented reference for `check_hooks` lacks the ability to specify what `set-hooks` does with `--type` flag.

**Comment by annaplotkin** [comment]
We need to address this in the docs.

**Comment by echlebek** [comment]
It appears that the functionality in the software is what's desired. The docs need correcting.

![skinner](https://user-images.githubusercontent.com/1633772/48870325-4cd90080-ed95-11e8-8815-12de803f23d5.jpg)
