### ISSUE TITLE
Missing route for sensuctl entity update

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#1994]
There exists an API function to update a sensuctl entity, but no route. It's possible to update entities using `sensuctl entity create`, but replacing an entire entity object to update one or two attributes is a bit overkill, especially for entities that are auto-created (i.e. when a sensu-agent connects for the first time).

**Comment by echlebek** [comment]
We don't have patch implemented anywhere, really, so this issue might be larger than expected.

**Comment by annaplotkin** [comment]
We should support PATCH as a verb instead. @annaplotkin to make a separate ticket.
