### ISSUE TITLE
Cluster health table format overflows on error field

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#1997]
I noticed in testing an assert.Contains(<error message>) my assertions were failing on any string longer than one word in a test error message. Error messages appear to overflow this table field:

![display_table_cluster_error](https://user-images.githubusercontent.com/2100610/44372947-5bb0ce00-a49b-11e8-9b7f-1f1da3b099f0.png)

I dug through our table writer and didn't see any obvious clues as to why the row is overflowing. This isn't a major issue but it is annoying.

**Comment by nikkiki** [comment]
I've found that `table.SetAutoWrapText(false)` gives us the desired effect for the cluster health command. This will prevent auto text wrapping for all other commands as well (unless the string contains a newline). I can move forward with this solution if it seems sufficient!

```
$ sensuctl cluster health
         ID           Name                    Error                   Healthy
 ────────────────── ───────── ────────────────────────────────────── ─────────
  8927110dc66458af   default   cluster error runs off screen: <nil>   true
```
