### ISSUE TITLE
Encountered panic when executing round robin check

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#2005]
## Expected Behavior

Check is delivered without panic.

## Current Behavior

Panic.

```
goroutine 232 [running]:
github.com/sensu/sensu-go/backend/messaging.(*wizardTopic).SendRoundRobin(0xc422325b80, 0x1f322e0, 0xc422565e00, 0x0, 0xc420314170)
        /Users/.../sensu-go/backend/messaging/wizard_topic.go:60 +0x1aa
github.com/sensu/sensu-go/backend/messaging.(*WizardBus).PublishDirect(0xc4222baf50, 0xc421ba86c0, 0x26, 0x1f322e0, 0xc422565e00, 0x2273757461747322, 0x7865222c3632313a)
        /Users/.../sensu-go/backend/messaging/wizard_bus.go:172 +0x115
github.com/sensu/sensu-go/backend/schedulerd.(*roundRobinScheduler).execute(0xc4224c43c0, 0xc4225b2600)
        /Users/.../sensu-go/backend/schedulerd/round_robin_scheduler.go:56 +0x93
created by github.com/sensu/sensu-go/backend/schedulerd.(*roundRobinScheduler).loop
        /Users/.../sensu-go/backend/schedulerd/round_robin_scheduler.go:48 +0x60
```

## Possible Solution

Unclear.

https://github.com/sensu/sensu-go/blob/master/backend/messaging/wizard_topic.go#L59-L61

It could be as simple as checking if the result of `t.bindings[id]` isn't nil but I'm not familiar enough with the messaging package to be certain. I'd rather not unintentionally wallpaper over the issue.

## Your Environment

One _maybe_ important note was that I encountered this while trying to replicate a different issue and was only running with **one** node at the time.

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `cbe26ec4d42bbfc366d8602c38af03f0f9ecbad9`
* Installation method (packages, binaries, docker etc.): n/a
* Operating System and version (e.g. Ubuntu 14.04): macOS

## Additional Context

This might one of those icky ones, I've had it happen twice but in general have had trouble replicating consistently.

```
{
  "type": "CheckConfig",
  "spec": {
    "command": " bat -print \"h\" https://www.google.com/search",
    "environment": "Production",
    "handlers": [
      "slack"
    ],
    "high_flap_threshold": 0,
    "interval": 5,
    "low_flap_threshold": 0,
    "name": "is-google-seriously-still-up",
    "organization": "BobsBurgers",
    "publish": true,
    "runtime_assets": [
      "bat",
      "http-checks"
    ],
    "subscriptions": [
      "www"
    ],
    "proxy_entity_id": "google",
    "check_hooks": null,
    "stdin": false,
    "subdue": null,
    "ttl": 0,
    "timeout": 0,
    "round_robin": true,
    "output_metric_format": "",
    "output_metric_handlers": null,
    "env_vars": null
  }
}
```

**Comment by echlebek** [comment]
Thanks James, I'll have a look soon :)

**Comment by echlebek** [comment]
I'm closing this out as round robin scheduling is currently disabled, and a new implementation is being actively worked on.
