### ISSUE TITLE
sensuctl output colors are bad when using a white background terminal

### ISSUE THREAD

**Issue by paulczar** [sensu/sensu-go#2006]
## Expected Behavior

I should be able to easily read output from sensuctl 

## Current Behavior

When using a white terminal window the gray of the titles in the output is very hard to read.

## Possible Solution
use better default colors to be suitable for both black and white background terminals.

## Steps to Reproduce (for bugs)

![sensuctl-output](https://user-images.githubusercontent.com/2488346/44546057-6c9c5200-a6dc-11e8-8031-b931f1b6d2bd.png)

## Your Environment
sensuctl  2.0.0-nightly on ubuntu / XFCE based laptop

**Comment by echlebek** [comment]
:tada:
