### ISSUE TITLE
Validate Go code style formatting

### ISSUE THREAD

**Issue by preed** [sensu/sensu-go#2011]
There've been a few discussions about how much linting we should do as part of CI, whether or not it should break the build, and what should drive that. (These have mostly involved me, @amdprophet, and @echlebek; see also #1946 and #1927.)

At Sensu Summit, @echlebek and I chatted (and afterward, @amdprophet and I chatted), and we came to the following conclusions: 

1. GoLangCI is nice, but it might (in the future) prove annoying, since the only way to reliably reproduce the results on your machine is to keep pushing to a pull-request. (That is: if GoLangCI fails, it may not be immediately clear what you should do to fix it, and if wanted to become a good citizen and lint your code _before_ you create a PR, you can't really do this either.)
1. Any linting/style checks that we should decide to do in CI should be driven by the build system, so that any Go dependencies that are needed are encoded there, and can be easily run by developers locally (i.e. `make lint` or similar).
1. @echlebek said there is the assumption that Go code _is_ correctly `go fmt`'d, so we should re-add a check in CI that validates this assumption... y'know... assuming this assumption is true. ;-)

**Comment by annaplotkin** [comment]
We need to decommission Travis as a prerequisite. Paul may need to scope and write a ticket on that.

**Comment by grepory** [comment]
@preed @echlebek 

golangci can be run locally with the same configuration as is run automatically by the service:

https://github.com/golangci/golangci-lint

**Comment by preed** [comment]
Landed in #2129.
