### ISSUE TITLE
WebUI - Add confirmation toast when tapping 'Re-Run' on the Check Results page. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2012]
We should add a toast to signal confirmation when the user taps 'Re-Run' on the Check Results page. 

## Expected Behavior
- When tapping 'Re Run', there should be visual confirmation (in the form of a toast) that tapping the button did what the user intended to do. Toast could say 'Re-Run initiated successfully' or something along those lines. 

## Current Behavior
- Right now, tapping the Re-Run button *APPEARS* to do nothing although it is actually being done.

**Comment by jamesdphillips** [comment]
Depends on #1932
