### ISSUE TITLE
DISCUSS: reject API requests with unknown query params

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#2014]
When an API request is made with query params that are not used by the backend; we should consider returning a 4xx HTTP status code. This will allow any scripts/apps/etc. to detect cases where the version of a backend may not support a feature. Additionally, this issue may be able to be solved by implementing https://github.com/sensu/sensu-go/issues/100 or something like it.

**Comment by cyphus** [comment]
This is related to the [API versioning discussion](https://docs.google.com/document/d/1FtpLJJCbPHApkFx0rM454GSvGoydiA2-5BI-VEQRiAg/edit?usp=sharing). If we are to allow multiple versions of API objects to be accepted by a given endpoint, then that may include extra query parameters that may be used by future versions of the API. I think it would be best to keep the API liberal in what it will accept.

We can provide an API endpoint to deliver the Swagger spec for that API so clients can do things like feature detection.

**Comment by amdprophet** [comment]
@cyphus that makes sense to me. I think that this problem is better solved by sending a header with the API version. I'll close this out.
