### ISSUE TITLE
Mismatching documentation and default for Agent.Config.KeepaliveInterval

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2018]
## Expected Behavior

Consistency between documentation of a default value and an actual default value.

## Current Behavior

The documentation for `Agent.Config.KeepaliveInterval` claims the default value is `60`.
The actual default value is `20`.

## Possible Solution

Pick a value and make sure it's consistent everywhere, or just not mention what the default value is in the documentation.

The real question to solve this issue: which value is "right"? `20`, `60`, or even something else altogether?

## Context
Documentation for `Agent.Config.KeepaliveInterval`:
https://github.com/sensu/sensu-go/blob/master/agent/agent.go#L89-L91

Actual default value set here:
https://github.com/sensu/sensu-go/blob/master/agent/agent.go#L45-L46

**Comment by palourde** [comment]
Sensu 1 default value is `20` and I don't see any reason why it would need to be higher by default. Let's use the actual value!

**Comment by ccressent** [comment]
Sounds good to me!
