### ISSUE TITLE
[Build Stability] CircleCI containers run out of memory during the link

### ISSUE THREAD

**Issue by preed** [sensu/sensu-go#2019]
Per @echlebek, some Go builds are running out of memory during the link step on CircleCI:

- https://circleci.com/gh/sensu/sensu-go/648
- https://circleci.com/gh/sensu/sensu-go/623

This issue tracks fixing that.

**Comment by preed** [comment]
I'm tracking this down; looks like we need to open a support ticket to get access to the `resource_class` attribute to bump up memory (from the default, 4 GB, to 6, the next tier up).

I just opened a request with them; we'll see what happens!

**Comment by oferrigni** [comment]
Since race detection removed from integration tests, this error has not recurred.
