### ISSUE TITLE
Nagios metric extraction failing with error

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2021]
running nagios check_load  plugin as check command and setting the metrics format to nagios_perfdata results in sensu agent error when running the check.

## Expected Behavior
command:
/usr/lib64/nagios/plugins/check_load -w 0.01,0.01,0.01 -c 0.01,0.01,0.01
output:
CRITICAL - load average: 0.01, 0.04, 0.05|load1=0.010;0.010;0.010;0; load5=0.040;0.010;0.010;0; load15=0.050;0.010;0.010;0;

sensu-agent should parse output as valid nagios perfdata.

## Current Behavior

sensu-agent logs this error message:

{"component":"agent","error":"invalid nagios perfdata metric: \n","level":"error","msg":"unable to extract metric from check output","time":"2018-08-31T23:28:57Z"}

## Possible Solution

something in the nagios extraction logic going wrong?

## Steps to Reproduce (for bugs)

1. create this check using nagios check_load command and set nagios_perfdata
`
{
  "command": "/usr/lib64/nagios/plugins/check_load -w 0.1,0.1,0.1 -c 0.2,0.2,0.2",
  "environment": "default",
  "handlers": [],
  "high_flap_threshold": 0,
  "interval": 30,
  "low_flap_threshold": 0,
  "name": "nagios_check_load",
  "organization": "default",
  "publish": true,
  "runtime_assets": [],
  "subscriptions": [
    "localhost"
  ],
  "proxy_entity_id": "",
  "check_hooks": null,
  "stdin": false,
  "subdue": null,
  "ttl": 600,
  "timeout": 10,
  "round_robin": false,
  "output_metric_format": "nagios_perfdata",
  "output_metric_handlers": [],
  "env_vars": null
}
`
2. run sensu-agent and watch for the the error log
3. reset output metric format to ""
4.  run agent and watch the agent return results

## Context
sensu-agent logs for reference:
`
{
  "component": "agent",
  "error": "invalid nagios perfdata metric: \n",
  "level": "error",
  "msg": "unable to extract metric from check output",
  "time": "2018-08-31T23:56:57Z"
}
`
`
{
  "component": "agent",
  "level": "debug",
  "msg": "sending message",
  "payload": "{\"timestamp\":1535759817,\"entity\":{\"class\":\"agent\",\"deregister\":false,\"deregistration\":{},\"environment\":\"default\",\"id\":\"test-agent\",\"keepalive_timeout\":120,\"last_seen\":1535759433,\"organization\":\"default\",\"redact\":[\"password\",\"passwd\",\"pass\",\"api_key\",\"api_token\",\"access_key\",\"secret_key\",\"private_key\",\"secret\"],\"subscriptions\":[\"localhost\"],\"system\":{\"hostname\":\"sensu-2.x-demo-centos7-x86-64\",\"os\":\"linux\",\"platform\":\"centos\",\"platform_family\":\"rhel\",\"platform_version\":\"7.5.1804\",\"network\":{\"interfaces\":[{\"name\":\"lo\",\"addresses\":[\"127.0.0.1/8\",\"::1/128\"]},{\"name\":\"enp0s3\",\"mac\":\"08:00:27:01:ab:81\",\"addresses\":[\"10.0.2.15/24\",\"fe80::a00:27ff:fe01:ab81/64\"]}]},\"arch\":\"amd64\"},\"user\":\"agent\"},\"check\":{\"command\":\"/usr/lib64/nagios/plugins/check_load -w 0.01,0.01,0.01 -c 0.01,0.01,0.01\",\"environment\":\"default\",\"handlers\":[],\"high_flap_threshold\":0,\"interval\":30,\"low_flap_threshold\":0,\"name\":\"nagios_check_load\",\"organization\":\"default\",\"publish\":true,\"runtime_assets\":[],\"subscriptions\":[\"localhost\"],\"proxy_entity_id\":\"\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":0,\"timeout\":10,\"round_robin\":false,\"duration\":0.01549033,\"executed\":1535759817,\"history\":null,\"issued\":1535759817,\"output\":\"CRITICAL - load average: 0.00, 0.03, 0.05|load1=0.000;0.010;0.010;0; load5=0.030;0.010;0.010;0; load15=0.050;0.010;0.010;0; \\n\",\"status\":2,\"total_state_change\":0,\"last_ok\":0,\"occurrences\":0,\"occurrences_watermark\":0,\"output_metric_format\":\"nagios_perfdata\",\"output_metric_handlers\":[],\"env_vars\":null},\"metrics\":{\"handlers\":null,\"points\":null}}",
  "time": "2018-08-31T23:56:57Z",
  "type": "event"
}
`

## Your Environment
centOS 7.x vagrant managed virtualbox VM
Installed Packages
`
sensu-agent.x86_64         2.0.0_beta.4~4-1
                                             
sensu-backend.x86_64      2.0.0_beta.4~4-1                                            

sensu-cli.x86_64                 2.0.0_beta.4~4-1                                           
`

**Comment by echlebek** [comment]
The bug is caused by this line: https://github.com/sensu/sensu-go/blob/master/agent/transformers/nagios.go#L63

The parser should be tolerant of multiple semicolons in order to correctly parse the nagios perfdata spec. See here for more information: https://nagios-plugins.org/doc/guidelines.html#AEN200

We can probably fix the bug by changing this from != 2 to >= 2.

**Comment by echlebek** [comment]
Looks like I was wrong. The bug was that the logic that split on whitespace was resulting in a single newline character being treated as a metric. The parser should trim whitespace as a first pass.
