### ISSUE TITLE
Determining Platform and PlatformVersion may fail on some Linux distros

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2027]
Determining `Platform` and `PlatformVersion` may fail on some Linux
distributions not explicitly supported by `gopsutil`, or for which the library
relies on `lsb_release` being available.

See `gopsutil` internals for Linux, in particular `PlatformInformation()`:
https://github.com/sensu/sensu-go/blob/master/vendor/github.com/shirou/gopsutil/host/host_linux.go#L298

## Expected Behavior

Tests run successfully if I follow the README instructions.
All system info is gathered successfully if I follow the README instructions.

## Current Behavior

Tests for the `sensu-go/system` package fail.

I'm assuming that means that an agent running on a Linux distribution not
explicitly supported by `gosputil`, or for which `gopsutil` relies on
`lsb_release` to get the `PlatformVersion` information (eg: Arch), might never
be able to fully fill in the system information even though the tests for
`sensu-go/system` assert those should not be empty!

## Possible Solution

Document the need for `lsb_release` to be installed for `gopsutil` to be able to
determine `Platform` and `PlatformInformation` in all cases.

## Steps to Reproduce

On a distribution not explicitly supported by `gopsutil`, or needing
`lsb_release` to be present according to the library's internals (Arch Linux is
an example):

```
$ pwd
/home/cyril/go/src/github.com/sensu/sensu-go/system

$ GOCACHE=off go test .
--- FAIL: TestInfo (0.02s)
	Error Trace:	system_test.go:21
	Error:      	Should NOT be empty, but was 
FAIL
FAIL	github.com/sensu/sensu-go/system	0.024s

$ sudo pacman -S lsb-release
...

$ GOCACHE=off go test .
ok  	github.com/sensu/sensu-go/system	0.022s
```

## Your Environment

- Arch Linux (rolling release)
- Current `master` branch 
  ```
  $ pwd
  /home/cyril/go/src/github.com/sensu/sensu-go/system
  $ git rev-parse --short master
  cabf9023
  ```

**Comment by oferrigni** [comment]
This potentially breaks assets if you're using platform filtering.

**Comment by annaplotkin** [comment]
Some investigation still needed.

**Comment by calebhailey** [comment]
@ccressent is this still a valid issue?

**Comment by ccressent** [comment]
Still valid, though I don't believe it's an issue for the distros we officially support for the agent.

**Comment by ccressent** [comment]
I've discussed this with @amdprophet some more, and we believe the best way forward to close this issue is through documentation.

The crux of the issue is that, because of the way the `gopsutil` library works, it can try to open `/etc/lsb_release` or run `/usr/bin/lsb_release` to determine system information. This is typically tried on Linux distributions not explicitly supported by `gopsutil`. The issue is that `lsb_release` is not part of the default installation for a lot of distributions. It's an additional package that needs to be installed by the operator. So in the rare combination of "agent running on Linux distribution not explicitly supported by `gopsutil`" and "lsb_release is not installed", the agent reports some empty system information.

Over time, the issue is mitigated by the fact that the library explicitly supports more and more distributions. But on the rare occasions where an agent is unable to report system information, the missing `lsb_release` package is likely to be the culprit.
