### ISSUE TITLE
Possibility to accept telegraf output in client

### ISSUE THREAD

**Issue by derkgort** [sensu/sensu-go#2031]
This is a feature request / idea.

The background of this request is that Telegraf from Influx is a great tool that's expanding with more and better metrics and checks each release. A lot of time has been put into it and it shows.
It's rather lightweight for what is does and has interesting features. 

Telegraf can be configured to send it's output to a lot of destinations like http, influx, stdout, file, etc.
It would be great if the Sensu client would have some way to receive the output of a running Telegraf and process it like it would process outputs of Sensu plugins. Not sure what's the best way, probably receiving the output from telegraf via a fifo device or a http localhost port would be similar to stdin input from running a plugin program.

This will give Sensu direct access to a lot of features and plugins in Telegraf. And it will keep people from developing the same thing in 2 places.

I've looked arround in the Sensu2 code but could not find a http input or file/fifo input.

**Comment by sureshsubramaniam** [comment]
This has been in telegraf community a Long back 
This would be a cool feature to have and will extend the usage of Sensu

**Comment by obfuscurity** [comment]
I think this makes a lot of sense. Most of the bits are there (aiui) to support this via sensu-go's events API (exists, but needs documentation), but we'd need to add support to recognize the intended Telegraf [data format output](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md).

cc @grepory @nikkiki @portertech for their thoughts

**Comment by grepory** [comment]
I think a telegraf output plugin would be a pretty amazing win for Telegraf and for Sensu! Being able to drop Telegraf into an environment already monitored by Sensu and then route it through Sensu to one or more TSDBs (including InfluxDB which we already support mutating to that format natively).

I think this is a great opportunity for us to contribute to Telegraf.
