### ISSUE TITLE
DISCUSSION - Rethinking Keepalives. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2032]
Engineering and product got together to discuss https://github.com/sensu/sensu-go/issues/1924. 

During that discussion, it became apparent that perhaps the way Keepalives function today is not optimal and could benefit from discussion and possible rethinking with Greg and Sean.

**Comment by grepory** [comment]
@annaplotkin Can you make sure that I'm there for that call?

**Comment by annaplotkin** [comment]
Absolutely @grepory! I forgot to put it in the description but the item was to have a follow up discussion with you and Sean. Sorry about that!

**Comment by annaplotkin** [comment]
Discussion set for 9/20.

**Comment by nikkiki** [comment]
Filed https://github.com/sensu/sensu-go/issues/2089.

**Comment by annaplotkin** [comment]
Discussion notes on 9/20:

1. Full rework of keepalives are not going to be tackled at this time. Simon and Cyril have addressed several bugs related to keepalives and it is functioning better now. If we run into scaling issues later, we will rethink them. 
2. To enhance the user experience, we are going to add a check to see if an agent is registered at authentication time. If it is not, we will send a registration event for the agent at that time. Anna to file a ticket and link here. 
3. Nikki has filed 2089 to make the diagram more accurate.

**Comment by annaplotkin** [comment]
Closing this issue.
