### ISSUE TITLE
API documentation & possible auto-discover/spec endpoint?

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu-go#2039]
Hey! I've recently begun dabbling in Sensu once more after a large hiatus (Finally working on a project that needs it!), and I wanted to dive into Sensu 2 because it solves a lot of my issues from 1.x.

Just curious however, is there any API documentation at the moment? I know the `sensuctl` is the main interface at the moment - and what a tool it is - but for config management, I don't want to have to rely on having that binary and piping `yaml -> json -> stdin`. I can carry on like this for now, but was just curious.

Also, is there any possibility of some kind of auto-discover/spec endpoint to allow auto-generation of API calls instead of hard-coding them?

## Expected Behavior
  - API should be documented for use with third-party integrations

## Current Behavior
  - No API documentation (That I could find?)

## Possible Solution
  - Document API endpoints
  - Optionally provide ways to discover endpoints

Regards,
James.

EDIT: I forgot to mention how much I love `sensuctl create` so that I can keep all my definitions in source control!

**Comment by grepory** [comment]
Thanks for the feedback @absolutejam!

We've had some discussions internally about generating the API with https://github.com/go-swagger/go-swagger -- I think it might be time to do a technical spike on what the implications of that are for our `apid` package, types package, etc. We'll be looking into this pretty soon.

**Comment by palourde** [comment]
The API has been manually documented for now, see https://docs.sensu.io/sensu-go/latest/api/overview/
