### ISSUE TITLE
Discussion: Versioned types for sensu 2.0

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2041]
We need to version the API and consequently our individual types.

Version specification of types can happen in one of two ways:

URL path specification (e.g. /api/v1/*) or as a part of the input to a version-agnostic path (e.g. /api/checks).

I think that the latter offers the most flexibility with the least cognitive burden. If we have experimental types or features of types, if we want to deprecate individual types, or if we want to modify individual types with potentially breaking changes, we can simply add a new version of that type, instead of adding more versions of "the api" for people to consider. We can encapsulate logic for how a version of a type is handled internally closer to the type itself.

Type versioning does make documentation of the API somewhat more confusing. For example, there's no built-in support for type versioning in Swagger/OpenAPI. They were originally designed for only versioning whole APIs. I'm not sure if go-swagger generates multiple versions of documentation (one per API version). So this approach might be more expensive from that perspective.

With individually-versioned types, we would have to add a version field to each type. I, personally, like the Kubernetes version specification syntax and that plays well with some kubernetes integration work that we would like to do in the future. E.g. `v1alpha1` -- where it's effectively a triple of the form (major version, "stability indicator", "release number"). This is not entirely unlike package versioning that we're familiar with.

While we're considering how to implement this, please take into consideration #2039 and if/how this might interact with go-swagger.

**Comment by nikkiki** [comment]
^^ Updated the link from the API Versioning discussion for read-access to all.
