### ISSUE TITLE
Consider renaming entity class field as 'class' is a reserved word in other languages

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#2049]
While working on the sensu-go-chef cookbook, we noticed that the entity `class` field is a reserved word in Ruby (and other object-oriented languages). While it's not a huge deal, it did require some attention to naming when referring to it in Ruby. `entity_class` might work, but potentially stutters in Go. For context, see discussion in https://github.com/sensu/sensu-go-chef/pull/32#discussion_r216483469

**Comment by grepory** [comment]
:+1: to EntityClass / entity_class.

**Comment by afstanton** [comment]
Ruby coders sometimes use "klass" when they want to use "class".

**Comment by annaplotkin** [comment]
Terrance to get a sense of the rename implications.
