### ISSUE TITLE
Choose between coreos/bbolt and boltdb/bolt

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2052]
We currently vendor both `coreos/bbolt` and `boltdb/bolt`.
The later is an embedded KV store that appear to be in maintenance mode while
the former is a fork claiming the following:

> bbolt is a fork of Ben Johnson's Bolt key/value store. The purpose of this fork
> is to provide the Go community with an active maintenance and development target
> for Bolt; the goal is improved reliability and stability. bbolt includes bug
> fixes, performance enhancements, and features not found in Bolt while preserving
> backwards compatibility with the Bolt API.

## Possible Solution

1. Keep vendoring and using both
2. Pick one or the other and update the code base accordingly

## Context

> @grepory:
> So as it turns out, I see very little difference between coreos/bbolt and
> boltdb/bolt. Basically just a handful of things have been cleaned up It looks
> like they moved from appveyor to travis I’m inclined to switch so we’re not
> vendoring two versions of boltdb and we’re using the version of bolt that etcd
> uses--because hi we’re gonna get really good at these things.

> @echlebek:
> I actually think we would be better off using the original. It's more stable in
> that they are not actively adding new features. And so far, we don't need any
> features from bbolt.
>
> The bbolt maintainers want to add new features, whereas Ben has said he's only
> doing bug fixes from now on. Software conservatism ;)

**Comment by echlebek** [comment]
I didn't consider that we already vendor bbolt when I was thinking about this before. Since we already depend on it, it makes more sense to just use it instead of vendoring another version. Let's use bbolt.

**Comment by ccressent** [comment]
**Consensus: use `coreos/bbolt` rather than `boltdb/bolt`.**

I'll take care of:
- changing dependencies from `boltdb/bolt` to `coreos/bbolt` and updating the code and tests anywhere needed (if at all)
- removing everything related to `boltdb/bolt` from our vendored dependencies
