### ISSUE TITLE
non json WARNING messages being issued on stdout

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2054]
my sensu-backend is throwing non JSON output WARNING messages to stdout.
Could impact log parsing, if there is a strong expectation that backend will be produce json to stdout.

## Expected Behavior
json output to stdout

## Current Behavior
Getting this message:
WARNING: 2018/09/09 13:25:08 grpc: addrConn.resetTransport failed to create client transport: connection>

The warning (i think) has to do we me trying to start a local sensu-backend service while I had a vagrant managed virtual machine running with some of its ports partially mapped to localhost via NAT.

The warning itself isn't such a big deal, but the format is a break from the expected json output to stdout.

I believe Eric made mention that it has something to do with a library logging and by passing the expected logging facility/formatter.
The log message seems to be from:
google.golang.org/grpc/clientconn.go

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
ran across this Warning while trying to help sort out an unrelated log parsing issue associated with journalctl.
ideally it would be nice to be able to take all the stdout message and pass them into jq for log parsing.
this Warning message prevents that.

## Your Environment

sensu-backend-2.0.0~nightly+20180911-1.x86_64 rpms running a a fedora and centos 7 systems.

**Comment by cyphus** [comment]
I did some investigation. gRPC exposes a function, `SetLoggerV2` to set the logger used by the entire gRPC package.

We call an etcd-wrapped version of this function in [backend/etcd/etcd.go's init](https://github.com/sensu/sensu-go/blob/1af5b06711056ab5c780fcd67e6a9c9667e924b3/backend/etcd/etcd.go#L48) to turn off all gRPC logging.

However, when we start the etcd server, the logger is [overwritten again](https://github.com/sensu/sensu-go/blob/1af5b06711056ab5c780fcd67e6a9c9667e924b3/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/grpc.go#L81), this time to write directly to stderr for warning and error messages. There is no configuration option or alternate function call that would avoid this behavior.

There is a [commit in etcd](https://github.com/etcd-io/etcd/commit/339cda03b31e0d0c857f14fa1c133f865d04025d#diff-78eab5345f5ae0390912b4fee2b5d664) that stops etcd from overwriting the gRPC logger, but it's part of etcd 3.4 which is unreleased at the time of this writing.

I'm going to add code to our etcd server startup function to overwrite the logger _after_ the server is started. Once etcd 3.4 is released we should be able to remove the workaround.

**Comment by cyphus** [comment]
Working around the logging issue necessarily creates a race condition where the gRPC logger is being used while being set.

Our options are to fork/edit etcd to prevent it from setting the gRPC logger, or to wait until etcd releases version 3.4 (sometime in 2018). After discussing on slack, we're going to wait for the next etcd release.
