### ISSUE TITLE
[Web UI] ServerError: 502

### ISSUE THREAD

**Issue by rreilly-edr** [sensu/sensu-go#2058]
502 error 

## Expected Behavior
it works?

## Current Behavior
i get the below 502 error 

## Steps to Reproduce (for bugs)
1. start sensu with basic config ( i am just getting my feet wet with 2.0)
2. go to ip:3000
3. log in with admin and  P@ssw0rd!

**Web UI Stack Trace:**

at `undefined` ([src/utils/fetch.js:17](https://github.com/sensu/sensu-go/blob/0de35c2/dashboard/src/utils/fetch.js#L17))
at `tryCatcher` (node_modules/bluebird/js/browser/bluebird.core.js:3414)
at `Promise._settlePromiseFromHandler` (node_modules/bluebird/js/browser/bluebird.core.js:2630)
at `Promise._settlePromise` (node_modules/bluebird/js/browser/bluebird.core.js:2687)
at `Promise._settlePromise0` (node_modules/bluebird/js/browser/bluebird.core.js:2732)
at `Promise._settlePromises` (node_modules/bluebird/js/browser/bluebird.core.js:2811)
at `Async._drainQueue` (node_modules/bluebird/js/browser/bluebird.core.js:163)
at `Async._drainQueues` (node_modules/bluebird/js/browser/bluebird.core.js:173)
at `Async.drainQueues` (node_modules/bluebird/js/browser/bluebird.core.js:47)
at `MutationObserver.<anonymous>` (node_modules/bluebird/js/browser/bluebird.core.js:3186)

## Your Environment
ubuntu 16.04
version: sensu-backend_2.0.0~nightly+20180913-1_amd64.deb

**Comment by annaplotkin** [comment]
@rreilly-edr Have you seen this again? Do you have a reverse proxy set up?

**Comment by jkerry** [comment]
I've got a very similar stacktrace showing up on the latest 5.0.0 build.
![image](https://user-images.githubusercontent.com/2170651/49743599-22c68000-fc69-11e8-925e-c9f26f6f90d3.png)

**Comment by jkerry** [comment]
It'll happen in chrome after letting the UI rest for a moment without interacting with it

**Comment by exitquote** [comment]
I'm also seeing the same issue after updating.  I'm running a cluster of 3 machines on CentOS 7 and using the docker container at 5.0.1.  Everything on the backend seems to work - making API calls and using sensuctl doesn't cause any problems, this seems specific to the dashboard.

**Comment by jkerry** [comment]
Might be cluster related without persistent connections? I'm also running a 3 container cluster

**Comment by jamesdphillips** [comment]
@rreilly-edr @exitquote are you both seeing this occur after you have authenticated?

**Comment by echlebek** [comment]
@jamesdphillips in the initial report the steps to reproduce include login.

**Comment by jamesdphillips** [comment]
@echlebek I want to isolate and understand if we are encountering two separate issues. (Even if they manifest in the same error.)

**Comment by exitquote** [comment]
@jamesdphillips yes - i can authenticate in a browser, but immediately afterward i get this error.

**Comment by exitquote** [comment]
in case it's at all helpful, the corresponding error with debug turned all the way up appears to be:

`{"component":"etcd","level":"info","msg":"http: proxy error: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\"\n","pkg":"","time":"2018-12-19T18:31:03Z"}`

**Comment by jamesdphillips** [comment]
@exitquote do you mind sharing your Sensu backend configuration?

My initial suspicion from your error message is that the `api-url` argument isn't correct. If, for instance you have TLS enabled the value may have to be `api-url: "https://localhost:8080"`.

**Comment by exitquote** [comment]
@jamesdphillips yes, this did turn out to be my issue.  in my config for the older version, i was not specifying api-url, i think this param was added between this build and the GA build that i'm using where this broke.  thank you!!
