### ISSUE TITLE
Remove /health dependency on StatusMap

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2061]
`GET /health` currently has a dependency on `Status()`, `StatusMap` and `StatusRouter` that will be deprecated in https://github.com/sensu/sensu-go/issues/1854: 
https://github.com/sensu/sensu-go/blob/613facf2e9894c2fbded012b4aedc78949d6c8d3/backend/apid/routers/status.go#L42-L50

I propose we refactor `/health` related logic to `/cluster/health` and `ClusterRouter`, and remove the dependency it has on anything status related.

Required by #1854

**Comment by echlebek** [comment]
Can we remove StatusMap entirely? What functionality is that providing right now?

**Comment by echlebek** [comment]
Oh I see, hence this issue, derp. I think it's reasonable to remove the call to r.Status().

**Comment by nikkiki** [comment]
After some slack chat, we decided to keep the endpoint as `/health` but we'll still refactor the router and controllers to something like `HealthRouter` and `HealthController`. /cc @palourde
