### ISSUE TITLE
No "tabular" output format + unexpected "none" format in sensuctl configure

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2063]
In `sensuctl configure`, when configuring the preferred output format, there is no "tabular" option listed (output format currently referred to in the docs). It seems to be replaced by an option called "none".

## Expected Behavior

Ability to pick `tabular` in the list of output formats.
No output format called `none`.

## Current Behavior

```
$ sensuctl configure
? Sensu Backend URL: http://127.0.0.1:8080
? Username: admin
? Password: *********
? Organization: default
? Environment: default
? Preferred output format:
❯ none
  json
  wrapped-json

$ sensuctl config view
=== Active Configuration
API URL:       http://127.0.0.1:8080
Sensu Edition: core
Environment:   default
Organization:  default
Format:        none
```

## Steps to Reproduce

Just run and follow the instructions from `sensuctl configure`.

## Your Environment

* Sensu version:
```
$sensuctl version
sensuctl version 2.0.0-dev#249a69d, build 249a69d1f3b19de832d8753974489ef0bbd3a87d, built 2018-09-13T17:16:17-070
```
* Installation method: git
* Operating System and version: Arch Linux (rolling release ; up to date)

**Comment by ccressent** [comment]
Tested `sensuctl configure` as far back as tag `2.0.0-alpha.1` and the same problem appear every time. I'm starting to think maybe there is a problem in my setup?

```
$ cd $GOPATH/src/github.com/sensu/sensu-go

sensu-go$ git checkout 2.0.0-alpha.1
HEAD is now at c057e896 Merge pull request #356 from sensu/alpha

sensu-go$ GOCACHE=off ./build.sh build_cli
Building cli for linux-amd64

sensu-go$ ./bin/sensuctl version
sensu-ctl version 2.0.0-alpha.1#c057e89, build c057e8966de0be81ee47b0ff2827d38db638fb3c, built 2018-09-17T14:47:33-0700

sensu-go$ ./bin/sensuctl configure
```

Can someone else try to reproduce it please?

**Comment by nikkiki** [comment]
@ccressent I don't think there is a problem with your setup. The behavior you are describing is the same on my end. I think its reasonable to update `none` to `tabular` since that describes the default format that is selected.

**Comment by ccressent** [comment]
From @palourde:
> So here we have the hardcoded `none` value: https://github.com/sensu/sensu-go/blob/0206af28d2bb8eac2096345e4aafc6b95221287a/cli/commands/configure/configure.go#L203 It should probably use that constant instead: https://github.com/sensu/sensu-go/blob/14870588130ed636c0c75e21f5d23c5dafb0b036/cli/client/config/config.go#L17 That being said, because of this default condition, both have the same effect: https://github.com/sensu/sensu-go/blob/bd3dd4ea69d40c525be3e47af145a3156c14193b/cli/commands/helpers/print.go#L27

Resolution should be easy then: replace that hardcoded `none` with that `FormatTabular` constant. That should do the trick.
