### ISSUE TITLE
Decouple asset manager from agent

### ISSUE THREAD

**Issue by cyphus** [sensu/sensu-go#2072]
Decouple sensu-agent from the asset manager by having [the agent struct](https://github.com/sensu/sensu-go/blob/bb39ab1dccfa8e1e953b0d3c029b3324fce3aaad/agent/agent.go#L188) depend on the [boltdb Getter interface](https://github.com/sensu/sensu-go/blob/cce7a1c02aa93d8d634f6853d714ed8609b9ad80/asset/boltdb_manager.go#L20-L22) instead of an `assetmanager.Manager` directly.

**Comment by grepory** [comment]
duplicate of #2038
