### ISSUE TITLE
keepalive event object does not contain ['check']['output']

### ISSUE THREAD

**Issue by barryorourke** [sensu/sensu-go#2081]
I've been taking a look at how keepalives and have discovered that the event object returned by keepalive checks does not contain ['check']['output'] as it does in Sensu 1.x.

## Expected Behavior
The keepalive event object should contain ['check']['output']. 

## Current Behavior
The keepalive event object does not contain ['check']['output'].

## Steps to Reproduce (for bugs)
I discovered this after trying to handle keepalive events using an internal handler we have written in python. 
Doing a comparison between a sensu 1.x and sensu 2.x keepalive event object should be enough evidence.  

## Context
This causes any handlers written for Sensu 1.x that refer to ['check']['output'] to fail to run.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
Sensu 2.0.0~nightly+20180918
* Installation method (packages, binaries, docker etc.):
RPM package
* Operating System and version (e.g. Ubuntu 14.04):
Scientific Linux 7.5

**Comment by palourde** [comment]
Hi @barryorourke 

Good catch, thank you for submitting an issue. I just submitted a patch, hopefully it will be merged soon!

Thanks
