### ISSUE TITLE
Update Event Flow Diagram

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#2089]
When discussing keepalives, we realized that there was some internal misunderstanding about the flow of keepalives through eventd. We should revisit the [Event Flow Diagram](https://github.com/sensu/engineering/wiki/Sensu-Architecture) and perhaps split up the diagram so we can add more detail around eventd and keepalived.
https://github.com/sensu/sensu-go/blob/6661f64756b0d42ffe02e15e9d33e35d4a41b300/backend/keepalived/keepalived.go#L315

**Comment by calebhailey** [comment]
@nikkixdev is this still relevant? Did #3652 change anything here? Are keepalives now processed like regular events?

**Comment by nikkixdev** [comment]
I think an updated event flow diagram would be even more useful now that we have had some architectural changes to the keepalive flow.
