### ISSUE TITLE
Checks history should not contain the current status

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2093]
## Expected Behavior
The current status should not appear in the check history. E.g. if the check was failing and just resolved, we should have:

```
history: [1, 1, 1]
status: 0
```

By doing so, we do not duplicate the current status and we obtain an _extra_ history point.

## Current Behavior
The history of a check presently contains the current status. If we take our example above, we currently have:

```
history: [1, 1, 0]
status: 0
```

## Possible Solution
In eventd, we could simply insert the status of the event fetched from the store, into the history, and not the current one.

## Steps to Reproduce (for bugs)
N/A

## Context
It was raised by @ccressent in https://github.com/sensu/sensu-go/pull/2076#discussion_r219272213.

## Your Environment
N/A

**Comment by palourde** [comment]
cc @portertech

**Comment by jspaleta** [comment]
question...
is this a break from classic behavior?

**Comment by palourde** [comment]
From @portertech:
> including latest state in history was for simplicity and I suppose correctness

**Comment by palourde** [comment]
@jspaleta Yes, it would be a breaking change from classic behavior.

**Comment by jspaleta** [comment]
@palourde   okay.  i definitely need to know how this discussion shakes out.  If this is stays as is in 2 I'll need to make sure the sensu-plugin shim code does the correct thing converting to 1.x.
