### ISSUE TITLE
Accept YAML arrays in agent and backend configuration files

### ISSUE THREAD

**Issue by jkerry** [sensu/sensu-go#2096]
Whenever appropriate it would be helpful for the agent and backend yaml configuration files to accept arrays instead of comma separated strings. This is much easier to work with in some configuration management / service discovery systems like Habitat where your templating engine has very little state or runtime compute capability

## Expected Behavior
Ex: etcd-initial-cluster
```
etcd-initial-cluster: 
  - backend1=http://backend1:2380
  - backend2=http://backend2:2380
  - backend3=http://backend3:2380
```

## Current Behavior
Ex: etcd-initial-cluster
```
etcd-initial-cluster: backend1=http://backend1:2380,backend2=http://backend2:2380,backend3=http://backend3:2380
```
## Possible Solution
accept both formats and do type detection in the configuration read? 

## Context
I'm scripting out habitat packages for clustering with habitat. Without the ability to generate yaml arrays for types like these I'll need to avoid using service discovery entirely or resort to post-templating, pre-service-start yaml transformation bash black magic.

**Comment by cyphus** [comment]
Hi @jkerry, thanks for submitting an issue!

Habitat's template engine comes with a builtin [strJoin helper](https://www.habitat.sh/docs/developing-packages/#strjoin) that should allow you to specify an `etcd-initial-cluster` in the current configuration format:

```
etcd-initial-cluster: {{strJoin etcd-members ","}}
```

I'm going to optimistically close this issue, but if the `strJoin` helper doesn't work for you, feel free to reopen.

Cheers!

**Comment by jkerry** [comment]
what we would need in habitat would be a map / join function since 
```
etcd-initial-cluster: 
  - backend1=http://backend1:2380
  - backend2=http://backend2:2380
  - backend3=http://backend3:2380
```

would translate to
```
etcd-initial-cluster: 
  {{#eachAlive svc.members as |backend| ~}}
    - {{member.sys.hostname}}=http://{{member.sys.hostname}}:{{member.cfg.etcd-listen-peer-port}}
  {{/eachAlive ~}}]
```

and as far as I know there's no way to load the result of that enumeration into a runtime only array, to then feed into strJoin.  

config management systems aside, I think a config format array might feel more natural than a comma separated list embedded in a string field

**Comment by cyphus** [comment]
I 100% agree that a yaml array would be more natural here. Whether or not it's technically possible with Habitat CM, it shouldn't require jumping through hoops in the configuration template.

Let's make the `etcd-initial-cluster` config option support both comma separated string and YAML list. We can join the array as a string in sensu-go itself.

**Comment by palourde** [comment]
We probably simply need to modify `flagEtcdInitialCluster` so it uses `GetStringSlice` instead of `GetString`.

**Comment by calebhailey** [comment]
@palourde can this be closed? I know we fixed a number of these config file string/slice issues a while back. Our [documentation still uses a string example](https://docs.sensu.io/sensu-go/latest/reference/backend/#configuration), is that accurate?
