### ISSUE TITLE
sensuctl event list  tabular display bug

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2099]
Found a bug doing my Yolo demo.
Check the attached screenshot for config details.
![screenshot from 2018-09-21 11-23-08](https://user-images.githubusercontent.com/39937/45902293-85a72a00-bd92-11e8-8f34-dca512eeeb3b.png)

Gut tells me its something specific with my podman based check command output.
It looks like the output parsing is all garbled..maybe due to line return characters at the end of the output?

sensuctl event info  frodo_baggins  docs.sensu.io   looks okay though
sensuctl event list --format=json   also looks fine.

see attached output of  sensuctl event list --format=json
[event_list.txt](https://github.com/sensu/sensu-go/files/2406758/event_list.txt)

## Expected Behavior
docs.sensu.io and docs_sensu_io checks should display correctly in event list tabular view

## Current Behavior
output for these checks are garbled.

## Steps to Reproduce (for bugs)
Not sure how to reproduce generally.. i've only seen this with my podman based check command.
Do we have a documented way for me to inject a check result via cmdline?

## Your Environment
rpm package sensu-backend-2.0.0~nightly+20180920-1.x86_64
Fedora

**Comment by nikkiki** [comment]
Oh this is a _fun_ one! Okay, I'm able to reproduce the issue! Yes, it has to do with the check output containing the return and newline characters: `/r/n`.
```
$ sensuctl event list
      Entity                 Check                     Output           Status   Silenced             Timestamp            
 ──────────────── ─────────────────────────── ──────────────────────── ──────── ────────── ─────────────────────────────── 
  frodo_baggins    always_false                                              1   false      2018-09-21 12:20:55 -0700 PDT  
        1   false      2018-09-21 12:20:33 -0700 PDT  tp WARNING: 301
                                                                                                                           
        1   false      2018-09-21 12:20:41 -0700 PDT  tp WARNING: 301
                                                                                                                           
  frodo_baggins    keepalive                                                 1   false      2018-09-21 12:22:49 -0700 PDT  
  samwise_gamgee   always_false_with_mapping                                 1   false      2018-09-14 12:21:06 -0700 PDT  
  samwise_gamgee   keepalive                                                 1   false      2018-09-21 11:59:51 -0700 PDT 
```

So, we _could_ render the check output last, which solves the immediate formatting problem. However, our resources that contain timestamps _typically_ display those as the last column.
```
$ sensuctl event list
      Entity                 Check             Status   Silenced             Timestamp                     Output          
 ──────────────── ─────────────────────────── ──────── ────────── ─────────────────────────────── ──────────────────────── 
  frodo_baggins    always_false                     1   false      2018-09-21 12:20:55 -0700 PDT                           
  frodo_baggins    docs.sensu.io                    1   false      2018-09-21 12:20:33 -0700 PDT   CheckHttp WARNING: 301
                                                                                                                           
  frodo_baggins    docs_sensu_io                    1   false      2018-09-21 12:20:41 -0700 PDT   CheckHttp WARNING: 301
                                                                                                                           
  frodo_baggins    keepalive                        1   false      2018-09-21 12:22:49 -0700 PDT                           
  samwise_gamgee   always_false_with_mapping        1   false      2018-09-14 12:21:06 -0700 PDT                           
  samwise_gamgee   keepalive                        1   false      2018-09-21 11:59:51 -0700 PDT                           
```

@annaplotkin I would love some product feedback on a direction here. I see a few different solutions.
1. Move the `Output` field to the right most column (see solution above). It's simple, but not the most consistent with other resources.
2. Sensuctl allows users to configure which special characters they want trimmed from fields, perhaps through a flag ex. `--trim-special-char '/n'`. Implementation might be complex unless we limit the fields that this flag can apply to. Performance deficit.
3. We leave it up to the user to trim special characters from check output, if they so choose. We would also make a note in the documentation regarding how tabular format only explicitly expresses values.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/3667
