### ISSUE TITLE
keepalives firing handler on OK status

### ISSUE THREAD

**Issue by barryorourke** [sensu/sensu-go#2104]
Keepalives are firing handlers no matter the status of the event.

## Expected Behavior
Keepalives should only fire handlers when their status is not OK.

## Current Behavior
Keepalives are firing handlers no matter the status of the event.

## Steps to Reproduce (for bugs)
I have set up a handler as follows for keepalive events, the handler is an internal one, but you should be able to reproduce this with any handler.

```
[root@phbtest ~]# sensuctl handler info keepalive                                                                                                                                                                                       
{
  "type": "Handler",
  "spec": {
    "name": "keepalive",
    "type": "set",
    "timeout": 60,
    "handlers": [
      "cst"
    ],
    "filters": null,
    "env_vars": null,
    "environment": "default",
    "organization": "default"
  }
}
[root@phbtest ~]# sensuctl handler info cst
{
  "type": "Handler",
  "spec": {
    "name": "cst",
    "type": "pipe",
    "command": "/usr/bin/handler-cst --map-v2-event-into-v1",
    "timeout": 60,
    "handlers": null,
    "filters": null,
    "env_vars": null,
    "environment": "default",
    "organization": "default"
  }
}
```

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
2.0.0~nightly+20180924
* Installation method (packages, binaries, docker etc.):
RPM
* Operating System and version (e.g. Ubuntu 14.04):
Scientific Linux 7.5

**Comment by annaplotkin** [comment]
Cyril to see if this was resolved with last week's fixes.

**Comment by ccressent** [comment]
Hi @barryorourke, thanks for taking the time to report your problem. I see
 you're not using the `is_incident` filter on your handlers, and I think that's
 why you're observing that behaviour. Please refer to [this section of the Sensu
 2.x
 documentation](https://docs.sensu.io/sensu-core/2.0/reference/handlers/#each-and-every-check-results-are-handled)
 for an explanation.
 
 Could you try adding that `is_incident` filter to your handlers? I think it
 should solve your problem. I'm closing this issue for now, but feel free to
 re-open if adding the filter doesn't help.
