### ISSUE TITLE
Epic: RBAC Redesign

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2105]
Epic to house the stories for the redesigned RBAC. 

Spec is here: https://docs.google.com/document/d/1vWQF7UtCViqOpsAclPY-nC8b6OmL4Qp3NiY-S64zAHs/edit#heading=h.go6w58vdi7ft

Parent of #2106 
Parent of #2107
Parent of #2108
Parent of #2109
Parent of #2110
Parent of #2145 
Parent of #2148

**Comment by majormoses** [comment]
@annaplotkin any chance on making that google doc public?
