### ISSUE TITLE
SPIKE - Redesign Authorization. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2107]
In the redesigned world of RBAC, we also need to redesign authentication. 

In this ticket, we would like to capture the following in an investigative spike: 
1. In the new RBAC model, how would we design authentication?
2. Document design overview.
3. Document any unresolved questions/concerns.
3. Breakdown of discrete tasks to accomplish design if no blocking questions/concerns are raised.

**Comment by palourde** [comment]
K8s authorization logic: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/rbac.go
