### ISSUE TITLE
Malformated log message from monitor

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2116]
## Expected Behavior

Log messages are formatted correctly.

## Current Behavior

Monitor has been seen to spit out messages of this form:
```
{"component":"monitor","level":"info","msg":"shutting down monitor for %s/sensu.io/monitors/8c10da7e794c","time":"2018-09-18T17:44:33Z"}
```

## Possible Solution

See:
- https://godoc.org/github.com/sirupsen/logrus#Info
- https://github.com/sensu/sensu-go/blob/efd4a59879684c0d986dd297a06ae6ea1ac7363c/backend/monitor/supervisor.go#L109

Use the correct logging function; eg: `Infof()` instead of `Info()` in the above example.

## Your Environment

* Sensu version used: `master`
* Installation method (packages, binaries, docker etc.): git
* Operating System and version (e.g. Ubuntu 14.04): n/a

**Comment by grepory** [comment]
References an old commit.
