### ISSUE TITLE
sensuctl feature request:  resource sub command to generate wrapped-json template for resources. 

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2123]
Make it possible to output a json representation of a resource template for each resource.
Reduce friction for using sensuctl create -f and api calls to create functional resource json definitions without a lot of trial and error.

Strawman Example:
sensuctl check template
outputs a wrapped-json template for a CheckConfig prepopulated with defaults, exposing a reasonable subset of attributes as makes sense.
 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by calebhailey** [comment]
@jspaleta is this still relevant? We've made a number of improvements to resource export/import since 2018 😅 so I wonder if we can close this. ☺️
