### ISSUE TITLE
Agent RFE: check ldd version for musl vs glibc vs uclibc on linux.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2136]
## Problem:
Musl, uclibc and Glibc dynamic linkers are not compatible. 

## Impact:
Assets built on stock Alpine which make use of dynamic libraries won't work on stock Ubuntu and vice versa (unless you make some additional effort to prep the system with musl-glibc compat wrappers) which is out of scope for asset payloads.

## Context 
Musl is an alternative MIT licensed implementation of libc, and is now being used regularly for containerized workloads. (Alpine linux uses musl and is now the default container linux for Docker)

## Proposed Solution
Have agent test running environment to see if running glibc, musl, uclibc, or other and pre-populate an entity attribute indicating detected libc type.  Use this automatically populated attribute in asset filter along with platform and cpu arch to correctly select between linux-glibc-x86_64 and linux-musl-x86_64 asset tarballs.  

## Detailed Strawman Proposal:
Have agent call `ldd --version` and check output for either case insenitive "musl" or "gnu" substring and set "detected_libc_type" to "musl", "gnu" or "unknown"  

### Notes
It is possible to have agent call `getconf GNU_LIBC_VERSION` to test to see if its a gnu libc, but there's no affirmative check for musl in this manner. And since the impact here is I think strictly a dynamic linking issue, its more correct to check the ldd version for matching substring for known libc implementations.

**Comment by calebhailey** [comment]
+1

Related: https://gist.github.com/calebhailey/ed581beb1997892f63637da45263516f

**Comment by calebhailey** [comment]
@jspaleta I think we can close this one! Implemented in #3622 (released in 5.19.0) and fixed on Alpine in #3682 (released in 5.19.1).
