### ISSUE TITLE
Make root urls return 200 on the api and agent webservices

### ISSUE THREAD

**Issue by jkerry** [sensu/sensu-go#2144]
Layer 7 load balancers are created when a k8s Ingress resource is created in google cloud platform kubernetes engine. Ingress endpoints are provisioned with a health check at the / route for every service and expects a 20* http return code. This is non-negotiable and any configuration change is squashed. The API services hosted on 8080 and 8081 do not return a 200 status code on the / root path.

## Expected Behavior
it would be nice if curl http://address:8080/ and http://address:8081/ would return a 200 status code

## Current Behavior
```
[12][default:/src:0]# curl -I localhost:8080/
HTTP/1.1 404 Not Found
Date: Mon, 08 Oct 2018 06:04:58 GMT
Content-Length: 31
Content-Type: text/plain; charset=utf-8

[13][default:/src:0]# curl -I localhost:8081/
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 08 Oct 2018 06:05:08 GMT
Content-Length: 21
```

**Comment by palourde** [comment]
I believe it's possible to specify a readinessProbe according to https://stackoverflow.com/questions/44584270/how-to-get-a-custom-healthcheck-path-in-a-gce-l7-balancer-serving-a-kubernetes-i, which should do the trick!
