### ISSUE TITLE
Spike - Communication between clusters. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2148]
This spike is to investigate how to architecture a solution for communication between multiple clusters (mostly for checks).

**Comment by palourde** [comment]
I feel like we could definitely learn some lessons from Kubernetes federation stuff. Here's some resources:

- Introduction to K8s v1 federation: https://coreos.com/blog/kubernetes-cluster-federation.html
- Concept overview: https://kubernetes.io/docs/concepts/cluster-administration/federation/
- v1 federation proposal: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multicluster/federation.md
- How Openshift does it (and why they didn't use K8s federation): https://blog.openshift.com/deploying-openshift-applications-multiple-datacenters/
- The v2 implementation: https://github.com/kubernetes-sigs/federation-v2

**Comment by nikkiki** [comment]
Design doc: https://docs.google.com/document/d/15HtSr-zmPBRPQe_LrAy30-vem9k5wCO8jk58MPv4UP8/edit?usp=sharing

**Comment by nikkiki** [comment]
Closing this spike and opening an epic placeholder in sensu-enterprise-go.
