### ISSUE TITLE
Internal type versions

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2155]
Rather than having to keep versioned api dependencies in sync across the sensu-go codebase, it makes sense to have internal versions that we rely on (except where we explicitly must do things like convert between external type versions).

The apis/{group}/{version} packages would then only include conversions and/or any supporting stuff for versioned objects.

**Comment by grepory** [comment]
@ccressent @palourde WDYT

**Comment by ccressent** [comment]
Is that internal version the canonical version we previously talked about? Then yes.

**Comment by grepory** [comment]
Well, sort of.

I had confused the idea of canonical versions and internal versions originally.

The canonical version of an object is a normalized version--which may mean there's no real change. For example, if the type includes a list (e.g. rules include a list of roles), we may want to sort those roles. That's canonicalization / getting the canonical version of the object so that it's always the same when we store/retrieve it.

The internal version is what I _originally_ described as the canonical version of the types.

If we do want this, then we'll have to talk about how people use the external versioned APIs from within Golang. This may mean a separate package / git repository where the versioned APIs are kept. We will need to figure out how to go about exposing and maintaining those versioned APIs in a way that's consistent and generally useful to us and third parties.

I don't know if this is necessarily a blocker for versioned APIs. We could go ahead and setup the conversion helpers as I described in the original comment, and then worry about exposing the Golang versioned APIs later.

**Comment by grepory** [comment]
Yeah. I agree. We're going to setup the internal/ api stuff now.

**Comment by palourde** [comment]
I believe this is solved now!
