### ISSUE TITLE
Next-gen storage key building

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2165]
We need to be able to build keys/paths to objects (both for the REST API and for Etcd). 

Create a uniform interface for determining the path to an object or type based on supplied data.

Given an API request of the following form

`/apis/{group}/{version}/namespaces/{namespace}/{type}/{name}`

When we want to interact with an object or type of object in Sensu, we have to be told:
- API Group
- Version
- Namespace (optional)
- Type
- Name

With that we can generate a REST path or an Etcd path by providing the following additional information:

- Whether or not the type is namespaced
- The prefix
  - /apis for REST
  - /sensu.io for Etcd
- Is the object versioned?
  - Yes for REST
  - No for Etcd

**Comment by ccressent** [comment]
Related PR: #2170.

**Comment by grepory** [comment]
@ccressent I think 2170 is not related.
