### ISSUE TITLE
Results from checks executed on behalf of a proxy entity do not indicate the agent they executed on

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2179]
## Expected Behavior

For a given check request executed on behalf of proxy entity, it should be possible to determine which agent entity executed the check.

## Current Behavior

Based on event data alone, it is not possible to determine which agent entity executed a check on behalf of a proxy entity.

## Possible Solution

Please note the following solution, which are the result of our 7/21 meeting: 

- Add `processed_by` field to the core.v2/Check type
- Update the Sensu Go agent to set the `processed_by` field to the local entity name when executing a check
- Update the Sensu Go agent events API to set the `processed_by` field to the local entity name when receiving events 

## Steps to Reproduce (for bugs)
1. Configure a check using proxy_request attributes
2. Configure two or more agents to execute check on behalf of the proxy entity
3. Try to determine which agent executed the check by examining event info

## Context

With multiple agents executing checks on behalf of proxy clients, it can be difficult to determine which client is returning unexpected check results due to misconfiguration. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 2.0 beta 4
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by echlebek** [comment]
We need to do some investigation to decide how to best support this. Do we just want the name of the agent entity, or the entire data structure to be available in the event? How should this information be represented in the event? (ie, do we need a new field?)

**Comment by annaplotkin** [comment]
Going  to add a field to check history called agent entity name.

**Comment by calebhailey** [comment]
@jspaleta can you check and see if this was implemented? Do proxy request events have an `agent_entity_name` field?

**Comment by cwjohnston** [comment]
I don't see any evidence this has been implemented as of 6.1

**Comment by portertech** [comment]
We ran into significant performance issue when adding data to check history. Adding flapping state resulted in a ~10%+ performance penalty. Need to revisit.

**Comment by cmccluskey1** [comment]
Would love to see this feature!

**Comment by portertech** [comment]
Recent discussion has us considering a single field to indicate the last agent to execute the check. For example, agent_entity_name.
