### ISSUE TITLE
[Web UI] Event prompts - last executed value can be in the future

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2192]
`Last executed in a few seconds` isn't an accurate representation of when a check was last executed. This value should not be in the future (because English), and it should actually represent the last executed time of the check.

## Expected Behavior
`Last executed just now`, `Last executed 2 minutes ago`, etc...

## Current Behavior
<img width="978" alt="screen shot 2018-10-19 at 10 06 50 am" src="https://user-images.githubusercontent.com/10634078/47236458-145a9700-d391-11e8-8537-7e9f002c0a41.png">

## Possible Solution
Pull the proper value for the check and calculate the time elapsed since now.

## Steps to Reproduce (for bugs)
1. Create some checks running at an interval.
2. Open the dashboard - events page

## Context
Issue found in manual qa - staging environment.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/05af2ca99b4db81a1c20a9cb05a74c7f258db042
* Installation method (packages, binaries, docker etc.): packages deployed from terraform in aws
* Operating System and version (e.g. Ubuntu 14.04): backend: Ubuntu 16.04, dashboard: OSX 10.13.6 (Google Chrome)

**Comment by jamesdphillips** [comment]
I imagine this is caused by drift on either the agent or your local system.

I guess when the delta between the current time on the client and the timestamp the agent gave us is negative we could fallback to zero? But this sort of feels like wallpapering over an issue.

**Comment by annaplotkin** [comment]
I agree with both of these points. 

1. We should file an issue to ensure the agent timestamp is accurate. 
2. In the case that we have just executed a check, we should change the verbiage to 'Last executed just now'.

**Comment by nikkiki** [comment]
I see that the related PR was closed https://github.com/sensu/sensu-go/pull/2295, are we going to be leaving this ticket open for investigation, or is this too risky of a change?

**Comment by dabria** [comment]
I've come across this in my QA on the event details page just now. I think that even if we can't programatically fix our timing issues we could potentially display a better message for this. I am pretty comfortable with Anna's suggestion for wording.

On the event details page, we show this as "Last Seen: _____", so the wording would need to fit both the above case and this case as well.

**Comment by nikkiki** [comment]
@dabria that sounds good! I'll move this ticket back into the backlog.

**Comment by portertech** [comment]
Great opportunity to recommend clock sync with NTP, for Agent and local machines.

**Comment by portertech** [comment]
We should improve our message, accepting future times as a thing.

**Comment by annaplotkin** [comment]
1. Docs issue to make sure we call setting NTP on the agent is a requirement. 
2. Verify that this issue doesn't occur in an env where NTP is set correctly. 
3. If this is just an issue on Staging, create a ticket to update.

**Comment by cwjohnston** [comment]
Opened https://github.com/sensu/sensu-docs/issues/1187 to document time synchronization requirement

**Comment by jamesdphillips** [comment]
I don't think we have seen this in a while, might be safe to say it's a non-issue when NTP is configured properly.
