### ISSUE TITLE
[Web UI] Event detail page - "Last Seen" value incorrect

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2193]
On the event detail page in the section "Check Summary," the entities "Last Seen" value does not appear to be correct, it does not match the entities detail page.

## Expected Behavior
An entities "Last Seen" value is consistent across different pages.

## Current Behavior
<img width="983" alt="screen shot 2018-10-19 at 10 42 10 am" src="https://user-images.githubusercontent.com/10634078/47237006-a616d400-d392-11e8-8dfc-18d75882c520.png">
<img width="983" alt="screen shot 2018-10-19 at 10 42 41 am" src="https://user-images.githubusercontent.com/10634078/47237007-a616d400-d392-11e8-99f4-da588b06fb1a.png">

## Possible Solution
Correct the entities "Last Seen" value on the event detail page.

## Steps to Reproduce (for bugs)
1. Create some checks running at an interval.
2. Open the dashboard - events detail page.
3. Click the entity name and go to the entities detail page
4. Observe different "Last Seen" values

## Context
Issue found in manual qa - staging environment.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/05af2ca99b4db81a1c20a9cb05a74c7f258db042
* Installation method (packages, binaries, docker etc.): packages deployed from terraform in aws
* Operating System and version (e.g. Ubuntu 14.04): backend: Ubuntu 16.04, dashboard: OSX 10.13.6 (Google Chrome)

**Comment by jamesdphillips** [comment]
The value is being pulled from the event. We should probably just remove the line from the card.
