### ISSUE TITLE
[Web UI] Entities page - kebab menu filters

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2199]
QA checklist: "Using kebab menu, can change list filters." The kebab menu only has silence, clear silences, and delete.

## Expected Behavior
The kebab menu has something with filters?

## Current Behavior
<img width="1095" alt="screen shot 2018-10-19 at 11 00 14 am" src="https://user-images.githubusercontent.com/10634078/47239751-07db3c00-d39b-11e8-9657-bc22457576f8.png">

## Possible Solution
Add the missing feature or remove from the QA checklist.

## Steps to Reproduce (for bugs)
1. Open the dashboard - entities page
2. Click the kebab menu
3. Observe silence, clear silences, delete options only

## Context
Issue found in manual qa - staging environment.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/05af2ca99b4db81a1c20a9cb05a74c7f258db042
* Installation method (packages, binaries, docker etc.): packages deployed from terraform in aws
* Operating System and version (e.g. Ubuntu 14.04): backend: Ubuntu 16.04, dashboard: OSX 10.13.6 (Google Chrome)

**Comment by jamesdphillips** [comment]
This is a failure on the part of the checklist, I will update it.
