### ISSUE TITLE
Documentation for the `sensuctl filter set-when` and `sensuctl filter remove-when` commands

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2202]
Task to add documentation for the `sensuctl filter set-when` and `sensuctl filter remove-when` commands.

**Comment by annaplotkin** [comment]
Dependent on #1955

**Comment by grepory** [comment]
Revisiting this after we look at check subdue and time window specification as a holistic feature. We'll rape filter-when into that.
