### ISSUE TITLE
Sensu Metric Format only supports float values

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#2213]
Sensu Metric Format currently only supports float values: https://github.com/sensu/sensu-go/blame/3c3ce064cfa8801297f7be679efcf649394726a6/types/metrics.proto#L30

InfluxDB syntax supports several other data types such as floats, integers, strings, and booleans as metric values: https://docs.influxdata.com/influxdb/v1.6/write_protocols/line_protocol_tutorial/#data-types 

We should consider changing the Sensu Metric Format value type if we want to support all other data types. Perhaps we could store all values as a string, and leave it to the handlers to convert to the appropriate type.

Related: https://github.com/sensu/proposal/blob/master/design/7-sensu-metric-format.md

**Comment by portertech** [comment]
Most time series data stores use a float for value. Influx is an exception. Metric tags can be used to service string values. Tags could also be used to stringify other types and handlers could decode. Closing this one.
