### ISSUE TITLE
[Web UI] Zooming in/out throws a javascript error

### ISSUE THREAD

**Issue by becon-cmichel** [sensu/sensu-go#2215]
Hey, every time zooming in or out the frontend a javascript error message appears and you have to refresh the page. 

## Expected Behavior
Zoom in and out works in every way and every depth as usual. 

## Current Behavior
Every time on every page you get a javascript error.
The error messages vary depending on which page you are.

![bildschirmfoto vom 2018-10-25 16-29-25](https://user-images.githubusercontent.com/9606222/47512879-63b33280-d87d-11e8-859e-11a53b9ef76d.png)
![bildschirmfoto vom 2018-10-25 16-19-24](https://user-images.githubusercontent.com/9606222/47512880-63b33280-d87d-11e8-84f7-3fb9f732eac6.png)

## Steps to Reproduce (for bugs)
1. access the frontend
2. zoom
2.1. press Ctrl & +
2.2. or press Ctrl & -
2.3. or press Ctrl & scroll with mouse wheel
3. press F5 to relaod the zoomed page and go on

**Web UI Stack Trace:**
at `ToolbarMenu/n.handleWindowResize<` (/static/js/main.92a674c2.js:66)
at `later` (/static/js/main.92a674c2.js:66)

## Your Environment
-Server-
Sensu:  sensu-backend - 2.0.0 nightly+20181011-1
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch

-Client-
Browser: Firefox  63.0+build2-0ubuntu0.16.04.2
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

:-)

**Comment by jamesdphillips** [comment]
Thanks for reporting this @becon-cmichel. This bug was recently fixed in #2211; updating to the latest nightly should alleviate the issue.
