### ISSUE TITLE
Add labels/annotations to Checks, Handlers, Mutators, and Extensions

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2244]
Labels and annotations are map[string]string that can be used to add metadata to objects, allowing programmatic interaction with Labels (e.g. labels can be accessed inside of filters) within Sensu, and interactions with annotations through the plugin/extension system.

**Comment by portertech** [comment]
@grepory should we also be adding to Filters?

**Comment by grepory** [comment]
Filters have extended attributes?
