### ISSUE TITLE
Interactive CLI - Core Workflow

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2265]
Background: 
Historically, the interactive CLI was built by hand and to serve the purpose of being a learning tool. In the time since its inception, the scope of it has grown introducing a maintenance and usability burden. Currently we have many fields that need to be confirmed with the checks. Any time a new feature is introduced, we have to manually update the interactive CLI to avoid breakage in the tool. 

Proposal going forward: 

1. Display a copy of the yaml template to the user for each resource individually. 
2. Allow user to modify the copy of the yaml template. 
3. The modified document will be sent via sensuctl create to the Sensu Backend. 

Implementation specification: 

1. For a given resource, serialize the resource's fixture to a temporary file. 
2. The template document format displayed will be compatible with the format sensuctl create expects. 
3. Invoke the editor defined by the user's EDITOR environment variable.
4. When the editor is closed and the file is saved, create the edited resource in the same way that sensuctl create does. 
5. TBD details - Instrument with Tessen. 

Potential implications: 
- Maintenance will be required if any new data types are introduced into the system. 
- We will not need to do maintenance if the fields are updated or removed.

**Comment by echlebek** [comment]
It would be easy to do this with `sensuctl edit`.

**Comment by echlebek** [comment]
I've pushed a patch to `sensuctl edit` that adds a flag, `--blank`, which allows the user to edit a blank copy of any resource.

No additional maintenance (beyond bugfixes) will need to be done for the feature, even if we add a type.
