### ISSUE TITLE
Agentd should have authz for agent users' access to the namespace they're putting events into (based on event.entity.namespace)

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2269]
When agentd handles events, we should ensure that we're only allowing it to create events namespaced within the entity's namespace. 

The default agent user should only allow access to the default namespace (imo, but we could have it have global access to all namespaces).

**Comment by palourde** [comment]
We're now tracking this via https://github.com/sensu/sensu-go/issues/2811
