### ISSUE TITLE
Round robin scheduling on proxy checks is inconsistent

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2279]
Create 3 proxy checks to be scheduled in a round robin fashion: https://github.com/sensu/sensu-staging/blob/0856914c2c17eef6978c07d0d218f57ed8350b4b/resources/resources.json#L474-L573. Sometimes, check `passing-round-robin-1` is not executed (though it is created) and entity `proxy-round-robin-1` is not created.

**Comment by annaplotkin** [comment]
@nikkiki Did this bug get addressed with the new implementation of round robin?

**Comment by nikkiki** [comment]
Yup, we verified this during QA for our 5.3.0 release. Closing this out 😄
