### ISSUE TITLE
Centralize configuration-based behavior of the agent.

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2286]
The configuration of the agent is currently mixed between Viper and the Agent itself. E.g.:

https://github.com/sensu/sensu-go/blob/5fc90fe1cf517aac8a7974a82953f7cbc910b747/cmd/sensu-agent/start.go#L176-L182

vs.

https://github.com/sensu/sensu-go/blob/5fc90fe1cf517aac8a7974a82953f7cbc910b747/agent/agent.go#L459-L461

We should either respond to configuration where we're using an agent (e.g. in a `main()`) or respond to it when creating / starting an agent in the `github.com/sensu/sensu-go/agent` package.

**Comment by grepory** [comment]
https://github.com/sensu/sensu-go/blob/5fc90fe1cf517aac8a7974a82953f7cbc910b747/cmd/sensu-agent/start.go#L176-L182

**Comment by calebhailey** [comment]
@palourde can you comment on whether this is still relevant? Thanks!

**Comment by palourde** [comment]
No longer relevant, closing!

**Comment by calebhailey** [comment]
Nice!
