### ISSUE TITLE
sensu-cli command to create asset archive

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#229]
Golang includes tar, so have a thing that creates the tar and associated checksum for users in the CLI.

**Comment by calebhailey** [comment]
It appears that #244 was a PR to add support for creating an asset _resource_, but this issue actually describes creating an asset _archive_ (the actual tarballs). Just FYI. 

In related news, this has been handy for the same purpose: https://github.com/calebhailey/sensu-asset-utils
