### ISSUE TITLE
Reduce the number of round-trips to etcd for keepalive handling

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2290]
From #1347

> If an event arrives with a check with the name "keepalive," this event is a `keepalive` event. In agent sessions, we also tag these events so that they're handled differently from the rest of the events, instead of inspecting the contents of the event. We do not treat events sent to the API the same way--I believe this is a bug (see #2288). Keepalives are first fed through keepalived. This is a somewhat expensive process as well. It requires first a get to see if we need to register the entity, then a call to etcd to send a keepalive keeping our session alive, then we get a lease and send a put, then we attempt to delete a failing keepalive event, and then we update the entity's last seen timestamp. All said, handling a single keepalive event requires (I think) 5 round-trips to Etcd.

**Comment by calebhailey** [comment]
@palourde can you comment on whether this is still relevant? I know we've implemented a number of improvements around etcd reads/writes, so maybe we've already done this?

**Comment by palourde** [comment]
@calebhailey I believe the fact that keepalives are handled differently than "normal" events is still the case, that being said I believe we greatly reduced the number of round-trips made to etcd, so I'm gonna close this one.

**Comment by calebhailey** [comment]
Excellent!
