### ISSUE TITLE
grpc extension regression

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2294]
Steps to reproduce:
1. Checkout beta 3 and build/run `sensu/sensu-go/rpc/extension/example/main.go` and all sensu binaries
2. Create an extension on that port, ex:
```
sensuctl extension register 'handle-extension' '127.0.0.1:31000'
```
3. Create a check that gets handled by the extension, ex:
```
sensuctl check create grpc-handle --interval 10 --subscriptions ext --command echo 'grpc' --handlers handle-extension
```
4. Observe the successful extension logs
5. Checkout beta 4 and build/run `sensu/sensu-go/rpc/extension/example/main.go` and all sensu binaries
6. Use the same extension and check resources
7. Observe the following panic when the extension receives its first event: [panic.txt](https://github.com/sensu/sensu-go/files/2551132/panic.txt)

Regressed @ https://github.com/sensu/sensu-go/commit/585370d1567b28f119c8c79dcc9d0ae1f5fec62e#diff-da0fb2ac892daab4810fb781272173c1

**Comment by palourde** [comment]
I'm gonna close this issue since extensions are no longer a thing.
