### ISSUE TITLE
Proposal: separate domain types from wire types and internal types

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2297]
Relates to #2155 

Introduction
----------------
Currently all project-wide datatypes in sensu-go are contained in the `github.com/sensu/sensu-go/types` package. These types are specified in `.proto` files and compiled into Go source files with a protocol buffer compiler. This proposal advocates for changing this approach, as it has a number of inherent issues.

Definitions
---------------
For the sake of discussion, some terms used throughout this proposal are defined here.
* _Domain types_ are types that we use to represent first-class product concepts in Sensu. They are responsible for representing business domain data and business domain logic that defines how Sensu works as a product. _Domain types_ are by necessity exposed to users, who are generally responsible for managing instances of them in a running Sensu installation.
* _Wire types_ are types that are involved in serialization and deserialization. They are sent across networks and stored on the filesystem as streams of bytes. This includes protobuf, yaml, and json.
* _Internal types_ are project-wide datatypes that do not fit the above two categories. They can be concrete or abstract.

Problems
-------------
Unifying our domain types with our wire types has a number of issues:
* The types package, as a Go package, is poorly documented and exposes protobuf implementation details.
* We cannot work with certain Go-specific datatypes as part of our domain types. This is restrictive, and makes designing our domain types more difficult than it otherwise would be. (Example: impossible to put concurrency primitives, generic maps, interface values or function values into our domain types.)
* We cannot include unexported fields our domain types, making encapsulation impossible for these types.

The `types` package also includes types that are not domain types, but rather, implementation details. This includes interfaces that are used across the project. This also causes issues:
* Users reading automatically generated documentation will have difficulty distinguishing between internal and external types.
* Allowing users to access internal types could result in breakage for some customers, as we will inevitably wish to change these types in the future.

Proposed Solution
-------------------------
I propose that we have separate domain and wire types - even if the domain and wire types are coincidentally identical - for the purposes of versioning, documentation generation, and encapsulation. This pattern has been adopted by many projects that use protocol buffers - including etcd. By creating and enforcing these separations, we could solve the problems described above.

Under this system, we could go from having `.proto` files being the source of truth to having `.go` files be the source of truth for our datatypes.

Concretely, we would define an interface that would represent the data requirements of each domain type, and then provide wire types that implement that interface. The wire types would be encapsulated within the data-provider interface, within the domain types. Whew, that's a mouthful. Let me illustrate with a concrete example.

Here is an example transition for a datatype. Currently we have:
```
// check.pb.go
package types

type Check struct {
  // fields
}
```

This would become, under the proposal:

```
// check.go
package sensu

type CheckData interface {
  GetCommand() string
  GetInterval() int
  // ...
}

type Check struct {
  data CheckData
  // other fields, for scheduler state, concurrency primitives, whatever we might need.
}
```
```
// generated.pb.go
package rpc

// Check implements sensu.CheckData
type Check struct {
  // Data fields
}

// generated protobuf methods
func (c *Check) Marshal() ([]byte, error) {
}
```
```
// check.go
package json

// Check implements sensu.CheckData
type Check struct {
  // Data fields, annotated appropriately for REST documentation generation
}

// File includes json-specific information and logic, Marshalers, Unmarshalers, etc.
```

Developers would deserialize into wire types, and then add them to domain types. Then, the domain type would be handed over to other components of the system. If we wish to create versions of types, or change the domain type in a way that is incompatible with the wire type, we can author custom conversions, or use multiple data provider interfaces. For example:

```
package sensu

type Check struct {
  datav1 v1.CheckData
  datav2 v2.CheckData
}
```

Another benefit of this solution is that adding new [ports and adapters](http://www.dossier-andreas.net/software_architecture/ports_and_adapters.html) can be done without disturbing the domain types. For instance, if we wish to add support for a new kind of database, we can do that cleanly without making any changes to the `sensu` package.

Documentation
--------------------
Once we have consistently separated packages for wire types, wire-specific documentation could be generated for each package. We could use different documentation generators for different wire types. For instance, the `json` package could have REST documentation, and the `rpc` package could just use `godoc`.

Cost to implement
-------------------------
Implementing this change would have a moderate cost in terms of developer effort. The tasks include, but are not limited to:
* Project-wide refactoring of type names.
* Addition of wire-specific packages and internal packages.
* Creation of new domain types.
* Integrating go-to-protobuf so that we don't have to write .proto files (optional, but nice to have)

I estimate the change could be fully implemented within 10 full-time days, including review and QA, by a single developer. That is, a single developer, without additional responsibilities, working at 80% capacity, for 10 days. Given that Sensu developers have other responsibilities, and that making large architectural changes can be hindered by other concurrent efforts, I estimate that a reasonable wall-clock length of the project would be one month from start of work to ship date.

Known Issues
-------------------
There are no known technical issues with this approach (yet).

Versioning
--------------
I believe this proposal, or a minor modification of it, is compatible with our vision for a versioned API. Under this proposal, we would simply treat new versions as different wire types, and house them in another package. We could create different versions of the data interfaces (v1.CheckData vs v2.CheckData)

Scheduling considerations
-----------------------------------
This proposal is reasonably backwards-compatible and we should be able to do it after GA.

Conclusion
---------------
While creating special types for wire protocols is extra work, we reap benefits by limiting the responsibilities of our domain types and our wire types. Adding new concepts to the system is also more work, but that work can be done in a piecemeal way, over multiple releases. Adding versions dovetails with the proposal. Generated documentation will be clean of unrelated concepts and functionality.

**Comment by palourde** [comment]
We moved everything to a versioned API, but we do not have interval versions. I believe what we have now is working okay and we can always move a new proposal if we have some specific needs!
