### ISSUE TITLE
"Live" button in dashboard difficult to see in dark mode

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#2301]
## Expected Behavior
The "Live" button should probably be in white

## Current Behavior
The button/text is black:

![dashboard-dark](https://user-images.githubusercontent.com/898627/48155019-ab7b8600-e28f-11e8-9239-f1f11f628695.png)

## Possible Solution
Change to white in dark mode

**Comment by dabria** [comment]
While we no longer have the live button, this is still relevant for the "reset" button which sits there now, and the "new" button which appears on the silences list
