### ISSUE TITLE
Generate CLI docs using Cobra doc tool

### ISSUE THREAD

**Issue by apaskulin** [sensu/sensu-go#2307]
## Expected Behavior

Docs for sensuctl, sensu-backend, and sensu-agent are automatically generated from the code.

## Current Behavior

Docs for Sensu Go CLI tools are created manually.

## Possible Solution

Use https://github.com/spf13/cobra/blob/master/doc/md_docs.md to generate Markdown docs.
The ideal format for these docs would be similar to https://docs.sensu.io/sensu-go/5.0/reference/agent/#configuration, but I'm happy to work with and iterate on whatever format we can get from the Cobra tool.

**Comment by palourde** [comment]
Don't think it's gonna happen anytime soon, so I'm gonna close this issue.
