### ISSUE TITLE
Hard to use sudo with assets

### ISSUE THREAD

**Issue by blufor** [sensu/sensu-go#2315]
## Expected Behavior
One should be able to configure `/etc/sudoers` so that some of the checks can be run with elevated privileges, like so:
```
sudo check-systemd-unit -u ssh.service
```

## Current Behavior
It's currently hard to configure sudoers, because of the necessity to change the `secure_path` variable in config management system every time the asset is updated. (The path contains the checksum of the asset)

## Possible Solution
Replacing checksum in the directory name with the asset name

**Comment by ninjasloth22** [comment]
Having a named asset dir would also help with using env_vars like PYTHONPATH in a check, where an asset has modules that need importing.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/sensu-go-plugin-distribution-model/1724/4
