### ISSUE TITLE
Feature Request: K8s-like contexts or AWS cli-like sections

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#2316]
In using Sensu Go, I've created several clusters that I would love to be able to switch back and forth between. Currently, I have to reconfigure Sensu every time in order to switch. Would it be possible to implement contexts/sections in my config so that I can make switching between clusters a non-issue?

**Comment by calebhailey** [comment]
I would also love this! In the interim, my workaround has been to switch sensuctl configs as I change directories from one project to another using `direnv`. <3 https://direnv.net/  

Upon `$ cd /projects/customer/acme-inc` the local .envrc updates sensuctl config to the acme-inc backend, namespace, user, tls cert, or all of the above!).

**Comment by DoctorOgg** [comment]
I would love to have this feature, as a have a local sense-go running at home for testing and others for work and some volunteer work, it would be nice to have my workstation setup to talk to all of them without games to switch out configs. Please prioritize this feature.

**Comment by ichilton** [comment]
I would really like this too!

**Comment by tarunptala** [comment]
+1

**Comment by calebhailey** [comment]
Quick update on this issue, for those of you who are following along at home: we're still working on longer-term plans around a first-class implementation here (e.g. something similar to `kubectl config use-context` switching). In the shorter/immediate term we're also considering a stopgap proposal to add `sensuctl` support for reading a single environment variable: `$SENSU_CONFIG_DIR`. This would enable "context switching" using simple OS primitives like environment variables. 

In the interim, the following workaround assumes familiarity with [`direnv`](https://direnv.net/) and should give you a preview of what to expect if we simply add support for the `$SENSU_CONFIG_DIR` environment variable: 

1. Create a wrapper script for `sensuctl`: 

   ```
   #!/bin/sh
   /usr/local/bin/sensuctl ${@} --config-dir ${SENSU_CONFIG_DIR}
   ```

   _NOTE: if we add `sensuctl` support for reading `$SENSU_CONFIG_DIR`, you wouldn't need this wrapper script._

2. Configure an alias or modify your `$PATH` to call this script. You can do this in your user profile, or add the following line to your `.envrc` files (again, assumes familiarity with tools like [`direnv`](https://direnv.net/)): 

   ```
   export PATH=/path/to/wrapper/bin/:$PATH
   ```

   _NOTE: same comment as above, if/when we add support for `$SENSU_CONFIG_DIR`, you won't need to modify your path._

3. Add `$SENSU_CONFIG_DIR` to your `.envrc` files! 

   Example file tree: 

   ```
   sensu/
   ├── us-central-1/
   │   ├── .envrc
   │   └── .sensu
   │       ├── cluster
   │       └── profile
   ├── us-east-1/
   │   ├── .envrc
   │   └── .sensu
   │       ├── cluster
   │       └── profile
   └── us-west-1/
       ├── .envrc
       └── .sensu
           ├── cluster
           └── profile
   ```

   Now `sensuctl` will automatically switch "contexts" (i.e. which sensu-backend you're connected to) as you switch directories! 

4. Profit? 😅   

I hope this helps!

**Comment by calebhailey** [comment]
Hello, all :wave: sorry for the radio silence here. 

We did manage to sneak in a related `sensuctl` enhancement in 6.3.0 (https://github.com/sensu/sensu-go/pull/4256) so you can now `sensuctl --api-url xxx --api-key xxx entity list` without a pre-configured sensuctl. The `--api-url` and `--api-key` flags will also override your local `sensuctl` configuration. 

We did not add support for the `SENSU_API_KEY` environment variable in the 6.3.0 release (an omission on my part), so we'll get that remedied in an upcoming release, along with support for `SENSU_CONFIG_DIR` (as outlined in this issue). These environment variables, along with the ability to seed new clusters with an API Key (https://github.com/sensu/sensu-go/issues/4162), should help simplify "multi cluster management". These improvements should land in 5.5.0 or 5.6.0. 

We are still interested in a first class "contexts" command (or similar) for Sensu Go in the long term, but #4256 and the related upcoming enhancements should make multi cluster management significantly easier in the interim.

**Comment by c-kruse** [comment]
:) TODONE! Thanks @fguimond for adding this about a year ago: https://github.com/sensu/sensu-go/pull/4393

This has been functional since 6.4.3 and appears to work rather well.
