### ISSUE TITLE
sensuctl update check and sensuctl create check parameter behave differently

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#2318]
## Expected Behavior
When using `sensuctl check update`, it is expected that I can do the same things I could with `sensuctl check create` with flags.

## Current Behavior
There is at least one scenario where I can not pass a value using `sensuctl check update`:

This works:

```
sensuctl check create echotest --command 'echo $PATH' --subscriptions sensu-app --interval 10
```

And then an entity subscribed to `sensu-app` will output its PATH:

<img width="1088" alt="screen shot 2018-11-12 at 4 00 38 pm" src="https://user-images.githubusercontent.com/19964713/48375081-c5a0d400-e694-11e8-961c-d13fc334cfc0.png">

If I run `sensuctl check update echotest` and update the command with `'echo $PATH'`, the command Sensu attempts to run is `'echo $PATH'` instead of `echo $PATH`:

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/19964713/48375106-df421b80-e694-11e8-9cc2-04cc3618e975.png">

Using `echo $PATH` does not work either, as the local shell passes it's path value.
Using `echo \$PATH` does not work either, giving a command not found error as well.

## Possible Solution
I have no direct input on an actual possible solution as my build experience is limited and my Go experience is nil.

If I have other commands with characters that a shell will interrupt, I will have to delete and re-make the check, rendering the update option useless in some cases.

It would be great to be able to make the interactive prompt as close as possible to the command line flags or JSON file ingestion.

If that is not possible to do and we need some sort of escaping, we'll need instructions to document that, preferably with all characters that can be interpreted by a users shell that runs `sensuctl`.

## Steps to Reproduce (for bugs)
1. Create a check using `sensuctl check create echotest --command 'echo $PATH' --subscriptions sensu-app --interval 10`
2. Observe the desired output.
3. Run `sensuctl check update echotest`
4. On the interactive prompt, for the line `Command` add `'echo $PATH'`
5. Observe that Sensu is trying to run the command `'echo $PATH'`.

## Your Environment

* Sensu version used:
  * sensuctl version 2.0.0-beta.5-5#31bfb4b
  * sensu-agent version 2.0.0-beta.7-7#0ad392d
  * sensu-backend version 2.0.0-beta.7-7#0ad392d
* Installation method (packages, binaries, docker etc.): Sensu install documentation.
* Operating System and version: OSX 10.14.1.

**Comment by palourde** [comment]
This is a limitation of the interactive mode. We are now trying to move away from this and it should be avoided as much as possible. The same thing can now be accomplished with `sensuctl check set-command echotest 'echo $PATH'`.
