### ISSUE TITLE
sensu check update Metric Format defaults to nagios_perfdata

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#2319]
## Expected Behavior
I'd expect `sensuctl check update`'s `Metric Format` to default to none.

## Current Behavior
When using `sensuctl check update`, `Metric Format` defaults to `nagios_perfdata`. 

## Possible Solution
Make it default to none.

Reasons:
1.) We don't know what metric format users will be using, so choosing none seems like the best UX.
2.) Not all checks will be metrics as well.

## Steps to Reproduce (for bugs)

1. Run `sensuctl check update` on a check.
2. Move through the prompts.
3. At `Metric Format`, observer:
```
❯ nagios_perfdata
  graphite_plaintext
  opentsdb_line
  influxdb_line
  none
```

## Your Environment

* sensuctl version 2.0.0-beta.5-5#31bfb4b

**Comment by calebhailey** [comment]
This was fixed in #2030 🎉
