### ISSUE TITLE
Use kind instead of type in Wrapper

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2320]
The Sensu Wrapper (https://github.com/sensu/sensu-go/blob/master/types/wrapper.go) needs to use the `kind` attribute instead of `type`.

**Comment by nikkiki** [comment]
Thanks for filing this! This reminded me of `type` in handlers. I'll look for an issue and file one if there's not one already!

**Comment by nikkiki** [comment]
We decided in sprint planning that we will not target this change for beta 8, ga, or otherwise.
