### ISSUE TITLE
[WebUI] update camelCase fields with snake_case

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2340]
Breaking changes in the backend have introduced some new issues on the frontend. Variable names now match API naming, so fields that were previously camelCased should be updated to snake_case.

**Comment by nikkiki** [comment]
It is unclear at this time what the impact this has. Leaving this open to be investigated, but not a blocker for the release.

**Comment by grepory** [comment]
@10xjs @dabria or @jamesdphillips -- can you look into this and see if it's still an issue (at your leisure)?

**Comment by jamesdphillips** [comment]
not at issue in the foreseeable future
