### ISSUE TITLE
Missing entity class flag for sensuctl entity update

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#2343]
## Expected Behavior
Should be able to specify `--entity-class` when running `sensuctl entity update`.

## Current Behavior
The `--entity-class` flag does not exist for the `sensuctl entity update` subcommand.

**Comment by nikkiki** [comment]
As sensuctl stands now, the update command is only available in `interactive` mode. But we should definitely discuss UX around changing that.

**Comment by echlebek** [comment]
We have much more general ways of handling this now, so I'm going to close this issue.
