### ISSUE TITLE
Improve array searching (previously IN operator) for javascript filters

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2348]
Currently filter authors and frontend users have to issue queries like
```
subscriptions.indexOf("metrics") >= 0
```

This is a bit obtuse, so let's see if we can find a better way of providing support for this.

**Comment by jamesdphillips** [comment]
We could include a polyfill for the `includes` method.

With the modular approach [core-js](https://github.com/zloirock/core-js/tree/master/packages/core-js) takes we could pick and choose percisely which features we would like to add, while avoiding any potential bloat.

**Comment by echlebek** [comment]
I'm not sure we could use core-js directly, but we could definitely harvest some of its functionality.

**Comment by annaplotkin** [comment]
This should be considered a larger discussion around polyfill.
