### ISSUE TITLE
Label redaction differs between sensuctl and log output

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#2349]
Redaction is not working correctly since the switch from extended attributes to labels and behaviour differs between `sensuctl entity list` output and log output.

## Expected Behavior
In both `sensuctl entity list` output and log output, the `ec2_access_key` label's value should show as `REDACTED` and the `secret` label's field should show as `P@ssw0rd!`.

## Current Behavior
When using the following labels:
* `ec2_access_key` with a value of `asdf1234`
* `secret` with a value of `P@ssw0rd!`

and the `redact` attribute set to `["ec2_access_key"]`

`sensuctl entity list --format json` shows the `ec2_access_key` label as an empty string and the `secret` label as `REDACTED`.

and log output shows the `ec2_access_key` label as `REDACTED` and the `secret` label as an empty string.

**Comment by nikkiki** [comment]
I just reproduced this issue on GA, however, the behavior is consistent across logging redaction and entity output.

`ec2_access_key` gets redacted:
```
journalctl -u sensu-agent.service -f | grep '\\"ec2_access_key\\":\\"REDACTED\\"'
```

`secret` logs an empty string, not `P@ssw0rd!` as expected:
```
journalctl -u sensu-agent.service -f | grep '\\"secret\\":\\"P@ssw0rd!\\"'
```

see `labels` below equals: `\"labels\":{\"ec2_access_key\":\"REDACTED\",\"secret\":\"\"}`
```
Dec 07 00:36:33 ip-10-0-1-147 sensu-agent[8707]: {"component":"agent","level":"debug","msg":"sending message","payload":"{\"timestamp\":1544142993,\"entity\":{\"entity_class\":\"agent\",\"system\":{\"hostname\":\"ip-10-0-1-147\",\"os\":\"linux\",\"platform\":\"ubuntu\",\"platform_family\":\"debian\",\"platform_version\":\"16.04\",\"network\":{\"interfaces\":[{\"name\":\"lo\",\"addresses\":[\"127.0.0.1/8\",\"::1/128\"]},{\"name\":\"eth0\",\"mac\":\"0a:c8:19:95:46:c4\",\"addresses\":[\"10.0.1.147/24\",\"fe80::8c8:19ff:fe95:46c4/64\"]}]},\"arch\":\"amd64\"},\"subscriptions\":[\"rbac\",\"round-robin\"],\"last_seen\":1544142450,\"deregister\":false,\"deregistration\":{},\"user\":\"agent\",\"redact\":[\"ec2_access_key\"],\"metadata\":{\"name\":\"staging-agent-2\",\"namespace\":\"devops\",\"labels\":{\"ec2_access_key\":\"REDACTED\",\"secret\":\"\"}}},\"check\":{\"command\":\"echo 'sending check to mutator with asset'\",\"handlers\":[\"handler-with-mutator\"],\"high_flap_threshold\":0,\"interval\":10,\"low_flap_threshold\":0,\"publish\":true,\"runtime_assets\":[],\"subscriptions\":[\"rbac\"],\"proxy_entity_name\":\"\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":0,\"timeout\":0,\"round_robin\":false,\"duration\":0.000707465,\"executed\":1544142993,\"history\":null,\"issued\":1544142993,\"output\":\"sending check to mutator with asset\\n\",\"status\":0,\"total_state_change\":0,\"last_ok\":0,\"occurrences\":0,\"occurrences_watermark\":0,\"output_metric_format\":\"\",\"output_metric_handlers\":[],\"env_vars\":null,\"metadata\":{\"name\":\"check-with-mutator\",\"namespace\":\"devops\"}},\"metadata\":{\"namespace\":\"devops\"}}","time":"2018-12-07T00:36:33Z","type":"event"}
```

We are expecting a label with `secret` to display the key. Although it is defined as a default redact field
https://github.com/sensu/sensu-go/blob/e3421f7ed050bfb3310f83a28aed5b9d85b4be64/api/core/v2/entity.go#L28-L29
it looks like we ignore the default fields if labels/annotations are defined
https://github.com/sensu/sensu-go/blob/e3421f7ed050bfb3310f83a28aed5b9d85b4be64/api/core/v2/entity.go#L54-L56

**Comment by ccressent** [comment]
After quite a bit of experimentation, I've boiled down this issue to a simple YAML configuration syntax error. Here is the relevant bit of agent configuration in the environment in which the issue was observed:

```
labels: 
  ec2_access_key:
    - "P@ssw0rd"
  secret: 
    - "P@ssw0rd"
```

The subtlety here is that `labels` is meant to be a collection of key:value pairs. In YAML, as defined above, `labels` is a collection of key:collection!
Here is the correct way to define those labels:

```
labels: 
  ec2_access_key: "P@ssw0rd"
  secret: "P@ssw0rd"
```

Label redaction then works correctly and as expected!
