### ISSUE TITLE
sensuctl filter create - non user friendly error message

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2350]
When creating a filter, if the filter name is already in use, `sensuctl` replies with a rather cryptic error message.

## Expected Behavior

The client gives a useful and clear error message.

## Current Behavior
```
$ sensuctl filter create my-filter -a deny -s "true"
Error: {"error":"my-filter","code":3}
```

## Steps to Reproduce (for bugs)

Try to create a filter with a name that is already in use:
```
$ sensuctl filter create my-filter -a deny -s "true"
OK
$ sensuctl filter create my-filter -a deny -s "true"
Error: {"error":"my-filter","code":3}
```

## Your Environment

* Sensu version:
```
$ sensuctl version
sensuctl version 2.0.0-beta.8-8#c07579c, build c07579c0b20f5f5e12788fb0704c3a9138882b58, built 2018-11-15T18:16:45+0000
```

**Comment by palourde** [comment]
This is still happening:

```
$ sensuctl filter create my-filter -a deny -s "true"
Error: my-filter
```

**Comment by echlebek** [comment]
This was resolved at some point and is no longer happening! :tada:
