### ISSUE TITLE
Add a built-in deregistration handler

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#2352]
We should add a built-in deregistration handler which deletes an entity and its related data (e.g. events). We're in the process of adding this in 1.x so this should be considered a feature parity request.

## Expected Behavior
Specify `deregistration` as the `deregistration_handler` for an agent. Stop the agent and have the built-in `deregistration` handler clean up the entity and its associated data.

## Current Behavior
There is no built in `deregistration` handler and as a result, nothing will happen when `deregister` is set to true.

## Possible Solution
Implement the equivalent of https://github.com/sensu-plugins/sensu-extensions-deregistration somewhere in the backend.

**Comment by palourde** [comment]
I believe deregistration is now working as expected!
