### ISSUE TITLE
Cannot configure sensu-cli with beta8

### ISSUE THREAD

**Issue by agrimal** [sensu/sensu-go#2372]
After fresh installation, when trying to configure sensu-cli, i got the following error : 

```
sensuctl configure --url "http://127.0.0.1:8081" --username admin --password 'P@ssw0rd!' -n
Error: unable to authenticate with error: Received an unexpected response from the API
```

And the logs show : 

`Nov 21 09:16:29 oapqsensu01 sensu-backend[8394]: {"addr":"127.0.0.1:49282","component":"agentd","error":"websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header","level":"error","msg":"transport error on websocket upgrade","time":"2018-11-21T09:16:29+01:00"}`

This was working fine with beta7, is there anything i'm missing ?

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): beta8
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): ubuntu 18.04

**Comment by echlebek** [comment]
I haven't seen that particular error from sensuctl before.

Can you confirm the installation is fresh as in from-scratch? That is, there was no existing state data?

**Comment by agrimal** [comment]
Yep i'm installing the sensu cluster in 3 LXD containers so i just destroy and recreate them each time i upgrade beta version. Then i just install sensu-backend and sensu-cli packages.

Here is the file /etc/sensu/backend.yml :
```
---
state-dir: /var/lib/sensu
debug: true
log-level: info
agent-host: 0.0.0.0
agent-port: 8081
dashboard-host: 0.0.0.0
dashboard-port: 3000
etcd-peer-client-cert-auth: true
etcd-trusted-ca-file: /etc/ssl/certs/ca.crt
etcd-peer-trusted-ca-file: /etc/ssl/certs/ca.crt
etcd-peer-cert-file: /etc/ssl/certs/oapqsensu01.crt
etcd-peer-key-file: /etc/ssl/private/oapqsensu01.key
etcd-client-cert-auth: false
etcd-name: oapqsensu01
etcd-initial-cluster-state: new
etcd-initial-cluster-token: sensu-qual
etcd-initial-cluster: oapqsensu01=https://192.168.80.14:2380,oapqsensu02=https://192.168.80.15:2380,oapqsensu03=https://192.168.80.17:2380
etcd-initial-advertise-peer-urls: https://192.168.80.14:2380
etcd-listen-peer-urls: https://192.168.80.14:2380
etcd-listen-client-urls: http://192.168.80.14:2379
```

**Comment by agrimal** [comment]
Ok i found my problem.
I was binding sensuctl on the agent port instead of the API port...
