### ISSUE TITLE
Include agent environment in check execution environment

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2390]
## Expected Behavior

When executing a check, I would expect the agent to search for commands in the PATH provided in the agent process's environment as well as the check and asset environments. In order of preference:

Check environment -> asset environments -> agent environment

## Current Behavior

If a check environment or asset environment are used, then the agent process's environment is ignored. The only time an agent's environment will not be ignored is when a check or asset environment don't exist.

See the documentation for os/exec's Cmd type:

https://godoc.org/os/exec#Cmd

## Possible Solution

When we create the execution context for the check, instead of merging only the check and asset environments, do a second merge with the agent environment.

https://github.com/sensu/sensu-go/blob/759384840bc2509669ada795e8191272ddcc8cff/agent/check_handler.go#L91-L98

## Context

Without including the environment of the sensu-agent process, any system-level configuration of the agent's environment is ignored when sensu provides (what should be) additional execution context in the form of check environments or asset environments.

**Comment by nikkiki** [comment]
It's worth noting that if we want handler and mutator execution to behave the same, we'll also want to add the backend environment to their execution contexts respectively.

**Comment by grepory** [comment]
@nikkiki Thanks! That's a great call out.

**Comment by portertech** [comment]
Agent's env variables are used https://github.com/sensu/sensu-go/blob/c95cbad4045a644276b7fd7b37e7231c47b92c0e/agent/check_handler.go#L172
