### ISSUE TITLE
Windows based Sensu-Agent does not work with Linux based Sensu-Backend

### ISSUE THREAD

**Issue by marcseguin** [sensu/sensu-go#2411]
I installed an testing environment as described in the https://docs.sensu.io/sensu-go/5.0/installation/install-sensu/.
The sensu-backend runs on Linux (CentOS 7.5) while sensu-agents run on Linux (still CentOS 7.5) and Windows (Server 2016)

## Expected Behavior

Windows based sensu-agents can be used.

## Current Behavior

Windows based sensu-agents can not be used.

While Linux based sensu-agents can register on the sensu-backend, the Windows based sensu-agents can't. They do not appear in the dashboard and the sensu server logs error messages:

`Nov 25 15:26:01 srv-mon01.ks.netoffice-kassel.de sensu-backend[1587]: {"component":"keepalived","error":"entity name must not be empty","level":"error","msg":"invalid keepalive event","time":"2018-11-25T09:26:01-05:00"}`

The error messages only appear when the Windows sensu-agent sends something to the sensu-backend.

## Possible Solution

I'm not sure but I believe that the Windows based sensu-agent is too old and transmits wrong data to the sensu-backend. (Maybe related to issue #2308)
The as download offered Windows based sensu-agent is rather old, please provide an up to date one; best would be to includes Windows based sensu-agents into the build and provisioning process.
BTW: The download is not downloaded as executable (.exe) it is necessary to rename it after the download (no big deal but still a small hick-up)

## Steps to Reproduce (for bugs)

Follow the installation guide https://docs.sensu.io/sensu-go/5.0/installation/install-sensu/

### Version Information:
* sensu-agent on Windows: `sensu-agent version 2.0.0-beta.4-4#a05ad41, build a05ad411199077286f49c06629eed4823331176c, built 2018-08-16T21:12:56+0000`
* sensu-backend on Linux: `sensu-backend version 2.0.0-beta.8-8#c07579c, build c07579c0b20f5f5e12788fb0704c3a9138882b58, built 2018-11-15T18:15:08+0000`
* sensu-agent on Linux: `sensu-agent version 2.0.0-beta.8-8#c07579c, build c07579c0b20f5f5e12788fb0704c3a9138882b58, built 2018-11-15T18:16:07+0000`

### Configuration Files
* Backend Configuration file:
```
---
##
# general configuration
##
state-dir: "/var/lib/sensu"

##
# agent configuration
##
agent-host: "[::]" # listen on all IPv4 and IPv6 addresses
agent-port: 8081

##
# api configuration
##
api-host: "[::]" # listen on all IPv4 and IPv6 addresses
api-port: 8080

##
# ssl configuration
##
#cert-file: "/path/to/ssl/cert.pem"
#key-file: "/path/to/ssl/key.pem"
#trusted-ca-file: "/path/to/trusted-certificate-authorities.pem"
#insecure-skip-tls-verify: false

##
# store configuration
##
#etcd-listen-client-urls: ""
#etcd-listen-peer-urls: ""
#etcd-initial-cluster: ""
#etcd-initial-advertise-peer-urls: ""
#etcd-initial-cluster-state: ""
#etcd-initial-cluster-token: ""
#etcd-name: ""

##
# dashboard configuration
##
#dashboard-host: "[::]" # listen on all IPv4 and IPv6 addresses
#dashboard-port: 3000

##
# other
##
#cache-dir: "/var/cache/sensu/sensu-backend"
#config-file: ""
#debug: false
#deregistration-handler: ""
log-level: "debug"

```

* Agent configuration file:
```
---
##
# agent configuration
##

#name: ""
#namespace: "default"
#subscriptions: ""
backend-url:
  - "ws://srv-mon01.ks.netoffice-kassel.de:8081"

##
# authentication configuration
##
#user: "agent"
#password: "P@ssw0rd!"

##
# api configuration
##
#api-host: "127.0.0.1"
#api-port: 3031
#disable-api: false

##
# socket configuration
##
#disable-sockets: false
#socket-host: "127.0.0.1"
#socket-port: 3030

##
# statsd configuration
##
#statsd-disable: false
#statsd-event-handlers: ""
#statsd-flush-interval: 10
#statsd-metrics-host: "127.0.0.1"
#statsd-metrics-port: 8125

##
# other
##
#cache-dir: "C:\ProgramData\sensu\cache\sensu-agent"
#config-file: ""
#deregister: false
#deregistration-handler: ""
#keepalive-timeout: 120
#keepalive-interval: 20
#extended-attributes: ""
log-level: "debug"
#redact: ""

```

### Installation method (packages, binaries, docker etc.):
Following the steps for RHEL/CentOS (backend, agent, sensuctl) and Windows (agent, sensuctl) as described in https://docs.sensu.io/sensu-go/5.0/installation/install-sensu/, which refers to a download of https://storage.googleapis.com/sensu-binaries/2.0.0-beta.4-1/windows/amd64/sensu-agent for the Windows based sensu-agent.

### Operating System and version (e.g. Ubuntu 14.04):
For sensu-backend: Linux CentOS 7.5
For sensu-agent: Windows Server 2016

**Comment by grepory** [comment]
The windows agent we released is quite old. We haven’t yet started building them again, but we do intend to have them available soon (likely this week or next).

**Comment by marcseguin** [comment]
>The windows agent we released is quite old. We haven’t yet started building them again, but we do intend to have them available soon (likely this week or next).

@grepory thx for the quick reply but I’m wondering why the issue is closed before the announced solution is available.
 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by grepory** [comment]
We can reopen it if you like. I will try to provide a timely update when we have windows packaging, but the community Slack, and Twitter are usually more timely channels for updates.

**Comment by marcseguin** [comment]
>We can reopen it if you like. I will try to provide a timely update when we have windows packaging, but the community Slack, and Twitter are usually more timely channels for updates. 

@grepory thank you very much. And thank you for the hint to slack. I will have a look to subscribe there as well.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RamblingCookieMonster** [comment]
for anyone watching this, looks like the binary is available and [linked in docs](https://docs.sensu.io/sensu-go/5.0/installation/install-sensu/), and works without issue.  Wheeee : D

**Comment by marcseguin** [comment]
I got the first connection sucessfully. THX!
