### ISSUE TITLE
PROPOSAL: Simplify Scheduler 

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#243]
## Difficulties

While the current implementation of check scheduling is by no means broken nor deficient in totality; it can be difficult to reason about, test in isolation and requires a separate manager to finagle it's state and lifecycle.

## Proposal

- Rewrite check scheduler into a single runloop that handles publishing _all_ check requests.
- Remove scheduler manager as we no longer have more than one scheduler we have to coddle.
- Given the smallest interval a check can have is a one second we have the runloop loop every ~1 sec.
  - We can determine which checks need to be run based the delta still we last time we looped.
  - So that start time can be deterministic (at least reasonably so) we loop for the first time after a second has ticked past. (eg. if were at 56:15:15.3 we wait until it's precisely 56:15:16.0) `time.Sleep(time.Second - (start.UnixNano() % time.Second))`
  - As a side effect this _likely_ addresses check schedule drift; at worst it should at least be slightly more predictable.
- Prior where we were dependent on scheduler's state manager to notify us of changes, with this solution we simply ask for the current state at the start of the loop, use for the duration of the loop and in any resulting goroutines.
  - Most importantly I think this will help make reasoning about the components of the scheduler daemon simpler, as we no longer have all this interdependent (mutable) state and callbacks.
- To avoid blocking the runloop, fire (and forget) building of the check request and publishing the result. (Also take advantage of these beautiful multi-core machines we all have.)
- There are probably other advantages. (And possibly some drawbacks.)

### Pseudo-code

https://gist.github.com/jamesdphillips/f894cec55f44d7d79398628a0ba3eb50
```golang
//
//   Operations
//
// 1. Sleep until next tick (~1 second.)
// 2. If we've received a message on the 'stopping' channel go to step 8.
// 3. Grab the most recent copy of the state.
// 4. Iterate over the checks contained in our state. After exhausting list go to step 7.
// 5. For each check determine if duration of time until it's next execution is less than our delta. If so go to step 6 else continue iterating.
// 6. Spawn goroutine to build & publish check request. Go to step 4.
// 7. Go to step 1.
// 8. Done.
//

func RunLoop() (chan struct{}) {
  stopping := make(chan struct{})

  go func() {
    for {
      // Sleep until next interval
      start := time.Now()
      delta := time.Second - (start.UnixNano() % time.Second) // (#1) Get delta & wait.
      time.Sleep(delta) // NOTE: Super naive; see incomplete implementation for more robust solution.
      
      switch {
      case <-stopping: // (#2) Check if we've stopped
        return
      default:
        // The state manager's reference to it's state is atomic, so
        // when we ask for the state from the manager we receive a
        // reference to the state at that point in time. The referenced
        // state will never be mutated.
        //
        // Relevant to this block in that we do not have to worry about
        // the state's contents changing underneath us while we iterate
        // over them or when the state is passed along to a goroutine.
        state := stateManager.State() // (#3) Get copy of state

        // (#4) We iterate through all of the known checks
        for _, check := range state.Checks() {
          
          // Using the start time we determine the amount of time until
          // it should be run next. If it less than the delta we know 
          // that it should be run.
          if shouldCheckBeRun(check, start, delta) { // (#5) Check
            
            // Given the check, state atom & message bus, we asynchronously 
            // build and build the check request.
            go publishCheckRequest(check, state, msgBus) // (#6) Defer exec to goroutine
          }
        }
      }
      
      // (#7) Start from the top.
    }
  }()

  return stopping
}
```

## Implementation

See incomplete- not to mention broken and untested- implementation of proposal here: https://github.com/sensu/sensu-go/compare/simplified-scheduler?expand=1#diff-b0b26840959192134d70c094448a6977

**Comment by echlebek** [comment]
I've discussed this a lot with Greg. I think what we really need is to have a scheduler per-agent.

Each scheduler will consume one and only one goroutine. We will implement our own timers.

This is after-GA type work.

**Comment by jamesdphillips** [comment]
After scheduler was largely rewritten in #2766, I think it is fair to punt this.
