### ISSUE TITLE
Determine behavior for when cache-dir is unresponsive

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2441]
Right now, an agent will block until its cache-dir storage responds (see [thread](https://github.com/sensu/sensu-go/pull/2182#discussion_r226040183)). For example, in the event that two agents are attempting to read from the same cache-dir, one will hang indefinitely.
- Is this the behavior we'd like to see, or should a timeout be re-implemented?
- Is there a way to detect _why_ the storage is unresponsive so we can log/handle that?

This can be done after GA. Whatever behavior decided on should be documented.

**Comment by calebhailey** [comment]
@nikkixdev can you confirm if this issue is still relevant? I know we've made one or two improvements to asset management since GA. 😅

**Comment by nikkixdev** [comment]
Looks like at some point we implemented a 60s timeout to open the cache directory.

https://github.com/sensu/sensu-go/blob/70ff30671e2cb4583187a22e98eafd0815fbacb8/asset/manager.go#L44

Closing this out!

**Comment by calebhailey** [comment]
Rad!
