### ISSUE TITLE
Kubernetes Operator for Sensu-Go

### ISSUE THREAD

**Issue by thomasriley** [sensu/sensu-go#2447]
It would be super awesome if there was a Kubernetes Operator for configuring Sensu-Go similar to the [prometheus-operator](https://github.com/coreos/prometheus-operator) for configuring Prometheus.

Typically when using Kubernetes users tend to want to avoid using Configuration Management for managing services running in K8 and it would be great if there was a collection of CRDs for configuring the different components of Sensu-Go and an Operator to make the magic happen automatically. 

I would be more than happy to discuss our use case further if this is of any use. Feel free to message me or DM me on Sensu Slack. I wish I had the Go skills to help kick start this but sadly this one is beyond me at the moment!

Cheers,
Tom

**Comment by grepory** [comment]
This has not been updated in some time, but it exists.

https://github.com/sensu/sensu-operator
