### ISSUE TITLE
Improve agent connection error messages

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2457]
In sensu-agent, when a connection error occurs, we should be writing out what the agent tried to connect to, not just the failure.

See `transport/client.go`.

**Comment by echlebek** [comment]
Refs #2453; in this case, the user misconfigured the agent, but didn't realize it, because we didn't print out the address of the URL we are connecting to in the error message.

**Comment by calebhailey** [comment]
@echlebek can you confirm whether this is still a valid issue? I know we've done some work around agent connections/reconnects lately (too many PRs to link)... so perhaps this is resolved?

**Comment by echlebek** [comment]
I think this was resolved at some point.
