### ISSUE TITLE
Keepalives and check TTLs can stomp on each other's state

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2470]
This is a strange issue we are looking into. Sometimes when all the staging resources are loaded up, keepalives don't seem to fail when an agent disappears.

When a blank database is used, keepalives fail when agents disappear, as expected.

**Comment by echlebek** [comment]
It turns out that check TTL monitors were aliased to keepalive monitors. There was a race condition occurring, where these events would stomp on each other's state.

We need to make sure there are distinct monitoring keys for keepalives and check TTL.

**Comment by echlebek** [comment]
Related, this is also why we observed issues with check TTL.

**Comment by nikkiki** [comment]
After a few hours of engineering swarming/debugging, we've identified the issue to be related to check ttl's overwriting the monitor key in a race condition. I verified this behavior in several environments by toggling an agent on/off which triggers failing keepalive events consistently in the absence of the `ttl-check` resource. We'll discuss Monday on how best to approach the solution.

**Comment by echlebek** [comment]
We decided that the solution was to prefix monitors so that this situation can't happen again.
