### ISSUE TITLE
sensuctl edit should provide flag to set the editor

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2477]
The `sensuctl edit` command currently uses the default editor vim if an editor is not defined as an environment variable. Especially for those that hate vim (just me? oh okay) it might be nice to additionally have the option to pass the editor as a flag: `sensuctl edit check ping-proxy --editor pico`.

**Comment by ccressent** [comment]
Standard Unix way to do what you want:
```
$ EDITOR=pico sensuctl edit check ping-proxy
```
That is, you explicitly set the env for the command you're about to run.

**Comment by nikkiki** [comment]
@ccressent thanks so much for providing that workaround! The command would still set the the environment variable though correct? What if for some reason (I'm not exactly sure if this is a viable use case, but theoretically speaking) a user in unable or unauthorized to update the environment variables of an instance? Providing a flag would serve as a less permanent tool to change the editor, or the user could use it as a one off. Just thinking out loud!

**Comment by ccressent** [comment]
That command would only set `EDITOR` to `pico` in the sub-shell that will execute the `sensuctl` command. The environment is local to the current shell and I'm not aware of any reason, or even techniques, to restrict what a user with a shell can do to its environment.

I'm fairly sure this method of defining the environment for a sub-shell is defined by POSIX!

**Comment by echlebek** [comment]
`EDITOR` is the unix way, closing :)
