### ISSUE TITLE
[Web UI] TypeError: Could not connect to the server.

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2483]
When a cluster loses quorum, etcd and the sensu api become unresponsive. This is an issue for the dashboard which relies on connectivity with the backend. In the event that this happens, we should gracefully handle the network error. Bonus points if we can detect the network error is due to quorum loss!

## Expected Behavior
Graceful error handling and message that a cluster has lost quorum?

## Current Behavior
Error and crash when a cluster loses quorum.
<img width="978" alt="screen shot 2018-12-03 at 4 01 35 pm" src="https://user-images.githubusercontent.com/10634078/49409424-768b1380-f715-11e8-99b9-b8b9e85a81fd.png">

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
1. Start a cluster with 3 nodes
2. Stop the backend service on 2 of the nodes
3. Observe failure on dashboard.

## Context
I don't expect to still see resources, but I would like to be notified maybe why the services are not working.

**Web UI Stack Trace:**

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `419c199`
* Installation method (packages, binaries, docker etc.): packages via terraform on was
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16

**Comment by jamesdphillips** [comment]
Closed by #2455
