### ISSUE TITLE
OS X `sensuctl version` doesn't report a version

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#2489]
The `sensuctl` from https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.0.0/sensu-go-5.0.0-darwin-amd64.tar.gz does not report a version.

```
$ sensuctl version                                                                                                                                         
sensuctl version #, build , built
```

**Comment by grepory** [comment]
CMake puts this version info into place. I don't think this is a bug.
