### ISSUE TITLE
Update or Remove FAQ.md

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#2493]
Parts of FAQ.md still seem to imply that Sensu is still in an alpha / beta state. Nor, does the document reflect the final name of the product.

We should update it or maybe simply replace the document with a link to the [FAQ in the docs](https://docs.sensu.io/sensu-go/5.0/getting-started/faq/).

**Comment by palourde** [comment]
This has been completed via https://github.com/sensu/sensu-go/pull/2655
