### ISSUE TITLE
Windows agent provides incorrect event status when running a PowerShell command, breaks front end

### ISSUE THREAD

**Issue by RamblingCookieMonster** [sensu/sensu-go#2494]
Checks based on PowerShell fail in a manner that provides an error code that the Sensu front end does not like.  The back end continues to work without issue, albeit the check status is incorrect.

## Expected Behavior

PowerShell based Sensu checks run without issue

## Current Behavior

PowerShell based Sensu checks fail to run, in a way that breaks the Sensu front end

Here's the check:

```json
{
    "command": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo -File C:\\rc\\sensu\\plugins\\check-windows-pagefile.ps1 80 90",
    "publish": true,
    "interval": 120,
    "metadata": {
        "name": "check-windows-pagefile",
        "namespace": "default"
    },
    "subscriptions": [
        "windows-base"
    ],
    "ttl": 240,
    "timeout": 30
}
```

Here's the ensuing error once this runs:

![image](https://user-images.githubusercontent.com/6377597/49604371-b7746980-f95b-11e8-98ff-74f84574bb37.png)

Here's the event data it's failing on (presumably you could display nonsensical exit codes vs failing?):

```json
"check": {
            "command": "Powershell.exe -NonInteractive -NoProfile -ExecutionPolicy Bypass -NoLogo -File C:\\rc\\sensu\\plugins\\check-windows-pagefile.ps1 80 90",
            "output": "I\u0000n\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000P\u0000o\u0000w\u0000e\u0000r\u0000S\u0000h\u0000e\u0000l\u0000l\u0000 \u0000e\u0000r\u0000r\u0000o\u0000r\u0000.\u0000 \u0000 \u0000L\u0000o\u0000a\u0000d\u0000i\u0000n\u0000g\u0000 \u0000m\u0000a\u0000n\u0000a\u0000g\u0000e\u0000d\u0000 \u0000W\u0000i\u0000n\u0000d\u0000o\u0000w\u0000s\u0000 \u0000P\u0000o\u0000w\u0000e\u0000r\u0000S\u0000h\u0000e\u0000l\u0000l\u0000 \u0000f\u0000a\u0000i\u0000l\u0000e\u0000d\u0000 \u0000w\u0000i\u0000t\u0000h\u0000 \u0000e\u0000r\u0000r\u0000o\u0000r\u0000 \u00008\u00000\u00000\u00009\u00000\u00000\u00001\u0000d\u0000.\u0000\r\u0000\n\u0000",
            "state": "failing",
            "status": 4294901760,
        }
    },
```

I've tried the following, all of these produce the same outcome/status:

* Unqualified powershell.exe
* Fully qualified path to powershell.exe
* powershell -command "exit 0"
* cmd /c the command

Running this same command from cmd or powershell works without issue.

## Possible Solution

Unsure.

* I suspect there's an agent issue related to how the `Command` process is invoked, or something around the environment in which the `Command` is invoked.
* The front-end should continue functioning even if an odd `Status` is received

## Steps to Reproduce (for bugs)

1. Add a basic check that runs a command on Windows
2. Run the check on a Windows box
3. Javascript errors on sensu front end.  backend looks fine

## Context

I can't run typical checks on Windows

## Your Environment

* Sensu version used: agent=5.0, backend=2.0.0-beta.8-1 (likely)
* Installation method: agent=run the process ad hoc.  backend=docker
* Operating System and version: agent=Windows Server 2016.  backend=centos 7.x

Thanks!  I'm @ pscookiemonster in your Slack team if you want to ping me outside this issue

**Comment by RamblingCookieMonster** [comment]
fwiw:  using the Command `cmd /c EXIT /B 1` worked without issue - this appears to be specific to PowerShell.exe, at the very least.

**Comment by portertech** [comment]
Reminds me of a Classic Core issue https://github.com/sensu/sensu/issues/1890

**Comment by RamblingCookieMonster** [comment]
fwiw @portertech - running essentially `powershell -command "exit 1"` results in the same behavior

**Comment by jamesdphillips** [comment]
Closing this issue as the Web UI issue has been resolved. Will track agent issue in #2514.
