### ISSUE TITLE
Ubuntu 18.04 sensu-go packages don't install systemd unit file

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2496]
## Expected Behavior

I'd expect installing `sensu-go-backend` to result in `sensu-backend` service being installed.

## Current Behavior

Currently the install is trying to install sysVinit file into /etc/init.d/ and that file seems to be absent from package.

## Steps to Reproduce (for bugs)

1. `docker run -it ubuntu:18.04 /bin/bash`
2. `apt-get update`
3. `apt-get install curl`
4. `curl -s https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh | bash`
5. `apt-get install sensu-go-backend`

Error:
```
Unpacking sensu-go-backend (5.0.0) ...
Setting up sensu-go-backend (5.0.0) ...
cp: cannot stat '/usr/share/doc/sensu-go-backend-5.0.0/sensu-backend': No such file or directory
chmod: cannot access '/etc/init.d/sensu-backend': No such file or directory
```

The directory `/usr/share/doc/sensu-go-backend-5.0.0` is empty and I'd expect the package to install systemd unit file and not /etc/init.d/ script for systemd system.

```
root@a7f6ddc01b1c:/# ls -la /usr/share/doc/sensu-go-backend-5.0.0/
total 8
drwxr-xr-x 2 root root 4096 Dec  3 22:40 .
drwxr-xr-x 1 root root 4096 Dec  6 22:13 ..
```

## Context

I am automating Puppet module with @ghoneycutt and now acceptance tests for Ubuntu 18.04 are failing when I switch from beta to stable.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.0.0
* Installation method (packages, binaries, docker etc.): DEB
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

**Comment by jaredledvina** [comment]
@pfak is correct, however, the `/etc/dpkg/dpkg.cfg.d/excludes` which includes `path-exclude=/usr/share/doc/*` ships directly from Canonical via their core image: https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-amd64-root.tar.gz 

```
root@ubuntu-18:/# cat /etc/dpkg/dpkg.cfg.d/excludes
# Drop all man pages
path-exclude=/usr/share/man/*

# Drop all documentation ...
path-exclude=/usr/share/doc/*

# ... except copyright files ...
path-include=/usr/share/doc/*/copyright

# ... and Debian changelogs
path-include=/usr/share/doc/*/changelog.Debian.*
```

I would expect that the `.deb` package to not error out when the `path-exclude=/usr/share/doc/*` option is set, as it is by default from Canonical.

**Comment by annaplotkin** [comment]
@amdprophet to review and respond

**Comment by amdprophet** [comment]
@jaredledvina @treydock can either of you confirm that this is fixed in the latest release? We've changed the path to `/usr/share/*/`.

**Comment by treydock** [comment]
Is it expected to have the install install sysVinit scripts into /etc/init.d and not systemd unit files?

The actual failure is resolved but the unit file in /usr/share/sensu-go-backend-5.1.1 isn't installed like I'd expect.  I am testing in docker and systemd isn't actually installed by default in the containers from ubuntu.  A real system would likely not have this problem.  I tried installing systemd in docker and installing sensu-go-backend but still can't find the unit file installed, what determines when to install the unit file vs sysvinit file?

**Comment by amdprophet** [comment]
@treydock we're using this block of code to determine if a system is running systemd or not when the post-install hook is run:

```
using_systemd()
{
    [ -e "/proc/1/comm" ] && grep -q "^systemd$" /proc/1/comm
}
```

**Comment by treydock** [comment]
I think that should be fine in docker because if you don't start a container with something like `/usr/sbin/init` then systemd won't be functional as PID 1 won't belong to systemd.  Tested behavior in Vagrant and looks like things are fine with 5.2.0.
