### ISSUE TITLE
Indexes for entities that allow searching by common fields

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#25]

**Comment by echlebek** [comment]
I think we need to take a step back and focus on the drivers for this issue. What features would rely on this index?

**Comment by palourde** [comment]
Like Eric mentioned, I'm not totally sure which functionality this issue describes. If I only rely on the title, entities query is now implemented at the API level via enterprise filtering. If there's something else missing we should probably open a new issue :)
