### ISSUE TITLE
[Web UI] Error: GraphQL error: {"Code":4,"Message":"unauthorized to perform action"}

### ISSUE THREAD

**Issue by craigpfeiffer** [sensu/sensu-go#2505]
Cannot log into web ui

## Expected Behavior
login with default admin creds and access sensu dashboard via http:// web ui

## Current Behavior
login with defaul admin and met with a graphql related error (shown below).  it also appears to be redirecting to https://

## Steps to Reproduce (for bugs)
1. enter http://sensu-dash in browser
2. enter default admin creds
3. loads https://sensu-dash with graphql error

## Context
cannot login to the dashboard at all. 

i am seeing this in the logs as well
`{"component":"rbac","level":"debug","msg":"unauthorized request","time":"2018-12-07T18:56:41Z","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"","resource":"namespaces","resourceName":"default","username":"admin","verb":"get"}}
{"component":"apid","duration":"1.875ms","level":"info","method":"GET","msg":"request completed","path":"/api/core/v2/namespaces/default","size":53,"status":403,"time":"2018-12-07T18:56:41Z"}`

**Web UI Stack Trace:**

at `new ApolloError` (/static/js/main.d07bc22e.js:7)
at `undefined` (/static/js/main.d07bc22e.js:60)
at `undefined` (/static/js/main.d07bc22e.js:60)
at `undefined` (/static/js/main.d07bc22e.js:60)
at `QueryManager.broadcastQueries` (/static/js/main.d07bc22e.js:60)
at `Object.next` (/static/js/main.d07bc22e.js:60)
at `notifySubscription` (/static/js/main.d07bc22e.js:60)
at `onNotify` (/static/js/main.d07bc22e.js:60)
at `SubscriptionObserver.next` (/static/js/main.d07bc22e.js:60)
at `undefined` (/static/js/main.d07bc22e.js:36)
at `Object.next` (/static/js/main.d07bc22e.js:36)
at `notifySubscription` (/static/js/main.d07bc22e.js:60)
at `onNotify` (/static/js/main.d07bc22e.js:60)

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `5.0.0-1`
* Installation method (packages, binaries, docker etc.): docker container built from sensu-go git repo
* Operating System and version (e.g. Ubuntu 14.04): amazon linux

**Comment by craigpfeiffer** [comment]
i want to update this a little and it appears it's still using http:// chrome just seems to make it appear as though it was an https:// site with a bad cert/self-signed cert.  when i copy the url it still shows http://

![image](https://user-images.githubusercontent.com/37307773/49676196-0e4e7180-fa36-11e8-9864-09d7e7dd8d12.png)

https://security.googleblog.com/2016/09/moving-towards-more-secure-web.html

**Comment by craigpfeiffer** [comment]
yet another update... my etcd cluster still had some remnants from the beta 8 environment that appears to be causing the issue.  i reset the etcd cluster entirely and restarted the backend servers and i'm able to login and view the dashboard without issue now.

**Comment by echlebek** [comment]
Pre-5.0.0 backends are not compatible with post-5.x components. Going forward, greater compatibility can be expected. :)
