### ISSUE TITLE
building docker container from git repo

### ISSUE THREAD

**Issue by craigpfeiffer** [sensu/sensu-go#2508]
this is more of an FYI - for people having trouble building the container from the repo.  attempting to build a docker container from the git repo results in failures due to incorrect paths.

## Expected Behavior
clone repo for sensu-go into $GOPATH ($HOME/projects)
run `./build docker build` from the sensu-go directory
```
.
truncating output for sanity
.

Step 2/14 : RUN apk add --no-cache curl
.
truncating output for sanity
.
OK: 6 MiB in 18 packages
---
.
truncating output for sanity
.
Successfully tagged sensu/sensu:master
```

## Current Behavior
run `./build docker build` from the sensu-go directory
```
cannot find package "github.com/sensu/sensu-go/cli" in any of:
    /usr/local/go/src/github.com/sensu/sensu-go/cli (from $GOROOT)
    /root/Projects/src/github.com/sensu/sensu-go/cli (from $GOPATH)
cmd/sensuctl/main.go:7:2: cannot find package "github.com/sensu/sensu-go/cli/commands" in any of:
    /usr/local/go/src/github.com/sensu/sensu-go/cli/commands (from $GOROOT)
    /root/Projects/src/github.com/sensu/sensu-go/cli/commands (from $GOPATH)
cmd/sensuctl/main.go:8:2: cannot find package "github.com/sensu/sensu-go/cli/commands/hooks" in any of:
    /usr/local/go/src/github.com/sensu/sensu-go/cli/commands/hooks (from $GOROOT)
    /root/Projects/src/github.com/sensu/sensu-go/cli/commands/hooks (from $GOPATH)
cmd/sensuctl/main.go:9:2: cannot find package "github.com/sensu/sensu-go/cli/commands/root" in any of:
    /usr/local/go/src/github.com/sensu/sensu-go/cli/commands/root (from $GOROOT)
    /root/Projects/src/github.com/sensu/sensu-go/cli/commands/root (from $GOPATH)
cmd/sensuctl/main.go:10:2: cannot find package "github.com/spf13/cobra" in any of:
    /usr/local/go/src/github.com/spf13/cobra (from $GOROOT)
    /root/Projects/src/github.com/spf13/cobra (from $GOPATH)
```

## Possible Solution
the build.sh script has a path of `github.com/sensu/sensu-go/` and the only way i got it to work was by cloning the repo to `$GOPATH/src/github.com/sensu/sensu-go` 

my guess is that it was done with the `go get` command which put it in the path that the script is using.

**Comment by echlebek** [comment]
Hi craigpfeiffer, this may indeed trip up people who aren't used to building Go projects.

All Go projects that are not using modules (or using any Go compiler prior to 1.11.x) must be located in `$(go env GOPATH)/src`. This is a function of how the Go compiler works, and is not specific to the project or docker build process.

It's worth noting that if users don't have a GOPATH in their environment, `go env GOPATH` defaults to `$HOME/go`.

**Comment by echlebek** [comment]
I'm closing this out so it doesn't clutter our inbox, but wanted to drop a link to the Go documentation on source code organization as well: https://golang.org/doc/code.html#Organization
