### ISSUE TITLE
listing assets returns null with format json

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2509]
## Expected Behavior

I'd expect `--format json` to result in JSON output even when nothing is returned.

## Current Behavior

```
[root@sensu_backend /]# /usr/bin/sensuctl asset list --all-namespaces --format json
null
```

## Possible Solution

Have assets return empty array with `--format json` when none present.

## Steps to Reproduce (for bugs)

```
[root@sensu_backend /]# /usr/bin/sensuctl asset list --all-namespaces --format json
null
```

## Context

I am using Puppet to automate sensu-go and with beta and nightlies I was able to always have Puppet get JSON data back with `--format json`.  That behavior seems to have changed between last beta and stable.

CC @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.0.0
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment]
Other resources like checks do what I'd expect:

```
[root@sensu_backend /]# /usr/bin/sensuctl check list --all-namespaces --format json
[]
```

**Comment by echlebek** [comment]
It should be consistent with the others and return `[]`. Technically `null` is valid JSON, but all the commands should have the same behaviour for empty lists. It's probably specific to the `sensuctl asset list` command.
