### ISSUE TITLE
Metric extraction: a bad line should not abort extraction

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#2511]
We ran into trouble extracting metrics from Kube State Metrics, using the [sensu-prometheus-collector plugin](https://github.com/sensu/sensu-prometheus-collector) and InfluxDB line output.

## Expected Behavior
The Sensu Agent will do its best to extract metrics from check output, logging invalid lines.

## Current Behavior
The Sensu Agent will abort check output metric extraction if it encounters an invalid line.

https://github.com/sensu/sensu-go/blob/a9f7289efe6107a8ba7c84fc571d2ae6dadf280c/agent/transformers/influx_db.go#L50

**Comment by echlebek** [comment]
Half enhancement, half bug IMO :)
