### ISSUE TITLE
[Web UI] TypeError: e.currentTarget is null error occurs when opening or closing dev tools

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2518]
## Expected Behavior
Opening dev tools in does not cause an exception.

## Current Behavior
Opening dev tools causes an exception, seemingly due to the resulting window resize.

## Steps to Reproduce (for bugs)
1. Make sure dev tools is in split pane configuration
2. Navigate to the Sensu dashboard
3. Right click in the window and click "Inspect element"

Note: it also works in reverse, ie if you have a dev tools pane open when you load the dashboard and then close it.

**Web UI Stack Trace:**

at `ToolbarMenu/n.handleWindowResize<` (/static/js/main.566beacb.js:66)
at `later` (/static/js/main.566beacb.js:66)

## Your Environment
Browser: Firefox 63.0 on OSX
Sensu Version: sensu-backend version 2.0.0-beta.8-8#c07579c, build c07579c0b20f5f5e12788fb0704c3a9138882b58, built 2018-11-15T18:15:08+0000 (installed by extracting the binary from the published deb package and deploying with a config management tool).

**Comment by jamesdphillips** [comment]
This issue has been fixed in the GA release of Sensu. #2475.
