### ISSUE TITLE
[Proxy Check Requests] publishing of proxy checks not working

### ISSUE THREAD

**Issue by becon-cmichel** [sensu/sensu-go#2521]
Since the last beta8 and even in the stable release of sensu go the publishing of proxy check requests are not working anymore. 

## Steps to Reproduce (for bugs)
1. Install sensu-go-backend and sensu-go-agent

2. Configure subscription "poller" to the sensu-go-agent
```
cat /etc/sensu/agent.yml | grep subscriptions
subscriptions: ["poller"]
```

3. Create check with "sensuctl create -f check_icmp.json"
```
{
	"type": "CheckConfig",
	"api_version": "core/v2",
	"metadata":{
		"namespace":"default",
		"name":"icmp",
		"labels": null,
		"annotations": null
	},
	"spec":{
		"command":"/usr/lib/nagios/plugins/check_icmp -H '{{ .entity.labels.ip_address }}' -n 10",
		"interval":10,
		"timeout":5,
		"proxy_requests":{
			"entity_attributes":["entity.entity_class == 'proxy'"],
			"splay":true,
			"splay_coverage":90
		},
		"handlers":[],
		"publish":true,
		"round_robin":false,
		"runtime_assets":[],
		"subscriptions":["poller"],
		"output_metric_format":"nagios_perfdata",
		"output_metric_handlers":[]
	}
}
```

4. Create check with "sensuctl create -f entity_dummy.json"
```
{
	"type": "Entity",
	"api_version": "core/v2",
	"metadata":{
		"namespace":"default",
		"name": "dummy",
		"annotations": null,
		"labels": {
			"ip_address": "127.0.0.1",
			"device_type": "localhost",
			"device_vendor": "lxc",
			"team": "test"
		}
  	},
	"spec":{
		"entity_class": "proxy",
		"subscriptions": []
	}
}
```

## Expected behavior
The icmp check should be executed by the local agent against the local address 127.0.0.1 and displayed in the frontend.

## Your Environment
OS:	Debian GNU/Linux 9.6 (stretch)
ii  sensu-go-agent  5.0.0  amd64  Sensu Go Agent
ii  sensu-go-backend  5.0.0  amd64  Sensu Go Backend
ii  sensu-go-cli  5.0.0  amd64  Sensu Go CLI

Thanks =)

**Comment by becon-cmichel** [comment]
OK, found it! 
If the token in the check definition is wrong or could not be found, the check is not published at all. I believe this was different in earlier versions!?

So the check definition should be like this
```
{
	"type": "CheckConfig",
	"api_version": "core/v2",
	"metadata":{
		"namespace":"default",
		"name":"icmp",
		"labels": null,
		"annotations": null
	},
	"spec":{
		"command":"/usr/lib/nagios/plugins/check_icmp -H '{{ .labels.ip_address }}' -n 10",
		"interval":10,
		"timeout":5,
		"proxy_requests":{
			"entity_attributes":["entity.entity_class == 'proxy'"],
			"splay":true,
			"splay_coverage":90
		},
		"handlers":[],
		"publish":true,
		"round_robin":false,
		"runtime_assets":[],
		"subscriptions":["poller"],
		"output_metric_format":"nagios_perfdata",
		"output_metric_handlers":[]
	}
}
```

The difference is the token definition.

1. Could not be found, so no check publishing
  "command":"/usr/lib/nagios/plugins/check_icmp -H '{{ .entity.labels.ip_address }}' -n 10",

2. Correct, so check publishing works
  "command":"/usr/lib/nagios/plugins/check_icmp -H '{{ .labels.ip_address }}' -n 10",

I would have assumed that the check requests were published even if the token is wrong.

**Comment by marcseguin** [comment]
I face the same issue :-(
Even if the behavior remains I suggest to add an info message with a proper reason-description in the logs of the backend as the current message is on debug level and only stating "check is not subdued" which is not really telling something.

**Comment by palourde** [comment]
I just confirmed and an error message is now appearing in sensu-backend logs:

```
{"check":"icmp","component":"schedulerd","error":"unmatched token: template: :1:61: executing \"\" at \u003c.entity.labels.ip_address\u003e: map has no entry for key \"entity\"","level":"error","msg":"error publishing proxy check requests","namespace":"default","time":"2019-05-29T13:07:14-04:00"}
```
