### ISSUE TITLE
Keepalive events will stop occurring on backend restart

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2530]
Although PR #2502 fixes the problems with Check TTL and Keepalives in the common case, the solution is in-memory only, and will fail when the backend's state is refreshed (i.e., restarted).

While monitors can transition between backends via etcd, the failure loop that causes backends to emit events relies on in-memory state.

This is related to #2135 and users who rely on durable keepalive and check TTL failure behaviour should be aware of this.

**Comment by 10xjs** [comment]
On starting, the sensu agent will attempt connection to a random backend. If the chosen backend is inaccessible it will continue trying to connect, without every trying a different backend.
