### ISSUE TITLE
[CLI] scheduled expire value is incorrectly formatted in cli output

### ISSUE THREAD

**Issue by 10xjs** [sensu/sensu-go#2531]
The result of `sensuctl silenced info` in tabular format incorrectly formats the value of the `expire` field in the case that `expire` is -1 and the `begin` field is set.

## Expected Behavior
If `expire` is -1 (unset value), it should always display as -1 (or a value indicating it is not set).

## Current Behavior
When the `begin` field is set, `expire` may be displayed as a nonsensical negative value. 

## Your Environment
on build 0150bbcb

**Comment by palourde** [comment]
It appears this has been fixed already:

```
$ sensuctl silenced list

     Name       Subscription     Check            Begin          Expire   ExpireOnResolve   Creator   Reason    Namespace
 ───────────── ────────────── ─────────── ───────────────────── ──────── ───────────────── ───────── ───────── ───────────
  *:check-cpu                  check-cpu   27 May 19 12:20 EDT   -1s      false             admin     testing   default
```
