### ISSUE TITLE
Proper TLS support in sensuctl

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2541]
`sensuctl` support for TLS is close to non-existent.

Unless the backend is using a certificate signed by a "proper" authority installed system-wide it's impossible to connect to the API over HTTPS.

On Windows systems, `sensuctl` cannot work over HTTPS at all because there is no mechanism in Go's x509 library to load the "default", system-wide CA certificates (see [here](https://golang.org/src/crypto/x509/cert_pool.go?s=1328:1368#L45)).

## Expected Behavior

`sensuctl` should be able to talk to the API over HTTPS, in many different
scenarios:

- ability to provide my own CA certificates if needed
- ability to skip certificate verification (probably with a warning)
- ability to provide a client certificate if asked by the server
- ...

## Current Behavior

Unless one is using a non-windows system and doctors the system-wide CA certificates (or use a certificate that's signed by a "proper" authority), it's impossible to talk to the API over HTTPS.

## Context

I was working on #2300, making small improvements to some aspects of our use of TLS and attempted to address @cwjohnston's comment about `sensuctl` while I was at it.

**Comment by echlebek** [comment]
If TLS doesn't work in sensuctl in Windows at all, I would consider this to be a bug, and a fairly serious one. Adding to 5.0.next.
