### ISSUE TITLE
Sensuctl delete asset command not existing

### ISSUE THREAD

**Issue by schampseix** [sensu/sensu-go#2542]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by palourde** [comment]
Hi @schampseix 

Thank for you reporting this problem. We already have an issue regarding the missing `delete` subcommand, https://github.com/sensu/sensu-go/issues/988, so I'll go ahead and close this one in order to avoid any duplicate.

Thanks
