### ISSUE TITLE
sensuctl edit fails to remove temporary file

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#2544]
When editing a check (or other resource) with 'sensuctl edit', the temporary file created for doing the actual edit with $EDITOR gets left behind in /tmp.

## Expected Behavior

Once $EDITOR exits when running 'sensuctl edit' the temporary file used for the edit should be removed.
## Current Behavior

The temporary file, following the pattern /tmp/sensu-resource.*.yaml123456789, is left behind.

```
# date
Mon Dec 17 09:00:02 PST 2018
# ls -l /tmp/sensu-resource*
ls: cannot access '/tmp/sensu-resource*': No such file or directory
# sensuctl edit check linux-cpu-check
[ $EDITOR runs against /tmp/sensu-resource.*.yaml963594219 and exits ]
# ls -l /tmp/sensu-resource*
-rw------- 1 root root 589 Dec 17 09:00 /tmp/sensu-resource.*.yaml963594219


# export EDITOR=echo
# sensuctl edit check linux-cpu-check
/tmp/sensu-resource.*.yaml227185834
# ls -l /tmp/sensu-resource.*.yaml227185834
-rw------- 1 root root 589 Dec 17 09:01 /tmp/sensu-resource.*.yaml227185834

```
## Steps to Reproduce (for bugs)

1. Create a resource such as a check
2. Run 'sensuctl edit' on that resource and then exit $EDITOR
3. Look in /tmp for new file name matching the name sensu-resource.*.yaml
4.

## Context

I'm trying to keep /tmp/ clear of files that are no longer needed or actively in use.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):  sensuctl version 5.0.1#af7d1d0, build af7d1d041092c130653cc8e2ca4b8aef479cb05a, built '2018-12-11T21:25:30+0000'
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04

**Comment by nikkiki** [comment]
Closed by https://github.com/sensu/sensu-go/commit/bd4b10f958ece7936a14098f931b025580abf4b0.
