### ISSUE TITLE
panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2545]
Sometimes the backend crashes soon after starting up with the following trace:

```
{"component":"monitor","level":"info","msg":"monitor timed out, for /sensu.io/monitors/default/keepalived/fc3cca518056, handling failure","time":"2018-12-14T22:18:41-08:00"}
{"component":"keepalived","entity":"fc3cca518056","level":"info","msg":"keepalive timed out, creating keepalive event for entity","time":"2018-12-14T22:18:41-08:00"}
panic: non-positive interval for NewTicker

goroutine 265 [running]:
time.NewTicker(0x0, 0xc420a3cb40)
	/usr/lib/go/src/time/tick.go:23 +0x1a1
github.com/sensu/sensu-go/backend/monitor.(*EtcdSupervisor).Monitor.func1(0x18fbb60, 0xc420d780c0, 0x0)
	/home/cyril/go/src/github.com/sensu/sensu-go/backend/monitor/supervisor.go:140 +0x115
created by github.com/sensu/sensu-go/backend/monitor.watchMon.func1
	/home/cyril/go/src/github.com/sensu/sensu-go/backend/monitor/supervisor.go:206 +0x1a8
[etcd-snapshot.zip](https://github.com/sensu/sensu-go/files/2687114/etcd-snapshot.zip)


```

I suspect this is due to previous entity/keepalive state in my local etcd.
This is concerning because after GA, I do not expect users to potentially have to completely erase their etcd store between sensu version updates.

## Expected Behavior

No panic.

## Steps to Reproduce (for bugs)
1. (maybe optional) unzip load the attached etcd state with `etcdctl snapshot restore`
2. start the backend
3. if the panic doesn't occur within a few seconds, stop the backend and try to start it again. It can take 10+ tries to trigger

## Your Environment

* Sensu version: c4373a6aece87679d225829160c6fd19fb14c20a
* Installation method: git
* Operating System and version: Arch Linux, kernel 4.19.4
* etcd snapshot: [etcd-snapshot.zip](https://github.com/sensu/sensu-go/files/2687128/etcd-snapshot.zip)

**Comment by annaplotkin** [comment]
@echlebek Assigning to you to take a look and see if we need to include this for 5.0.2.
