### ISSUE TITLE
TLS is inflexible and limited

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2548]
The `TLSOptions` type is too simple and "server centric". It needs to be more
granular and closer to the standard library type to allow for things like client
certificate request and verification.

The `tls.Config` type from the `crypto/tls` standard library is what is
actually underneath `TLSOptions`, and that type is much richer and granular.

At the moment, I see the following issues with sensu-go:

#### No support for client certificates

The backend never requests client certificates and cannot be configured to do
so, be it for API clients (sensuctl) or websocket clients (sensu-agent). The consequence 
is that both `--cert-file` and `--key-file` cannot have any real effect when given 
to sensu-agent and sensuctl.

See `tls.Config.ClientAuth`. Untils client authentication can be configured,
there is no point in having the `--cert-file` and `--key-file` flags for
sensu-agent and sensuctl.

#### `--trusted-ca-file` is currently useless when given to sensu-backend

This bundle of CA certificates is ultimately put in `tls.Config.RootCAs`, which
is only used by clients to verify the certificate presented by the server end of
the TLS connection. To verify the certificate presented by the client end, that
certificate bundle needs to be put in `tls.Config.ClientCAs` instead.

See the `crypto/tls` package documentation:
`tls.Config.RootCAs` is "the set of root certificate authorities that clients
use when verifying server certificates".
`tls.Config.ClientCAs` is "the set of root certificate authorities that servers
use if required to verify a client certificate".

#### `--insecure-skip-tls-verify` is currently useless when given to the backend

Since the backend doesn't check client certificates, `--trusted-ca-file` or even
the system's certificate bundle (used by default) is never needed.

#### No reason to couple the various TLS flags

I don't see a reason for `--trusted-ca-file` to need both `--cert-file` and
`--key-file` to also be specified (see [here](https://github.com/sensu/sensu-go/blob/c4373a6aece87679d225829160c6fd19fb14c20a/backend/cmd/start.go#L178-L198)).

Not specifying `--trusted-ca-file` will make `tls.Config.RootCAs` nil, which in
turn will make the library use the system's bundle of root CAs (on non windows
OSes).

Presenting a certificate (`--cert-key` and `cert-file`) is orthogonal to
verifying a certificate presented to you (`--trusted-ca-file`).

## Possible Solution

* Rework the various TLS flags and options to fully take advantage of what the standard library gives us for free.
* Decouple the flags as appropriate

## Context

This was discovered while working on #2300.
The `sensuctl` side of things is covered in #2541.

**Comment by gbolo** [comment]
I agree with this. I experienced the same issues

**Comment by gbolo** [comment]
Hi @ccressent 

I have quickly reviewed your issue and I agree with most of it. Please see #2700 which aims to clean up the TLS a bit

I am brand new to this code base, however, In terms of some of the points you made:

### No support for client certificates
I agree with this, I opened up #2689 to specifically deal with this issue.

### `--trusted-ca-file` is currently useless when given to sensu-backend
I agree with this, however, when mutual TLS support is added, we can rename this as `client-ca-file` or something

### No reason to couple the various TLS flags
completely agree with this, and #2700 fixes it

### `--insecure-skip-tls-verify` is currently useless when given to the backend
Currently, the backend appears to actually acts as a client for things like etcd and possibly more? therefore this option is useful in those cases. Ofcourse, it's only useful for those of us who do not know how to configure TLS properly...

**Comment by ccressent** [comment]
I'm going to have a look at your PR very soon, thanks again for taking the time to contribute @gbolo!

Regarding `--insecure-skip-tls-verify` being useless on the backend: the backend is indeed a client for etcd, but nothing else. There is a separate set of TLS flags for that connection to etcd, all prefixed with `etcd` (see `sensu-backend start help`), but no `--etcd-insecure-skip-tls-verify` flag.

I would argue that since the backend-client and backend-etcd connections are separate, with 2 separate sets of flags, they shouldn't share an `insecure-skip-tls-verify` flag. To recap, I'm in favor of having the following flags for the backend:

- `--insecure-skip-tls-verify`
Used to skip the certificate verification on the backend-client connection

- `--etcd-insecure-skip-tls-verify`
Used to skip the certificate verification on the backend-etcd connection

**Comment by gbolo** [comment]
> 
> Regarding `--insecure-skip-tls-verify` being useless on the backend: the backend is indeed a client for etcd, but nothing else. There is a separate set of TLS flags for that connection to etcd, all prefixed with `etcd` (see `sensu-backend start help`), but no `--etcd-insecure-skip-tls-verify` flag.

Ahh, your right, I missed that. Thanks @ccressent. I agree with have two different named flags for skipping TLS verification based on backend client or etcd client

**Comment by palourde** [comment]
I believe a lot of work has been done around TLS configuration. We should definitely re-open new issues that target some specific functionalities/use cases around TLS if the need arise.
