### ISSUE TITLE
Ubuntu cosmic packages don't install, require too old "base-files" dependency

### ISSUE THREAD

**Issue by growse** [sensu/sensu-go#2553]
## Expected Behavior
The documented installation steps:
```
$ curl -s https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh | sudo bash`
$ apt-get install sensu-go-cli
```
should successfully install package.

## Current Behavior
Package installation fails, complaining current `base-files` package is too new:

```
$ apt-get install sensu-go-cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 sensu-go-cli : Depends: base-files (< 10.1ubuntu3)
E: Unable to correct problems, you have held broken 
packages.
```

This seems to occur for all three packages (agent, backend and cli).

## Possible Solution

I'm not entirely sure why the packages are so opinionated about the version of `base-files` they require. My current version (up to date system):
```
$ dpkg --list | grep base-file
ii  base-files                                    10.1ubuntu7                                 amd64        Debian base system miscellaneous files
```
This is also the version currently available in the main ubuntu repos:
```
$ apt-cache madison base-files
base-files | 10.1ubuntu7 | http://gb.archive.ubuntu.com/ubuntu cosmic/main amd64 Packages
```

## Steps to Reproduce (for bugs)

1. Install fresh copy of Ubuntu 18.10
2. Update all packages to latest
3. Install Sensu packagecloud repository as per the documentation
4. apt-get install `sensu-go-cli` 

## Context
I'm trying to install the latest `sensu-go-cli` package on my local laptop running an up-to-date version of Ubuntu 18.10.

**Comment by treydock** [comment]
Ran into this same issue attempting to add Ubuntu 18.10 support to sensu-puppet module.

CC @ghoneycutt

**Comment by ghoneycutt** [comment]
Bump to keep open.

**Comment by treydock** [comment]
I'm unable to reproduce this with latest Sensu Go.  I think this was resolved at some point.
