### ISSUE TITLE
Proxy entity subscription is duplicated in events

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2557]
## Expected Behavior
The entity's subscriptions in an event should match the entity's subscriptions.

## Current Behavior
The entity's subscriptions in the event has a duplicated entity subscription.

example from staging:
```
    subscriptions:
    - metrics
    - misc
    - round-robin
    - proxy
    - entity:staging-agent-0
    - entity:staging-agent-0
```

## Steps to Reproduce (for bugs)
Create a proxy check, and inspect the event corresponding to it.

**Comment by palourde** [comment]
I believe this is not longer happening and I confirmed it via a deployed sensu-staging environment.
