### ISSUE TITLE
Proxy checks execute too often

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2558]
## Expected Behavior
Proxy checks execute according to their specified interval. Event history contains one history item for each interval of time.

## Current Behavior
Two executions per interval are often observed, at the same time.

## Steps to Reproduce (for bugs)
`sensuctl event info staging-agent-0 ping-proxy` on staging.

This may be related to #2557

**Comment by echlebek** [comment]
The problem is that proxy checks will execute on every agent that matches the subscription. There is no effort to distribute proxy checks equally to agents, or to make sure that for a given proxy entity, only a single agent will execute the check per interval.

Users can work around this with splay, but we should be able to only send the request to a single agent per proxy entity.

In a clustered environment this gets a bit trickier.

**Comment by palourde** [comment]
I believe this is not longer happening and I confirmed it via a deployed sensu-staging environment.
