### ISSUE TITLE
User API missing namespace argument

### ISSUE THREAD

**Issue by schampseix** [sensu/sensu-go#2561]
https://github.com/sensu/sensu-go/blob/3731bcda2c40b39f162675dad0fa269b761e9da5/api/core/v2/user.go#L42

Hi the user api for POST method is not working looks like namespace is missing in the code url. 

My request : 
curl -v -s -H "Authorization:$(tkn)" --data @user.json -X POST https://sensu-dashboard.staging.monitoring.com:8080/api/core/v2/techops/users/

* upload completely sent off: 122 out of 122 bytes
< HTTP/1.1 404 Not Found
< Date: Wed, 19 Dec 2018 09:18:32 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 33
< Connection: keep-alive
< 
{"code":2,"message":"not found"}

**Comment by nikkiki** [comment]
Users are not a namespaced resource type (see [https://docs.sensu.io/sensu-go/5.0/reference/rbac/#namespaced-resource-types](namespaced resource types) and [https://docs.sensu.io/sensu-go/5.0/api/users/](users api docs)).
