### ISSUE TITLE
Capture GOARM build time flag as part of System information

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2565]
golang GOARCH is not sufficient to when trying to filter assets running on ARM systems

go compile time requires GOARM to be set when GOARCH='arm' to build correctly for
ARMv5, ARMv6, and ARMv7

Reference:
https://github.com/golang/go/wiki/GoArm

We need a way to capture the value of GOARM at build time and make it part of entity.system
for agent and backend binaries.

That way asset built for armv5-7 can be correctly filtered for people using community builds of sensu-go.

## Expected Behavior
build sensu-go-agent for ARMv5 and ARMv7
write asset configs that filter like `entity.system.arm == '5'  and entity.system.arch == 'arm' `
to specify its armv5 asset.

## Current Behavior
No way to filter assets for ARMv5 from ARMv7 at present

## Possible Solution
Capture value of GOARM env from go build system when cross-compiling.
If native compiling use the GOARM value go build determines is most correct for the host.

Note this does not yet impact arm64 as it is only available for ARMv8... but futureproofing for ARMv9 and beyond will probably require GOARM to be captured for arm64 as well.

**Comment by amdprophet** [comment]
This was implemented in https://github.com/sensu/sensu-go/pull/3206.
