### ISSUE TITLE
[Web UI] TypeError: Failed to fetch

### ISSUE THREAD

**Issue by kudipudi** [sensu/sensu-go#2572]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

**Web UI Stack Trace:**

at `undefined` (TypeError: Failed to fetch:undefined)

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `8ad0479`
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by annaplotkin** [comment]
@kudipudi Can you please put more repro steps and information into this ticket describing your error scenario? This will helps us repro on our end so we can address. Thanks!

**Comment by jaredledvina** [comment]
I also get this, I think what's happened with my setup is that my proxy server (Traefik in this case) had died. In an incognito window, loading my Sensu Go setup completely failed but, in my regular window, it tried to load with an error:
<img width="549" alt="Screen Shot 2019-05-01 at 9 18 08 AM" src="https://user-images.githubusercontent.com/15491304/57018603-2a73ca80-6bf2-11e9-9608-a21f27bf88c1.png">

```
/auth/token:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
2main.a4489b6a.js:60 Uncaught Error: Network error: 0
    at new ApolloError (main.a4489b6a.js:7)
    at main.a4489b6a.js:60
    at main.a4489b6a.js:60
    at Array.forEach (<anonymous>)
    at main.a4489b6a.js:60
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (main.a4489b6a.js:60)
    at main.a4489b6a.js:60
    at tryCatcher (main.a4489b6a.js:60)
    at Promise._settlePromiseFromHandler (main.a4489b6a.js:60)
    at Promise._settlePromise (main.a4489b6a.js:60)
    at Promise._settlePromise0 (main.a4489b6a.js:60)
    at Promise._settlePromises (main.a4489b6a.js:60)
    at Async._drainQueue (main.a4489b6a.js:60)
    at Async._drainQueues (main.a4489b6a.js:60)
    at Async.drainQueues (main.a4489b6a.js:60)
```

@annaplotkin - I _think_ this just has to do with caching the assets client side, and then not handling the above error. Hope that helps happy to grab more info too.

**Comment by annaplotkin** [comment]
@jaredledvina This is great, thanks for the additional info! We'll take a look 👍

**Comment by annaplotkin** [comment]
We would like to verify that this is still an issue with a more recent build. More comments to come

**Comment by jamesdphillips** [comment]
Hey, @jaredledvina from the SHA included in you screenshot it appears as if you are running release ~ `v5.2.0`. A fix for the error you encountered _should_ have been fixed in `v5.4.0`.

Could you confirm which the version of your Sensu Go cluster?

**Comment by jaredledvina** [comment]
Ah, it looks like because of https://github.com/sensu/sensu-go/issues/2715 by sensu-backend process hasn't restarted in a looong time but, has been getting upgraded. 

Anyway, I went ahead and restarted `sensu-backend` and now, when my proxy server (Traefik) is stopped the UI logs:
```
POST https://snip.fqdn/graphql net::ERR_CONNECTION_REFUSED
Uncaught Error: Network error: 0
    at new ApolloError (vendor_a994.js:89)
    at QueryManager.<anonymous> (vendor_a994.js:89)
    at step (vendor_a994.js:104)
    at Object.next (vendor_a994.js:104)
    at vendor_a994.js:104
    at Promise.n._execute (vendor_a994.js:89)
    at Promise._resolveFromExecutor (vendor_a994.js:89)
    at new Promise (vendor_a994.js:89)
    at __awaiter (vendor_a994.js:104)
    at vendor_a994.js:89
    at vendor_a994.js:89
    at Array.forEach (<anonymous>)
    at vendor_a994.js:89
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (vendor_a994.js:89)
    at QueryManager.<anonymous> (vendor_a994.js:89)
```
<img width="1440" alt="Screen Shot 2019-05-06 at 3 43 04 PM" src="https://user-images.githubusercontent.com/15491304/57250529-a8323e80-7015-11e9-9fd5-1ccf0c02198e.png">

And then on reload, Chrome cleanly fails with `ERR_CONNECTION_REFUSED`. So, I think this is much better and defer to you folks if you want to catch ^ as well. 

```
❯ aptitude show sensu-go-backend
Package: sensu-go-backend
Version: 5.6.0-2141
New: yes
State: installed
Automatically installed: no
Priority: optional
Section: Network
Maintainer: Sensu, Inc. <support@sensu.io>
Architecture: amd64
Uncompressed Size: 38.3 M
Description: Sensu Go Backend

Homepage: https://sensu.io
```
```
❯ sensuctl version
sensuctl version 5.6.0#4bd3afc, build 4bd3afcf64de3cb73bb12e9712c7e537a9a3144d, built 2019-04-26T22:22:22Z
```

Noting that , https://github.com/sensu/sensu-go/issues/1739 would have helped me realize the backend was outdated for this as well.

**Comment by jamesdphillips** [comment]
Unfortunately, the offline banner shipped in parallel with the landing page and didn't inherit that functionality. This bug however has now been fixed and will ship with 5.7, coming in a couple days.

**Comment by jamesdphillips** [comment]
As noted above, we should probably prioritize the work related to exposing the current version in web/CLI. Otherwise, I think it is now safe to close this issue.

**Comment by jaredledvina** [comment]
Sounds good! Thanks @jamesdphillips !

**Comment by execptionerror** [comment]
[[Solved] Getting “TypeError: Failed to fetch” when the request hasn’t actually failed
](https://exerror.com/getting-typeerror-failed-to-fetch-when-the-request-hasnt-actually-failed/)
