### ISSUE TITLE
Understanding when `sensuctl configure` would need to be re-run

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2578]
This is more of an inquiry than an issue.  I've noticed I can change the `admin` password and I do NOT have to re-run `sensuctl configure` with the new password to continue using `sensuctl`.  I'm assuming the access and refresh tokens are somehow functioning regardless of the password change.  I wanted to make sure this is intentional design of sensuctl and not a bug or oversight as I am updating the sensu-puppet module with the assumption I don't have to re-run `sensuctl configure` if someone changes the admin password.

## Context

Working with @ghoneycutt on sensu-puppet module and would like to be sure design decisions for the module are using features and and not bugs in sensuctl.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.0
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by palourde** [comment]
We no longer maintain an access list of tokens as of 5.15.0 so I'll close this issue since it's now working as expected.
