### ISSUE TITLE
[Web UI] Feature request: display labels

### ISSUE THREAD

**Issue by bbomgardner** [sensu/sensu-go#2581]
Labels are a key feature for filtering and check templates, etc. however they are not visible in the dashboard.

## Expected Behavior
Labels visible in entity page and as filterable criteria in table view.

## Current Behavior
Labels not in dashboard

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.0
* Installation method (packages, binaries, docker etc.): rpm
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.6

**Comment by annaplotkin** [comment]
Support for displaying labels is now live! 🎉Let us know if you are still seeing issues.

**Comment by bbomgardner** [comment]
Thank you very much!
