### ISSUE TITLE
"Enterprise license not found" message is misleading

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2582]
## Expected Behavior

Messages logged at `error` level should indicate an actionable error.

## Current Behavior

Without an enterprise license installed, sensu-backend logs this message at `error` level:

```
{"component":"ee-licensing","level":"error","msg":"No enterprise license found","time":"2019-01-02T18:07:57
```

## Possible Solution

Change log level for this message to `info`

## Steps to Reproduce (for bugs)
1. Install sensu-backend
2. Start sensu-backend
3. Observe "No enterprise license found" at error level in sensu-backend logs

## Context

Logging this message as an error is causing users to think that something is wrong, when in fact there's no enterprise license by default.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by echlebek** [comment]
Agreed. Arguably, this message should be logged at Info level.

**Comment by palourde** [comment]
This made sense when we expected to ship two binaries, but since sensu-go is now shipped from the enterprise codebase, it is no longer the case. I already made this change in the changes I've made last week so I'll just assign myself this issue!
