### ISSUE TITLE
sensuctl won't delete hook (or other resources) without specifying namespace

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#2583]
When attempting to delete a hook in the current namespace, it shouldn't be required to specify namespace via the --namespace argument to sensuctl.  Is this wrong?  Or is it working as designed?  If it is working as designed then documentation needs to be updated to reflect this and the code for argument checking should require it and usage and error output should list it is such.

## Expected Behavior

'sensuctl hook delete hook_name' should delete a hook in the current namespace.

Or it should error out better about requiring namespace.
```
# sensuctl hook delete linux-process-list-hook --skip-confirm
delete hooks given name

Usage:  sensuctl hook delete [NAME] [flags] --namespace string

Flags:
  -h, --help           help for delete
      --skip-confirm   skip interactive confirmation prompt

Global Flags:
      --api-url string      host URL of Sensu installation
      --cache-dir string    path to directory containing cache & temporary files (default "/root/.cache/sensu/sensuctl")
      --config-dir string   path to directory containing configuration files (default "/root/.config/sensu/sensuctl")
      --namespace string    namespace in which we perform actions (default "default"), required for delete

Error: --namespace required for delete
```

## Current Behavior

If you don't specify a namespace via the --namespace argument, running 'sensuctl hook delete hook_name' fails with "Error: not found".
## Steps to Reproduce (for bugs)

1. Create a hook in a non-default namespace
```
# cat hook.json
{
  "type": "HookConfig",
  "api_version": "core/v2",
  "spec": {
    "command": "/usr/bin/top -b -n 1 | head -20",
    "timeout": 30,
    "stdin": false
  },
  "metadata": {
    "name": "linux-process-list-hook",
    "namespace": "AWS"
  }
}

# sensuctl create -f hook.json
```
2. Confirm that your sensuctl is configured for that namespace
```
# sensuctl config view                          
=== Active Configuration
API URL:       http://127.0.0.1:8080
Sensu Edition: enterprise
Namespace:     AWS
Format:        tabular
```
3. Confirm the hook exists
```
# sensuctl hook info linux-process-list-hook
=== linux-process-list-hook
Name:      linux-process-list-hook
Command:   /usr/bin/top -b -n 1 | head -20
Timeout:   30
Stdin?:    false
Namespace: AWS
```
4. Attempt to delete the hook without specifying the current namespace
```
# sensuctl hook delete linux-process-list-hook --skip-confirm
Error: not found
```
5. Delete the hook specifying the current namespace
```
# sensuctl hook delete linux-process-list-hook --skip-confirm --namespace AWS
OK
```

## Context

Minor annoyance that should be fixed.  The main reason being that if other sensuctl commands work without --namespace (e.g. sensuctl hook info hook_name), then they all should or if namespace is required for deletion then the error should state this and usage and documentation should reflect this.

In reviewing the code for most commands' delete subcommands, I am seeing the following snippet in delete.go:

```
                        if namespace, _ := cmd.Flags().GetString("namespace"); namespace != "" {
                                hook.Namespace = namespace
```
This to me makes it seem that this may be working as designed as this same code is missing from info.go. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensuctl version 5.1.0#b2ea9fc, build b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, built '2018-12-18T21:31:11+0000'
sensu-backend version 5.1.0#b2ea9fc, build b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, built '2018-12-18T21:31:11+0000'
* Installation method (packages, binaries, docker etc.):  packages
* Operating System and version (e.g. Ubuntu 14.04):  Ubuntu 16.04

**Comment by echlebek** [comment]
There is certainly some inconsistency here. Thanks for filing this issue.
