### ISSUE TITLE
[Web UI] Can't show more than 100 entities per page

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2592]
When a user tries to configure the page to display more than 100 entities (and more than 100 entities exist), an error is displayed.

![image 1](https://user-images.githubusercontent.com/1633772/50801773-21ee3180-129b-11e9-9446-24c5af2b1e14.png)

**Comment by craigpfeiffer** [comment]
Just to add to this... After ramping up to 548 agents I am getting the same error if I display anymore than 15 entities per page.
