### ISSUE TITLE
Epic - Audit of data displayed in the Web UI

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2594]
Business case: To ensure we are providing the expected data to our users in the Web UI, we would like to do an audit of the following: 

1. Data that we send [backend]
2. Data that we display on the WebUI and which page.
3. Organized diff of the deltas between the two. 

Once this audit is complete, we can move on to the next steps of prioritizing showing the proper data in a thought-out and consistent way. 

Parent of #2671
Parent of #2670
Parent of #2669
Parent of #2668
Parent of #2667
Parent of #2666
Parent of #2687

**Comment by jamesdphillips** [comment]
@annaplotkin https://docs.google.com/document/d/1blo8zcCKUgQzQvJnxeIo5x3hYD-Uwg0S-Vot6vMfbZE
