### ISSUE TITLE
Add pagination to the HTTP API

### ISSUE THREAD

**Issue by RamblingCookieMonster** [sensu/sensu-go#2604]
At the moment, I can't find clear guidance on pagination.  Will the Sensu Go API simply not use pagination?  Will it be added at some point with breaking changes to code written with the assumption of no paging?

I didn't see an issue on the API side, figured it would be worth having something others can search and find

## Expected Behavior

* Pagination behavior is documented
* There is a roadmap of sorts for API basics, if there are plans in place (paging, auth in particular)

## Current Behavior

* No docs on paging, presumably no support for paging?

## Possible Solution

* Add paging, or let us know if it's not something you plan to implement (eek!)?

Thanks!

**Comment by echlebek** [comment]
We do plan to implement paging, but have not gotten around to it yet. We don't expect supporting it to be a breaking change. Thanks for filing this!

**Comment by echlebek** [comment]
Pagination spec here: https://docs.google.com/document/d/1R8AtkOjJJgZD0cMgZDypNiYrn-bl6ing9YzOWsLHqro/edit?usp=sharing
