### ISSUE TITLE
proxy_entity_name not honored in results submitted via agent socket

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2605]
## Expected Behavior

Providing `proxy_entity_name` attributes in a check result submitted via agent socket will cause the result to be associated with the named proxy entity. The named proxy entity will be created if it does not already exist.

## Current Behavior

Providing `proxy_entity_name` in a check result submitted via agent socket neither associates the result with an existing named proxy entity, nor creates the named proxy entity.

### non-existent proxy entity case

1. send a check result to the client socket, including the `proxy_entity_name` attribute with a value that does not match the name of an existing proxy entity. e.g.

`echo '{"name": "test_check", "status": 2, "output": "test is critical!", "spec": { "proxy_entity_name": "new_entity" } }' | nc 127.0.0.1 3030`

2. use `sensuctl event list` to observe that the result sent to the agent socket creates an event associated with the running agent entity, not the named proxy entity.
3. use `sensuctl entity list` to observe that the named proxy entity has not been created

### existing proxy entity case

1. send a check result to the client socket, including the `proxy_entity_name` attribute with a value that matches the name of an existing proxy entity. e.g.

`echo '{"name": "test_check", "status": 2, "output": "test is critical!", "spec": { "proxy_entity_name": "existing_entity" } }' | nc 127.0.0.1 3030`

2. use `sensuctl event list` to observe that the result sent to the agent socket creates an event associated with the running agent entity, not the existing named proxy entity.

## Context

This behavior seems to be inconsistent with expected behavior. 

[Agent socket input specification](https://docs.sensu.io/sensu-go/5.1/reference/agent/#socket-input-specification) states that the JSON check result body may include:
> Any other attributes supported by the Sensu check specification

The [check specification](https://docs.sensu.io/sensu-go/5.1/reference/checks/#spec-attributes) includes `proxy_entity_name` under the `spec` attributes. I have tried specifying the `proxy_entity_name` attribute in both the `spec` scope and the top-level of the check result. The result is the same in either case.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): Sensu Go 5.1
* Installation method (packages, binaries, docker etc.): official packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by portertech** [comment]
We have deprecated this socket in favour of the agent's API, this is documented https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/agent/#create-observability-events-using-the-agent-tcp-and-udp-sockets Will not fix.
