### ISSUE TITLE
Error when running sensu-backend in shell the C-c out

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#2606]
## Expected Behavior
Process exits normally (I guess).

## Current Behavior
Currently if you have the `sensu-backend` stopped, then run `sudo sensu-backend start`. It starts normal. But then a ctcl-c out of the process results in an additional error message:

```
{"component":"sensu-etcd","error":"error creating backend ID: error granting lease: context canceled","level":"error","msg":"error generating backend ID","time":"2019-01-14T20:52:13Z"}
```
## Possible Solution
Find out if the error message is suppose to happen or is harmful/misleading.
I was made aware that this message has been seen in other contexts by @cwjohnston.

## Steps to Reproduce (for bugs)
Use the vagrant file and shell script here:

https://gist.github.com/rgeniesse/54cc19f767e7fc6d257b6d2486e1fc6e

Once up, `vagrant ssh`, `sudo systemctl stop sensu-backend`, `sudo start sensu-backend`, wait for Enterprise license error, then control-c out of the process.

## Context
Originally seen in:

https://secure.helpscout.net/conversation/753880982/12847

## Your Environment
See gist for details on OS. Ran on Sensu Go 5.1 for agent/backend/sensuctl.

**Comment by echlebek** [comment]
This is a bug, but fairly harmless. We probably need to do some QA around our process kill behaviours in various places. Do you happen to know what status the process exited with?

**Comment by echlebek** [comment]
@rgeniesse is this still an issue?

**Comment by rgeniesse** [comment]
Just tried on 5.18.1 and the error no longer happens. Things appear to exist cleaner. Closing!
