### ISSUE TITLE
Proxy check requests for different hosts cannot share an agent

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2612]
The documented use case for proxy checks is for pinging switches that can't run a Sensu agent, however pinging multiple switches from a single proxy agent is not supported which seriously limits the usefulness of this feature. As it currently stands, one would need to run a separate agent process for each proxy target they want to run a ping check against.

## Expected Behavior
Given the following check config:
```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "spec": {
    "metadata": {
      "name": "switch_ping",
      "namespace": "default"
    },
    "command": "check_ping.py --hostname {{ .labels.hostname }}",
    "subscriptions": [
      "{{ .labels.colo }}"
    ],
    "handlers": [],
    "publish": true,
    "interval": 60,
    "proxy_requests": {
      "entity_attributes": ["entity.labels.indexOf('colo1') >= 0"]
    }
  }
}
```
A new check request will be generated for each entity matching the `entity_attributes` field, as expected, and in this case will all be sent to the `colo1` pubsub channel.

Running a single agent with the `colo1` subscription (as one might as a proxy node for all their switches in a single colo, as a separate agent per switch is somewhat overkill) I would expect the check to successfully execute for all matched entities every 60s.

## Current Behavior
The check executes intermittently for some entities, with an apparent race condition controlling which entities are successfully checked.

Relevant logs:
```
Jan 17 10:00:50 lab sensu-agent[1725]: {"component":"agent","level":"info","msg":"message received","payload":"{\"config\":{\"command\":\"check_ping.py --hostname host1\",\"handlers\":[],\"high_flap_threshold\":0,\"interval\":60,\"low_flap_threshold\":0,\"publish\":true,\
"runtime_assets\":null,\"subscriptions\":[\"colo1\"],\"proxy_entity_name\":\"host1\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":0,\"timeout\":0,\"proxy_requests\":{\"entity_attributes\":[\"entity.subscriptions.indexOf('colo1') \\u003e= 0\"],\"splay\":false,\"splay_coverage\":0},\"round_robin\":false,\"output_metric_format\":\"\",\"output_metric_handlers\":null,\"env_vars\":null,\"metadata\":{\"name\":\"switch_ping\",\"namespace\":\"default\",\"labels\":null,\"annotations\":null}},\"assets\":null,\"hooks\":null,\"issued\":1547737250}","time":"2019-01-17T10:00:50-05:00","type":"check_request"}             Jan 17 10:00:50 lab sensu-agent[1725]: {"component":"agent","level":"info","msg":"scheduling check execution: switch_ping","time":"2019-01-17T10:00:50-05:00"}
Jan 17 10:00:50 lab sensu-agent[1725]: {"component":"agent","level":"info","msg":"message received","payload":"{\"config\":{\"command\":\"check_ping.py --hostname host2\",\"handlers\":[],\"high_flap_threshold\":0,\"interval\":60,\"low_flap_threshold\":0,\"publish\":true,\
"runtime_assets\":null,\"subscriptions\":[\"colo1\"],\"proxy_entity_name\":\"host2\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":0,\"timeout\":0,\"proxy_requests\":{\"entity_attributes\":[\"entity.subscriptions.indexOf('colo1') \\u003e= 0\"],\"splay\":false,\"splay_coverage\":0},\"round_robin\
":false,\"output_metric_format\":\"\",\"output_metric_handlers\":null,\"env_vars\":null,\"metadata\":{\"name\":\"switch_ping\",\"namespace\":\"default\",\"labels\":null,\"annotations\":null}},\"assets\":null,\"hooks\":null,\"issued\":1547737250}","time":"2019-01-17T10:00:50-05:00","type":"check_request"}
Jan 17 10:00:50 lab sensu-agent[1725]: {"component":"agent","error":"check execution still in progress: switch_ping","level":"error","msg":"error handling message","time":"2019-01-17T10:00:50-05:00"}
```
What happens here is that checks are scheduled and received by the single agent for both `host1` and `host2`. The check for `host1` starts, and then the check for `host2` fails with the error `"check execution still in progress: switch_ping"`.

## Possible Solution
This appears to be triggered by this block of code:
https://github.com/sensu/sensu-go/blob/master/agent/check_handler.go#L30-L48

Maybe a better solution is to use the combination of the check name and the proxy entity name as a key to `a.inProgress`? This would still provide protection against multiple checks when not proxying them, but would allow one to have a single proxy agent running the same check against multiple different hosts. This is also much more like how Nagios schedules and manages checks in my experience.

## Context
I want to run agents at a different ratio to switches than 1:1 (more likely one agent per colo or similar sort of logical grouping). Running individual agents for each proxy entity adds significant configuration and management overhead for no gain, since the load on a single agent in this setup will be minimal anyway. I suspect this is common (and iirc is how proxy checks worked in Sensu 1 since I didn't have this problem before with the previous, non-sensu-go, test cluster).

## Your Environment
Running 2.0.0-beta.8-1 backend and agent, but this issue is present on master.

**Comment by echlebek** [comment]
Thank you for this insightful bug report and analysis. We should be able to fix the issue in the way you describe.

**Comment by cwjohnston** [comment]
hi @roganartu, thanks again for reporting this issue. I think the change that @echlebek is working on is appropriate to ensure reasonable behavior by default, but in the meantime I wanted to add a workaround that might help 

In most cases you should be able to work around the limitation you've described by making use of `splay` and `splay_percentage` [Proxy requests attributes](https://docs.sensu.io/sensu-go/5.1/reference/checks/#proxy-requests-attributes).

Here's your example check definition with `splay` and `splay_coverage` attributes added:

```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "spec": {
    "metadata": {
      "name": "switch_ping",
      "namespace": "default"
    },
    "command": "check_ping.py --hostname {{ .labels.hostname }}",
    "subscriptions": [
      "{{ .labels.colo }}"
    ],
    "handlers": [],
    "publish": true,
    "interval": 60,
    "proxy_requests": {
      "entity_attributes": ["entity.labels.indexOf('colo1') >= 0"],
      "splay": true,
      "splay_coverage": 50
    }
  }
}
```

Specifying `splay: true` and `splay_coverage: 50` tells Sensu to schedule these checks evenly over the 30 seconds (50 percent of the 60 second interval) following the scheduled execution request. Depending on how many proxy entities match, you may need to increase the splay coverage to fit all the executions into the 60 second interval, or increase the interval as well.

Hope this helps!

**Comment by roganartu** [comment]
I don't think this is resolved. It appears to work correctly on the first scheduled check after the agent is restarted, but subsequent checks fail due to a check already running.

With the same check config as given above, the logs now show the following immediately after the agent is restarted:
```
Feb 08 14:08:53 agent1 sensu-agent[24528]: {"component":"agent","level":"info","msg":"message received","payload":"{\"config\":{\"command\":\"/sensu/python/bin/check_ping.py --hostname switch1\",\"handlers\":[],\"high_flap_threshold\":0,\"interval\":60,\"low_flap_threshold\":0,\"publish\":true,\"runtime_assets\":null,\"subscriptions\":[\"colo1\"],\"proxy_entity_name\":\"switch1\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":120,\"timeout\":30,\"proxy_requests\":{\"entity_attributes\":[\"entity.subscriptions.indexOf('colo1') \\u003e= 0\"],\"splay\":false,\"splay_coverage\":0},\"round_robin\":false,\"output_metric_format\":\"\",\"output_metric_handlers\":null,\"env_vars\":[],\"metadata\":{\"name\":\"switch_ping\",\"namespace\":\"default\"}},\"assets\":null,\"hooks\":null,\"issued\":1549652933}","time":"2019-02-08T14:08:53-05:00","type":"check_request"}
Feb 08 14:08:53 agent1 sensu-agent[24528]: {"component":"agent","level":"info","msg":"scheduling check execution: switch_ping","time":"2019-02-08T14:08:53-05:00"}
```

```
Feb 08 14:09:53 agent1 sensu-agent[24528]: {"component":"agent","level":"info","msg":"message received","payload":"{\"config\":{\"command\":\"/sensu/python/bin/check_ping.py --hostname switch1\",\"handlers\":[],\"high_flap_threshold\":0,\"interval\":60,\"low_flap_threshold\":0,\"publish\":true,\"runtime_assets\":null,\"subscriptions\":[\"colo1\"],\"proxy_entity_name\":\"switch1\",\"check_hooks\":null,\"stdin\":false,\"subdue\":null,\"ttl\":120,\"timeout\":30,\"proxy_requests\":{\"entity_attributes\":[\"entity.subscriptions.indexOf('colo1') \\u003e= 0\"],\"splay\":false,\"splay_coverage\":0},\"round_robin\":false,\"output_metric_format\":\"\",\"output_metric_handlers\":null,\"env_vars\":[],\"metadata\":{\"name\":\"switch_ping\",\"namespace\":\"default\"}},\"assets\":null,\"hooks\":null,\"issued\":1549652993}","time":"2019-02-08T14:09:53-05:00","type":"check_request"}
Feb 08 14:09:53 agent1 sensu-agent[24528]: {"component":"agent","error":"check execution still in progress: switch_ping","level":"error","msg":"error handling message","time":"2019-02-08T14:09:53-05:00"}
```

If we look at the journal logs, the most recent check scheduled for _any_ host was during the initial scheduling that came after the agent restart:
```
╰ sudo journalctl -u sensu_agent --since 14:08:52 --until 14:11:00 | rg "scheduling check execution" | tail -n 1
Feb 08 14:08:53 agent1 sensu-agent[24528]: {"component":"agent","level":"info","msg":"scheduling check execution: switch_ping","time":"2019-02-08T14:08:53-05:00"}
```
So the second round of checks requested by the server at 14:09:53 failed to schedule any checks as the agent believes a check is running for every proxy host. The checks are definitely not running at 14:09:53 for two reasons:
1) the check timeout is set to 30s, so if they were still running Sensu should've killed them already
2) on agent restart, after it successfully schedules the checks for each proxy host, the dashboard clears all the alerts for the check that were caused by expired TTL.

Looking at the PR, it appears to be caused by this line: https://github.com/sensu/sensu-go/pull/2625/files#diff-28127dce0084ee51f4ac4de5c3995ab8R71

The check is scheduled using the new `checkKey` hashing function, and that is what is checked, but the check name is still what's deleted from the map so the check mutex is never released.

**Comment by m8ndevops** [comment]
i installed sensu-agent using docker in client machine but it does not detect the client machine it shows the ip of the sensu-agent docker container, what would be the problem?
