### ISSUE TITLE
Add `sensuctl delete`, which works similarly to `sensuctl create`, but deletes resources

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2613]
`sensuctl create --file` is great for creating/updating checks from a list of provided config files, but it can't be used on its own to enforce a config-as-code setup because it doesn't delete things that are no longer present in the provided JSON files.

## Expected Behavior
Given a JSON file with two check definitions in it, for the sake of simplicity lets call the checks `check1` and `check2`.

1. Run `sensuctl create --file checks.json` to create the two checks if they are missing, or update them to match the provided definitions if they already exist.
2. Delete the definition of `check1` from the JSON file
3. Run `sensuctl create --file checks.json --delete checks` to sync Sensu with the provided JSON file by deleting `check1` as it is no longer present

This enables one to have a CI deployment like the following to enforce config-as-code:
```
sensuctl create --file /path/to/checks/*.json --delete checks
sensuctl create --file /path/to/filters/*.json --delete filters
...
```
or alternatively, if the desire is to control all resources with JSON files:
```
sensuctl create --file /path/to/all/config/*.json --delete all
```

## Current Behavior
Currently `sensuctl create` can only be used to create or update checks, not delete them.

## Possible Solution
`sensuctl create --delete` is a little confusing. Perhaps adding a new command like `sensuctl sync checks --file /path/to/checks/*.json` would be better.

## Context
The way to workaround this problem atm if you want config-as-code is to use `sensuctl create` to create resources, and then run a homemade script that parses the JSON files for a list of resource names, hits the Sensu API, and issues DELETE requests for each item that is present in Sensu but not in the JSON files.

`sensuctl create` is already most of the way to this solution and I think it makes sense for it to close the gap so users don't all reinvent the same wheel.

**Comment by echlebek** [comment]
@annaplotkin, this is a good point about a gap in the `sensuctl create` UX. We should implement the suggestion, or think about other ways to address this use case.

**Comment by jkerry** [comment]
the ability to do a "complete" deployment with an enforced delete makes sense but imo it almost requires an inheritance mechanism for sensu objects. We've been organizing repositories of check configuration by platforms and customers.

base_windows repo:  contains basic checks for all windows hosts under a "windows" subscription
iis repo:  Contains checks specific to IIS operation, which is a superset of windows. "iis" subscription.
application A repo:  checks for application A, runs on IIS
application B repo:  checks for application B, runs on IIS

In a scenario like this I'd almost want a sensuctl manifest / lock file that lists git tags to pull for each of these that can be enforced idempotently (Similar to Chef's policyfiles feature)

**Comment by echlebek** [comment]
We need a way to generically delete resources, so I'm commandeering this issue in service of that goal.

Goals
=====
Add a command to the cli called `sensuctl delete`. The `sensuctl delete` tool should take the same options as `sensuctl create`, and it should work in the same way, parsing resource definitions so that the system can issue `DELETE` API calls.

Non-goals
=========
It is not the goal of this tool to have behaviours like "delete all resources", or "delete all resources except the ones present". We think this would go against the grain of REST, in that it would require an RPC side-effecting protocol.

Thanks @roganartu for filing the initial issue and advocating some potential solutions!
