### ISSUE TITLE
Release tags missing or unrelated to releases

### ISSUE THREAD

**Issue by thefloweringash** [sensu/sensu-go#2621]
I'm trying to build the 5.1.0 release from source, but I can't find the corresponding release tag.

 - The latest release in this repo is `2.0.0-beta.8-1` from November 16
 - The 5.1.0 release was on December 19
 - Inspecting the docker image for 5.1.0
   - the dashboard reports version 74e65cb which is approximately the right time
   - the backend reports version b2ea9fcdb21e236e6e9a7de12225a6d90c786c57, which is not present in this repository.

## Context
I'm hoping to package this for a smaller linux distribution, which prefers to build things from source instead of distributing pre-built binaries.

**Comment by echlebek** [comment]
Hi, thanks for filing this issue.

I've added tags for the 5.x.y releases. This was a bit of an oversight as we started vendoring sensu-go into a private repository, which we are releasing the official binaries from. (This is to enable enterprise integration.)

We've discussed the need of continuing to tag sensu-go going forward, and will be creating tags for subsequent sensu-go releases.

Tags are available here: https://github.com/sensu/sensu-go/tags
