### ISSUE TITLE
100% CPU usage after a random period of time

### ISSUE THREAD

**Issue by Surian** [sensu/sensu-go#2635]
## Expected Behavior

Sensu backend should run normally.

## Current Behavior

After a random period of time (can be lass than 2 hours or more than 12 hours), the sensu-backend process start to consume 100% of the CPU available on the virtual machines.

A restart of the process solves the problem until the next time. CPU is normally around 5% usage (there is only a few agents registered and only 3/4 checks per agents for now).

## Steps to Reproduce (for bugs)

This bug is totally random.

There is nothing abnormal in the logs. The backend still works as expected (scheduling checks, handling events, etc) but the sensu-backend process is taking 100% of the CPU.

## Context
Backend configuration:
```
# general configuration
state-dir: "/var/lib/sensu"

# etcd cluster configuration
etcd-advertise-client-urls: "http://sensu-etcd-cluster.staging.monitoring.xxx.com:2379"
no-embed-etcd: true

# deregistration
deregistration-handler: "deregister"

# logging
log-level: "debug"
```
## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.0
* Installation method (packages, binaries, docker etc.): Ubuntu packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

Backends are on AWS EC2 instances behind an ALB. etcd cluster is accessed through a NLB also on EC2 instances.

**Comment by schampseix** [comment]
Hi @Surian ,

As discussed with sensu team on slack channel I got this feedback : 
`palourde   [3 days ago]
Hi @Yakhatape! We might have identified a CPU/network consumption problem whenever the web UI is used by multiple users. Have you tried to switch the dashboard users to an another backend and see if the CPU overload moves to this new backend? `

I explain to sensu team our architecture in place (backend clustering) for agent and the backend standalone(for user dashaboard access and CLI) : 

`palourde   [3 days ago]
I see, interesting, thanks for sharing this with us, I’ll let the rest of the team know.`

`Eric   [3 days ago]
Hi @Yakhatape, would you be interested in helping us debug this problem? I can instruct you on how to capture a CPU profile which would show us where in the application the high usage is occurring.`

I will try to keep some times to debug this point with them.

I keep you informed if anythings news is come to me

**Comment by schampseix** [comment]
Hi @echlebek 
You can find below the file requested about our CPU issue on backend side.
[debug-trace-CPU100.zip](https://github.com/sensu/sensu-go/files/2884467/debug-trace-CPU100.zip)

**Comment by echlebek** [comment]
We were finally able to reliably reproduce this bug during a recent QA session. It seems to trigger when watcher errors occur, which should normally be infrequently.

We're investigating a solution and should have more information soon.

**Comment by schampseix** [comment]
WHOUHOUUUUU GOOD NEWS !!!  :+1:  

![image](https://user-images.githubusercontent.com/43807559/55787107-daec2400-5ab5-11e9-99cf-637973934205.png)
