### ISSUE TITLE
POST /events do not create a timestamp (must be provided)

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#2636]
From the Classic to Go gap analysis:

> API Endpoint that allows users to inject events into the event pipeline on an ad-hoc basis, similar to the /request POST endpoint in Sensu 1.x. Currently in Sensu Go, we have POST and PUT endpoints for the Events API, but they don’t generate their own timestamps. (I haven’t tested whether events created by these endpoints are processed by handlers.)

**Comment by echlebek** [comment]
We should fill in the current time when the time is not set, but users should be able to set the time in the request.
