### ISSUE TITLE
Tuning embedded etcd

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2644]
An operator _may_ find it beneficial to configure embedded etcd's storage size `QuotaBackendBytes` and max request size `MaxRequestBytes`.
https://github.com/sensu/sensu-go/blob/66b0502402384f7a5de669513f2e1862473a0e74/backend/etcd/etcd.go#L161-L162 These values can be loaded as backend flags and config file arguments.

Related to https://github.com/sensu/sensu-go/issues/2641

## Expected Behavior
The following command would configure embedded etcd's variables accordingly.
```
sensu-backend start --etcd-max-request-bytes $((1.5 * 1024 * 1024)) --etcd-quota-backend-bytes $((4 * 1024 * 1024 * 1024))
```

## Current Behavior
There is no way to configure embedded etcd's variables with sensu, however using external etcd would probably allow you to do so.

## Possible Solution
Provide config arguments. https://github.com/sensu/sensu-go/issues/2641 solves a similar issue.

## Steps to Reproduce (for bugs)
N/A

## Context
This would allow us to empower operators to tune embedded etcd. Developers may need to better understand the implications of allowing operators to tune embedded etcd rather than using default (and suggested) values.

## Your Environment
N/A

**Comment by ninjasloth22** [comment]
I would also like to be able to tweak things like the heartbeat interval and election timeouts. 
Some way to add additional configuration options to etcd would be great.

**Comment by palourde** [comment]
Closed by https://github.com/sensu/sensu-go/pull/2968
