### ISSUE TITLE
Not logging missing handler

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#2658]
## Expected Behavior
If I define a handler in a check, but the handler itself hasn't been defined, I should see an error in the log telling me that the handler isn't defined.

## Current Behavior
No log message is present when a handler is called that has not been defined.

## Possible Solution
It looks like this might have been an issue previously, but fixed (#1260) - perhaps the issue has resurfaced

## Steps to Reproduce (for bugs)
1. create a check definition with a handler called "jerome"
2. watch check execution in log
3. notice there is no error showing the handler that the check is using has not been defined

## Context
Sometimes folk have typos in their check configs, if we log the issue when a handler is not present, it will make troubleshooting typos, or misconfiguration much simpler.

## Your Environment
sensuctl version 5.1.1#2c617e2, build 2c617e299e9892251763c98dacd00dfd112e9d1d, built '2019-01-24T01:22:11+0000'

**Comment by nikkiki** [comment]
@agoddard It appears that pipelined _should_ be logging an error if the handler is not found in the store: https://github.com/sensu/sensu-go/blob/0150bbcb0a2b70f720fa20a9a47c7e91bacd72b1/backend/pipelined/handle.go#L127-#L134. Are you seeing any logs on the backend related to that, or the check?

**Comment by nikkiki** [comment]
Looks like we need to log the case for if `handler` and `err` are nil.
```
handler, err := p.store.GetHandlerByName(ctx, handlerName)
```

**Comment by agoddard** [comment]
@nikkiki not seeing any errors with debug log level

**Comment by palourde** [comment]
For reference, I've just tried to reproduce this issue and we are now logging something at the _info_ level:

```
{"check_name":"ttl-check","check_namespace":"default","component":"pipelined","entity_name":"whisky.local","entity_namespace":"default","level":"info","msg":"no handlers available","time":"2019-05-29T14:04:10-04:00"}
```
