### ISSUE TITLE
Backup and restore the sensu embedded etcd (etcdctl snapshot save)

### ISSUE THREAD

**Issue by AnthonyCaetano** [sensu/sensu-go#2660]
I don't see how to backup and restore a sensu-go embedded etcd.  Is it possible?

## Expected Behavior
I expect to be able to backup sensu for recovery if the etcd cluster loses quorum (I only have 2 data centres so this is real scenario for me)

## Current Behavior
I can't find any backup option

## Possible Solution
sensuctl cluster snapshot save?
OR
document the backup & restore of sensu based on external etcd?

## Steps to Reproduce (for bugs)
n/a

## Context
I need to ability to backup & restore sensu if the cluster loses quorum.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-go-backend-5.1.1-1
* Installation method (packages, binaries, docker etc.): rpm
* Operating System and version (e.g. Ubuntu 14.04): rhel7.5

**Comment by palourde** [comment]
We do not have any built-in backup solution in sensuctl yet (see https://github.com/sensu/sensu-go/issues/2742). That being said, you can use `etcdctl` directly against etcd by following a guide like https://coreos.com/etcd/docs/latest/op-guide/recovery.html.
