### ISSUE TITLE
Remove extended attributes from types

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#2662]
Labels and Annotations have replaced extended attributes. Objects should no longer reference extended attributes.

Related to #2248 

e.g. Check https://github.com/sensu/sensu-go/blob/6ae633269e8d618d94ce5eebd5870ab430e34dba/api/core/v2/check.proto#L84

**Comment by calebhailey** [comment]
![image](https://user-images.githubusercontent.com/141373/52075218-9df93380-2540-11e9-913d-fcdceb480bdc.png)
