### ISSUE TITLE
updating asset dependency is not reflected in check behavior

### ISSUE THREAD

**Issue by exitquote** [sensu/sensu-go#2678]
## Expected Behavior

When I change an asset dependency of a check by removing the value in the "runtime_assets" array and adding a different value, the asset definition pointed to by the new value should cause the agent to go collect and run the new asset, and the check should no longer require or try to fetch the removed asset.

## Current Behavior

When I change an asset dependency of a check by removing the value in the "runtime_assets" array and adding the new value, this change is reflected in the check definition (i.e., I can query the API and see that the value is what I expect), but the behavior of the check still reflects the old asset (which cannot be deleted, but should have been removed from any association with the check).

Example:  I create a check.  In the runtime_assets array for this check definition, I have the following:

"runtime_assets": [
        "my-old-asset-definition"
]

This works, and the agent downloads the asset.  The asset definition's metadata has the following:

        "metadata": {
            "name": "my-old-asset-definition",
            "namespace": "default"
        }

This works without a problem.

Now, I no longer want to use this asset - the name does not match the convention I have decided to use.  So, I create a new asset with a new name, new hash, new url:

        "metadata": {
            "name": "my-new-asset-defintion",
            "namespace": "default"
        }

I go to my check definition, and change my runtime_asset field to match the new asset, so my check now shows:

   "runtime_assets": [
        "my-new-asset-definition"
    ]

When I retrieve my check with the API, it shows the new asset name, as above.

However, when the check runs, it is clearly still trying to retrieve the old asset, to which the check is ostensibly no longer pointing.  I tested this by updating the OLD asset defintion (my-old-asset-defintion) with a garbage URL and hash.  So to recap, I have the following two asset definitions:

    {
        "url": "http://realurl.harvard.edu/assets/check-opennebula-hypervisors.tar.gz",
        "sha512": "b931aaae27b5783b09d26a77d0db82737a66956896e81b5bbbc58af5887339ed51bbbf5e411612d72dc369f5611429053f442a5c265b6b1c6347497bd60c13df",
        "filters": null,
        "metadata": {
            "name": "my-new-asset-definition",
            "namespace": "default"
        }
    },
    {
        "url": "https://unresolveablegarbage",
        "sha512": "GARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGEGARBAGE",
        "filters": null,
        "metadata": {
            "name": "my-old-asset-definition",
            "namespace": "default"
        }
    },

And my check definition shows:

   "runtime_assets": [
        "my-new-asset-definition"
    ]

But when I run my check, I get 
error getting assets for event: error fetching asset: Get https://unresolveablegarbage: dial tcp: lookup unresolveablegarbage

Something seems to be hanging on to the old asset definition even though I've removed it.

## Steps to Reproduce (for bugs)

I have tried to at least confirm that there is somewhere in the DB that might have this, and I suspect they must still be linked somewhere, but I haven't been able to get a lot of help in Slack for looking into this issue, so haven't yet been able to confirm that this is the case, although I'm working on it.  I am not sure, but I would guess it could possibly be reproduced by creating a check definition, creating an asset, tying the asset to the check definition, creating a new asset, then removing the old asset from the check definition and adding the new one instead; but since I don't know enough about the underlying functionality, I can't say this for sure.

## Context

I'm trying to change the runtime asset that one of my check definitions uses.  I can't delete or rename assets, so I need some way to change which assets a check uses.

## Your Environment
I am running the sensu backend version 5.1.1 in docker with built-in etcd, clustered among 3 machines.  sensuctl and sensu-agent version 5.1.1 installed as binaries.  all machines run centos 7.4.

**Comment by palourde** [comment]
I just tried to reproduce this problem by replacing the asset for a check with `sensuctl check set-runtime-assets $CHECK_NAME $ASSET_NAME` but I confirmed the agent is downloading the right asset. If you still face this problem, please provide us more output and the exact commands/step you are doing. Thanks!

**Comment by nandeeshb09** [comment]
Im facing this issue still...please help me here...the key is automatically generating new one everytime we run the checks.

sensu go version 5.23.1
error getting assets for event: sha512 'd0b8795970a4093a31f6a485d34a92e9408d309817d6f0aa178a96b28ff05a1006b72823a640e2f9921e47296b9c4ab278d13767377ec06bf026d1865d4d5d87' does not match specified sha512: 'a1b9c17a2df0c686f378f6238d2d1180477a66cf908651e9dd3fe253a370e95860496908d47dfb2e773c03787d4bda2ea45cb750f74b7f0b6c6422aded1359f7'
