### ISSUE TITLE
Support environment variables in sensu-backend

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2680]
## Expected Behavior

Specifying a configuration attribute via an environment variable in sensu-backend should work, e.g.

```
SENSU_LOG_LEVEL=debug sensu-backend start
```

## Current Behavior

The environment variables are ignored, in comparison to sensu-agent where it's supported: https://github.com/sensu/sensu-go/blob/321ff41fe8170b37ae4673cce1df2cf29733f702/agent/cmd/start.go#L76-L78

## Possible Solution
We simply need to add the same three lines to the backend/cmd/start.go init function.

## Steps to Reproduce (for bugs)
N/A

## Context
Reported by a user in Slack: https://sensucommunity.slack.com/archives/C9BB9AW7K/p1549309756912700

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.1.1
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by gbolo** [comment]
I recommend we use `viper.SetEnvPrefix("sensu_backend") ` so that any shared variable names can be controlled independently (like log level)
