### ISSUE TITLE
[Web UI] Add annotations and labels

### ISSUE THREAD

**Issue by dabria** [sensu/sensu-go#2687]
We would like to add annotations and labels to the web ui. We want to give our users access to these fields quickly, as to see the many ways they're being used. Following that, we would like to redesign the details pages and display them in a more cohesive and better fitting manner.

* Child of #2594
* Redesign tickets #2670 #2671

## Expected Behavior
Display these fields

## Current Behavior
Doesn't display these fields

## Possible Solution
Display these fields

**Comment by jamesdphillips** [comment]
Related #2674
