### ISSUE TITLE
Add TLS mutual authentication support

### ISSUE THREAD

**Issue by gbolo** [sensu/sensu-go#2689]
When the sensu backend is exposed to the internet for agents to reach it, perhaps having the option for TLS mutual authentication would help with our security posture.

The backend would take it a flag for `mutual-tls-enabled` then also take a flag for `client-ca-file`. The agent can take an additional two flags for `client-cert-file` and `client-key-file`. What else needs to talk to backend?

**Comment by joemiller** [comment]
👍  We would like for the agent to also present an mTLS client cert when fetching assets. This would allow us to more easily create a centralized asset service that performs validation of connecting clients before allowing download of the asset tarballs.

**Comment by portertech** [comment]
@gbolo thank you for opening this issue. We added this functionality to the Sensu Go commercial distribution (completely free up to 100 entities), you can find the documentation at: https://docs.sensu.io/sensu-go/latest/guides/securing-sensu/#sensu-agent-tls-authentication Closing this issue, however, we will investigate using the mTLS client cert when fetching assets (see #3163).
