### ISSUE TITLE
Payloads to agent socket can not find defined handlers

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#2691]
## Expected Behavior
Payloads to agent socket have access to handlers in the same namespace

## Current Behavior
Agent socket appears to not have the ability to find handlers in the same namespace as the event.

https://docs.sensu.io/sensu-go/5.1/reference/agent/#using-the-tcp-socket

Command used:

```
echo '{"name": "check-mysql-status", "output": "error!", "status": 1, "handlers": ["pushbullet"]}' > /dev/tcp/localhost/3030
```

Error when agent socket is used running the above command:
```
Feb 05 22:51:17 sensu-centos sensu-backend[22239]: {"check_name":"check-mysql-status","check_namespace":"default","component":"pipelined","entity_name":"sensu-centos","entity_namespace":"default","level":"info","msg":"no handlers available","time":"2019-02-05T22:51:17Z"}
```

I can get the handler to fire using the events API and a normal check definition that is forced into a non-zero status.

API call:
```
curl -X POST -H 'Content-Type: application/json' -d '{
  "check": {
    "metadata": {
      "name": "check-mysql-status"
    },
    "handlers": [
    "pushbullet"
    ],
    "status": 1,
    "output": "could not connect to mysql"
  }
}' http://127.0.0.1:3031/events
```
Check definition to force non-ok status:
```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "sample-check",
    "namespace": "default"
  },
  "spec": {
    "command": "ls",
    "handlers": ["pushbullet"],
    "interval": 10,
    "publish": true,
    "subscriptions": [
      "pushbullet"
    ],
    "ttl": 0,
    "timeout": 0,
    "env_vars": null
  }
}
```

Handler and Asset used:

```
{
    "api_version": "core/v2",
    "type": "Handler",
    "metadata": {
        "namespace": "default",
        "name": "pushbullet"
    },
    "spec": {
        "type": "pipe",
        "command": "sensu-pushbullet-handler --alldevices",
        "timeout": 10,
        "env_vars": [
            "PUSHBULLET_APP_TOKEN=o.Xi059lX33C6UHCFUj3FJ6cNLQONB1HWh"
        ],
        "filters": [
            "is_incident",
            "not_silenced"
        ],
        "runtime_assets": [ "sensu-pushbullet-handler" ]
    }
}
{
  "type": "Asset",
  "api_version": "core/v2",
  "metadata": {
    "name": "sensu-pushbullet-handler",
    "namespace": "default"
  },
  "spec": {
    "filters": null,
    "sha512": "e20f25994f5da8027d794b208fefda125cd12e5ae095d07764b1e122838b4da2b32b00c0ef1ea0adc34f40527536807e895e5c44114296d7cbedbb88907c8ad1",
    "url": "https://github.com/rgeniesse/sensu-pushbullet-handler/releases/download/1.0.0/sensu-pushbullet-handler_1.0.0_linux_386.tar.gz"
  }
}
```

## Possible Solution
Not sure, but this was possible in 1.x as we used it to show end-to-end tests.

## Steps to Reproduce (for bugs)

Note: I used a Pushbullet handler. I'd expect an email or slack handler to behave the same. Please let me know if I should test those as well and add the results here.

1. Using the above asset and handler definitions, attempt to send a payload to the agent socket.
2. Observe that the handler does not fire.
3.
4.

## Context
Useful for showing end to end tests.
Users also use it to send payloads to the agent socket, so the desire to have those handled is there.
See https://sensucommunity.slack.com/archives/C68LV5M9U/p1549346188192300.

## Your Environment
CentOS 7
Sensu agent, backend and sensuctl 5.1.1.

**Comment by portertech** [comment]
The v1 check result type does not support `handler` or `handlers` (takes precedence): https://github.com/sensu/sensu-go/blob/master/types/v1/check.go

**Comment by shaneshort** [comment]
Is this considered a legacy way of injecting events? Is the HTTP endpoint (which seems to work) considered the right way(tm)?

**Comment by echlebek** [comment]
@shaneshort this is indeed a legacy method - the data structure is intended to be a 1.x CheckResult. However, it looks like this was not properly implemented, and although the docs are consistent with the implementation, both are implementation and the 2.x docs are inconsistent with the 1.x docs.

I'll file a PR against this issue and also a related docs PR.
