### ISSUE TITLE
Epic - Re-enabling round robin scheduling.

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2699]
Epic to house the work required to re-enable round robin scheduling in Sensu Go. 

Proposal document: https://docs.google.com/document/d/1lxgTouMOCOBDJG5ri0Jp2G97banHFRDrRbxA6sj_ZEs/edit

Parent of #2431 
Parent of #2005 
Parent of #2735

**Comment by echlebek** [comment]
Parent of #2735
