### ISSUE TITLE
write IOPS used by etcd doubled between 5.1.1 and 5.2.0

### ISSUE THREAD

**Issue by Surian** [sensu/sensu-go#2707]
## Expected Behavior
Sensu backend 5.2.0 should not make etcd cluster write IOPS raise by a x2 factor compared to Sensu backend 5.1.1.

## Current Behavior
Since our backend servers have been upgraded to 5.2.0, we observed that the write IOPS and throughput consumed by the etcd cluster (external cluster dedicated to our Sensu backends) have doubled.

You can see the graph of our write IOPS and write throughput of one of our 3 etcd node below before and after the upgrade that took place on friday around 10:30AM UTC+1:
http://u.lnk.pm/i/5/1/15497238885cQ-iops-etcd.png
http://u.lnk.pm/i/0/3/1549723880Vvv-throughput-etcd.png

## Steps to Reproduce (for bugs)
1. Get a running 5.1.1 sensu backend with an external etcd cluster with agents and checks running on it
2. Upgrade sensu backend to 5.2.2
3. Compare write IOPS consumed before and after the upgrade

## Context
We have approximatively 180 agents connected to our backends (2 servers) with approximativerly 3500/4000 events.

We dit not changed the configuration before and after the upgrade.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): backend 5.2.0 (agents are still in 5.1.1 version for 95% of them)
* Installation method (packages, binaries, docker etc.): Debian packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

Will be happy to provide more information if needed.

**Comment by echlebek** [comment]
5.2.0 improves durability of check TTL events by writing more information to etcd. Are you using the check TTL feature?

**Comment by Surian** [comment]
We are not using the TTL feature and just in case I just verified, every check has ttl set to 0.

**Comment by echlebek** [comment]
During a recent load testing session we discovered that the system was not correctly guarding against writes when check TTL is disabled, leading to unnecessary writes.

We should be able to resolve this issue in the next release.
