### ISSUE TITLE
Changing a users password should invalid all existing sessions

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-go#2708]
## Expected Behavior
After executing `sensuctl user change-password`, any existing sessions to the dashboard and authenticated `sensuctl` setups should be invalided. 

## Current Behavior
After running `sensuctl user change-password --interactive` my existing dashboard sessions continue to work, and from another computer, I'm still able to use `sensuctl` that was authenticated with the previous password. 

## Possible Solution
Not totally sure as I'm not very familiar with this codebase (yet!). 

## Steps to Reproduce
1. Log into the Sensu dashboard with the default `admin`/`P@ssw0rd!` creds
2. Run `sensuctl user change-password --interactive` and rotate the password
3. Verify that the dashboard is still logged in and fully usable. 

## Context
Tangentially related to https://github.com/sensu/sensu-go/issues/2434, but, the change-password logic really should be revoking all of the existing sessions. In the event that a user's password was leaked, it'd be most ideal to just rotate that password with a guarantee that any existing sessions/configurations with that password are now revoked. 

To add, when https://github.com/sensu/sensu-go/issues/850 is implemented, I would expect that after changing the password, your current session would also be logged out. 

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.0
* Installation method (packages, binaries, docker etc.): Packages
* Operating System and version (e.g. Ubuntu 14.04): Debian 9

**Comment by echlebek** [comment]
We need to invalidate JWTs that are associated with the user whose password is changing.

**Comment by echlebek** [comment]
Due to the design of JWTs, it is not possible to do this. The JWTs now expire every 5 minutes and are stateless, so there is no way to expire them.
