### ISSUE TITLE
metadata.namespace shouldn't be needed to create Role with API

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2716]
When trying to create a Role with the API:
```
$ curl -H 'Content-Type: application/json' -H 'Authorization: <token>' -d '{
  "metadata": {
    "name": "read-only"
  },
  "rules": [
    {
      "resources": ["*"],
      "verbs": ["read"]
    }
  ]
}' http://localhost:8080/api/core/v2/namespaces/default/roles

{"message":"invalid argument(s) received","code":1}
```

`metadata.namespace` needs to be specified for the input to be considered valid:
```
$ curl -H 'Content-Type: application/json' -H 'Authorization: <token>' -d '{
  "metadata": {
    "name": "read-only",
    "namespace": "default"
  },
  "rules": [
    {
      "resources": ["*"],
      "verbs": ["read"]
    }
  ]
}' http://localhost:8080/api/core/v2/namespaces/default/roles

{"rules":[{"verbs":["read"],"resources":["*"],"resource_names":null}],"metadata":{"name":"read-only","namespace":"default"}}
```

I don't see why that is necessary since that namespace can be inferred from the URL.

## Possible Solution

We should set `obj.Namespace` with the value captured in the URL by the router, at this location: https://github.com/sensu/sensu-go/blob/c4ba1e2/backend/apid/routers/roles.go#L46

Other object types might need a similar treatment.

## Context

I came across this while investigating a community member reporting having issues using the API to create a Role ([Slack link](https://sensucommunity.slack.com/archives/C9BB9AW7K/p1550008399057600)).

## Your Environment

* Sensu version: c4ba1e2

**Comment by palourde** [comment]
I believe this should be covered by https://github.com/sensu/sensu-go/issues/2826 too. In this case, sensuctl would simply determine the right namespace to use in the URL but the API should be responsible to make sure the resource is valid if it can inferred. I'll go ahead and close this issue to avoid duplication but I made sure to mention this issue in the other one!
