### ISSUE TITLE
Review logging of all CRUD operations

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2719]
This issue was filed in response to a question from @zee-vikas, who was wondering if sensu-go is logging all CRUD operations. At the time, I wasn't certain enough about our logging of these operations to say "yes".

Review how CRUD operations are logged for all resource types, and ensure that consistent logging across all resources is performed.

If there are inconsistencies between how operations are logged, implement a consistent logging approach for all CRUD operations.

CRUD operations should be logged at INFO level.

**Comment by asachs01** [comment]
From a customer request--the following operations are what they're interested in seeing inside of the logs:
a) User/group creation
b) Creation of application roles/profiles
c) Modification of roles/profiles
d) Modification of user access rights
e) Manual password reset (done by admin)
f) Unsuccessful login (failure at logon)
g) Successful login if required to support forensic purpose
h) Account lockouts
i) Manual log stoppage (log restart)
j) Changes to authentication level
k) Access control changes
l) Key management/encryption changes

**Comment by asachs01** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Citi Sensu Go validation](https://trello.com/c/6q60DBWI/100-citi-sensu-go-validation)

**Comment by echlebek** [comment]
I've done an audit of our logging facilities in the API. Currently, we log all requests at info level, and display the following facts about the response after the request has been processed:
* duration in ms
* response status
* size of response
* request path
* request method

These facts are sufficient to infer knowledge about all of the above requirements, except:
1. account lockouts
2. key management / encryption changes

For all other requirements, this knowledge can be inferred by a combination of request method, request URL, and response status.

For (1), There is currently no way to distinguish between a user being disabled and another user update, based on logging alone. However, we could add a special case for this requirement.

For (2), there is no way for the backend to know if encryption certificates have changed. I believe it would be out of scope for the backend to be concerned with this.
