### ISSUE TITLE
Results submitted to agent socket do not follow 1.x behavior wrt source attribute

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2720]
## Expected Behavior

Results received via agent socket treat the value of `source` attribute as the entity with which the check result should be associated.

## Current Behavior

When results are received via the agent socket, the value of the `source` attribute is not considered when associating the event with an entity.

## Possible Solution

* honor the value of `source` attribute as specifying the entity with which the check result (event) should be associated
* also honor [`proxy_entity_name` as a synonym for `source`](https://github.com/sensu/sensu-go/issues/2605)
* discard the `client` attribute (under 1.x this is treated as a custom check result attribute and does not influence which entity the result is attributed to)

## Context

In preparing [updates for agent socket documentation](https://github.com/sensu/sensu-docs/pull/1200), we've found that the handling of source and client attributes differs between Sensu 1.x and Sensu Go. As we believe the agent socket should be backward compatible with the 1.x check result format, we also expect the treatment of `source` attributes to be the same under Go as it is under Sensu 1.x.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by echlebek** [comment]
* The agent should fill in the `client` attribute, and the user should not be required to. Currently, the user is required to fill in `client`, this is a bug.

* Add the `source` attribute  and use it to set the proxy entity name.
