### ISSUE TITLE
Tokens are not "translated" during check execution using Token Substitution in combination with Redaction on Proxy Check Requests 

### ISSUE THREAD

**Issue by becon-cmichel** [sensu/sensu-go#2723]
I am monitoring network devices represented by proxy entities. I use token substitution for credentials, like snmp credentials. To avoid that users see these credentials I need to use token substitution in combination with redaction. But then the token is redacted (and not re-redacted) when the check is executed. Therefore the check uses "REDACTED" as password / snmp community etc., what results in failing checks. 

## Expected Behavior
Tokens should be "re-redacted" for the check execution itself, but being further on redacted for event info and entity info.

## Current Behavior
Token is transformed to "REDACTED" and the check is using this explicit string in the check execution. Therefore the check fails. 

## Possible Solution
Tokens should be usable "un-redacted" during check execution and only unvisible in the event and entity info. 

## Steps to Reproduce (for bugs)
1. create a proxy request check using a password (via token substitution => .label.xyz) in the check
2. create a proxy entity with a label xyz and redact this labelname xyz
3. let one agent execute this proxy check
4. see that the check fails or output the command the agent should execute into a file

## Context
I am monitoring network devices represented by proxy-entities. I need to use token substitution and redaction to avoid that users see credentials. Using token substitution in combination with redaction, the token is redacted (and not re-redacted) when the check is executed. 

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): debian 9.7

**Comment by echlebek** [comment]
Hi, thanks for taking the time to file this issue. Unfortunately, I don't think we can support your use case at this time.

While the use case is natural and makes a great deal of sense, supporting it would involve sending redacted values over the wire. This in turn would lead to values that are meant to be redacted being logged by the backend and agent, as they handle HTTP requests.

Redaction is not meant to stand in for a secrets store, rather, it is to guard against secrets being accidentally captured and displayed from execution environments.

This conflicts with the design of proxy entities, which have their definitions stored centrally. As such, there is no secure way to usefully store secrets in proxy entities, as there is with agent entities.

Some potential workarounds do come to mind:
- storing the secrets on the agents, perhaps in a file or environment variable, and referencing them in the check.
- storing the secret without redaction in the proxy entity, if you are comfortable sending the secret over the wire, and having it be logged.

We do hope to provide a secrets API in the future, but we think it will be a while before this comes to fruition. Hopefully people can work around this problem for now. If you discover a novel strategy, please let us know!

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/sensu-go-token-expansion-and-redaction/1643/2
