### ISSUE TITLE
add test cases for TLS and sample production-like deployment

### ISSUE THREAD

**Issue by gbolo** [sensu/sensu-go#2724]
We need some test cases for TLS as well as a sample deployment (using compose) on how we recommend to deploy a production-grade environment (from a security and availability point of view)

Let me know if there is any interest in this and I can work on it.

**Comment by gbolo** [comment]
If there is little to no interest in this, then I can close this issue.

**Comment by echlebek** [comment]
Hi, while we do deploy with TLS to our staging environment, this is in a private repository and not accessible to the community.

I would be supportive of adding more test cases for TLS and supporting TLS in compose.

Can you describe what you have in mind with a little more details? Thanks!

**Comment by gbolo** [comment]
Hi @echlebek 

In terms of sample deployment, something like this (still working on it): https://github.com/gbolo/dockerfiles/tree/master/sensu-go/compose

expanded to include multiple backends, load balancer for backend (nginx or HAproxy), and future features (like tls mutual auth). I'm not sure if you would find this appropriate or useful for this repo. I was hoping to even add some sensuctl scripts that configure some standard features like checks, handlers, metrics, exc.

for TLS test cases, I was thinking something simple like ensuring the TLS related flags are working as expected. I guess we could go further and ensure that clients cannot negotiate non-recommended TLS versions and ciphers. I already tested all of this manually, but the test cases would ofcourse ensure that this remains true for all future commits.

Let me know your thoughts, I'm open to anything (even closing this if you feel it overkill)
