### ISSUE TITLE
Some errors are not logged

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2728]
## Expected Behavior

Any errors encountered after starting Sensu services are logged.

## Current Behavior

Some errors are not logged, only become visible when running services interactively.

## Steps to Reproduce (for bugs)
1.  stop sensu-backend service (e.g. via systemctl)
2. chown -R root.root /var/{lib,cache}/sensu/sensu-backend
3. start sensu-backend service
4. note that the service is in a failed state because of the modified permissions
5. review logs (e.g. via journalctl) and note that there are no log entries related to the failure
6. run the sensu-backend command interactively, e.g. `sudo -u sensu sensu-backend start -c /etc/sensu/backend.yml` and note that fatal errors are visible

## Context

In a few support cases we've encountered scenarios where the permissions of directories like /var/lib/sensu and /var/cache/sensu are such that services running under the `sensu` user cannot create or modify the contents of files and subdirectories therein.

Ostensibly these incorrect permissions are the result of Sensu executables being run manually/interactively as `root` or some other user, resulting in errors like this:

```
{"cache":"/var/cache/sensu/sensu-backend","component":"asset-manager","level":"debug","msg":"initializing cache directory","time":"2019-01-16T17:28:37Z"}
{"component":"sensu-enterprise","level":"fatal","msg":"error initializing asset manager: open /var/cache/sensu/sensu-backend/assets.db: permission denied","time":"2019-01-16T17:28:37Z"}
```

These errors are only observable when the command is run interactively, i.e. outside of service management like systemd, making these permissions issues difficult to identify.

Per @ccressent: 
> I had a quick look and skimming through the code it seems like you might see a similar issue with anything happening in `backend.Initialize()`. I think it might be because it is actually called through Cobra, the library we use to parse command line arguments.
> Anyway, it requires a closer look...

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.1#cd944d6
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by portertech** [comment]
Time box this to 3 days max.

**Comment by palourde** [comment]
### Current behavior

- `chown -R root.root /var/lib/sensu/sensu-backend`
```
Nov 07 19:25:00 backend-0 sensu-backend[32518]: {"component":"sensu-enterprise","error":"error starting etcd: stat /var/lib/sensu/sensu-backend/etcd/data: permission denied","level":"fatal","msg":"error executing sensu-backend","time":"2019-11-07T19:25:00Z"}
```

- `chown -R root.root /var/cache/sensu/sensu-backend`
```
Nov 07 19:27:27 backend-0 sensu-backend[32673]: {"component":"sensu-enterprise","error":"error initializing asset manager: open /var/cache/sensu/sensu-backend/assets.db: permission denied","level":"fatal","msg":"error executing sensu-backend","time":"2019-11-07T19:27:27Z"}
```

I'm realizing now that this is an extremely old issue and it appears it has been fixed since it was open. @cwjohnston please let us know if you are still facing this problems with some customers!

**Comment by cwjohnston** [comment]
As a service to anyone who may find this issue in the future, I believe the behavior I described in this issue is related to https://github.com/systemd/systemd/issues/2913

As a workaround, our [troubleshooting documentation](https://docs.sensu.io/sensu-go/latest/guides/troubleshooting/#narrow-your-search-to-a-specific-timeframe) has been updated with examples showing usage of the `_COMM` variable.
