### ISSUE TITLE
Feature Request: Support persisting mutations

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2732]
Allow mutators to persist their changes to the store, instead of just forwarding them down the pipeline.

## Expected Behavior
- As a user I can specify an option in the spec of my mutator to instruct Sensu to save the changes it makes (if any) to the etcd store.
- The mutator runs as normal
- On receiving the mutated event, Sensu checks if the event was modified (optional, might have performance implications) and persists the changes to the store before forwarding the mutated event to the next step in the pipeline as usual.

## Current Behavior
Mutations are wholly contained within the pipeline with which they run.

## Possible Solution
https://github.com/sensu/sensu-go/pull/2733

## Context
Sometimes events need some dynamic context added to them, which is why mutators already exist. Allowing mutators to persist this dynamic data allows tools querying Sensu data (eg: sensutctl, the dashboard, and any other tooling users may create or use that leverages the API) to provide this extra  context without having to implement the ability to query these external dependencies themselves.

Some examples that come to mind where this feature might be useful:
- A handler that raises tickets (eg JIRA) for events might want to persist the ticket key or link in the events
- A mutator that looks up some dynamic state for the alerting host from an external service

**Comment by annaplotkin** [comment]
@roganartu Thank you so much for the time, effort and consideration that you put into filing this issue and staging the proposed PR (2733). We really appreciate you bringing this use case to us for review and discussion! Community input such as this helps us all end up with the best version of Sensu.

After thorough discussion and review, we feel that this approach may introduce more ‘gotchas’ and undesirable side effects than it will solve. With this in mind, we are going to close this for now and continue to work on addressing the underlying use case. Thanks so much again for the contribution and we look forward to future collaboration with you!
