### ISSUE TITLE
Web UI - long check commands do not display correctly on details page.

### ISSUE THREAD

**Issue by exitquote** [sensu/sensu-go#2734]
Display of very long check commands overlays text instead of wrapping:
<img width="1118" alt="screen shot 2019-02-15 at 3 34 54 pm" src="https://user-images.githubusercontent.com/444524/53029773-93430780-3437-11e9-8eff-69cecb1dc45e.png">

## Expected Behavior

Long check commands should wrap properly in the UI
## Steps to Reproduce (for bugs)

1. Create a check with a long command - 190 characters is plenty for me on a 2560 x 1600 display
2. View the check in the dashboard

## Context
We have a lot of checks (particularly hardware checks) which require long strings of parameters.  These display really strangely in the dashboard and overlap/cover other relevant text on the screen.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
5.1.1
* Installation method (packages, binaries, docker etc.):
sensu-backend with docker, sensu-agent and sensuctl with yum
* Operating System and version (e.g. Ubuntu 14.04): 
MacOS High Sierra 10.13.6 - Chrome, Firefox, and Safari

**Comment by annaplotkin** [comment]
I would like to see this wrap to a maximum of two lines and if it is any longer, truncate and provide a 'more' button to display the whole command.
