### ISSUE TITLE
Agent Check Caching 

### ISSUE THREAD

**Issue by smbambling** [sensu/sensu-go#2736]
This is not so much an issue as an idea for possible improvement/feature request. 

Add a caching mechanism on the agent along with a tunable refresh interval on the backend to publish checks for agents to execute.

Currently, the agent is very simplistic and the backend publishes check subscriptions at the specified interval for each check for an agent to execute if he is a member of one or more of the group listed for the check.

## Expected Behavior
* When a check is published the agent will cache the check subscription until a refresh timer that is tunable per check expires.  

  * After the refresh timer expires the check subscription should be removed from the cache. This would help prevent 'stale' check subscriptions on agents nodes, without the need to restart the agent. The agent will continue to execute the cached check at the set check interval and publish results back to the message bus as it does currently.

* The backend would only publish subscriptions for checks in the following scenarios

  - An agent subscribes to a subscription that it's not already registered to, similar to initial agent registration.  
      - All checks that are part of that subscription could be either published immediately or during their next scheduled interval
  - The refresh interval for a check has expired
  - An ad-hoc check request is generated via the API
  - The check has been updated on the backend, for example, the occurrences, interval or handlers are modified

## Current Behavior
The current behavior is that checks are continually published at the check interval.

## Possible Solution
See Expected Behavior

## Steps to Reproduce (for bugs)
N/A

## Context
Looking at moving to Sensu-GO from Sensu 1.x without the pub/sub model.  As it stands currently it looks like we are going to have much more network traffic along with needed more robust manager to handle the additional load of scheduling and publishing checks to agents.

## Your Environment
N/A This would be moving to a fresh instance of Sensu-GO

**Comment by annaplotkin** [comment]
Thanks so much for filing this! We have reviewed internally and have decided against moving forward with this for now due to potential technical complexity. We will keep these requirements in mind and very much appreciate your collaboration!
