### ISSUE TITLE
Using sensuctl edit entity with namespace flag gives a not found error

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#2739]
## Expected Behavior
Running `sensuctl edit entity sensu-docs --namespace web` after a `web` namespace is made and an `entity` is added to that namespace is able to find the resource as it would in the `default` namespace.

## Current Behavior
Entity is not found when made in a `web` namespace.

## Steps to Reproduce (for bugs)

1. Make a namespace named `web` (or any non-default one)
2. Create an entity inside that namespace
3. Attempt to run `sensuctl edit entity sensu-docs --namespace web`
4. Get error:
```
Error: not found
Error: couldn't get resource: exit status 1
```

## Context
Worth noting that the `--namespace` flag works with the `default` namespace. Also works if an entity is in the `default` namespace  and the `--namespace` flag is used with the `web` value. This leads me to believe the flag isn't being honored at all and if an entity isn't in the `default` namespace, it won't be found by the command.

First reported in a [docs issue](https://github.com/sensu/sensu-docs/issues/1214)

Worth noting that `sensuctl edit entity help` shows the flag as a possible option.

## Your Environment

sensu-go-cli-5.2.1-1.x86_64
sensu-go-backend-5.2.1-1.x86_64
sensu-go-agent-5.2.1-1.x86_64

**Comment by annaplotkin** [comment]
@rgeniesse This seems possibly related to #2345, which we are working on this Sprint. Please review and let me know your thoughts.

**Comment by rgeniesse** [comment]
@annaplotkin I believe that to be the same issue. I'll close this and once #2345 is believe to be resolved, I can re-test to make sure and re-open if needed.

Thanks for bringing that one up!
