### ISSUE TITLE
Agent does not switch to a working sensu-backend on startup

### ISSUE THREAD

**Issue by hezor** [sensu/sensu-go#2741]
When there is a sensu-backend cluster (for example, 3 backend members), sensu-agent seems to randomize the backend it tries to connect at startup. Although, if for any reason that particular sensu-backend node is down, the agent tries to connect to it indefinitely instead of trying another sensu-backend node.

## Expected Behavior

The agent should try another sensu-backend node that is configured in agent.yml.

## Current Behavior

The agent tries to connect indefinitely to a non-operational sensu-backend on startup.

## Possible Solution

When the agent is unable to connect to a sensu-backend, try another sensu-backend that is defined in agent's configuration.

## Steps to Reproduce (for bugs)

1. Shutdown a sensu-agent that has all the sensu-backend cluster members configured in backend-url at agent.yml.
2. Shutdown all sensu-backend cluster members.
3. Start the sensu-agent.
4. From the sensu-agent's log, see what is the sensu-backend it initially tries to connect to.
5. Start all other sensu-backend cluster nodes, except the one the agent is trying to connect to.
6. From the sensu-agent's log, you can see it still tries to connect to the sensu-backend node that is still down.

## Context

When there are maintenance periods (or failures) for sensu-backend nodes, new sensu-agent instances might not be able to instantly connect to the sensu-backend cluster due to this problem.

sensu-backend cluster configuration/status (when a node named sensu-backend3 is deliberately down):
```
$ sudo sensuctl cluster health
- memberid: 1570574892990769795
  name: sensu-backend2
  err: ""
  healthy: true
- memberid: 9463877035209692980
  name: sensu-backend3
  err: 'dial tcp 172.18.22.225:2379: connect: connection refused'
  healthy: false
- memberid: 10895331062010048491
  name: sensu-backend1
  err: ""
  healthy: true
```

sensu-agent backend-url configuration in agent.yml:
```
backend-url:
  - "wss://sensu-backend1.redacteddomain.fi:8081"
  - "wss://sensu-backend2.redacteddomain.fi:8081"
  - "wss://sensu-backend3.redacteddomain.fi:8081"
```

sensu-agent log at startup:
```
$ sudo systemctl start sensu-agent && sudo journalctl -u sensu-agent -l -f
Feb 21 08:47:08 sensu-agent-testmachine systemd[1]: Started The Sensu Agent process..
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","level":"info","msg":"starting statsd server on address: 127.0.0.1:8125","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","level":"info","msg":"starting UDP listener on address: 127.0.0.1:3030","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","level":"info","msg":"starting TCP listener on address: 127.0.0.1:3030","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","event":{"Title":"Gostatsd started","Text":"Gostatsd started","DateHappened":1550731628,"Hostname":"sensu-agent-testmachine","AggregationKey":"","SourceTypeName":"","Tags":null,"SourceIP":"","Priority":1,"AlertType":0},"level":"info","msg":"statsd received an event","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","level":"info","msg":"starting api on address: 127.0.0.1:3031","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","error":"dial tcp 172.18.22.225:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","error":"dial tcp 172.18.22.225:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:08 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","error":"dial tcp 172.18.22.225:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2019-02-21T08:47:08+02:00"}
Feb 21 08:47:10 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","error":"dial tcp 172.18.22.225:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2019-02-21T08:47:10+02:00"}
Feb 21 08:47:20 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","error":"dial tcp 172.18.22.225:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2019-02-21T08:47:20+02:00"}
Feb 21 08:47:30 sensu-agent-testmachine sensu-agent[2944]: {"component":"agent","error":"dial tcp 172.18.22.225:8081: connect: connection refused","level":"error","msg":"reconnection attempt failed","time":"2019-02-21T08:47:30+02:00"}
...
```

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.1
* Installation method (packages, binaries, docker etc.): yum packages from the official repo
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.6.1810

**Comment by annaplotkin** [comment]
Related to #2533

**Comment by hezor** [comment]
From version 5.4.0, this has been fixed. Thanks!
