### ISSUE TITLE
Avoid writing event.metrics to etcd (only store record). 

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2743]
## Expected Behavior
As a user of the sensu-prometheus-collector check, I would like the check to only result in metrics events, so that the metrics are not stored in Sensu.

## Current Behavior
All checks are stored along with metrics data in Sensu.

## Possible Solution 1
Add a flag called "metrics_only" to check configurations, so that successful check executions are only transmitted as metrics events, and thus not stored. Unsuccessful checks are still transmitted as regular check events, so that users can easily detect failure.

## Possible Solution 2
Add a flag called "no_store_metrics" to check configurations, so that extracted metrics are not stored along with the check event.

## Context
A user is attempting to push a large amount of metrics through Sensu, but the default etcd request size limit is hampering that effort.

**Comment by portertech** [comment]
I would expect the check execution to be stored in etcd as record. I would expect the produced Event.Metrics to bypass etcd and go straight to the pipeline(s).

**Comment by annaplotkin** [comment]
+1 for keeping the record stored in etcd.

**Comment by nikkiki** [comment]
We'll definitely have to update sensu-staging and sensu-go-qa-crucible after these changes. They validate metrics are contained in the check's event. Maybe we can hack around this by injecting the metrics json into the output of a _new_ event (by using the /events api handler).

Just writing my thoughts here so I don't forget :)
