### ISSUE TITLE
Feature request: Implement keepalive critical state

### ISSUE THREAD

**Issue by hezor** [sensu/sensu-go#2747]
The old Sensu 1.x had the feature where you could define warning ja critical thresholds for keepalive checks. In Sensu Go, there is only one configuration flag (keepalive-timeout) that sets the keepalive event to a warning state, never critical.

## Expected Behavior

Allow configuring the keepalive-interval (as it can be done now), keepalive-warning-threshold (for example 120 seconds) and keepalive-critical-threshold (for example 240 seconds).

## Current Behavior

Configuration flag keepalive-timeout changes the event to a warning state, never critical.

## Possible Solution

Remove keepalive-timeout flag, add keepalive-warning-threshold and keepalive-critical-threshold flags (or whatever naming convention suits best).

## Steps to Reproduce (for bugs)

Not relevant.

## Context

Every critical event in production pages our on-call officer 24/7, this includes critical keepalive events with Sensu 1.x. This way we can tell if the corresponding host is not working properly. With Sensu Go, the keepalive warning would not trigger this without getting hands dirty by creating some filters and mutators for this use case.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.1
* Installation method (packages, binaries, docker etc.): yum packages from the official repo
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.6.1810

**Comment by annaplotkin** [comment]
Hi @hezor ! Thanks so much for raising this and the team is engaged in discussion on this and will keep this issue updated. 

In the meantime with Sensu Go, an occurrences filter can be used to achieve this in the meantime: https://docs.sensu.io/sensu-go/5.11/reference/events/#occurrences-and-occurrences-watermark

**Comment by echlebek** [comment]
We won't be removing `keepalive-timeout`, as that would introduce a breaking change. But it seems like it should be fine to have `keepalive-timeout`, and `keepalive-critical-timeout`. What do you think, @hezor?

**Comment by agm650** [comment]
In my use case this would be very handy. I’d like to have that :)

**Comment by hezor** [comment]
> We won't be removing `keepalive-timeout`, as that would introduce a breaking change. But it seems like it should be fine to have `keepalive-timeout`, and `keepalive-critical-timeout`. What do you think, @hezor?

That would be great!

**Comment by nikkixdev** [comment]
See the [classic implementation](https://github.com/sensu/sensu/blob/012c2c0fd35e22817ad030626f75172b4b67cd1e/lib/sensu/server/process.rb#L1112-L1144) for the parity logic around different cases of warn and critical thresholds.

**Comment by nikkixdev** [comment]
I got to thinking about the different configurations an operator could set with `keepalive-timeout` and `keepalive-critical-timeout` and what the intended behavior should be for each. @cwjohnston @portertech would we say that the below proposed behavior is in line with 1.x parity?

**Possible use cases:**
1. critical threshold < warning threshold
    - critical event is created first
    - warning event does not overwrite it (ignore the second keepalive event)
2. critical threshold > warning threshold
    - warning event is created first
    - critical event does overwrite it (persist the second keepalive event)
3. critical threshold == warning threshold
    - critical event takes precedence
4. critical threshold == 0 && warning threshold == n
    - warning event is created after n seconds
    - critical event is disabled
5. critical threshold == n && warning threshold == 0 
    - critical event is created after n seconds
    - warning event is disabled

**Flag validation:**
- current default for warning keepalive = 120 seconds
- current keepalive warning threshold must be >= 5
- proposed keepalive warning threshold must be 0 or >= 5
- proposed keepalive critical threshold must be 0 or >= 5

**Comment by majormoses** [comment]
I think its still missing the ability to setup specific handlers on the agent and not just thresholds. My use case is that we would have a `web` namespace where some agents need to go to specific SRE teams while others need to go to all sre teams. Basically if you own the application you own the infra that runs on it. In some cases some apps have shared ownership (often monoliths). If you want to tackle this in a new issue that is fine but its something that we require and was supported in 1.x.

**Comment by majormoses** [comment]
Sorry I think I was confusing it with this one as they are related but technically different features missing from sensu-go that were available (and heavily used) in sensu-ruby.

https://github.com/sensu/sensu-go/issues/3267
