### ISSUE TITLE
Feature Request: Cancel Asset download and running check commands when agent recieves SIGINT

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2756]
sensu-agent run from cmdline will wait for asset download and check commands to complete when using CTRL-C.  The wait can be several minutes long (depending on external factors like asset size and network bandwidth), and this makes it appear as if the agent is "stuck".  

 
## Expected Behavior
CTRL-C results in clean agent shutdown within reasonable amount of time. say 10 seconds

## Current Behavior
CTRL-C while asset is downloading causes agent to appear to "hang" until asset download is complete without any indication as to what is going on.

## Possible Solution
Refactor signal handling so that client processes such as asset download and check commands can be passed SIGINT  and do a graceful aboirt/clean up as necessary so agent can exit more quickly.

## Steps to Reproduce (for bugs)
1. setup check using "large" asset
2. run sensu-agent from cmdline with subscription necessary to run check
3. wait for asset to start download ... download cached under /tmp/
4. attempt to quit agent using Ctrl-C
5. wait for asset download to complete

## Context
I originally came across this issue when testing the asset download timeout fix in PR #2746.  The timeout fix is unrelated but makes agent "hang" on CTRL-C more obvious.

**Comment by annaplotkin** [comment]
This would benefit from a larger discussion, added the appropriate label.
