### ISSUE TITLE
Community repo has no sensu-plugins-ruby for Debian

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#2757]
## Expected Behavior

I'd expect community repo to support same distributions as main stable repo.

## Current Behavior

Currently unable to install `sensu-plugins-ruby` from the community repo on Debian 8 and Debian 9.

## Context

I am adding plugin install support to the sensu-puppet module and our test matrix includes Debian 8 and Debian 9 and those tests are failing because the package `sensu-plugins-ruby` is missing.

## Your Environment
Debian 8 and Debian 9

**Comment by treydock** [comment]
CC @ghoneycutt

**Comment by amdprophet** [comment]
This makes sense. I've opened up https://github.com/sensu/sensu-plugins-omnibus/issues/3 and am closing this issue out in favour of it.
