### ISSUE TITLE
Leases aren't being cleaned up after a server is deregistered

### ISSUE THREAD

**Issue by gattie** [sensu/sensu-go#2760]
## Expected Behavior
After an agent is removed or deregisters from sensu-go the keepalive leases should disappear and not return after their TTL is met.

## Current Behavior
TL;DR - When an agent is removed from sensu-go, either by auto deregistration or manually deleting it from the UI or API, once all of it's keepalive leases reach their TTL they all get recreated and leased over and over at the TTL interval forever.

I connect an agent to my sensu-go cluster.

If I run `etcdctl least list` I see 7 total leases. 6 of them represent each backend, and the 7th is the agent's keepalive.

Every 20s (the keepalive value) a new lease is created and the old lease no longer has an associated key.

Since the keepalive value is 20s and the TTL is 120s we end up with 5 leases with no attached keys and 1 lease for the agent's keepalive key.

Running something like `for i in $(etcdctl lease list | tail -n +2); do etcdctl lease timetolive --keys $i; done` I can see each lease and the keys in that lease.

```
lease 5f816935c078c817 granted with TTL(120s), remaining(5s), attached keys([])
lease 5f816935c078c882 granted with TTL(120s), remaining(25s), attached keys([])
lease 5f816935c078c8ed granted with TTL(120s), remaining(45s), attached keys([])
lease 5f816935c078c019 granted with TTL(60s), remaining(45s), attached keys([/sensu.io/backends/5f816935c078c019])
lease 491f6935c078f90c granted with TTL(60s), remaining(47s), attached keys([/sensu.io/backends/491f6935c078f90c])
lease 61956935c0789c0c granted with TTL(60s), remaining(49s), attached keys([/sensu.io/backends/61956935c0789c0c])
lease 5f816935c078c027 granted with TTL(60s), remaining(54s), attached keys([/sensu.io/backends/5f816935c078c027])
lease 5f816935c078c032 granted with TTL(60s), remaining(54s), attached keys([/sensu.io/backends/5f816935c078c032])
lease 5f816935c078c043 granted with TTL(60s), remaining(54s), attached keys([/sensu.io/backends/5f816935c078c043])
lease 5f816935c078c958 granted with TTL(120s), remaining(65s), attached keys([])
lease 5f816935c078c9c3 granted with TTL(120s), remaining(85s), attached keys([])
lease 5f816935c078ca2e granted with TTL(120s), remaining(105s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
```

Now if I stop sensu-agent on my agent, and either let deregistration occur, or manually delete the entity from sensu if deregistration is false I'll see the leases with no attached keys reach their TTL and expire.

Once the lease with the agent's keepalive key attached reaches it's TTL 6 new leases are created. One will contain the agent's keepalive key despite that agent no longer being registered in sensu-go. The other 5 will have no keys attached. All 6 have a TTL of 120s that are in sync and will expire at the same time. When they expire another 6 leases will be created. This continues until I stop my sensu-backends and delete the etcd data and start with a brand new cluster.

The below data is output from the following running every 30s:

```shell
for i in `etcdctl lease list | tail -n +2`; do etcdctl lease timetolive --keys $i; done | grep -v backends
```

- Agent sensu-go-agent connects to the cluster

```
Thu Feb 28 13:44:48 MST 2019
lease 5f816935d94bb340 granted with TTL(120s), remaining(107s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
```

- After 43 seconds we see 2 keepalives have occurred, therefore we have 2 leases with no keys and 1 lease for our current keepalive
```
Thu Feb 28 13:45:19 MST 2019
lease 5f816935d94bb35e granted with TTL(120s), remaining(117s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
lease 5f816935d94bb340 granted with TTL(120s), remaining(77s), attached keys([])
lease 5f816935d94bb350 granted with TTL(120s), remaining(97s), attached keys([])
```

- After 30 more seconds another keepalive has occured
```
Thu Feb 28 13:45:49 MST 2019
lease 5f816935d94bb340 granted with TTL(120s), remaining(47s), attached keys([])
lease 5f816935d94bb350 granted with TTL(120s), remaining(66s), attached keys([])
lease 5f816935d94bb35e granted with TTL(120s), remaining(86s), attached keys([])
lease 5f816935d94bb36c granted with TTL(120s), remaining(106s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
```

- Another 30 seconds later we're at 5 empty leases and our current keepalive. lease 5f816935d94bb340 has 16s remaining and will expire before the next view.
```
Thu Feb 28 13:46:20 MST 2019
lease 5f816935d94bb388 granted with TTL(120s), remaining(116s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
lease 5f816935d94bb35e granted with TTL(120s), remaining(56s), attached keys([])
lease 5f816935d94bb37a granted with TTL(120s), remaining(96s), attached keys([])
lease 5f816935d94bb340 granted with TTL(120s), remaining(16s), attached keys([])
lease 5f816935d94bb350 granted with TTL(120s), remaining(36s), attached keys([])
lease 5f816935d94bb36c granted with TTL(120s), remaining(76s), attached keys([])
```

- 30 seconds later we see 5f816935d94bb340 is gone and our previous active keepalive lease of 5f816935d94bb388 is now empty. This is all expected.
```
Thu Feb 28 13:46:50 MST 2019
lease 5f816935d94bb3e5 granted with TTL(120s), remaining(106s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
lease 5f816935d94bb350 granted with TTL(120s), remaining(5s), attached keys([])
lease 5f816935d94bb35e granted with TTL(120s), remaining(25s), attached keys([])
lease 5f816935d94bb36c granted with TTL(120s), remaining(45s), attached keys([])
lease 5f816935d94bb37a granted with TTL(120s), remaining(65s), attached keys([])
lease 5f816935d94bb388 granted with TTL(120s), remaining(85s), attached keys([])
```

- Now the agent has been removed from the cluster. We should start to see the leases drop away...
- 30 seconds has past since the last check and we see one lease has expired and since the agent has been deleted we don't see a new lease created every 20s.
```
Thu Feb 28 13:47:21 MST 2019
lease 5f816935d94bb44f granted with TTL(120s), remaining(95s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
lease 5f816935d94bb36c granted with TTL(120s), remaining(15s), attached keys([])
lease 5f816935d94bb37a granted with TTL(120s), remaining(35s), attached keys([])
lease 5f816935d94bb388 granted with TTL(120s), remaining(55s), attached keys([])
lease 5f816935d94bb3e5 granted with TTL(120s), remaining(75s), attached keys([])
```

- 30 seconds later another has expired
```
Thu Feb 28 13:47:51 MST 2019
lease 5f816935d94bb44f granted with TTL(120s), remaining(64s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
lease 5f816935d94bb37a granted with TTL(120s), remaining(4s), attached keys([])
lease 5f816935d94bb388 granted with TTL(120s), remaining(24s), attached keys([])
lease 5f816935d94bb3e5 granted with TTL(120s), remaining(44s), attached keys([])
```

- Another 30 seconds and we only have 2 left
```
Thu Feb 28 13:48:22 MST 2019
lease 5f816935d94bb3e5 granted with TTL(120s), remaining(14s), attached keys([])
lease 5f816935d94bb44f granted with TTL(120s), remaining(34s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
```

- One lease remaining...
```
Thu Feb 28 13:48:52 MST 2019
lease 5f816935d94bb44f granted with TTL(120s), remaining(3s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
```

- 30 seconds later they're all back and notice the time remaining on all of them is the same. The agent no longer exists yet we have a keepalive key for it.
```
Thu Feb 28 13:49:22 MST 2019
lease 5f816935d94bb744 granted with TTL(120s), remaining(94s), attached keys([])
lease 5f816935d94bb74a granted with TTL(120s), remaining(94s), attached keys([])
lease 61956935d94be01d granted with TTL(120s), remaining(94s), attached keys([/sensu.io/switchsets/keepalived/default/sensu-go-agent])
lease 5f816935d94bb745 granted with TTL(120s), remaining(94s), attached keys([])
lease 491f6935d94c031f granted with TTL(120s), remaining(93s), attached keys([])
lease 5f816935d94bb748 granted with TTL(120s), remaining(93s), attached keys([])
```

- At the same time that these were created we see these messages start to appear in the logs every 2 minutes (the 120s TTL time):
```
Feb 28 13:48:57 sensu-go-backend sensu-backend[12601]: {"component":"keepalived","level":"debug","msg":"creating a lease for /sensu.io/switchsets/keepalived/default/sensu-go-agent with TTL 120","time":"2019-02-28T13:48:57-07:00"}
Feb 28 13:50:57 sensu-go-backend sensu-backend[12601]: {"component":"keepalived","level":"debug","msg":"creating a lease for /sensu.io/switchsets/keepalived/default/sensu-go-agent with TTL 120","time":"2019-02-28T13:50:57-07:00"}
```
That appears to come from https://github.com/sensu/sensu-go/blob/69c45d3079d2c840e4cda430cf97ddc0eb5db08e/backend/liveness/liveness.go#L308

## Possible Solution

Seems like this was possibly being addressed here? --> https://github.com/sensu/sensu-go/commit/2251429d58eccf82176ad14fd94c764998486c81

https://github.com/sensu/sensu-go/blob/69c45d3079d2c840e4cda430cf97ddc0eb5db08e/backend/liveness/liveness.go#L94-L97 The above seems to reference potentially what I am seeing, but the lingo is a bit opaque so I'm not sure if what I am seeing is the "underworld". If it is, I don't understand why this data would be kept around forever or why leases with no attached keys would live in the underworld.

## Steps to Reproduce (for bugs)

1. Setup a sensu-go backend server
2. Connect an agent to it
3. Run `etcdctl lease list` to see all of the leases. If you just have one backend and one agent there should be 2 to start. If the keepalive interval is 20s and the TTL is 120s you should see a new lease created every 20s and the old ones expire and disappear after their TTL is met.
4. Run `for i in `etcdctl lease list | tail -n +2`; do etcdctl lease timetolive --keys $i; done` to see the keys attached to each lease.
5. Stop the sensu-agent service on your agent and delete it from sensu (via the UI or sensuctl)
6. Continue to watch the leases. After they all expire (after 120s) they will all re-appear.

## Context

While trying to scale sensu go to thousands of agents using the benchmark utility I noticed a lot of CPU thrashing and lots of context switching. Even after removing agents the context switching appeared to continue to occur until I stopped sensu-backend and deleted the storage directory and started from scratch.

I appears this might be putting some unnecessary load on the server as well as filling up etcd with data.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
  * sensu-backend version 5.2.1#cd944d6, build cd944d6cf04aefc00a84c2ad8fbf7141f6283523, built 2019-02-09T00:03:30Z
  * sensu-agent version 5.2.1#cd944d6, build cd944d6cf04aefc00a84c2ad8fbf7141f6283523, built 2019-02-09T00:04:19Z
  * sensuctl version 5.2.0#21a24d9, build 21a24d9cf073863d6c2b02c0b7acaae673e4f597, built 2019-02-06T22:09:26Z
  * etcdctl version: 3.3.11; API version: 3.3
  * HA-Proxy version 1.5.18 2016/05/10
* Installation method (packages, binaries, docker etc.): RPM on the etcd backends and agents. Docker on the backends without etcd.
* Operating System and version (e.g. Ubuntu 14.04): Centos 7.5.1804

I'm using a 3 node sensu-go cluster with embedded etcd, with 3 more sensu-go servers without etcd fronting them and handling all of the sensu-api, agent-api, and dashboard calls. These are sitting behind haproxy.

```
                 |-->backend1--|   |-->sensu-go-etcd1
                 |             |   |
agent-->HAProxy--|-->backend2--|-->|-->sensu-go-etcd2
                 |             |   |
                 |-->backend3--|   |-->sensu-go-etcd3
```

However, this occurs even with a single node backend with embedded etcd.

**Comment by echlebek** [comment]
Thanks for the excellent bug report. Looks like there are two problems, just guessing off the cuff here. 

1) backends compete to lease keys for keepalives. The backends that lose the competition should revoke the obtained leases immediately, but it seems they do not.

2) When entities are deleted or when the deregistration handler is run, the process that continually pumps these leased keys should be cancelled. However, it seems that this process remains active.
