### ISSUE TITLE
etcd-advertise-client-urls is not present in example template

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#2761]
## Expected Behavior
Docs example is consistent with the template. That is, both contain the values listed here https://docs.sensu.io/sensu-go/latest/guides/clustering/#sensu-backend-configuration

## Current Behavior
There is currently a difference between the values in https://docs.sensu.io/sensu-go/latest/guides/clustering/#sensu-backend-configuration and the example template:

**Docs Guide Example**
```
##
# store configuration for backend-1/10.0.0.1
##
 etcd-advertise-client-urls: "http://10.0.0.1:2379"
etcd-listen-client-urls: "http://10.0.0.1:2379"
etcd-listen-peer-urls: "http://0.0.0.0:2380"
etcd-initial-cluster: "backend-1=http://10.0.0.1:2380,backend-2=http://10.0.0.2:2380,backend-3=http://10.0.0.3:2380"
etcd-initial-advertise-peer-urls: "http://10.0.0.1:2380"
etcd-initial-cluster-state: "new"
etcd-initial-cluster-token: ""
etcd-name: "backend-1"
```

**Example Template**
```
$ cat /usr/share/doc/sensu-go-backend-5.2.1/backend.yml.example
##
# store configuration
##
#etcd-listen-client-urls: ""
#etcd-listen-peer-urls: ""
#etcd-initial-cluster: ""
#etcd-initial-advertise-peer-urls: ""
#etcd-initial-cluster-state: ""
#etcd-initial-cluster-token: ""
#etcd-name: ""
```

The main difference here (aside from the populated values in the docs) is the attribute ` etcd-advertise-client-urls: ""`

I see in the help for starting the backend that the default is http://localhost:2379. So is this needed in the template? There's a part of me that feels that the two should be consistent.

**Comment by palourde** [comment]
The default `etcd-advertise-client-urls` value is now configured to `http://localhost:2379` in the example template provided in the packages.
