### ISSUE TITLE
multiple arguments in sensuctl silently fail

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#2765]
## Expected Behavior
`sensuctl create -f file1.yaml -f file2.yml` should either create from both definitions or display a warning stating that the multiple arguments will result in only the last one applying.

## Current Behavior
`sensuctl create -f file1.yaml -f file2.yml` acts as if the command was actually `sensuctl create -f file2.yml`

## Possible Solution
Accept both files, or throw an error/warning alert

## Steps to Reproduce (for bugs)
1) `sensuctl create -f file1.yaml -f file2.yml`
2) Check for configuration updates based on content of file1.yaml and file2.yaml
3) Observe that only the contents of file2.yaml have been applied

## Context
Watching a user assume that `-f` might work, user attempted and wasn't sure if it had worked or not

## Your Environment
Sensu 5.2.1, binary install on RHEL 7

**Comment by echlebek** [comment]
We should make `-f` accept multiple arguments.
