### ISSUE TITLE
Backend websocket API should offer unauthenticated health check endpoint

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2773]
## Expected Behavior

As an operator I can put one or more backends behind a load balancer and the load balancer can perform health checks on the API, UI and Agent transport.

## Current Behavior

Health checks against `/` on Agent transport (port 8081) return a 401 response code which load balancers interpret as unhealthy.

## Possible Solution

Provide an unauthenticated endpoint, e.g. `/healthz` for determining the health of the Agent transport

## Steps to Reproduce (for bugs)
1. Deploy one or more Sensu backend nodes behind an ELB or ALB in AWS
2. Configure health check against Agent transport (HTTP port 8081) 
3. Observe that backend nodes are marked as unhealthy

## Context

Some load balancers, e.g. AWS ALB, do not provide overrides for acceptable HTTP responses, so we can't work around this via configuration.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend 5.2.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by portertech** [comment]
Backend websocket server `/healthz` endpoint.
