### ISSUE TITLE
[Web UI] Command text doesn't wrap long lines

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2775]
## Expected Behavior
A user can see the command value wraps, respecting spaces at the end of lines.

## Current Behavior
A command with an unbroken line will overflow into the form.
<img width="1195" alt="screen shot 2019-03-06 at 2 40 04 pm" src="https://user-images.githubusercontent.com/10634078/53919953-5b83b480-4020-11e9-92c3-7084e5e6b2d6.png">

## Possible Solution
Implement a max width? Idk.

## Steps to Reproduce (for bugs)
1. Deploy staging instances and resources.
2. Navigate to the check details page for a check that has the command similar to this garbage:
```
echo \n hi \n foo far bardasfdddddddddddddddddddddddddddddddddddddddddddda;eksdfja;sdklfjas;dlkfjasdkfhskjdahfalsjkdfhasldkjfhasldkjfhasldkjfhalsdkjfhasdlf
```
3. Observe that the command text overflows.

## Context
Readability.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-enterprise-go/commit/9924e30caca162a841bc687f339df29d92a7adce
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16

**Comment by dabria** [comment]
I've addressed this in #2778 and #2782
