### ISSUE TITLE
FIPS-140-2 Compliance

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-go#2787]
## Context
There's a specific part of the world that has FIPS-140-2 as a continuous burden. 

Does Sensu Inc. have any plans to support deploying Sensu Go in a FIPS 140-2 compliant configuration? 

I know there's a lot to actually ensuring the cryptography is fully FIPS compliant but, starting off with supporting configuration for the the FIPS validated algorithms would be a decent start, https://csrc.nist.gov/csrc/media/publications/fips/140/2/final/documents/fips1402annexa.pdf. If I recall correctly, there's a boringcrypto version/branch of Go that Google works on to support FIPS within their Google Cloud services. 

I'm mostly opening this up to check if Sensu has ever looked at FIPS compliance, if support is something being tracked, or if FIPS support is a hard no. 

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.3.0
* Installation method (packages, binaries, docker etc.): RPM Packages
* Operating System and version (e.g. Ubuntu 14.04): RedHat Enterprise Linux 7

**Comment by calebhailey** [comment]
@jaredledvina hi there! :wave: I hope you're well! 

Sorry for the radio silence on this one. If I understand correctly, you're not actively managing Sensu at `<your company>` anymore, but in case you want to pass an update along, FIPS compliance is pretty high on our radar at the moment and we're committed to finding a solution ASAP.

Cheers 🍻

**Comment by jaredledvina** [comment]
Hey @calebhailey, Yep, unfortunately that's correct (although I do still run Sensu Go on my personal stuff!). 

If you folks need any feedback, feel free to reach out, I'm always happy to help. Currently, I believe the following are some decent initial sources for getting Golang's to use crypto that is FIPS-140-2 compliant:
* https://github.com/golang/go/blob/dev.boringcrypto/README.boringcrypto.md
* https://github.com/golang/go/blob/dev.boringcrypto.go1.12/misc/boring/README.md
* https://developers.redhat.com/blog/2019/06/24/go-and-fips-140-2-on-red-hat-enterprise-linux/

**Comment by amdprophet** [comment]
FIPS builds of Sensu Go are now available for RHEL 7 & 8 upon request.
