### ISSUE TITLE
[Tessen] Seeds

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2790]
The default Tessen configuration should be created and stored when a backend starts up, only if one does not exist already. The configuration should be persistent, but the default is opt-in. See: https://github.com/sensu/sensu-go/blob/master/backend/seeds/seeds.go 

Depends on https://github.com/sensu/sensu-go/issues/2789

**Comment by annaplotkin** [comment]
Closing this, collapsed the requirement into the Daemon ticket.

**Comment by nikkiki** [comment]
Closed in favor of https://github.com/sensu/sensu-go/issues/2791.
