### ISSUE TITLE
Make agent /events API asynchronous, create relay handler

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2800]
This Epic is to house the work needed to enable an agent API buffer. 

Applications (and scripts) can send data into Sensu using a local Sensu Go Agent API (/events). Currently, if the local Agent is not connected to a Backend, the data is lost and the Agent still responds with a 200. The Agent API should hold onto the data until it is able to successfully send it to a Backend for processing. This can also apply to Events produced by the Agent statsd server.

Parent of #2801
Parent of #2804
Parent of #2805

**Comment by palourde** [comment]
This has been implemented!
