### ISSUE TITLE
Agent API buffer - The /events endpoint can receive an event and send along to a connected backend to be processed in near real time.

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2802]
As a user, I can send a Sensu Go Event to the Agent API /events endpoint while the Agent is connected to a Backend and see my Event processed by that Backend in near real time.

Acceptance criteria: 

1. If the agent is connected to a backend at the time of event creation, that event will be sent to the /events endpoint and connected backend for processing immediately.

**Comment by echlebek** [comment]
Closing in favour of #2801
