### ISSUE TITLE
Agent API buffer - Events can be sent and accepted to the /events API from an agent even if not connected to a backend.

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2803]
As a user, I can send a Sensu Go Event to the Agent API /events endpoint while the Agent is NOT connected to a Backend and when the Agent connects to a Backend I can see my Event processed by that Backend. 

Acceptance Criteria: 
1. If an agent is not connected to a backend, an event can still be sent to and accepted by the /events endpoint. 
2. The /events endpoint will respond with a 202.

**Comment by echlebek** [comment]
Closing in favour of #2801
