### ISSUE TITLE
Add Quality-of-Service features to agent event relaying

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2805]
As an agent, when I connect to a backend and send it queued events, I will not overwhelm it with requests. (rate limiting)

As an agent, when I am trying to connect to a backend that is unavailable, I will not retry constantly. (Avoid the thundering herd problem.) Instead, I will try again with exponential backoff.

Acceptance Criteria: 
1. Provide a way of limiting on events per second (must be configurable). 
1. Include a reasonable default configuration for rate limiting.
1. Include configuration for exponential backoff.

**Comment by echlebek** [comment]
Implementation details:
* Use Sensu's retry package for exponential backoff. Pick good defaults, but do not expose configuration for the backoff period, in the interest of minimizing adjustable knobs.
* Use https://godoc.org/golang.org/x/time/rate for rate limiting. Make sure to expose the limit and burst configuration to users.
