### ISSUE TITLE
Agent API buffer - Agent has a concept of backoff when attempting to connect to a backend unsuccessfully. 

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2806]
As an agent, when I cannot connect to a backend, I will not overwhelm it with retry attempts. (backoff)

Acceptance criteria: 
1. Paradigm in place for the agent to rate-limit the retry attempts and do a logical backoff.

**Comment by echlebek** [comment]
Closing in favour of #2805
