### ISSUE TITLE
User without explicit permission can list all namespaces

### ISSUE THREAD

**Issue by funkypenguin** [sensu/sensu-go#2812]
I'm using RBAC to build a multi-tenanted Sensu platform. I create a per-department namespace, create users, assign them to groups, and apply the cluster-role "admin" to the group with a role-binding in their namespace. The intended result is that the users in each department are isolated from named resources in any other department.

## Expected Behavior
A user logs into the dashboard (or uses sensuctl), and lists namespaces. He can only see the namespaces for which he's inherited access via RBAC.

## Current Behavior
User can see all namespaces, although he can't see entities within the ones he hasn't inherited access to.

## Possible Solution
Don't return namespaces to a user as the result of an API query if that user doesn't have rights to list namespaces

## Steps to Reproduce (for bugs)
1. Create namespace "test-rbac-issue" (```sensuctl namespace create test-rbac-issue```)
2. Create user "test-rbac-issue" (```sensuctl user create test-rbac-issue -p "test-rbac-issue```
3. Add user to group (```sensuctl user add-group test-rbac-issue group-test-rbac-issue```)
4. Add role-binding (in namespace) to group (```sensuctl role-binding create role-test-rbac-issue-admin --cluster-role admin -g group-test-rbac-issue --namespace test-rbac-issue```
5. Log into the dashboard as the user. The user can switch between the "create test-rbac-issue" namespace and the "default" namespace (and any others which exist)

## Context
I want isolation of namespaces between users to include the name of the namespace. Users with access to only the "austrialia" namespace should not even be able to see the "europe" namespace

## Your Environment
Running sensu/sensu Docker container under Kubernetes on GKE

Server:
```
/ # sensu-backend version
sensu-backend version 5.3.0#379593a, build 379593a8859315e746da28eedfdc8ae4907091fa, built 2019-03-11T20:23:43Z
/ #
```

**Comment by funkypenguin** [comment]
Sorry, hit enter 1 too many times. Editing now.

**Comment by palourde** [comment]
Hi @funkypenguin,

I apologize for the delay. The simple reason why all users can list namespaces is simply because the dashboard relies on it, for the namespace selector. If it's not something that you care about, you could always edit the default [`system:user` role](https://github.com/sensu/sensu-go/blob/760d1e2f77adadf9585598121e224b3c9bc12ce3/backend/seeds/seeds.go#L242) to remove this particular rule.
