### ISSUE TITLE
HTTP(S) proxy not supported for asset retrieval

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2813]
## Expected Behavior

Agent and backend can download asset files via an HTTP(S) proxy

## Current Behavior

Neither agent nor backend honors `HTTP_PROXY` or `HTTPS_PROXY` env vars and does not otherwise expose proxy configuration.

## Possible Solution

* Add support for HTTP_PROXY and HTTPS_PROXY env vars
* Add explicit configuration (e.g. via config yml, env vars and/or flags) for proxy use

## Steps to Reproduce (for bugs)
1. Configure Sensu instance in an environment where HTTP proxy usage is enforced by network ACLs
2. Configure Sensu agent and/or backend with HTTP_PROXY env vars
3. Observe that the agent and/or backend hits net/http timeout attempting to download the asset directly w/o going through proxy.

## Context

In order to achieve specific security requirements, many regulated environments make use of network ACLs and other controls in place to force HTTP(S) and other network traffic.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-agent, sensu-backend
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

**Comment by annaplotkin** [comment]
- Review of how we are handling this in all places. 
- GoNET library supports this, environment variables are important to support. 
- Perhaps we are scrubbing asset environment during fetch?

**Comment by echlebek** [comment]
@cwjohnston, unfortunately I was not able to reproduce the issue.

The `net/http` library supports `$HTTP_PROXY` by default in its client. Inspection of the HTTP client used in asset downloading reveals that the default client is used, meaning that HTTP proxy support should be working out of the box.

And in fact, this is what testing reveals.

Here, agents have been given a configuration of `HTTP_PROXY=http://example.com:4242`, and `NO_PROXY="localhost, 127.0.0.1, backend1, backend2, backend3"`. A check has been created to depend on an asset, and we can see that the check fails to execute, with a dial timeout to the HTTP proxy.

```
  Entity     Check                                                                             Output                                                                            Status   Silenced             Timestamp            
 ──────── ─────────── ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── ──────── ────────── ─────────────────────────────── 
  agent1   foo         error getting assets for event: error fetching asset: Get https://github.com/blah/blah/blah: proxyconnect tcp: dial tcp 93.184.216.34:4242: i/o timeout        3   false      2019-04-18 15:10:24 -0700 PDT  
```

**Comment by echlebek** [comment]
Some progress:

It looks like systemd doesn't pick up most system-wide environment variables by design. You instead have to set an option in the unit file.

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment

There are options for setting specific variables and for setting a file to read variables from.

It's unclear to me right now if we can fix this in our packaging so that the service just picks up the HTTP_PROXY and NO_PROXY environment variables.

**Comment by cwjohnston** [comment]
per @nixwiz , this is working as expected when providing `HTTP_PROXY=http://proxy.example.com:3128/` in `/etc/default/sensu-backend`. In our original testing we had specified `export HTTP_PROXY=http://proxy.example.com:3128/` which is not compatible with systemd's EnvironmentFile implementation.

I'm closing this issue as it is no longer valid. I've opened https://github.com/sensu/sensu-docs/issues/1384 to track needed documentation updates around environmental configuration for Sensu services.

**Comment by ninjasloth22** [comment]
It looks like you are already creating a custom ```http.Client```.
Do you think we could add proxy_server/proxy as an actual parameter to an Asset definition? 
Which should just require the addition of some transport options to the ```http.Client{}```. 
```Transport: &http.Transport{Proxy: http.ProxyURL(proxyUrl)}```
I feel this might be a slightly better approach as it would prevent the environment variables effecting other things (like http checks on internal hosts) trying to use the proxy.
