### ISSUE TITLE
Add lets-encrypt CA to sensu-agent

### ISSUE THREAD

**Issue by funkypenguin** [sensu/sensu-go#2815]
I setup my sensu backend with a valid LetsEncrypt certificate (for the dashboard in the browser). As such, the same cert is used for agent->server communications. I expected the agent to trust the LetsEncrypt cert, but it complains that the certificate authority is unknown.

## Expected Behavior
sensu-agent validates API certificate using commonly trusted CAs (incl. LetsEncrypt)

## Current Behavior
sensu-agent refuses to connect to a wss: backend signed by LetsEncrypt, unless ```insecure-skip-tls-verify``` is set to true

## Possible Solution
Include commonly trusted CAs in the sensu-agent

## Steps to Reproduce (for bugs)
1. Attempt to connect an agent to ```wss://sensu.funkypenguin.co.nz:8081```
2. The attempt will fail due to invalid cert
3. Set ```insecure-skip-tls-verify``` to true, and restart agent
4. The attempt will fail (this time) for invalid authentication (expected)

## Context
The lack of trusted CA support means that agent deployments are either more complex (have to bundle in a trusted CA cert), or less secure (ignoring cert validity altogether)

## Your Environment

```
root@node1:~# sensu-agent version
sensu-agent version 5.3.0#379593a, build 379593a8859315e746da28eedfdc8ae4907091fa, built 2019-03-07T19:00:05Z
root@node1:~#
```
^ On Ubuntu 1604

**Comment by Berdir** [comment]
As a workaround, you can use the chain.pem file as trusted ca file in the agents.

I think the missing piece is that the backend ssl configuration should include a chain file, like apache/nginx.

**Comment by palourde** [comment]
@funkypenguin @Berdir You can use the `--trusted-ca-file` config flag on the agent to include LetsEncrypt CA certificate.
