### ISSUE TITLE
Add Windows service utilities to agent

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#2839]
## Expected Behavior
We need the ability to install or remove a Windows service using the `sensu-agent` command (e.g. sensu-agent windows-service install). We also need the ability to configure certain flags (e.g. config file path) so that the service knows where to look.

## Current Behavior
This feature doesn't exist yet.

## Possible Solution
Make use of the `sys/windows/svc` package in go: https://github.com/golang/sys/blob/master/windows/svc/example/service.go

**Comment by cwjohnston** [comment]
Closed by #2896
