### ISSUE TITLE
Remove events when corresponding entities are removed

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2846]
## Expected Behavior
An entity is removed. Afterwards, no events associated with the entity exist.

## Current Behavior
An entity is removed. Afterwards, the events associated with the entity still exist.

## Issues
Right now, the event lifecycle is somewhat decoupled from that of entities. Changing how this works will probably need careful analysis.

Schedule a discussion to identify any issues around deleting events when entities are deleted. Look for corner cases that could create bugs.

**Comment by jweede** [comment]
Noticed that this bug makes it seemingly impossible to delete events from removed entities through the documented REST API. Supposedly the GraphQL API will allow it, but I couldn't dig up any docs on it.

**Comment by echlebek** [comment]
Pulled this one into 5.11 because it was bothering me
