### ISSUE TITLE
[Tessen] Sandbox metrics

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2850]
- [ ] Implement a backend configuration option `--sandbox-lesson string` to pass to TessenD
- [ ] Add the key/value metric tag `sandbox_lesson:string_from_config` to _every_ metric reported to Tessen
- [ ] Update the Sensu Go Tessen dashboard queries to filter out any metrics with a non empty `sandbox_lesson` tag
- [ ] On start up send a single tagged metric to Tessen for all sandbox installations (see snippet below)
- [ ] Create a new tile in the Sensu Go Tessen dashboard to display a bar graph of aggregates across different lesson plans
```
if sandboxLesson != "" {
	data.Metrics = corev2.Metrics{
		Points: []*corev2.MetricPoint{
			&corev2.MetricPoint{
				Name:      "sandbox",
				Value:     1,
				Timestamp: now,
				Tags: []*corev2.MetricTag{
					&corev2.MetricTag{
						Name:  "sandbox_lesson",
						Value: sandboxLesson,
					},
				},
			},
		},
	}
}
```

**Comment by jspaleta** [comment]
Sandbox related variables of interest in priority order:
1. tag to indicate its a sandbox install: 
2. tag to indicate specific sandbox lesson plan: 

These two items could be smooshed into a single string if it makes sense from a data collection pov.
