### ISSUE TITLE
[Tessen] Opt-out notification

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2862]
As per the [tessen spec](https://docs.google.com/document/d/1bjPAxzCNnfRizGytL9THgVjDLM8NSGr1G6iU4ycizx8) we need to inform and surface to the Tessen AWS service when a user has opted out. This final payload would _not_ include collected data metrics such as entity count and server count (as the user has opted out), but should indicate the change in opt-out status. Perform a small spike to determine how best to surface this data in the payload.

**Comment by nikkiki** [comment]
@portertech @anna Here's a mock of one way we could display these events in the dashboard. I created a sortable table which contains opt-in and opt-out events (of course we could create a conditional if we only wanted opt-out). These columns are all customizable, so if there's any other information you'd like displayed, hidden, or changed, it's all pretty easy to do. Let me know your thoughts!

<img width="1472" alt="Screen Shot 2019-04-05 at 1 38 06 PM" src="https://user-images.githubusercontent.com/10634078/55655155-3e214200-57a8-11e9-90f6-4c93adb66e0b.png">

**Comment by annaplotkin** [comment]
@nikkiki This looks good to me!

**Comment by nikkiki** [comment]
Closing out this spike in favor of the implementation ticket, https://github.com/sensu/sensu-go/issues/2880.
