### ISSUE TITLE
Agent socket should support 1.x custom attributes as labels

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2873]
Related: #2720, #417

## Expected Behavior
Custom fields passed to the agent socket are added as 1.x custom attributes, or 2.x labels.

## Current Behavior
Custom fields passed to the agent socket are ignored, and the event is still created without the custom fields.

## Possible Solution
Use some reflection to populate the fields as labels.

## Steps to Reproduce (for bugs)
1. Send this payload to the agent socket: `{"name": "check-mysql-status", "output": "error!", "status": 1, "foo": "bar"}`
2. Observe an event is created without the field `"foo":"bar"`

## Context
1.x parity

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/34315c36d36ce21cd87ebf5652584fb698867ce1
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS

**Comment by nikkiki** [comment]
If the agent socket is deprecated, further development/support is probably no longer necessary. Leaving this open until we can discuss in Inbox cleanup.

**Comment by portertech** [comment]
@nikkixdev can you please confirm the current behaviour. If the socket accepts the data and sends an event sans custom attributes, we can close this.

**Comment by nikkixdev** [comment]
The current _behavior_ is still the same. The socket accepts the data and sends an event without custom attributes or labels. Closing the issue per this comment: https://github.com/sensu/sensu-go/issues/2873#issuecomment-534691014.
