### ISSUE TITLE
Expose Sensu version via local agent API 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2879]
## Expected Behavior

It is possible to determine the running version of a sensu-agent process

## Current Behavior

It is not possible to know the running version of a sensu-agent process

## Possible Solutions

* Add an endpoint to the local agent API, e.g. `/version` or `/healthz`
* Add the version as a constant on results returned via the `/metrics` local agent API 

## Context

Knowing the running version of a service helps operators in various troubleshooting scenarios.

The sensu-agent has a `version` subcommand which helps us know the installed version of the agent, but currently we can't be certain that the installed version is also the running version without changing the system, i.e. restarting the service.

See https://github.com/sensu/sensu-go/issues/1739 for a similar issue on the backend API.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.5.0

**Comment by jaredledvina** [comment]
Would it be possible to feed this version information into the entity info as well? Commented on https://github.com/sensu/web/issues/13#issuecomment-494641682 with something I ran across today.
