### ISSUE TITLE
Store metrics

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#288]
We need metrics for the store. We need to know the number of transactions per second that we're making and what kind of transactions they are (CreateEvent, UpdateEvent, CreateCheck, etc). For each transaction, we should record the time it took Etcd to respond. If we can have metadata about Read vs Write on the metric, that's also helpful.

**Comment by palourde** [comment]
Etcd metrics are now exposed and we were able to use that in our benchmarks. I'll go ahead and close this issue.
