### ISSUE TITLE
Event payload according to sensuctl no longer contains the metrics object as of 5.4.0

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#2888]
## Expected Behavior
When using the check attributes `output_metric_format` and `output_metric_handlers`, an object inside the event payload called `metrics` is created containing the sensu metric format for each data point found in the check output. It is then reflected when running `sensuctl event info entity-name  check-name --format wrapped-json` For example:

```
"metrics": {
  "handlers": [
    "influx-db"
  ],
  "points": [
    {
      "name": "sensu-go-sandbox.curl_timings.time_total",
      "tags": [],
      "timestamp": 1552506033,
      "value": 0.005
    },
    {
      "name": "sensu-go-sandbox.curl_timings.time_namelookup",
      "tags": [],
      "timestamp": 1552506033,
      "value": 0.004
    }
  ]
}
```

## Current Behavior
When using the check attributes `output_metric_format` and `output_metric_handlers`, no object named `metrics` is shown when running `sensuctl event info entity-name  check-name --format wrapped-json`

## Steps to Reproduce (for bugs)

1. Run sensu-agent/sensu-backend/sensu-cli 5.5.1.
2. Add the following resources:

```
{
  "type": "Asset",
  "api_version": "core/v2",
  "metadata": {
    "name": "sensu-plugins-disk-checks",
    "namespace": "default"
  },
  "spec": {
    "url": "https://github.com/sensu-plugins/sensu-plugins-disk-checks/releases/download/5.0.0/sensu-plugins-disk-checks_5.0.0_centos_linux_amd64.tar.gz",
    "sha512": "0ce9d52b270b77f4cab754e55732ae002228201d0bd01a89b954a0655b88c1ee6546e2f82cfd1eec04689af90ad940cde128e8867912d9e415f4a58d7fdcdadf"
  }
}
{
  "type": "Asset",
  "api_version": "core/v2",
  "metadata": {
    "name": "sensu-ruby-runtime",
    "namespace": "default"
  },
  "spec": {
    "url": "https://github.com/sensu/sensu-ruby-runtime/releases/download/0.0.4/sensu-ruby-runtime_0.0.4_centos_linux_amd64.tar.gz",
    "sha512": "1c9f0aff8f7f7dfcf07eb75f48c3b7ad6709f2bd68f2287b4bd07979e6fe12c2ab69d1ecf5d4b9b9ed7b96cd4cda5e55c116ea76ce3d9db9ff74538f0ea2317a"
  }
}
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "namespace": "default",
    "name": "metrics_disk"
  },
  "spec": {
    "command": "metrics-disk.rb",
    "subscriptions": [
      "system"
    ],
    "interval": 10,
    "publish": true,
    "output_metric_handlers": ["influxdb"],
    "output_metric_format": "graphite_plaintext",
    "runtime_assets": [
      "sensu-plugins-disk-checks",
      "sensu-ruby-runtime"
    ]
  }
}
```

3. Run `sensuctl event info entity-name  metrics_disk --format wrapped-json`
4. Observer that the event payload reported by `sensuctl` does not show the `metrics` object.

## Context
Sensu Go 5.3.0 does not show this issue. Sensu Go 5.4.0 does show this issue.

Debug logging does show that the event pay load sent by the sensu agent and received by the sensu backend has the `metrics` object populated as expected. This leads me to believe it is not being stored properly in `etcd`

Documentation referenced:
https://docs.sensu.io/sensu-go/5.4/reference/events/#metric-attributes

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.3.0, 5.4.0 and 5.5.0 tested.
* Installation method (packages, binaries, docker etc.): Packages.
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by rgeniesse** [comment]
I'd like to note that it would appear this data is making it to an external TSDB when a handler like that is configured. So it would further seem like this is either an etcd storage issue or sensuctl just isn't returning what is there.

If it were impacting what makes it to an external TSDB, this would be much more impactful of an issue.

**Comment by cwjohnston** [comment]
@rgeniesse I believe its intentional that metric data isn't being persisted to etcd, see https://github.com/sensu/sensu-go/pull/2785

**Comment by rgeniesse** [comment]
Ah yes, you are correct. We will want this to be a documentation issue the to remove that output. Debug logs will they be the source of truth for getting metrics at least from the check.

We may also want to consider a way to turn debugging on inside handlers. Or if there is one, document that.
