### ISSUE TITLE
Add more Sensu Go data points to /metrics data

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2890]
## Expected Behavior

The /metrics API endpoint reports useful information regarding configuration of the Sensu backend.

## Current Behavior

The /metrics API does not report much in the way of Sensu Go-specific metrics. Currently limited to "events processed" counter.

## Context

/metrics API endpoint, added in 5.4.0, reports lots of etcd related metrics, but not much regarding Sensu's own data.

```
curl -sk https://sensu-go.local:8080/metrics | grep sensu_go
# HELP sensu_go_events_processed The total number of processed events
# TYPE sensu_go_events_processed counter
sensu_go_events_processed{status="success"} 774467
```

It would be helpful to know:

* number of registered/known entities
* number of configured checks

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.5.1
* Installation method (packages, binaries, docker etc.): packages

**Comment by palourde** [comment]
This has been implemented via https://github.com/sensu/sensu-go/pull/2936.
