### ISSUE TITLE
[Build stability] Intermittent failure in liveness integration tests

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2891]
See the CircleCI test failure: [test.log](https://github.com/sensu/sensu-go/files/3105207/test.log)

**Comment by echlebek** [comment]
![image](https://user-images.githubusercontent.com/1633772/56605088-2d4e3a00-65b8-11e9-80a4-3b248bc9662e.png)

**Comment by nikkiki** [comment]
Hit this again today on circle ci.

**Comment by palourde** [comment]
![](https://ljdchost.com/037/vd9gU6R.gif)
