### ISSUE TITLE
Pagination header does not match documentation

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2913]
Documentation says that the newly added pagination header is `X-Sensu-Continue`, however it is only being sent as `Sensu-Continue` without the suffix.

## Expected Behavior
A pagination request to return the `X-Sensu-Continue` header with the response when further results are available.

## Current Behavior
Pagination request returns `Sensu-Continue` header.

## Possible Solution
Change this const to include the `X-` prefix:
https://github.com/sensu/sensu-go/blob/dc0544b8910243fe6740b9a132fa2316c91f3489/api/core/v2/protocol.go#L19

It seems to only be used here, where it is added to the headers without any suffix:
https://github.com/sensu/sensu-go/blob/9dfb8d29ace7ac94d4c89a62a09196a957855393/backend/apid/routers/lister.go

## Context
Documentation says it should be `X-Sensu-Continue` which matches convention for custom headers.
https://docs.sensu.io/sensu-go/5.6/api/overview/#pagination

## Your Environment
```
sensuctl version 5.6.0#4bd3afc, build 4bd3afcf64de3cb73bb12e9712c7e537a9a3144d, built 2019-04-26T22:22:23Z 
```

**Comment by flowerysong** [comment]
I would vote for fixing the documentation rather than changing the header; the `X-` convention has been deprecated for [almost seven years](https://tools.ietf.org/html/rfc6648) and just adds unnecessary noise. The `Sensu-` prefix already signals that this is a non-standard header.

**Comment by ccressent** [comment]
As @flowerysong mentioned, `Sensu-Continue` is indeed what we wanted and is "correct" with regard to the latest RFC recommendations. `X-Sensu-Continue` was used during the development of the feature though, and there was a miscommunication that lead to the docs not being updated. I'm sorry you had to dig through the code base @roganartu...

`Sensu-Continue` is the correct header, we'll update the documentation!

**Comment by ccressent** [comment]
Thanks again for bringing this to our attention @roganartu; I'm closing this issue in favor of https://github.com/sensu/sensu-docs/pull/1431.
