### ISSUE TITLE
Secure socket communication protocols and ciphers should be configurable

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2914]
## Expected Behavior

As an operator I can configure Sensu network daemons for secure communication, including configuring the permitted security protocols and ciphers.

## Current Behavior

Operators can enable secure socket communication, but cannot explicitly enable or disable particular protocols and ciphers.

## Possible Solution

Make TLS/SSL protocols and ciphers configurable.

## Context

The security policies of many organizations require that protocol and cipher combinations with known vulnerabilities or suspected weaknesses be disabled. 

It is recommended that [testssl.sh tool](https://github.com/drwetter/testssl.sh) tool be used for testing secure socket communication. This tool runs a battery of tests against a given URL, checking for various known vulnerabilities and undesirable protocol/cipher combinations. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.6.0
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by sureshsubramaniam** [comment]
If there is a possibility to have inclusion list of Ciphers in the configuration, it would be awesome

**Comment by annaplotkin** [comment]
This is a high priority security issue reported by Citi during their audit of Sensu Go.

**Comment by palourde** [comment]
For reference, something relatively similar (configurable list) was implemented in Uchiwa: https://github.com/sensu/uchiwa/pull/745/files

**Comment by sureshsubramaniam** [comment]
some references to weak ciphers in etcd
https://github.com/etcd-io/etcd/issues/8320

**Comment by echlebek** [comment]
I've filed the following issues to cover non-etcd communication:

https://github.com/sensu/sensu-go/issues/2952
https://github.com/sensu/sensu-go/issues/2953
https://github.com/sensu/sensu-go/issues/2954
https://github.com/sensu/sensu-go/issues/2955

I believe that since etcd cipher suite selection is the primary issue at hand, we can consider the scope of this issue to cover etcd communication only.
