### ISSUE TITLE
Feature Request: better support for roaming/offline devices

### ISSUE THREAD

**Issue by bzed** [sensu/sensu-go#2916]
## Expected Behavior
Currently it is tricky to use a sensu agent on a laptop or some other device which does not necessarily have an internet connection all the time. Please support to disable keepalives in the agent and add a way to return checks when a device is online, otherwise just maybe mark it as offline without alerting.

## Current Behavior
While you can do various trick with filters/mutators to stop receiving alters from agents, which are known not to be online reguarily, they still show up as issue in the dashboard. Devices which are known to be offline regularily should be just marked as offline or as having keepalived disabled, not as being broken in general.

## Possible Solution
Agents which are subscribed to "laptop" are not monitored for being alive, maybe add an extra list for them.

## Steps to Reproduce (for bugs)
Monitor a laptop, disconnect it :)

## Context
We have a bunch of laptops and would like to do some basic monitoring (bios version, smart faults, ....), but they are not online regularily.

## Your Environment
Debian stretch or buster, latest package from the sensu packagecloud.

**Comment by palourde** [comment]
You could simply use the `--deregister` flag in the sensu-agent, which will deregister the agent once it goes offline: https://docs.sensu.io/sensu-go/5.11/reference/agent/#ephemeral-agent-configuration-flags.
