### ISSUE TITLE
HTTPStatusFromCode() doesn't cover all the codes

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#2929]
[`HTTPStatusFromCode()`](https://github.com/sensu/sensu-go/blob/5.6.0/backend/apid/routers/routers.go#L81-L96) is used to map a given [`actions.Error`](https://github.com/sensu/sensu-go/blob/5.6.0/backend/apid/actions/error.go#L53-L61) (with possible `ErrCode` defined [here](https://github.com/sensu/sensu-go/blob/5.6.0/backend/apid/actions/error.go#L11-L41)) to an appropriate HTTP status code for the API to return.

The problem is that `HTTPStatusFromCode()` doesn't support some of the `actions.Error.ErrCode` values and maps them to a default 500 code (internal server error) to return.

## Possible Solution

Rework `HTTPStatusFromCode()` to include the newer values for `actions.Error`, such as `actions.PermissionDenied` and `actions.Unauthenticated`.

This is not hard, but it could be considered to be a small breaking change for the API since some operations or failures would return appropriate code instead of 500!

We're also probably missing some tests that would have caught the above, probably in the `routers` package.

## Your Environment

* Sensu version: 5.6.0

**Comment by palourde** [comment]
`HTTPStatusFromCode` now includes the newer values such as `PermissionDenied` & `Unauthenticated`. Gonna close this issue.
