### ISSUE TITLE
Feature Request: Expose backend entity information to authorized user

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#2938]
Problem:
Handler and mutator assets can be filtered based on entity information such as os, platform, arch and so on.   But we don't expose the backend entity info in a way that a multi-tenancy user can see in order to make the correct asset filtering choices.  You have to have access to the backend logs to capture that information...which is a very privledged user.

## Expected Behavior
be able to login with sensuctl or dashboard and inspect cluster backendsfor entity level information.

## Current Behavior
Must have access to backend logs.

## Context
deploying a Ruby based handler asset... the difference between alpine and debian matters due to musc versus glibc shared libraries.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/2184
