### ISSUE TITLE
Checks API does not return silenced when configured

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-go#2943]
I'm leveraging the Sensu Go Check's API some, and noticed that if I create a check with `silenced: True`, on GET's after that, the `silenced` attribute is not returned, but instead `publish` is `False`. 

## Expected Behavior
GET's to `/checks/:check`  would return `silenced` attribute if configured. 

## Current Behavior
GET's to `/checks/:check`  do not return `silenced` attribute if configured. 

## Possible Solution
I think this is a bug, but, it feels like a weird UX that when I explicitly set something on a check, future GET's result in the key not being in the response from the api, and instead another key has changed it's value. 

## Steps to Reproduce (for bugs)
1. Have a working Sensu Go 5.7 setup
2. Use https://docs.sensu.io/sensu-go/5.7/api/checks/#checks-post-example to make a check, and set `silenced: true`
3. Use https://docs.sensu.io/sensu-go/5.7/api/checks/#checks-get-example to GET the check, and notice that `silenced` isn't in the result and now `published` is `false`.

## Context
Filing an issue just because I'm now having to add special cases for attributes. Not a horrible issue but, feels pretty muddy to me. I'd be happy to just see `silenced` removed entirely from the API spec since it's the same idea as `published` and more confusing because it sounds like it creates a silenced event which, if it's supposed to do that, then it's entirely broken. 

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.7.0
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Debian 9

**Comment by echlebek** [comment]
This is quite a surprising result. The `silenced` attribute is typed as an array of strings. See https://github.com/sensu/sensu-go/blob/master/api/core/v2/check.pb.go#L348.

If you set a boolean for silenced, the server should have rejected your request with an unmarshaler error.

**Comment by jaredledvina** [comment]
Huh, that also doesn't match the docs: https://docs.sensu.io/sensu-go/5.7/reference/checks/#spec-attributes which is why I was using a boolean. 

I see the commit automatically linked but, for now, I dropped the use of silenced since it seems to be a bit wacky.

**Comment by echlebek** [comment]
Hmm I think that's a doc bug. Thanks, I'll file an issue against the docs repo.

**Comment by echlebek** [comment]
Sorry, I was wrong earlier - `silenced` is a check _result_ attribute, and not a configuration attribute. It shouldn't be specified for check configs.

That `sensuctl` displays a true or false for silences in its table format is a matter of presentation logic only.

The docs are still incorrect here, but in a different and less consequential way than I thought.

**Comment by echlebek** [comment]
This also doesn't explain the behaviour around `publish`, which will need to be tested and reproduced.

**Comment by jaredledvina** [comment]
I went ahead and retested this after talking on Slack with Alex Paskulin about another issue
 - https://sensucommunity.slack.com/archives/C9BB9AW7K/p1557678752409300 

I think I was actually mixing up the way `publish` and `silenced` are working when submitting this. The `published` flipping to `false` was because I had not been setting that and it appears to default to `false`.

Re-testing, I see this:
```
❯ curl \
-s \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $(jq .access_token ~/.config/sensu/sensuctl/cluster | sed 's/"//g')" \
-X GET \
https://sensu.techsmix.net/api/core/v2/namespaces/default/checks/check_test \
| jq .
{
  "message": "not found",
  "code": 2
}
```
```
~
❯ curl \
-s \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $(jq .access_token ~/.config/sensu/sensuctl/cluster | sed 's/"//g')" \
-X POST \
-d '{
  "command": "/bin/true",
  "subscriptions": ["all"],
  "interval": 60,
  "publish": true,
  "silenced": true,
  "metadata": {
    "name": "check_test",
    "namespace": "default"
  }
}' \
https://sensu.techsmix.net/api/core/v2
```

```
❯ curl \
-s \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $(jq .access_token ~/.config/sensu/sensuctl/cluster | sed 's/"//g')" \
-X GET \
https://sensu.techsmix.net/api/core/v2/namespaces/default/checks/check_test \
| jq .
{
  "command": "/bin/true",
  "handlers": [],
  "high_flap_threshold": 0,
  "interval": 60,
  "low_flap_threshold": 0,
  "publish": true,
  "runtime_assets": null,
  "subscriptions": [
    "all"
  ],
  "proxy_entity_name": "",
  "check_hooks": null,
  "stdin": false,
  "subdue": null,
  "ttl": 0,
  "timeout": 0,
  "round_robin": false,
  "output_metric_format": "",
  "output_metric_handlers": null,
  "env_vars": null,
  "metadata": {
    "name": "check_test",
    "namespace": "default"
  }
}
```

So the original piece here is correct, if you create a check with `silenced: true` it goes through but, then the API doesn't return it. Which I was only doing as the check specification documentation seemed to imply that was an attribute I could configure.

**Comment by palourde** [comment]
Going back to https://docs.sensu.io/sensu-go/5.7/api/checks/, looks like the documentation has been corrected because it no longer refers to the `silenced` attribute being configurable. Let us know if you still face any confusion!

**Comment by jaredledvina** [comment]
Hey @palourde,

So the confusing bit is that from https://docs.sensu.io/sensu-go/5.8/api/checks/#checks-post-specification it refers to the checks specification and then over in https://docs.sensu.io/sensu-go/5.8/reference/checks/#spec-attributes it lists `silenced` as a check attribute. 

The API seems to accept `silenced` without error, which I think is a bug(?), as issuing a GET after POST'ing with `silenced: true` is set, `silenced` isn't returned.

**Comment by echlebek** [comment]
Hi Jared,

What you are observing is the system simply ignoring the `silenced` field in your request. There is no `silenced` field for a `CheckConfig` - only for a `Check`, which is the result type of a Check, rather than the configuration type that you are attempting to use.

JSON parsers do not typically emit errors on extraneous fields, as this would harm backwards compatibility between systems, so we won't be able to emit an error in this case.
