### ISSUE TITLE
Support initiating ad-hoc check execution from the command line

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#2947]
## Expected Behavior

As an operator, I can queue check execution on an ad-hoc basis from the command line using sensuctl, similar to the capability provided by the web UI

## Current Behavior

Ad-hoc check execution requests can be queued from the command line by making requests to the [`/check/:check/execute` API endpoint](https://docs.sensu.io/sensu-go/latest/api/checks/#checkscheckexecute-post).

## Possible Solution

Implement a sub-command in sensuctl which allows operators to schedule execution of a named check to an optional list of subscriptions. When no subscriptions are specified, publish the check request to the subscriptions already configured in the specified check.

## Context

The ability to request check execution on an ad-hoc basis makes it easier for operators to interact with Sensu while remaining in the command line where many feel they are more efficient.

**Comment by nikkiki** [comment]
@cwjohnston is `sensuctl check execute [NAME]` sufficient? If so, that subcommand already exists.

**Comment by cwjohnston** [comment]
@nikkiki yep, that appears to be exactly what I thought was lacking. Thanks!
