### ISSUE TITLE
Configuring TLS for etcd leads to site failure

### ISSUE THREAD

**Issue by jbmcfarlin31** [sensu/sensu-go#2958]
## Expected Behavior
I configured the etcd section in the `backend.yml` config file, and etcd should be communicating over TLS.

## Current Behavior
The entire site (site being dashboard at `localhost:3000`) appears to never come back up.

## Steps to Reproduce (for bugs)
The following is my `backend.yml` etcd config:
```
#etcd-advertise-client-urls: "https://127.0.0.1:2379"
etcd-cert-file: "/etc/sensu/ssl/wildcard.pem"
etcd-client-cert-auth: false
etcd-initial-advertise-peer-urls: "https://127.0.0.1:2380"
#etcd-initial-cluster: "http://127.0.0.1:2380"
#etcd-initial-cluster-state: "new" # new or existing
#etcd-initial-cluster-token: "sensu"
#etc-key-file: "/etc/sensu/ssl/wildcard.key"
etcd-listen-client-urls: "https://127.0.0.1:2379"
etcd-listen-peer-urls: "https://127.0.0.1:2380"
#etcd-name: "default"
etcd-peer-cert-file: "/etc/sensu/ssl/wildcard.pem"
etcd-peer-client-cert-auth: "true"
etcd-peer-key-file: "/etc/sensu/ssl/wildcard.key"
etcd-peer-trusted-ca-file: "/etc/sensu/ssl/ca-bundle.pem"
etcd-trusted-ca-file: "/etc/sensu/ssl/ca-bundle.pem"
#no-embed-etcd: false
```

The following line shows up before TLS is configured:
`May 14 15:41:49 sensu-eap sensu-backend[34078]: {"component":"etcd","level":"warning","msg":"serving insecure client requests on 127.0.0.1:2379, this is strong`

Then when configured it disappears. However, the following lines now show after a few seconds:
`May 14 15:38:03 sensu-eap sensu-backend[33652]: WARNING: 2019/05/14 15:38:03 grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...`

I also manage to see this line at time also:
`May 14 15:35:03 sensu-eap sensu-backend[33307]: WARNING: 2019/05/14 15:35:03 Failed to dial 127.0.0.1:2379: grpc: the connection is closing; please retry.`

I had one time where there was no error messages coming back with etcd being configured, so I assumed it was configured correctly - however that is when I noticed that the dashboard site would never load back up.

I was following the [secure sensu](https://docs.uchiwa.io/sensu-go/5.7/guides/securing-sensu/#securing-etcd-peer-communication) documention, but I feel like it is lacking some information in terms of configuration choices.

For example, what kind of cert is being expectd (self signed, CA issued, etc), as well as is the need for the `trusted-ca-certificate` optional or required? I am using a wildcard cert, and my organization uses SSL interception certs also. 

If there is a formal and more documented way for configuring TLS with etcd in this instance, please share. Thanks!

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `5.7`
* Installation method (packages, binaries, docker etc.): binaries (followed the link [here](https://docs.sensu.io/sensu-go/5.7/installation/install-sensu/))
* Operating System and version (e.g. Ubuntu 14.04): `Ubuntu 16.04`

**Comment by palourde** [comment]
Hi @jbmcfarlin31,

It looks like you left some configuration attributes commented, such as `etcd-advertise-client-urls`. Since you configured etcd to listen on `https://127.0.0.1:2379`, you need to also let the client know that it should use  `https`.

For reference, here's etcd documentation around TLS; most of these flags are available with the `etcd` prefix in sensu-backend: https://coreos.com/etcd/docs/latest/op-guide/security.html
