### ISSUE TITLE
What user does sensu agent run checks as

### ISSUE THREAD

**Issue by jbmcfarlin31** [sensu/sensu-go#2959]
## Expected Behavior
As per the documentation here: [Sensu checks](https://docs.sensu.io/sensu-go/5.7/reference/checks/)

Checks are supposedly ran by a user named `sensu`. This was true in the older versions of sensu-core. After upgrading to the newest version of `5.7 Sensu Go`, those same checks would be ran by the same user.

## Current Behavior
When the checks are executed, they are not run as the `sensu` user in my environment. I have certain logs files that are owned by apache, so the permissions look something like:
`rw-rw-r--   myfile.log`.

In my older deployment of sensu, the sensu user was added to the apache group and all I had to was edit the group permissions for my log file (since it needs access to write to the log). This does not happen, when I execute the sensu check from my dashboard it returns back `permission denied on my log file`. 

If I change the permissions to `chmod 666 myfile.log', and re run the check, it successfully goes through. This leads me to believe that is is being ran by another user, and is falling under the `other` option for linux permissions.

My check was this:
```
sensuctl check create mynewcheck \
--command = "/usr/local/bin/python /etc/sensu/plugins/mynewcheck.py" \
--interval 86400 \
--subscriptions "prod"
```

## Steps to Reproduce (for bugs)

1. Configure a simple check in sensu
2. Add it to the subscription your node is running on
3. Execute the check from the dashboard

## Context
We use custom Python scripts that are leveraging Django objects, so these scripts load certain Python libraries for our checks that use to monitor certain things in our application.

Since they are loading Django objects, they are needing access to the logs that Django leverages under apache. In older sensu all we had to do was add the user to the apache group and give the log files write permissions for the group. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `5.7`
* Installation method (packages, binaries, docker etc.): Binaries on the install docs page
* Operating System and version (e.g. Ubuntu 14.04): `Ubuntu 16.04`

**Comment by palourde** [comment]
Hi @jbmcfarlin31,

The agent executes, by default, checks under the `sensu` user & group when using the supported packages. You can double check that information by looking at the systemd service definition under, which is normally located in `/lib/systemd/system/sensu-backend.service` (it might differ based on the distribution).

One thing you could try to do to investigate this permission problem is to have your python script write a new file within a folder with `777` permissions or something like this, and then check the permissions/ownership of the created file. This will let you confirm that the script is ran by the right user. Then, you could change the ownership of this folder to the user under which Apache is ran and pursue your investigation.
