### ISSUE TITLE
Add build instructions to build sensu-go from source to Readme

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#2971]
## Expected Behavior

As an end user, I'd like to have instructions for building sensu-go from source, especially if want to use a purely open-source approach.

## Current Behavior

Instructions are currently missing, and only point to the docs site, which provide instructions for packages currently.

## Possible Solution

Write up some instructions

**Comment by palourde** [comment]
Here's the current instructions we have: https://github.com/sensu/sensu-go/blob/master/CONTRIBUTING.md#building.

That being said, we should probably try to walk away from the `build.sh` script and provide simple Go/bash commands!

**Comment by asachs01** [comment]
@palourde IMO those instructions would be better served living under https://github.com/sensu/sensu-go#installation, rather than in contributing. As it stands, it's not clear from an end-user perspective that I need to go to the contributing doc for instructions on compiling. 

FWIW, the build.sh script is great, but yeah, for me, I'd rather see exactly what I'm doing vs. reading through a script. I also found it _much_ easier to just do a `go build` or `go install`.
