### ISSUE TITLE
Round robin proxy checks perform poorly with high proxy entity counts

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2979]
CPU can spike above 100% under certain conditions. These conditions were produced in the staging environment, and reproduced locally. A clustered Sensu installation can contain 1k entities at normal CPU consumption. When round robin proxy checks are added to that environment, we observed abnormal CPU consumption.

From @echlebek:
So here is what we know:
- there are a reasonable number of goroutines running
- the CPU time on backend-2 is being spent on rings and watchers
- there are far too many auth tokens in etcd
- tokens and rings do not directly interact
- there seems to be too much memory allocated for the system load
- the issue has been present for at least one other release
- etcd requests are taking too long to execute, >100 ms
- the key structure of rings looks OK
- the key structure of switchsets looks OK
_after restarting and the CPU drops_
What does this imply?
- the CPU load on backend-2 was due to the program state, not the database state
- so therefore the CPU load was due to an infinite recursion or a resource leak
Steps to reproduce:
- After I created a round robin proxy check, CPU usage increased to ~140%
- So it seems that the CPU usage increases as a function of proxy entities when proxy checks are scheduled
- The 1000 entities do not share a subscription with the proxy check

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.7.0, 5.8.0
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16

**Comment by ccressent** [comment]
At @echlebek's request, I captured the backends' heaps and CPU profiles while this was happening:
[sensu-backend_heaps-20190521.tar.gz](https://github.com/sensu/sensu-go/files/3208286/sensu-backend_heaps-20190521.tar.gz)
[sensu-backend_profiles-20190521.tar.gz](https://github.com/sensu/sensu-go/files/3208287/sensu-backend_profiles-20190521.tar.gz)

**Comment by portertech** [comment]
An important note, a proxy check does not need to share a subscription with the inspected/evaluated entities, the subscriptions are used to determine which Agent sessions to publish to. A proxy check requires a full-scan of all entities (which is brutal), classic also does this.

**Comment by portertech** [comment]
Classic would slice/batch client (now entity) evaluation https://github.com/sensu/sensu/blob/51319e4b58c8d9986f101ad71ff729aa3e51e951/lib/sensu/server/process.rb#L917-L928

**Comment by palourde** [comment]
I did some profiling against a sensu-staging deployment with 1000 proxy entities registered and clearly the bottleneck here is the evaluation of the `entity_attributes` expressions via Otto:
[backend1.pdf](https://github.com/sensu/sensu-go/files/3237489/backend1.pdf).

That being said, I'm still unable to reproduce the issue we saw with cancelled contexts and watchers taking most of the CPU.
