### ISSUE TITLE
Auth tokens are never purged from etcd

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#2981]
Although auth tokens eventually expire, they are never purged from etcd. We should perform some cleanup as to not overload storage.

**Comment by echlebek** [comment]
If the tokens were created with a lease, they would expire automatically.

**Comment by palourde** [comment]
We currently maintain an access list for both [access and refresh tokens](https://github.com/sensu/sensu-go/blob/6780d12f05bca9c296e95ca99688a17b9b1e7eb3/backend/apid/routers/authentication.go#L79). So for every HTTP request, we need to [hit the store](https://github.com/sensu/sensu-go/blob/1e9f8983f08636e5ea7874939379b635c1f5e17c/backend/apid/middlewares/allowlist.go#L36) to validate that the access token is still authorized. Instead, we should decrease the period of validity of an access token from 15 minutes to 5 minutes and only maintain an access list of refresh tokens. 

The downside to that approach is that a disabled user could still access the system for up to 5 minutes after its deactivation, but considering the nature of our application, I'd say that an acceptable risk.

**Comment by palourde** [comment]
This is no longer relevant since https://github.com/sensu/sensu-go/pull/3345 removed the access list.
