### ISSUE TITLE
Feature Request: Agent: strip metrics from command output

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3014]
check commands that have human readable output prepended with metrics end up polluting the human-oriented event UI.

events generated from the sensu-prometheus-collector even more so.

It would be great if the agent could strip the metrics its ingested from the command output leaving only human readable output as part of the command when there is a metrics output format configured as part of the check.

If no metrics output format is configured... then the full (or perhaps a truncated command output) is provided.

## Expected Behavior
Metrics ingested by agent are stripped from command output, keeping the output short for human readability

## Current Behavior
Metrics in the output clobber readability in sensuctl event list  and web ui

## Possible Solution
Have agent strip metrics ingested from command output.

**Comment by calebhailey** [comment]
Good idea. Perhaps we can add a check config (e.g. `output_metrics_prune` or similar) to feature flag this?
