### ISSUE TITLE
Bug Fix:  include triple dash at the top of resource when outputting yaml format

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3023]
Adding triple dash line at the top of each yaml output from sensuctl commands makes it possible to  cat multiple outputs together into a single yaml file for later re-import with create -f.

Examples:
```
sensuctl check list --format yaml
```    

is close it has the triple dashes between resource, but is missing the leading triple dash at the top, so that iut can be concatenated together with other resources lists into a single file, to be re-imported
```
sensuctl check info fancy-check --format yaml
```    
If this had a leading triple dash at the top of the output, it could be concatenated together with other info output

Ideally each call for yaml output would prepend a single triple dash line at the top of the output.

**Comment by calebhailey** [comment]
@jspaleta is this still a valid issue?
