### ISSUE TITLE
Unexpected error running sensuctl cluster health when cluster is in degraded state.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3036]
Running 3 member sensu-backend cluster, fail a member and then sensuctl cluster health times out with  
```
Error: GET "/health": Get http://127.0.0.1:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

## Expected Behavior
sensuctl cluster health should return a list showing cluster member state

## Current Behavior
sensuctl cluster health  returns  GET "/health" error

## Steps to Reproduce (for bugs)

1. create cluster
2. fail a member
3. run sensuctl cluster health
4.

## Your Environment

* Sensu version: 5.9
* Installation method binaries
* CentOS 7

**Comment by nikkiki** [comment]
This test passed on our latest release QA. Could you provide sanitized configurations for the backends that experienced this problem? Are you running sensuctl on a backend that is still up?
