### ISSUE TITLE
Windows Agent generates errors when parsing graphite metric output

### ISSUE THREAD

**Issue by adammcdonagh** [sensu/sensu-go#3043]
Not so much an issue for me, but looks like a bug, and is logging lots of errors. The results still get passed through to the server OK it seems.

It gets quote spammy when there are 10s of lines being returned by each metrics check.

I have a Windows agent running a script to output metrics in standard graphite format e.g.
```
os.SERVER.net.Ethernet.tx_bits 2562989216 1560358425
```

In my code I am simply sending a `\n` after each line.. However it seems the OS or something is also adding a `\r` too, which it looks like the agent is not handling nicely.

```
{"check":"metrics-wrapper-os-only-windows-60s","component":"agent","error":"unable to extract metric from check output","level":"error","line":24,"msg":"metric timestamp
is invalid, third argument must be an int: 1560358427\r","namespace":"default","time":"2019-06-12T17:53:47+01:00"}
```

## Expected Behavior
Sensu should ignore/handle `\r` characters on Windows the same as `\n`

## Current Behavior
Agent generates log messages about being unable to parse the check output

## Steps to Reproduce (for bugs)
In my case, I have a Perl script being triggered by the agent as part of the check. It has code in the script something like:
```
print "os.SERVER.net.Ethernet.tx_bits 2562989216 1560358425\n";
```

## Your Environment
Running on Windows Server 2012
Sensu client is version 5.9

**Comment by palourde** [comment]
As suggested by @echlebek, we should stop doing stuff like https://github.com/sensu/sensu-go/blob/170178230b00533d90cc8184a4ab2505d5479199/agent/transformers/graphite.go#L46

And switch to something like this: https://golang.org/pkg/bufio/#ScanLines

**Comment by echlebek** [comment]
```
s := bufio.NewScanner(strings.NewReader(metric))
for s.Scan() {
    line := s.Text()
}
if err := e.Err(); err != nil {...}
```
