### ISSUE TITLE
Backup utility for Sensu Go

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#3047]
We need to implement a backup utility and pattern for Sensu Go. 

Acceptance Criteria: 
- When the backup utility is initiated, all resources that the user has access to get ported to a yaml file at a specific directory. 
- By default, this utility will port all types. 
- Allow for type exclusion (e.g. events) if the user wishes to exclude particular types from being ported.

**Comment by palourde** [comment]
Closing this issue in favor of https://github.com/sensu/sensu-go/issues/2742.
