### ISSUE TITLE
action: deny filter with multiple expressions does not work as documented

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3050]
The documentation says that the filters configured with `action: allow` will AND multiple expressions together, while filters configured with `action: deny` will OR multiple expressions together. Instead, both perform AND.

## Expected Behavior
Here's a contrived example clearly illustrating the problem:
```
{
    "type": "EventFilter"
    "api_version": "core/v2",
    "metadata": {
        "name": "allow_none",
        "namespace": "default"
    },
    "spec": {
        "action": "deny",
        "expressions": [
            "1 !== 1",
            "1 === 1"
        ],
        "runtime_assets": []
    },
}
```

One of the expressions matches for all events, so all events should be filtered.

## Current Behavior
No events are filtered.

## Possible Solution
The problematic code is here: https://github.com/sensu/sensu-go/blob/613f31c430c7d2b8d00de82e8815756f68f118c9/backend/pipelined/filter.go#L63-L67

This results in the `deny` filter not being applied because one of the expressions evaluates to `False`. This contradicts the current documentation here: https://docs.sensu.io/sensu-go/5.10/reference/filters/#inclusive-and-exclusive-filtering
which specifically says:
> Configuring a handler to use multiple inclusive filters is the equivalent of using an AND query operator (only handle events if they match inclusive filter x AND y AND z).
> Configuring a handler to use multiple exclusive filters is the equivalent of using an OR operator (only handle events if they don’t match x OR y OR z).

## Your Environment
Problem exists on current master (170178230b).

**Comment by flowerysong** [comment]
This is a misreading of the documentation; the part you quote specifies that it applies to "multiple {inclusive|exclusive} filters", not to your single filter with multiple expressions. Changing the filter action does not (and in my opinion should not) modify which events match the filter, only what action is taken.

**Comment by roganartu** [comment]
Ah so it is, my mistake thanks for pointing that out.
