### ISSUE TITLE
Sensu Go dashboard with Azure Active Directory single sign-on

### ISSUE THREAD

**Issue by jpascalw** [sensu/sensu-go#3058]
This is a feature request to secure the Sensu Go dashboard with Azure Active Directory (AAD) single sign-on.

## Expected Behavior

On initial login to the Sensu Go dashboard the user is redirected to AAD login screen. If authentication is successful the user is redirected back to the Sensu Go dashboard with the default role assignment set by the Sensu Go cluster admin, for example "user" role in the namespace "default".

## Current Behavior

Latest version of Sensu Go (5.9 as of this writing) doesn't support AAD single sign-on

## Possible Solution

https://www.influxdata.com/blog/securing-chronograf-with-oauth-2-0-in-microsoft-azure-active-directory/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Like many large companies we use Azure Active Directory (AAD) for centralized user authentication and authorization. Shared services, such as Sensu Go event management, will not be allowed to be made available to users without this user security solution.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by charlesrg** [comment]
For SSO we used https://github.com/sensu/uchiwa/issues/295#issuecomment-239800555 on uchiwa.  The difference is we use Kerberos Tickets.
 AuthType Kerberos
                AuthName "Kerberos authenticated Intranet"
                KrbAuthRealms DOMAIN.CORP
                KrbServiceName HTTP/sensu.domain.corp@DOMAIN.CORP
                Krb5Keytab /etc/httpd/sensu.domain.corp.keytab
                KrbMethodNegotiate On
                KrbMethodK5Passwd On
                Require valid-user

**Comment by calebhailey** [comment]
@jspaleta I believe we validated that our OIDC provider gives us the ability to authenticate via Azure Active Directory in the manner as described in this issue. Can you confirm? 

Thanks!

**Comment by taapawi2** [comment]
What are the supported user claim we can use ?

`{
  "type": "oidc",
  "api_version": "authentication/v2",
  "metadata": {
    "name": "azuread"
  },
  "spec": {
    "additional_scopes": [
      "profile",
      "email"
    ],
    "client_id": "ID",
    "client_secret": "SECRET",
    "redirect_uri": "https://URI/api/enterprise/authentication/v2/oidc/callback",
    "server": "https://login.microsoftonline.com/TENANTID/v2.0",
    "username_claim": "verified_primary_email"
  }
}`

{"message":"UsernameClaim not found","code":0}
