### ISSUE TITLE
Agent fails to start on RHEL5

### ISSUE THREAD

**Issue by adammcdonagh** [sensu/sensu-go#3059]
I'm unable to get the agent (v5.9) running on a RHEL5 (5.11) server. There appear to be at least 2 issues..

## Expected Behavior
Agent should start up successfully when running `service sensu-agent start`

## Current Behavior
1. Startup script fails.
2. `sensu-agent` command crashes

Looking at the startup script, there's a call to `chroot` passing in the --userspec parameter.. This doesn't seem to exist on the version of `coreutils` installed on RHEL5 by default:
`coreutils-5.97-34.el5_8.1`

```
# chroot --help
Usage: chroot NEWROOT [COMMAND...]
  or:  chroot OPTION
Run COMMAND with root directory set to NEWROOT.

      --help     display this help and exit
      --version  output version information and exit

If no command is given, run ``${SHELL} -i'' (default: /bin/sh).

Report bugs to <bug-coreutils@gnu.org>.
```

If I simply remove the userspec parameter and just call the binary directly as the sensu user, the client simply crashes immediately with the following output:

```
$ /usr/sbin/sensu-agent
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0xf83548, 0x17)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.netpoll(0x271060fd847e00, 0x0)
        /usr/local/go/src/runtime/netpoll_epoll.go:75 +0x209
runtime.sysmon()
        /usr/local/go/src/runtime/proc.go:4326 +0x374
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1206 +0xc4
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1172 +0x6f

goroutine 1 [chan send]:
os/signal.signal_enable(0xc00000000f)
        /usr/local/go/src/runtime/sigqueue.go:207 +0x6c
os/signal.enableSignal(...)
        /usr/local/go/src/os/signal/signal_unix.go:50
os/signal.Notify.func1(0xf)
        /usr/local/go/src/os/signal/signal.go:135 +0x8f
os/signal.Notify(0xc0002c63c0, 0xc000125e28, 0x2, 0x2)
        /usr/local/go/src/os/signal/signal.go:147 +0x148
main.main()
        /go/src/github.com/sensu/sensu-enterprise-go/cmd/sensu-agent/main.go:23 +0x119

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 19 [select]:
github.com/sensu/sensu-enterprise-go/vendor/github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000957d0)
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/ipfs/go-log/writer/writer.go:76 +0x11c
created by github.com/sensu/sensu-enterprise-go/vendor/github.com/ipfs/go-log/writer.NewMirrorWriter
        /go/src/github.com/sensu/sensu-enterprise-go/vendor/github.com/ipfs/go-log/writer/writer.go:41 +0xb9
```

## Steps to Reproduce (for bugs)
1. Perform a clean installation on RHEL5.11
2. Run `service sensu-agent start` - Then check /var/log/sensu/sensu-agent.log
3. Give `sensu` user a shell in `/etc/passwd`
4. `su` to `sensu` user and manually run `/usr/sbin/sensu-agent`

## Context
Unable to use Sensu on RHEL 5

## Your Environment
Sensu v5.9
RHEL 5.11

**Comment by adammcdonagh** [comment]
Have you dropped support for RHEL5 in 5.10? Still listed on the site, but there's no new RPM for EL5 in packagecloud...

**Comment by annaplotkin** [comment]
We are not going to support RHEL 5 at this time, closing this issue.

**Comment by adammcdonagh** [comment]
May I suggest you take this off your website please? Especially since people looking to purchase Enterprise (like me) may see this and think it’s viable to migrate everything to Sensu Go... I’ve now got to redevelop a load of stuff due to the incorrect listing on your site...

**Comment by annaplotkin** [comment]
@adammcdonagh Apologies for the miscommunication and confusion! We are definitely updating our documentation and website to accurately reflect this. 👍
