### ISSUE TITLE
Developing and debugging filter libraries is relatively difficult

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3069]
## Expected Behavior

As a Sensu implementor it's relatively easy for me to develop and debug JavaScript filter libraries.

## Current Behavior

It's relatively difficult to develop and debug filter libraries, due in part to the lack of visibility into the event object actually received by a filter.

## Possible Solution

Implement a JavaScript REPL in sensuctl which allows implementers to experiment with a copy of a given event -- i.e. import the latest event for a specified agent/check pair into the REPL as the `event` object -- and make it possible for the REPL session to be dumped to a text file so that folks can pull the content into their IDE of choice.

## Steps to Reproduce (for bugs)

1. Write a filter library, package it as an asset
2. Configure filter definition using that asset, and a handler to use the filter
3. Send test events which you expect to be filtered or not filtered, perhaps see in the backend logs that your expectations are not met
4. Attempt to gain insight into what's happening in your filter library by adding console.log and other methods of printing debugging messages, but find that those messages are not printed in a way thats visible in the backend logs.

## Context

The above steps to reproduce are a reflection of my experience in developing a filter library for contact routing. Ultimately we were able to get the library working by drawing on the expertise of Sensu Go engineering team, who helped us determine that the filter was failing because we were trying to access some parts of an event which we expected to be present but were not.

In an effort to find a different approach the problem, I learned that Sensu Go is using [otto](https://github.com/robertkrimen/otto) to provide the JavaScript VM for filter execution. Otto has a [REPL package](https://godoc.org/github.com/robertkrimen/otto/repl) which I think could be used to implement the possible solution described above. I believe that if I had been able to play with an example event in a REPL my development time would have been shortened significantly.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend 5.9
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by annaplotkin** [comment]
Design challenge: 

- Interface for canned events (modifiable template perhaps?)
- REPL can give people access to event fixture and they can set attributes on that in the REPL
- Create, modify and send event through their filters (what API would be this be?)


** Create prototype of an otto REPL with utilities to create an interface for canned events
