### ISSUE TITLE
Create proxy entity if an entity doesn't exist for events published to the Events API(s) 

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#3081]
## Expected Behavior

For all events published to the `sensu-backend` /events API, check if the referenced `entity` exists in the API, and if not, create an entity with `"class": "proxy"`. 

## Current Behavior

We don't automatically create an entity upon processing an event if the event references an entity that doesn't exist in the registry (we used to do this in Sensu 1.x). 

## Possible Solution

Create missing entities (with `"class": "proxy"`) for events published to the `sensu-backend` /events API. 

## Context

The "monitoring event pipeline" workflow from Sensu Classic is compromised in Sensu Go without this change. 

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): any
* Installation method (packages, binaries, docker etc.): any
* Operating System and version (e.g. Ubuntu 14.04): debian stretch

**Comment by calebhailey** [comment]
It's been a while since I've tested this. I have observed that this functionality is not present in `sensu-backend` (i.e. the backend API) as of version 5.10; however I don't recall if the behavior is different in the `sensu-agent` events API. IIRC, the sensu-agent does behave differently (perhaps already implementing this feature), which is great – but we should ideally see both of these /events API endpoints behave more consistently.

**Comment by cwjohnston** [comment]
Adding my two cents here:

* I can confirm that submitting events to the agent API does create a proxy entity when the check specifies a `proxy_entity_name` which does not yet exist
* I agree that the backend `/events` API should implement this same behavior
* From a previous conversation I have noted the following per @portertech:
  > We should create the proxy entity, we should ensure the user posting the event has the right RBAC permissions to create both the event and the entity

**Comment by roganartu** [comment]
Didn't see this when I opened #3179, but it's definitely related (though instead is a feature request to disable this functionality).

There's also #3178 which is a bug caused by the way the agent -> backend interaction creates new entities. It's unlikely an implementation of this would hit the same race condition that causes #3178, however the fix I proposed in #3195 makes significant changes to the `getProxyEntity` function likely to be re-used by the backend API for this, so I thought it was also worth linking here.

**Comment by calebhailey** [comment]
@roganartu I like the idea of a toggle to disable this functionality. The default should be to accept all events (given valid authentication and RBAC), and create proxy entities for entities that don't exist; but if you want to disable this functionality, we add a `--reject-orphaned-events` flag (or similar), as you suggest in #3179.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/634

**Comment by portertech** [comment]
Simon to comment with findings.

**Comment by palourde** [comment]
For reference, this behavior is currently possible if you specified an entity name via the check's attribute `proxy_entity_name`:

https://github.com/sensu/sensu-go/blob/40b1d59382517863bd0ba38cdc2241d6d6c1196e/backend/agentd/entity.go#L23-L31

The `getProxyEntity` function is called from the `handleEvent` method of the agentd's session:

https://github.com/sensu/sensu-go/blob/572b4b5facc4a4f7b310dcf0eb34ef711e9583e5/backend/agentd/session.go#L356-L360

Therefore, with a simple tweak to this condition, we could simply create the proxy entity all the time and use `proxy_entity_name` to override the entity name:
https://github.com/sensu/sensu-go/blob/40b1d59382517863bd0ba38cdc2241d6d6c1196e/backend/agentd/entity.go#L24

**Comment by portertech** [comment]
We should probably change the function name to better represent what it's doing.

**Comment by portertech** [comment]
"The change itself is simple, however, there is a good deal of testing to be done"

**Comment by portertech** [comment]
This could be considered a breaking change.
