### ISSUE TITLE
Improve unit/integration test coverage for tessen

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3093]
While there is decent [unit/integration test coverage](https://github.com/sensu/sensu-go/blob/master/backend/tessend/tessend_test.go) for Tessen, it would be beneficial to validate the exact payloads which are sent by the daemon. We should utilize mocks for the etcd `Count` function which is used for each resource type: https://github.com/sensu/sensu-go/blob/20a39ac88e90a1c806685453ad18be57612aa724/backend/tessend/tessend.go#L552

**Comment by portertech** [comment]
The objective is to eliminate the need for some of our tessen end-to-end testing.

**Comment by echlebek** [comment]
[coverage.pdf](https://github.com/sensu/sensu-go/files/4277198/coverage.pdf)

**Comment by portertech** [comment]
Light refactoring to improve line coverage. Reduce QA Tessen end-to-end tasks to just verifying the presence of data.

**Comment by nikkixdev** [comment]
The following e2e tests can be removed once unit/integration test coverage is improved:
- https://sensuinc.testrail.io/index.php?/cases/view/6835
- https://sensuinc.testrail.io/index.php?/cases/view/5514
- https://sensuinc.testrail.io/index.php?/cases/view/6836
