### ISSUE TITLE
It should be possible to determine which filter(s) dropped an event

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3107]
## Expected Behavior

As a Sensu implementor I can debug filter expressions and event filter definitions by reviewing log output.

## Current Behavior

Log messages do not indicate which filter or filters matched an event.

## Possible Solution

List in the log message which filter(s) caused the event to be dropped.

## Steps to Reproduce (for bugs)

1. configure a handler with one or more filters
2. send an event to that filter
3. observe log message 

## Context

Example log message:
```json
{"check_name":"fatigue_test","check_namespace":"default","component":"pipelined","entity_name":"sensu-go","entity_namespace":"default","handler":"pushover","level":"info","msg":"event filtered","time":"2019-07-02T17:58:53Z"}
```
I happen to know this event was dropped by a filter called 'fatigue-check' which is not present in the log entry.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.10
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by palourde** [comment]
For reference, this information is already logged but at the `debug` log level, e.g. https://github.com/sensu/sensu-go/blob/8c6d5564bd66c0fecf6a52d1e9b2c32460829330/backend/pipelined/filter.go#L105

We should probably just move stuff around so the actual reason is logged.
