### ISSUE TITLE
Set handler with multiple single-level nested set handlers erroneously flagged as deeply nested

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3109]
Creating a set handler that has multiple single-level nested set handlers will flag the handler as deeply nested, even though it doesn't exceed the nesting limit of 3.

## Expected Behavior
With the following handlers defined:
```
{
  "type": "Handler",
  "api_version": "core/v2",
  "metadata" : {
    "name": "keepalive",
    "namespace": "default"
  },
  "spec": {
    "type": "set",
    "handlers": [
      "page",
      "audit"
    ]
  }
}

{
    "type": "Handler",
    "api_version": "core/v2",
    "metadata": {
        "name": "page",
        "namespace": "default"
    },
    "spec": {
        "handlers": [
            "pagerduty",
            "slack"
        ],
        "type": "set"
    }
}

{
    "type": "Handler",
    "api_version": "core/v2",
    "metadata": {
        "name": "audit",
        "namespace": "default"
    },
    "spec": {
        "handlers": [
            "elasticsearch"
        ],
        "type": "set"
    }
}
```

All handlers should attempt to execute.

## Current Behavior
The following error is seen in the logs every time a keepalive event is generated:
```
Jul 02 15:18:09 shanetmon1 sensu-backend[22273]: {"component":"pipelined","error":"handler sets cannot be deeply nested","handler":"audit","level":"error","msg":"failed to expand handler set","namespace":"default","time":"2019-07-02T15:18:09-04:00"}
```

Sensu is successfully expanding the `page` handler set, but then complaining that the identically-deep `audit` handler set is too deeply nested.

## Possible Solution
The cause is here: https://github.com/sensu/sensu-go/blob/65d5d01d37affaada8890efbc896fad11cc23607/backend/pipelined/handle.go#L159-L161
The level is incremented for each handler in the top-level set.

`level++` should be removed and the recursive call should become:
```
setHandlers, err := p.expandHandlers(ctx, handler.Handlers, level+1)
```

## Your Environment
This exists on master.

**Comment by palourde** [comment]
Good catch @roganartu, thanks for opening this issue!
