### ISSUE TITLE
Filters runtime_assets return "null" when empty

### ISSUE THREAD

**Issue by JqckB** [sensu/sensu-go#3115]
As discussed on Slack, when you are requesting GET /filters and if runtime_assets is empty,
runtime_assets equals null.

On the documentation `https://docs.sensu.io/sensu-go/5.10/api/filters/#filters-get` we are expecting runtime_assets: [].

## Expected Behavior

With POST /filters

```
{
    "metadata": {
      "name": "yolo2",
      "namespace": "default",
      "labels": null,
      "annotations": null
    },
    "action": "allow",
    "expressions": [
      "event.check.occurrences == 1"
    ],
    "runtime_assets": []
}
```

When requesting GET /filters : 
```
[{
    "metadata": {
      "name": "yolo2",
      "namespace": "default",
      "labels": null,
      "annotations": null
    },
    "action": "allow",
    "expressions": [
      "event.check.occurrences == 1"
    ],
    "runtime_assets": []
}]
```

## Current Behavior

With POST /filters

```
{
    "metadata": {
      "name": "yolo2",
      "namespace": "default",
      "labels": null,
      "annotations": null
    },
    "action": "allow",
    "expressions": [
      "event.check.occurrences == 1"
    ],
    "runtime_assets": []
}
```

When requesting GET /filters : 
```
[{
    "metadata": {
      "name": "yolo2",
      "namespace": "default",
      "labels": null,
      "annotations": null
    },
    "action": "allow",
    "expressions": [
      "event.check.occurrences == 1"
    ],
    "runtime_assets": null
}]
```

## Possible Solution

Change null to empty list.

## Context
I'm currently implementing an Ansible role that install and configure Sensu-Go.

My variable sensu_filters is a list of dicts, representing the JSON of each objects.
As I want to know if a filter is already configured, I'm comparing the result from the API to my list of filters locally. 

It is easier to tell on my role that it is a list, empty or not, to compare it.

## Your Environment
sensu-go 5.10.1 in Docker

**Comment by JqckB** [comment]
I really think that you have this issue with all empty list in GET requests : I just saw the same issue with /handlers that doesn't respond as documented in the API documentation.

Is it possible to get a feedback on this ?

**Comment by palourde** [comment]
I believe this is caused by protobuf serialization. Somehow we are transforming `nil` slices to empty slices for a couple of attributes:

https://github.com/sensu/sensu-go/blob/c7c0221125a842e5ed704f48b9633207b1011bf5/api/core/v2/check.go#L200-L205

We should figure out a way to easily standardize this pattern without having to write a ton of conditions!
