### ISSUE TITLE
Add check_dependencies for feature parity

### ISSUE THREAD

**Issue by hanej** [sensu/sensu-go#3122]
Sensu Go needs the same check_dependencies filter feature of Sensu Core to reduce alert fatigue.

https://docs.sensu.io/sensu-core/1.7/reference/filters/#check-dependencies-filter

## Expected Behavior

It should work the same way as in Sensu Core

## Current Behavior

This is not implemented in Sensu Go

## Context

This feature is absolutely critical to determine root cause when monitoring many different events.  Currently we are seeing lots of red when one process goes down and it's difficult to determine where the problem actually is.  On call cannot be paged multiple times for a single issue.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):
Sensu Go 5.10
RHEL 7.6 RPM

**Comment by majormoses** [comment]
To add a bit more flavor this is accomplished in the ruby sensu via https://github.com/sensu/sensu-extensions-check-dependencies which is a sensu filter written in ruby as an extension. I am not sure if this makes sense to pull in the core :thinking:

**Comment by scalp42** [comment]
jumping on this but it's the biggest blocker for us to adopt Sensu Go as we always put a dependency on `keepalive` for example.

**Comment by ichilton** [comment]
IMO this is an essential feature.

If say a web server fails, you don't want to be swamped with alerts for sites on that server. Or if a connection fails, you don't want alerts for all hosts behind that connection - you just want to know the link is down so you can fix it.

Is there a workaround or the possibility of bumping up the priority of this feature?

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/reducing-event-floods-and-check-dependencies/1802/1

**Comment by hanej** [comment]
This was a deal breaker for us so we moved to Zenoss.  Very happy with the decision.

**Comment by echlebek** [comment]
Last week, I authored a proposal to make this type of feature possible in sensu-go.

We are going to expand the Javascript event filter feature to allow querying the Sensu event store. Users will be able to query the store for events and inspect their attributes, even if those events aren't related to the one being filtered.

This capability will enable us to write a filter asset that can be used to do check dependency filtering, which we will make available on Bonsai.

We'll be meeting next week to file issues and define the scope of the work, and probably start work on the feature shortly after that.

It's still too early to comment on the release schedule for this feature, but work has begun and is in progress.

**Comment by ichilton** [comment]
Amazing - that sounds brilliant and will be useful for a number of things! Thanks @echlebek! - look forward to seeing that progress!

**Comment by ichilton** [comment]
@echlebek 2 things for you to think about when discussing this.

1) Let me explain this with an illustration.

Say you have an event for a VM which is dependent on a VM host (or a site that's dependent on a web server and a backend and/or database server). The dependency might be down, but you're in the middle of the interval and don't know yet. So you'd handle the alert for the VM and then x seconds later, you'd alert for the vm host being down and that'd be bad.

Maybe this is a non-issue if you have a handler with an occurrences filter - as by the time you get to the 2nd or 3rd occurrences, the dependency will have returned critical at least once so the dependency check will work.

What I was thinking though is it would be good if when you get an event for a check with dependencies, it delays handling that event until it's forced a check execution and received the results, for each dependency. Not sure if that is possible/practical? - but something to think about.

2) The bigger problem here might be resolution events. And this links in to https://github.com/sensu/sensu-go/issues/3785. 

Using the same examples for illustration - say a vm host or web server dies, with the functionality above, we can filter events for vms on that host or sites on that web server so they are not handled.

But then the vm host or web server comes back up. So then we get resolution events for the VM or site... and because the dependency is now back up, how do we stop those resolution events being handled? - because that would be bad.... you'd then get a flood of resolution events for alerts you didn't raise. So we really need some way of filtering resolution events, so a resolution event is only handled if the incident event was successfully handled.

See what I mean?

Thanks.

**Comment by portertech** [comment]
We are shipping check dependencies in Sensu Go 6.0, which is currently schedule to be released this Thursday (the 23rd)! The release also includes several other exciting changes, including those describe in https://blog.sensu.io/unlocking-another-level-of-automation-with-sensu-go-6.

We developed check dependencies as part of an enhanced commercial filtering engine, it is available to anyone using the commercial distribution (which is free of under 100 entities). The documentation is currently a work in progress, but here are a few usage examples.

```
// If the network and disk checks are passing on the same entity as
// the event being filtered, then true is returned. Otherwise, false.
sensu.CheckDependencies("network", "disk")

// If the disk check is passing on the same entity as the event
// being filtered, and the ping check is passing on the router entity,
// then true is returned. Otherwise, false.
sensu.CheckDependencies("disk", {entity: "router", check: "ping"})

// An error is raised. The check was not found. Filter execution
// is aborted.
sensu.CheckDependencies("not_found_check")

// An error is raised. The wrong type of argument was supplied.
// Filter executino is aborted.
sensu.CheckDependencies(0.5)

// No checks are specified. CheckDependencies returns true.
sensu.CheckDependencies()
```

The `sensu.CheckDependencies()` function builds upon several other functions (i.e. `sensu.EventStatus()`), making is possible to construct your own take on dependency filtering. You will be able to uses these functions and the store API in your filter expressions and custom Javascript assets \o/ These functions will be documented soon after time of release.

For OSS users, our developer advocates will be sharing one or more patterns for accomplishing check dependency like filtering, using OSS features like filter javascript assets, API keys, and the events API.

@hanej Thank you for creating this issue! I hope this new and improved form of check dependency filtering will serve you well!

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/check-depenedencies-support-for-oss-users/2071/1

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/reducing-event-floods-and-check-dependencies/1802/5

**Comment by daswars** [comment]
have any of you a real live example with check_dependencies and the oss version

**Comment by hanej** [comment]
@portertech Any update on this comment?

> For OSS users, our developer advocates will be sharing one or more patterns for accomplishing check dependency like filtering, using OSS features like filter javascript assets, API keys, and the events API.

**Comment by roganartu** [comment]
For anyone already running a fork or building the OSS version themselves, getting this working was actually pretty trivial. I thought I'd share for future readers. This is the diff to the backend you need (from v6.2.3 tag):
```
diff --git a/backend/pipeline/filter.go b/backend/pipeline/filter.go
--- a/backend/pipeline/filter.go
+++ b/backend/pipeline/filter.go
@@ -63,9 +63,10 @@
 
 	synth := dynamic.Synthesize(event)
 	env := FilterExecutionEnvironment{
-		Event:  synth,
-		Assets: assets,
-		Funcs:  PipelineFilterFuncs,
+		Event:    synth,
+		Assets:   assets,
+		Funcs:    PipelineFilterFuncs,
+		MyFuncs: MyPipelineFilterFuncs,
 	}
 
 	// Add silences as they require the store to be passed in
diff --git a/backend/pipeline/my_filter_funcs.go b/backend/pipeline/my_filter_funcs.go
new file mode 100644
--- /dev/null
+++ b/backend/pipeline/my_filter_funcs.go
@@ -0,0 +1,11 @@
+/*
+	This file is adds custom filter functions to the event pipeline.
+	They end up under the "my" namespace inside filters, such that one can do the
+	following:
+
+		my.<filter_func_name>(arg1, arg2)
+*/
+package pipeline
+
+// MyPipelineFilterFuncs holds filter function definitions.
+var MyPipelineFilterFuncs = map[string]interface{}{}
diff --git a/backend/pipeline/js.go b/backend/pipeline/js.go
--- a/backend/pipeline/js.go
+++ b/backend/pipeline/js.go
@@ -19,6 +19,9 @@
 	// Funcs are a list of named functions to be supplied to the JS environment.
 	Funcs map[string]interface{}
 
+	// MyFuncs are a list of custom named functions to be supplied to the JS environment.
+	MyFuncs map[string]interface{}
+
 	// Assets are a set of javascript assets to be evaluated before filter
 	// execution.
 	Assets asset.RuntimeAssetSet
@@ -49,11 +52,18 @@
 	var result bool
 	err := js.WithOttoVM(assets, func(vm *otto.Otto) (err error) {
 		if f != nil {
+			// Built-in Sensu funcs
 			funcs := make(map[string]interface{}, len(f.Funcs))
 			for k, v := range f.Funcs {
 				funcs[k] = dynamic.Function(ctx, vm, v)
 			}
 			parameters["sensu"] = funcs
+			// My custom funcs
+			myFuncs := make(map[string]interface{}, len(f.MyFuncs))
+			for k, v := range f.MyFuncs {
+				myFuncs[k] = dynamic.Function(ctx, vm, v)
+			}
+			parameters["my"] = myFuncs
 		}
 		result, err = js.EvalPredicateWithVM(vm, parameters, expression)
 		return err
diff --git a/backend/pipeline/pipeline.go b/backend/pipeline/pipeline.go
--- a/backend/pipeline/pipeline.go
+++ b/backend/pipeline/pipeline.go
@@ -12,6 +12,8 @@
 	"github.com/sensu/sensu-go/command"
 	"github.com/sensu/sensu-go/rpc"
 	"github.com/sensu/sensu-go/types"
+	"github.com/sensu/sensu-go/backend/authorization/rbac"
+	"github.com/sensu/sensu-go/backend/api"
 )
 
 // Pipeline takes events as inputs, and treats them in various ways according
@@ -59,6 +61,20 @@
 	for _, o := range options {
 		o(pipeline)
 	}
+
+	// Setup MyPipelineFilterFuncs.
+	// The store passed to these functions is shared across all pipeline ctors afaict.
+	// Just init the functions on first pass.
+	auth := &rbac.Authorizer{
+		Store: pipeline.store,
+	}
+	client := api.NewEventClient(pipeline.store, auth, nil)
+	if _, ok := MyPipelineFilterFuncs["FetchEvent"]; !ok {
+		MyPipelineFilterFuncs["FetchEvent"] = client.FetchEvent
+	}
+	if _, ok := MyPipelineFilterFuncs["ListEvents"]; !ok {
+		MyPipelineFilterFuncs["ListEvents"] = client.ListEvents
+	}
 	return pipeline
 }
```

The above is intentionally short on functionality, because it's easier to maintain a JS function than it is to make changes to the backend. To get feature parity with the documented check dependencies you then just need the following JS func:
```
// Queries Sensu via my.FetchEvent method (patched in API access in the backend)
// for event(s) matching the given objects. Returns true if all events are ok, false
// otherwise (or on error).
function CheckDependencies() {
    if (arguments.length === 0) {
        console.log("No arguments passed to CheckDependencies, skipping")
        return true;
    }

    if (event === undefined || event.check === undefined) {
        return false;
    }

    // Short-circuit if the my methods aren't defined
    if (typeof my === "undefined") {
        console.log("my undefined, passing through filter");
        return true;
    }

    for (var i = 0; i < arguments.length; i++) {
        var arg = arguments[i];
        var entity = event.entity.name;
        var check = null;
        if (typeof arg === "string") {
            check = arg;
        }
        else if (typeof arg === "object") {
            entity = arg.entity;
            check = arg.check;
        } else {
            throw new TypeError("argument to CheckDependencies should be either a string or an object")
        }

        if (!entity || !check) {
            throw new Error("Failed to determine check or entity");
        }
        if (typeof entity !== "string" || typeof check !== "string") {
            throw new TypeError("Check and entity arguments to CheckDependencies should be strings.")
        }

        if (entity === event.entity.name && check === event.check.name) {
            console.log("Skipping dependency check for self");
            continue;
        }

        var upstreamEvent = my.FetchEvent(entity, check);

        if (upstreamEvent === undefined) {
            throw new Error(entity + ":" + check + " not found.")
        }
        if (upstreamEvent.check.status !== 0) {
            console.log(entity + ":" + check + " dependency is failing.")
            return false;
        }
    }
    return true;
}
```

We've been running this in prod for a while now against many thousands of events/minute without issues. Hope it helps someone.
