### ISSUE TITLE
Enhancement: Allow more expressive asset names

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3146]
Moving forward I'd like to be able to capture more information as to upstream source for a particular asset in the asset name. Goal is to provide at a glance origin in the asset name, and to provide an asset name that potentially maps to specific asset registry.

Strawman Assetname:
github.com/jspaleta/crazy-handler:4.0.0-pre.1+wassup_arch_platform

Goal:
work towards a naming scheme that can be used to pull a Bonsai config by "repo:tag"
like naming scheme,

Info I want to encode into the asset name

origin: ex: github.com/jspaleta 
asset name: ex: crazy-handler
asset semver: ex: 4.0.0-pre.1_wassup
asset arch  
asset platform 

Currently "colon" and "plus" are illegal characters I believe.

Question can we extend naming to allow "colon" and "plus" symbols.

**Comment by nikkixdev** [comment]
Asset names can now include colons and forward slashes.
