### ISSUE TITLE
Sensuctl Windows Packaging Updates: Convert Zip to an MSI, Extract to common folder for executables & Add Sensuctl to 

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3149]
## Expected Behavior

As a Windows user installing `sensuctl` feels a bit second-class on Windows. Ideally, I'd be able to run an .msi and the executable to would be added to a folder with other executables and this would be added to my path.

## Current Behavior

The amount of effort to unzip, place the executable in a folder with other executables, and ensure that it's added to my path is far too manual of a process. I'm spending more time trying to get sensuctl installed and configured than I am writing checks. Since this is the primary tool for interacting with Sensu, these sorts of hurdles are a bit deflating if it's expected that Sensu is easy to set up and get running. That may be more on the backend case, or the agent case. It doesn't feel like that for a Windows operator.

**Comment by asachs01** [comment]
It should also be noted that it would make things easier to have this installed via chocolatey.

**Comment by echlebek** [comment]
We have chocolatey now, so can this be closed?

**Comment by calebhailey** [comment]
@asachs01 can we close this, given the many Windows packaging improvements we've implemented?

**Comment by asachs01** [comment]
👍
