### ISSUE TITLE
Support informat media types for achives

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#3157]
See https://discourse.sensu.io/t/sensu-asset-file-format-is-invalid-error/1272/6.

We should also support `x-gzip` & `x-tar` in here: https://github.com/sensu/sensu-go/blob/cce7a1c02aa93d8d634f6853d714ed8609b9ad80/asset/expander.go#L45-L56.

**Comment by jspaleta** [comment]
So this is tough... technically that 'x-' is an unregistered type and we can't assume anything in that space. 'x-' types are experimental should be agreed to by both ends 
Ref: rfc2048 and rfc2045

which I interpret to mean we shouldn't hardcode ANY 'x-' types at all as they have no agreed on meaning.

What we should do is offer a configurable list of additional file types to allow as part of config.

**Comment by jspaleta** [comment]
Hey so user is reporting that the archive does exapand but the "given file of format" error is showing up in the logs.. Maybe we need to enhance the error message to provide information as to which file is producing the error message?

**Comment by jspaleta** [comment]
FYI:
Here's where the matching logic is that we are using to infer the Mimetype from the tmpfile on disk

https://github.com/h2non/filetype/blob/v1.0.10/matchers/archive.go

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/sensu-asset-file-format-is-invalid-error/1272/26
