### ISSUE TITLE
Usernames cannot contain uppercase characters

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3167]
## Expected Behavior

As a cluster administrator I can create usernames which contain uppercase characters

## Current Behavior

Usernames which contain uppercase characters aren't allowed via sensuctl

## Possible Solution

Use a more permissive regex?

## Steps to reproduce
1. Configure sensu-backend and sensuctl
2.`sensuctl user create FooBar --password foobarbazqux`
3. Observe message `Error: username cannot contain spaces or special characters`

## Context

Customer sought to implement a naming scheme where a user `$NAMESPACE-admin` would be created with full permissions for `$NAMESPACE`. As we worked to implement this we found that the namespace can be created with uppercase characters but the username cannot. This seems rather arbitrary.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.11.0
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by palourde** [comment]
The username is the only string validated with the [ValidateNameStrict](https://github.com/sensu/sensu-go/blob/a786ceeb603601f89a39276824de346b098ad5e4/api/core/v2/validators.go#L34) validator, which uses this regex:

https://github.com/sensu/sensu-go/blob/a786ceeb603601f89a39276824de346b098ad5e4/api/core/v2/validators.go#L18

Before modifying this regex, we need to make sure all components (web-ui, sensuctl, etc.) are case sensitive; I know etcd is, so it shouldn't be a problem.
