### ISSUE TITLE
Register /opt/sensu with LANANA

### ISSUE THREAD

**Issue by jaredledvina** [sensu/sensu-go#3172]
Since I somehow end up in fun corners of the internet, I was reviewing the Linux Filesystem Hierarchy Standard and came across http://refspecs.linuxbase.org/FHS_3.0/fhs/ch03s13.html

I was curious if Sensu Inc has registered to use `/opt/sensu` so, I started the adventure on http://lanana.org/index.html and per http://lanana.org/lsbreg/providers/providers.txt, Sensu is not a registered provider. It looks like the source is also hosted in https://github.com/LinuxStandardBase/lanana

## Expected Behavior
Sensu is listed as a current provider for the LANANA managed LSB spec for `/opt/sensu`. 

## Current Behavior
Sensu is not registered. 

## Possible Solution
Register with LANANA as outlined on http://lanana.org/lsbreg/instructions.html and copied below.

> Namespace management requests and actions are tracked in a public bugtracker. To apply for a new reservation, or request a change to an existing one over which you have control, please file a new bug at: https://lsbbugs.linuxfoundation.org/, using Product: LANANA and Component: "/opt/ namespace assignment". Note you will need to create a bugzilla account here if you don't already have one.
> 
> When applying for a name in LSB namespaces for Init Scripts, Cron Scripts, Package Names or Provider Names, please perform the following steps for faster action on a submission:
> 
> Check LANANA's web pages to see if the name you wish to reserve is still available.
> Check if there is a pending registration listed in the bugtracker.
> Include the following information in your request:
> Your name
> An Email contact address
> Name of the Entity (company, organization, etc.) you represent
> Name of the Application or Project needing a reserved name.
> Project Website (if there is one).
> Suggested reserved names and from which namespace (init|cron|package|provider) desired.
> Any other notes that would help processing the application.
> Notes:
> 
> It is preferred if the email address is a persistent name, humans do leave the organizations they represent and the current LANANA data already have quite a few non-working contact emails. Thus, the style lanana-admin@example.com, set to deliver to the person submitting the request or other current contact, but able to be changed later without contacting LANANA, is a good idea.
> For the case of reserving init script namespace(s), please include a description of each init script's purpose. Example:
> foobar - start/stop the foobard daemon
>             
> Please try to anticipate what might be ambiguous to the registry team, and use the notes to explain. The team will ask for more information in the bugreport if needed, but it's quicker if there doesn't have to be a lot of back-and-forth.

## Context

Would be a shame if anyone else stole the namespace and made claims that Sensu violated the use of `/opt/sensu`.

**Comment by amdprophet** [comment]
Thanks for filing this @jaredledvina! Although we no longer use the `/opt/sensu` namespace with Sensu Go, I've gone ahead and filed a request for the reservation for our various projects. The reservation can be found here: https://lsbbugs.linuxfoundation.org/show_bug.cgi?id=4267

**Comment by dereckson** [comment]
Perhaps reopen this issue to track upstream need for update?

There is a comment needing to be addressed at  https://lsbbugs.linuxfoundation.org/show_bug.cgi?id=4267#c1
