### ISSUE TITLE
GLIBC_PRIVATE not defined in file libc.so.6 

### ISSUE THREAD

**Issue by joaogabriel-mb** [sensu/sensu-go#3174]
## Expected Behavior
It was expected that sensu checks works

## Current Behavior
I got this message: 

`check-cpu   ruby: relocation error: /var/cache/sensu/sensu-agent/8d6e7ef9bab057493ab25c4d5b9d68d324600b032b467e09cc26450141c1d4868fcd74704b7fc2c4523c23021c80291ee53f95f139d11a03b9fbf506d3455fbe/lib/libpthread.so.0: symbol __libc_dl_error_tsd, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
`

## Steps to Reproduce (for bugs)
1. Start an Amazon Linux 2 instance
2. Install Sensu-Go following the official documentation
3. Install check-cpu and sensu-ruby-runtime
4. execute sensuctl event list
5. the error occurred

## Your Environment
* Sensu version used (5.11, sensu-backend, and/or sensu-agent):
* Installation method by packages
* Operating System and version: Amazon Linux 2

**Comment by picapdjoe** [comment]
Following. Different os in my instance - Ubuntu 18.04.

**Comment by palourde** [comment]
Hi,

This is not an issue with Sensu Go, but rather `sensu-ruby-runtime`.

According to https://github.com/sensu/sensu-ruby-runtime/issues/18, the version 0.0.5 should work, not sure about the 0.0.8 one though.

**Comment by jspaleta** [comment]
Just released 0.0.9  with some changes concerning glibc handling.
Can you retest to see of the 0.0.9 debian asset works now for you?
