### ISSUE TITLE
Log rotation on non-systemd systems requires sensu-agent restart

### ISSUE THREAD

**Issue by zenmetsu** [sensu/sensu-go#3175]
The sensu-agent does not appear to respond to USR1 or USR2 signals as far as I can tell.  Without a means of re-opening the logs, on non-systemd systems this seems to require a complete restart of the sensu-agent.

## Expected Behavior
sensu-agent should re-open logs after receiving a USR1 signal via a logrotation script.

## Current Behavior
sensu-agent appears to ignore USR signals.

## Possible Solution
Addition of feature

## Steps to Reproduce (for bugs)
1. Set logging in agent.yml to "debug"
2. Restart sensu-agent
3. Verify /var/log/sensu/sensu-agent.log is filling up with data
4. Remove /var/log/sensu/sensu-agent.log via `rm` or other mechanism
5. Observe that log file is not re-created.
6. Send various kill signals to sensu-agent and observe that log file is not created.
7. Issue restart to sensu-agent to re-create the log.

## Context
Restarting the agent could potentially cause issues.  It will certainly present an opportunity for missed checks, and additionally there could be issues with the restart causing the agent to remain offline, triggering alerts.

## Your Environment
* sensu-agent 5.11
* Installation via package manager (yum/apt)
* Observed in both CentOS and Debian

**Comment by palourde** [comment]
@zenmetsu I believe the simplest solution here is to configure logrorate with the `copytruncate` option.

Handling log file rotation/deletion is not an easy problem to solve, because we would have to wrap the log file with a `io.Writer` that's passed to `Logger.SetOutput` and handle signals there.

**Comment by echlebek** [comment]
sensu-agent does not log to a file, except on Windows, where log rotation support is pending.

Since sensu-agent logs to standard out, there is nothing to be done, even if we did install a handler for SIGUSR1 or SIGUSR2. (Note, we recently made a change that SIGUSR1 now increments the logging level.)

Did you try the suggested approach of configuring logrotate to use copytruncate? If this was not successful, please let us know.

**Comment by hgfranco** [comment]
@echlebek is there a reason why the sensu-agent does not log to a log file except on Windows?

**Comment by echlebek** [comment]
@hgfranco Windows is the only OS sensu-agent supports that does not have good options for handling logs that are output to stderr. Tools like `logrotate` are much more mature than what sensu-agent does on Windows, and we want to steer users towards these options instead.

We expect that most if not all users will be best served by using `journalctl` via systemd, or hooking up stderr to a log consumer service in a system like kubernetes.
