### ISSUE TITLE
Sensugo generate same ID in all installation so unable to create cluster

### ISSUE THREAD

**Issue by masifpak** [sensu/sensu-go#3177]
## Need to install Sensu-Go in cluster mode on three machines

I have prepared three machines from scratch (Not cloned or not deploy using OVF or OVA).
Problem is that whenever and where ever I install sensu-go, it assign same ID to host. So same ID to three machines which cause to not create cluster of sensu-go.
I have three machines and all shows same result so no cluster.

[root@sensugonode01 ~]# sensuctl cluster member-list
=== Etcd Cluster ID: 3b0efc7b379f89be
         ID                                 Name                  Peer URLs                  Client URLs         
 ────                          ──────          ────                    ─────────
  8927110dc66458af     sensugonode1   http://127.0.0.1:2380     http://192.168.0.196:2379

**Comment by nikkixdev** [comment]
Hey @masifpak I'm sorry you're having trouble with your sensu cluster! I would recommend reading up on the [clustering docs](https://docs.sensu.io/sensu-go/5.11/guides/clustering/#traditional-computer-instance) as it will take you through some backend configuration examples to get a cluster up and running. Sensu backends do not have auto-discovery, so backends must be manually added with `sensuctl cluster member-add` or in the backend configuration files. Judging by your etcd cluster id, it appears that your 3 machines are running sensu locally, but are not configured to talk to _eachother_ yet. If you are still unsuccessful after going through the docs guide, please provide your backend configurations so we can help investigate further.

**Comment by masifpak** [comment]
I have fixed it. Remove /var/lib/sensu . folder, Reinstall everything again
