### ISSUE TITLE
Feature Request: Allow dropping of events with no entity

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3179]
Provide an option to the backend that causes it to drop (and log) events received for entities that do not exist.

## Expected Behavior
Submitting an event via the API for an entity that does not exist should not create an entity or an event.

## Current Behavior
Submitting an event via the API for an entity that does not exists creates a new entity and attaches the submitted event to it.

## Possible Solution
Add a flag to `sensu-backend` to enable this feature.

When the flag is provided and an event is received for an entity that doesn't exist, log a warning/error and drop the event.

## Context
We have tooling that syncs all our entities to Sensu from an existing central source of truth, so there is no situation where we would ever want to create an event for an entity that doesn't already exist. I would be useful if we could disable this automatic entity creation entirely.

This idea was motivated by the impact of #3178 on our environment.

**Comment by annaplotkin** [comment]
Moving so the team can discuss this morning.

**Comment by roganartu** [comment]
We came across another use case for this today: entity names are case sensitive, so an external tool we use to parse syslogs and create Sensu events created a new entity even though it already existed with a downcased name.

Sanitised output demonstrating this:
```
env  sensuctl entity info fooBAR                                                                     
=== fooBAR
Name:                   fooBAR
Entity Class:           proxy
Subscriptions:          entity:fooBAR
Last Seen:              N/A
Hostname:               
OS:                     
Platform:               
Platform Family:        
Platform Version:       
Auto-Deregistration:    false
Deregistration Handler: 

env  sensuctl entity info foobar
=== foobar
Name:                   foobar
Entity Class:           proxy
Subscriptions:          colo:foo, category:network, role:switch, entity:foobar
Last Seen:              2020-08-03 15:13:41 +0000 UTC
Hostname:               foobar
OS:                     
Platform:               baz
Platform Family:        
Platform Version:       
Auto-Deregistration:    false
Deregistration Handler:
```

This only became apparent because our tooling returned Not Found for events when using the lowercase variant. We will address this by downcasing all hostnames on egress from this syslog parsing service, but ultimately would prefer to be able to configure Sensu to return an error to that event creation instead.

I think this feature request could be better summarised as: Allow Sensu to be configured to respect an external source-of-truth for entities. The desire to ignore events from non-existent entities is simply a side-effect of the fact that we populate entities in Sensu from an external source-of-truth, really.
