### ISSUE TITLE
CI builds are failing to report version

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3184]
## Expected Behavior

I'd expect `sensuctl version` and other `version` subcommands to return values.

## Current Behavior

```
[root@sensu_backend /]# sensuctl version
sensuctl version #, build , built 
```

## Steps to Reproduce (for bugs)

First install RPMs from CI repo then install sensu packages and try the `version` subcommand.

## Context

The Puppet module for Sensu (sensu/sensu-puppet) is running acceptance tests for that module against CI builds for Sensu Go and those tests have started to fail.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 
```
[root@sensu_backend /]# rpm -qa | grep sensu
sensu-go-backend-5.11.1-5310.x86_64
sensu-go-cli-5.11.1-5310.x86_64
```
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment]
CC @ghoneycutt

**Comment by amdprophet** [comment]
Thanks for bringing this to our attention! This seems to have happened when we moved to go modules from dep for dependency management. We're currently investigating how to go about fixing this.

**Comment by amdprophet** [comment]
We've just merged a fix for this. Future packages in the `ci-builds` repository should not have this issue.
