### ISSUE TITLE
Replace Appveyor with CircleCI

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3188]
CircleCI recently announced [Windows support](https://circleci.com/blog/windows-general-availability-announcement/?mkt_tok=eyJpIjoiWVRJMllUUTBOVGxoTURZMyIsInQiOiJScjNWbm1oNEVQRUl4MzNkSHBsaHdXUVhcLzVWNVVBMUlIKzFlTlQrVnBqSzloQnJvekVsRjNHdGpxQThlZDVjYWduc2ZcL2ExTVNaR24zbjlkR0RubnNIcHMzbVpCUmxldWdtbUkzRkU0cUFCTUdqNEUxUGo2SnBxaGhzZHU3WlFWIn0%3D). We should attempt to port our [Appveyor configuration](https://github.com/sensu/sensu-go/blob/master/.appveyor.yml) to [CircleCI](https://github.com/sensu/sensu-go/blob/master/.circleci/config.yml) to evaluate its stability, and if all goes well completely remove Appveyor from our CI pipeline.

**Comment by nikkixdev** [comment]
Past Nikki thought this was a good idea. Present Nikki thinks this is a great idea.
