### ISSUE TITLE
Improve metrics exposed for Prometheus scraping

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3193]
Improve the set of metrics exposed for Prometheus scraping, mostly by adding new ones.

## Expected Behavior
The `/metrics` endpoint exposed by the agent and backend should provide more comprehensive metrics coverage of Sensu internals.

I would personally like to see metrics for the following things at least:
- Extend the existing wizard message bus metrics to maintain a counter of messages sent/received instead of just the current queue size
- agent: check execution counts and runtime histograms (with name and status as labels)
- Handler processing and runtime histograms (with name and success/fail/executed as labels)
- Filter processing and runtime histograms (with name, asset hash if it applies, filtered/matched, and error as labels)
- Hook execution and runtime histograms
- Mutator execution and runtime histograms
- Add event status as a label to the existing `sensu_go_events_processed` metric
- Backend and agent start time in seconds
- Silenced count, number of events silenced, count of cleared on resolution etc
- Asset counts (and maybe last updated timestamp labeled by hash? unsure if that's a good idea. We don't have very dynamic assets but maybe some people do)

Optional, but nice to have:
- Counter for number of proxy entities matched by schedulerd, labeled by check
- Histogram timings of all etcd store operations, labeled by operation (eg: `{store="event", action="find"}`)
- Histogram timings of all API endpoints, labeled by non-parametrized endpoint (ie: `{method="GET", "endpoint="/events/:entity/:check", status="200", le="..."}`, but without filling in ID to avoid high-cardinality in large installations)
- API response size histograms
- API response code counts
- RBAC logins (incl failures), permission denials, permission grants, user/role/role-binding counts

## Current Behavior
The metrics coverage is currently limited, exposing the following:
- internal etcd stats (these are reasonably good, but are provided by the etcd lib)
- grpc stats (also pretty good, also provided by the grpc lib)
- backend: message queue sizes (`sensu_go_wizard_bus`)
- backend: total number of event messages processed (`sensu_go_events_processed`)
- backend: number of active agent sessions (`sensu_go_agent_sessions`)
- agent: nothing except the default metrics that the prometheus go lib provides

## Context
Managing production services is much better when you can observe internals via metrics. There are logs for some of these things, but not many and debug logging is often not a great solution to observability. Metrics collection is relatively cheap.

**Comment by echlebek** [comment]
Great suggestions, thanks!
