### ISSUE TITLE
Check result view should surface check and entity labels

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3196]
##  Expected Behavior

As a Sensu user viewing event details (check result view), I can see the labels defined for the relevant check and entity.

## Current Behavior

I have to visit the check and entity definitions separately to view any labels.

## Context

Providing a URL for a runbook or other documentation in check attributes is a common practice in Sensu 1.x. Making such attributes visible in the event/check result view makes those responding to these events easier as the information needed to respond to the event is immediately accessible.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend 5.11.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): centos 7

**Comment by dabria** [comment]
Completed: https://github.com/sensu/web/pull/222
