### ISSUE TITLE
Feature Request: Add support for env vars in hooks

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3197]
## Expected Behavior

As a user implementing hooks in my workflow, I have cases where I'd like to make calls out to an external service or API and those calls might contain sensitive information, such as an API token or key. Ideally, those values could be obfuscated through the use of environment variables inside of my hook definition.

## Current Behavior

Currently, I have make the bare call out that contains my API token, which is not ideal.

## Possible Solution

Implement support to allow for env vars in the hook primitive.

**Comment by calebhailey** [comment]
@asachs01 seems like what we might want now is support for Secrets in Hooks?
