### ISSUE TITLE
Redaction broken

### ISSUE THREAD

**Issue by ollivers** [sensu/sensu-go#3207]
Redacted passwords are not passed to the involved command script. Instead the word "REDACTED" is passed

## Expected Behavior
We are using proxy entities with labels set i.e.:

Entity:
--------
type: Entity
api_version: core/v2
metadata:
  name: rz2-fas-3-0016 
  namespace: ICS-STO
  labels:
    aggr_critical: "90"
    aggr_warning: "80"
    username: "nagios"
    password: XXXXXXX
    ipaddress: "172.16.x.xxx"
    proxy_type: "netapp"
spec:
  entity_class: proxy

Check:
---------
type: CheckConfig
api_version: core/v2
metadata:
  name: check_cdot_aggr
  namespace: ICS-STO
spec:
  command: /opt/nagios/netapp/netapp-cdot-nagios/check.sh {{ index .labels "password" }}
  env_vars: ["PERL5LIB=/opt/nagios/netapp/netapp-manageability-sdk-9.6/lib/perl/NetApp"]
  handlers:
  - email_stosberg
  interval: 60
  publish: true
  proxy_requests:
    entity_attributes:
    - entity.entity_class == 'proxy'
    - entity.labels.proxy_type == 'netapp'
  subscriptions:
    - proxy

Password XXXXXXX should be passed to check.sh

## Current Behavior
String "REDACTED" is passed to check.sh

## Steps to Reproduce (for bugs)

check.sh:
#!/bin/bash
echo ${1}

create above entity and check.

check event log:

~# sensuctl event info rz2-fas-3-0016 check_cdot_aggr
=== rz2-fas-3-0016 - check_cdot_aggr
Entity:      rz2-fas-3-0016
Check:       check_cdot_aggr
Output:      REDACTED
Status:      0
History:     0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Silenced:    true
Silenced By: *:check_cdot_aggr, entity:rz2-fas-3-0016:*
Timestamp:   2019-08-16 13:07:56 +0200 CEST

## Context
NetApp system cannot authenticate without valid password string

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensuctl version 5.11.1#39d2bf2, build 39d2bf22c416f9a78f22c4817dc74ab62d7f4d63, built 2019-07-18T13:31:59Z
sensu-agent version 5.11.1#39d2bf2, build 39d2bf22c416f9a78f22c4817dc74ab62d7f4d63, built 2019-07-18T13:31:26Z
sensu-backend version 5.11.1#39d2bf2, build 39d2bf22c416f9a78f22c4817dc74ab62d7f4d63, built 2019-07-18T13:30:28Z

* Installation method (packages, binaries, docker etc.):
Packages

* Operating System and version (e.g. Ubuntu 14.04):
Ubuntu 18.04

**Comment by palourde** [comment]
Hi @ollivers 

I apologize for the late response. I just attempted to reproduce this issue but it appears to now be working as expected on the latest release.

From this point I'll go ahead and close this issue but please let us know if you still face the same problem on the 5.16 release.

Thanks!
