### ISSUE TITLE
Feature Request: Add timestamp to agent header when downloading an asset

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3208]
## Feature Suggestion

As a user who uses S3 to host assets for compliance and security reasons, I'd like to not have to use HAproxy to inject the header information to the agent requests to S3. I'd like to have the ability to use S3, or S3-compliant storage and have the header include the timestamp (see https://docs.aws.amazon.com/general/latest/gr/sigv4-date-handling.html for more info) so that my agents can download assets. 

## Possible Implementation

Agent could have the label:
`use_s3: true`

Which would cause the header to be injected.

## Context

In a conversation with a customer, it was discussed that they use S3 to ensure that certain security policies are enforced. As part of this, they'd like to have the header `x-amz-date` with a timestamp that is in UTC and follows the ISO 8601 format: YYYYMMDD'T'HHMMSS'Z'.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/3695 (many other asset templating enhancements shipping in ~5.21.0, not including timestamps).
