### ISSUE TITLE
URLs in label values should be clickable links in web UI

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3212]
## Feature Suggestion

Label values which contain URLs should be rendered as clickable links in the web UI.

## Context

This is a feature of Uchiwa and Sensu Enterprise Dashboard which is frequently used to help responders quickly connect to documentation and other information that provides context about the check, entity or event they are viewing.

**Comment by rgeniesse** [comment]
In addition to clickable links, it appears on the actual event page as of Sensu Go 5.14 that neither labels or annotations are available. As labels are a better fit for clickable links, as an operator I'd like to have labels available for additional context when viewing events (and most likely annotations as well for other information)
