### ISSUE TITLE
Ability to query PostgresConfig state

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3218]
## Feature Suggestion

It would be ideal if there was a way to query that a `PostgresConfig` had been created or defined.

## Possible Implementation

`sensuctl datastore info` if there is only plans to support one datastore at a time or `sensuctl datastore list` if multiple are possible.

## Context

I am writing Puppet logic for sensu-puppet module to manage the PostgreSQL datastore and there is no way for Puppet to know if the datastore is configured since the only hooks are create and delete. I can not add support for delete because I have no way to know if a create has taken place other than creating arbitrary state files and that's really not ideal.

**Comment by portertech** [comment]
We're actively working on this, tracking on the internal enterprise repository.

**Comment by echlebek** [comment]
As of 5.14, you will be able to do this with:

```
sensuctl dump store/v1.PostgresConfig
```
