### ISSUE TITLE
YAML parser can not handle comments

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3219]
## Expected Behavior

I'd expect that a YAML File passed into `sensuctl create -f` would be able to have comments which is supported by YAML spec.

## Current Behavior

Currently YAML comments break sensuctl.

## Steps to Reproduce (for bugs)

```
[root@sensu_backend /]# cat /etc/sensu/postgresql.yaml 
# File managed by Puppet
---
type: PostgresConfig
api_version: store/v1
metadata:
  name: postgresql
spec:
  dsn: postgresql://sensu:changeme@localhost:5432/sensu
  pool_size: 20

[root@sensu_backend /]# sensuctl create -f /etc/sensu/postgresql.yaml 
resource 0: error parsing spec: type could not be found: ""
Error: some resources couldn't be parsed
```

REMOVE COMMENT

```
[root@sensu_backend /]# cat /etc/sensu/postgresql.yaml 
---
type: PostgresConfig
api_version: store/v1
metadata:
  name: postgresql
spec:
  dsn: postgresql://sensu:changeme@localhost:5432/sensu
  pool_size: 20
[root@sensu_backend /]# sensuctl create -f /etc/sensu/postgresql.yaml 
[root@sensu_backend /]# 
```

## Context

Sometimes it's necessary for the Puppet module for Puppet to write out a YAML file for sensuctl and it's a best practice to put a comment in Puppet managed files to indicate it's managed by Puppet.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensuctl version 5.11.1#39d2bf2, build 39d2bf22c416f9a78f22c4817dc74ab62d7f4d63, built 2019-07-18T13:31:59Z`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment]
Somehow this is not causing errors:

```
---
# File managed by Puppet
type: PostgresConfig
api_version: store/v1
metadata:
  name: postgresql
spec:
  dsn: postgresql://sensu:changeme@localhost:5432/sensu
  pool_size: 20
# absent
```

The way to write YAML with Puppet won't be able to do the above comment at the top.

**Comment by flowerysong** [comment]
Putting the comment before the document marker (`---`) turns this into a multi-document YAML file, which is probably not what Sensu is expecting. Either put the comment after the marker, or leave out the marker entirely.

**Comment by portertech** [comment]
Thank you @flowerysong. This is expected behaviour. Closing this issue.
