### ISSUE TITLE
Expose sensu-go version in entity information available for asset filters.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3225]
## Feature Suggestion
Expose sensu-go-backend and sensu-go-agent  version in entity information available for asset filters to use.

## Context
Relates to: #3067 and #3222 
This potentially helps corner cases when using multi-build asset definition with a mix of multi-build capable agents (>= 5.X) and multi-build incapable agents ( < 5.X ) for whatever X is the minor release that introduces multi-build assets

we could define single build assets to be used only for the older agents that filter on the agent version.

**Comment by jspaleta** [comment]
Note:
For the purpose of proxy requests... what should be exposed is the version of the actual agent executing the check.. not the version set in the proxy entity definition

**Comment by nikkixdev** [comment]
The `sensu_agent_version` is populated in all agent entities. ex. `sensu_agent_version: 5.19.3`.  Related to https://github.com/sensu/sensu-go/issues/2184 for backend entity information.

**Comment by calebhailey** [comment]
@jspaleta can we close this as "won't fix"? At the time I think we were concerned about compatibility issues with the new Asset "builds" functionality, but it doesn't seem that many (any?) users encountered issues there?
