### ISSUE TITLE
home missing in dashboard

### ISSUE THREAD

**Issue by thorko** [sensu/sensu-go#3242]
When I call the sensu-backend dashboard the home is missing.
When I call the URL http://localhost:3000/default/home it says
not found in namespace

**Comment by palourde** [comment]
Hello @thorko,

Did you deleted the `default` namespace by chance? Or is it possible the user you're trying to log in with does not have access to that namespace?

Thanks

**Comment by thorko** [comment]
Hi,
I've compiled the sensu-backend binary by myself. When I started a
single sensu-backend node I don't get the home screen in the default
node. So I guess I need to compile it with different options.
The options I used were
```
 CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags '-X
$(BUILDVERSION) -X $(BUILDDATE)' -o dist/amd64/sensu-backend
cmd/sensu-backend/main.go
```
Cheers

Am 19.11.19 um 19:48 schrieb Simon Plourde:

**Comment by palourde** [comment]
Hi @thorko,

Could you provide us some screenshots of what you are seeing? Also, with the same user configured on `sensuctl`, could you give us the output of the `sensuctl namespace list` command?

Thanks

**Comment by thorko** [comment]
Hi,
I've created user admin and password test with
%%snip%%
sudo ./dist/amd64/sensu-backend init -c /etc/sensu/backend.yml 
--cluster-admin-password password --cluster-admin-username admin
%%snip%%

I've attached the screenshots I'll get when starting the backend


sensuctl namespace list
   Name
 ─────────
  default

Regards

Am 06.01.20 um 17:17 schrieb Simon Plourde:

**Comment by kovukono** [comment]
I'm still experiencing this same issue with the 5.17.1 release. While the commercial version appears able to show the dashboard without issue, creating your own binary from source does not show the home option on the dashboard, and is also producing a different URL (URL/c/~/n/default/home). Attempting to connect to that URL assumes that it's trying to use "c" as that namespace. Attempting to connect to "URL/n/default/home" produces the error "not found in namespace".

![Sensu-Go-Built](https://user-images.githubusercontent.com/11382431/74779774-2cd00f80-526c-11ea-99b4-a1c7cd11ba21.png)
![Sensu-Go-Commercial](https://user-images.githubusercontent.com/11382431/74779776-2cd00f80-526c-11ea-8437-8292e45f6ab9.png)

**Comment by palourde** [comment]
Hi all!

I just spoke with our web UI team and it appears that the homepage is a commercial feature that's only part of our commercial distribution. Therefore, the behavior you are seeing is expected. I apologize for the confusion.

I've opened [an issue](https://github.com/sensu/sensu-docs/issues/2189) on the sensu-docs repo, in order to update the documentation so it's appropriately identified as a commercial feature.

Thanks
