### ISSUE TITLE
new tag  format vX.XX break compilation build.sh

### ISSUE THREAD

**Issue by realPy** [sensu/sensu-go#3248]
The build.sh use the last tag to catch the version number for compilation.
The regex use in version/cmd/version/version.go handle only X.XX
The bugs appears with the git tag v5.12 and must be tag as 5.12 like the other tags

**Comment by palourde** [comment]
Hi @realPy, we've deprecated the `build.sh` script since it was no longer used and maintained by the team. Instead, we added some simple instructions on how to run and build from source: https://github.com/sensu/sensu-go#building-from-source

Hopefully this will make it easier for you!
