### ISSUE TITLE
How can we see status of entities in grid instead of a single column?

### ISSUE THREAD

**Issue by masifpak** [sensu/sensu-go#3250]
I don't know is it possible or not to see all entities in grid instead of a single column. If not, it may be a good feature.

**Comment by palourde** [comment]
Hello @masifpak,

Are you referring to the dashboard or sensuctl view? Also, do you have a concrete example of what you would like to see?

Thanks!

**Comment by palourde** [comment]
I'm going to close this issue since we did not received any response from the author.
