### ISSUE TITLE
Handlers for keepalive events should be configurable

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3267]
## Feature Suggestion

It should be possible to send keepalive events to any configured handler.

## Possible Implementation

Allow agent configuration to specify a list of handlers which should receive the agent’s keepalive events.

## Context

This is a 1.x parity feature.

Current implementation in Sensu Go is limited to sending keepalive events to a `keepalive` handler in the agent namespace.

**Comment by portertech** [comment]
We need to implement Agent `keepalive-handlers`, the keepalive generated events can pull the handler list from this.
