### ISSUE TITLE
windows ctl download link

### ISSUE THREAD

**Issue by derekgroh** [sensu/sensu-go#3271]
As discussed at SensuSummit, provide a link to directly download SensuCTL for windows.

## Expected Behavior
https://sensu.io/products/downloads should provide a download link for SensuCTL the same as RHEL/CentOS.

## Current Behavior
Link is not available on download site, but can be obtained by using the following link: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.11.1/sensu-enterprise-go_5.11.1_windows_amd64.tar.gz

## Possible Solution
* Provide updated link upon release of new versions.
* Release a choco package for sensuCTL

## Steps to Reproduce (for bugs)
1. Visit https://sensu.io/products/downloads 

## Context
Provides a barrier to entry for Windows users, lack of clarity and transparency.

## Your Environment
N/A

**Comment by calebhailey** [comment]
the /products/downloads path is from the old website, which we have recently completely overhauled - including a new downloads page: https://sensu.io/downloads 

This downloads page provides much better visibility into every available download for Sensu Go, including the Windows binary downloads: https://sensu.io/downloads#windows 

It looks like we currently offer links to a tarball w/ the Windows sensuctl + sensu-agent binaries, and the website offers instructions that you can copy & paste to install sensuctl on Windows: https://sensu.io/get-started?platform=windows (see step 2). 

We'll go ahead and close this issue, but please feel free to comment or open a new issue if you don't think it is resolved. 

Thanks!

**Comment by derekgroh** [comment]
@calebhailey tarballs are not native to Windows, which is original intent with this issue. 
The packaging provides individuals rpms for each component of SensuGo for linux: https://sensu.io/downloads#linux but fails to do the same for windows. This request is to treat both platforms equally to promote easier adoption for windows users.

**Comment by calebhailey** [comment]
@derekgroh ah, I see. We do provide links to windows .zip archives, FWIW (see: https://sensu.io/downloads#windows), but it seems you're looking for MSIs. This issue title indicates a desire for "direct download links" (which we have satisfied with the new website), and the original description referenced an S3 URL to a windows binary tarball: 

> Link is not available on download site, but can be obtained by using the following link: https://s3-us-west-2.amazonaws.com/sensu.io/sensu-go/5.11.1/sensu-enterprise-go_5.11.1_windows_amd64.tar.gz

So it seems we have resolved the initial request here, but what you really want now is an MSI that installs `sensuctl` only. Makes sense. We have an issue open for this in a private repo; let me see if we can move that to this repo so you can comment on it with a +1. Sound good? 

Even if we don't move that issue, do know that this is on our radar and we will update the downloads page as soon as `sensuctl` MSIs are available. 😃
