### ISSUE TITLE
Embedded etcd has a critical bug

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3278]
See https://github.com/etcd-io/etcd/issues/9949

Upgrading to the latest patch release should mitigate this bug.

**Comment by echlebek** [comment]
@portertech, I think that we should try to address this for 5.15.

**Comment by palourde** [comment]
Should we use this opportunity to upgrade to v3.4.2?

**Comment by echlebek** [comment]
I think we should yes.

**Comment by echlebek** [comment]
We are going to use the latest 3.3 release branch to target 5.14.1 for this.

**Comment by portertech** [comment]
@echlebek looking for updates here.
