### ISSUE TITLE
Allow for more effective filtering using sensuctl

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3286]
## Possible Implementation

In a recent customer interaction, they mentioned the following:

```
It would be great if we could filter using the in operator on entity names, or even use some regex.

Often we would like to quickly filters that match parts of our host naming convention for a given server role.

[We] notice the in operator also appears to want a full string match.
e.g for a subscriptions called "foobar"
"foobar in entity.subscriptions" will return results
"foo in entity.subscriptions" will not.
This is a be counter-intuitive for the in operator as it is acting more like a
```

## Context

This is affecting the customer's ability to effectively search using `sensuctl`

Related: https://github.com/sensu/web/issues/200 in the web project

**Comment by calebhailey** [comment]
I notice that the excerpt from the customer doesn't actually mention `sensuctl` - do we know for sure that they meant `Sensuctl and not the web UI?

**Comment by nikkixdev** [comment]
Sensuctl and the web ui use the same mechanism for filtering, so I believe it would apply to both if implemented. Wondering if this is satisfied by the `matches` operator from 5.19.0?
