### ISSUE TITLE
sensu-agent does not parse SENSU_SUBSCRIPTIONS environment variable correctly

### ISSUE THREAD

**Issue by johannagnarsson** [sensu/sensu-go#3287]
## Expected Behavior

when setting environment variable SENSU_SUBSCRIPTIONS I would expect it to behave the same way as the `--subscriptions` parameter.
## Current Behavior

When setting the SENSU_SUBSCRIPTIONS environment variable to: `linux,foo,bar` it results in subscriptions on the client side that look like this:
```
subscriptions:
- linux,foo,bar
- entity:<hostname>
```
when starting the agent via `sensu-agent start --subscriptions linux,foo,bar` it results in subscriptions that look like this:
```
subscriptions:
- linux
- foo
- bar
- entity: <hostname>
```
## Possible Solution

Ideally the SENSU_SUBSCRIPTIONS environment variable would be parsed in the same way as the `--subscriptions` command line argument.
## Steps to Reproduce (for bugs)

1. Remove the subscriptions portion from agent.yml
``` yaml
# cat /etc/sensu/agent.yml
---
backend-url:
- wss://backend.domain.com:8081
trusted-ca-file: "/etc/sensu/ssl/ca.crt"
```
2. set SENSU_SUBSCRIPTIONS to a comma separated value; "linux,foo,bar"
```
# cat /etc/systemd/system/sensu-agent.service.d/override.conf 
[Service]
PermissionsStartOnly=true
ExecStartPre=/usr/bin/bash -c "/usr/bin/systemctl set-environment SENSU_SUBSCRIPTIONS=linux,foo,bar"
```
3. start sensu-agent
4. verify subscriptions with `sensuctl entity info <hostname>`
```
sensuctl entity info <hostname>
=== <hostname>
Name:                   <hostname>
Entity Class:           agent
Subscriptions:          linux,foo,bar entity:<hostname>
Last Seen:              2019-09-19 10:51:50 -0700 PDT
Hostname:               <hostname>
OS:                     linux
Platform:               centos
Platform Family:        rhel
Platform Version:       7.6.1810
```

## Context

We have a dynamic environment that requires us to set certain configuration values based on runtime data from the host. This prevents us from correctly setting subscriptions

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
sensu-{agent,ctl,backend} 5.13
* Installation method (packages, binaries, docker etc.):
sensu signed RPM packages.
* Operating System and version (e.g. Ubuntu 14.04):
CentOS 7.6.1810

**Comment by palourde** [comment]
@johannagnarsson This is due to the way Viper, the library we rely on to parse configs, deals with values from environment variables and flags in an [inconsistent manner](https://github.com/spf13/viper/issues/380).

I'm not totally sure how we could implement a workaround on our side but in the meantime, you can always do the following instead:

```
SENSU_SUBSCRIPTIONS="linux macos" sensu-agent

```

**Comment by echlebek** [comment]
I'm going to close this, as this appears to be inherent in the way our CLI framework works, and not something we can directly address without forking or replacing it.
