### ISSUE TITLE
Expose embedded etcd heartbeat interval and election timeout options

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3300]
Expose embedded etcd heartbeat interval and election timeout options so that they may be tuned under certain conditions.

etcd timing docs: Add CLI flags etc for the two options.

## Feature Suggestion
Add Backend CLI flags and options for the two etcd options.

`--etcd-heartbeat-interval=100 --etcd-election-timeout=500`

**Comment by ccressent** [comment]
Great link for documentation purposes: https://github.com/etcd-io/etcd/blob/master/Documentation/tuning.md#time-parameters
