### ISSUE TITLE
Check TTL events can be created even if failing keepalive events exist

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3304]
## Expected Behavior
An entity with a keepalive failure event should not create a check TTL event.

## Current Behavior
Failing events are created for both keepalives and checks.

## Possible Solution
When a check TTL event fails to fire, the handler should consult the store for whether or not a failing keepalive event exists for the entity in question.

## Steps to Reproduce (for bugs)
1. Create a check with TTL enabled.
2. Take the associated entity offline.
3. Observe failing events for both the keepalive and check.

## Context
Reported by steveberryman in the community slack.

**Comment by calebhailey** [comment]
It this getting released with 5.17.0?

**Comment by palourde** [comment]
Yep, it has been included in 5.17 but it wasn't merged right away in `master` so Github didn't closed it automatically 🤦‍♂

**Comment by rmatte** [comment]
I really wish this change had been added with a switch that we could switch this off with on a per check basis. Not being able to do that is causing major issues for us right now with something we're trying to implement. We're using a handler to add/remove nodes from a service automatically based on the result of a check and it works fine as long as the entire remote agents doesn't go down. When it goes down a keepalive event gets generated and the check just completely stops working which means that the check itself doesn't see the agent go down and the handler never gets called. Having a switch that could be enabled to disable this behavior on individual checks would be very nice. This implementation seems unnecessarily rigid.

**Comment by echlebek** [comment]
The reason this was implemented this way is that it keeps the cluster from being destabilized by check TTL events when there are mass agent outages. 

You can avoid that behaviour by using a proxy entity, which isn't subject to keepalive failures.

**Comment by sabbene** [comment]
I agree with @rmatte.  Sensu core had the concept of check dependencies that would prevent cluster from being overwhelmed by check ttl events.  That allowed much more flexibility.
