### ISSUE TITLE
sensuctl should print messages indicating the success or failure of operations

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3319]
## Feature Suggestion

sensuctl output should indicate when CRUD operations succeed or fail. 

## Possible Implementation

A few ideas:
* Use response codes from the API to determine if CRUD operations are successful. 
* When the input describes multiple resources, print one line for each resource acted upon.
* When the input describes multiple resources, print a summary showing N resources created/updated, N deleted, N failed?

## Context

Without messages like these, operators may not feel very confident that the requested action was taken. This extends to contexts where sensuctl is run under automation.

**Comment by cwjohnston** [comment]
Reopening this as a recent customer experience has brought this gap back to the forefront for me.

In this case, the customer had need to restore their Sensu instance from backups. Having followed advice to create backups using `sensuctl dump`, they had a 45mb yaml file to recover from.

Restoring the yaml via `sensuctl create -f resources.yml`, the command ran for a while and exited without printing any output. Since no errors were produced, this was ostensibly a successful execution. 

A quick check showed that some expected resources were present, e.g. namespaces, entities and checks, but for some reason the entities weren't being updated. We puzzled over this for some time, before realizing none of the expected roles or role bindings necessary for their agents to communicate had been created. 

Extracting RBAC resources from the superset of resources helped to restore agent communication, but now the team will need to manually review the dump and compare it to what is present in sensu-backend to identify any gaps.

**Comment by ccressent** [comment]
Next time something of that sort happens, try to also capture what the exit status of `sensuctl` is, e.g. with `echo $?` right after the tool's execution.

That will help us decide which of the following cases most likely applies here:
- status 0: likely there is a bug or errors ignored
- status > 0: we're not displaying all errors

**Comment by calebhailey** [comment]
Closing this in favor of #3079. We just updated 3079 with a proposed solution that would cover the requirements here.
