### ISSUE TITLE
Usefulness of sensuctl dump is limited due to sensitive information

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3326]
## Expected Behavior

As a Sensu operator I can use automation to both create and restore backups of my Sensu backend configuration.

## Current Behavior

Using `sensuctl dump all > resources.yml` yields a backup which cannot be automatically restored due to password attributes having been omitted from the spec for each User resource. Other resource types may have similar limitations around secret or sensitive attributes.

## Possible Solution

1. Extend the /core/v2/users API and sensuctl to allow specifying hashed passwords when creating users
2. Add a flag to `sensuctl dump` which allows operators to opt-in to exporting hashed user passwords in the dump

## Context

I've run into these limitations while trying to write tooling to enable automated backup and restore of a single backend in an autoscaling group. I can see a way forward by manipulating user resources to add a temporary password, but this feels wrong for a variety of reasons.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by portertech** [comment]
It would seem, if authentication providers were able to leverage secrets management, `sensuctl dump` could be a viable means of backup and restore (via `sensuctl create`). If an authentication provider is not used, the only way we could support the user resource would be if we introduce a way to configure user password hashes (eric "it feels wrong, but maybe it's ok").

**Comment by portertech** [comment]
Related issues:

Add `sensuctl hashpass` command: https://github.com/sensu/sensu-go/issues/1768

Support specifying password hash directly in user json: https://github.com/sensu/sensu-go/issues/1697

**Comment by portertech** [comment]
cyril "eh"

**Comment by nikkixdev** [comment]
I'm going to set up a conversation for this next week!
