### ISSUE TITLE
Periodically disconnect agents from backends

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3329]
Over time, agent connection distribution can become skewed, if a backend experiences an outage, for instance. We can rebalance the cluster by forcing agents to reconnect periodically.

Add a configuration flag to the `sensu-agent` that specifies the amount of time, in minutes, that agents should remain connected before disconnecting and reconnecting to another backend. The configuration flag should be named `--max-session-length` and should be specified as a time duration. (i.e. 3s, 10m, 1h)

The default should be 15m.

Add jitter to the time when calculating when to reconnect agents, so that a thundering herd scenario does not occur. The jitter algorithm should be
```
wait = wait + time.Duration(rand.Float64()*float64(wait))
```

**Comment by echlebek** [comment]
I think the outcome from casual discussion around this issue is that it's something a load balancer should handle.

**Comment by echlebek** [comment]
It looks like we would like to do this after all.

**Comment by portertech** [comment]
We will make it opt in with no default value.

**Comment by portertech** [comment]
Work also includes loadit updates and SPDC testing.

**Comment by calebhailey** [comment]
Getting close to testing against SPDC. Cyril has observed a failing integration test that he's investigating.
