### ISSUE TITLE
Bug: Sensuctl dump producing invalid yaml with dumping multiple resources to a file.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3333]
some of the  resource breaks  "triple dash" are missing from the file output and are outputed to stdout instead.
## Steps to Reproduce (for bugs)

1. run:
`sensuctl dump all -f /tmp/dump.yaml`

2. Notice some triple dashes leak into stdout
3. examine dump.yaml  and see that triple dashes are missing in front of the first resource in each resource type.
4. cry

## Your Environment
sensuctl 5.14

**Comment by ydkn** [comment]
see #3331

I also thought that the YAML would be invalid (due to duplicate keys) but interestingly running "sensuctl create" with the file seems to have worked after I gave it a quick test.

**Comment by echlebek** [comment]
Closed in #3331
