### ISSUE TITLE
Implement option for multip-build asset configuration in sensuctl

### ISSUE THREAD

**Issue by Blue0ctober** [sensu/sensu-go#3341]
Running `sensuctl asset update foo` acts like it's updating a single-build asset, prompting for all values as if the asset is not already defined.

## Feature Suggestion

When multi-build assets from bonsai are created via `sensuctl asset add foo`, each version should be configurable via an alias or by it's hash value.

Alias can be something like `foo/bar_alpine_linux_amd64` and `foo/bar_centos_linux_amd64`

Their name should still remain the same (universal) for ease of adding assets to configurations. 

## Possible Implementation

`sensuctl asset update foo/bar:HASH`
or
`sensuctl asset update foo/bar_version`

## Context

This has caused issue when having to update an asset added via `sensuctl asset add foo` and requiring to edit the filters as they were too narrow.

**Comment by portertech** [comment]
Let's try and document the `sensuctl edit` experience for multi-build assets. Pulling the `sensuctl asset update` feature could be a viable means of "fixing" this terrible UX. eric "The only good code is dead code"
