### ISSUE TITLE
[Feature Request] Expose "state" field in check history

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3350]
The `state` field of [Events](https://docs.sensu.io/sensu-go/5.15/reference/events/#top-level-attributes) describes whether the event is currently considered to be flapping. Include this field in the check history to enable more advanced filtering and handler behaviour, mimicking the flapping start/end notifications that Nagios sends.

## Feature Suggestion
Sensu follows the same algorithm for flap detection as Nagios as outlined here: https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/flapping.html

One of the features that Nagios exposes is notifications for start/end of flapping. This allows users to perform actions when flapping starts/end. Exposing this `state` field in check history would enable Sensu filters and handlers to differentiate between "this check is flapping" and "this specific event is when the check started/ended flapping".

## Possible Implementation
This could be added to the `Check.MergeWith` method that handles updating check history:
https://github.com/sensu/sensu-go/blob/8a21de8d0cd336d81418bc1cb4c55ed855cfe1bf/api/core/v2/check.go#L229-L249

The field could be added as the `state` string as currently stored in the check, or a `flapping` bool, or similar.

## Context
We have a slack channel that some alerts are sent to depending on filters etc. Instead of simply filtering events where `state=="flapping"` we would like to be able to send "X started flapping" and "X finished flapping: current status is Y" notifications when flapping starts and ends.

**Comment by echlebek** [comment]
We'd like to pick this up internally and add the "state" field to the event history, rather than only a flapping boolean, as we feel this would address more use cases, being more general.

We will also take a look at the issue with low_flap_threshold. Thanks!
