### ISSUE TITLE
[Feature Request] Support filters for set handlers

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3353]
Add support for filters to be attached directly to set handlers, allowing control over whether the set handler is expanded.

## Feature Suggestion
Set handlers currently ignore filters. This is documented here:
https://docs.sensu.io/sensu-go/5.15/reference/filters/#how-do-sensu-filters-work
> NOTE: Filters specified in a handler set definition have no effect. Filters must be specified in individual handler definitions.

And is confirmed in the source here:
https://github.com/sensu/sensu-go/blob/71fa44a/backend/pipelined/handle.go#L56-L70
where you can see set handlers are expanded by `expandHandlers` before filters are applied.

## Possible Implementation
Apply filters that are attached to set handlers before expanding those handlers, allowing the filter to control whether the handlers are expanded.

## Context
I have a set handler that controls paging, approximately as follows:
```
{
  "metadata": {
    "name": "page",
    "namespace": "default"
  },
  "type": "set",
  "timeout": 60,
  "handlers": [
    "pagerduty",
    "slack",
    "email"
  ],
}
```
Where each of `pagerduty`, `slack`, and `email` are handlers with their own filters.

I want to make a specific check only trigger this `page` handler during business hours. I can't modify each of the nested handlers because that will affect every alert. With this feature I would be able to create a second set handler with a `business_hours` filter. Currently this functionality requires I also duplicate each of the nested handlers (eg: `pagerduty_business_hours`, ...) where the only different between `pagerduty` and `pagerduty_business_hours` is the additional filter.

**Comment by roganartu** [comment]
cc @echlebek as he originally told me to raise this issue when I brought this up in the slack a couple of months ago

**Comment by ichilton** [comment]
I too have requested this! (before seeing this issue). It's well described here.
