### ISSUE TITLE
Backend Cluster Init Utility

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3359]
From WIP internal proposal (needs implementation discussion): https://docs.google.com/document/d/14exgupRiOp1DBieDs51Nshl9E8mfKETbvvOWm4tG2Mk/edit?usp=sharing

## Abstract

Sensu Backend should not ship with a built in Admin username and password. A Backend cluster (one or more Backends) should require an initialization, which bootstraps the first Admin user account. The created Admin will be granted the Cluster Admin role. An operator only need to provide a username and password string (they do not need to understand RBAC etc). The Sensu Backend Init Utility provides a command to initialize a fresh Cluster with these details.

## Background

Sensu Backend currently ships with a built-in Admin username and password (admin:P@ssw0rd!). This is problematic but makes things “easy”.

## User Stories

As an operator, I need to deploy a new Sensu Backend cluster and initialize it with a unique and secure admin username and password.

## Proposal

Hashi Vault does something similar: https://www.vaultproject.io/docs/commands/operator/init.html
`sensu-backend init`

env vars:
`SENSU_ADMIN_USERNAME`
`SENSU_ADMIN_PASSWORD`

command line flags:
`--admin-username`
`--admin-password`

interactive mode:
`sensu-backend init --interactive`

Removed the current default admin username and password seed values.

## Rationale

Using a utility makes the installation process consistent across platforms.

## Compatibility

Existing users can upgrade without issue, no need to initialize, since their cluster has already seeded the default admin username and password (hopefully changed since then). New users will require guidance and documentation which includes the addition of a cluster initialization step.

## Implementation

- [ ] Remove the default admin user from fixed seed data (https://github.com/sensu/sensu-go/blob/master/backend/seeds/seeds.go)
- [ ] Create a sensu-backend init subcommand
      - Two required arguments, see above.
      - Two environment variables, see above.
      - Interactive mode, see above.
- [ ] The init subcommand will use the same etcd configuration as defined in `backend.yml`, and the same defaults if undefined

Required by https://github.com/sensu/sensu-staging/issues/164
Required by https://github.com/sensu/sensu-docs/issues/1917
Required by https://github.com/sensu/website/issues/447

**Comment by majormoses** [comment]
see https://github.com/sensu/sensu-go/issues/2898 for additional context

**Comment by portertech** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configurable Sensu seed data](https://trello.com/c/Yk7DhyU1/8-configurable-sensu-seed-data)
