### ISSUE TITLE
Optional Content-Type: application/octet-stream for Agent WebSocket handshake

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#337]
If an agent connects to agentd and includes in the request header `Content-Type: application/octet-stream`, the agent session on the backend should use protobuf for serialization/deserialization.

Otherwise it should default to JSON decoding/encoding.

**Comment by echlebek** [comment]
This is going to be important when we start trying to push the number of agents a backend can service. I'm adding a suggested 5.1.0 milestone as a placeholder for renewed discussion.

**Comment by grepory** [comment]
There is potential that we may not support websockets in the future. I'd rather take a step back and instead of focusing on a potential solution/optimization to a future problem, solve the problem when it arises--not limiting ourselves to this approach.

**Comment by echlebek** [comment]
I'm re-opening this issue, as we now wish to enable protobuf serialization in `sensu-agent`.
