### ISSUE TITLE
[Feature Request] Include check output in history

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3370]
Add output from check to history.

## Feature Suggestion
Currently, the history only includes two fields: `status` and `executed`. #3363 proposes adding a `flapping` boolean field to indicate whether the check was flapping at a particular point in time, allowing for more powerful filtering (specifically, start and end flap notifications similar to Nagios).

This request is for adding the `event.check.output` field to each entry in `event.check.history`.

## Possible Implementation
Implementation would be basically identical to that in #3363, ie add a new field and populate it on check merge.

One potential complication that may need to be discussed is whether there should be a max size for the added field, where anything above is truncated by the check merge? History size is hardcoded to 21 entries per event, so this is possibly not a major concern.

## Context
In a similar vein to #3363 enabling more intelligent filtering, there are situations where it would be useful for filters to have access to previous check output in order to make better decisions.

### Generic examples

- Perform a certain action for stale checks, but not on the first occurrence. With the current check history it is not possible to differentiate between a regular warning and one generated due to TTL being exceeded.
- Match a filter only if a certain pattern has been seen in a number of outputs in history. Consider for example a disk check where you wish to ignore a particular mountpoint for certain machines. Check output is likely to contain some kind of structured `mountpoint, usage` output, but having a separate check for each mountpoint makes little sense, nor does baking logic into the check to whitelist certain mountpoints for certain machines. `occurrences` doesn't help with this case either as it also doesn't allow you to historically differentiate between `/mnt/a -> warn | /mnt/b -> ok` and `/mnt/a -> ok | /mnt/b -> warn`. A filter could do this with access to output history, and seems like the logical place for it (at least to me).

### Specific, motivating example
We have a large number of checks that are logically grouped but that make little sense to have a separate check name for each. I previously proposed more complex grouping functionality be added in #2750 but it seems unlikely to happen due to entrenched assumptions throughout various Sensu components about the uniqueness of hostname+check name.

We have solved this by storing an encoded JSON object in our check outputs which contains more detailed information about each component of a check. Take the following (decoded) output from a ping check as a concrete example of what this looks like:
```
{
    "foo": {
        "status": 2,
        "data": {
            "rta": {
                "threshold": {
                    "critical": "disabled",
                    "warning": "disabled"
                },
                "status": "ok",
                "value": 37.1,
                "description": "ok"
            },
            "packet_loss": {
                "threshold": {
                    "critical": ">= 60%",
                    "warning": ">= 30%"
                },
                "status": "critical",
                "value": 75.0,
                "description": "100.0 >= 60%"
            }
        }
    }
}
```
As you can see there is detailed information there about the state of each component of the check that (for some of our less generic checks) it would be useful to be able to make filtering decisions based on the history of.

**Comment by echlebek** [comment]
Thanks for requesting this feature.

We feel that adding check output to the history is not going to be workable from a performance standpoint.

Users that need detailed histories can't really rely on the event history, which mostly exists for the purposes of things like flap detection and is quite limited.

For users who need richer event history, we would suggest using a TCP or pipe handler to feed events into an external database. Unfortunately this brings the information outside of Sensu, but we have size constraints around events and they are already quite heavy.
