### ISSUE TITLE
[Feature Request] Support multiple silences for a single entity/subscription

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3374]
Add support for multiple (potentially overlapping) silences for a single entity/subscription.

## Feature Suggestion
Users should be able to have two silences with different start/end times, but that are otherwise identical.

## Possible Implementation
I don't think this is trivial to achieve due to the way silences are currently structured and processed.

There are strong assumptions about both the uniqueness of names, and the structure of those names are currently used to process the silence. See https://github.com/sensu/sensu-go/issues/3356#issuecomment-545471799 for an example bug this approach has caused however, so perhaps the design of silences should be revisited.

## Context
There are many scenarios where this behaviour is desirable, and arguably necessary. Nagios (and I think every other monitoring tool I've ever used) allows you to have multiple silences for a single check, but Sensu does not.

Duplicate silences with different start/end dates are very useful for controlling alerts and responding to incidents. Consider the following simple-but-common scenario:

1) User has planned some work for some point in the future, and proactively schedules downtime for the checks/entities expected to be affected by creating a silence with a start date in the future.
2) Before that silence time arrives, an incident occurs for which the responding user sets an immediate downtime for the affected check/entity in order to silence alerts while they work to remediate the issue.

Doing this in other monitoring tools involves simply creating a new downtime with a start date set to now. Doing this in Sensu as it currently stands requires either deleting the existing silence first, or editing the existing silence to change the date to start immediately, but both of these require noting the previous silence details in order to recreate them after the fact.

### Example Current Output
```
 sensuctl silenced create --interactive
? Namespace: default
? Subscription: 
? Check: keepalive
? Begin time: now
? Expiry in Seconds: 3600
? Expire on Resolve: No
? Reason: Testing
Created

 sensuctl silenced list                
     Name       Subscription     Check            Begin          Expire   ExpireOnResolve   Creator   Reason    Namespace  
 ───────────── ────────────── ─────────── ───────────────────── ──────── ───────────────── ───────── ───────── ─────────── 
  *:keepalive                  keepalive   01 Nov 19 11:28 EDT   59m55s   false             admin     Testing   default    

 sensuctl silenced create --interactive
? Namespace: default
? Subscription: 
? Check: keepalive
? Begin time: now
? Expiry in Seconds: 4000
? Expire on Resolve: No
? Reason: Testing 2
Error: resource already exists
```

**Comment by roganartu** [comment]
protip: don't accidentally hit `enter` in the issue title input before writing out your issue :man_facepalming:

**Comment by roganartu** [comment]
The above PR (#3376) removes the dependence on `Silenced.Name` for applying silences to events, which afaict is the only reason this isn't already possible. Multiple silences can be applied to events (and there are existing tests for it), so the specific limitation preventing this from working is the way the name is automatically constructed from the subscription and check.

Thinking about it a little, would the following approach to this be acceptable?

1. Add option for `name` to sensuctl, to allow users to optionally specify a name for silences created
2. Keep the logic that builds the name for new silences, but gate it behind the condition that a name hasn't already been provided
3. If the built name already exists, append a 1, 2, 3 etc and try again until a non-clashing name is found

There may also be assumptions about uniqueness of silence names in other places (like the UI) that I'm not aware of which would also need to be addressed.

**Comment by majormoses** [comment]
this should be a 1.x parity issue and not a standard feature request as this was always the case in previous implementations.

**Comment by nikkixdev** [comment]
Requires a spike to decide if users should optionally be able to name silences or should the names be automatically generated by specific field in the silence?
