### ISSUE TITLE
Implement the Sensu 1.0 Extensions API as a gRPC API

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#338]
We won't be reimplementing all of [Sensu::Extension::Base](https://github.com/sensu/sensu-extension/blob/v1.5.0/lib/sensu/extension.rb), but I'd propose the following gRPC service definition:

```
service SensuExtension {
  rpc Name(google.protobuf.Empty) returns (NameResponse)
  rpc NameAlias(google.protobuf.Empty) returns (NameResponse)
  rpc Definition(google.protobuf.Empty) returns (DefinitionResponse)
  rpc Run(RunRequest) returns (RunResponse)
}

message NameResponse {
  string name = 1;
}

message DefinitionResponse {
  string type = 1;
  string name = 2;
}

message RunRequest {
  Event event = 1;
}

message RunResponse {
  Event event = 1;
}
```

This doesn't take into consideration backward compatibility. I think that in Sensu 1.0, we are passing "Check"s which are the whole check request/response in a single hash. People are going to expect their existing Ruby extensions to work, which means we may want to have a backward compatible API, e.g.

```
message RunRequest {
  Event event = 1;
  Sensu1Check = 2; // or something...
}
```

Where a Sensu1Check is a compacted message. We'll need a way to merge a Sensu1Check and an Event. So I would say that if we decide to do a backward compatible API, we do it carefully and provide a mechanism for mapping the Sensu1Check onto the existing event, overwriting the 2.0 Event with all values in the Sensu1Check.

**Comment by echlebek** [comment]
We ended up going with the service definition spec'd in the extensions proposal: https://github.com/sensu/sensu-go/pull/1191. However, that doesn't address one of the requirements that this issue captures: v1 compatibility.

We should come up with a strategy for dealing with the need to write v1 CheckRequests.

cc @grepory

**Comment by echlebek** [comment]
Would it be sufficient to write the Ruby extension service in such a way that it would translate 2.x data structures into 1.x data structures?

**Comment by echlebek** [comment]
Kicking this back to "next" until we can determine the above question. :)

**Comment by grepory** [comment]
A ticket exists for 2.x -> 1.x translation within the grpc service. Closing.
