### ISSUE TITLE
[Feature Request] Make silence details available in event filters

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3380]
Make details for silences that have been applied to an event accessible in filter functions.

## Feature Suggestion
#3376 removes the dependence on names of silence entries for applying silences to events, and as such makes it so that the silence name available under `event.check.silenced` field is no longer an accurate description of the silence itself, making the list in this field no more useful than the existing `event.is_silenced` boolean filter available.

Additionally, silences support labels which would be useful to be able to access in filters in order to create more intelligent silencing rules.

## Possible Implementation
Options for implementing this I can think of:

#### Extend `event.check.silenced` to include full silence instead of just name

I don't think this is the correct approach, as it changes an existing data structure and so would be a breaking change

#### Add silence information as event labels

This would work and wouldn't be a breaking change, but it is not very clean and wouldn't handle multiple silences very well. I would think the best way to do this would be to structure the label keys something like `<subscription_name>__<subscription_label_key>`.

The benefit of this approach is the silence data will also be available in handlers, not just filters.

#### Expose matched silences directly to filters

I think this is probably the way to implement this, with the downside of not having detailed silence information in handlers (but I think it's likely less necessary there).

There is already precedent for this in the event synthesization process, where actual and derived attributes are added to the `event` object that is available to filter functions (ie: https://docs.sensu.io/sensu-go/5.15/reference/filters/#event-attributes-available-to-filters).

Exposing detailed silence data under `events.silences` for each matched silence should work well, and is not a breaking change as it is a new property.

## Context
More powerful silencing capabilities.

Consider the following scenario:
- You have a check that runs on all monitored hosts
- A change is rolled out to a subset of those hosts that doesn't align with a specific subscription
- The change causes the check to start failing on those hosts with a specific pattern appearing in the check output (eg a stack trace)

This proposal would allow the following approach to silencing noisy alerts without affecting alerts from the hosts that weren't subject to the bad change:
1) Create a silence with a wildcard subscription and `Silence.Check` set to the affected check name, with a label containing the pattern expected to be present in the output
2) Have a filter that looks for that label in any silences that matched the event, and only suppresses alerts if their output matches the given pattern.

**Comment by raags** [comment]
Another use case is to silence group and silence alerts with arbitrary tags. For e.g. silence alerts for a specific team or project. Right now the entity_name and subscription attributes for a silence are too restrictive.
