### ISSUE TITLE
Allow sensu-agent to optionally use unix domain socket instead of tcp socket for events api

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3394]
currently tcp socket has limited permission granularity. You can bind it to listen for connections from localhost only, which works great for container sidecars, but on multi-user systems this may not be granular enough to prevent bogus events from being generated by inproperly configured applications run by j-random user on the system.

A unix domain socket would allow for filesystem user,group permissions to be used to give admins the ability to limit agent events api access to specific local applications and/or users for agents run on multi-user systems.  

## Feature Suggestion
New configuration option to support optional API unix domain socket.

This would be an additional configuration option, that could be enabled side-by-side with the http API  host/port 

## Possible Implementation
Strawman:
`--api-unix-socket  /path/to/socket`

By default the unix-socket would be disabled, and would only be enabled if configured via the setting.

## Context
This should make it possible to use sensu agent events api for lightweight APM for applications running on multi-user systems without monitoring disruption.

**Comment by echlebek** [comment]
We can probably transparently support this feature with the existing flag.

**Comment by calebhailey** [comment]
Neat idea!
