### ISSUE TITLE
Update CONTRIBUTING.md with Go Version and Go module

### ISSUE THREAD

**Issue by arnaldomf** [sensu/sensu-go#3396]
## Feature Suggestion
The `CONTRIBUTING.md` file doesn't reflect the `README.md` file in terms of Go's version and Git cloning instruction.

## Context
Sensu Go [README.md](https://github.com/sensu/sensu-go/blob/master/README.md#building-from-source) file tells the contributor to clone the repository outside of $GOPATH and to use Go version 1.13.1. In the other hand, the CONTRIBUTING.md file tells to [clone into $GOPATH](https://github.com/sensu/sensu-go/blob/master/CONTRIBUTING.md#contributing) and to [use Go version 1.10.X](https://github.com/sensu/sensu-go/blob/master/CONTRIBUTING.md#development)

**Comment by palourde** [comment]
Thanks @arnaldomf for reporting this issue. I actually opened a new patch so the `CONTRIBUTING.md` guide refers to the `README.md` instructions instead, so we don't have duplicated information, which would be easier to keep up-to-date.

**Comment by arnaldomf** [comment]
Hi @palourde ! Great, looks better this way :)
