### ISSUE TITLE
Extensions registry and process manager

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#340]
In order to use extensions, we need to have them running and listening for requests. This means we need to be able to spawn external processes that are extensions and then communicate with them over the network.

Extensions should always listen on 127.0.0.1 and we should tell them what port to listen on. We can then create a gRPC client to the external process for routing `run` requests to the extension.

It's important that the CLI for these be well-specified as people will maybe want to write their own extensions in their lingua franca.

Would it be cool if this used the `AssetManager` to deal with installing extensions in sensu-backend?

**Comment by echlebek** [comment]
We decided to go in another direction with this. Sensu 2.x will not take on the role of process supervisor, and only register URLs to gRPC extensions.

While we should make every effort to convince users that their extensions should only run on localhost, there is actually no technical requirement for this, so the design has been done around URLs as extension points.

Closed via #1113
