### ISSUE TITLE
agent cannot connect to backend - EOF error - misleading logs from systemd

### ISSUE THREAD

**Issue by gtarnaras** [sensu/sensu-go#3400]
My agents cannot connect to the backend because the agent port it is already used. However, sensu does not raise an error that indicates what is actually happening and the logs are misleading. 

## Expected Behavior
When an agent starts with a correct configuration file, using the cli or systemd, it should be able to connect to the cluster. If something goes wrong we should be able to see an error using e.g. journactl

## Current Behavior
The agents cannot connect to the backend and i am getting an EOF error. This happened because the agent port 8081 is already used in the backend and sensu fails to bind this port. However, i was not able to see this since the error thrown from sensu was not clear. The backend was started using systemd but the error was clear only when i started sensu-backend using the cli.

## Steps to Reproduce (for bugs)
1. Create a 3 node cluster using embedded etcd
2. Have another service running on the same port
3. Wait until the cluster is UP (i am currently waiting 5 mins)
4. Login to Sensu's built in dashboard
5. Start the agent on the node you want to monitor

## Context

Systemd logs

`{"component":"agent","level":"info","msg":"compacting api queue","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"finished api queue compaction","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"starting api on address: <x.x.x.x>:3031","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"starting UDP listener on address: <x.x.x.x>:3030","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"starting TCP listener on address: <x.x.x.x>:3030","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"using password auth","time":"2019-11-18T17:41:59Z"}
{"cache":"/var/cache/sensu/sensu-agent","component":"asset-manager","level":"debug","msg":"initializing cache directory","time":"2019-11-18T17:41:59Z"}
{"cache":"/var/cache/sensu/sensu-agent","component":"asset-manager","level":"debug","msg":"done initializing cache directory","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:41:59Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:41:59Z"}
{"component":"agent","error":"EOF","level":"error","msg":"reconnection attempt failed","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:41:59Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:41:59Z"}
{"component":"agent","error":"EOF","level":"error","msg":"reconnection attempt failed","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:41:59Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:41:59Z"}
{"component":"agent","error":"EOF","level":"error","msg":"reconnection attempt failed","time":"2019-11-18T17:41:59Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:42:01Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:42:01Z"}
{"component":"agent","error":"EOF","level":"error","msg":"reconnection attempt failed","time":"2019-11-18T17:42:01Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:42:11Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:42:11Z"}
{"component":"agent","error":"EOF","level":"error","msg":"reconnection attempt failed","time":"2019-11-18T17:42:11Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:42:21Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:42:21Z"}
{"component":"agent","error":"EOF","level":"error","msg":"reconnection attempt failed","time":"2019-11-18T17:42:21Z"}
{"component":"agent","level":"info","msg":"connecting to backend URL "wss://<x.x.x.x>:8081"","time":"2019-11-18T17:42:31Z"}
{"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-11-18T17:42:31Z"}`

Starting the sensu-backend service from the cli clearlyu shows what is happening and  i am getting a "bind: Address already in use" error. The same should be logged in systemd.

## Your Environment
The OS is RHEL7.7
I am hosting the packages on a custom yum repo. The following packages are installed
sensu-go-agent.x86_64 5.14.2-7022
sensu-go-backend.x86_64 5.14.2-7022
sensu-go-cli.x86_64 5.14.2-7022

**Comment by palourde** [comment]
@gtarnaras Hi,

Unfortunately I wasn't able to reproduce this issue. It appears the same error message is also reported to systemd:

```
sudo journalctl -u sensu-backend -f
[...]
Nov 19 16:27:32 backend-0 sensu-backend[9319]: {"component":"agentd","error":"listen tcp 0.0.0.0:8081: bind: address already in use","level":"error","msg":"failed to start http/https server","time":"2019-11-19T16:27:32Z"}
```

You might want to increase the log level to reduce the number of log entries sent or filter the log entries when using journalctl (e.g. `sudo journalctl -u sensu-backend | grep error`).

Thanks

**Comment by gtarnaras** [comment]
@palourde thank you so much for checking. I will try the log level and see if it makes any difference.

**Comment by palourde** [comment]
Awesome, let us know how it goes!
