### ISSUE TITLE
version.Semver() no longer contains SHA

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#3409]
## Expected Behavior
SHA is a postfix in the /version API.
```
$ curl -s https://127.0.0.1:8080/version
{"etcd":{"etcdserver":"3.3.17","etcdcluster":"3.0.0"},"sensu_backend":"5.14.2#19d57bb"}
```

## Current Behavior
SHA is not a postfix in the /version API.
```
$ curl -s https://127.0.0.1:8080/version
{"etcd":{"etcdserver":"3.3.17","etcdcluster":"3.0.0"},"sensu_backend":"5.15.0"}
```

## Possible Solution
Revisit some refactoring to the version package.

## Context
Honestly, I'm not sure which version we like better.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.15.0
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16

**Comment by amdprophet** [comment]
We may want to put the sha in a separate field to prevent the need for tools to strip the version info they're looking for.

**Comment by nikkixdev** [comment]
@amdprophet it looks like the version package refactoring also removed the SHA associated with all tools that use `version.Semver()`. This includes the [tessen cluster version](https://github.com/sensu/sensu-go/blob/9b3c09c5071f1d35b8cc6a3711bfcba5081a446b/backend/tessend/tessend.go#L517) and the [Entity.SensuAgentVersion](https://github.com/sensu/sensu-go/blob/80c129750f907303074588a8b2d1b68420f2afd9/agent/entity.go#L23).

Pre-refactor has git sha:
https://github.com/sensu/sensu-go/blob/9b3c09c5071f1d35b8cc6a3711bfcba5081a446b/version/version.go#L54-L66

Post-refactor removes git sha:
https://github.com/sensu/sensu-go/blob/d0d951875fbafd62ba4da4cb4571b06af2976699/version/version.go#L25-L37

**Comment by portertech** [comment]
We are currently confident in the accuracy of our release tags and we can still fetch the SHA from `sensu-backend version`.
