### ISSUE TITLE
Redact information in handlers

### ISSUE THREAD

**Issue by wakemaster39** [sensu/sensu-go#3410]
For client side information, it is possible to redact the values so they don't show up in the UI. For server side values I do not find a method to do this. 

## Feature Suggestion
Provide a mechanism to redact secrets in the UI that are known to the backend that a user might not want easily visible. 

## Context
Take the influxdb handler as an example, for security reasons they suggest putting the username/password as env vars. While I know this isn't overly secure itself, if someone gets on the box and can see those env vars I probably have already lost at that point.

What i might have is less privileges users who I want to give access to via the sensu ui, but might not want to share the values stored in those env vars. Visiting the handler page, annotations, labels, env vars are all in clear text and I can't find any documented way of hiding those values.

**Comment by portertech** [comment]
We are currently working on secrets management, which will remove sensitive information from the handler resource and web ui views. Not going to attempt string redaction. Thank you for the issue, demonstrates how important proper secrets management is :+1:
