### ISSUE TITLE
Unable to add sensuctl command from Bonsai

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3421]
## Expected Behavior

I'd expect examples from Sensu Go documentation to work when adding `sensuctl command install` using bonsai asset

## Current Behavior

```
[root@sensu-backend ~]# sensuctl command install sensu-email-handler sensu/sensu-email-handler:0.2.0
fetching bonsai asset: sensu/sensu-email-handler:0.2.0
Error: one or more asset builds are required
```

## Context

I am attempting to automate the management of `sensuctl command` and unable to add a command from Bonsai.

CC @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensuctl version 5.15.0, build b1bf6a92a51a6423540ecba306f4663dd492650c, built 2019-11-23T09:23:23Z
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by portertech** [comment]
`sensuctl command install` is for installing sensuctl command plugin assets, you wouldn't use it for `sensu/sensu-email-handler:0.2.0`. There is logic to prevent users from installing non command plugin assets (using labels), however, it seems this error was encountered before that.

**Comment by treydock** [comment]
I was just going by what was in Sensu Go docs, so maybe this is a documentation issue also?

https://docs.sensu.io/sensu-go/5.15/sensuctl/reference/#extend-sensuctl-with-commands

**Comment by treydock** [comment]
@portertech I am testing CI builds after I saw #3429 get merged and now I get this:

```
[root@sensu-backend ~]# sensuctl command install sensu-email-handler sensu/sensu-email-handler:0.2.0
fetching bonsai asset: sensu/sensu-email-handler:0.2.0
Error: namespace cannot be empty
```

Passing `--namespace` has no effect.

If this Bonsai asset is the wrong one to use then is there one I can test with?

**Comment by portertech** [comment]
@amdprophet can you please provide @treydock with a working asset for testing?

**Comment by amdprophet** [comment]
@treydock there aren't currently any sensuctl command assets available on Bonsai that I'm aware of. You can try testing the test asset I created using the `--url` installation method with the url & checksum from the build listed in https://gist.github.com/amdprophet/43790e007e949aed19131b100e1576af.

**Comment by treydock** [comment]
Thanks, that test case worked for me.
