### ISSUE TITLE
sensuctl dump of EtcdReplicator does not include "insecure" property

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3422]
## Expected Behavior

I'd expect all properties for EtcdReplicator to be present in `sensuctl dump`.

## Current Behavior

Currently the `insecure` property is not included in dump

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat etcdreplicator.json 
{
  "api_version": "federation/v1",
  "type": "EtcdReplicator",
  "metadata": {
    "name": "role_replicator"
  },
  "spec": {
    "ca_cert": "/path/to/ssl/trusted-certificate-authorities.pem",
    "cert": "/path/to/ssl/cert.pem",
    "key": "/path/to/ssl/key.pem",
    "insecure": false,
    "url": "http://127.0.0.1:3379",
    "api_version": "core/v2",
    "resource": "Role",
    "replication_interval_seconds": 30
  }
}
[root@sensu-backend ~]# sensuctl create -f etcdreplicator.json 
[root@sensu-backend ~]# sensuctl dump federation/v1.EtcdReplicator --format json --all-namespaces
type: EtcdReplicator
api_version: federation/v1
metadata:
  name: role_replicator
spec:
  api_version: core/v2
  ca_cert: /path/to/ssl/trusted-certificate-authorities.pem
  cert: /path/to/ssl/cert.pem
  key: /path/to/ssl/key.pem
  namespace: ""
  replication_interval_seconds: 30
  resource: Role
  url: http://127.0.0.1:3379
```

## Context

I am trying to automate new EtcdReplicator resource with Puppet and rely on some way to set values and then query all those values and right now not being able to query `insecure` makes it essentially a value that can't be managed.

CC @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensuctl version 5.15.0, build b1bf6a92a51a6423540ecba306f4663dd492650c, built 2019-11-23T09:23:23Z
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment]
I verified that setting `insecure` to `true` does produce output. The dump only omits `insecure` if the value is `false`.

**Comment by ccressent** [comment]
Hi @treydock,

Thanks for reporting this; this is probably due to the `insecure` field being tagged as `omitempty` in the `EtcdReplicator` struct. I'll check with the team why that's the case and will fix accordingly.

**Comment by portertech** [comment]
We should be explicit, let's dump with the bool value even if its the default (false).
