### ISSUE TITLE
Add metrics emitter to sensu-backend

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#343]
We want to be able to emit metrics from sensu-backend.

Create a `Daemon` that regularly emits metric Events to WizardBus for sensu-backend.

This is going to require finally specifying the [Metrics](https://github.com/sensu/sensu-go/blob/master/types/metrics.go) type for Sensu 2.0.

We should, as part of this, write a simple handler that emits these metrics to Sensu 2.0.

This would be very useful for clusters we stand up with the tooling from #342.

**Comment by echlebek** [comment]
@grepory if this is still an issue, can you flesh it out a bit?

**Comment by grepory** [comment]
This can be closed in favor of working on tessen reporting for sensu 2.x in the future. Not that we don't need to instrument Sensu 2.x, but that doesn't have to be done en masse or driven by a single ticket.
