### ISSUE TITLE
Add "distribution" to Tessen data

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3431]
## Feature Suggestion
Add "distribution" to Tessen data to identify if a cluster is "oss" or "commercial".

## Possible Implementation
Add a field to https://github.com/sensu/sensu-go/blob/7bf0c3c15540f0373d22068848731ff19297fafb/backend/tessend/data.go#L21
Set the value to "oss" in sensu-go, override with "commercial" in sensu-enterprise-go.

**Comment by portertech** [comment]
Or use a field name like "flavour" 🇨🇦

**Comment by nikkixdev** [comment]
When someone writes "flavour."

![giphy](https://user-images.githubusercontent.com/10634078/69680168-ee58f900-105e-11ea-8b8c-0d812a092778.gif)
