### ISSUE TITLE
"error":"error initializing the store: etcdserver: mvcc: database space exceeded","level":"fatal","msg":"error executing sensu-backend","time":"2019-10-30T09:27:15Z"Unexpected Error: "500"

### ISSUE THREAD

**Issue by nandeeshb09** [sensu/sensu-go#3433]
we are getting this error and we tried below steps but it did not help.

we tried to defrag manually each etcd cluster node , but still we are getting this error.

ETCDCTL_API=3 etcdctl defrag

And before defrag it was 2.1 GB and post defrag its reduced to 2.6 MB .
--------------+------------------+---------+---------+-----------+-----------+------------+
|    ENDPOINT    |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+----------------+------------------+---------+---------+-----------+-----------+------------+
| 127.0.0.1:2379 | 7665499395959bc2 |   3.3.8 |  2.6 MB |      true |       145 |  102860083 |
+----------------+------------------+---------+---------+-----------+-----------+------------+

Please help us resolve this issue as soon as possible.

Our sensu version is 5.12
etcd image version -- latest

**Comment by hkwi** [comment]
It looks I encountered the same issue, and fixed with `etcdctl alarm disarm` as described in [etcd docs](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/maintenance.md#space-quota) .
