### ISSUE TITLE
Cluster registration does not support self-signed certificates

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3434]
## Expected Behavior
I can connect to a sensu-go cluster that is secured with a self-signed certificate, or CA that is not recognized by my operating system's chain of trust.

## Current Behavior
Connections are rejected when using self-signed certificates.

## Possible Solution
Two possible solutions:
1) Add a CA certificate field to the cluster resource.
2) Consult the backend's `--trusted-ca-file` flag.

## Steps to Reproduce (for bugs)
Set up a remote cluster with TLS enabled, and observe that it is impossible to connect to the remote cluster.

## Context
Discovered by @cwjohnston while testing.

**Comment by cwjohnston** [comment]
Adding my CA cert to the Centos system trust store and restarting sensu-backend resolved the `x509: certificate signed by unknown authority` error.

**Comment by portertech** [comment]
We feel that option 1 ("Add a CA certificate field to the cluster resource.") is the better approach.

- Adding a field to the cluster resource type
- Use the CA certificate field (when set) when creating a TLS connection for graphql to the cluster in question
