### ISSUE TITLE
Allow sensuctl api-key to query key for specific user

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#3435]
I can query on a per key basis with the info subcommand, but no query exists for finding a key by the user name.  If I want that, I have to do something similar to the following:

```sensuctl api-key list --format json | jq -r '.[] | select(.username == "admin") | .metadata.name'```

**Comment by palourde** [comment]
@nixwiz What about a simple grep?

```
$ sensuctl api-key list|grep admin
```

There's also a field selector just for that in our commercial distribution:

```
$ sensuctl api-key list --field-selector "api_key.username == 'admin'"
```

WDYT?

**Comment by nixwiz** [comment]
The grep is no better than my example using jq, if I'm looking at doing this in a script.

The second alternative doesn't work.
```
$ sensuctl api-key list --field-selector "api_key.username == 'admin'"
Error: could not parse the requirements: unexpected token 'invalid rune: "'"': expected an identifier or literal value

$ sensuctl version
sensuctl version 5.18.0, build 670381e539b7af2ee9dff3863249950d71db7b53, built 2020-02-25T19:11:28Z

$ rpm -qi sensu-go-cli
Name        : sensu-go-cli
Version     : 5.18.0
Release     : 9470
Architecture: x86_64
Install Date: Wed 26 Feb 2020 07:09:35 PM UTC
Group       : Applications/Internet
Size        : 26251457
License     : Proprietary
Signature   : (none)
Source RPM  : sensu-go-cli-5.18.0-9470.src.rpm
Build Date  : Tue 25 Feb 2020 07:12:24 PM UTC
Build Host  : 5e657135943f
Relocations : /usr
Vendor      : Sensu, Inc.
URL         : https://sensu.io
Summary     : Sensu Go CLI tools
Description :
Sensu Go CLI tools
```

**Comment by palourde** [comment]
@nixwiz Make sure to upgrade sensu-backend to 5.18, we just released a bugfix so single quotes can also be used to delimit strings in selectors.

**Comment by palourde** [comment]
For context, API keys are not stored by username because each user can have multiple API keys.

**Comment by nixwiz** [comment]
The backend upgrade did fix that and that more or less fixes my use case.
