### ISSUE TITLE
"sensu-backend init" subcommand missing from CI builds

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3439]
## Expected Behavior

I'd expect #3414 change to be showing up in CI builds, `sensu-backend init`.

## Current Behavior

```
[root@sensu-backend ~]# sensu-backend init
Error: unknown command "init" for "sensu-backend"
Run 'sensu-backend --help' for usage.
{"component":"sensu-enterprise","error":"unknown command \"init\" for \"sensu-backend\"","level":"fatal","msg":"error executing sensu-backend","time":"2019-11-28T03:38:49Z"}
```

## Context

I wanted to make sure the Puppet module for Sensu was prepared for `sensu-backend init` change but unable to test.

CC @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-backend version 5.15.0, build 326688213c750c4210275b43a2670bc6ee9eb47b, built 2019-11-28T02:59:58Z`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment]
init is missing from help output too:

```
[root@sensu-backend ~]# sensu-backend -h
sensu backend

Usage:
  sensu-backend [command]

Available Commands:
  help        Help about any command
  start       start the sensu backend
  version     Show the sensu-backend version information

Flags:
  -h, --help   help for sensu-backend

Use "sensu-backend [command] --help" for more information about a command.
```

**Comment by echlebek** [comment]
The CI builds are produced from the enterprise product. I've vendored the OSS codebase in there now, so you should be all set.

**Comment by treydock** [comment]
@echlebek Will this be available now or on next push to master? I am still not seeing `init`:

```
[root@sensu-backend ~]# sensu-backend init
Error: unknown command "init" for "sensu-backend"
Run 'sensu-backend --help' for usage.
{"component":"sensu-enterprise","error":"unknown command \"init\" for \"sensu-backend\"","level":"fatal","msg":"error executing sensu-backend","time":"2019-11-30T15:49:59Z"}
[root@sensu-backend ~]# sensu-backend version
sensu-backend version 5.15.0, build 0436b97f7ee6b1a7aa5a23bbdd7b5243239be137, built 2019-11-30T01:36:14Z
```

**Comment by echlebek** [comment]
@treydock sorry about that, there was an additional PR that needed to be merged in the enterprise repo. You should be good to go now.
