### ISSUE TITLE
Unable to create EtcdReplicator using API

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3444]
## Expected Behavior

I'd expect API to be able to create EtcdReplicator.

## Current Behavior

`{"message":"resource name does not match path (rolebinding_replicator != )","code":0}`

## Steps to Reproduce (for bugs)

```
[root@sensu_backend /]# curl -k -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" -d '{"spec":
{"ca_cert":"/path/to/ssl/trusted-certificate-authorities2.pem",
"cert":"/path/to/ssl/cert2.pem",
"key":"/path/to/ssl/key2.pem",
"insecure":false,
"url":"http://127.0.0.1:3379",
"api_version":"core/v2",
"resource":"RoleBinding",
"replication_interval_seconds":60},
"metadata":{"name":"rolebinding_replicator"},
"api_version":"federation/v1","type":"EtcdReplicator"
}' https://sensu_backend:8080/api/enterprise/federation/v1/etcd-replicators
```

## Context

I am trying to use the API to manage Puppet resources and unable to add EtcdReplicators.

CC @ghoneycutt

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-backend version 5.15.0, build 13884593ee08a7f25d7f66a8b71da61c529de014, built 2019-11-19T20:18:33Z` Also CI builds from 11/30/19
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by echlebek** [comment]
Please use
```
https://sensu_backend:8080/api/enterprise/federation/v1/etcd-replicators/rolebinding_replicator
```
as the URL. As with most of our APIs, it is more natural to use PUT, but the server will accept POST as a verb as well.

**Comment by echlebek** [comment]
Apologies, this appears to be a bug.

**Comment by palourde** [comment]
This is actually caused by the exact same problem as https://github.com/sensu/sensu-go/issues/3442. We successfully confirmed the patch we have also fixes this problem.
