### ISSUE TITLE
How to query state of 'sensu-backend init' in context of automation

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3448]
## Feature Suggestion

It would be handy if there was a way to query the state of `sensu-backend init`.

## Possible Implementation

Maybe something like `sensu-backend init --query` and return exit code based on whether the backend has been initialized.

## Context

I am working on integrating the new `sensu-backend init` into the Sensu supported sensu-puppet module and it seems like I can run `sensu-backend init` many times and get no feed back as to whether the operation was already performed. Puppet operates on state and needs to know if a command should be executed or not and if something like `sensu-backend init` has no way to query state then I'd have to resort to really ugly hacks like touching a file after running init which is a bad practice and also won't work for people who have already installed Sensu Go before the change coming in 5.16 and also using the Puppet module.

If there already is a designed way to query the initialized state maybe no change is necessary but I'm not quite sure the best way to find out if `sensu-backend init` needs to be run.

CC @ghoneycutt

**Comment by echlebek** [comment]
Would it be enough to write a nonzero status if init has already been performed?

**Comment by treydock** [comment]
That could work. I think the exit code would have to be something other than 1 if 1 is what's used upon failure.

I presume running init after the first time doesn't actually change anything?

**Comment by treydock** [comment]
Either using exit code of 3 or some tricks in Puppet with checking if password works for configured password or bootstrap password. Closing issue
