### ISSUE TITLE
Modular and extendible agent configuration

### ISSUE THREAD

**Issue by bovy89** [sensu/sensu-go#3452]
Hi, we are facing an issue with puppet configuration during the migration from sensuclassic to sensugo (see https://github.com/sensu/sensu-puppet/issues/1183 for more details).

The issue is the following: due to the change from json to yaml (and the lack of hash merge), we can not dynamically add things (like subscription).

To obtain the same flexibility of sensuclassic I'm going to propose the following changes to agent configuration management.

Option 1:

Let the user exentend agent.yml, moving subscriptions, labels, annotations, etc. to external files (e.g. https://docs.gitlab.com/ee/ci/yaml/#include)

```
# agent.yml
<conf_here>
include subscriptions.yml
include labels.yml
include annotations.yml


# subscriptions.yml
subscriptions: 
  - postgres


# labels.yml
labels:
  ssh_protocol: "2.0"
  ssh_version: "OpenSSH_7.4" 


# annotations.yml
annotations:
  myannotationkey: "myannotationvalue"
```

NOTE: the include keyword is not standard

In this way we can mimic what we used to do with sensuclassic puppet module

Example. 

In the main sensu puppet module:

```
concat { '/tmp/subscriptions.yml':
    owner => 'root',
    group => 'root',
    mode  => '0644'
}

concat::fragment { 'subs_header':
    target  => '/tmp/subscriptions.yml',
    content => "subscriptions:\n",
    order   => '01',
}

define gen_subscription(
    $sub_name = $title,
){
    concat::fragment { $sub_name:
        target  => '/tmp/subscriptions.yml',
        content => "  - ${sub_name}\n",
        order   => '02',
    }
}
```

In our modules:

```
gen_subscription {'postgres': }
```

Option 2:

The same as Option 1, but more "docker-compose style": agent process can read more than one config file (https://docs.docker.com/compose/extends/#multiple-compose-files). The merge part will be done by the agent process.

<agent> -c agent.yml -c subscriptions.yml -c annotations.yml -c labels.yml

Option 3:

Let the user to configure agent using json (agent process will merge all json hash, sensuclassic style). This way, we can reuse the same logic (and puppet code) of sensuclassic.

**Comment by bodgit** [comment]
Something that allows the configuration to be split up into multiple files and merged like it was possible in core/classic is very much needed. This unfortunately looks like a blocker for us to migrate as it's unusable with our Puppet estate without massively compromising the flexibility we currently have.

**Comment by afalabel** [comment]
This would be very useful also for us.
