### ISSUE TITLE
reverse proxying sensu dashboard with nginx

### ISSUE THREAD

**Issue by franz82** [sensu/sensu-go#3453]
Hi all,
this config:

     location / {
        proxy_pass  http://127.0.0.1:3000/;
    }

reverse proxying a sensu dashboard binded on localhost interface.
Any working configs in order to switch from location **/** to location **/test** ?
Thanks
-f

**Comment by toozej** [comment]
if I'm understanding your question correctly, you're 95% of the way there yourself. You can use this:

```
 location /test {
    proxy_pass  http://127.0.0.1:3000/;
}
```

https://nginx.org/en/docs/http/ngx_http_core_module.html#location has more information about the Location directive if you want to learn more.

**Comment by echlebek** [comment]
Hi, please file questions like this to https://discourse.sensu.io, as we'd like to constrain the sensu-go issue tracker to issues with sensu-go only. Thanks!
