### ISSUE TITLE
TLS client auth, handshake error 402

### ISSUE THREAD

**Issue by franz82** [sensu/sensu-go#3455]
I'd like to secure sensu agent to server communications like described [here](https://docs.sensu.io/sensu-go/5.15/guides/securing-sensu/#securing-sensu-agent-to-server-communication)

## Expected Behavior
sensu agents able to talk with sensu backend through a TLS authenticated connection

## Current Behavior
agent is rejected with error: `handshake failed with status 402`

## Possible Solution
I suppose something is missing in my config

## Steps to Reproduce (for bugs)
1. https://docs.sensu.io/sensu-go/5.15/guides/securing-sensu/#securing-sensu-agent-to-server-communication
2. https://docs.sensu.io/sensu-go/5.15/guides/securing-sensu/#sensu-agent-tls-authentication

## Context
from `backend.yml`:
> agent-auth-cert-file: "/etc/ssl/sensu/backend.crt"
agent-auth-key-file: "/etc/ssl/sensu/backend.key"
agent-auth-trusted-ca-file: "/etc/ssl/sensu/ca.pem"

from `agent.yml`:
> backend-url:
   "wss://xxx:8081"
cert-file: "/etc/ssl/sensu/v2clt.crt"
key-file: "/etc/ssl/sensu/v2clt.key"
trusted-ca-file: "/etc/ssl/sensu/ca.pem"

backend certificate CN match backend DNS name (FQDN replaced with xxx)

backend and agent TLS certs generated with [easy-rsa](https://github.com/OpenVPN/easy-rsa) CA

agent logs:

> Dec  7 15:46:56 v2 sensu-agent[6891]: {"component":"agent","level":"info","msg":"connecting to backend URL \"wss://xxx:8081\"","time":"2019-12-07T15:46:56+01:00"}
Dec  7 15:46:56 v2 sensu-agent[6891]: {"component":"agent","header":"Accept: application/octet-stream","level":"debug","msg":"setting header","time":"2019-12-07T15:46:56+01:00"}
Dec  7 15:46:56 v2 sensu-agent[6891]: {"component":"agent","error":"handshake failed with status 402","level":"error","msg":"reconnection attempt failed","time":"2019-12-07T15:46:56+01:00"}

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): both sensu-backend and sensu-agent version 5.15.0, build 13884593ee08a7f25d7f66a8b71da61c529de014, built 2019-11-19T20:18:33Z. sensu-backend and sensu-agent on the same machine
* Installation method (packages, binaries, docker etc.): deb packages through APT
* Operating System and version (e.g. Ubuntu 14.04): Debian bullseye/sid, kernel 5.3.0-2-amd64

**Comment by echlebek** [comment]
Hi, please head over to our discourse forum for questions (discourse.sensu.io) or file an issue to https://github.com/sensu/sensu-docs if you believe there is an error in the documentation.
