### ISSUE TITLE
Repeated POST call for the same filter returns 403

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-go#3459]
- Successful call to POST /filters returns a 201 (https://docs.sensu.io/sensu-go/5.15/api/filters/#filters-post).
- Sending another POST for the same filter returns a 403.

Eric said that the 403 should only happen if I don't have permission to create filters, so it could be a bug. [Slack conversation](https://sensu.slack.com/archives/C60EEQFH8/p1575486704381700)

## Expected Behavior
I'm not sure what the correct behavior would be (in terms of the correct code for sending a repeated POST for the same filter).

## Current Behavior
- Successful call to POST /filters returns a 201 (https://docs.sensu.io/sensu-go/5.15/api/filters/#filters-post).
- Sending another POST for the same filter returns a 403.

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)

- Successful call to POST /filters returns a 201 (https://docs.sensu.io/sensu-go/5.15/api/filters/#filters-post).
- Sending another POST for the same filter returns a 403.

## Context
I noticed that the response codes we list in the docs often don't match up with the response codes I get when I actually call the endpoints.

## Your Environment

- sensu-backend configured on Mac to run development environment (Nikki helped me set it up).
- Sending API calls via Postman app.

**Comment by echlebek** [comment]
The reason the HTTP server returns an error is that the resource already exists. At the time, my thinking was that 403 was the wrong status code.

However, on review I don't see a better option than returning 403.

I'm not thrilled with how our API behaves here. In fact I don't think we should ever return an error if a resource already exists, nor should we allow POST to a non-list endpoint.

However, at this point it is what it is, and I don't think we can really change it.

If you want to try the request multiple times, use PUT, and the resource will be overwritten and a 2xx response will be returned.
