### ISSUE TITLE
cluster health sometimes omits unresponsive backends

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#3467]
##  Expected Behavior
When a backend is unresponsive, it should be listed with an error in `sensuctl cluster health`.
```
ubuntu@backend-2:~$ sensuctl cluster health
=== Etcd Cluster ID: 8762f28783cb71fc
         ID            Name                Error             Healthy  
 ────────────────── ─────────── ─────────────────────────── ───────── 
  61cf57303478138b   backend-0   context deadline exceeded   false    
  570321e744334f57   backend-1                               true     
  567e21fecea88f1b   backend-2                               true    
```

## Current Behavior
When a backend is unresponsive, it can sometimes be omitted from `sensuctl cluster health`.
```
ubuntu@backend-2:~$ sensuctl cluster health
=== Etcd Cluster ID: 8762f28783cb71fc
         ID            Name      Error   Healthy  
 ────────────────── ─────────── ─────── ───────── 
  570321e744334f57   backend-1           true     
  567e21fecea88f1b   backend-2           true  
```

## Possible Solution
There could be an edge case or race condition if the cluster is queried too soon after the backend is stopped.

## Steps to Reproduce (for bugs)
1. In a 3 node cluster, stop 1 backend.
2. Run `sensuctl cluster health` on a different backend immediately, observe the missing backend.
3. Run `sensuctl cluster health` a few more times and the backend should appear with the appropriate error.

## Context
Cluster health should list all members regardless if they are alive or not.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): RC1 `sensuctl version 5.16.0, build d0a4a1d734021121713cba3e2682e07eaa1fbd2b, built 2019-12-12T22:34:39Z`
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/3469
