### ISSUE TITLE
Validate Role and ClusterRole verbs and resources

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3471]
TL;DR - was on a call with a customer troubleshooting the reason their role didn't work and it boiled down to this:

**Their role**
```
type: ClusterRole
api_version: core/v2
metadata:
name: silencer
spec:
rules:
- resource_names: null
resources:
- silenced
verbs:
- create,update,delete
```

**Working Role***
```
type: ClusterRole
api_version: core/v2
metadata:
name: silencer
spec:
rules:
- resource_names: null
resources:
- silenced
verbs:
- create
- update
- delete
```

The request here is, if possible, add some checking around arrays used for configuring various Sensu resources. I'm not quite sure how we'd accomplish this, but checking to see that if an array is being used, the array should only have one value, not a series of comma-delimited values.

**Comment by echlebek** [comment]
We should validate in the HTTP server that the resource contains only valid verbs.

**Comment by echlebek** [comment]
@asachs01 it is not really possible, in general, to validate any array to make sure it doesn't contain some mistake. But we can do validation on some arrays, including the `verbs` and `resources` in RBAC roles and cluster roles.

**Comment by asachs01** [comment]
@echlebek I think validating `verbs` and `resources` would be a good move in this case.
