### ISSUE TITLE
Add support for ARMv8 and 32-bit OS used by most Raspberry PIs

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3474]
## Feature Suggestion

It would be handy if the binaries provided for ARM also supported ARMv8 (Raspberry Pi 4) and 32-bit because things like Raspbian are 32-bit operating systems.

Also would be handy if there were armhf Docker images.

## Context

I wanted to experiment with Sensu Go on Raspberry Pi 4 systems and be nice not to have to build from source. Also I presume enterprise features will be missing if I build from source.

**Comment by echlebek** [comment]
I don't think there is any such thing as a 32-bit armv8 executable, though I could be wrong.

You should be able to run the 32 bit arm binaries on an rpi 4, did you try it?

**Comment by treydock** [comment]
I'm just going off research and from reading. I am getting my first Raspberry Pi 4 this week and should have something to play with this weekend.  My understanding from reading is the official OS, Raspbian, is 32-bit despite the processor being 64-bit.

According to https://sensu.io/downloads the ARM binaries are all 64-bit. I will give them a try once I have my Pi 4 running but would expect it not to work for OS compiled as 32-bit.

For Docker the arch is `armhf`, I am not sure if the other arm architectures will work.

**Comment by amdprophet** [comment]
That's a typo on the downloads page. ARMv5 - 7 are 32-bit.

**Comment by treydock** [comment]
Ah ok, in that case for Pi 4 would need ARMv8 32-bit.

**Comment by amdprophet** [comment]
Pi 4 should work with any of the ARMv5 - v7 binaries. ARMv7 should have the most optimizations for the Pi 4.

**Comment by echlebek** [comment]
I've already tried running Sensu on a Pi 4 compiled for arm7, and it works well.

**Comment by echlebek** [comment]
Feel free to re-open if you run into issues with the pi!
