### ISSUE TITLE
Error refreshing token for AD

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3479]
This came in via customer ticket. This customer is on 5.16 and is running on RHEL with AD configured. They advised:

> We raised a ticket earlier with 5.15.0 where the session kicks us out(AD authenticated User) in less then 5 min of login with the below error message (Sensu Go integrated with Active Directory)
Later today we were testing the 5.16.0 from the test repo, it also has the same behavior

```
{"component":"authentication/v2","level":"debug","msg":"running ldap search with basedn \"DC=nsroot,DC=net\" and filter \"(\u0026(objectClass=person)(sAMAccountName=ss05710))\"","time":"2019-12-13T03:59:38-05:00"}
{"component":"apid.routers","error":"could not refresh user \"ss05710\" with provider \"ad\": ldap search for user \"ss05710\" failed: LDAP Result Code 1 \"Operations Error\": 000004DC: LdapErr: DSID-0C090A4C, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839\u0000","level":"info","msg":"unexpected error while authorizing refresh token","time":"2019-12-13T03:59:39-05:00"}
{"component":"apid","duration":"180.454ms","level":"info","method":"POST","msg":"request completed","path":"/auth/token","size":22,"status":500,"time":"2019-12-13T03:59:39-05:00"}
{"component":"rbac","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2019-12-13T03:59:40-05:00","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"","resource":"namespaces","resourceName":"default","username":"citiadmin","verb":"get"}}
{"component":"rbac","level":"debug","msg":"request authorized by the binding cluster-admin","time":"2019-12-13T03:59:40-05:00","zz_request":{"apiGroup":"core","apiVersion":"v2","namespace":"default","resource":"handlers","resourceName":"","username":"citiadmin","verb":"list"}}
```
Not sure about what we can do to try and replicate. Full content of ticket is here https://secure.helpscout.net/conversation/1031455712/19322?folderId=1211658

**Comment by sureshsubramaniam** [comment]
May be when the AD integration is done without a bind account, using the user credential to bind to AD and when the token refreshes it is not able to bind with AD after the initial successful login, just thoughts

**Comment by palourde** [comment]
Issue moved to [sensu/sensu-enterprise-go #822](https://github.com/sensu/sensu-enterprise-go/issues/822) via [**ZenHub**](https://www.zenhub.com/)

**Comment by palourde** [comment]
This is an issue with a commercial functionality, transferring it to the appropriate repository.
