### ISSUE TITLE
Event Filter Sensu Go API built-in client

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3480]
Provide a built-in Sensu Go API client for Event filters, via one or more javascript functions.

## Feature Suggestion
Provide a built-in Sensu Go API client for Event filters, via one or more javascript functions.

We have a proposal for the Sensu SDK: https://docs.google.com/document/d/14X-R7KBFJMFx_gV1_0yOS4GQsJTAva-CHBu06XUkb4w/edit#heading=h.letafivq6wet

## Possible Implementation
Expose the internal API client through javascript.

## Context
All Event Filters to query the API efficiently. This could be very useful, for example: check dependency filtering (https://github.com/sensu/sensu-go/issues/3122).

**Comment by echlebek** [comment]
We now have the ability to read events within Sensu Query Expressions (SQEs)!
