### ISSUE TITLE
Unable to run sensu-backend init with Amazon Linux 2 on initial cluster

### ISSUE THREAD

**Issue by acrawly** [sensu/sensu-go#3481]
Since v5.16's introduction of `sensu-backend init`, we're unable to install Sensu Go. 

## Expected Behavior
Expect to be prompted for default admin username and password. 

## Current Behavior
Currently, we receive the following error:
```
[ec2-user@ip-10-0-0-82 ~]$ sudo sensu-backend init --interactive
{"component":"sensu-enterprise","error":"error connecting to cluster: context deadline exceeded","level":"fatal","msg":"error executing sensu-backend","time":"2019-12-18T17:44:31-07:00"}
[ec2-user@ip-10-0-0-82 ~]$ 
```

## Possible Solution
This worked fine in 5.15 and 5.14. I haven't reviewed the source code. 

## Steps to Reproduce (for bugs)
1. Launch Amazon Linux 2 Instance
2. Run `curl -s https://packagecloud.io/install/repositories/sensu/stable/script.rpm.sh | sudo bash`
3. Run `sudo yum install sensu-go-backend`
4. Run `sensu-backend init --interactive`

## Context
Launching new Sensu go deployment in AWS. 

## Your Environment
Barebones right now.

**Comment by nikkixdev** [comment]
@acrawly The sensu-backend must be running in order for `sensu-backend init` to initialize the user. Can you confirm that solves your issue?

I'll look into the docs because that requirement is not super obvious right now.

**Comment by acrawly** [comment]
@nikkixdev, it's relieving to get such a speedy response. No, that does not solve it. I've tried the following combinations:

1. Stopping the service and running the init.
2. Running the command while the service is running
3. Ensuring all etcd cluster related settings are NOT included while service is running
4. Ensuring all etcd cluster related settings are NOT included while service is stopped
5. (This is the one I filed this bug report with.) A fresh instance launch and manually installing sensu. 

Here's the commands:

```
[ec2-user@ip-10-0-0-82 ~]$ sudo service sensu-backend start
Redirecting to /bin/systemctl start sensu-backend.service
[ec2-user@ip-10-0-0-82 ~]$ sudo sensu-backend init --interactive
{"component":"sensu-enterprise","error":"error connecting to cluster: context deadline exceeded","level":"fatal","msg":"error executing sensu-backend","time":"2019-12-18T18:18:28-07:00"}
[ec2-user@ip-10-0-0-82 ~]$ 
```

**Comment by acrawly** [comment]
I'm sorry, @nikkixdev. I rushed those commands and used the wrong syntax for Amazon Linux 2 among not doing some further troubleshooting. 

Looking more closely, you're right. After ensuring the service was running correct, it did work!

That leaves me with two pieces of feedback. The first is that the service wouldn't start because `/etc/sensu/backend.yml` wasn't created. The docs should make it clear that you need to touch that path. The second is can you update the cluster configuration guide to include how to handle this new initialization command? This doesn't seem to follow semantic versioning because prior to this, we were able to specify all the etcd cluster options with our installation initially and it would configure as expected with the default Sensu username and password. With this new model, it seems we need to stand up each node individually, run `sensu-backend init`, and then add the etcd cluster configurations. It feels more complex, not simpler. 

````
-- Logs begin at Wed 2019-12-18 17:27:39 MST. --

Dec 18 18:40:42 ip-10-0-0-74.vcaantech.com systemd[1]: Starting The Sensu Backend service....

Dec 18 18:40:42 ip-10-0-0-74.vcaantech.com sensu-backend[2816]: {"component":"sensu-enterprise","error":"open /etc/sensu/backend.yml: no such file or directory","level":"fatal","msg":"error executing sensu-backend","time":"2019-12-18T18:40:42-07:00"}

Dec 18 18:40:42 ip-10-0-0-74.vcaantech.com systemd[1]: sensu-backend.service: main process exited, code=exited, status=1/FAILURE
````

**Comment by nikkixdev** [comment]
Glad you could make it past this roadblock @acrawly, and thanks for the feedback. I would suggest filing an issue to https://github.com/sensu/sensu-docs with your feedback regarding `/etc/sensu/backend.yml`.

Regarding your second point, I don't believe `sensu-backend init` should have any impact on your cluster configuration. You _should_ be able to configure your cluster as you normally would, and would just have to initialize the cluster admin user on _one_ of the backends in the cluster. If that is not the case, https://discourse.sensu.io/ or the community slack would be a great way to ask troubleshooting questions regarding your setup. If you believe the issue to be a bug, then please file a separate issue with steps to reproduce. Thanks again for the feedback!

**Comment by echlebek** [comment]
Please feel free to reopen this if any further discussion is needed.

**Comment by acrawly** [comment]
I finally did figure out how to do this. It turns out that you must run `sensu-backend init` ONCE for the entire cluster. The problem was that we ran it on each member of the cluster we stood up. Once we adjusted our Ansble playbook to use this, it worked great.

````yaml
- name: Initialize sensu backend
  command: sensu-backend init
  run_once: true
  environment:
    SENSU_BACKEND_CLUSTER_ADMIN_USERNAME: "{{ vault_sensu_default_username }}"
    SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD: "{{ vault_sensu_default_password }}"
````
