### ISSUE TITLE
health endpoint does not work when one of etcd nodes fails

### ISSUE THREAD

**Issue by dorroddorrod** [sensu/sensu-go#3484]
I have 5 backends nodes + 5 etcd nodes.
When one of the etcd nodes fails, the sensu-backend health endpoint does not work ( returning nothing )
I have a consul service that based on that endpoint and all my agents connected through this service.

## Steps to Reproduce (for bugs)
1.Run backend cluster
2.Run etcd cliuster
3.Stop etcd service on one of the nodes
4.check the health endpoint

## Your Environment
sensuctl & sensu-backend & sensu-agent version are 5.14.0-6578
etcd v3.3.17
installed with binaries and running on Ubuntu 14.04

**Comment by palourde** [comment]
Hi @dorroddorrod 

I'm happy to let you know that this issue has been fixed in the 5.16.0 release: https://github.com/sensu/sensu-go/blob/master/CHANGELOG.md#5160---2019-12-11

Please let us know if you still have any problems!
