### ISSUE TITLE
Memory leak in entity cache

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3486]
## Expected Behavior
Under stable load conditions, Sensu should use a constant amount of RAM.

## Current Behavior
Sensu consumes more RAM over time, constituting a memory leak. The leak is generally slow until the number of entities reaches into the tens of thousands.

## Possible Solution
The memory leak was traced to the entity cache, which uses etcd watchers to stay up to date. It seems that for whatever reason, this cache was leaking memory. It's unclear at this time what precisely is responsible for the leak. However, given that a simpler design that doesn't involve watchers seems to perform just as well, we can fix the problem just by refreshing the cache on an interval.

## Steps to Reproduce (for bugs)
Run Sensu with 40,000 agents, and observe linear RAM consumption.

## Context
Performance testing

## Your Environment
Fedora Linux, Enterprise Sensu, Postgres, 3 backends, 40K agents, 40K events per second, 40 checks

**Comment by palourde** [comment]
Quick update:

This bug appears to be caused not by a memory leak but rather a buildup of watch responses; The linear search used to update elements in the cache is not efficient enough and quickly prevents the cache from consuming watch results, which in turns block the watchers and therefore increases the memory consumption.

**Comment by palourde** [comment]
Closed by https://github.com/sensu/sensu-go/pull/3489
