### ISSUE TITLE
[Spike] Agent local services auto-discovery

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3502]
Proposal: https://docs.google.com/document/d/1HgQWesubiFvNTq-uSBIn5e0hj43PeIUMjdEbFoT-XBo/edit#

Investigate [gopsutil](https://github.com/shirou/gopsutil) vs [go-ps](https://github.com/mitchellh/go-ps), understand the tradeoffs, and choose “the best” library for our needs.

**Comment by amdprophet** [comment]
**github.com/mitchellh/go-ps**
* only supports pid, ppid, and executable
* executable name can get cut off if too long
* only supports linux, macOS, solaris, and windows
* 41 commits, 7 contributors, 776 stars

**github.com/shirou/gopsutil**
* supports all of the platforms we currently support in Sensu
* supports pid, ppid, executable name, executable full path, current working directory, group ids, user ids, nice, tgid, time stats, threads, children, and more
* 1,484 commits, 159 contributors, 4.6k stars
* we’re already using this library in Sensu

Based on this information, I conclude that we should use gopsutil for local service auto-discovery.

**Comment by amdprophet** [comment]
I should note that this is for process discovery.

`gopsutil` supports listing of Windows services. I'm currently looking into what's available for service listing on other platforms.
