### ISSUE TITLE
Spike: Agent local platform auto-discovery

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3503]
Proposal: https://docs.google.com/document/d/1HgQWesubiFvNTq-uSBIn5e0hj43PeIUMjdEbFoT-XBo/edit#

Investigate platform detection methods and available golang libraries.

Caleb has already done some good ground work [here](https://github.com/sensu/sensu-enterprise-go/issues/544).

**Comment by echlebek** [comment]
@portertech can you please have a quick review on my findings in the proposal doc?
