### ISSUE TITLE
Keepalive timeout value does not update after agent reconnection

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3509]
## Expected Behavior
When an agent reconnects with a different keepalive timeout value, the keepalive behaviour will be modified accordingly.

## Current Behavior
The old keepalive timeout value will be used.

## Possible Solution
The old keepalive switch should be destroyed when an agent reconnects.

## Steps to Reproduce (for bugs)
1. Create an agent with a keepalive interval of 5 and a timeout of 15
2. Stop the agent and immediately reconnect with an interval of 30 and a timeout of 60.
3. Observe that a keepalive failure occurs before being cleared.

**Comment by palourde** [comment]
@echlebek With the latest keepalive bugfixes, do you think this bug still exists?

**Comment by echlebek** [comment]
This was fixed in https://github.com/sensu/sensu-go/pull/3677
