### ISSUE TITLE
Proposal: add generic API hooks

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3515]
## Feature Suggestion
The generic API should provide a way to add hooks, so that we can express all of our API operations in terms of the generic API, instead of just some of our API operations.

For instance, imagine
```
routes.Put(r.handlers.DeleteResource).BeforeDeleteDo(func (req *http.Request, w types.Wrapper) error {
  entity := w.Resource.(*corev2.Entity)
  events, err := store.GetEventsByEntity(req.Context(), entity.Name)
  if err != nil {
    return err
  }
  for _, event := range events {
    if err := store.DeleteEventByEntityCheck(req.Context(), event.Entity.Name, event.Check.Name); err != nil {
      return err
    }
  }
  return nil
})
```

## Context
We need the flexibility of a generic API, while retaining as much power as possible.

**Comment by palourde** [comment]
@jamesdphillips mentioned that it could be really cool to have something like this for the api packages that GraphQL use. We maybe need to think a bit more about it.
