### ISSUE TITLE
sensuctl configure cached trusted CA as relative path on disk.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3520]
`sensuctl configure --trusted-ca-file  ./keys/ca.pm`
caches trusted-ca-file as relative path not full path in the `cluster` file.

This leads to unexpected results when using sensuctl from a different directory then the one used to run `sensuctl configure`

## Expected Behavior
Caches trusted ca file in `cluster` using absolute path.

## Current Behavior
Caches trusted ca file in `cluster` using relative path.

## Your Environment
sensu 2.16.1
centos 7

**Comment by echlebek** [comment]
We should use the absolute path of the argument.

**Comment by Salamek** [comment]
Maybe this issue should be closed since #3536 is merged? (and then 5.17.1 release?)

**Comment by nikkixdev** [comment]
Looks like the hook for the “Closes” keyword failed to fire. I’ll manually close this out since the associated PR is merged!
