### ISSUE TITLE
Sensu Go API asset upload do not allow uppercase in asset name

### ISSUE THREAD

**Issue by Salamek** [sensu/sensu-go#3522]
I'm unable to install asset with uppercase in Github owner name...
Sensu Go API name validation regexp require it to be lowercase:
https://github.com/sensu/sensu-go/blob/8c519bbd3cbae9bc4ae820d5df4a47104a554a46/api/core/v2/asset.go#L113

## Expected Behavior
I should be able to install Salamek/sensu-go-load-check or Thor77/sensu-telegram-handler using:

```bash
sensuctl asset add Salamek/sensu-go-load-check
```

## Current Behavior
```
root@sensu:~# sensuctl asset add Salamek/sensu-go-load-check
no version specified, using latest: 0.0.4
fetching bonsai asset: Salamek/sensu-go-load-check:0.0.4
Error: error putting resource 0 (/api/core/v2/namespaces/default/assets/Salamek%2Fsensu-go-load-check): invalid argument(s) received
root@sensu:~# sensuctl asset add Thor77/sensu-telegram-handler
no version specified, using latest: 0.1.3
fetching bonsai asset: Thor77/sensu-telegram-handler:0.1.3
Error: error putting resource 0 (/api/core/v2/namespaces/default/assets/Thor77%2Fsensu-telegram-handler): invalid argument(s) received
```

## Possible Solution
Allow uppercase in sensu go asset name, since asset name is combination of GitHub username and repository name, we should validate only repository name to be lowercase not a GitHub username part...

## Steps to Reproduce (for bugs)
just run 
```
sensuctl asset add Salamek/sensu-go-load-check
```
on your sensu go installation

## Context
I was trying to publish and use my first sensu go asset and create much more... now i'm stuck because my GitHub account name has a uppercase letter in it...

**Comment by jspaleta** [comment]
Thanks for filing!

Just some context for everyone.

Bonsai is currently trying to implementing a workaround now to downcase generated asset name metadata in all asset configs being pulled by sensuctl.  Ref: https://github.com/sensu/bonsai/issues/276#issuecomment-579472048

I'll update this bug report if the proposed workaround works. We'll hopefully be testing it this week.

But there is probably something that needs ot be done in the sensu-go codebase to help prevent future confuston.

## Suggested Enhancements to sensu-go
1. Remove the lower case name requirement in asset spec and from associated validation routines.

2. Have sensuctl sanitize asset name metadata prior to trying to create/update the asset resource. In fact this maybe required, I'm not sure how sensuctl is choosing to populate the metadata name. It sensuctl is just re-using the argument passed to `sensuctl asset add` then the Bonsai workaround will not be sufficient.

**Comment by echlebek** [comment]
It seems to make more sense to loosen the spec on asset names, so that it accepts uppercase characters, than it does to modify how bonsai works. Recommending we do that.
