### ISSUE TITLE
Make entity.metadata.entity_class optional for events published to the events APIs

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#3525]
## Feature Suggestion

Related to #3081. 

If we implement #3081, and make that default to creating proxy entities, then `entity.metadata.entity_class` should not be required for valid events published to the Events APIs.  

## Possible Implementation

Minimum valid events published to the events APIs should be as follows: 

- `POST /api/core/v2/namespaces/:namespace/events` 

   ```json
   {
     "entity": {
       "metadata": {
         "name": "I-424242"
       }
     },
     "check": {
       "metadata": {
         "name": "helloworld"
       },
       "status": 0,
       "output": "everything is a-ok!"
     }
   }
   ```

   Default values: 
   - `entity.metadata.namespace` defaults to the `:namespace` URL path element
   - `check.metadata.namespace` defaults to the `:namespace` URL path element  
   
   <br>_NOTE: these defaults are not yet implemented._

- `POST /api/core/v2/namespaces/:namespace/events/:entity/:check` 

   ```json
   {
     "check": {
       "status": 0,
       "output": "everything is a-ok!"
     }
   }
   ```

   Default values: 
   - `entity.metadata.name` defaults to the `:entity` URL path element 
   - `entity.metadata.namespace` defaults to the `:namespace` URL path element 
   - `check.metadata.name` defaults to the `:check` URL path element 
   - `check.metadata.namespace` defaults to the `:namespace` URL path element  
   
   <br>_NOTE: these default values are already implemented._

## Context

Let's make the Sensu APIs easier to use! 🙌

**Comment by echlebek** [comment]
@calebhailey, in the next major revision we hope to make all APIs use wrapped data types, which will help us avoid some major technical pitfalls we have with the current system. Is that something you see as being compatible with ease of use?

**Comment by portertech** [comment]
We are going to address #3081 and ensure `event.entity.entity_class` (not `entity.metadata.entity_class`) defaults to "proxy" and is not a required field on API POST/PUT.

**Comment by calebhailey** [comment]
![tenor](https://user-images.githubusercontent.com/141373/74494855-0cc6d780-4e8b-11ea-855a-44c0617ad058.gif)
