### ISSUE TITLE
Create etcd gauge implementations

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3534]
In https://github.com/sensu/sensu-go/issues/3436, three Gauge interfaces were specified. Implement these as concrete types using etcd.

Gauges measure a current quantity, unlike counters, which are monotonically increasing.

Do not modify the store interface. Create these data types in isolation.

Use a background polling process to generate the gauges and store them in memory. When requested by method call, the gauge values should be retrieved from a cache.

The polling interval should be configurable. Creating the gauges should start up a background worker that gets cancelled when the backend restarts.

Utilize the gauges in tessend, and additionally, write out their values to prometheus.

**Comment by portertech** [comment]
These gauges need to be scoped per namespace and our plan to expose this data via the prometheus endpoint is a non-starter (think multi-tenant deployments).
