### ISSUE TITLE
Support RHEL/CentOS 8

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3541]
## Feature Suggestion

Support RHEL/CentOS 8. This OS has been available for maybe a year or so, RHEL is now on 8.2 beta.

## Possible Implementation

Update builds and package releases to include RHEL/CentOS 8.

**Comment by agm650** [comment]
Unless I'm wrong you already have packages for [EL8](https://packagecloud.io/app/sensu/stable/search?dist=el%2F8) on packagecloud.io

**Comment by treydock** [comment]
Correct, they are, I was going off Docs supported platforms page. I'll open an issue against sensu-docs

**Comment by treydock** [comment]
https://github.com/sensu/sensu-docs/issues/2151
