### ISSUE TITLE
Add Agent CheckResult type/struct

### ISSUE THREAD

**Issue by tarcinil** [sensu/sensu-go#3549]
When creating a Result to be submitted via the Agent API, if you directly use types.Result, you will get a compliant check, but it will considered malformed by the API as it needs to be wrapped in `{"check: ...}`.  

types.Event does not work well for this as it requires Entity to validate properly, which appears to violate the [Agent API spec](https://docs.sensu.io/sensu-go/latest/reference/agent/#events-post-specification), but not the Backend API.  The API Queue for the Agent seems to add the entity later via the `PrepareEvent() + a.getEntities()` methods.  If the API request from the Agent was to pass Event with Entity, I came up with two questions.

1. I believe that it would work but would it represent meaningful information as it is possible to munge via `ProxyEntityName`?
2. How would the `PrepareEvent() + a.getEntities()` handle this?

https://github.com/sensu/sensu-go/blob/40b1d59382517863bd0ba38cdc2241d6d6c1196e/agent/entity.go#L47-L59

It is important not to break the usage of `Validate()` as it offers a clean interface to ensure that the check is compliant with the check specifications.

## Feature Suggestion
Add a CheckResult Type that can be passed into Agent API.

## Possible Implementation
```golang
type AgentResult struct {
	Check types.CheckResult `json:"check"`
}
```
## Example
```golang
SensuTypes "github.com/sensu/sensu-go/types"
type AgentResult struct {
	Check SensuTypes.CheckResult `json:"check"`
}

var agentResult AgentResult
var checkResult SensuTypes.CheckResult

checkResult.ProxyEntityName = "foo"
checkResult.Name = fmt.Sprintf("%s-%s-%d", "foo", result.ip, result.port)
checkResult.Namespace = "REDACTED"
checkResult.Interval = 3600
handler := []string{"REDACTED"}
checkResult.Handlers = handler
checkResult.Status = result.status
checkResult.Output = fmt.Sprintf("%s : %s", REDACTED[result.status], result.message)
if err := checkResult.Validate(); err != nil {
	fmt.Println("UNKNOWN : Check Result Validation Failed:", err)
	os.Exit(3)
}

agentResult.Check = checkResult

SubmitToAgentAPI(agentResult)
```

## Context
The standard exit code + standard output works well for simple cases, but when you want to start adding labels and annotations.  The opportunity cost start getting expensive when dealing with creating a custom struct or figuring out how to blend custom Structs + SensuGo Types.

This will allow an easy interface to extend for submitting events to the Agent `/event` via the standard expected per https://docs.sensu.io/sensu-go/latest/reference/agent/#events-post-specification

**Comment by echlebek** [comment]
cc @calebhailey, who has been active in discussions around agent API ergonomics lately.

**Comment by calebhailey** [comment]
I'll need to look at this on again when I'm at my desk, but I *think* what we would want here is to keep things simple (and uniform). It seems to me that the Agent API could (or should?) consume valid types.Event payloads. I know we've recently changed some of the `types.Event` validation logic in the backend API (several PRs that I won't bother to link here); could we look into doing the same in the Agent API (if no entity info is provided, use the agents entity details)? 

Anyway, my initial reaction here is that I don't think we want to introduce another type for this, even if it's a wrapper.

**Comment by tarcinil** [comment]
>  It seems to me that the Agent API could (or should?) consume valid types.Event payloads.

I agree with this as it does makes sense as it would create a clean `Event` pipeline regardless of the entry point.
