### ISSUE TITLE
silenced.check field selector doesn't seem to work properly

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-go#3553]
API response filtering using the `silenced.check` [field selector](https://docs.sensu.io/sensu-go/latest/api/overview/#field-selector) returns the same result for all of these requests:

```
curl -H "Authorization: Key xxxxxxxxxxxxxxxxxxxxxxxx" http://127.0.0.1:80\0/api/core/v2/silenced -G \
> --data-urlencode 'fieldSelector=silenced.check == true'

curl -H "Authorization: Key xxxxxxxxxxxxxxxxxxxxxxxx" http://127.0.0.1:80\0/api/core/v2/silenced -G \
> --data-urlencode 'fieldSelector=silenced.check != true'

curl -H "Authorization: Key xxxxxxxxxxxxxxxxxxxxxxxx" http://127.0.0.1:80\0/api/core/v2/silenced -G \
> --data-urlencode 'fieldSelector=silenced.check == false'
```

## Expected Behavior
It seems like `fieldSelector=silenced.check == true` should return all silenced checks, and `fieldSelector=silenced.check != true` should return all unsilenced checks (the inverse of `== true`).

## Current Behavior
These three field selector query parameters all return the same result:
'fieldSelector=silenced.check == true'
'fieldSelector=silenced.check != true'
'fieldSelector=silenced.check == false'

Here are my results for these requests. When I made these requests, I had several checks unsilenced and the `checksensusite` check was the only silenced.
```
vagrant@sensu-go-ldap:~$ curl -H "Authorization: Key f178683a-a05d-4cd7-8801-5a1947f10346" http://127.0.0.1:80\0/api/core/v2/silenced -G \
> --data-urlencode 'fieldSelector=silenced.check == true'
[{"metadata":{"name":"*:checksensusite","namespace":"default"},"expire":-1,"expire_on_resolve":false,"creator":"admin","check":"checksensusite","begin":1581542907}]
vagrant@sensu-go-ldap:~$ curl -H "Authorization: Key f178683a-a05d-4cd7-8801-5a1947f10346" http://127.0.0.1:80\0/api/core/v2/silenced -G \
> --data-urlencode 'fieldSelector=silenced.check != true'
[{"metadata":{"name":"*:checksensusite","namespace":"default"},"expire":-1,"expire_on_resolve":false,"creator":"admin","check":"checksensusite","begin":1581542907}]
vagrant@sensu-go-ldap:~$ curl -H "Authorization: Key f178683a-a05d-4cd7-8801-5a1947f10346" http://127.0.0.1:80\0/api/core/v2/silenced -G \
> --data-urlencode 'fieldSelector=silenced.check == false'
```

## Possible Solution
I'm not sure

## Steps to Reproduce (for bugs)
1. Silence a couple checks
2. Query the silenced API using field selector `silenced.check` with different operators
3. All results are identical

## Context
I ran into this issue while testing examples and updating the API overview section on response filtering.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.17.1
* Installation method (packages, binaries, docker etc.): I used the [sensu-go-ldap](https://github.com/sensu/skunkworks/tree/master/sensu-go-ldap) skunkworks virtual machine
* Operating System and version (e.g. Ubuntu 14.04): 18.04

**Comment by nikkixdev** [comment]
I was able to reproduce the issue. It appears that the [silenced router](https://github.com/sensu/sensu-go/blob/master/backend/apid/routers/silenced.go) does not have a routes for listing silences against it's [fields](https://github.com/sensu/sensu-go/blob/master/api/core/v2/silenced.go#L190-L201). I will have a patch for this shortly. 

@hillaryfraley It is important to note the fields you are using in your examples. `silenced.check` refers to the name of the check, it is not a boolean value. Rather, the fieldSelector should be expressed within quotes, ex. `fieldSelector=silenced.check == "check1"`.

**Comment by hillaryfraley** [comment]
Thank you, @nikkixdev !
