### ISSUE TITLE
Secret resource validation requires namespace

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3559]
When using `sensuctl create -f` to create a number of Sensu resources from YAML files, I get `resource is invalid: secrets require a namespace`.

## Expected Behavior
Secret resources should use the `sensuctl` namespace, either the set default or explicit `--namespace`.

## Current Behavior
`sensuctl create -f` returns an error, `resource is invalid: secrets require a namespace`.

## Context
https://github.com/portertech/sensu-stackdriver-kube/blob/715d4756dbb329cdda60930681e8f767a49bcc19/sensu/pipelines/stackdriver.yml#L10-L17

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.17.1
* Installation method (packages, binaries, docker etc.): Binsary
* Operating System and version (e.g. Ubuntu 14.04): Mac 10.15.2 (19C57)

**Comment by nikkixdev** [comment]
Secrets were the first namespaced resource implemented, and required some refactoring to some of the generic functions. I wouldn't be surprised if some of the cli tooling hasn't been ported over, such as the utility to load the current namespace into each command.
