### ISSUE TITLE
After #3446 the backend is unstable in the face of agent restarts

### ISSUE THREAD

**Issue by flowerysong** [sensu/sensu-go#3571]
## Expected Behavior

Agent behaviour should not affect backend stability.

## Current Behavior

Agents disconnecting and reconnecting can cause the backend to restart. Additionally, the restart is unreliable and etcd sometimes fails to come back up.

## Possible Solution

This doesn't happen every time an agent restarts, so it feels like a race condition of some sort.

## Steps to Reproduce (for bugs)

1. Occurs with the default config.

2.
```
#!/bin/bash

logfile=backend-$(date +%s).log

./sensu-backend start &>$logfile &
backpid=$!

i=0

while [[ $(( i++ )) -lt 1000 ]] && ! grep -q 'backend stopped working' $logfile; do
    ./sensu-agent start &>/dev/null &
    apid=$!
    sleep 0.1
    kill $apid
done

kill $backpid
```

## Context

After upgrading to v5.17.1 we started experiencing strange half-alive states where many of the components were up and running but etcd was not. I managed to reliably reproduce it in our dev environment, then whittled down the scenario and created a reproducer.

Quickest occurrence (at the default log level): https://gist.githubusercontent.com/flowerysong/ee585a2a69c06baec7045288d0146240/raw/97db4b6107ca8fe9b58e6567c4d7e73e62722470/backend-1582144510.log
Verbose backend log running 572b4b5facc4a4f7b310dcf0eb34ef711e9583e5: https://gist.github.com/flowerysong/e62e60b12e090f1163918930b50e8924/raw/b9a028b35906968a589380ee24b9d70001173a8a/backend-1582144823.log

Verbose backend log running 20fb131a89e55cf395c925988cbad228aa71fa3f (no components appear to fail): https://gist.githubusercontent.com/flowerysong/e62e60b12e090f1163918930b50e8924/raw/b9a028b35906968a589380ee24b9d70001173a8a/backend-1582145452.log

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): First experienced in v5.17.1, bisected down to 572b4b5facc4a4f7b310dcf0eb34ef711e9583e5
* Installation method (packages, binaries, docker etc.): `go build`
* Operating System and version (e.g. Ubuntu 14.04): Amazon Linux 2

**Comment by echlebek** [comment]
Thank you for the detailed bug report. I ran the script you provided, but was only partly able to reproduce what you have in your logs. (Fast laptop, Linux 5.4)

I was not able to provoke the backend restart that is present in your logs.

What I was able to reproduce were the error logs generating by quitting agents. For each disconnection, 3 lines of logging were produced during the session shutdown. This is more or less normal, but could perhaps be cleaned up a bit so agents don't cause so much noise when shutting down.

It doesn't seem conclusive that the agent restarts are causing the backend to stop, but if you are experiencing reduced stability after upgrading, it's still a regression in some way.

More investigation will be needed.

**Comment by echlebek** [comment]
@flowerysong it seems possible that the linked PRs may have resolved this issue. Can you please test with 5.18.1 or greater, and let us know if that is indeed the case? Thanks!

**Comment by flowerysong** [comment]
@echlebek Still seems to happen, though the error right before the restart is one I haven't seen before:

```
{"addr":"10.0.80.219:46906","agent":"ip-10-0-80-219.us-east-2.compute.internal","component":"agentd","error":"Connection closed: websocket: close 1001 (going away): bye","level":"warning","msg":"stopping session","time":"2020-03-27T00:55:03-04:00"}
{"component":"agentd","level":"info","msg":"shutting down agent session: stopping receiver","time":"2020-03-27T00:55:03-04:00"}
{"component":"agentd","level":"info","msg":"shutting down agent session: stopping sender","time":"2020-03-27T00:55:03-04:00"}
{"agent":"ip-10-0-80-219.us-east-2.compute.internal","component":"agentd","level":"info","msg":"removing agent from ring","namespace":"default","time":"2020-03-27T00:55:03-04:00"}
{"agent":"ip-10-0-80-219.us-east-2.compute.internal","component":"agentd","level":"info","msg":"removing agent from ring","namespace":"default","time":"2020-03-27T00:55:03-04:00"}
{"level":"warn","ts":"2020-03-27T00:55:03.464-0400","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-e1446c25-d41c-4916-bdea-28aac1aa0ece/localhost:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
{"component":"backend","error":"internal error: internal error: context canceled","level":"error","msg":"backend stopped working and is restarting","time":"2020-03-27T00:55:03-04:00"}
```

**Comment by flowerysong** [comment]
@echlebek I had the time and motivation to poke at this some on my own, and I believe #3707 will finish resolving the issue.
