### ISSUE TITLE
Add agent platform auto-discovery

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3587]
Add the following 4 fields to Entity.System:
```
string libc_type ("glibc", "musl", "apple", "")
string vm_system (described above)
string vm_role ("guest", "host", "")
string cloud_provider ("EC2", "GCP", "Azure", "")
```

Use the design doc to understand how to populate these fields agent-side.

https://docs.google.com/document/d/1HgQWesubiFvNTq-uSBIn5e0hj43PeIUMjdEbFoT-XBo/edit#

**Comment by portertech** [comment]
Will be picked back up following the 5.18.1 release.
