### ISSUE TITLE
Object metadata created by (HTTP API)

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3591]
Update all object metadata to contain a "created by" field. This field would be set by the API and override any user provided value. This field adds context that can be leveraged by features and improves optics on user creation and management.

## Feature Suggestion

Update all object metadata to contain a "created by" field. This field adds context that can be leveraged by features and improves optics on user creation and management.

## Possible Implementation
The object metadata created by field could be set by the API and override any user provided value.

**Comment by nikkixdev** [comment]
Limiting the scope of this ticket to just the HTTP API. All resources that are created or updated via the HTTP API will populate the `created_by` field with the sensu user responsible for the changes. Agent side resources will be handled as part of https://github.com/sensu/sensu-go/issues/3601.
