### ISSUE TITLE
Cluster configuration to disable automatic proxy entity creation

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3593]
Sensu Go will automatically create a proxy entity for events that reference one that does not exist. This includes events created via the Backend API. This behaviour should be configurable, cluster wide.

## Feature Suggestion

Add a cluster configuration option to disable automatic proxy entity creation. Another option could be to drop events for non-existent entities (requiring explicit user creation ahead of time).

## Possible Implementation

Add a cluster configuration resource to handle this and alike configuration options. A cluster configuration resource is better than using `backend.yml`, as configuration changes will apply to all Sensu Go Backends within a cluster.

OR

We leverage RBAC policy and context to limit automatic proxy entity creation.

## Context

This should address issues like:

https://github.com/sensu/sensu-go/pull/3192
https://github.com/sensu/sensu-go/pull/3195

**Comment by calebhailey** [comment]
The Sensu data model expects every event to have an associated entity. The way to bypass entity creation is to reference an existing entity (e.g. `proxy_entity_name`).
