### ISSUE TITLE
sensuctl license info should additionally output entity information

### ISSUE THREAD

**Issue by rgeniesse** [sensu/sensu-go#3611]
## Feature Suggestion
When running `sensuctl license info`, the information found at:

https://docs.sensu.io/sensu-go/latest/reference/license/#entity-limit

Should also be printed.

```
Sensu-Entity-Count: 4
Sensu-Entity-Limit: 0
```

## Context
As entity limits and counts are part of licenses, having this at the license info endpoint seems natural.

**Comment by portertech** [comment]
We should be able to expose the API response header info (Entity Count) in the tabular output.

We could add another subcommand for just this purpose.

Outputting these headers in YAML or JSON output would be strange and create inconsistency with other subcommands, e.g. `sensuctl dump`.

**Comment by portertech** [comment]
We will add this header information in the `sensuctl license info` tabular output, using `===` as a object delimiter and state something like "You are currently using X out of Y entities". We must handle the case where the entity limit is `0` (unlimited).
