### ISSUE TITLE
Health endpoint does not work when one node is down

### ISSUE THREAD

**Issue by twosevenska** [sensu/sensu-go#3621]
The health endpoint no longer works when at least one node is down. However if we use the same `?timeout=3` query param that is used in the sensuctl command line tool it still works. 
Seeing as this was fixed in 5.16 per https://github.com/sensu/sensu-go/issues/3484 this might be a regression.

## Steps to Reproduce (for bugs)

1. Run backend cluster
2. Stop service on one of the nodes
3. Check the health endpoint 

## Your Environment
* Sensu version used: 5.18 for both sensu-backend and sensuctl 
* Installation method: binaries
* Operating System and version: CentOS 7.7

**Comment by palourde** [comment]
We should fallback to a default value if no timeout parameter was provided here:
https://github.com/sensu/sensu-go/blob/7a9f9f423d2dd556e6ac3e5ae4a91b2b916052a3/backend/apid/routers/health.go#L38

**Comment by twosevenska** [comment]
I just took a quick peek and it seems the issue might be that inside parseTimeout it is expected that the length of FormValue result will be 0 when no timeout flag is provided. However according to the golang http package docs FormValue will return an empty string when the key is not present: https://golang.org/pkg/net/http/#Request.FormValue
