### ISSUE TITLE
Mirroring https://assets.bonsai.sensu.io on Artifactory

### ISSUE THREAD

**Issue by rforberger** [sensu/sensu-go#3624]
## Description
I want to mirror https://assets.bonsai.sensu.io on Artifactory
## Proposal
no proposal

## Spec
no spec

## Issues
no issues

Hi,

since we want to use Sensu but are behind a corporate firewall and web proxy, we would like to mirror assets.bonsai.sensu.io on our JFrog Artifactory, which we can access behind the firewall.

Can anyone tell me what repository type assets.bonsai.sensu.io is using?

I would then be able to set up the repo in Artifactory.

Thanks in advance.

Best regards,
rforberger

**Comment by jspaleta** [comment]
Hello,

At present assets.bonsai.sensu.io points to a CloudFront CDN, backed by an s3 bucket. 

I'm not sure how you would go about mirroring it, as the CDN isn't traversable like a flat filesystem and I don't think we are going to expose the s3 bucket to the public..that would defeat the purpose of having a CDN in place.  

What you might be able to do is talk to the bonsai api and discover all the active assets and mirror them that way.

take a look at: https://bonsai.sensu.io/apidoc
There is an api endpoint that will provide a list of all registered assets 

I hope this helps.

**Comment by rforberger** [comment]
Hi @jspaleta ,

thank you for your information. 

I cannot go for discovering the active assets via api because our Artifactory doesn't support it.
I tried to mirror with Generic repo type, but it says general error.

Thank you anyway.

Best regards,
rforberger
