### ISSUE TITLE
[Spike] Investigate silenced naming

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3630]
Decide if users should optionally be able to name silences or should the names be automatically generated by specific field in the silence. Once investigation is done, specify implementation details required for https://github.com/sensu/sensu-go/issues/3374.

**Comment by nikkixdev** [comment]
Silences are currently cached which could make this a little more complex. We estimate that the work required to refactor this could be large, potentially worth bumping to 6.0.
