### ISSUE TITLE
[Proposal] Allowing Resty HTTP Timeout to be configurable

### ISSUE THREAD

**Issue by naemono** [sensu/sensu-go#3635]
https://github.com/sensu/sensu-go/blob/master/cli/client/client.go#L43

The question/proposal is centered around the above code ^^.  Would a PR be acceptable to
* allow that timeout to be configurable at all?
* allow that timeout to be configurable from the cli?
* allow that timeout configurable item to be persisted in the configuration file

## Possible Implementation

Draft PR here https://github.com/naemono/sensu-go/pull/1

## Context

In heavily used sensu-go installations, sometimes 15 seconds isn't quite enough time to get a response.

**Comment by echlebek** [comment]
It looks reasonable to me, I'll bring it to the team and let you know!

**Comment by echlebek** [comment]
@naemono we're supportive of this change. Please file a PR whenever you are ready. Thanks! :+1: :tada:

**Comment by naemono** [comment]
thanks @echlebek .  Should this just be closed now?  #3637 opened.

**Comment by echlebek** [comment]
We can close it once #3637 is merged. Thanks!
