### ISSUE TITLE
It is impossible to express quoted strings in token substitution templates

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3640]
## Expected Behavior
Uses should be able to express quoted strings like this in templates:

```
{{ "\"foo\"" }}
```

## Current Behavior
The escaped quotes are discarded by the template preprocessor: https://github.com/sensu/sensu-go/commit/717b5a729754fe22d33a216d6bca162507eeb681

## Possible Solution
Unclear.

## Steps to Reproduce (for bugs)
Attempt to use the above example, observe that the template (which is valid on its own) will not compile.

## Context
Debugging for @cwjohnston

**Comment by nikkixdev** [comment]
The following commits add or modify the logic to replace escape characters in token substitution:
- https://github.com/sensu/sensu-go/commit/717b5a729754fe22d33a216d6bca162507eeb681 derives from https://github.com/sensu/sensu-go/pull/944
- https://github.com/sensu/sensu-go/commit/eacf6ed570a5d085b35a3796a68af5299a67d6ce derives from https://github.com/sensu/sensu-go/pull/868

**Comment by echlebek** [comment]
Thanks for the investigation :100:
