### ISSUE TITLE
The number of TLS configuration flags needed to secure a backend is too high

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3649]
## Expected Behavior

For simple scenarios, only one certificate, key and trusted CA need be specified in the backend configuration to secure all listening ports.

## Current Behavior

Securing all listening ports with a single TLS certificate/key pair requires providing values for the following parameters:

* etcd-cert-file
* etcd-key-file
* etcd-trusted-ca-file
* etcd-peer-cert-file
* etcd-peer-key-file
* etcd-peer-trusted-ca-file
* cert-file
* key-file
* trusted-ca-file

## Possible Solution

Allow `cert-file`, `key-file` and `trusted-ca-file` values to act as defaults for corresponding flags prefixed with `etcd-` and `etcd-peer-`.

## Context

![](https://i.imgflip.com/3u2xzf.jpg)

**Comment by echlebek** [comment]
Something we can address in 6.0!

**Comment by portertech** [comment]
I am concerned that setting a default value for the etcd keys could be problematic as it would force encryption when it may not be desired. Further discussion is needed, removing from the 6.0 milestone.

**Comment by portertech** [comment]
Cyril's comment: "we intentionally split these out in response to user demand"

**Comment by portertech** [comment]
@cwjohnston I would like us to discuss this one before I close it.
