### ISSUE TITLE
Asset mismatch log messages should provide more context

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3651]

**Comment by echlebek** [comment]
Oh the irony :laughing:

**Comment by nikkixdev** [comment]
@cwjohnston could you elaborate more on the issue so we can triage?

**Comment by echlebek** [comment]
@cwjohnston we need to know what kind of context you or the customer is looking for in these log messages, please!

**Comment by cwjohnston** [comment]
Closing in favor of https://github.com/sensu/sensu-go/issues/3674 which I believe is a bug.
