### ISSUE TITLE
Asset builds with highest counted elements of build filter takes precedence 

### ISSUE THREAD

**Issue by tarcinil** [sensu/sensu-go#3655]
## Feature Suggestion
When multiple builds have passing filters use the build with the highest (counted elements) matched filters.

## Possible Implementation
N/A - I haven't reviewed the current code.

## Context
> For assets with multiple builds, only the first build which matches will be downloaded and installed.

Based on this from [Asset Documentation](https://docs.sensu.io/sensu-go/latest/reference/assets/#asset-build-evaluation), it means that if you have:

```
filters: ["entity.system.os == 'linux'", "entity.system.arch == 'amd64'"]
```
vs.
```
filters: ["entity.system.os == 'linux'", "entity.system.arch == 'amd64'", "some.label.zone == 'foo'"]
```

Present Implementation would use the build information from the first `build` slice.

Feature: Because the 2nd slice has 3 total elements, it takes precedence.  
Edge Case: same present condition, if 2 slices of the same size exists, use first.

**Comment by echlebek** [comment]
Interesting idea, thanks!

**Comment by nikkixdev** [comment]
We should audit how filtering behaves currently, @amdprophet believes it's the first match. If that's the case, implementing this could be a breaking change for some use cases. Potentially a good candidate for 6.0.0, but needs more investigation first.

**Comment by calebhailey** [comment]
I removed the `wontfix` label, but this might have to sit in the backlog until the next major release (2021) as it would be a breaking change, as commented above.

**Comment by tarcinil** [comment]
That is fine.  I have worked around the issue in Ruby.
