### ISSUE TITLE
allow --all-namespaces parameter with prune command

### ISSUE THREAD

**Issue by arkpoah** [sensu/sensu-go#3668]
## Feature Suggestion
Pruning is not possible via a resource file, so it would be useful having --all-namespaces parameter with prune command

## Context
I manage resources via a docker image which send create command to sensu backend in Kubernetes.
If i want to use prune, I need to run a command per namespace, so an image per command, so --all-namespaces would be great for that !

Thanks

**Comment by nikkixdev** [comment]
This is just the feedback we need for the alpha feature, thanks for filing this! We did consider an `--all-namespaces` option during the first round of development, but aired on the side of caution when it came to deleting resources. I do see this as a valid enhancement for many use cases.

**Comment by arkpoah** [comment]
It is also valid for others commands like entity or event.
It is possible use  `--all-namespaces`  to list but not to delete.
thx !

**Comment by raddessi** [comment]
I still see this as being useful
