### ISSUE TITLE
sensu-agent allows setting keepalive-timeout lower than keepalive-interval

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3671]
## Expected Behavior
Attempting to set `keepalive-warning-timeout` or `keepalive-critical-timeout` lower than the keepalive interval should result in the agent crashing with an error.

## Current Behavior
The agent functions as expected, and keepalive events flap between passing and failing.

## Possible Solution
Disallow setting timeout lower than interval.

## Steps to Reproduce (for bugs)
```
sensu-agent start --keepalive-warning-timeout 10
```

## Context
Doing testing related to keepalives.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/3677
