### ISSUE TITLE
Keepalive timeout does not get set immediately on agent start

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3673]
## Expected Behavior
When the agent starts up with a different keepalive timeout, the existing persisted keepalive timeout should be destroyed.

## Current Behavior
The keepalive mechanism can trip even if it's set to longer on agent connect.

## Possible Solution
Destroy the agent's switchset on agent connect.

## Steps to Reproduce (for bugs)
```
sensu-agent start --keepalive-warning-timeout 10 --keepalive-interval 5
# wait a bit and terminate
sensu-agent start --keepalive-warning-timeout 60 --keepalive-interval 20
```

Observe a failing keepalive is produced.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/3677
