### ISSUE TITLE
Asset checksum mismatch messages are confusing

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3674]
## Expected Behavior

Log messages are clear and actionable

## Current Behavior

When a downloaded asset artifact checksum does not match the checksum specified in the asset definition, a message similar to this one is logged by the agent:

```
error getting assets for event: sha512 '5ca389e611da25dc09310220e5965c7bde51c733128725c76f8baf153ca9fcc126cb9a5dfa55afb7a4c62a78c14a1b2b89cbd72e579af7486f3c12a20e15c6a8' does not match specified sha512: 'ecbbb9ade80307bd598458f10410d4b136948198aea85358d0cbd250f8a16676a21aa8dce4a468c9e6ffa52ecfd360c566a7809d0930e21a309ae92ec330df16'
```

In this case `5ca389` is the checksum I specified in the asset definition, and `ecbbb` is the checksum computed for the downloaded artifact.

A number of operators have indicated that the text `specified sha512: <checksum>` implies to them that the checksum after the colon would be the one specified in the asset definition. 
## Possible Solution

* Revise the log message to better reflect which checksum is from the downloaded artifact and which checksum is from the asset definition
* Add information about the size of the retrieved artifact in the log message -- this will help operators avoid logging into the system where the agent is running to discover that the agent has downloaded a small HTML error page instead of the expected tarball

## Steps to Reproduce (for bugs)
1. create an asset definition with a working asset URL but known-incorrect sha512 checksum (e.g. `5ca389e611da25dc09310220e5965c7bde51c733128725c76f8baf153ca9fcc126cb9a5dfa55afb7a4c62a78c14a1b2b89cbd72e579af7486f3c12a20e15c6a8` )
2. create a check using the known-incorrect asset definition as a runtime_asset
3. note that the log message indicates the known-incorrect checksum as the `specified sha512` checksum
4.

## Context

Confusion due to unclear log messages leads to wasted time troubleshooting.

**Comment by gojkoz** [comment]
Love both possible solutions, you should implement them both :) "small html error page" is a common issue...

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/4118
