### ISSUE TITLE
Keepalive events will stop generating new UUIDs after failing

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3676]
## Expected Behavior
Every updated keepalive event will get a new UUID.

## Current Behavior
The old UUID is re-used.

## Possible Solution
Use a new UUID for each subsequent keepalive event.

## Steps to Reproduce (for bugs)
1. Cause a keepalive failure.
2. Observe that each updated keepalive failure event has the same UUID as before.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/3677
