### ISSUE TITLE
Entity state based on an event state of a check which does not exist anymore

### ISSUE THREAD

**Issue by arkpoah** [sensu/sensu-go#3679]
## Expected Behavior
After prune of a check resource, the check is still visible in events list of the entitie page, why not.
Entitie should not be affected by the state of this event, which is a check that does not exist anymore.

## Current Behavior
If a check is in a critical state then is pruned, entity stays to critical state.

## Steps to Reproduce (for bugs)
1. Create a check
2. Get it to critical state
3. prune it
4. Entity still in critical state whereas others checks are ok

## Your Environment

* sensuctl and sensu-backend : 5.19.0
* Installation method : https://github.com/sensu/sensu-k8s-quick-start
* Operating System and version : Kubernetes v1.14.8

**Comment by palourde** [comment]
This is related to https://github.com/sensu/sensu-go/issues/3095.

We already [delete entities associated with a deleted entity](https://github.com/sensu/sensu-go/pull/3066) but we do not apply the same logic to delete checks.
