### ISSUE TITLE
Getting events by entity can return results for the wrong entity

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3686]
## Expected Behavior
Getting events by entity returns events only for the exact match of the entity.

## Current Behavior
Using a non-existent entity which is a prefix of an entity that does exist will return the results for the entity that does exist.

For instance:

```
GET http://example.com:8080/api/core/v2/namespaces/default/events/localhost
```

Will return results for `localhost.localdomain`, if those events exist.

## Steps to Reproduce (for bugs)
See description.

**Comment by nikkixdev** [comment]
I was able to reproduce this as long as the prefix used is at least 6 characters. An interesting behavior, but should make this easier to track down.

**Comment by echlebek** [comment]
Haha, 6 characters, interesting!

**Comment by nikkixdev** [comment]
I can also confirm that this bug only exists in the etcd event store, not the postgres event store. I'm trying to get a better understanding around some of the etcd function calls that are likely responsible (ex. `GetPrefixRangeEnd`, `WithRange`, etc).

**Comment by echlebek** [comment]
@nikkixdev the method reads all key/value pairs at a given prefix, it should likely have a slash appended to the end of it so it doesn't read from entities that it's not supposed to.
