### ISSUE TITLE
Asset Templating

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3695]
**The following user stories have been identified as improvements to asset templating:**
- As an operator, I can access the asset path in my check, mutator, hook or pipe handler command parameter so I can pass the full path of a file in my asset as a command argument.
- As an operator, I can access env vars in asset headers for secure information such as authorization keys.
- As an operator, I can access entity information in my asset to discern information such as the security zone.
- As an operator, I can to access custom environment variables in my asset that contains information such as the bin path.

**The following tasks have been identified to help achieve the aforementioned user stories:**
- https://github.com/sensu/sensu-go/issues/3639 Enable token substitution in assets
- https://github.com/sensu/sensu-go/issues/3662 Add a template function to retrieve the asset path via token substitution
- https://github.com/sensu/sensu-go/issues/3698 Enrich the backend entity by loading in labels/annotations from the backend config

**The following tasks have been identified as future improvements in relation to asset templating, but will not encompass the work of this epic:**
- https://github.com/sensu/sensu-go/issues/2184 Store the backend as an entity
- https://github.com/sensu/sensu-go/issues/3619 Access asset env vars in headers
- https://github.com/sensu/sensu-go/issues/3492 Enable environment variables in assets

See [notes doc](https://docs.google.com/document/d/1xbQjfI40DAOlfzlYjIIyXBgUhZDxg7QanmwlOHEJAK4) for more information.

**Comment by calebhailey** [comment]
Thanks for creating this issue, @nikkixdev 

This looks great! Excited for these improvements. 💪
