### ISSUE TITLE
Add a template function to retrieve the asset path via token substitution

### ISSUE THREAD

**Issue by nikkixdev** [sensu/sensu-go#3696]
## Feature Suggestion
Add a template function to retrieve the asset path via token substitution, ex. `SOME_VAR: {{ assetPath "sensu/ruby:1.1.1" }}`

## Possible Implementation
- [ ] create a new go template function, `assetPath` (see [defaultFunc](https://github.com/sensu/sensu-go/blob/60fd09166b025e805ea5345b8a497b7d68c824bd/agent/token.go#L119-L141) as an example)
- [ ] expose the absolute base path of the asset through this function
  - [ ] document that it is operator responsibility to append/prepend any other strings, ex. `bin`
  - [ ] the absolute path of the asset depends on the agent configuration fields, so this information will need to be injected somehow for the standalone library to reference

## Context
Requires https://github.com/sensu/sensu-go/issues/3639

**Comment by nikkixdev** [comment]
Closing in favor of https://github.com/sensu/sensu-go/issues/3662.

**Comment by palourde** [comment]
@nikkixdev Should we close this issue?

**Comment by nikkixdev** [comment]
Close and comment button must not have worked (or I clicked the wrong button 😜).. closing actually now!
