### ISSUE TITLE
sensuctl prune multi file handling is busted

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3702]
## Expected Behavior
prune multi-file handling should work 

## Current Behavior
using -r  or multple calls to -f  result if prune cleaning out all resources intead of leaving the named resources from the files in place

## Steps to Reproduce (for bugs)

1.  using sensu-community/monitoring-plugins repo
2.  sensuctl create -r -f system/linux/cpu system/linux/disk    (creates 20 checks)
3. sensuctl prune checks -f system/linux/cpu/check-cpu.yaml  -f system/linux/disk/check-disk-usage.yaml     (all checks pruned
4.  sensuctl create -r -f system/linux/cpu system/linux/disk
5. sensuctl prune checks -r -f system/linux/cpu/   ( all checks pruned)

**Comment by jspaleta** [comment]
Shell catting files still works as expected
`cat system/linux/cpu/check-cpu.yaml system/linux/disk/check-disk-usage.yaml | sensuctl prune checks`

Leaves 2 checks behind as expected

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/live-webinar-on-april-23-getting-started-with-assets/1696/2

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/whats-new-in-sensu-april-16-2020/1687/2

**Comment by nikkictl** [comment]
See https://github.com/sensu/sensu-go/issues/3845 for additional context.

**Comment by raddessi** [comment]
Are there any plans to fix this?

**Comment by calebhailey** [comment]
@raddessi yes! We don't have an ETA as of yet, but it's becoming a priority so I would expect to see some progress here soon. 

In the interim, can you share any details about how this is impacting you? Are you implementing `sensuctl prune` as part of your CI/CD pipeline by any chance? 

Thanks in advance for your feedback!

**Comment by raddessi** [comment]
Great news :) I tried to use prune with multiple files but right now am only using it with a single file. I tried to implement it with multiple files as the management method for my setup but found this bug so I stopped moving in that direction until this is resolved.
