### ISSUE TITLE
Agent connection messages are not visible at the default log level

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3704]
## Expected Behavior

Agent logs messages related to backend connection status at the default log level.

## Current Behavior

Agent logs useful messages like "connecting to backend URL foo" and "successfully connected" at `info` level, which is not visible at agent's default log level of `warn`. 

## Possible Solution

* Use `warn` log level for [these sort of messages](https://github.com/sensu/sensu-go/blob/v5.19.1/agent/agent.go#L452-L461).
* Change agent default log level to `info`

## Context

As a person supporting Sensu users, I would like agent logs to provide explicit indication that the agent connected successfully without requiring operators to change the log level from defaults.

**Comment by echlebek** [comment]
The default agent log level should be INFO. WARN default seems to be a bit heavy handed. We may need to move some INFO logging to DEBUG.

**Comment by portertech** [comment]
Requirements:

- [ ] Draft log message severity guidelines
- [ ] Apply severity guidelines to the Agent codebase (i.e. make connection message available at info)
- [ ] Change Agent default log level to info

**Comment by ccressent** [comment]
Logging level guidelines document:
https://docs.google.com/document/d/1zCEakwrmYE2KiTQ9zsb6nqe2swgzVTvGUQhK7FmxfM4
