### ISSUE TITLE
Feaure Request: provide new option to dump to strip namespaces from dumped resources.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3705]
## Feature Suggestion
allow sensuctl dump to optionally strip namespace from metadata.
This makes it possible to dump resource in one namespace as templates meant to be imported into another namespace.

This will help a number of prototyping workflows where ops are working in a dev namespace and need to export new pipelines into a production namespace on a different cluster.

**Comment by palourde** [comment]
@jspaleta We believe this could be easily achieved with something like `jq`. WDYT?

@portertech How do you feel about this one? The team is afraid it will just open the door to a bunch of features that can be achieved the "unix way".

**Comment by calebhailey** [comment]
@jspaleta I believe you worked on a sensuctl command plugin for this? Can we close this issue with a link to your plugin?
