### ISSUE TITLE
Provide packages for Ubuntu 20.04 (Focal Fossa)

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#3719]
Ubuntu 20.04 LTS has been released last week, so we need to determine what's required for providing packages to this new version in packagecloud.

**Comment by palourde** [comment]
While we are tackling this issue, we probably need to make sure we also provide packages for 19.10 (Eoan Ermine)

**Comment by amdprophet** [comment]
This will be shipping with 5.19.2.

**Comment by tvdstaaij** [comment]
I think something went wrong with this for the latest release (Sensu Go 5.21.0). I was wondering why my Ubuntu 20.04 machine wouldn't upgrade from 5.20.2, and it looks like that's because there are focal packages for ARM64 but not for AMD64.
