### ISSUE TITLE
Support triggering internal restart with SIGHUP

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3722]
## Feature Suggestion
Force sensu-backend to restart when it encounters SIGHUP.

## Context
We've had several bugs around the internal backend restart feature. The backend is designed to restart internally when it encounters fatal errors, in the hope that shedding load and re-establishing itself will clear up whatever issues it is facing. However, since it's difficult to trigger this behaviour in a healthy system, it is also hard to test. As a result, there have been some bugs that only show up when the backend restarts.

If we could intentionally trigger a backend restart, it would make debugging problems easier, and improve stability testing.

**Comment by echlebek** [comment]
@portertech says SIGUSR2 and SIGHUP are commonly used to support this type of feature in applications.

**Comment by calebhailey** [comment]
@echlebek it looks like we intended #3723 to close this issue, so I'm going to go ahead and close it. 🙌  Let me know if it should be reopened.
