### ISSUE TITLE
Add --omit to sensuctl dump all

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3724]
## Feature Suggestion
Add the flag `--omit` to `sensuctl dump all`, as a way to omit certain resources from being dumped. This will allow users to dump "everything but X".

The omit flag should map to a slice of inputs, allowing users to specify `--omit` multiple times, or allowing users to comma-separate the resources passed to `--omit`.

The resources will be in short form, i.e. `checks,handlers` or in long form, i.e. `core/v2.CheckConfig`.

## Context
Making sensuctl dump fit for backup and restore.

## Gif
![image](https://media.giphy.com/media/3orifd47Hhul6a8hfW/giphy.gif)

**Comment by palourde** [comment]
Related to https://github.com/sensu/sensu-enterprise-go/issues/929

**Comment by portertech** [comment]
We should make a gen-eric package to be applied to other CLI commands.

**Comment by nikkixdev** [comment]
Related: https://github.com/sensu/sensu-enterprise-go/issues/929
