### ISSUE TITLE
Upgrade to etcd 3.4

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#3729]
###  Background

We should consider upgrading etcd to v3.4. There's a couple of [significant improvements](https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md#v340-2019-08-30) that we could probably benefit from. Additionally, etcd now recommends 3.3.18+, and 3.4.2+ as minimal versions for production.

One important thing to notice is that etcd 3.4 switched to go modules and is now known as the `go.etcd.io/etcd/v3` module, which signifies we will need to update the import path in our codebase.

### Acceptance Criteria

- [ ] sensu-go with etcd 3.4 is benchmarked to make sure it doesn't introduce any performance regression
- [ ] The new 3.4 features are reviewed and spikes and/or feature requests are open if there's anything significant we should explore/implement.

### Definition of Done

- [ ] sensu-backend w/ etcd 3.4 is benchmarked
- [ ] sensu-backend w/ etcd 3.4 passes the automated QA

**Comment by palourde** [comment]
We might have to wait for 3.5: https://github.com/etcd-io/etcd/issues/11154

**Comment by nikkictl** [comment]
For multiple reasons (described in https://github.com/sensu/sensu-go/issues/3760#issuecomment-630353334), we must wait for etcd v3.5 to update etcd, bolt, and go.

**Comment by portertech** [comment]
@eric to comment.

**Comment by eric** [comment]
I have no comment 😬

**Comment by portertech** [comment]
@eric This made my day :laughing: 

Will the real @echlebek please stand up.

**Comment by nikkictl** [comment]
We can track the v3.5 milestone here: https://github.com/etcd-io/etcd/milestone/37

**Comment by amdprophet** [comment]
Implemented in #4229.
