### ISSUE TITLE
sensu-backend maintenance mode -- authlessly-configurable state for backend

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#374]
We need to be able to put the backend into a state where it's configurable.

For example:

- A user needs to reset their password
- We need to seed the database with an initial user, role, environment, organization.

When in maintenance mode, the backend shouldn't accept connections via the API or Agents, but it still needs to be connected to the rest of its peers.

If it's not accepting connections via the usual API, though, then what good is maintenance mode? How might we limit interaction? In MySQL/Postgres this is via a local UNIX socket. How do those systems do it on Windows? Can we easily add a subset of functionality to a new sub-command in sensu-backend (e.g. `sensu-backend admin reset-password <user>`).

**Comment by echlebek** [comment]
@grepory is this still something that's needed?

**Comment by grepory** [comment]
This can be broken up into multiple issues, and we should revisit / rethink the requirements and problem we're trying to solve.
