### ISSUE TITLE
Report entity limits in Tessen

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3741]
## Feature Suggestion
- [ ] Tessen reports if a customer is approaching or has hit their total entity limit
- [ ] Tessen reports if a customer is approaching or has hit any of their entity class limits

## Possible Implementation
Clean up and utilize entity limiter headers (in sensu-enterprise-go) and report those metrics with Tessend.

## Context
https://docs.google.com/document/d/1lLphB_q2QE-sjhxd3EpQVW8AQiD4c17o5bjRJqR1Ymc/edit#

**Comment by nikkixdev** [comment]
I believe we have enough information in Tessen already to view this information. I need to verify if we can query the license contents (to get the entity limits and entity class limits) against the total entity count (broken down by entity class tags).

**Comment by nikkixdev** [comment]
After playing around in Grafana with our new Postgres data schema, I've determined the following implementation details would make the most sense to enable the desired information in Tessen:
- Display entity class limits and entity class counts in license metadata
  - https://github.com/sensu/sensu-enterprise-go/issues/1021 this is needed anyway for additional context around `sensuctl license info`
- Add license metadata to the Postgres metric tags in [Tessen](https://github.com/sensu/tessen/blob/13220f97af40fb0134275373d367e77f42434899/v2/psql/writer.go#L162-L176)
  - `"entity_class_agent_count": license.ObjectMeta.Labels["sensu.io/entity-class-agent-count"]`
  - `"entity_class_agent_limit": license.ObjectMeta.Labels["sensu.io/entity-class-agent-count"]`
  - `"entity_class_proxy_count": license.ObjectMeta.Labels["sensu.io/entity-class-agent-count"]`
  - `"entity_class_proxy_limit": license.ObjectMeta.Labels["sensu.io/entity-class-agent-count"]`
  - `"entity_limit": license.ObjectMeta.Labels["sensu.io/entity-class-agent-count"]`
  - `"entity_count": license.ObjectMeta.Labels["sensu.io/entity-class-agent-count"]`

**Comment by portertech** [comment]
@nikkixdev are the limit labels necessary if the data is already present in the license entity class limits map? Does duplicating the data make the implementation easier or experience better?

**Comment by portertech** [comment]
It does seem more convenient.

**Comment by nikkixdev** [comment]
Duplicating limit labels when the information is already available in the license does seem a little strange. I wonder if it was originally done like that so both labels are retrieved from the same [entity limiter interface](https://github.com/sensu/sensu-enterprise-go/blob/e4d70874e8d3820a69b217d681b9626f9fad835b/backend/apid/routers/license.go#L50-L51)? Entity count is necessary as a label however since that value will constantly change. https://github.com/sensu/sensu-enterprise-go/pull/967 makes me think it was for consistency.

Looks like Tessend sends the license info as a LicenseFile but Tessen interprets it as a License. We'll need to modify it to a LicenseFile in order to get the metadata.

**Comment by nikkixdev** [comment]
https://github.com/sensu/sensu-enterprise-go/pull/1035 will add all the necessary information to the license file (metadata). @echlebek do you think I could pair with you tomorrow on modifying some Tessen postgres queries?

**Comment by echlebek** [comment]
@nikkixdev certainly, happy to help.

**Comment by nikkixdev** [comment]
After a 🍐ing session with @echlebek and @portertech we decided upon a simpler path forward that would not require us to modify the `metadata` postgres table at this time. The following PRs address the desired behavior.
- https://github.com/sensu/sensu-go/pull/3757
- https://github.com/sensu/sensu-enterprise-go/pull/1041
- https://github.com/sensu/tessen/pull/17
