### ISSUE TITLE
Some field are not populated in the entity details

### ISSUE THREAD

**Issue by agm650** [sensu/sensu-go#3752]
## Expected Behavior
When looking at an entity details page in the Sensu Dashboard, I have fields "Cloud Provider", "VM System", "VM Role", "libc Implementation" or "Float Type". I would have expect for most of them to get values.

## Current Behavior
At the present time with Sensu Go 5.20 I have nothing in the mentioned fields.

Following a request from @palourde, I check the sensuctl entity info on some of my entities, and for most of the fields it's also empty, except for the libc part where I have glibc.

So I don't know how those fields get populated, but I would have expected some value at least in the libc field.

In addition, I don't know if it can have an impact, but I did an upgrade from 5.19 version for both agent and backend.

## Possible Solution

At least in my case (not sure if it's applicable for everyone) to resolve the "cloud provider" (VMware Esxi) a lookup on the mac address can be used. I have access to a libVirt environment too, and I will try the upgrade too and let you know of the result.

## Steps to Reproduce (for bugs)

1. Install Sensu Go Backend 5.20
2. Install Sensu Go Agent 5.20.0
3. Open the WebUI
4. Go to the namespace and open the detail of an entity, observe "Cloud Provider", "VM System", "VM Role", "libc Implementation" or "Float Type" fields

## Context

I attached the info of two entities.
[entities.yml.gz](https://github.com/sensu/sensu-go/files/4623929/entities.yml.gz)

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.): Packages
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7 (7.5 and 7.4) hosted on VMware ESXi

**Comment by agm650** [comment]
So I did some more test
With the docker image sensu/sensu-rhel:latest, fields "VM System" and "VM Role" are present in the dashboard with Docker/guest values. But still nothing for the libc field.
[docker_sensu-rhel.yaml.gz](https://github.com/sensu/sensu-go/files/4624076/docker_sensu-rhel.yaml.gz)

Same behavior with the sensu/sensu:latest image
[docker_sensu.yaml.gz](https://github.com/sensu/sensu-go/files/4624094/docker_sensu.yaml.gz)

**Comment by agm650** [comment]
Just another update on the topic...
The main issue is just linked to the libc field not being populated on the entity page when it's available in the entity information
The other field are probably not to be populated in my original case
"Cloud Provider", "VM System", "VM Role" => Only for docker or other system like that? Maybe not for hypervisor like ESXi?
"Float Type" => It's linked to the kind of CPU arch you have

**Comment by nikkixdev** [comment]
@agm650 Just to double check, the agent has `--detect-cloud-provider` enabled right?

**Comment by agm650** [comment]
Hello

I do not remeber for docker, so lets assume I didnt do it.
For the centos 7.4/7.5 I didn't used the `--detect-cloud-provider`, but instead I set up the following in the agent.yml:
```
discover-processes: true
detect-cloud-provider: true
```

I will redo all the test and archive agents configuration

**Comment by palourde** [comment]
Hi @agm650!

I was able to investigate a bit more and here's my findings:

- `Cloud Provider`: For the moment, we will only return whether the agent runs on EC2, GCP or Azure. Therefore, this field is expected to be empty in your case. We will better document that.
- I'd expect `VM System` & `VM Role` to be filled; Could you provide us the output of `cat /proc/modules` of a CentOS box running on ESXi?
- `libc`: We identified a bug in the Web UI, which will be fixed in 5.20.1. That being said, it should properly be filled if you look via `sensuctl entity info`; I was able to confirm using a CentOS 7.8 box.
- `Float Type` is a misleading attribute and will only be filled for the `mips` architecture, therefore we will remove it from the dashboard in 5.20.1 since it will be empty the vast majority of the time

**Comment by palourde** [comment]
Hello @agm650!

Just to let you know that 5.20.1 has just been released, which fixes a couple of issues around the process discovery and cloud detection. Please let us know if there's anything else!

Cheers

**Comment by agm650** [comment]
I've tested the new version (5.20.1) and it's good for me
Thx
