### ISSUE TITLE
info level log messages for API requests do not include authorized user

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3763]
## Expected Behavior

As an operator running sensu-backend, I can see which users are making API requests so that I can troubleshoot and report on user activity using service logs at `info` level.

## Current Behavior

All API requests are [logged at `info`](https://github.com/sensu/sensu-go/blob/c031fe6540d225ffb2f76f978d8509fda064e967/backend/apid/middlewares/logging.go#L35), but they do not include the name of the authorized user.

## Possible Solution

Add the user name to the request log message at info level.

## Context

Running at `debug` log level produces RBAC log entries useful for this purpose, but debug is too noisy for normal operation.

**Comment by nikkictl** [comment]
We should be able to retrieve the user from the jwt claims of the request!
