### ISSUE TITLE
Compilation with GCC's Go compiler

### ISSUE THREAD

**Issue by grepwood** [sensu/sensu-go#3764]
GCC has a Go compiler that can target more architectures than the reference compiler, Google Go. Is there a way to compile Sensu with GCC instead?

**Comment by echlebek** [comment]
`gccgo` can be used to build sensu-go, but it's likely that there will be spotty or missing support for more exotic architecture/os combinations. We have investigated building for some combinations not supported by `gc`, and there are some minor roadblocks in third-party libraries, and libraries in /x/. YMMV!

**Comment by echlebek** [comment]
Closing this issue as it would be better discussed in our discourse forum (https://discourse.sensu.io/)
