### ISSUE TITLE
Improve logging around TLS auth failures

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3771]
## Expected Behavior
When an agent tries to connect with mTLS, but gets a handshake error, there should be a log entry at some log level in the backend.

## Current Behavior
No obvious log message is emitted.

## Possible Solution
Improve mTLS connection instrumentation, add logging.

**Comment by portertech** [comment]
This needs further investigation. Once we have an idea of what's involved, we can point and execute on the necessary changes.

**Comment by nikkictl** [comment]
This is a funny problem. I can confirm that the backend is logging all TLS handshake errors it _receives_.
https://github.com/sensu/sensu-go/blob/05c24b47d3ff8648b4449f2ecb0eec698bdcc971/backend/agentd/agentd.go#L121
**Agent:**
```
{"component":"agent","error":"x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs","level":"error","msg":"reconnection attempt failed","time":"2020-06-18T11:36:36-04:00"}
```
**Backend:**
```
{"component":"agentd","level":"warning","msg":"http: TLS handshake error from 127.0.0.1:60071: remote error: tls: bad certificate","time":"2020-06-18T11:36:36-04:00"}
```

However, in some instances of misconfiguration on the agent, it appears that the client-side websocket request may not actually be getting through to the backend.

**Agent:**
```
{"component":"agent","error":"handshake failed with status 400: Client sent an HTTP request to an HTTPS server.\n","level":"error","msg":"reconnection attempt failed","time":"2020-06-18T11:37:50-04:00"}
```
**Backend:**
No relevant logs.

https://github.com/sensu/sensu-go/blob/05c24b47d3ff8648b4449f2ecb0eec698bdcc971/transport/client.go#L39
If the client detects an issue on dialup _before sending_ the handshake request, it would make sense that the client is allowed to short-circuit the error (ex. client attempting to contact the wrong server or server is not available).

I'm reading up on [RFC6455](https://tools.ietf.org/html/rfc6455) for more information on this, and will report back on my findings. All of the TLS negotiation happens at the [gorilla/websocket](https://www.gorillatoolkit.org/pkg/websocket) and [net/http](https://golang.org/pkg/net/http/) layer of the code and Sensu surfaces those errors accordingly. If for whatever reason there is a bug in either of those implementations with regard to RFC6455, we'll probably need to rework some things.

**Comment by nikkictl** [comment]
[Compared to other packages,](https://github.com/gorilla/websocket#gorilla-websocket-compared-with-other-packages) gorilla/websocket is actually more compliant with RFC6455.

In the handshake error I produced that does not get logged on the backend, the Origin header does not match the scheme and host of the connection URL. In this case, a 400 status code response is returned and the connection is rejected. The server does not produce this error or response, rather the client can determine _before_ pinging the server that it is not who it says it is. Perhaps the agent log is sufficient in this case.

**Comment by nikkictl** [comment]
ConnState in [http.Server](https://golang.org/pkg/net/http/#Server) appears that it could help us log additional errors before the connection is severed. Patch incoming.

**Agent:**
```
{"component":"agent","error":"handshake failed with status 400: Client sent an HTTP request to an HTTPS server.\n","level":"error","msg":"reconnection attempt failed","time":"2020-06-22T15:55:36-04:00"}
```
**Backend:**
```
{"component":"agentd","error":"tls: first record does not look like a TLS handshake","level":"error","msg":"websocket connection error","time":"2020-06-22T15:55:36-04:00"}
```
