### ISSUE TITLE
Need to get $HOSTNAME of sensu-agent using deregister handler, before going down.

### ISSUE THREAD

**Issue by akashkant-tech** [sensu/sensu-go#3773]
Expected Behavior
To get $HOSTNAME of a instance before going down and has a deregister handler associated to it. 

Current Behavior
Not able to get any details/information about that node/instance as soon as the node/instance go down. Deregister handler do gets executed but can not fetch any details of a node like its $hostname from it. Tried using Api calls and "event creation" using "registration" handler.

Any help to get the $HOSTNAME of stopped instance using deregister can help us execute tasks associated to that instance.

**Comment by echlebek** [comment]
By default, the agent name is the hostname, and the hostname is also captured in the entity system information. Your deregistration handler can parse this entity information, it's included in the event that's sent to the deregistration handler's standard in.
