### ISSUE TITLE
The issued attribute of an event should default to the current time

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3774]
When creating an event via the API, if you don't specify the issued attribute, it defaults to 0.

## Expected Behavior

issued should default to the current time.

## Current Behavior

issued defaults to 0.

## Steps to Reproduce (for bugs)

Run this on an agent:

```
curl -X POST \
-H 'Content-Type: application/json' \
-d '{
  "check": {
    "metadata": {
      "name": "test-check"
    },
    "status": 1,
    "output": "Test warning event"
  }
}' http://127.0.0.1:3031/events
```

## Context
Scripting some event creation and the events are showing as issued on Jan 1st. Means i've got to start retrieving the time and get it in the right format to supply, when it should just default to 'now' when the event is inserted by either the agent or backend.

## Your Environment
sensu 5.20.1-12427 on Debian.

**Comment by portertech** [comment]
Check issued is a field usually set by the scheduler. While it is a bit odd to set it outside of the context, I can see how it makes general scripting a little more challenging (i.e. need a conditional for `0`). I don't believe sensu/sensu set issued for API creation, but it did set it for keepalives and other internal checks (inconsistent).

**Comment by echlebek** [comment]
Users can cause the Issued field to be non-zero by specifying it in their request, and we don't know if setting it automatically will break someone else's workflow.
