### ISSUE TITLE
Ability to more effectively filter resolution events

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3785]
When creating filters, it's often quite easy to envisage the logic to the filter the events themselves. The problem (for me at least) is filtering of the resolution events.

You only want to send a resolution message if you sent an alert for the original issue.

The problem is, i've not come across a way of being able to tell, from the context of a filter on an event, whether an alert was previously sent for that event.

## Feature Suggestion

I'm not really sure of the best way to resolve that. Trying to describe what I want to know in words would be: whether there was previously an is_incident event for the current check/entity combo which was passed to the current handler which has not since had a resolution handled.

Or does anyone have a better suggestion or way of articulating it?!

## Context

I've had this dilemma a few times, but the one i've currently got is - if i've got an event, I want to add a check hook and filter based on the results of that hook to cut down the alerts I see through a particular handler.

The problem is though, i'll filter the alerts, but still get resolution alerts for events that were previously filtered out.

**Comment by echlebek** [comment]
It's possible that the check dependencies feature could help with this, but I don't think we can track alerts themselves.
