### ISSUE TITLE
Allow the event history amount to be configurable (or queryable!)

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3787]
Currently, events contain a history of the previous 21 events.

This appears to be hardcoded as i've not seen any mention of being able to configure it.

## Feature Suggestion

Allow that number of events to be configurable in the sensu-backend configuration file.

## Possible Implementation

I'm not familiar with etcd, but certainly with the PostgreSQL data store, it should be possible to easily pull out a lot of event history.

An alternate but more powerful suggestion would be to provide a mechanism to query event history from an event. That would be cool!

## Context

I might want to see further back than the last 21 events.

**Comment by echlebek** [comment]
The reason we store 21 events has to do with our flap detection algorithm, which is similar to Nagios'. Just wondering, what's your use case for having a larger number of history events?

Many of our users use a handler for storing events into a TSDB, have you checked out projects like https://github.com/sensu/sensu-influxdb-handler?
