### ISSUE TITLE
Allow the ability to delay resolution events.

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3789]
Currently, only the first !OK -> OK event is marked as a resolution event with `event.is_resolution` and allowed through `is_incident`.

## Feature Suggestion

I'd like to delay that resolution event - or put another way, make it so a resolution event only happens after x number of OK events.

## Possible Implementation

Have an attribute on a check or event that delays the is_resolution event (and therefore the  `is_incident` filter letting it through) until there has been a specified number of OK events.

## Context

So I can currently have a 'state change only' filter, like `(event.check.occurrences == 1)` - as is often documented. That's all good.

However, it gets more sticky when I have some checks which are probe to flapping (eg: ping checks, CPU, load etc). I want to filter them so it takes say 2 or 3 occurrences before an alert is sent - to make sure it's a genuine problem, not just a transient thing (and this is very effective at filtering those).

However, if I set: `(event.check.occurrences == 2)`, like you would think - then I don't get resolution messages. That's because by the time check.occurrences == 2, the event isn't let through `is_incident` because it's not a resolution event any more and `event.is_resolution` is false.

So then I end up with a much more complicated "only_after_2_events" filter, like this:

```
(event.check.occurrences == 2 || (event.is_resolution && event.check.occurrences_watermark >= 2))
```

That works, but apart from being more complex and harder to understand, what that still does is sends resolution messages on the first OK - so that can lead to flapping/alert spam.

For example, if I have:
`OK, WARNING, WARNING, WARNING, OK, WARNING, WARNING`
.. i'd get an alert, resolution, alert.

Whereas, what I really want is:
`OK, WARNING, WARNING, WARNING, OK, WARNING, WARNING, OK, OK`
... would only generate a single alert and final ok, if the filter was `event.check.occurrences == 2` but the resolution event was delayed until occurrences was 2.

**Comment by echlebek** [comment]
Have you tried changing the flapping threshold parameters?

https://docs.sensu.io/sensu-go/latest/reference/filters/

**Comment by echlebek** [comment]
Closing this, please re-open if the flapping threshold approach didn't work out!
