### ISSUE TITLE
backend falls back to plain text

### ISSUE THREAD

**Issue by trombik** [sensu/sensu-go#3791]
## Expected Behavior

when you enable TLS, you do not want to transfer anything in plain text. when configuration has errors, or logically invalid configuration, you do not want to fall back to plain text. thus, an application should refuse to run.

## Current Behavior

`sensu-go-backend` does not exit, but falls back to plain text.

## Possible Solution

Two options:

add `enable_tls_in_backend` configuration or something. if it's true, and the backend cannot successfully run TLS-enabled application, exit with error. do not fall back to plain text.

validate every TLS configuration flags, and exit with error if validations fail.

## Steps to Reproduce (for bugs)

1. set key-file for dashboard, but do not set cert-file.
2. run sensu-backend

## Context

the current implementation is like: "hey, you have invalid TLS configuration! you cannot enable TLS without certification file. but don't worry, i will run plain text version for you. no encryption is better than no service!".

here is an example:

https://github.com/sensu/sensu-go/blob/5c92b947125ee683661914fab3c5615182b16537/backend/backend.go#L433-L435

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.20.0
* Installation method (packages, binaries, docker etc.): my own package
* Operating System and version (e.g. Ubuntu 14.04): FreeBSD

**Comment by echlebek** [comment]
That's true, the TLS operating mode should be enabled if any TLS flag is enabled, not all TLS flags.
