### ISSUE TITLE
Use core/v3 EntityConfig in the scheduler entity cache

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3801]
Requires #3799

Once `core/v3.EntityState` is available, modify schedulerd's entity cache to use `core/v3.EntityConfig` instead of `core/v2.Entity`.

It should be a simple matter of just replacing core/v2.Entity with core/v3.Entity.

**Comment by nikkictl** [comment]
Although this is still blocked by in progress work, I'm going to start on this and rebase when a branch containing core/v3.Entity is made available.

**Comment by echlebek** [comment]
Hi, this is not blocked and work can be started on it, it just won't work end-to-end until the current entity store is replaced.

**Comment by nikkictl** [comment]
@echlebek yes I have already started work on this. I have a few questions about the current corev3 resources and the issue spec:
- Why change `ObjectMeta` to `Metadata` in corev3?
- Why is `Metadata` not embedded in `core/v3.EntityConfig` and `core/v3.EntityState` protos?
- Should the resource cache still work with corev3 resources? I'm getting the impression that corev3 resources do not conform to corev2 resource interfaces.
- Why is it only the entity cache in schedulerd that needs to be bumped to corev3, what about the other corev2 references?

**Comment by echlebek** [comment]
* Metadata is the name we give the structure in the JSON representation of core/v2 resources.
* Embedding the metadata as a non-pointer turned out to be undesirable. It's better to have a non-embedded pointer.
* The resource cache will not work with core/v3 resources. We have two options.
  - Create a new resource cache based on the old one for core/v3.
  - Use a conversion function to wrap EntityState into something that is a core/v2 resource. (See core/v3 resource.go)
* We can continue using core/v2 in most places. The reason we need to start using core/v3 in the entity cache is that we want to stop caching entity state, and cache only config.
