### ISSUE TITLE
Update keepalived to use core/v3.EntityState and core/v3.EntityConfig.

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3802]
Requires #3799

Update keepalived so that it uses `core/v3.EntityConfig` in the `dead` keepalive callback function. (`GetEntityByName` is used).

For calls to `UpdateEntity`, use `core/v3.EntityState`.

After the refactoring, keepalived `dead`, should only read from `core/v3.EntityConfig`, and `handleUpdate` should only write to `core/v3.EntityState`.

**Comment by amdprophet** [comment]
@echlebek I think that the `dead` method will need access to `core/v3.EntityState` in addition to `core/v3.EntityConfig`: https://github.com/sensu/sensu-go/blob/master/backend/keepalived/keepalived.go#L517

**Comment by echlebek** [comment]
@amdprophet I wonder if we should let the agent assert the `LastSeen` time?

**Comment by echlebek** [comment]
@amdprophet in terms of reading `LastSeen`, I think we can get the necessary information from `event.Entity.LastSeen`. Can you verify?
