### ISSUE TITLE
sensuctl env should refresh tokens as needed

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3815]
## Feature Suggestion

if tokens on disk have expired `sensuctl env` should automatically refresh them before printing to stdout 

## Context

In our docs and in practice, we use `eval $(sensuctl env)` to set $SENSU_ACCESS_TOKEN and other env vars useful for interacting with Sensu HTTP API via curl.

Access tokens expire every 15 minutes. This means that periodically the env vars need to be updated. Frequently we have to manually run `sensuctl entity list` or some other command to trigger refresh of access tokens before `sensuctl env` will generate updated output which can be used with curl.

**Comment by agoddard** [comment]
😍

**Comment by portertech** [comment]
We should consider uplifting API keys as the preferred approach to API interaction via curl. I believe API keys came after we started to use `sensuctl env` as a way to script against the API. For me, getting `sensuctl env` inline with the other commands in regards to token refresh when expired might make it worth it anyways.

**Comment by cwjohnston** [comment]
I think I am wrong about the current behavior. In my latest testing session I can see `sensuctl env` does generate a new access token on every invocation.

Not sure what I was seeing before, but as of sensuctl 5.19.0 this is no longer an issue.
