### ISSUE TITLE
Provide check output truncation for Nagios Perf Data

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#3824]
When using dual-purpose (check & metrics) checks with Nagios Perf Data, provide a check output truncation option to drop the Perf Data from the check output so it's not displayed in the WebUI, events output, or sent to handlers.

I had started work on using a mutator to do this, but that only affects what is sent to handlers.
## Feature Suggestion

It should be similar to the existing check attribute max_output_size and truncate_output. 

With this attribute the check output (for WebUI, `sensuctl event {list,info}`, and handlers) below:
```
CheckCPU OK: user=0.63% system=0.25% iowait=0.25% other=0.38% idle=98.50% | cpu_user=0.63%;80;90 cpu_system=0.25%;80;90 cpu_iowait=0.25%;80;90 cpu_other=0.38%;80;90 cpu_idle=98.50%
```
Becomes the more readable:
```
CheckCPU OK: user=0.63% system=0.25% iowait=0.25% other=0.38% idle=98.50%
```
## Possible Implementation

truncate_nagios_perfdata (or other similarly named attribute) being true would cause the Nagios PerfData (the | and everything right of it) to be removed from Check output for storage and sending to handlers.
## Context

The additional Nagios Perf Data included in check output can be mostly redundant and makes check output less readable.  Adding an option to strip it from check output will help in readability.

**Comment by portertech** [comment]
Currently a low priority.

**Comment by portertech** [comment]
Slapping a "won't fix" on this one. Love you.
