### ISSUE TITLE
Investigate rewriting build.sh & build.ps1 as Makefile

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#383]
To try and avoid maintaining two build scripts (one for windows, one for other platforms) we should look into using a single Makefile to do builds, testing, etc.

It appears that AppVeyor already has the `make` command pre-installed so this may be quite trivial.

**Comment by echlebek** [comment]
@amdprophet is this still on your bucket list?

**Comment by amdprophet** [comment]
I'll close this out. Our build scripts are going to get an overhaul as part of the upcoming CI work.
