### ISSUE TITLE
Allow accessing secrets from event filters

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3844]
Modify event filters to include secrets, the way checks do. The event filter protobuf type should be extended to include an array of strings specifying secrets, just like check request: https://github.com/sensu/sensu-go/blob/master/api/core/v2/check.proto#L38

When the filter is loaded and executed, the secrets should be retrieved and provided to the Javascript execution environment. The user should be provided with the following API, or equivalent:
```
var apiKey = Sensu.loadSecret("my_api_key");
```

**Comment by portertech** [comment]
Removing from the 6.0 milestone, as its not a hard requirement for the initial implementation of the filter store API. This remains an excellent future enhancement.
