### ISSUE TITLE
Sensuctl prune only works with single resource file

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#3845]
When using `sensuctl prune -f /path/to/resource/files` where files is a directory containing more than one file, *all* resources are deleted.
## Expected Behavior

It should behave the same as it does with a single file.
## Current Behavior

All resources are deleted.
## Steps to Reproduce (for bugs)

(In my testing, I used a separate user with admin privs and a non-default namespace with zero existing non-cluster resources)
```
git clone https://github.com/nixwiz/prune_demo.git
cd prune_demo
sensuctl create -r -f username
sensuctl dump checks,handlers,filters,mutators,secrets/v1.Secret,assets | wc -l (should be non-zero)
sensuctl prune checks,handlers,filters,mutators,secrets/v1.Secret,assets -r -f username
sensuctl dump checks,handlers,filters,mutators,secrets/v1.Secret,assets | wc -l (will now be zero)
```
To confirm it works with a single file:
```
sensuctl create  -r -f username
sensuctl dump checks,handlers,filters,mutators,secrets/v1.Secret,assets | wc -l (should be non-zero)
sensuctl dump checks,handlers,filters,mutators,secrets/v1.Secret,assets > resources.yaml
sensuctl prune checks,handlers,filters,mutators,secrets/v1.Secret,assets -f resources.yaml
sensuctl dump checks,handlers,filters,mutators,secrets/v1.Secret,assets | wc -l (should match the number from before)
```
## Context

Being able to point to the same set of resources as the create would be most beneficial when using in a CI/CD pipeline.  Workaround currently is to have job concatenate all resources prior to pruning.
## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):  5.20.1
* Installation method (packages, binaries, docker etc.):  packages
* Operating System and version (e.g. Ubuntu 14.04):  CentOS 7

**Comment by nikkictl** [comment]
Dupe of https://github.com/sensu/sensu-go/issues/3702?

**Comment by nixwiz** [comment]
Yes, closing.
