### ISSUE TITLE
Check silenced key is present only when event is silenced 

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3855]
## Expected Behavior

Each event with check data includes a `check.spec.silenced` key indicating any matching `silenced` entries.

## Current Behavior

Events with check data only include the `check.spec.silenced` key when one or more `silenced` entries match the event.

## Possible Solution

Default `check.spec.silenced` to an empty array, such that the `silenced` key will always be present. An event is considered silenced when the array value has a length greater than zero.

## Context

> Explicit is better than implicit.

Sensu 1.x provided a `silenced` attribute with true/false which was easy for event consumers to act on, explicitly indicating whether or not the event was silenced.

The current implementation is implicit, leaving event consumers to infer that the event was not silenced due to the lack of a `silenced` key in the event data. 

Using an empty array to indicate "no matching silenced entries" makes the event state more explicit, without going the extent of adding a new attribute with a boolean value.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by portertech** [comment]
We would have to introduce a new/separate field, `check.spec.is_silenced`, a boolean. This would not break the existing feature implementation. We need to investigate existing use of `is_silenced` property.

**Comment by portertech** [comment]
- Create field in protobuf
- Set JSON field to "is_silenced"
- Set "is_silenced" in eventd

**Comment by portertech** [comment]
* Add field
* Add setting for field
* Add tests
* Fix existing tests
* Release minor version of the core/v2 module

**Comment by calebhailey** [comment]
Looks like the PR is ready to go here. 👍 

https://github.com/sensu/sensu-go/pull/3927 

🎉
