### ISSUE TITLE
Concurrent map write bug

### ISSUE THREAD

**Issue by jtopjian** [sensu/sensu-go#3861]
Hello,

I maintain the [Sensu Terraform Provider](https://github.com/jtopjian/terraform-provider-sensu) and I've recently run into a race issue with a concurrent map write.

I think the bug is being triggered [here](https://github.com/sensu/sensu-go/commit/21a71bb23c8b0d3392003dba4e2d05a994d27b05#diff-956571bc126deb997197601bf096aa96).

I ran into this when attempting to add support for Bonsai-based assets. This required a vendor/module update, which pulled in the latest commits from the past few months. Historically, the Terraform Provider has built with no issues, but upon updating the Sensu library, Travis immediately began erroring. Oddly enough, I can only reproduce this 10% of the time on my local workstation, but it is reproducible. 

The following Travis logs have the full trace. I apologize for the size of the logs:

* https://travis-ci.org/github/jtopjian/terraform-provider-sensu/builds/702224932#L11832
* https://travis-ci.org/github/jtopjian/terraform-provider-sensu/builds/702190582#L13341
* https://travis-ci.org/github/jtopjian/terraform-provider-sensu/jobs/702187739#L11722
* https://travis-ci.org/github/jtopjian/terraform-provider-sensu/builds/702224938#L14684
* https://travis-ci.org/github/jtopjian/terraform-provider-sensu/jobs/702185588#L15124

They're all pointing to the `c.SetHeader()` call identified in the above commit.

I could be completely wrong with my assessment. Please let me know if I can provide any additional information or if I can help troubleshoot in any way.

## Expected Behavior

Concurrent usage of the client should be safe.

## Current Behavior

There's a race condition happening with the client.

## Possible Solution

Locking the client before writing the header?

## Steps to Reproduce (for bugs)

You can run the acceptance test suite of the Terraform Provider. The Travis file should outline how it's run, but let me know if you have any questions.

I haven't looked into writing a reproducible test case outside of Terraform.

## Your Environment

* Sensu version used: master for the client library, 5.21.0 for the backend
* Installation method (packages, binaries, docker etc.): Docker
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 18.04

**Comment by echlebek** [comment]
How annoying! I'm displeased with the resty client and want to remove it from our codebase, but it would be a pretty big job as it's tightly coupled with the CLI.

Thanks for the bug report, we'll definitely look into it.

**Comment by jtopjian** [comment]
@echlebek Thanks for looking into this 🙂 

I have a question: is there a reason the [User-Agent](https://github.com/sensu/sensu-go/blob/41a04e39d367741d49805eb2dea0f58a1f483c84/cli/client/client.go#L54) header was added to the `OnBeforeRequest` method? 

I think the reason why the concurrent map write is happening is because if there are multiple client requests happening, a `SetHeader` is going to be happening at multiple times. Could this header be added to the general setup of the client instead ([here](https://github.com/sensu/sensu-go/blob/41a04e39d367741d49805eb2dea0f58a1f483c84/cli/client/client.go#L50))?

I can look at testing this myself, but before I did, wanted to know if there was a specific reason for this header to be in `OnBeforeRequest`.

**Comment by echlebek** [comment]
Hello, I don't know of any specific reason that the header would be set in `OnBeforeRequest`, other than it being a possible place to do it. It could be done elsewhere.

It's unclear to me why state would be shared for headers between requests. I wonder if you have discovered a bug in go-resty?

In any case, it seems like it could be alleviated in the way you descfibe. If you would like to make a PR we would be happy to receive it!

**Comment by jtopjian** [comment]
>  I wonder if you have discovered a bug in go-resty?

It's possible, yes. At least specific to Terraform, a client is created once (as the [provider](https://github.com/jtopjian/terraform-provider-sensu#terraform-configuration-example) and then shared between multiple resources (eg checks, assets, etc). The resources are managed concurrently when possible (a check and asset will be created in parallel if they are not related).

My theory is that since a single client is created, there is never an issue of concurrent map writes, so adding the User-Agent string outside of `OnBeforeREquest` _should_ be fine. 

But yeah, I think there's a larger issue where resty isn't properly locking at all when setting headers - just an assumption, though.

> In any case, it seems like it could be alleviated in the way you descfibe. If you would like to make a PR we would be happy to receive it!

Sure, will do!

**Comment by echlebek** [comment]
I'll close this issue with the presumption it's resolved, please re-open if you observe the problem moving forward!

**Comment by jtopjian** [comment]
Oh, sorry - I should have closed this. All looks good. Thank you for your help 🙂
