### ISSUE TITLE
shutting down scheduler issue

### ISSUE THREAD

**Issue by JacquesDunoyer** [sensu/sensu-go#3862]
Hello,

We are using sensu-go oss in order to monitor our infrastructure.
For now, we have 3 backend in cluster mode with 2 poller in round-robin.

We are exclusivly using sensugo to monitor blackboxes via SNMP, with proxy-entity.

Right now, we have 10 000 entities.

ETCD's buffer and worker have been increased to 1600.

Each server (Backend / Poller) is working with 8GB RAM and 8 vCPUs.

Every entity is being polled by a sensu-go agent every 5min.

## Expected Behavior

Whenever we add a new entity to the monitoring system (API request or sensuctl), 
it should keep polling other entities, and add this one to the next run on requests

## Current Behavior

Whenever we add a new entity to the monitoring system (API request or sensuctl), we are facing an issue where :
- Every run of polling gets delayed for 5 minutes (as if the run was ignored), on every entities
- Backend log a new warning :

```json
{"component":"schedulerd","level":"warning","msg":"shutting down scheduler","name":"lab_device_polling","namespace":"default","scheduler_type":"round-robin interval","time":"2020-06-24T17:20:16+02:00"}
```

- Without a device creation :
    Polling 1 (time t) - Polling 2 (t + 5min) - Polling 3 (t + 10min) 

- With a device creation :
    - Should be :
        Polling 1 (time t) - Create device - Polling 2 (t + 5min) - Polling 3 (t + 10min)

    - But this happens :
        Polling 1 (time t) - Create device = "Shutting down scheduler" - No Polling 2 (t + 5min) - Polling 3 (t + 10min)

## Possible Solution

No idea, we just don't have the problem when we are not using a clustered sensu infrastructure.

## Steps to Reproduce (for bugs)

1. Deploy 3 Backend in cluster-mode, with internal built-in ETCD
2. Deploy 2 or more sensu-agent (as poller)
3. Create a round-robin, proxy check with interval of 300s
4. Create the first entity with sensuctl and a yaml file
5. Wait for 2 or 3 polling to occur 
6. Add an other entity with sensuctl and a yaml file
7. You might have the error message, in the backend log file, immediatly
8. The next polling that should be run within 300s, will not be trigger

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.20.0 for all
* Installation method (packages, binaries, docker etc.): OSS from Github
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04

**Comment by portertech** [comment]
@echlebek please explain why this is the behaviour when using a clustered deployment.

**Comment by echlebek** [comment]
The scheduling behaviour is the same no matter the cluster size (1, 3, 5, ...).

It seems that adding entities to the pool of executors disrupts the scheduler and it restarts. I think we can consider that a bug. It's not immediately clear to me why this happens.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/handler-not-triggered-automatically-but-can-triggered-manually/1999/7

**Comment by portertech** [comment]
We were not able to reproduce the issue :( We have recently discovered a few issues/constraints in regards to the etcd backed round-robin scheduler, for more details please read https://github.com/sensu/sensu-go/issues/4013#issuecomment-788240470
