### ISSUE TITLE
Re-work entity cache

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3871]
Now that entity configuration is updated much less frequently, our caching strategy can change to reflect it.

Currently, we are reading the entire corpus of entities from etcd every 5 seconds. This produces stable performance under load when there are a lot of entity writes, but is probably overkill when there are very few.

Additionally, 5 seconds can be a long time to get the newest entity configuration. We can do better.

Re-work the entity cache to use watchers instead of polling. Now that entity configuration writes are infrequent, the watch events will be as well, reducing the amount of work needed to do caching.

The cache should use a two-layer `sync.Map` and store entities along with their synthesized version by namespace.

```
cache
  |_ namespace
        |_ entities by name
```

The cache should function the same as before from the perspective of callers. It should deliver sorted slices when requested, just as before. With `sync.Map`, the entities will be stored unsorted, but we can simply sort them after pulling them out of the cache.

The new entity cache should support the new backend entity management pattern of sending entity updates to agents. To do this, it will send entity updates to wizard bus, so that agentd can forward the message along to agents. The cache should called `messaging.TopicEntityConfig()` in order to get the name of the topic to send `*corev3.EntityConfig` messages.

**Comment by portertech** [comment]
Removing from 6.0. We are going to shelve this one for now. We are building a separate entity modification notification mechanism. See https://github.com/sensu/sensu-go/issues/3881.
