### ISSUE TITLE
Update keepalived registration handler to publish registered entity

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3872]
Keepalived receives agent registration events, whenever an agent connects. This handler is useful for hooking agent registration.

We can extend the registration handler to send the agent entity to wizard bus, when the agent connects for the first time. This enables the initialization part of backend entity management.

The logic, in psuedo-code, is as follows:
```
if err := UpdateEntityConfig(e); err == nil {
  PublishEntityConfig(e)
} else if err == store.ErrAlreadyExists {
  e = GetEntityConfig(e.Name)
  PublishEntityConfig(e)
} else {
  return err
}
```

When an agent connects, it sends its "local" entity configuration. The backend will create this configuration if it does not already exist, and then keepalived will publish the entity to wizard bus.

If the entity already exists, then keepalived will read the entity and send it to wizard bus instead.

**Comment by nikkictl** [comment]
@echlebek I have a few clarifying questions about the spec:

> Keepalived receives agent registration events, whenever an agent connects. This handler is useful for hooking agent registration.

Doesn't Keepalived _create_ agent registration events whenever an agent connects and sends it to `TopicEvent`:
https://github.com/sensu/sensu-go/blob/c3914d6787dccd0c68a729bb9dc835c0952f557a/backend/keepalived/keepalived.go#L358

> We can extend the registration handler to send the agent entity to wizard bus, when the agent connects for the first time. This enables the initialization part of backend entity management.

Extend the registration handler to send the agent entity to `TopicEntityConfig`?

> The logic, in psuedo-code, is as follows:
```
if err := UpdateEntityConfig(e); err == nil {
  PublishEntityConfig(e)
} else if err == store.ErrAlreadyExists {
  e = GetEntityConfig(e.Name)
  PublishEntityConfig(e)
} else {
  return err
}
```
Why would `UpdateEntity` return an error if the entity already exists? Rather, wouldn't it error if the entity does not exist?

> When an agent connects, it sends its "local" entity configuration. The backend will create this configuration if it does not already exist, and then keepalived will publish the entity to wizard bus.

Publish to `TopicEvent`?

> If the entity already exists, then keepalived will read the entity and send it to wizard bus instead.

Publish to `TopicEntityConfig`?

Based on my initial understanding of the spec, I drafted something like below but I'm not quite sure how to verify the functionality. Let me know if I'm totally off here.
```
fetchedEntity, err := k.store.GetEntityByName(tctx, entity.Name)

if err != nil {
    // Warning: do not wrap this error
    return err
}

if fetchedEntity == nil {
    event := createRegistrationEvent(entity)
    err = k.bus.Publish(messaging.TopicEvent, event)
} else {
    err = k.bus.Publish(messaging.TopicEntityConfig, fetchedEntity)
}

return err
```

**Comment by echlebek** [comment]
> Doesn't Keepalived create agent registration events whenever an agent connects and sends it to TopicEvent:
In this case I was referring to the keepalive event sent and being consumed by https://github.com/sensu/sensu-go/blob/master/backend/keepalived/keepalived.go#L244. It's probably more accurate to say that keepalived _brokers_ registration.

> Extend the registration handler to send the agent entity to TopicEntityConfig?
It should be sent to the topic specific to the entity in question, so that the appropriate agent session receives it.

> Why would UpdateEntity return an error if the entity already exists? Rather, wouldn't it error if the entity does not exist?
The intent is that you would use `storev2.CreateIfNotExists` here.

> Publish to TopicEvent?
No, nothing new should be getting published to TopicEvent.

> Publish to TopicEntityConfig?
Use https://github.com/sensu/sensu-go/blob/master/backend/messaging/message_bus.go#L92 to compute the correct topic for a given entity.

The general idea is that you try to create the entity as part of registration, using `storev2.CreateIfNotExists`. If you get an error saying it already exists, then you read the entity and publish it to the bus so that the agent session can pick it up and send it to the agent.

It's important to attempt to create the entity before you read it, as the information could potentially become stale between the two calls in a flaky network situation.
