### ISSUE TITLE
Display silence reason in dashboard

### ISSUE THREAD

**Issue by nicolasbrechet** [sensu/sensu-go#3882]
In the Sensu dashboard, under "Silences", one can easily see the silenced checks, as well as the silence expiration. However, the reason of the silence requires the user to hover on the "silencer" name (which is not intuitive), and then on the horizontal accordion icon to finally see the reason.

## Feature Suggestion

It would be very useful to display the reason alongside the expiration, so that you can see what was silenced, when it expires, and also why it was silenced, all in one go.

## Possible Implementation

Sorry, at this point I'm not (yet) up to date on how the dashboard works... 

Maybe something like : 
![reason](https://user-images.githubusercontent.com/1842586/86467360-8cb7e600-bd35-11ea-9d2d-f4cffaf57061.png)

## Context

In my context, I have several checks silenced, some of them linked to the same incident, and when checking what checks have been silenced because of incident XYZ, it is very annoying to click through each silence entry just to see the reason

**Comment by meni2029** [comment]
I agree with the proposal.

I would also suggest to add the info (Silence _Expiration_ and _Reason_) in the Events view, when we mouse-hover the Silence icon.
It would look something like this example :
![image](https://user-images.githubusercontent.com/56351431/86475443-f7245280-bd44-11ea-8491-8b1fc0b458af.png)

**Comment by agm650** [comment]
I still think this would be a nice enhancement!

**Comment by calebhailey** [comment]
This has been fixed in the commercial distribution of Sensu and will be released in version 6.3.0 :+1:
