### ISSUE TITLE
sensuctl asset add return output should include a usage example

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3885]
`sensuctl asset add` return output should include a usage example. Current output includes "added asset: org/name" which is informative but doesn't help the Sensu Go user put the newly registered asset to use.

![Screenshot from 2020-07-06 14-03-35](https://user-images.githubusercontent.com/149630/86643972-f9c7b780-bf91-11ea-8479-86a1010c6a6c.png)

## Feature Suggestion
Update the `sensuctl asset add` sub command to return a helpful message after successfully registering the asset with the Sensu Go backend API. For example:

```
added asset: org/name
you can now use this as a runtime asset for the appropriate resource (e.g. for a check, runtime_assets: ["org/name"]).
```
Words and formatting are important, this likely needs to be refined.

## Context
Help new Sensu Go users understand how assets work. This enhancement along with future documentation changes should improve the getting started experience for more users. As someone who goes off the rails when playing with new technology, I would welcome more "connective tissue" to help guide me, providing hints etc.

Related Reddit thread: https://www.reddit.com/r/sysadmin/comments/hl2xiu/is_sensu_go_broken_or_am_i_incompetent/

**Comment by portertech** [comment]
We should also consider including some words to make it clear that the Sensu Go agent and backend fetch and unpack the runtime assets on demand (not when the assets are registered or referenced in resources).

**Comment by nikkictl** [comment]
@portertech WDYT?

```
$ sensuctl asset add sensu/monitoring-plugins:2.2.0-1
fetching bonsai asset: sensu/monitoring-plugins:2.2.0-1
added asset: sensu/monitoring-plugins:2.2.0-1
help usage:

You have successfully added the Sensu asset resource, but the asset will not get downloaded until
it's invoked by another Sensu resource (ex. check). To add this runtime asset to the appropriate
resource, populate the "runtime_assets" field with ["sensu/monitoring-plugins"].
```
