### ISSUE TITLE
sensu-backend upgrade should support bypassing confirmation

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3900]
## Feature Suggestion

There should be a flag like `--no-confirm` for `sensu-backend upgrade` with Sensu Go 6.x

## Possible Implementation

Add `--no-confirm` to `sensu-backend upgrade`.

## Context

I am working with @ghoneycutt to integrate the sensu-puppet module with Sensu Go 6.0 changes and we will need to write some automation around `sensu-backend upgrade`. The automation will be a Bolt talk to allow users to run the upgrade command using tools for Puppet around ad-hoc commands.  In order to semi-automate the process there can not be any prompts for user input, and right now it appears like there is no way to bypass the upgrade confirmation.

**Comment by treydock** [comment]
FWIW there is a somewhat ugly work around of sending the response via stdin, but still think `--no-confirm` is a good idea
```
[root@sensu-backend ~]# echo "true" | sensu-backend upgrade
? Do you really want to upgrade your Sensu 5.x database to 6.x? This operation cannot be undone; make sure you back up your database! true
{"component":"store","level":"warning","msg":"migrating etcd database to a new version","time":"2020-07-11T15:07:50Z"}
{"component":"store","database_version":1,"level":"info","msg":"successfully upgraded database","time":"2020-07-11T15:07:50Z"}
{"component":"store","database_version":2,"level":"info","msg":"successfully upgraded database","time":"2020-07-11T15:07:50Z"}
```

**Comment by nikkictl** [comment]
FWIW `--skip-confirm`  aligns with other sensuctl commands.

**Comment by echlebek** [comment]
Let's go with `--skip-confirm` as Nikki suggests.
