### ISSUE TITLE
Add filter or option to dashboard to hide silenced checks

### ISSUE THREAD

**Issue by mxpgmbh** [sensu/sensu-go#3902]
## Feature Suggestion
see title

## Possible Implementation
- Add an filter to the home dashboard to hide silenced checks
or
- Add an option to define whether the silensed checks should be shown in the dashboard or not.

## Context
we also use sensu to monitor server updates.
If updates are available, warnings are displayed that can be ignored in principle because they are automatically applied at night by a hook.
The dashboard shows warnings that are actually just information. It is then not important for us to see them on the dashboard and block the overview with real problems.
It also doesn't look very nice if 60 incidents are shown in the dashboard of 62 servers, 55 of which are just the information about upcoming and planned updates.

**Comment by portertech** [comment]
This is already a commercial feature, available in the supported packages since 5.19.0.
