### ISSUE TITLE
sensuctl should return status 2  when help message is shown due to malformed command error

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#3912]
## Current Behavior
Badly formed sensuctl commands return help and status 0
Example:
```
$ sensuctl check > /dev/null; echo $?
0
```

## Expected Behavior
Should return status 2 in these situations where help output displayed without being explicitly requested due to malform command.

**Comment by nikkictl** [comment]
Great find @jspaleta, this is definitely a bug and we should return an error exit status if any sensuctl command fails.

**Comment by amdprophet** [comment]
Closed by #4119.
