### ISSUE TITLE
Add support for .NET Core in Docker image

### ISSUE THREAD

**Issue by goorallab** [sensu/sensu-go#3917]
## Add support for .NET Core in Docker image
NET Core is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems. It is a cross-platform successor to .NET Framework.
Sensu product would benefit from adding out-of-the box support for [.NET Core self-contained applications](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#self-contained-deployment).

.NET Core self-contained applications can be compiled into [single binary](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#single-file-executables) (similarly to GOLang binaries), and do not require installing full .NET Core runtime, which makes them perfect match for sensu. 

This would allow developers that come form Windows/.NET background to write assets for Handlers, Filters and Mutators in programming language familiar to them (i.e. C#).
This would also potentially open door, for developers, familiar with Microsoft products and ecosystem (like Office365, Azure, Microsoft Teams) to write their own assets for bonsai.

## Possible Implementation
To allow .net core self-contained applications to be run on Alpine distribution, [following libraries](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies) have to be installed:
- icu-libs
- krb5-libs
- libgcc
- libintl
- libssl1.1 (Alpine v3.9 or greater)
- libssl1.0 (Alpine v3.8 or lower)
- libstdc++
- zlib

To achieve this, following line in `Dockerfile` would add those libraries to image:
```docker
RUN apk add icu-libs krb5-libs libgcc libintl libssl1.0 libstdc++ zlib
```

To allow .net core self-contained applications to be run on RHEL distribution, [following libraries](https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine#dependencies) have to be installed:
- krb5-libs
- libicu
- openssl-libs

To achieve this, following line in `Dockerfile` would add those libraries to image:
```docker
RUN yum install krb5-libs libicu openssl-libs -y
```

## Context
Currently to allow using .NET Core self-published applications in sensu backed, it's required to create your own image, by adding dependencies:
```docker
FROM sensu/sensu:5.21.0

RUN apk add icu-libs krb5-libs libgcc libintl libssl1.0 libstdc++ zlib
```
Which takes away from official image flexibility.

**Comment by echlebek** [comment]
We feel that it's more important to keep the official image small. Please use the technique you described! Thanks for creating the issue.
