### ISSUE TITLE
Ephemeral agent uses stale config

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3919]
## Expected Behavior
An ephemeral agent (`deregister: true`) is able to modify its config via the local agent configuration file.

## Current Behavior
An ephemeral agent (`deregister: true`) is not able to modify its config via the local agent configuration file and uses a stale config.

## Possible Solution
Investigate agent sessions/deregistration with new backend entity management feature.

## Steps to Reproduce (for bugs)
https://sensuinc.testrail.io/index.php?/cases/view/23003

## Context
https://sensuinc.testrail.io/index.php?/cases/view/23003

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/b906a5bf0ec35e88d2296986b5c3da93dbeaeff7
* Installation method (packages, binaries, docker etc.): binaries 
* Operating System and version (e.g. Ubuntu 14.04): MacOS Catalina

**Comment by palourde** [comment]
@nikkictl I'm gonna go ahead and close this issue, in favor of https://github.com/sensu/sensu-go/issues/3919.

As discussed, the tricky part here is that we need to wait for the keepalive mechanism to deregister the entity before restarting the agent.
