### ISSUE TITLE
Linter does not show file names or line numbers

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3926]
## Expected Behavior
The golang-ci linter should show each failure in the file and line number it was encountered at.

## Current Behavior
The linter simply reports failure, leaving the user to hunt for the lint themselves.

## Possible Solution
???

![linter](https://user-images.githubusercontent.com/1633772/87860879-d7209180-c8f5-11ea-809f-7795918cc4c1.png)

**Comment by nikkictl** [comment]
Okay, looks like if you go to the github actions tab for the run, it will print out the line number responsible for the lint error. The log should definitely have that in there regardless, but thought I would share this workaround in the meantime.

<img width="1009" alt="Screen Shot 2020-07-20 at 11 08 10 AM" src="https://user-images.githubusercontent.com/10634078/87954415-58089600-ca7a-11ea-9c04-1c6556b9f084.png">

**Comment by nikkictl** [comment]
If you read [golangci-lint-action](https://github.com/golangci/golangci-lint-action#comments-and-annotations), they mention that lint failures are shown as annotations. These annotations are listed in the high level breakdown of the golangci-lint github action (see previous comment), and also displayed in [commits](https://github.com/sensu/sensu-go/commit/70797da0a9402a0832ad62c68151bf9373fe0f52#annotation_308516645) and code reviews (see file comparison below).

<img width="982" alt="Screen Shot 2020-07-20 at 2 05 22 PM" src="https://user-images.githubusercontent.com/10634078/87970680-12f05e00-ca92-11ea-9055-b6ca1471d6f0.png">

While the UX is a little counterintuitive, there isn't anything we can do from our CI to resolve this. https://github.com/golangci/golangci-lint-action/issues/5 exists to create code review comments for lint issues, but has not yet been implemented.

I'm going to close out this issue, but use https://github.com/sensu/sensu-go/pull/3928 to bump the dependencies to the most current.
