### ISSUE TITLE
Sensuctl command exec output goes to stderr

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#3935]
## Expected Behavior 
```
$ sensuctl command install runbook nikkictl/sensu-runbook
no version specified, using latest: 0.0.5
fetching bonsai asset: nikkictl/sensu-runbook:0.0.5

$ sensuctl command exec runbook -- --command true --subscriptions misc --id runbook-1 > stdout 2>stderr
$ cat stdout 
time="2020-07-21T14:39:28-04:00" level=info msg="asset includes builds, using builds instead of asset" asset=sensu-runbook component=asset-manager entity=sensuctl
2020/07/21 14:39:28 registering runbook job ID default/runbook-1 with --command true
2020/07/21 14:39:28 registered runbook Job "runbook-1"
2020/07/21 14:39:28 requested runbook Job "runbook-1" execution on subscriptions: misc
$ cat stderr 
```

## Current Behavior
```
$ sensuctl command install runbook nikkictl/sensu-runbook
no version specified, using latest: 0.0.5
fetching bonsai asset: nikkictl/sensu-runbook:0.0.5

$ sensuctl command exec runbook -- --command true --subscriptions misc --id runbook-1 > stdout 2>stderr
$ cat stdout 
$ cat stderr 
time="2020-07-21T14:39:28-04:00" level=info msg="asset includes builds, using builds instead of asset" asset=sensu-runbook component=asset-manager entity=sensuctl
2020/07/21 14:39:28 registering runbook job ID default/runbook-1 with --command true
2020/07/21 14:39:28 registered runbook Job "runbook-1"
2020/07/21 14:39:28 requested runbook Job "runbook-1" execution on subscriptions: misc
```

## Possible Solution
Investigate command exec and golang exec mechanics.

## Steps to Reproduce (for bugs)
1. `sensuctl command install runbook nikkictl/sensu-runbook`
2. `sensuctl command exec runbook -- --command true --subscriptions misc --id runbook > stdout 2>stderr`
3. `cat stdout` (observe empty)
4. `cat stderr` (observe output)

## Context
Output of a successful command should go to stdout.

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): https://github.com/sensu/sensu-go/commit/ec65b9ffcd0a2b40727dde13f2023c2950102d93
* Installation method (packages, binaries, docker etc.): binaries
* Operating System and version (e.g. Ubuntu 14.04): MacOS Catalina

**Comment by ccressent** [comment]
The real "issue" here is that those plugins log to `stderr`. `sensuctl command exec` output goes to whatever the plugin decides.

We used to combine `stderr` and `stdout` and output everything to `stdout`. That's why their output was showing on `stdout`, as a side effect. This was silly because that breaks using the shell's `|` operator with those commands.

**Comment by nikkictl** [comment]
@ccressent `log.Printf` outputs to `stderr`? That doesn't seem right..

**Comment by nikkictl** [comment]
I think there is some cleaning up that needs to happen in the plugin regardless to ensure a consistent exit status/output.

**Comment by ccressent** [comment]
> @ccressent `log.Printf` outputs to `stderr`? That doesn't seem right..

https://golang.org/pkg/log/
> [...] has a predefined 'standard' Logger accessible through helper functions Print[f|ln], Fatal[f|ln], and Panic[f|ln], which are easier to use than creating a Logger manually. That logger writes to standard error [...]

**Comment by nikkictl** [comment]
Huh.. I guess we could just use `log.SetOutput(os.Stdout)` in the plugin then. I'll close this out in that case!
