### ISSUE TITLE
[CLI] Ability to view summaries of alerts in different long vs short formats

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#395]
From GoDaddy feedback discussion: https://docs.google.com/document/d/1XfyQwlpsSVT7onW3C5B9yppt2Zs2ZIhyO-9lrasYQGo.

Re: CLI improvements.

Matt:
> One example was the ability to view summaries of alerts in different long vs short formats (similar to the many git log options). 
> 
> I could see inspiration coming from git and github's work with `hub` along with incorporating the helpful behavior of sensu-wrapper.
>
> https://github.com/github/hub
> https://github.com/jaxxstorm/sensu-wrapper

**Comment by palourde** [comment]
Closing that for now, I believe the tabular output format addresses this concern!
