### ISSUE TITLE
Avoid setting etcd.Config values with backend.Config values when nil/empty

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#3952]
## Expected Behavior
The defaults that etcd sets should be used unless an override is specifically set by Sensu.

## Current Behavior
Sensu always overrides the default values of `etcd.Config` when `NewEtcd()` is called: https://github.com/sensu/sensu-go/blob/v5.21.0/backend/etcd/etcd.go#L156.

## Possible Solution
Add conditionals to check if Sensu config values are not nil or empty.

**Comment by portertech** [comment]
Cyril to open up a PR this week.
