### ISSUE TITLE
Build for new ARM-based macOS

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#3954]
## Feature Suggestion

Creating this issue to track support for the new ARM-based macOS.

### Tasks
- [x] Wait for Go to add support (targeted for Go 1.16)
- [x] Add support to dependencies (gopsutil and possibly others)

Both @jamesdphillips and myself have access to Apple Developer Transition Kits for porting & testing.

**Comment by amdprophet** [comment]
I've got both sensuctl and sensu-agent running natively on `darwin/arm64`. I was able to build them by using a patched Go 1.14.6 and by adding the appropriate files to gopsutil.

![Screen Shot 2020-07-31 at 1 07 25 AM](https://user-images.githubusercontent.com/120659/89014318-3a34ff80-d2ca-11ea-81b6-784976230780.png)

**Comment by amdprophet** [comment]
I opened https://github.com/shirou/gopsutil/pull/917 to add support for `darwin/arm64` in gopsutil.

**Comment by nikkictl** [comment]
This will be blocked until the aforementioned PR is merged and Go 1.16 is released. But we should definitely do this :)

**Comment by amdprophet** [comment]
This is shipping with 6.4.0.
