### ISSUE TITLE
Sensu Go 6 unable to query redacted labels via API or sensuctl

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#3955]
## Expected Behavior

I'd expect there to be some kind of ability to query the value of a label or annotation if it's in the redacted list.

## Current Behavior

Currently all redacted labels and annotations come back as `REDACTED` when queried as `admin` and this makes Puppet management of these values impossible.

## Possible Solution

Allow `admin` to query redacted labels and annotations or add a optional flag to expose redacted values.

## Steps to Reproduce (for bugs)

```
[root@sensu-backend ~]# cat entity.json 
{
  "type": "Entity",
  "api_version": "core/v2",
  "spec": {
    "entity_class": "agent",
    "subscriptions": null,
    "deregister": false,
    "deregistration": {},
    "user": "agent",
    "redact": [
      "password",
      "passwd",
      "pass",
      "api_key",
      "api_token",
      "access_key",
      "secret_key",
      "private_key",
      "secret",
      "foo"
    ]
  },
  "metadata": {
    "name": "sensu-backend.example.com",
    "namespace": "default",
    "labels": {
      "foo": "bar"
    },
    "annotations": {
      "contacts": "test"
    }
  }
}
[root@sensu-backend ~]# sensuctl create -f entity.json 
[root@sensu-backend ~]# sensuctl entity info sensu-backend.example.com --format json | jq .metadata.labels
{
  "foo": "REDACTED",
  "sensu.io/managed_by": "sensuctl"
}
```

## Context

I am working with @ghoneycutt on the Puppet module for Sensu Go and need the ability to query label values and annotations regardless of if they are redacted. Not having access to the value makes managing state with Puppet impossible.  Because agent labels and annotations have to be managed via API in Sensu Go 6, this is even more important that the values be available by some means.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): `sensu-backend version 6.0.0+ee, enterprise edition, build f66f07ec84f8aeb367113c2cf01bc35fa9647739, built 2020-07-23T22:16:26Z, built with go1.14.6`
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by calebhailey** [comment]
This seems like the desired behavior IMO. I can see how this might be a challenge from a CM perspective, but I wonder if the right solution here is to document this as a known limitation / caveat, and/or modify the Puppet module to apply changes via a multi-step edit/verify/redact process?

For example: 

1. Add a label "foo" to the entity resource 
2. Create the entity resource 
3. Get the entity resource and verify that the label was added
4. Modify the entity resource to add "foo" as a redacted field
5. Get the modified entity resource to verify that the "foo" field is included in the "redact" list, and that the "foo" label is now returning "REDACTED"

I don't think it's a good idea to build-in exceptions to the redaction logic in Sensu, as it's more likely to create unintended side effects. Redaction should mean redaction. 

Thoughts?

**Comment by treydock** [comment]
That's now how Puppet works...you don't do things in stages or in parts, you manage the state of the system and getting `REDACTED` means the state is not going to match the Puppet catalog.  The only Puppet way to handle this is to just assume if the value is `REDACTED` no update is needed and only apply changes to an entity if a non-redacted value changes but that is horrible and not how Puppet should be doing things.  Before Sensu Go 6 we managed these things in `agent.yml` and that was the source of truth, managed by Puppet. Now by having to modify entities via API, there will no longer be a source of truth for redacted values when dealing with Puppet environments and that is very bad.  Setting a value and not being able to then query that set value is very unfriendly to any configuration management system, but especially ones like Puppet that operate on state of the entire system. 

If you remove Puppet from the equation, how does an admin check if the redacted value of a label or annotation is correct?  How does `sensuctl dump` reconcile dumping redacted values for purposes of backing up configs?  There are going to be more places than just Puppet that this behavior could cause problems.

**Comment by ghoneycutt** [comment]
I would encourage Sensu to implement set and get for its data access model. If you can set data, then you should also be able to get the data. You might need to be admin to do, but some user is capable of this. You wouldn't take notes in invisible ink. As Operations, we will want that capability to ensure data is what we believe it to be. As Security, we want to verify data to check if we are in compliance. While it certainly affects Puppet, it will have similar repercussions not just for tooling but for the admins themselves. @calebhailey @portertech

**Comment by treydock** [comment]
Is there a way to modify just a single label via API? What we do right now in Puppet is download entire JSON for entity , modify single label then re-upload that modified JSON. But because some values are redacted, they get overwritten with the literal value `REDACTED` rather than their actual value.  If there is not a way for API to change just a single label or annotation than this limitation will make it impossible for Puppet to support Sensu Go 6.  The way Puppet works if if you define 10 labels, those are 10 distinct resources that do not necessarily know the value of each other, they are applied independently, Puppet does not gather up all labels and apply them at once, that's not how Puppet is designed. So either we need a way to see the real value of a REDACTED label or annotation or there needs to be a way with API to modify just single label or annotation.

@portertech

**Comment by treydock** [comment]
I think only way we could support Sensu Go 6 with Puppet and modify individual labels and annotations is by reading the values from `agent.yml` which is really not a great design.  There is no other way for Puppet to re-upload the JSON back to backend with the real value when other resources are involved since PUppet operates on individual things and not all labels at once.

**Comment by treydock** [comment]
This is what things look like in Puppet at this time:

```
  sensu_agent_entity_config { 'annotations key contacts on sensu-agent.example.org in dev':
    ensure => 'present',
    value  => 'dev@example.com',
  }
  sensu_agent_entity_config { 'annotations key foo on sensu-agent.example.org in dev':
    ensure => 'present',
    value  => 'var',
  }
```

If either of those is redacted the other will not know the value of each other, Puppet doesn't share values of resources between resources, they are designed to manage their own state and that is all.  Thought might help to see how this is being designed in Puppet.  These individual annotations were suppposed to be sort of "injected" into agent entity via API but like I've described, that does not work with redacted values in the JSON.

**Comment by treydock** [comment]
To clarify, what Puppet is struggling to support is updating agent entity via API now that agent.yml is only for bootstrap. There is no safe way to update entity settings if there are redacted values in labels or annotations. If there is a way to update individual labels or annotations via API, that would solve the problem, or if there was a way to see redacted values. Hopefully the issue is clear, if not let me know and I'll try to clarify further.

**Comment by calebhailey** [comment]
Thanks for the additional context, @treydock - and thanks for your comments, @ghoneycutt - much appreciated. 

We do have plans to add support for a PATCH API, which might allow you to write individual entity labels (or make other individual field updates) and get an HTTP response code back to indicate success or failure. This is currently not prioritized so I don't have a release date, but I'm curious if you have experience using Puppet with other such PATCH APIs, and if so what is your general assessment of that approach? 

Thanks again! ✌️

**Comment by treydock** [comment]
I think a PATCH API to inject an individual entity configs would work.  The API would have to support all entity config options that have moved from getting updates via agent.yml to getting updates via API so labels, annotations, subscriptions, redact, and likely others.  I think I've managed to come up with Puppet tricks to work around the fact there is no way to see REDACTED values, but those tricks will only work once there is some way to update individual entity config items like via some PATCH API.

The structure of data sent to API via PATCH from Puppet perspective would only be able to supply key (in case of hash), value, entity name and namespace of entity.  I could expand to include more data if needed but right now that seemed like minimal amount of data needed to update entity configs.

**Comment by portertech** [comment]
I believe we need to add HTTP 304 "NOT MODIFIED" support to the backend API.

**Comment by treydock** [comment]
A return code might not help Puppet because we'd have to apply changes to know if changes are needed and that's not a good design for Puppet. For Puppet there is a "query" step to dump all resources and then those resources are compared with the catalog and changes are made when the state of the system doesn't match the catalog.  Having to make a change to check if changes are needed won't work with the place in Puppet code where the "query" is executed. For performance resources there is a single query for all resources of the same type and so at that stage it has no access to the catalog of what should be configured.  The single query is in a class method, not instance method and instance methods are the only things that have access to the site configured properties of a given resource.

**Comment by portertech** [comment]
Sensu Engineering is conducting a [spike on API resource HTTP PATCH support](https://github.com/sensu/sensu-go/issues/3986).
