### ISSUE TITLE
Potential collision and risk from indirect dependence "github.com/jbenet/go-reuseport"

### ISSUE THREAD

**Issue by KateGo520** [sensu/sensu-go#3970]
## Dependency line:

github.com/sensu/sensu-go --> [github.com/atlassian/gostatsd](https://github.com/sensu/sensu-go/blob/master/go.mod#L17) --> [github.com/jbenet/go-reuseport](https://github.com/sensu/sensu-go/blob/master/go.mod#L48)

github.com/atlassian/gostatsd af79662  -->  github.com/jbenet/go-reuseport 7b4e9d2 (2017.10.10)
https://github.com/atlassian/gostatsd/blob/af796620006e1d43fa05a44ec8ad77ed8154d7e1/glide.lock
```
- name: github.com/jbenet/go-reuseport
  version: 7b4e9d23b569c604ed9be4439a2e9ada26774b4f 
```

## Background
Repo `atlassian/gostatsd` used the old path to import `go-reuseport`， and didn’t use module in the commit af79662:
https://github.com/atlassian/gostatsd/blob/af796620006e1d43fa05a44ec8ad77ed8154d7e1/glide.lock#L66 
```
- name: github.com/jbenet/go-reuseport
  version: 7b4e9d23b569c604ed9be4439a2e9ada26774b4f 
```
This caused that `github.com/libp2p/go-reuseport` and `github.com/jbenet/go-reuseport` coexist in this repo：
https://github.com/sensu/sensu-go/blob/master/go.mod （Line 48 & 49）
```
github.com/jbenet/go-reuseport v0.0.0-20180416043609-15a1cd37f050 // indirect
github.com/libp2p/go-reuseport v0.0.0-20180416043609-15a1cd37f050 // indirect 
```

That’s because the `go-reuseport` has already renamed it’s import path from "github.com/jbenet/go-reuseport" to "github.com/libp2p/go-reuseport"，in this commit 15a1cd37f050. When you use the old path "github.com/jbenet/go-reuseport" to import the `go-reuseport`, will reintroduces `go-reuseport` through the import statements "import github.com/libp2p/go-reuseport" in the go source file of `go-reuseport`.

https://github.com/libp2p/go-reuseport/blob/15a1cd37f0502f3b2eccb6d71a7958edda314633/test/main.go#L10
```
package main
import (
	…
	resolve "github.com/jbenet/go-net-resolve-addr"
	reuse "github.com/libp2p/go-reuseport"
)
```

"github.com/libp2p/go-reuseport" and "github.com/jbenet/go-reuseport" are the same repos. This will work in isolation, bring about potential risks and problems. 

## Solution
1. Add replace statement in the go.mod file:
```
replace github.com/jbenet/go-reuseport => github.com/libp2p/go-reuseport 15a1cd3
```
Then clean the dependencies.
2. Update the direct dependency [github.com/atlassian/gostatsd](https://github.com/sensu/sensu-go/blob/master/go.mod#L17). This problem does not exist in the new version in the new version of `github.com/atlassian/gostatsd`.

**Comment by KateGo520** [comment]
@echlebek  @palourde  Could you help me review this issue? Thx :p

**Comment by amdprophet** [comment]
@KateGo520 Thank you for taking the time to open this issue. Can you elaborate on how this issue is affecting you?

**Comment by KateGo520** [comment]
@amdprophet  Thank you for your reply! The following is my opinion:
1. The "github.com/jbenet/go-reuseport" has been redirected to "github.com/libp2p/go-reuseport". The `libp2p/go-reuseport` already declared it's module path to `"github.com/libp2p/go-reuseport"`.
https://github.com/libp2p/go-reuseport/blob/master/go.mod#L1
```
module github.com/libp2p/go-reuseport
```
So I think it seems a little dangerous to keep the old import path in the go.mod file. It is easy to cause this error when updating dependencies.
```
go get: github.com/jbenet/go-reuseport@v0.0.2: parsing go.mod:
        module declares its path as: github.com/libp2p/go-reuseport
                but was required as: github.com/jbenet/go-reuseport
```

2."github.com/libp2p/go-reuseport" and "github.com/jbenet/go-reuseport" are the same repos. Importing a repo through two different import paths does not make sense.This will work in isolation, bring about potential risks and problems.

**Comment by echlebek** [comment]
So what problem has the current state of things caused you?

**Comment by KateGo520** [comment]
@echlebek  It's just a suggestion to prevent potential problems

**Comment by portertech** [comment]
Thanks for the suggestion! We are planning to replace the gostatsd library with our own implementation altogether. This won't be a concern for much longer.
