### ISSUE TITLE
Backend API calls may remove per-entity subscription

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3980]
## Expected Behavior

Per-entity subscriptions (e.g. `entity:i-424242`) are always available on any given entity.

## Current Behavior

When updating entity subscriptions via the /entities API, a given agent’s per-entity subscription will be removed if it is not explicitly included in the API payload.

## Possible Solution

* Prevent the removal of per-entity subscriptions via the API
* Automatically re-add per-entity subscriptions when processing updates received via the API

## Steps to Reproduce (for bugs)

With an existing 6.0 backend and agent 

1. sensuctl entity info agent --format yaml > agent.yml
2. Manually edit agent.yml to remove `entity:agent` subscription
3. sensuctl create -f agent.yml
4. Inspect output of sensuctl entity info agent --format yaml and see that the per-entity subscription is removed
5. Restart sensu-agent all you like, the entity subscription is not recreated

## Context

Per-entity subscriptions are something of a special case, as they are automatically added by the agent in addition to any explicitly configured subscriptions. Although allowing their removal via the API could be considered desirable for maximum flexibility, the absence of these subscriptions makes it effectively impossible to silence one or more checks from a particular entity where they’ve been removed.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.0.0
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by nikkictl** [comment]
Closed by https://github.com/sensu/sensu-go/pull/3991
