### ISSUE TITLE
Spike: Investigate API resource PATCH support

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#3986]
Investigate what we would need to do to enable API resource HTTP `PATCH` and `304 Not Modified` support. Enable users to edit resources with partials.

MDN web docs on HTTP PATCH: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH

Assigned engineer to document their findings on this issue.

**Comment by echlebek** [comment]
Proposal documents:

304 for HTTP PUT: https://docs.google.com/document/d/1s5rmoeJBBtqjCtXdmwiX73dN_rZURVw5DzSOPasvlhM/edit
HTTP PATCH: https://docs.google.com/document/d/1IH-SdBDMN77Xx6OQlLW0kdEF6h8fCX6snw-fn3ypFVw/edit#heading=h.letafivq6wet
