### ISSUE TITLE
Sensu Go Clustering and etcd performance

### ISSUE THREAD

**Issue by LordGr1m** [sensu/sensu-go#3996]
Hello Sensu Go Team,

Planning to migrate from sensu core to sensu go here. 
Not sure where to ask these questions, As my company is a not for profit company and we, therefore, need to keep costs low.

1.   Building from open source will override the sensu-backend free 100 entities limit?

2. Does the etcd performance is enough for sensu cluster with 2,500-3,000 agents?

3. Etcd max database size limit is 8-10GB.  Is it sufficient for this number of agents?  PostgresSQL is only available to commercial versions only?

Thank you!

**Comment by palourde** [comment]
Hi @LordGr1m,

We would like to invite you to open a discussion on [discourse.sensu.io](https://discourse.sensu.io/) as it is a better forum for sharing knowledge than Github issues.

Thanks
