### ISSUE TITLE
Race condition in JS VM cache locking causes panic

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#3997]
There is a race condition in the JS VM creation/disposal logic that results in a runtime panic.

## Expected Behavior
No panic.

## Current Behavior
```
fatal error: sync: unlock of unlocked mutex

goroutine 20 [running]:
runtime.throw(0xf9ddcb, 0x1e)
        /scratch/tl/go/src/runtime/panic.go:1116 +0x72 fp=0xc0001da8e0 sp=0xc0001da8b0 pc=0x4368c2
sync.throw(0xf9ddcb, 0x1e)
        /scratch/tl/go/src/runtime/panic.go:1102 +0x35 fp=0xc0001da900 sp=0xc0001da8e0 pc=0x436845
sync.(*Mutex).unlockSlow(0xc00035b888, 0xffffffff)
        /scratch/tl/go/src/sync/mutex.go:196 +0xd6 fp=0xc0001da928 sp=0xc0001da900 pc=0x475246
sync.(*Mutex).Unlock(...)
        /scratch/tl/go/src/sync/mutex.go:190
github.com/sensu/sensu-go/js.(*vmCache).Dispose(0xc00011ae70, 0xf84c66, 0x3)
        /home/tl/src/go/src/github.com/sensu/sensu-go/js/vm_cache.go:98 +0xa3 fp=0xc0001da978 sp=0xc0001da928 pc=0xc7bf93
github.com/sensu/sensu-go/js.releaseOttoVM(0x11112e0, 0xc000111fc0)
        /home/tl/src/go/src/github.com/sensu/sensu-go/js/js.go:95 +0x5a fp=0xc0001da9f8 sp=0xc0001da978 pc=0xc7aa0a
github.com/sensu/sensu-go/js.WithOttoVM(0x11112e0, 0xc000111fc0, 0xc0001daae0, 0x0, 0x0)
        /home/tl/src/go/src/github.com/sensu/sensu-go/js/js.go:188 +0xdf fp=0xc0001daa50 sp=0xc0001da9f8 pc=0xc7b39f
github.com/sensu/sensu-go/backend/pipeline.(*FilterExecutionEnvironment).Eval(0xc0001dadb0, 0x111de40, 0xc00011ae40, 0xf8564a, 0x4, 0x203000, 0xc00014a000, 0xc00013c6e0)
        /home/tl/src/go/src/github.com/sensu/sensu-go/backend/pipeline/js.go:50 +0x29e fp=0xc0001dac40 sp=0xc0001daa50 pc=0xd68d9e
github.com/sensu/sensu-go/backend/pipeline.(*Pipeline).evaluateEventFilter(0xc000114f50, 0x111de40, 0xc00011a660, 0xc000158000, 0xc00010e8f0, 0xc000118048, 0x1, 0x1, 0x1)
        /home/tl/src/go/src/github.com/sensu/sensu-go/backend/pipeline/filter.go:76 +0x333 fp=0xc0001db070 sp=0xc0001dac40 pc=0xd62073
github.com/sensu/sensu-go/backend/pipeline.(*Pipeline).FilterEvent(0xc000114f50, 0xc0000dbe38, 0xc000158000, 0x0, 0x0, 0x0, 0x0)
        /home/tl/src/go/src/github.com/sensu/sensu-go/backend/pipeline/filter.go:172 +0x780 fp=0xc0001db930 sp=0xc0001db070 pc=0xd633f0
github.com/sensu/sensu-go/backend/pipeline.TestPipelineNoPanicOnAssetKeyChange.func1(0xc00012c900)
        /home/tl/src/go/src/github.com/sensu/sensu-go/backend/pipeline/filter_test.go:483 +0x999 fp=0xc0001dbf80 sp=0xc0001db930 pc=0xd752e9
testing.tRunner(0xc00012c900, 0xc000110b60)
        /scratch/tl/go/src/testing/testing.go:991 +0xdc fp=0xc0001dbfd0 sp=0xc0001dbf80 pc=0x510f9c
runtime.goexit()
        /scratch/tl/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001dbfd8 sp=0xc0001dbfd0 pc=0x468ae1
created by testing.(*T).Run
        /scratch/tl/go/src/testing/testing.go:1042 +0x357

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00012c7e0, 0xfa2f67, 0x23, 0xfc8810, 0x491801)
        /scratch/tl/go/src/testing/testing.go:1043 +0x37e
testing.runTests.func1(0xc00012c6c0)
        /scratch/tl/go/src/testing/testing.go:1284 +0x78
testing.tRunner(0xc00012c6c0, 0xc0001dfe10)
        /scratch/tl/go/src/testing/testing.go:991 +0xdc
testing.runTests(0xc000110b20, 0x189cc20, 0x13, 0x13, 0x0)
        /scratch/tl/go/src/testing/testing.go:1282 +0x2a7
testing.(*M).Run(0xc00011e080, 0x0)
        /scratch/tl/go/src/testing/testing.go:1199 +0x15f
main.main()
        _testmain.go:80 +0x135

goroutine 19 [chan receive]:
testing.(*T).Run(0xc00012c900, 0xf94a0c, 0x16, 0xc000110b60, 0xc00010e708)
        /scratch/tl/go/src/testing/testing.go:1043 +0x37e
github.com/sensu/sensu-go/backend/pipeline.TestPipelineNoPanicOnAssetKeyChange(0xc00012c7e0)
        /home/tl/src/go/src/github.com/sensu/sensu-go/backend/pipeline/filter_test.go:428 +0x586
testing.tRunner(0xc00012c7e0, 0xfc8810)
        /scratch/tl/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
        /scratch/tl/go/src/testing/testing.go:1042 +0x357

goroutine 22 [select]:
github.com/sensu/sensu-go/js.(*vmCache).reapLoop(0xc00011ae70)
        /home/tl/src/go/src/github.com/sensu/sensu-go/js/vm_cache.go:50 +0x115
created by github.com/sensu/sensu-go/js.newVMCache
        /home/tl/src/go/src/github.com/sensu/sensu-go/js/vm_cache.go:37 +0x8d
```

This happened to us a number of times in production, however I was unable to reproduce it in a running cluster anywhere else.

The specific scenario we found triggered it pretty reliably was overwriting an existing asset definition with a new hash. Our production environment processes a couple of thousand events per minute and all our filters are done using statements defined in a single Javascript asset.

This is where the panic originates, specifically the `Dispose` function: https://github.com/sensu/sensu-go/blob/2950446717205f0c5b90b37e8cfaf4e9b1f9dfa3/js/vm_cache.go#L72-L94

## Possible Solution
A basic fix might be to only call `asset.RuntimeAssetSet.Keys()` once at VM init, and use the returned string val for later disposal instead of re-calling `Keys()`. The race seems to occur when the underlying slice changes, resulting in `Keys()` returning a different value.

Specifically, this function should maybe pass a key instead of deriving it from the mutable `RuntimeAssetSet`. The race condition seems to exist due to the assumed immutability of this underlying `RuntimeAssetSet`.

https://github.com/sensu/sensu-go/blob/2950446717205f0c5b90b37e8cfaf4e9b1f9dfa3/js/js.go#L169-L177

There might be a more robust way to use some stdlib `sync` primitives to make this safer though. 

## Steps to Reproduce (for bugs)
See the new unit test in the attached patch file: [unit_test.patch.txt](https://github.com/sensu/sensu-go/files/5185861/unit_test.patch.txt)

It applies cleanly on `master` (tested against `dd02b042`). Run that specific test and should see the following:
```
$ go test -v ./backend/pipeline -run TestPipelineNoPanicOnAssetKeyChange
=== RUN   TestPipelineNoPanicOnAssetKeyChange
=== RUN   TestPipelineNoPanicOnAssetKeyChange/asset_key_changed_deny
newOttoVM assets: [0xc00011a4e0]
newOttoVM key: foo
releaseOttoVM assets: [0xc00011a4e0]
releaseOttoVM key: bar
fatal error: sync: unlock of unlocked mutex

goroutine 20 [running]:
runtime.throw(0xf9ddcb, 0x1e)
        /scratch/tl/go/src/runtime/panic.go:1116 +0x72 fp=0xc0001da8e0 sp=0xc0001da8b0 pc=0x4368c2
sync.throw(0xf9ddcb, 0x1e)
        /scratch/tl/go/src/runtime/panic.go:1102 +0x35 fp=0xc0001da900 sp=0xc0001da8e0 pc=0x436845
sync.(*Mutex).unlockSlow(0xc00035b888, 0xffffffff)
        /scratch/tl/go/src/sync/mutex.go:196 +0xd6 fp=0xc0001da928 sp=0xc0001da900 pc=0x475246
sync.(*Mutex).Unlock(...)
```

You can see here (in the debug print outputs) that the sleeps in the test case successfully change the asset key that `ottoCache.Dispose()` is using to dispose, simulating a `PUT` to the filter definition during filter execution, which is what seemed to be triggering this for us in production.

The race condition appears to exist between these two lines: https://github.com/sensu/sensu-go/blob/2950446717205f0c5b90b37e8cfaf4e9b1f9dfa3/js/js.go#L71-L72

To try and simplify the timeline for what I think is happening (and hence what the unit test attempts to emulate):
1. filter with asset list `["foo"]` and `RuntimeAssetSet.Key() == "hash1"` begins executing (call this `filter1`)
2. new otto VM is initialized and stored in `sync.Map` with key `"hash1"`
3. underlying asset list changes due to a PUT or something else. I am not sure why or how exactly this happens.
4. filter with asset list `["foo"]` and (different) `RuntimeAssetSet.Key() == "hash2"` begins executing (call this `filter2`)
5. `filter1` acquires the mutex using the key `hash1` as it was computed and stored in a variable before the underlying asset list changed
6. `filter1` attempts to release the mutex it acquired, but upon calling `RuntimeAssetSet.Key()` it gets `hash2`, which has not been locked by any goroutine yet

Step 4 is the most important part in recreating the race I think. Before I added the `HasKey` method to the `vmCache` object the two test cases resulted in a deadlock instead of a panic, presumably because the first test case acquired and never released the `hash1` key (failing silently on the release because of the missing `sync.Map` value), and the second test case deadlocked attempting to also acquire a lock on the `hash1` key.

## Context
Panics in prod are not fun :(

## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): can reproduce on current master.

**Comment by roganartu** [comment]
cc @echlebek (and I pinged you in slack too, as requested)

**Comment by Surian** [comment]
We are facing this bug which is preventing us to upgrade to 6.0.0. :(

Our CI pipeline (a clean backend with no agent connected) randomly fails when updating assets and the backend logs are reporting the same kind of panic.
