### ISSUE TITLE
HTTP PATCH

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#3998]
See [the proposal](https://docs.google.com/document/d/1IH-SdBDMN77Xx6OQlLW0kdEF6h8fCX6snw-fn3ypFVw/)

We must support PATCH requests, with an optional ETAG.

- [x] Implement a _Patcher_, probably based on https://github.com/evanphx/json-patch.
- [x] Add a Patch method to the core/v2 generic store
- [x] Add a Patch method to the generic handler
- [ ] Add support for PATCH to all configuration resources
- [x] Support the `Content-Type: application/merge-patch+json` header and fallback to this value; return an error if another value is passed for now (we might want to support `application/json-patch+json` or other strategies later)
- [x] Add a free-standing Etag() function to the store package
- [x] Set the Etag header for all GET requests in APId that resolve an individual resource.

**Comment by portertech** [comment]
We need to guard resource name and namespace alteration. A user should not be able to change the resource name and namespace with PATCH.

**Comment by palourde** [comment]
Test cases:

- A label can be added
- An array is replaced
- Boolean/integer values not specified in the patch are not overridden with the default value
- An etag is returned on 200 OK
- A 204 No Content is returned when no modification has been performed
- Etags are returned for all GET requests
- A namespace cannot be altered
- A resource name cannot be altered
- A 412 Precondition Failed is returned if the etag in If-Match does not match the stored resource

**Comment by palourde** [comment]
Resources to test:

- [ ] apikeys
- [ ] checks
- [ ] clusterrolebindings
- [ ] clusterroles
- [ ] filters
- [ ] hooks
- [ ] mutators
- [ ] namespaces
- [ ] rolebindings
- [ ] roles

Resources to implement
- [ ] entities
- [ ] silenced
- [ ] users
