### ISSUE TITLE
Check status uses the wrong datatype

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4000]
## Expected Behavior
Check status is a signed integer.

## Current Behavior
Check status is an unsigned integer. This causes havoc when using the postgres store, if the status is larger than 2^31-1, as the postgres store correctly assumes that status will be a 32 bit signed integer.

## Possible Solution
It is possible to simply change the unsigned integer to a signed integer in the protobuf definition. This is explicitly said in the docs: https://developers.google.com/protocol-buffers/docs/overview

> int32, uint32, int64, uint64, and bool are all compatible – this means you can change a field from one of these types to another without breaking forwards- or backwards-compatibility. If a number is parsed from the wire which doesn't fit in the corresponding type, you will get the same effect as if you had cast the number to that type in C++ (e.g. if a 64-bit number is read as an int32, it will be truncated to 32 bits).

## Context
Users of the postgres store can get errors when events with very large statuses are sent to sensu-backend.

**Comment by palourde** [comment]
We need to schedule a meeting to have a proper discussion about that!

**Comment by portertech** [comment]
Call scheduled tomorrow.

**Comment by portertech** [comment]
Getting a sensu-enterprise-go issue.

**Comment by portertech** [comment]
Closed by https://github.com/sensu/sensu-enterprise-go/pull/1276
