### ISSUE TITLE
sensuctl user hash-password should not require a valid sensuctl configuration

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4003]
The `sensuctl user hash-password` utility is very useful for generating bcrypt password hashes. In some contexts, a user might want to leverage this utility when a sensu-backend API is not available (e.g. as part of a CI/CD pipeline). 

## Feature Suggestion

Running `sensuctl user hash-password` prior to configuring sensuctl returns an error: 

```
Error: Unable to locate credentials. You can configure credentials by running "sensuctl configure"
```

## Possible Implementation

Don't validate sensuctl configuration when running the `sensuctl user hash-password` command? 

## Context

Auto-generating RBAC profiles for training users in the [sensu-go-workshop](https://github.com/sensu/sensu-go-workshop) project. 🙂

**Comment by palourde** [comment]
We should do the same thing for `sensuctl login oidc`

**Comment by portertech** [comment]
Let's scope this to `hash-password` only for now.
