### ISSUE TITLE
libc6-compat is missing in sensu/sensu:latest docker image

### ISSUE THREAD

**Issue by pandaatrail** [sensu/sensu-go#4009]
## Presentation
When using official Docker image, this is an Alpine linux version.
This version lacks libc6-compat which is not installed by default, and this leads to errors when using assets like sensu-plugins-disk-checks for example.

## Expected Behavior
The official image should embed libc6-compat so that community assets work out of the box, without the need to manually install a dependency, or worse, to maintain a custom docker image based on official layer.

## Current Behavior
The current behavior is: the libc6-compat package is missing, and this leads to execution errors in ruby-based community assets like sensu-plugins-disk-checks, which tells us a require has failed because of missing libcrypt.so.

## Possible Solution
Rebuild official image adding libc6-compat package in Alpine images.

## Steps to Reproduce (for bugs)
1. use `docker run ...` to start a sensu-agent
2. add an asset from sensuctl
3. go to the web UI and/or use docker logs on the newly created sensu-agent
4. witness the fact that libcrypt is missing

## Your Environment
* Centos 8
* Docker version 19.03.12, build 48a66213fe
* sensu/sensu:latest

**Comment by ccressent** [comment]
Thank you for bringing this to our attention @pandaatrail!

You mention [sensu-plugins-disk-checks](https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-disk-checks) being one of the assets affected; do you know of others?

**Comment by jspaleta** [comment]
Hello @pandaatrail ,

I think perhaps you are a little confused with regard to how the Ruby based Sensu assets work.

The asset for sensu-plugins-disk-checks is built against the ruby environment provided by the sensu-ruby-runtime asset, and expects the sensu-ruby-runtime asset to be available when check commands are called. The sensu-ruby-runtime provides a ruby environment and several support libraries (including libcrypto). On Alpine, the sensu-ruby-runtime provides a libcrypto library linked against musl as per Alpine best practices, so there's normally no need for libc compatibility. 

Based on what you wrote, it sounds like you are not using the sensu-ruby-runtime asset in your check definition. But based on the information I have, I can't be sure. If you are using the sensu-plugins-disk-checks asset without the sensu-ruby-runtime asset on other platforms, you've just gotten a little lucky so far and just happened to have a working ruby environment already provided by the host OS. But the intended and tested way to use the sensu-plugins-disk-checks asset is in conjunction with the sensu-ruby-runtime asset.

Maybe the Overview section in the README for sensu-plugins-disk-checks repository isn't as clear as it should be on the role sensu-ruby-runtime plays in making sure the Ruby based plugins work as assets.

We have an effort underway to communicate some best practices configurations for a lot of the common monitoring workloads, using Sensu assets when they are available at https://github.com/sensu-community/monitoring-checks

For example take a look at:
https://github.com/sensu-community/monitoring-checks/blob/master/system/linux/disk/check-disk-usage.yaml

This configuration yaml above has a disk check example making use of both assets.

**Comment by pandaatrail** [comment]
Hi @ccressent and @jspaleta,

Thanks a lot for your answers.

@jspaleta I totally admit that, as completely new to sensu, and often without enough time to read every doc page at work, I may have misunderstood some of the key concepts behind the ruby shared lib.

Here is what I did:

- used a docker-compose file to deploy a backend, and a ctl services, separately
- installed assets, and amongst them was shared lib ruby runtime
- used docker run to deploy some agents here and there on servers
- when deploying the agents, using sensu/sensu or sensu/sensu-based custom docker image (in which I simply added libc6-compat), I can see the build are  installed as they match the scope definitions

Here is what happens in details (I should have probably provided more details in the first message, sorry for that):

The asset in installed in agents, as we can see:

```json
{"asset":"sensu-ruby","component":"asset-manager","entity":"testtesttesttest","filter":["entity.system.os == 'linux'","entity.system.arch == 'amd64'","entity.system.platform == 'alpine'","entity.system.platform_version.split('.')[0] == '3'"],"level":"debug","msg":"entity filtered, installing asset build","time":"2020-09-17T09:20:47Z"}
```

And instantly, I can see in the backend an error popping:

```
/var/lib/sensu/8d768d1fba545898a8d09dca603457eb0018ec6829bc5f609a1ea51a2be0c4b2d13e1aa46139ecbb04873449e4c76f463f0bdfbaf2107caf37ab1c8db87d5250/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': Error loading shared library libcrypt.so.1: No such file or directory (needed by /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/ffi-1.13.0/lib/ffi_c.so) - /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/ffi-1.13.0/lib/ffi_c.so (LoadError)
	from /var/lib/sensu/8d768d1fba545898a8d09dca603457eb0018ec6829bc5f609a1ea51a2be0c4b2d13e1aa46139ecbb04873449e4c76f463f0bdfbaf2107caf37ab1c8db87d5250/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/ffi-1.13.0/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/ffi-1.13.0/lib/ffi.rb:3:in `<top (required)>'
	from /var/lib/sensu/8d768d1fba545898a8d09dca603457eb0018ec6829bc5f609a1ea51a2be0c4b2d13e1aa46139ecbb04873449e4c76f463f0bdfbaf2107caf37ab1c8db87d5250/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/sensu/8d768d1fba545898a8d09dca603457eb0018ec6829bc5f609a1ea51a2be0c4b2d13e1aa46139ecbb04873449e4c76f463f0bdfbaf2107caf37ab1c8db87d5250/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/sys-filesystem-1.3.4/lib/sys/unix/sys/filesystem/structs.rb:1:in `<top (required)>'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/sys-filesystem-1.3.4/lib/sys/unix/sys/filesystem.rb:2:in `require_relative'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/sys-filesystem-1.3.4/lib/sys/unix/sys/filesystem.rb:2:in `<top (required)>'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/sys-filesystem-1.3.4/lib/sys/filesystem.rb:13:in `require_relative'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/gems/sys-filesystem-1.3.4/lib/sys/filesystem.rb:13:in `<top (required)>'
	from /var/lib/sensu/8d768d1fba545898a8d09dca603457eb0018ec6829bc5f609a1ea51a2be0c4b2d13e1aa46139ecbb04873449e4c76f463f0bdfbaf2107caf37ab1c8db87d5250/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/sensu/8d768d1fba545898a8d09dca603457eb0018ec6829bc5f609a1ea51a2be0c4b2d13e1aa46139ecbb04873449e4c76f463f0bdfbaf2107caf37ab1c8db87d5250/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/lib/ruby/2.4.0/bundler/gems/sensu-plugins-disk-checks-55a44d04b3a8/bin/check-disk-usage.rb:31:in `<top (required)>'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/bin/check-disk-usage.rb:14:in `load'
	from /var/lib/sensu/63f8d2c2c597270cc82217bd609e6f3068247416bc623dc076ef62b20a12d893424b9b0b3118628a5290f3ddfe3318e38ce36c9502acce956bb774bb96f18609/bin/check-disk-usage.rb:14:in `<main>'
```

There is one thing that I don't understand: after 2020-09-17T09:20:47Z, my asset is supposed to be installed, so why other similar messages pop continuously after that ?

```json
{"asset":"sensu-ruby","component":"asset-manager","entity":"testtesttesttest","filter":["entity.system.os == 'linux'","entity.system.arch == 'amd64'","entity.system.platform == 'alpine'","entity.system.platform_version.split('.')[0] == '3'"],"level":"debug","msg":"entity filtered, installing asset build","time":"2020-09-17T09:22:46Z"}
```

So, could you please tell me what am I doing wrong ?? If the issue is not with missing package and deals with shared lib, what am I supposed to do to make it work properly ? I've probably missed something very important in the docs :/

Thanks for your time guys,

**Comment by jspaleta** [comment]
@pandaatrail 

This appears to be a problem in how the disk check asset is being built on alpine. The intent is that all additional dynamic libraries needed by the asset should be included in the asset's lib directory but for some reason the libcrypt is not being bundled like it should.

In fact looking at the build process, the libcrypt library is never installed on the system at all in the alpine build of the asset. I would have expected to fail the build but it didn't. I'm going to refile this against the check-disk asset and see if I can fix up the alpine asset build there.

**Comment by jspaleta** [comment]
@pandaatrail 
I think the fastest solution to this problem is to try to produce a new version of the ruby runtime asset that has has the sys-filesystem gem installed.  the runtime already installs the ffi gem.
I'll get back to you as soon as I've confirmed a fix

**Comment by jspaleta** [comment]
@pandaatrail 
Okay I've tested a local build of the ruby runtime. I'm going to do a new ruby runtime release now which should help.

**Comment by jspaleta** [comment]
@pandaatrail 
Hello!
new sensu-ruby-runtime release out version 0.0.11  
https://bonsai.sensu.io/assets/sensu/sensu-ruby-runtime

If you install the new version of this asset this should hopefully solve your problem.

**Comment by pandaatrail** [comment]
@jspaleta hi !

Just waking up and I see you've found where the issue comes from. So cool !

Thank you !

I'll try some new builds after installing the new asset in the next few days and will report how it behaves on my side. I think I won't be able to try this before before Monday...

Thanks again !

**Comment by calebhailey** [comment]
@pandaatrail did that updated Ruby runtime asset resolve this issue for you?

**Comment by pandaatrail** [comment]
@calebhailey sorry for the late answer.

Apparently (I didn't test much that point as I have some other issues right now with sensu) it corrects the problem I had.

But in the other hand it seems that this 0.0.11 lib is not compatible with every other plugin around: check-disk-usage.rb refuses to work if I "plug" it to sensu-ruby-runtime 0.0.11, but works smoothly with 0.0.10...

So we probably have to manage several versions of ruby-runtime in the end.

**Comment by pandaatrail** [comment]
I think I'm going to close this, and let someone reopen a new one if needed, as I don't have the same issue anymore.

But I would like to bring your attention on the fact that 0.0.10 and 0.0.11 don't seem to be working with every other asset.
Some may need 0.0.10, while others may need 0.0.11

I've met this fact using:

`   io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu-plugins/sensu-plugins-disk-checks
    io.sensu.bonsai.name: sensu-plugins-disk-checks
    io.sensu.bonsai.namespace: sensu-plugins
    io.sensu.bonsai.tags: ruby-runtime-2.4.4
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-disk-checks
    io.sensu.bonsai.version: 5.1.3`

which I could not get working with 0.0.11. So I've decided to use as many ruby-runtimes as needed, just by overriding their names while installing assets with option -r
