### ISSUE TITLE
Creating an agent entity through the API breaks entity listing

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4010]
## Expected Behavior
I'd expect to be able to create an agent entity with the API, and then connect the agent, without issue.

## Current Behavior
Entity iteration breaks if the agent never connects.

## Possible Solution
Investigate how entity configuration and entity state are combined, and improve the system to be more tolerant.

## Steps to Reproduce (for bugs)
1. Create several entities.
2. Create an agent entity with the API whose name is in the middle of the others.
3. List entities, observe the lower half after the special entity are missing.

## Customers
1. Weta digital

**Comment by portertech** [comment]
Closed by #4020
