### ISSUE TITLE
Add API key auth support to sensuctl

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#4012]
Allow users to use API keys to authenticate with `sensuctl`.

### Expected behaviour
```
$ sensuctl --api-key ... [command]
```

### Current behaviour
```
$ sensuctl configure
$ sensuctl [command]
```

There is also a race condition with concurrently running scripts in this case which API keys avoid. Consider the following scenario:
t0: `$ sensuctl configure`
t1: `$ sensuctl entity list` (ref: `exec1`)
t2: `$ sensuctl event list` (ref: `exec2`)
t3: `exec1` reads config file
t4: `exec2` reads config file
t5: `exec1` issues token refresh
t6: `exec2` command fails as unauthorised due to stale token

## Context
This would be useful for periodic tasks (eg: `sensuctl dump` on a systemd timer) and for simplifying CI/CD pipelines.

**Comment by calebhailey** [comment]
Thanks, @roganartu :+1:
