### ISSUE TITLE
Silences fail to resolve after cluster restart

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4014]
## Expected Behavior
After a silence is applied, it should resolve after its period, even through cluster restarts.

## Current Behavior
Silences seem to persist past cluster restarts.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Create silences for pretty much everything, and do a rolling upgrade of Sensu.
2. Observe that silences don't resolve.

## Context
Reported by a customer.

**Comment by portertech** [comment]
This likely requires a spike.
