### ISSUE TITLE
Can't build time based filters on keepalive timeout 

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#4022]
## Expected Behavior
Should be able to build an hourly filter around .check.ttl  for timeouts as part of an alert fatigue or remediation escalation.

## Current Behavior
the keepalive timeout interval that triggers a non-zero keepalive event is not exposed in the event itself, so it's not possible to build a timeout

### Treat keepalive timeout as check.ttl
When keepalive timeout event is generated, stop the keepalive timeout that triggers as the .check.ttl in the generated event.  This would fix the keepalive specific problem and allow keepalive timeout events to be filtered the same way that check ttl timeouts are.

when warning is generated  .check.ttl should be keepalive-warning-timeout
when critical  is generated  .check.ttl should be keepalive-critical-timeout

### Extend event with attribute indicating ttl/keepalive timeout event
Also add an additional boolean as a top level event attribute or to the generated .check in the event that indicates that a ttl interval has been breached, and thus this event is being generated by the backend and is not being generated by the entity. Set this boolean to true any time a ttl condition is breached and the backend has to generate a ttl event (for any check not just limited to keepalive).  

## Steps to Reproduce (for bugs)

1. create keepalive handler
2. create agents with keepalive-warning-timeout of 180 (3 minutes ) and 200 (5 minutes)
3. try to create reusable 15 minute filter for keepalive handler for both agents

**Comment by portertech** [comment]
Team would like to follow up with Jef after his PTO.

**Comment by palourde** [comment]
Turns out `keepalive-warning-timeout` maps to `event.check.timeout`, and `keepalive-critical-timeout` to `event.check.ttl`.

One important thing to note is that `keepalive-critical-timeout` has no default value, so `event.check.ttl` will be `0` if none is set.

@jspaleta will open an issue so we try to document that.
