### ISSUE TITLE
How to apply alert fatigue filter on continuous failing event subsequence?

### ISSUE THREAD

**Issue by hjj8645561** [sensu/sensu-go#4025]
## Feature Suggestion

We are researching to use sensu-go observability pipeline as an alert service. So call api to only generate Failing event to input data. There is no Passing event being input to pipeline. So we don't know the fixed interval of check as well.
Alert fatigue strategy we need:
* Alert when occurrences == 3 
* Avoid duplicated alert in one hour/day
## Possible Implementation

I found [handle_when](https://docs.sensu.io/sensu-enterprise/latest/filters/handle-when/#handlewhen-attributes) filter maybe can implement similar function. But it seems not possible in Sensu-Go when [migrate from sensu core](https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/migrate/#filters).
Could you offer and describe some other solutions if existed.
## Context

This is my create event request body:
```
{
    "entity": {
        "entity_class": "proxy",
        "metadata": {
            "name": "{{$someHost}}",
            "namespace": "default"
        }
    },
    "check": {
        "issued": {{$timestamp}},
        "executed": {{$timestamp}},
        "output": "Server error",
        "state": "failing",
        "status": 2,
        "handlers": [
            "email"
        ],
        "metadata": {
            "name": "urlWatch",
            "labels":{
                "serverTypeId": "131",
                "zoneType": "URL Watch Zone"
            },
            "annotations":{
                "fatigue_check/occurrences": "4",
                "fatigue_check/interval": "600",
                "fatigue_check/allow_resolution": "false"
            }
        }
    },
    "timestamp": {{$timestamp}}
}

**Comment by portertech** [comment]
This would be a great discourse post, please submit your questions there: https://discourse.sensu.io/

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/apply-alert-fatigue-filter-on-continuous-failing-event-subsequence/2070/2
