### ISSUE TITLE
Load checks from json files.

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4030]
Unlike sensu core, in sensu go I am not able load checks from json file. In sensu core, the way we store in json files in /etc/sensu/conf.d/ and the checks load on sensu server startup.

I have more than 500 checks and its tough for me to create each check using sensuctl create -f <filename>.
I tried to create checks using multiple jsons but seems sensuctl create -f accepts one file at a time.

Would be great if you can let me know whether below requests are already present:
    Loading from file  (/etc/sensu/conf.d/check1.json)
    ensuctl create -f <file1> <file2> <file2>

**Comment by calebhailey** [comment]
Hi there 👋 the Sensu Go CLI does support recursive file loading (i.e. `sensuctl create -r -f`), though it appears this might not be super obvious in the documentation. 

Can you give that a try and let us know if that helps? I'll check with our team and see if this needs to be flagged as a documentation issue. 

Thanks!

**Comment by hillaryfraley** [comment]
I updated the docs to list the sensuctl create flags: https://docs.sensu.io/sensu-go/latest/sensuctl/create-manage-resources/#sensuctl-create-flags

**Comment by ccressent** [comment]
Closing as it's already possible using the techniques mentioned above (or shell loops).
