### ISSUE TITLE
Filter with previous status is not working

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4040]
I am trying to handle and event based on the previous status. I did the following filter but it's not working. Event is getting handled every time.
type: EventFilter
api_version: core/v2
metadata:
  annotations: null
  labels: null
  name: filter_new
  namespace: default
spec:
  action: allow
  expressions:
  - event.check.history[len(event.check.history)-2].status == 2
  runtime_assets: []

**Comment by amdprophet** [comment]
There is no `len` function in the javascript filters. Please visit https://discourse.sensu.io for any questions with using Sensu.

**Comment by jamesdphillips** [comment]
```
event.check.history[event.check.history.length-2].status == 2
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/length
