### ISSUE TITLE
Keepalive event.check metadata should be configurable

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4042]
## Feature Suggestion

As an operator, I can use configuration to add labels and annotations to keepalive events.

## Possible Implementation

1. Expose agent metadata as check metadata in keepalive events.
2. Add keepalive metadata concept to entities?

## Context

Currently, I can configure labels and annotations on checks, and that information is available as metadata in the `check` scope of the event. I can use the API to request events based on labels, e.g.

```
curl -s -X GET http://sensu.example.com:8080/api/core/v2/namespaces/default/events -H "Authorization: Key $SENSU_API_KEY" -G --data-urlencode 'labelSelector=checktype == "servers" && instance == "instance1"'
```

Compared to events produced by scheduled checks, keepalive events are something of a special case. The backend creates these events them on behalf of an agent -- and near as I can tell there's no affordance for backend to include labels and annotations in the check scope.

This means that to get the complete picture of an entity's state, a second API call is necessary to find any keepalive events:

```
curl -s -X GET http://sensu.example.com:8080/api/core/v2/namespaces/default/events -H "Authorization: Key $SENSU_API_KEY" -G --data-urlencode 'labelSelector=instance == "instance1"' --data-urlencode 'fieldSelector=event.check.name == "keepalive"'
```

**Comment by calebhailey** [comment]
Related support ticket: https://secure.helpscout.net/conversation/1176136379/21329?folderId=1931919

**Comment by calebhailey** [comment]
Related support ticket: https://secure.helpscout.net/conversation/1145187127/20910?folderId=1931916

**Comment by agm650** [comment]
would it be "acceptable" to add new fields in the agent configuration ? something like in agent.yml:
```yaml
keepalive-labels:
    checktype: servers

keepalive-annotations:
    test: value
```

If so, it should be easy to add to the agent, and I think I can try to do a PR for that.

**Comment by portertech** [comment]
@ccressent to look into this.
