### ISSUE TITLE
is_incident filter is not working as per definition

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4043]
is_incident  filter is handling event when state change from anything to zero. In definition I see is_incident resolution is only from when 1>0 or 2>0.

In my case I have only critical alerts with status 2 and don't want resolved alerts when state change from anything>0.

I was able to fix it using source code modification. Would be great if you can add in the Packaged installation.

**Comment by amdprophet** [comment]
This is working as intended. You can add an additional filter to implement the functionality you're describing.
