### ISSUE TITLE
sync sensu agent database asset list with sensu backend

### ISSUE THREAD

**Issue by fgouteroux** [sensu/sensu-go#4044]
Hi, 

When the sensu agent starts, it start the asset manager (if no option DisableAssets in config):
https://github.com/sensu/sensu-go/blob/master/agent/agent.go#L278

The sensu backend send to the agent the list of assets to get and install.

When an new/updated asset or new/updated subscription is declared on the backend, the agent add the new asset hash in his DB and download/install them.

But when the asset release/subscription changes, his DB is never updated.
I think the entry should be remove from his DB.

That could be help us, to keep a list of used assets.
With that we could script or develop an simple go binary to cleanup old assets based on the asset hash list in the bolt db.

Would it be possible to implement the removal of the asset entry in the bold database ?

**Comment by calebhailey** [comment]
It sounds like you're after a way to purge unused assets, which may or may not require synchronization with the Sensu Backend. Is that right?

**Comment by fgouteroux** [comment]
Yes, this is right.

**Comment by amdprophet** [comment]
There is a lot of complexity in implementing this correctly. We recommend deleting the assets directory on a schedule to work around this limitation.

**Comment by fgouteroux** [comment]
It's not the solution at all, when we have lots of sensu agents, we don't want that they re-download all assets. I don't understand the complexity to implement the delete entry in local agent db...

**Comment by calebhailey** [comment]
Re-opening this issue because we still need a solution for cleaning up "stale" assets. I don't think it's a synchronization between agent and backend, but I want to leave this open until we have an issue that correctly captures the needed improvement.
