### ISSUE TITLE
HTTP authz middleware is broken for PATCH requests

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4058]
## Expected Behavior
PATCH requests will succeed as long as a user has "update" permissions for a resource.

## Current Behavior
PATCH requests only work for users with cluster-wide permissions. (admin)

## Possible Solution
Add a case here: https://github.com/sensu/sensu-go/blob/main/backend/apid/middlewares/authorization_attributes.go#L39

## Steps to Reproduce (for bugs)
1. try to issue a patch request as a user without cluster-wide permissions

**Comment by ccressent** [comment]
More precisely, I _think_ that happens to roles that don't have a verb of `*`. That is, if you make an an equivalent cluster wide role that lists verbs instead of using `*`, it still won't work, even though you'd technically have cluster-wide permissions.
