### ISSUE TITLE
Upgrade Go version

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#4059]
We are currently "stuck" with Go 1.13 because it depends on https://github.com/sensu/sensu-go/issues/3729.

Once we are done with the etcd upgrade, updating Go to 1.15 or later will require some work because of the following behaviour:

When running tests with Go 1.15, the following failure is exhibited:
```
--- FAIL: TestHandlerTypeMutatorField (0.00s)
panic: cannot create context from nil parent
[recovered]
        panic: cannot create context from nil parent
[...]
FAIL    github.com/sensu/sensu-go/backend/apid/graphql  0.074s
```

This is because of a change introduced in Go 1.15.

## Feature Suggestion

Do whatever is necessary do be able to move forward with Go 1.15 and later versions.

## Possible Implementation

1. Fix the failing tests in package `backend/api/graphql`

I've left a few notes [here](https://github.com/sensu/sensu-go/commit/06f655da86d96ff3cc3bd0f6ba1a5c99f110761f) to achieve that. 

2. Audit the code base to see if we need changes elsewhere

Thinking about the issue, I realized we may need to do much more than just 1. because the issue is not catched at compile time. The Go 1.15 change leads to a panic at runtime. The panic in 1. was catched by tests, but there may be other places that suffer from the same problem, that are not triggered by testing!

## Context

I came across failing test cases while running tests on my machine that were passing on CI and other people's machines. We narrowed it down to a change in Go 1.15.

- https://github.com/golang/go/issues/40737
- https://golang.org/doc/go1.15#context

**Comment by ccressent** [comment]
A thought just popped up in my head: [I mentioned here](https://github.com/sensu/sensu-go/commit/06f655da86d96ff3cc3bd0f6ba1a5c99f110761f?branch=06f655da86d96ff3cc3bd0f6ba1a5c99f110761f&diff=unified#diff-256b8632694384d64d57696fce9cf77f55dc795ff7b7a2f5595ec56f6449163dR13-R14) that maybe we can alleviate the issue by checking if a context is `nil` before calling functions like `context.WithValue()` and replace it with `context.Background()` if that's the case.

But surely, if it was that simple, that's how the Go team would have gone about fixing it in the `context` library? Why didn't they do that? Let's be careful with the approach I suggest...

**Comment by echlebek** [comment]
I think we can analyze sensu-go and our dependencies with https://golangnews.org/2020/07/semgrep-lightweight-static-analysis-for-many-languages/
