### ISSUE TITLE
Asset SHA-512 should not be case sensitive

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4064]
## Expected Behavior
Asset SHA-512 should not be sensitive to upper or lower-case encoding.

## Current Behavior
SHA is compared with its literal string representation.

## Possible Solution
Translate to lower before comparing, or better yet decode hex to []int.

## Steps to Reproduce (for bugs)
1. Create asset with upper-case SHA-512 checksum.
2. Observe that asset will raise an error saying it doesn't match, with the lower cased version of the same checksum.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/4118
