### ISSUE TITLE
Env vars SENSU_CONFIG_FILE and SENSU_BACKEND_CONFIG_FILE are ignored

### ISSUE THREAD

**Issue by treydock** [sensu/sensu-go#4069]
## Expected Behavior

I would expect `SENSU_CONFIG_FILE=/etc/sensugo/agent.yml` and `SENSU_BACKEND_CONFIG_FILE=/etc/sensugo/backend.yml` to work as both are documented on Sensu Go reference pages.

## Current Behavior

Currently using either of these environment variables to start daemons results in the `/etc/sensugo` configs not getting loaded.  The only way I've been able to get the non-default config path loaded is with `-c/--config-file` flags.

## Context

The puppet module for Sensu needs a way to support changing the config path from `/etc/sensu` to other paths, especially when sites are installing both Sensu Go and Sensuclassic on the same host during migrations.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.1.0
* Installation method (packages, binaries, docker etc.): RPM
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by treydock** [comment]
CC @ghoneycutt

**Comment by portertech** [comment]
We currently use a separate CLI/Env parsing library for `--config-file`, we do not currently support the `SENSU_CONFIG_FILE` and `SENSU_BACKEND_CONFIG_FILE` variables. This would be new feature work.

**Comment by portertech** [comment]
We need to apply the env var vs cli arg values in the correct order to match how viper does it.
