### ISSUE TITLE
Sensu go webUI crashing

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4070]
I installed sensu go backend where inbuilt webui crashes frequently and I need to rerun even sensu backend which is effecting check execution.

Request you fix this and also provide a way to start webui separately so that we don't need to restart backend in case of webui crash.

**Comment by raihanchdy** [comment]
This is a major bug. In my case  webui crashing frequently. Could you please investigate this and if possible please provide a way to restart the UI when not running. As of now I have to restart whole server.

**Comment by palourde** [comment]
Hi @raihanchdy,

Please open a new issue and use the provided bug template to help us investigate this issue, so we have more information about your setup, the error you are seeing and possibly some logs.

Thanks

**Comment by tgdfool2** [comment]
Experiencing the same with my Sensu Go installation (6.2.0) under Ubuntu 20.04.

@raihanchdy: did you open an issue as requested by @palourde? Thanks!
