### ISSUE TITLE
event filter issue when trying to filter timeout.

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4076]
I configured sensu-go from source code following github doc.

I am trying to create event filter when timeout of a check happens but unfortunately I cannot provide /n while creating filter expression "Execution timed out\n"

This /n is coming by default which is a road block to stop sending alerts when timeout happens.

Please remove /n from the output and it should be "Execution timed out" only. Then I can write an expression like this:

"event.check.output != 'Execution timed out'"   

I tried removing it from the file sensu-go/command/command.go but don't see any effect.

**Comment by raihanchdy** [comment]
Requesting you to update

**Comment by calebhailey** [comment]
Hi there, @raihanchdy 👋 

Have you tried to modify the filter expression instead? E.G. `!event.check.output.includes("Execution timed out")`? 

Sensu Query Expressions support a lot more than simple `==` and `!=` operators, so this should be pretty easy to resolve...

> SQEs are valid ECMAScript 5 (JavaScript) expressions that return either true or false.

Reference: https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-filter/sensu-query-expressions/

**Comment by portertech** [comment]
You could also javascript `replace()` in your filter to strip out the `\n`. The filter engine is powerful, just need to use a few more of it's capabilities.

**Comment by raihanchdy** [comment]
Hi portertech, 

Filters do not accept \n at all. How can I replace then

**Comment by raihanchdy** [comment]
Hi calebhailey,

Java script expression does not work here.

Tried "!event.check.output.includes('Execution')" but no luck.
It does not even check, and every time event handler gets executed

**Comment by raihanchdy** [comment]
I fixed it. Below is the expression
"event.check.output.slice(0,-1) != 'Execution timed out'"
