### ISSUE TITLE
sensuctl errors when vault provider certificates aren't present on the local system

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4083]
## Expected Behavior

sensuctl does not require the ca certificate specified in a vault provider definition to be present locally

## Current Behavior

running `sensuctl create -f vault.json` if the filepath `ca_cert` defined in `vault.json` is not present on the host where sensuctl is running

## Steps to Reproduce (for bugs)

Assuming a known working sensu-backend and sensuctl

1. create a vault.json
```
{
  "type": "VaultProvider",
  "api_version": "secrets/v1",
  "metadata": {
    "name": "vault"
  },
  "spec": {
    "client": {
      "address": "https://vault:8200",
      "agent_address": "",
      "max_retries": 2,
      "rate_limiter": {
        "burst": 100,
        "limit": 10
      },
      "timeout": "20s",
      "tls": {
        "ca_cert": "/etc/sensu/ca.pem",
        "ca_path": "",
        "client_cert": "/etc/sensu/vault.pem",
        "client_key": "/etc/sensu/vault-key.pem",
        "cname": "sensu-agent",
        "insecure": false,
        "tls_server_name": ""
      },
      "token": "",
      "version": "v2"
    }
  }
}
```
2. Ensure the specified ca_cert `/etc/sensu/ca.pem` does not exist on the host running `sensuctl`
3. Run `sensuctl create -f vault.json`
4. Observe an error 
```
resource 0: Error loading CA File: open /etc/sensu/ca.pem no such file or directory
Error: in vault.json: some resources couldn't be parsed
```
5. copy a valid pem-formatted CA certificate to the /etc/sensu/ca.pem file path
6. rerun the create command, note that it succeeds
7. run `sensuctl dump secrets/v1.Provider` and note that it succeeds
8. move or delete the certificate at /etc/sensu/ca.pem so that the file path no longer exists
9. run `sensuctl dump secrets/v1.Provider` and note that it now fails with an error:
```
Error: API error: json: cannot unmarshal object into Go value of type secrets.Provider
```

## Context

I first encountered the unmarshaling error when attempting to dump all resources from a sensu-backend instance. An API key with the same permissions can retrieve valid JSON from the backend API, and sensuctl running on the backends themselves can also successfully dump these resources.

What I finally realized was that the environment experiencing the error does not have a valid pem-formatted certificate at the path specified in the vault provider definition, whereas the backends themselves do. Interacting with  vault provider resources via sensuctl succeed on those hosts.

It's a good idea for backends to check for the presence of these certificates at the time of resource creation, but applying the same requirement to sensuctl is less than ideal.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.1.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): ubuntu 20.02, centos 8.2

**Comment by portertech** [comment]
Need to do the validation in the API and not in sensuctl.

**Comment by portertech** [comment]
We are going to address this one as a validation bug, however, we won't be adding further QA automation/coverage at this time. If another bug/issue comes along that would have been caught by a sensuctl on a separate QA host, we'll admit we were wrong and do the work.
