### ISSUE TITLE
Cannot create an agent entity using the PUT method

### ISSUE THREAD

**Issue by tadeboro** [sensu/sensu-go#4084]
The [entity docs][edocs] state that the `PUT` method can create or update entities, but this is not the case when the `entity_class` is set to `agent`.

   [edocs]: https://docs.sensu.io/sensu-go/latest/api/entities/#entitiesentity-put

## Expected Behavior

Calling `PUT /entities/my_e` should create a new agent entity when the payload is as follows:

    {
      "metadata": {
        "namespace": "default",
        "name": "my_e"
      },
      "entity_class": "agent"
    }

## Current Behavior

Calling `PUT /entities/my_e` returns back with status 200, but the entity is not created.

## Context

We discovered this while adding a few more tests to the Sensu Go Ansible Collection. Note that this bug is only present in Sensu Go >= 6.0.0 (we tested this on 6.0.0 and 6.1.2). Sensu Go 5.20.2 and 5.21.3 both work as expected.

**Comment by palourde** [comment]
@tadeboro This issue has been fixed in https://github.com/sensu/sensu-go/blob/main/CHANGELOG.md#611---2020-10-22

I was able to successfully reproduce it on my local instance:
```
$ curl -X PUT \
-H "Authorization: Key $SENSU_API_KEY" \
-H 'Content-Type: application/json' \
-d '{
  "metadata": {
    "namespace": "default",
    "name": "my_e"
  },
  "entity_class": "agent"
}
' \
http://127.0.0.1:8080/api/core/v2/namespaces/default/entities/my_e
{"entity_class":"agent","system":{"network":{"interfaces":null},"libc_type":"","vm_system":"","vm_role":"","cloud_provider":"","processes":null},"subscriptions":null,"last_seen":0,"deregister":false,"deregistration":{},"metadata":{"name":"my_e","namespace":"default"},"sensu_agent_version":""}

$ sensuctl entity list
     ID       Class     OS      Subscriptions               Last Seen
 ─────────── ─────── ──────── ────────────────── ───────────────────────────────
  my_e        agent                               N/A

$ sensuctl entity info my_e
=== my_e
Name:                   my_e
Entity Class:           agent
Subscriptions:
Last Seen:              N/A
Hostname:
OS:
Platform:
Platform Family:
Platform Version:
Auto-Deregistration:    false
Deregistration Handler:
```

Please make sure to follow the instructions in https://docs.sensu.io/sensu-go/latest/operations/maintain-sensu/upgrade/, namely restarting the backend processes after the upgrade and let us know if you still face any issue.

**Comment by tadeboro** [comment]
We are using official Sensu Go docker images in our tests. Let me test this manually and report back with results.

**Comment by tadeboro** [comment]
My bad. This only fails on 6.0.0, 6.1.2 works just fine. I messed up because I was working on two things at once: on PUT failure and on behavior change on entities that are not of agent or proxy class (custom entities gained automatic subscription in 6.1.x and this also failed our tests, but that is another story).

So I guess this issue is indeed solved in 6.1.2. I will probably just remove 6.0.0 from our testing matrix becase this fix will not be backported to 6.0.x series, right?

**Comment by palourde** [comment]
@tadeboro Indeed, we do not plan to backport this bugfix to 6.0 at the moment!

**Comment by tadeboro** [comment]
Thanks, @palourde, for your help. And sorry for wasting your time with a half-valid issue. I will close this now and drop 6.0.0 from our integration tests in Sensu Go Ansible Collection.
