### ISSUE TITLE
Bug: entity labels not updating after an entity registered w/o label

### ISSUE THREAD

**Issue by acrawly** [sensu/sensu-go#4086]
If we update the agent.yml file with some label data AFTER the agent already 'registered' with the Sensu backend, the label will not appear. 

## Expected Behavior
We'd expect the label to show up in the web interface.

## Current Behavior
Currently, the label does not appear. If we manually delete the entity and allow it to 're-register,' the label will show up as expected.

## Possible Solution
Make entities update their labels when they do a keepalive check?

## Steps to Reproduce (for bugs)
1. Create a sense server
2. Create an agent WITHOUT any labels inside the agent.yml file
3. Confirm the entity is on the sensu server
4. Add label data to the agent.yml file
5. The label data will NOT appear via the web interface on the sensu server

## Context
We need to organize our entities and this is preventing that from happening without deleting ALL our entities whenever we make an update to our labels. 

## Your Environment
Sensu 6.1 cluster w/ 3 nodes

**Comment by mcbsd** [comment]
Hi @acrawly , this is now default behavior as explained at https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-entities/entities/
```
NOTE: You cannot modify an agent entity with the agent.yml configuration file unless you delete the entity. The entity attributes in agent.yml are used only for initial entity creation unless you delete the entity.
```

**Comment by acrawly** [comment]
Hey @mcbsd,

Thanks for replying. I'm sorry I missed that on the documentation. I read that page, too. 

We'll look into the deregister attribute. Thank you!
