### ISSUE TITLE
sensuctl --interactive resource missing sensu.io/managed_by label

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#4087]
Sensuctl resource creation with `--interactive` does not produce resources with the `sensu.io/managed_by` label. Sensuctl prune is unable to prune these resources. `sensuctl edit` does add the  `sensu.io/managed_by` label :sweat_smile: 

## Expected Behavior
Resources created via `sensuctl create --interactive` have the `sensu.io/managed_by` label set to `sensuctl`. These resources can be pruned.

## Current Behavior
Sensuctl resource creation with `--interactive` does not produce resources with the `sensu.io/managed_by` label. Sensuctl prune is unable to prune these resources.

## Possible Solution
Updated sensuctl `--interactive` logic to include the `sensu.io/managed_by` label in the produced object.

## Steps to Reproduce (for bugs)
`sensuctl handler create --interactive`
`sensuctl prune handlers -r -f example/handlers/`

## Context
Used `--interactive` to create a rogue handler to be pruned, but it could not be pruned.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by palourde** [comment]
Some context: the intent of that label was to be used for pruning, see https://github.com/sensu/sensu-go/issues/3594, so only resources created by `sensuctl create` would have this value.

That being said, it seems that [this refactoring](https://github.com/sensu/sensu-go/pull/3616) also made `sensuctl edit` add this value if missing, which is definitely a bug.

In retrospection, `sensuctl` was probably not a good value for that.

From this point, I think we could rename `sensuctl` for the `sensu.io/managed_by` label to `sensuctl-create`, for example, when created via `sensuctl create` and make all other sensuctl commands set the value `sensuctl-interactive` (or wtv).

**Comment by portertech** [comment]
Based on team input, we are not going to add the `managed_by` label to `--interactive` resources and instead remove the label creation from `sensuctl edit`.
