### ISSUE TITLE
event ID keys are not consistent in sensu-backend logs

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4093]
## Expected Behavior

In reviewing sensu-backend logs, I can refer to a consistent key name for the event UUID.

## Current Behavior

sensu-backend log messages use inconsistent key names when logging event UUID. Some log messages use key `event_uuid`, whereas others use key `uuid`. 

## Possible Solution

Standardize name for key whose value is the event UUID

## Steps to Reproduce (for bugs)

1. Turn on debug level logging in your sensu-backend
2. Submit one or more events via the Agent, scheduled or using the agent's /events HTTP API
3. Identify UUID for the event, then grep the UUID from backend-logs
4. Note that although each message uses the same UUID value, the keys which provide that value vary

## Context

Some log messages use key `event_uuid`, whereas others use key `uuid`, and this appears to be inconsistent even for log messages coming from the same backend component but differing log levels:

```
{
  "check_name": "check-sensu-filebeat-process",
  "check_namespace": "monitoring",
  "component": "pipelined",
  "entity_name": "sd-25f8-415b",
  "entity_namespace": "monitoring",
  "handler": "monitoring-email",
  "level": "info",
  "msg": "sending event to handler",
  "time": "2020-11-05T09:30:00-05:00",
  "uuid": "47eedb71-9430-4120-b471-9680a1c2f09d"
}
{
  "assets": [
    "sensu-email-handler"
  ],
  "check": "check-sensu-filebeat-process",
  "component": "pipelined",
  "entity": "sd-25f8-415b",
  "event_uuid": "47eedb71-9430-4120-b471-9680a1c2f09d",
  "handler": "monitoring-email",
  "level": "debug",
  "msg": "fetching assets for handler",
  "namespace": "monitoring",
  "time": "2020-11-05T09:30:00-05:00"
}
```

Further more, the event payload sent to handlers and event-log (when configured) uses key name `id`.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by portertech** [comment]
Let's use `event_id` in the logs. It is more consistent with the event ID.
