### ISSUE TITLE
sensu-go-agent is ignoring http_proxy/no_proxy environment variables when downloading assets since version 6.x

### ISSUE THREAD

**Issue by AndreasUfert** [sensu/sensu-go#4101]
Proxy is defined in /etc/default/sensu-agent by setting http_proxy.
Platform is Ubuntu, any of 16.04, 18.04 or 20.04

## Expected Behavior
sensu-agent honors http_proxy and contacts proxy for asset download

## Current Behavior
sensu-agent tries to directly resolve assets.bonsai.sensu.io and subsequently fails to download the asset

## Possible Solution
downgrade to sensu-go-agent=5.21.3-42094 and hold this version

## Steps to Reproduce (for bugs)
1. install sensu-agent version 6.1.3-3642 (or any 6.x) on Ubuntu 16.04, 18.04, 20.04
2. set http_proxy in /etc/default/sensu-agent
3. add any asset + check to the entity
4. look for any connection in proxy log: it is missing
5. look for asset download errors in sensu-agent log: 

## Context
Our AWS VPC is not internet connected and the only way to connect to assets.bonsai.sensu.io is a http proxy .

Everything works fine in sensu-go-agent=5.21.3-42094

## Your Environment
Entity platform is Ubuntu, any of 16.04, 18.04 or 20.04
Backend platform is Ubuntu 20.04

all packages install via apt repository

sensu-go-agent   6.1.3-3642
sensu-go-backend   6.1.3-3642
sensu-go-cli   6.1.3-3642

**Comment by portertech** [comment]
It's not obvious what would have broken this in 6.x.

Is it possible you have a conflicting `http_proxy` or `HTTP_PROXY`? Have you checked the env for the running Sensu agent?

**Comment by AndreasUfert** [comment]
Tried both http_proxy and HTTP_PROXY but never both. Thus no conflicting env vars. Tried with and without no_proxy. Process environment in /proc/pid shows that vars are applied to sensu-agent's environment.

You can simply change behavior by upgrading an downgrading the ubuntu package:

sudo apt-get install sensu-go-agent=6.1.3-3642
-> download fails (proxy is ignored)

sudo apt-get install sensu-go-agent=5.21.3-42094
-> download works like a charm

No files additional file changed or touched during downgrade - just downgraded the package.

**Comment by portertech** [comment]
Thank you :+1: Prioritizing this.

**Comment by cwjohnston** [comment]
In my testing this appears a regression between versions 6.0.0 and 6.1.0.

**Comment by palourde** [comment]
Alright, I finally understood what happened.

According to [Go docs](https://golang.org/pkg/net/http/#RoundTripper), `&http.Client{}` will use `DefaultTransport` which automatically includes [`ProxyFromEnvironment`](https://golang.org/pkg/net/http/#ProxyFromEnvironment).

However, since https://github.com/sensu/sensu-go/pull/3975, we construct a non-default `Transport`, so an extra proxy configuration is now required.

**Comment by palourde** [comment]
Update: I forgot to mention that it only happens with assets using HTTPS; assets using an URL with HTTP do not have this problem.

**Comment by palourde** [comment]
Hi @AndreasUfert,

Could you let us which value you set to `http_proxy`? In particular, I'd be interested to know if you used `127.0.0.1` or `localhost`.

Thanks!

**Comment by AndreasUfert** [comment]
Neither localhost nor 127.0.0.1. The proxy does not run locally on the agent's host.

If the question was whether I use an IP or a host name to connect to the proxy: it's a host name.

**Comment by palourde** [comment]
@AndreasUfert Thank you for the info; one last question: did you configured the `trusted-ca-file` configuration attribute for the agent in question?

Thanks again

**Comment by AndreasUfert** [comment]
Guess so (can't confirm definitely right now). But since the agent has been configured to use mutual TLS with certificates generated solely for mTLS I guess I configured key, cert and trusted ca.

**Comment by palourde** [comment]
Thanks @AndreasUfert for these information, definitely gave us a better idea of what might happen.

**Comment by palourde** [comment]
Quick update: we were able to solve that issue via the PR https://github.com/sensu/sensu-go/pull/4113.

We will include this bugfix in our next release.
