### ISSUE TITLE
Sensu-backend v6.1.0CE gets into panic when connecting 1500 or more agents at once

### ISSUE THREAD

**Issue by nadeem1701** [sensu/sensu-go#4107]
**I am benchmarking SensuGo for a larger deployment. Whenever I try to connect more than 1500 sensu-agents at once it backend gets into panic state. it does not admit any new agents and drops if any already connected. It works fine if connect the agents in smaller batches like 1000 or less.**

In logs of sensu-backend, I found:
`Nov 27 09:43:39 ip-172-31-82-204 sensu-backend[469]: {"level":"warn","ts":"2020-11-27T09:43:39.707Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-999b3656-1d41-48d3-9dd4-e3cf228f742a/172.31.91.226:2379","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
Nov 27 09:43:39 ip-172-31-82-204 sensu-backend[469]: {"agent":"sensu-client-43_23","component":"agentd","error":"context canceled","level":"error","msg":"error querying the entity config","namespace":"default","time":"2020-11-27T09:43:39Z"}
Nov 27 09:43:39 ip-172-31-82-204 sensu-backend[469]: {"address":"34.228.52.3:40214","agent":"sensu-client-43_23","component":"agentd","error":"context canceled","level":"error","msg":"failed to start session","namespace":"default","time":"2020-11-27T09:43:39Z"}`

I wasn't able to find something about it in documentation or KB.
**I wanna know if it is a bug or application limitation.**

## Steps to Reproduce (for bugs)

1.Run a sensu-backend with an external etcd.
2.Run 2000 agents but block them with firewall
3.Allow them to connect at once.

## Context

SensuGo cannot be possible solution for large scale deployment because we wont be able to recover from a disaster.

## Your Environment

* sensu-backend version 6.1.0+ce, community edition, built 2020-10-19, built with go1.15.3
* sensu-agent version 6.1.0+ce, community edition, built 2020-10-19, built with go1.15.3
* external etcd v3.5.0
* Installation method (compiled binaries running as service, Containerized sensu-agents)
* Operating System and version (backend: linux-debian-10, agent: alpine-3.5-container ):

**Comment by echlebek** [comment]
Closing, please see https://discourse.sensu.io/t/sensugo-v6-1-0-ce-gets-into-a-panic-when-connecting-more-than-1500-agents-at-once/2294/2
