### ISSUE TITLE
No document to configure checks on HA cluster

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4108]
I have setup 3 node cluster. Not sure where to create the checks. 
Should I create the checks on the leader node or on all the 3 nodes.

Not able to find if any document is present for this. If not please update the document

**Comment by mcbsd** [comment]
Hi,
it's in HA. You e.g. load the check via sensuctl and it is propagated across the cluster. If you then use sensuctl to show checks, you will see the same output on each node.

**Comment by raihanchdy** [comment]
Thanks,
Should I load the checks on leader node or any node is fine

**Comment by mcbsd** [comment]
Man, why don't you try it by yourself and see? This is is not a community chat - there is dedicated discourse channel for it.
And yes, any node is fine, omg.

**Comment by rehanch178** [comment]
I can explore myself which is not a big deal.
Make the documents atleast clear. 

You could simply mention the same in the documentation.

**Comment by rehanch178** [comment]
Thanks for the help.

**Comment by echlebek** [comment]
Hey folks, just a friendly reminder, our discourse forum (https://discourse.sensu.io/) is the best place for Q&A and discussion. This is the issue tracker for sensu-go, and it does not include our documentation. That can be found at https://github.com/sensu/sensu-docs/.

If there are concrete suggestions for docs improvements we would welcome issues or pull requests there. Thanks!

**Comment by cwjohnston** [comment]
Hi @rehanch178, and thanks for your feedback!

I've opened https://github.com/sensu/sensu-docs/issues/2866 to describe the gap you've encountered. If you would share in that issue which documents you looked to for information and found lacking, that context would help us to improve.

**Comment by mcbsd** [comment]
@rehanch178 
Sorry to be expressive but one thing to be clear to not shed bad light on Sensu developers, I am just random Sensu user, I am not from Sensu team...

**Comment by hillaryfraley** [comment]
We merged https://github.com/sensu/sensu-docs/pull/2869 to clarify in several docs pages that clustered backends only require API calls to one cluster member.
