### ISSUE TITLE
failed to write response

### ISSUE THREAD

**Issue by lk3687051** [sensu/sensu-go#4109]
## Current Behavior

Can not open the ui .  
Logs:
Dec 01 18:16:46 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:27864: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:16:46+08:00"}
Dec 01 18:17:10 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:64297: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:17:10+08:00"}
Dec 01 18:17:35 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:65077: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:17:35+08:00"}
Dec 01 18:17:58 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:41533: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:17:58+08:00"}
Dec 01 18:18:24 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:28274: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:18:24+08:00"}
Dec 01 18:18:48 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:46913: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:18:48+08:00"}
Dec 01 18:19:13 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:21830: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:19:13+08:00"}
Dec 01 18:19:30 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:25408: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:19:30+08:00"}
Dec 01 18:19:46 WXJD-PSC-P9F1-MCORE-PM-OS01-BCOPS-01 sensu-backend[60816]: {"component":"apid.routers","error":"write tcp 10.174.68.6:32605-\u003e172.20.152.110:31197: i/o timeout","level":"error","msg":"failed to write response","time":"2020-12-01T18:19:46+08:00"}

![image](https://user-images.githubusercontent.com/10841484/100731892-f3d1e780-3406-11eb-9bdc-d19effe8caef.png)

## Possible Solution

None
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
Sensu-go 5.21.3
* Installation method (packages, binaries, docker etc.):
binaries
* Operating System and version (e.g. Ubuntu 14.04):
Centos 7

**Comment by lk3687051** [comment]
Append tcpdump information:
`POST /graphql HTTP/1.1
Host: 10.174.68.6:32605
Connection: keep-alive
Content-Length: 2420
accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDY4MTg5MjUsImp0aSI6ImFiNDMzNTA1MDQxOWY5YzM2OThmNjRjZGU5YTViOTYwIiwiaXNzIjoiaHR0cDovLzEwLjE3NC42OC42OjMyNjA1Iiwic3ViIjoiYWRtaW4iLCJncm91cHMiOlsiY2x1c3Rlci1hZG1pbnMiLCJzeXN0ZW06dXNlcnMiXSwicHJvdmlkZXIiOnsicHJvdmlkZXJfaWQiOiJiYXNpYyIsInByb3ZpZGVyX3R5cGUiOiIiLCJ1c2VyX2lkIjoiYWRtaW4ifSwiYXBpX2tleSI6ZmFsc2V9.TrYCahxcgUhDF9srFVZaeqrnPK5uIwxPJPQX76whceg
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47
content-type: application/json
Origin: http://10.174.68.6:32605
Referer: http://10.174.68.6:32605/n/default/events
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,ja;q=0.5

[{"operationName":"EventsViewQuery","variables":{"namespace":"default","limit":25,"offset":0,"order":"LASTOK","filters":[]},"query":"query EventsViewQuery($namespace: String!, $filters: [String!], $order: EventsListOrder, $limit: Int, $offset: Int) {\n  namespace(name: $namespace) {\n    id\n    ...EventsView_namespace\n    __typename\n  }\n}\n\nfragment EventsView_namespace on Namespace {\n  id\n  ...EventsList_namespace\n  __typename\n}\n\nfragment EventsList_namespace on Namespace {\n  checks(limit: 1000) {\n    nodes {\n      name\n      __typename\n    }\n    __typename\n  }\n  entities(limit: 1000) {\n    nodes {\n      name\n      __typename\n    }\n    __typename\n  }\n  events(limit: $limit, offset: $offset, filters: $filters, orderBy: $order) {\n    nodes {\n      id\n      namespace\n      entity {\n        name\n        __typename\n      }\n      check {\n        nodeId\n        name\n        proxyEntityName\n        __typename\n      }\n      silences {\n        ...ClearSilencedEntriesDialog_silence\n        __typename\n      }\n      ...EventsListHeader_event\n      ...EventsListItem_event\n      __typename\n    }\n    pageInfo {\n      ...Pagination_pageInfo\n      __typename\n    }\n    __typename\n  }\n  ...EventsListHeader_namespace\n  __typename\n}\n\nfragment ClearSilencedEntriesDialog_silence on Silenced {\n  ...SilenceExpiration_silence\n  id\n  name\n  creator\n  __typename\n}\n\nfragment SilenceExpiration_silence on Silenced {\n  expireOnResolve\n  expires\n  __typename\n}\n\nfragment EventsListHeader_namespace on Namespace {\n  checks(limit: 1000) {\n    nodes {\n      name\n      __typename\n    }\n    __typename\n  }\n  entities(limit: 1000) {\n    nodes {\n      name\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment EventsListHeader_event on Event {\n  isSilenced\n  __typename\n}\n\nfragment EventsListItem_event on Event {\n  isSilenced\n  isNewIncident\n  timestamp\n  check {\n    name\n    status\n    ...EventStatusDescriptor_check\n    __typename\n  }\n  entity {\n    name\n    __typename\n  }\n  namespace\n  ...EventStatusDescriptor_event\n  __typename\n}\n\nfragment EventStatusDescriptor_check on Check {\n  lastOK\n  status\n  occurrences\n  __typename\n}\n\nfragment EventStatusDescriptor_event on Event {\n  timestamp\n  __typename\n}\n\nfragment Pagination_pageInfo on OffsetPageInfo {\n  totalCount\n  __typename\n}\n"}]`

**Comment by lk3687051** [comment]
@jspaleta  Could you help with it.

**Comment by echlebek** [comment]
Can you make a discourse post? It seems most likely that this is network configuration problem, and not a sensu-go issue.
