### ISSUE TITLE
Api to get the etcd leader node info in a cluster

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4110]
I have deployed ha setup in docker containers.

Since checks creation is automatic, I need an api call to know which is leader node so that I can create checks only on one node in an automated way. As of now all the 3 nodes having same info and the automation script may create checks in all the 3 nodes which is not the suitable configuration.

**Comment by echlebek** [comment]
You shouldn't need to do this. It doesn't matter which node is the etcd leader. You can create checks on any backend and the information will be available to the entire cluster.

I'd advise taking this one to the discourse forums if you need more information. It's not really a sensu-go issue per se.
