### ISSUE TITLE
error getting assets for event: sha512 does not match

### ISSUE THREAD

**Issue by nandeeshb09** [sensu/sensu-go#4117]
Hi Team,

Please help here, we are facing this issue all of sudden here mismatch between asset key.

Even though we have updated properly in the asset and which will download from s3 bucket.

Its not matching with asset key and in the sensu backend and always it will generate new one from sensugo.

Even we tried to upgrade sensugo backend to 5.21.3, but still the issue is same here.

Is this bug at your side?... please help here, due to this non of our checks are not running and blocked our production.

error getting assets for event: sha512:a37e528a7e6c4c976ef7bbc68fe06d8cc1c2ac5944452e0a7e7e742b23a555fdc57510875b6f9c351600d203c91b9f1c5e6039c20b563ab598e539bd96a374f3 does not match..

Agent not downloading the asset from s3 bucket and am able to download manually.

/var/cache/sensu/sensu-agent # ls -la
total 44
drwxr--r--    2 root     root            39 Dec  8 06:59 .
drwxr--r--    3 root     root            25 Dec  8 06:59 ..
-rw-------    1 root     root         16384 Dec  8 06:59 assets.db
-rw-------    1 root     root         32768 Dec  8 06:59 queue.db

**Comment by nandeeshb09** [comment]
Team,

Any help on this issue.?

**Comment by portertech** [comment]
Have you verified the download URL and checked the resulting sha512 for the download? I don't believe this is a bug in Sensu, it could be an issue w/ your asset publishing and configuration workflow. Please take this issue and discussion to the Sensu Discourse: https://discourse.sensu.io/

**Comment by nandeeshb09** [comment]
@portertech thanks for your responce
