### ISSUE TITLE
Silenced API in 6.2.0 broke backward-compatibility

### ISSUE THREAD

**Issue by tadeboro** [sensu/sensu-go#4143]
The silencing API up until 6.2.0 returned back a static representation of silencing entries and since 6.2.0, API returns back some non-static calculated values. 

## Expected Behavior

`GET /api/core/v2/namespaces/default/silenced/*:chk` should return a superset of data that was used to create the silencing entry.

## Current Behavior

`GET /api/core/v2/namespaces/default/silenced/*:chk` contains updated data in the `expire` field. The value in the `expire` field is also not static and changes with every `GET` call to the API.

## Possible Solution

In an ideal world, the previous behavior would be restored. And if the currently returned information is needed, it should be added into a new field.

## Steps to Reproduce (for bugs)

Download the script from https://gist.github.com/tadeboro/ad904d7365768f5cf9c94e747e9ade8b. Run:

    $ ./silence.sh 6.2.0  # This will show changing numbers
    $ ./silence.sh 6.1.4  # Output is static for all loop iterations (can also use any other Sensu Go version)

## Context

We discovered this change when we started testing Sensu Go Ansible Collection on 6.2.0. The first failure we encountered was caused by the fact that we were creating some expired silences in our tests and Sensu Go 6.2.0 did not return them back. But this was our error because there is no reason to assume expired entries will remain alive on the backend.

Once we sorted the previous error out, our idempotency checks started failing because the Ansible module for managing silences starting detecting changes where should be none. And we managed to track this down to the change in the `expire` value returned by the API.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): Tested on 6.2.0 and 6.1.4
* Installation method (packages, binaries, docker etc.): docker

/cc @echlebek because he already helped me on Slack. No good deeds go unpunished ;)

**Comment by palourde** [comment]
For reference, here's a thread about it in the community Slack: https://sensucommunity.slack.com/archives/C9BB9AW7K/p1608552870192700
