### ISSUE TITLE
Incorrect history of an event.

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4145]
History data is getting updated when I execute the check for second time.

At first time executing the check does not add any history data in the event. This information is misleading while we want to create any filter based on the first history data point.

Below is the history data I got after executing the check for second time.

     "history": [
      {
        "status": 0,
        "executed": 1608785570
      }
      ]

**Comment by portertech** [comment]
Which event store are you using? etcd or postgres?
