### ISSUE TITLE
Add a sensu-backend init flag to exit 0 if already initialized

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4161]
## Feature Suggestion

Orchestrating `sensu-backend init` on cloud-native platforms (and I suspect equally challenging to automate on other cloud platforms) can be difficult because running `sensu-backend init` on an already-initialized cluster results in a non-zero exit status.

## Possible Implementation

Add a `--quiet` flag to suppress "already registered" causing non-zero exit status.

**Comment by portertech** [comment]
Engineering would like to use the flag `--ignore-already-initialized` for this purpose, as it's more specific.

**Comment by calebhailey** [comment]
SGTM!

**Comment by portertech** [comment]
TODO:

- [ ] Add flag `sensu-backend init --ignore-already-initialized`
- [ ] Update exit status behaviour to account for `--ignore-already-initialized` (exit 0 instead of 3)
