### ISSUE TITLE
Add support to initialize a cluster with an API KEY

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4162]
## Feature Suggestion

Add support for optionally supplying an API Key via `sensu-backend init`. If paired with #4012 this would simply new-cluster provisioning. New clusters could be initialized and seeded with default configuration with less "orchestration"; i.e. instead of initializing the cluster, configuring `sensuctl` with username and password, and then executing resource management commands w/ sensuctl... you can eliminate the `sensuctl` configure step and just execute `sensuctl` commands with two flags `--api-key=` and `--api-url=`. 

## Possible Implementation

- Accept any valid UUIDv4 via a new `--sensu-cluster-admin-apikey` flag and/or `$SENSU_CLUSTER_ADMIN_APIKEY` environment variable. 
- Like other `sensu-backend init` functions, this cluster admin API Key should only be granted when initializing a fresh cluster

## Context

Monitoring as code for new cluster provisioning.

**Comment by calebhailey** [comment]
This will be even more valuable thanks to https://github.com/sensu/sensu-go/pull/4256

**Comment by calebhailey** [comment]
@echlebek updated the description per our discussion; i.e. `s/sensu-backend-cluster-admin-apikey/sensu-cluster-admin-apikey/`.

**Comment by echlebek** [comment]
@calebhailey danke!
