### ISSUE TITLE
--agent-managed-entity flag broken when no agent labels defined

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4171]
## Expected Behavior
--agent-managed-entity flag allows managing entities agent-side.

## Current Behavior
Agent crashes.

## Possible Solution
Fix the nil map assignment in the agent.

## Mitigation
Define at least one label on the agent configuration.

**Comment by antgilles** [comment]
This mitigation doesn't seem to work when agent-managed-entity is configured in agent.yml.

**Comment by treydock** [comment]
I've also noticed that the mitigation causes labels defined in `agent.yml` to be ignored if the workaround label is specified at the command line which is far from ideal.

**Comment by amdprophet** [comment]
Fixed by https://github.com/sensu/sensu-go/pull/4173 which will ship with the next release.
