### ISSUE TITLE
Reflect external etcd version in /version API results

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4174]
## Feature Suggestion

When configured with external etcd, the response body of /version API endpoint should reflect the external etcd version.

## Context

Output from backend /version API doesn't reflect version of etcd running on external cluster, so the output could be misleading.

**Comment by calebhailey** [comment]
We should also include the etcd location (i.e. "embedded" vs "external") in the /status output.

**Comment by portertech** [comment]
Implementation would entail using the etcd client to query external etcd for its version, when the backend is running with no embed.

Francis mentioned he gets a version when using external etcd, we suspect that it's not reporting the correct etcd.

**Comment by c-kruse** [comment]
From what I have gathered, it doesn't look like our current [Version API Model](https://github.com/sensu/sensu-go/blob/79021374d3c0f1c882639df0992a0323976b237a/api/core/v2/version.go#L9) is entirely coherent with sensu backend running with an external etcd cluster.

Sensu's `v2.Version` has an `Etcd` field of type [go.etcd.io/etcd/api/v3/version.Versions](https://pkg.go.dev/go.etcd.io/etcd/api/v3/version#Versions), which is intended to express both etcd Server and Cluster versions of a particular etcd server instance. The Cluster and Server version can be different during a cluster upgrade. It makes sense to communicate both when sensu has an embedded etcd processes, but when using an external cluster I don't think that there is any particular etcd server we care about.

Could use advice on how we aught to handle this. I see a few options for squeaking by using the existing version API.
1. "Lie" and set etcdserver and etcdcluster version to cluster version
2. omit etcdserver or set it to some "N/A"-type status
