### ISSUE TITLE
Sensu backend Memory Address issue.

### ISSUE THREAD

**Issue by rehanch178** [sensu/sensu-go#4176]
I have 3 node cluster which was running fine. I checked and found cpu/memory utilization is very low but the cluster suddenly went down. Attaching error logs for the reference.

{"component":"etcd","level":"error","msg":"failed to read 9e83e7f64749072d on stream Message (unexpected EOF)","pkg":"rafthttp","time":"2021-01-16T00:00:46Z"}
{"component":"agentd","error":"","level":"error","msg":"unexpected error while watching for entity config updates","time":"2021-01-16T00:00:47Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x104e3b6]

goroutine 2137 [running]:
github.com/sensu/sensu-go/backend/agentd.(*Agentd).handleEvent(0xc000180840, 0x0, 0x4, 0x1, 0x1)
        /sensu/sensu-go/backend/agentd/agentd.go:249 +0x76
github.com/sensu/sensu-go/backend/agentd.(*Agentd).runWatcher(0xc000180840)
        /sensu/sensu-go/backend/agentd/agentd.go:241 +0x165
created by github.com/sensu/sensu-go/backend/agentd.(*Agentd).Start
        /sensu/sensu-go/backend/agentd/agentd.go:217 +0x21b
{"component":"store","error":"etcdclient: no available endpoints","level":"error","member":8489119027689070460,"msg":"unhealthy cluster member","name":"sensu-backend3","time":"2021-01-16T00:02:50Z"}
{"component":"etcd","level":"error","msg":"failed to dial 4c98a5b754af677d on stream MsgApp v2 (dial tcp: lookup sensu-backend3 on 127.0.0.11:53: no such host)","pkg":"rafthttp","time":"2021-01-16T00:02:56Z"}

Requesting you look at the stability issues.

**Comment by amdprophet** [comment]
This can happen when the etcd client returns a `WatchError`. It seems like etcd was not available judging by the log line: `etcdclient:  no available endpoints`. A crash should not happen as a result of this and it should be considered a bug.

I ran into this exception myself this past week and I've implemented a fix that should go out with the 6.3.0 release.
https://github.com/sensu/sensu-go/compare/bump-etcd-go#diff-bf238bc8d1248a0fa763d9b9b3709d1302a0cd5b53005917b9d65abb8473fe76

**Comment by raihanchdy** [comment]
@amdprophet  For your reference sharing logs of the error.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf6c202]

goroutine 842469 [running]:
github.com/sensu/sensu-go/command.KillProcess(...)
github.com/sensu/sensu-go@v0.0.0-20210114171747-6c2b13310466/command/proc_unix.go:23
github.com/sensu/sensu-go/command.(*ExecutionRequest).Execute.func2()
github.com/sensu/sensu-go@v0.0.0-20210114171747-6c2b13310466/command/command.go:169 +0x62
created by time.goFunc
time/sleep.go:168 +0x44

FYI: I am using OSS version with etcd as data store.
