### ISSUE TITLE
Agent does not clean up failed asset downloads

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4180]
## Expected Behavior

Sensu agent gracefully handles asset download failures by deleting temporary files when a download fails.

## Current Behavior

Sensu agent does not delete temporary files when a download attempt exceeds a timeout.

## Context

Given a system with limited disk space and sufficiently slow or unreliable internet, it's possible for Sensu agent to fill the disk.

A customer reports that agent filled their disk with incomplete downloads and the agent log reflects messages indicative of a timeout being reached:

```
error getting assets for event: error fetching asset: Get https://example.com/asset.tgz: context canceled
```

![2021-01-20 at 4 44 PM](https://user-images.githubusercontent.com/148017/105254413-c3711480-5b3e-11eb-8664-bb7dd54524d9.png)

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.0.0
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04): Windows

**Comment by calebhailey** [comment]
Bumping this up to 6.5.0 as a "nice to have".
