### ISSUE TITLE
Incidents missing in dashboard

### ISSUE THREAD

**Issue by mjiderhamn** [sensu/sensu-go#4181]
## Expected Behavior
Events listed as not passing (`event.check.state != passing`) under `/c/~/n/*/events` should be included in `INCIDENTS` total and the `Incidents`, `Crit` and `Warn` columns of the dashboard.

## Current Behavior
Incidents are sometimes ignored. As an example, in our production system we current have one event in warning state, but the dashboard lists 0 `Incidents` for that namespace, regardless of whether I'm looking at all namespace or that particular namespace.

I can see that the `/graphql` endpoint returns 0. Is there an issue with the GraphQL API...?

## Steps to Reproduce (for bugs)
???

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.2.2
* Installation method (packages, binaries, docker etc.): docker
* Operating System and version (e.g. Ubuntu 14.04): n/a

**Comment by jamesdphillips** [comment]
Two things come to mind,

1. dashboard implementation may not be showing incidents properly (may be using the status field instead of state),
1. cache is updated on an interval, and either displaying stale data or under load is falling behind

Will investigate.

**Comment by portertech** [comment]
@mjiderhamn are you using the commercial distribution? If so, we also fixed a Postgres store bug in 6.2.5 where the state field index was empty.

**Comment by mjiderhamn** [comment]
@portertech , we don't have a commercial license (less than 100 entities) and don't use Postgres store.
