### ISSUE TITLE
"sensu asset update" does not work on assets installed with the rename (-r) flag

### ISSUE THREAD

**Issue by jsnod** [sensu/sensu-go#4189]
`sensu asset update <assetname>` does not work on assets which were installed with the `rename` (`-r`) flag. Instead it prompts for a `URL`.

## Expected Behavior
As asset installed with the `rename` flag should be able to be updated with `sensu asset update <assetname>`

## Current Behavior
It prompts for a URL instead of updating the already installed asset.

## Possible Solution
Derive the Bonsai URL from the renamed asset.

## Steps to Reproduce (for bugs)
1. Install an old version of an asset using the rename flag:
```bash
> sensuctl asset add sensu-plugins/sensu-plugins-aws:18.4.0 -r sensu-plugins-aws
```
2. Check for updates:
```bash
> sensuctl asset outdated
     Asset Name                Bonsai Asset             Current Version   Latest Version
 ─────────────────── ───────────────────────────────── ───────────────── ────────────────
  sensu-plugins-aws   sensu-plugins/sensu-plugins-aws   18.4.0            18.6.0
```
3. Try updating, notice it prompts for a URL. The interrupt is from me ctrl-C'ing out of the prompt.
```bash
> sensuctl asset update sensu-plugins-aws
? URL:
Error: interrupt
```
4. Try updating using the Bonsai Asset name, results in not found:
```bash
> sensuctl asset update sensu-plugins/sensu-plugins-aws
Error: not found
```

## Context
I'm unable to update to the latest version of assets. I'm unsure what the URL should be, but it seems that sensuctl should be smart enough to derive the URL from whatever is already installed.

The workaround is to completely remove the old asset and re-install the new one:
```bash
sensuctl asset delete sensu-plugins-aws
sensuctl asset add sensu-plugins/sensu-plugins-aws -r sensu-plugins-aws
```

## Your Environment
```bash
> sensuctl version
sensuctl version 6.2.3+ee, enterprise edition, build 56c4e71fe0b3c27fa8e622c4f56af9562e42651e, built 2021-01-20T23:42:31Z, built with go1.13.15
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H15
```

**Comment by calebhailey** [comment]
Thanks for this issue @jsnod – can you share the output of `sensuctl asset info sensu-plugins-aws --format yaml`? 

The `sensuctl asset update` command _should_ use asset metadata to determine the Bonsai asset URL (i.e. the `io.sensu.bonsai.url` annotation), so if that's there then I would classify this as a bug.

**Comment by jsnod** [comment]
> Thanks for this issue @jsnod – can you share the output of `sensuctl asset info sensu-plugins-aws --format yaml`?

Here you go @calebhailey:

```
17:00:11 [~] sensuctl asset info sensu-plugins-aws --format yaml
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu-plugins/sensu-plugins-aws
    io.sensu.bonsai.name: sensu-plugins-aws
    io.sensu.bonsai.namespace: sensu-plugins
    io.sensu.bonsai.tags: ruby-runtime-2.4.4
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-aws
    io.sensu.bonsai.version: 18.4.0
  created_by: admin
  name: sensu-plugins-aws
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    - entity.system.platform_family == 'rhel'
    headers: null
    sha512: b68da32e0e7228e2c1e81b3cbcdd0358fb099a9df68d6ded88222a252593107951f3ed3fe0ed7e49610a5631c397494c786e0a1e3ee9a47fa905bfa0c3db894e
    url: https://assets.bonsai.sensu.io/5f04e0fd667ec7b89b5a570c03528a476859b08c/sensu-plugins-aws_18.4.0_centos_linux_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    - entity.system.platform_family == 'debian'
    headers: null
    sha512: c057951d33aa1d4e952b2f781df452e55ab4b5f39cedc250ae209bc6630858797ffb82fc8e445e7efe50b269ece46a3aa74e45e4c2da6b31d3d8a4dbfdd3012a
    url: https://assets.bonsai.sensu.io/5f04e0fd667ec7b89b5a570c03528a476859b08c/sensu-plugins-aws_18.4.0_debian_linux_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    - entity.system.platform == 'alpine'
    headers: null
    sha512: e8ff3ac85cc7dbf8c6ebd6dc0500cffbc9ff3863a6ef6bbdc1a9926a3b4b3846c16cba291e9be9e35652038cdd929ed0222f3f1d8dace7a4a7295836b92d372d
    url: https://assets.bonsai.sensu.io/5f04e0fd667ec7b89b5a570c03528a476859b08c/sensu-plugins-aws_18.4.0_alpine_linux_amd64.tar.gz
  filters: null
  headers: null
```

**Comment by calebhailey** [comment]
@jsnod thanks! 👍

**Comment by jsnod** [comment]
Just tried updating `sensu-ruby-runtime` and hit this again:

```
> sensuctl asset update sensu-ruby-runtime
? URL:
Error: interrupt
```

Workaround:
```
> sensuctl asset delete sensu-ruby-runtime
> sensuctl asset add sensu/sensu-ruby-runtime -r sensu-ruby-runtime
```

**Comment by fguimond** [comment]
First the problem is still present in the current version. In addition to the assets created using the `-r` flag the problem is also present for assets added using `sensuctl add`, which uses Bonsai. The asset definitions [returned by Bonsai](https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-aws/versions/18.4.0) do not return the `url` property which is expected by the `sensuctl update` command. Instead of the URL appears to be present in the form of the `io.sensu.bonsai.url` annotation.

I see a few things that can be addressed:

1. Fix Bonsai to return a `url` property along with the asset definition
2. If not present set the `url` property when adding the asset
3. When updating the asset look for the annotation if the `url` property is not present

Note that unless the data is fixed option (3) will be required to allow updating existing assets.

**Comment by fguimond** [comment]
Currently there are two ways of creating an asset. 

The first one is to use `sensuctl asset create`, providing a URL to an asset archive and a SHA512 checksum, and optionally filters to include the platform. 

The second one is to use Bonsai and provide an asset namespace/name `sensuctl asset add <assetname>`. This workflow queries Bonsai for the asset definition which includes the builds for the supported platforms and stores that as is.

To update an asset created using `sensuctl asset create` one can use the `sensuctl asset update` command and interactively provide a new URL and SHA512. This command does not appear to support upgrading Bonsai assets.

For Bonsai assets all I could find was the `sensuctl asset outdated` command which lists the outdated assets but aside from recreating the asset (delete/add) I haven't found a way to update a Bonsai asset to the latest version.

In this case it appears that what the user is trying to do with `sensuctl asset update` is simply not supported at the moment.

A new issue will be created to implement a new command to upgrade Bonsai assets.
