### ISSUE TITLE
sensu backend does not provide api port 8080 anymore

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-go#4201]
## Expected Behavior

The sensu backend should run fine for days...

## Current Behavior

After a few days of operation, the sensu backend does not expose the api on port 8080 anymore. The logs look like this:
https://pastebin.com/FjQ6Psc2

## Steps to Reproduce (for bugs)

1. setup sensu in k8s
2. connect external etcd store
3. publish a lot of events
4.

## Context

We have an existing sensu classic env with a lot of clients and we try to migrate them to sensu go oss.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.2.5
* Installation method (packages, binaries, docker etc.): docker in k8s aws eks
* Operating System and version (e.g. Ubuntu 14.04): amazon linux ami for eks

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/sensu-classic-vs-sensu-go-scalability/2438/1

**Comment by portertech** [comment]
It seems etcd was overwhelmed with the load put onto the cluster, putting the cluster into an unrecoverable crash-loop. The postgres store is a feature designed to address the scaling issues around etcd, perhaps spin up a postgres instance and try to reproduce the issue once again?

**Comment by runningman84** [comment]
Does the oss version support postgres datastore at all? The etcd cluster running in k8s did not throw any error.

I do not think that the sensu-go free version with the 100 entity limit would suffer from any problem...

**Comment by portertech** [comment]
An OSS build does not contain the Postgres store.

**Comment by acrawly** [comment]
> An OSS build does not contain the Postgres store.

We tried scaling etcd to 7 nodes (using the embedded etcd install) and this issue still persisted with 19k events / 600 entities.

**Comment by echlebek** [comment]
We recently found and fixed an issue where Sensu was crashing and deadlocking on its way there. That issue has now been patched, so overloaded Sensu instances should crash properly instead of deadlocking.

**Comment by echlebek** [comment]
For context, here is the papertrail https://github.com/sensu/sensu-go/issues/4461
