### ISSUE TITLE
Am I using redact the wrong way ?

### ISSUE THREAD

**Issue by elfranne** [sensu/sensu-go#4231]
Using Puppet I added a couple of entries to redact that resulted in adding those 3 line to `/etc/sensu/agent.yml`
```yaml
redact:
- web_password
- db_read_password
```
You might notice that the formatting for arrays is not valid YAML(missing two spaces at the start of each array entry). Fixing the formatting has no effect and, for example the subscriptions is working fine: 
```yaml
subscriptions:
- system/linux
- system/linux/debian
- system/linux/virtual
```
(might be a bug to report to the Sensu Puppet repo)

Using a [debug handler](https://sensu.io/blog/using-a-debug-handler-with-sensu-go) I see that the output does not contains the newly added options: 

```json
    "redact": [
      "password",
      "passwd",
      "pass",
      "api_key",
      "api_token",
      "access_key",
      "secret_key",
      "private_key",
      "secret"
    ]
```
The agents and backend service have been restarted after the config update 

## Expected Behavior
Updated redact when changing the config. 

## Steps to Reproduce (for bugs)
1. add a key to redact in `/etc/sensu/agent.yml`
2. execute a check with debug output
3. check json for updated redact

## Context
I was trying to add checks using labels and redact to make those password not visible in the Web UI.

## Your Environment
sensuctl version 6.2.5
sensu-agent version 6.2.5
sensu-backend version 6.2.3
OS: Ubuntu 20.04 (agent) and Ubuntu 18.04 (backend)
Puppet 6.21.1

**Comment by flowerysong** [comment]
The generated list *is* valid YAML; the extra indentation that many people add is not actually required (because the `-` is counted as part of the indentation), so it will not usually be inserted by YAML serialisers and is discouraged by some style guides. See https://yaml.org/spec/1.1/#id931893

(I personally still add the spaces because *my* eyes don't read `- ` as whitespace, but it's not causing the issue you're having.)

**Comment by echlebek** [comment]
Please see https://docs.sensu.io/sensu-go/6.0/release-notes/#600-release-notes for why this is happening. As of 6.x, entities are first created via agent.yml but then must be managed through the API, unless you explicitly set configuration saying otherwise.

**Comment by elfranne** [comment]
thanks @echlebek  for pointing into the right direction. I ended up using the kinda-new `agent-managed-entity`
