### ISSUE TITLE
Agent events API requires that check is defined

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4232]
## Expected Behavior
I can send events to the agent events API that only include metrics.

## Current Behavior
The events API requires that a check is present.

## Possible Solution
Change how the payload is validated.

## Steps to Reproduce (for bugs)
1. Send an event carrying only metrics to the sensu-agent events API.

## Context
@portertech discovered this while innocently trying to use metrics.

**Comment by jspaleta** [comment]
Note:  right now from a backend tracking pov, event's effectively require a check with a name to be defined.
event api GET  requires entity name and check name 

https://docs.sensu.io/sensu-go/latest/api/events/#eventsentitycheck-get-specification

metrics only events could be made to flow through, but we'd have a very hard time tracking their processing right now, except for going into the backend logs looking for metrics handler errors.

**Comment by echlebek** [comment]
Metrics events aren't stored in the event store, so there is no way to get them anyways.

**Comment by calebhailey** [comment]
Good catch!
