### ISSUE TITLE
Nil maps are not correctly being represented

### ISSUE THREAD

**Issue by mgibson323** [sensu/sensu-go#4236]
When using `index` function in token substitution against an empty `labels` object, it does not correctly evaluate to `false`. 

## Expected Behavior

On a check that uses token substitution when executed on an entity with no labels, the following token substitution should return "foobar":

` '{{ index .labels "foo.bar" | default "foobar" }}'`

## Current Behavior

Token substitution returns this error: 

`error calling index: index of untyped nil`

## Context

Labels containing dots "`.`" must use the `index` function in token substitution.
Sensu internal reference: https://secure.helpscout.net/conversation/1460992000/25017?folderId=1211658

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): **6.2.5**
* Installation method (packages, binaries, docker etc.): **packages**
* Operating System and version (e.g. Ubuntu 14.04): **Ubuntu 20.04**

**Comment by calebhailey** [comment]
Thanks for filing!
