### ISSUE TITLE
Cron does schedule when using comma

### ISSUE THREAD

**Issue by elfranne** [sensu/sensu-go#4237]
Using a comma (in the day field) creates some unexpected scheduling of checks.

## Expected Behavior
Scheduling of checks according to the cron expression.

## Current Behavior
Scheduling stops after one execution.

## Possible Solution
Not sure if the issue is with sensu-go or the [cron library](https://github.com/robfig/cron).

## Steps to Reproduce (for bugs)
1. Create a check with `whoami` (for example) as command and a cron entry of either `* 9-17 * * 6,0` or `* 9-17 * * 6-0`
2. The cron entry with a comma will only execute a single time while the entry with dash executes every minute as expected.

## Context
I am trying to schedule different check during weekends and weekdays.

## Your Environment
sensuctl version 6.2.5
sensu-agent version 6.2.5
sensu-backend version 6.2.3
OS: Ubuntu 20.04 (agent) and Ubuntu 18.04 (backend)
Puppet 6.21.1

**Comment by portertech** [comment]
Closed by #4311
