### ISSUE TITLE
Changelog for 6.2.6 is missing

### ISSUE THREAD

**Issue by boutetnico** [sensu/sensu-go#4244]
Hello!
This is a friendly request for adding version 6.2.6 in the changelog.
This version was tagged on this repo but was not added in https://github.com/sensu/sensu-go/blob/main/CHANGELOG.md.
Thank you.

**Comment by ccressent** [comment]
Hi @boutetnico,

There is actually no change to `sensu-go` between `6.2.3` and `6.2.6`. Everything listed as "unreleased" there has indeed not been released yet.

`6.2.{4,5,6}` have been patch releases that only affected `sensu-enterprise-go`. `sensu-enterprise-go` uses `sensu-go`, this repository, as a dependency and we keep them both tagged in lockstep. This is sort of a wart in our release process that means that this repository can get new version tags even though they all point to the same commit.

Sorry for the confusion; we'll look into making that clearer in the change log when such situations occur.
