### ISSUE TITLE
Odd behaviour when RBAC roles cannot be resolved

### ISSUE THREAD

**Issue by ccressent** [sensu/sensu-go#4268]
When a `ClusterRoleBinding` refers to a non existent `Role` or `ClusterRole` it leads to odd behaviour in the WebUI and unhelpful error messages in the CLI.

I suspect that `RoleBinding` suffers from the same issue.

## Expected Behavior

The user gets as clear an error as possible when something doesn't go well. At least enough to be able to continue investigating instead of being dumbfounded.

## Current Behavior

- In the CLI, most operations result in an error: `unexpected error occurred during authorization`
- In the WebUI, we're told the session has expired and we are prompted to log in again, _ad infinitum_

## Possible Solution

Generally: warn about "missing references" when creating objects (that can't be an error though, since objects can be created in arbitrary order; think of `sensuctl create` being fed the content of a directory for example)

Specifically: handle this error in the authorizer or its middleware so that it gives a more precise error message instead of the generic "unexpected authorization error" on the CLI and "Session expired" popup in the WebUI.

## Steps to Reproduce (for bugs)

1. Create a `ClusterRoleBinding` that refers to a non-existent `ClusterRole`
2. Log in as a user that's a subject of the binding and try to perform operations that require any type of permission

## Context

This was observed while testing an OIDC setup. Everything worked once we finally realized that we were giving the Cluster Role Binding we were trying to setup a reference to a `Role` instead of a `ClusterRole`: `role_ref.type = "Role"` instead of `role_ref.type = "ClusterRole"`.

Through a bit of luck, the output of `sensuctl namespace list` hinted at what the problem was and we were able to solve it pretty quickly from there.

## Your Environment

* Sensu version used: `df4abb44d5b73424423bbb7534bc35d47ff14d1e` but all versions affected.

**Comment by portertech** [comment]
I am in favour of the second suggested possible solution:

````
Specifically: handle this error in the authorizer or its middleware so that it gives a more precise error message instead of the generic "unexpected authorization error" on the CLI and "Session expired" popup in the WebUI.
