### ISSUE TITLE
Unhealthy keepalives appear to only be checked every keepalive-warning-timeout interval

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#4272]
## Expected Behavior
A critical keepalive event should be generated after the given `keepalive-critical-timeout` interval.

## Current Behavior
When using the following options:
```
--keepalive-warning-timeout 10 --keepalive-critical-timeout 15
```

a warning keepalive event is correctly generated around 10 seconds but a critical keepalive event isn't generated until around 20s.

## Steps to Reproduce (for bugs)
1. Use the flags from the Current Behavior section.
2. Wait 15 seconds.
3. Observe no critical keepalive event.
4. Wait another 5 seconds or so.
6. Observe that a critical keepalive event has been created.
7. Check the keepalive event history and observe that the `executed` field is ~10s apart.

**Comment by ccressent** [comment]
I've ping-ponged quite a bit over what to do with this issue, but after reviewing the behaviour, the code and the documentation, I think there is no issue here and this is working as expected. The description for these agent flags in the `--help` output could be improved though.

See:
- [Agent Reference - Keepalive Monitoring](https://docs.sensu.io/sensu-go/6.2/observability-pipeline/observe-schedule/agent/#keepalive-monitoring)
- [Agent Reference - Keepalive Configuration Flags](https://docs.sensu.io/sensu-go/6.2/observability-pipeline/observe-schedule/agent/#keepalive-configuration-flags)
