### ISSUE TITLE
Use separate websocket connections for keepalive events and check events

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4273]
To improve stability, we should use separate websocket connections between the backend and agents for keepalive events and check events.

Rationale:
* Keepalive and check event delivery have different stability outcomes.
* If keepalives cannot be delivered because of a backlog of events, then the system can destabilize.
* The backend needs to be able to create backpressure on agents so that it can prevent too many check events from overwhelming it.
* The backend needs to receive timely keepalive events from the agents, so that they won't be marked as failing.

Proposal:
* Add two new routes to the backend's agent API: /ws/events and /ws/keepalives. Preserve the original /ws route for backwards compatibility.
* When an agent connect to /ws/events, set up a session for events. When an agent connects to /ws/keepalives, set up a session for keepalives.
* When an agent connects to /ws, behave as before.
* ~When the agent receives back pressure on /ws/events such that new check events can't be sent, then the agent should report a keepalive warning to the backend that the backend is overloaded. (This is different than the backend's switch timing out for the agent!)~

Additional considerations:
* The agent may connect to two different physical backends, if the connection is mediated using a load balancer. Implementations should not assume that both connections will be to the same backend.
* There will be independent websocket timeouts for each connection. We can't make any assumptions about one connection given the state of another.
* ~Keeaplived will still be subject to backpressure from eventd, by virtue of sending the event there after resetting the keepalive switch. To fully realize the value of this change, we'll need to come up with a way to avoid blocking there, either via dropping events or prioritizing keepalive events over check events.~ (To become its own issue)

**Comment by ccressent** [comment]
Experimental work was done in https://github.com/sensu/sensu-go/pull/4323, but the usefulness of doing this was not proven.
We have decided to shelve the idea for now, to be revived later.

**Comment by c-kruse** [comment]
We're back just about 1 year later! Hope you all have a good memory.

I recently stumbled on some [eventd code](https://github.com/sensu/sensu-go/blob/v6.7.3/backend/eventd/eventd.go#L399-L413) that appeared to be attempting to prioritize keepalive event processing, but is actually not doing anything. Asking questions lead me back here.

It appears to me that the eventd keepalive prioritization was never fully hooked up (confirmed on Cyril's branch), and could be the reason that two web sockets was not measurably different than one.

@echlebek @ccressent  do we want to revisit this idea?
