### ISSUE TITLE
Add separate points of ingress for keepalives into eventd

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#4292]
## Feature Suggestion
To reduce the chance of a keepalive event creation storm & mass agent disconnect, we should prioritize keepalive events from agents over other events. We can achieve this by adding a second point of ingress to eventd specifically for keepalive events. Process all keepalives in the buffer before processing other events.

**Comment by portertech** [comment]
From slack:

```
for {
  select {
    case event := <-eventQueue:
      for keepalive := range keepaliveQueue {
        handle(keepalive)
      }
      handle(event)
    case keepalive <-keepaliveQueue:
      handle(keepalive)
  }
}
```

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu-go/issues/4273

**Comment by portertech** [comment]
This landed on main.
