### ISSUE TITLE
Add event size histogram metrics

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4298]
## Feature Suggestion

Instrument the backend to measure bytes/s received/processed by `eventd`. 

## Possible Implementation

We've done this before! https://github.com/sensu/sensu-go/blob/6555322be77ff04b2a176a13be694868e408fa09/backend/eventd/eventd.go#L89-L96

1. Measure event bytes/s in two places, agentd sessions, and the store. Use metric labels to indicate if the event(s) will be persisted etc (contains a check resource).

   - Agent event bytes/s for events w/ check data (aggregated)
   - Agent event bytes/s for events w/ metrics data (aggregated)
   - Agent event bytes/s for events w/ check+metrics data (aggregated)
   - Store event bytes/s for events w/ check data
   - Store event bytes/s for events w/ metrics data
   - Store event bytes/s for events w/ check+metrics data

2. Add event size histogram metrics to metrics logger (see #4299)

## Context

We have observed that some customers are processing unusually large event payloads, in which case certain deployment/architecture considerations may need to be taken to tune the system for optimal performance. Evaluating events/s throughput with the additional context of bytes/s will help identify these opportunities if a user experiences degraded performance.

**Comment by portertech** [comment]
We need a histogram of event payload sizes.

**Comment by portertech** [comment]
We've done this before! https://github.com/sensu/sensu-go/blob/6555322be77ff04b2a176a13be694868e408fa09/backend/eventd/eventd.go#L89-L96

**Comment by portertech** [comment]
We need to:

- label metric to indicate if the event will be persistent (contains a check resource)

We should consider:

- emit metrics from agent sessions as the events come in over the transport (lacking event history)

**Comment by portertech** [comment]
I'll update the issue details to be more specific.

**Comment by calebhailey** [comment]
@portertech notes from our [6/28 meeting](https://docs.google.com/document/d/1ozfPtJDD9ySbikRKZJT7OXDxz3Oeata0-4Zum5kvZzc/edit): 

- Agent event bytes/s for events w/ check data (aggregated)
- Agent event bytes/s for events w/ metrics data (aggregated)
- Agent event bytes/s for events w/ check+metrics data (aggregated)
- Store event bytes/s for events w/ check data 
- Store event bytes/s for events w/ metrics data
- Store event bytes/s for events w/ check+metrics data
