### ISSUE TITLE
Periodic logging of key platform metrics

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4299]
## Feature Suggestion

Sensu Go already provides a /metrics API, a Prometheus exporter that makes certain Sensu performance metrics available in Prometheus exposition format. 

It would be helpful if some ~~or all~~ of these same metrics were emitted via a log file (e.g. stats.log) for evaluation and troubleshooting without external tooling.

## Possible Implementation

~Proposed key metrics (I'm sure I'm missing some):~

~- **events/s**~
~- **bytes/s** (see https://github.com/sensu/sensu-go/issues/4298)~
~- **buffered event stats** (quantity and perhaps also bytes?)~

Please note the following requirements, which are the result of our [6/28 meeting](https://docs.google.com/document/d/1ozfPtJDD9ySbikRKZJT7OXDxz3Oeata0-4Zum5kvZzc/edit): 

Requirements: 

1. New `--disable-platform-metrics` flag (i.e. making platform metrics logging an opt-out)

1. New `--platform-metrics-logging-interval` flag with a default value of `60` (seconds)

1. New `--platform-metrics-log-file` flag with a default value of `< --state-dir >/stats.log`

1. New `--platform-metrics-format` flag with a default value of `influxdb_line`

1. Use the existing Unix signal for log rotation reopen, copy logic used in the event logger feature

1. List of metrics to log

   Three major components to collect metrics from: WizardBus, Agents per backend, Etcd (disk sync speed, memory usage, etc). 

   **WizardBus Metrics**

   - `sensu_go_wizard_bus{topic="sensu:event-raw"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2700))
   - `sensu_go_wizard_bus{topic="sensu:event"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2707))
   - `sensu_go_wizard_bus{topic="sensu:keepalive"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2714))
   - `sensu_go_wizard_bus{topic="sensu:check"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2721))
   - `sensu_go_wizard_bus{topic="sensu:entity-config:default:sensu-centos"}` 

   **Backend Metrics**
   
   - `sensu_go_event_handler_duration` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L81))
   - `sensu_go_events_processed` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L175))
   - `sensu_go_events_processed{status="success"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L270))
   - `sensu_go_events_processed{status="failure"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L277))
   - `sensu_go_agent_sessions`
   
   **Etcd Metrics**

   - `etcd_debugging_mvcc_keys_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L371))
   - `etcd_debugging_mvcc_delete_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L465))
   - `etcd_debugging_mvcc_put_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L473))
   - `etcd_debugging_mvcc_range_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L481))
   - `etcd_debugging_mvcc_txn_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L489))
   - `etcd_debugging_mvcc_db_total_size_in_bytes` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L587))
   - `etcd_disk_wal_fsync_duration_seconds_bucket` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L687))
   - `etcd_disk_backend_commit_duration_seconds_bucket` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L697))
   - `etcd_network_client_grpc_received_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1627))
   - `etcd_network_client_grpc_sent_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1726))
   - `etcd_network_peer_received_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1825))
   - `etcd_network_peer_sent_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1926))
   - `etcd_snap_db_fsync_duration_seconds_bucket`

**Comment by calebhailey** [comment]
Todo: 

- Finalize decision to make this an "opt-out" feature
- Finalize list of metrics (which is more than outlined in the issue description above, but fewer than every metric available at /metrics) 
- Estimate metric payload size (how many bytes per log line?)
- Use payload size data to decide logging interval

**Comment by calebhailey** [comment]
Assigning this one to myself until we have collected answers to these questions ☝️

**Comment by calebhailey** [comment]
Please note the following requirements, which are the result of our [6/28 meeting](https://docs.google.com/document/d/1ozfPtJDD9ySbikRKZJT7OXDxz3Oeata0-4Zum5kvZzc/edit): 

Requirements: 

1. New `--disable-platform-metrics flag` (i.e. making platform metrics logging an opt-out)

1. New `--platform-metrics-logging-interval` flag with a default value of `30` (seconds)

1. New `--platform-metrics-log-file` flag with a default value of ??? 

1. List of metrics to log

   Three major components to collect metrics from: WizardBus, Agents per backend, Etcd (disk sync speed, memory usage, etc). 

   **WizardBus Metrics**

   - `sensu_go_wizard_bus{topic="sensu:event-raw"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2700))
   - `sensu_go_wizard_bus{topic="sensu:event"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2707))
   - `sensu_go_wizard_bus{topic="sensu:keepalive"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2714))
   - `sensu_go_wizard_bus{topic="sensu:check"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2721))
   - `sensu_go_wizard_bus{topic="sensu:entity-config:default:sensu-centos"}` 

   **Pipeline Metrics**
   
   - `sensu_go_event_handler_duration` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L81))
   - `sensu_go_events_processed` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L175))
   - `sensu_go_events_processed{status="success"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L270))
   - `sensu_go_events_processed{status="failure"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L277))
   - New "bytes/s" metrics (see #4298)
   
   **Etcd Metrics**

   - `etcd_debugging_mvcc_keys_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L371))
   - `etcd_debugging_mvcc_delete_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L465))
   - `etcd_debugging_mvcc_put_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L473))
   - `etcd_debugging_mvcc_range_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L481))
   - `etcd_debugging_mvcc_txn_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L489))
   - `etcd_debugging_mvcc_db_total_size_in_bytes` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L587))
   - `etcd_disk_wal_fsync_duration_seconds_bucket` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L687))
   - `etcd_disk_backend_commit_duration_seconds_bucket` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L697))
   - `etcd_network_client_grpc_received_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1627))
   - `etcd_network_client_grpc_sent_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1726))
   - `etcd_network_peer_received_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1825))
   - `etcd_network_peer_sent_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1926))
   - `etcd_snap_db_fsync_duration_seconds_bucket`
   
   **Host & Other Metrics** (TBD)

   - `node_cpu_seconds_total{mode="system"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1199))
   - `node_cpu_seconds_total{mode="user"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1208))
   - `node_cpu_seconds_total{mode="iowait"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1217))
   - `node_cpu_seconds_total{mode~".*irq"}` as "Busy IRQs" ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1225))
   - `node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}` as "Busy Other" ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1233))
   - `node_cpu_seconds_total{mode="idle"}` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1225))
   - `node_memory_MemTotal_bytes` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1383))
   - `node_memory_MemTotal_bytes - node_memory_MemFree_bytes` as "RAM Used" ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1392))
   - `node_memory_Cached_bytes + node_memory_Buffers_bytes` as "RAM Cache + Buffer" ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1401))
   - `node_memory_MemFree_bytes` as "RAM Free" ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1409))
   - `node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes` as "SWAP Used" ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1417))
   - `process_resident_memory_bytes` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L1514))
   - `node_network_receive_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2087))
   - `node_network_transmit_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2095))
   - `grpc_server_started_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2192))
   - `grpc_server_handled_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2201))
   - `node_disk_reads_completed_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2403))
   - `node_disk_writes_completed_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2411))
   - `node_disk_read_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2596))
   - `node_disk_written_bytes_total` ([source](https://github.com/sensu/sensu-perf/blob/main/grafana/Sensu_Benchmarks-1562276016486.json#L2604))

**Comment by portertech** [comment]
Perhaps we should spec a field to select the output line format and ship it with one option for now.

**Comment by portertech** [comment]
We should default the log file location to the state directory.

**Comment by calebhailey** [comment]
Updated the issue description with the actual spec/plan. :+1:

**Comment by calebhailey** [comment]
Removed #4298 and #4239 from this issue so that we can complete an initial implementation with existing metrics, then extend that implementation as #4298 and #4239 are completed. I also update the descriptions of #4298 and #4239 accordingly. 👍

**Comment by echlebek** [comment]
The total set of metrics that we expose in our prometheus endpoint is probably too much information to write out to this file but I feel we should probably export all of the sensu_go metrics. The full list:

```
# HELP sensu_go_agent_sessions Number of active agent sessions on this backend
# TYPE sensu_go_agent_sessions gauge
sensu_go_agent_sessions{namespace="default"} 1
# HELP sensu_go_build_info Sensu Go build information
# TYPE sensu_go_build_info gauge
sensu_go_build_info{buildsha="",goversion="go1.15.7",version=""} 1
# HELP sensu_go_bus_message_duration message publish latency distributions
# TYPE sensu_go_bus_message_duration summary
sensu_go_bus_message_duration{topic="sensu",quantile="0.5"} 0.00781
sensu_go_bus_message_duration{topic="sensu",quantile="0.9"} 0.01037
sensu_go_bus_message_duration{topic="sensu",quantile="0.99"} 0.01474
sensu_go_bus_message_duration_sum{topic="sensu"} 1872.8122630000714
sensu_go_bus_message_duration_count{topic="sensu"} 264786
# HELP sensu_go_bus_messages_published The total number of messages published to wizard bus
# TYPE sensu_go_bus_messages_published counter
sensu_go_bus_messages_published{topic="sensu"} 256938
# HELP sensu_go_event_handler_duration event handler latency distribution
# TYPE sensu_go_event_handler_duration summary
sensu_go_event_handler_duration{quantile="0.5"} 0.666542
sensu_go_event_handler_duration{quantile="0.9"} 0.751423
sensu_go_event_handler_duration{quantile="0.99"} 0.843933
sensu_go_event_handler_duration_sum 58431.669254001274
sensu_go_event_handler_duration_count 85645
# HELP sensu_go_event_handlers_busy The number of event handlers currently processing
# TYPE sensu_go_event_handlers_busy gauge
sensu_go_event_handlers_busy 0
# HELP sensu_go_events_processed The total number of processed events
# TYPE sensu_go_events_processed counter
sensu_go_events_processed{status="error",type="check"} 0
sensu_go_events_processed{status="error",type="unknown"} 0
sensu_go_events_processed{status="success",type="check"} 85645
sensu_go_events_processed{status="success",type="metrics"} 0
# HELP sensu_go_interval_schedulers Number of active interval check schedulers on this backend
# TYPE sensu_go_interval_schedulers gauge
sensu_go_interval_schedulers{namespace="default"} 2
# HELP sensu_go_keepalives The total name of processed keepalives
# TYPE sensu_go_keepalives counter
sensu_go_keepalives{status="alive"} 4079
sensu_go_keepalives{status="dead"} 0
# HELP sensu_go_websocket_upgrade_duration websocket upgrade latency distribution
# TYPE sensu_go_websocket_upgrade_duration summary
sensu_go_websocket_upgrade_duration{quantile="0.5"} NaN
sensu_go_websocket_upgrade_duration{quantile="0.9"} NaN
sensu_go_websocket_upgrade_duration{quantile="0.99"} NaN
sensu_go_websocket_upgrade_duration_sum 0.552142
sensu_go_websocket_upgrade_duration_count 1
# HELP sensu_go_wizard_bus Number of elements in a topic
# TYPE sensu_go_wizard_bus gauge
sensu_go_wizard_bus{topic="sensu:check:default:test"} 0
sensu_go_wizard_bus{topic="sensu:entity-config:default:da2"} 0
sensu_go_wizard_bus{topic="sensu:event"} 0
sensu_go_wizard_bus{topic="sensu:event-raw"} 0
sensu_go_wizard_bus{topic="sensu:keepalive"} 0
```

I was thinking it would be a good idea to log all of the etcd metrics too, but the etcd metrics are extremely rich and include grpc metrics, totallying 175KB.

**Comment by calebhailey** [comment]
New metrics we've added since 6.5.0: 

* sensu_go_handler_requests (6.5.1)
* sensu_go_handler_requests_total (6.5.1)
* sensu_go_event_handler_duration_sum (6.5.2)
* sensu_go_event_handler_duration_count (6.5.2)
* sensu_go_event_handler_duration (6.5.2)
* sensu_go_pipelined_message_handler_duration (6.5.2)
* sensu_go_pipeline_duration (6.5.2)
* sensu_go_pipeline_resolve_duration (6.5.2)
* sensu_go_pipeline_filter_duration (6.5.2)
* sensu_go_pipeline_mutator_duration (6.5.2)
* sensu_go_pipeline_handler_duration (6.5.2)
* sensu_go_eventd_create_proxy_entity_duration (6.5.2)
* sensu_go_eventd_update_event_duration (6.5.2)
* sensu_go_eventd_bus_publish_duration (6.5.2)
* sensu_go_eventd_liveness_factory_duration (6.5.2)
* sensu_go_eventd_switches_alive_duration (6.5.2)
* sensu_go_eventd_switches_bury_duration (6.5.2)
* sensu_go_asset_fetch_duration (6.5.2)
* sensu_go_asset_expand_duration (6.5.2)
* sensu_go_lease_ops (6.5.5)
* graphql_duration_seconds (6.5.5) 
* graphql_duration_seconds_sum (6.5.5)
* graphql_duration_seconds_count (6.5.5)
* graphql_duration_seconds (6.5.5)
* sensu_go_event_metric_points_processed (6.6.4)

**Comment by hillaryfraley** [comment]
`sensu_go_etcd_cluster_leases` was added in 6.7.0 (I didn't see it listed here already)
