### ISSUE TITLE
the initial entity config was never received, using the local entity sensu go

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4301]
In a running sensu cluster the issue is suddenly coming where sensu agents are not able to connect sensu server.

below is the error:
the initial entity config was never received, using the local entity sensu go

{"component":"agent","error":"Connection error: read tcp 10.84.1.243:53114-\u003e10.84.2.251:3031: i/o timeout","level":"error","msg":"transport receive error","time":"2021-05-28T06:55:16Z"}

**Comment by portertech** [comment]
This looks like a configuration error, e.g. `10.84.1.243:53114-\u003e10.84.2.251:303`, there should only be a single address. For help with your configuration, please head on over to the Sensu Community Slack or Discourse.
