### ISSUE TITLE
sensu-backend CPU usage at 200%, lots of "took too long" messages

### ISSUE THREAD

**Issue by koo5** [sensu/sensu-go#4303]
i'm experimenting with sensu like this:
```docker run  --rm --name sensu-backend \           
      --network sensu -p 8080:8080 -p 3000:3000 \
      -v sensu-backend-data:/var/lib/sensu \
      sensu/sensu:6.2.7 sensu-backend start
```
today, after resuming my computer from sleep, i get this.

## Expected Behavior

normal cpu usage.

## Current Behavior

permanent 200% cpu usage

## Possible Solution

no idea.

[sensu_log.txt](https://github.com/sensu/sensu-go/files/6568520/sensu_log.txt)

**Comment by portertech** [comment]
It looks like etcd and lease timeouts, this is to be expected when sleeping a host. As this is not a normal operating condition, we won't fix.
