### ISSUE TITLE
dashboard not working

### ISSUE THREAD

**Issue by kylehz** [sensu/sensu-go#4306]
dashboard not working

## Expected Behavior
sensu-backend start and dashboard listening on 3000

## Current Behavior
when sensu-backend start, dashboard not start

## Possible Solution
bug

## Steps to Reproduce (for bugs)
1.build on macos
2.sudo curl -L https://docs.sensu.io/sensu-go/latest/files/backend.yml -o configs/backend.yml
3../bin/sensu-backend start -c configs/backend.yml

## Context
try to use sensu

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): sensu-backend version (devel)+ce, community edition, built with go1.16.3
* Installation method (packages, binaries, docker etc.): CGO_CFLAGS=-Wno-undef-prefix go build -o bin/sensu-backend ./cmd/sensu-backend
* Operating System and version (e.g. Ubuntu 14.04): Darwin MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by jamesdphillips** [comment]
Hey @kylehz! Due to a feature freeze of the open-source dashboard, it is not longer embedded in the open-source release of Sensu. See [INSTALL.md](https://github.com/sensu/web/blob/master/INSTALL.md) for more information regarding running the open-source dashboard.
