### ISSUE TITLE
Bug  internally generated deregistration events are invalid events

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#4307]
deregistration events fail the event validation function from api/core/v2
Specifically the event validation function calls the check validation function which requires non-empty string subscriptions

Discovered using the email handler based on the plugin sdk which does event validation using the api/code/v2 event validation function.

## Expected Behavior
deregistration events should validate as valid events.

## Current Behavior
deregistration events fail to validate because the event as created by the backend contains a "" subscription in the subscriptions array instead of just an empty subscriptions array. 

This is invalid according the the core/v2 event validation function. All subscription names must be non-empty strings.

## Possible Solution
Refactor how deregistration events are generated so that they do not include a "" subscription.  

We probably also need to add a reusable de-registration event fixture for testing, that generates a dereg event as well to ensure valid dereg event creation works as expected

## Steps to Reproduce (for bugs)
1. use sensu-email-handler with de-registration event
2. watch it fail to validate
3. capture dereg event and save to file
4. notice the event captured to file has a zero length "" subscription string in the event's check's subscription array.
5. Compare to keepalive event from `sensuctl event info`, notice empty subscriptions array in check section

**Comment by jspaleta** [comment]
I also have to wonder if the same problem is occurring with keepalive events as well.

**Comment by agoddard** [comment]
here is a sample deregistation event:
```
{
  "check": {
    "handlers": [
      "email"
    ],
    "high_flap_threshold": 0,
    "interval": 1,
    "low_flap_threshold": 0,
    "publish": false,
    "runtime_assets": null,
    "subscriptions": [
      ""
    ],
    "proxy_entity_name": "",
    "check_hooks": null,
    "stdin": false,
    "subdue": null,
    "ttl": 0,
    "timeout": 0,
    "round_robin": false,
    "executed": 0,
    "history": null,
    "issued": 0,
    "output": "",
    "status": 1,
    "total_state_change": 0,
    "last_ok": 0,
    "occurrences": 0,
    "occurrences_watermark": 0,
    "output_metric_format": "",
    "output_metric_handlers": null,
    "env_vars": null,
    "metadata": {
      "name": "deregistration",
      "namespace": "default"
    },
    "secrets": null,
    "is_silenced": false,
    "scheduler": ""
  },
  "entity": {
    "entity_class": "agent",
    "system": {
      "hostname": "sensu-agent",
      "os": "linux",
      "platform": "alpine",
      "platform_family": "alpine",
      "platform_version": "3.12.3",
      "network": {
        "interfaces": [
          {
            "name": "lo",
            "addresses": [
              "127.0.0.1/8"
            ]
          },
          {
            "name": "eth0",
            "mac": "08:42:ac:16:00:04",
            "addresses": [
              "172.22.0.5/16"
            ]
          }
        ]
      },
      "arch": "amd64",
      "libc_type": "musl",
      "vm_system": "docker",
      "vm_role": "guest",
      "cloud_provider": "",
      "processes": null
    },
    "subscriptions": [
      "dev",
      "poller",
      "system",
      "linux",
      "docker",
      "entity:sensu-agent"
    ],
    "last_seen": 1623101211,
    "deregister": true,
    "deregistration": {
      "handler": "email"
    },
    "user": "agent",
    "redact": [
      "password",
      "passwd",
      "pass",
      "api_key",
      "api_token",
      "access_key",
      "secret_key",
      "private_key",
      "secret"
    ],
    "metadata": {
      "name": "sensu-agent",
      "namespace": "default"
    },
    "sensu_agent_version": "6.2.3"
  },
  "id": "cdd4ec65-3a6b-4732-ac44-7b0a40aff0c2",
  "metadata": {},
  "sequence": 0,
  "timestamp": 1623101331
}

```

**Comment by calebhailey** [comment]
Notes: 

- There may have been a recent change in event validation that is causing this behavior (TBD if this is a regression); we'll look into this 
- We can at least update the event generated for deregistration such that we no longer produce an (invalid) event.check.subscriptions slice containing an empty string subscription (""). 
- It may also be appropriate to make a small change in event validation logic 
- We will add this to the list of agenda items RE: core/v3.Event design considerations
