### ISSUE TITLE
Add support for external etcds that use username/password authentication

### ISSUE THREAD

**Issue by atomicules** [sensu/sensu-go#4316]
Add support for external etcds that use username/password authentication. I.e. instead of supplying an argument of `--etcd-client-cert-auth` we can start the backend using arguments of `--etcd-client-username` and `--etcd-client-password` that will be used to authenticate to the external etcd.

## Feature Suggestion

See Possible Implementation.

## Possible Implementation

[Branch here](https://github.com/atomicules/sensu-go/tree/external-etcd-user-pass-auth). This has been tested both via simple `start` and `init` and in "production". Per the Contributing guidelines I am creating an issue before PR'ing.

Notes on that branch:

- There are no tests for this feature request
- Position of code changes, names used, etc can be changed as required
- I'm not totally happy with the `if {} else {}` config setup. Maybe that could be streamlined by appending a config? Not sure how possible that is.

## Context

I want to be able to use an external etcd from a DBaaS provider. These typically support username/password authentication and not client certificate authentication.

**Comment by portertech** [comment]
GitHub compare https://github.com/atomicules/sensu-go/compare/main...external-etcd-user-pass-auth

**Comment by portertech** [comment]
Ideally `username` and `password` configuration should be done via environment variables. The Sensu eng team has regrets in regards to use CLI arguments for sensitive information.

**Comment by atomicules** [comment]
That sounds reasonable/sensible. Is that a "only configurable via environment variables" request or "also configurable via environment variables"?

**Comment by atomicules** [comment]
Ah... viper gets us automatic env vars so we can do this already:

```
SENSU_BACKEND_ETCD_CLIENT_USERNAME=someone
SENSU_BACKEND_ETCD_CLIENT_PASSWORD=something
```

So do I need to change it so that they can _only_ be set via env vars?

**Comment by portertech** [comment]
@atomicules yes, we don't want to create an opportunity for the sensitive information to leak via the process table etc.

**Comment by atomicules** [comment]
Add [this commit](https://github.com/atomicules/sensu-go/commit/c86fde4b3cd7ef3608e01dc3dd542db208995262) to address this. Removes the flags and only allows user/pass to be set by environment variables.

I haven't yet updated that branch to main, thought I'd wait on further feedback.

**Comment by echlebek** [comment]
@atomicules Hello! :wave: We'd like to work on integrating your branch. Can you please make a pull request? Thanks so much for your efforts on this.

**Comment by atomicules** [comment]
Created a PR here: https://github.com/sensu/sensu-go/pull/4381
