### ISSUE TITLE
Use more aggressive exponential backoff for agents when the server responds with HTTP 429

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4328]
In some circumstances, sensu-backend can respond with HTTP 429. In the enterprise product, this status is delivered when the cluster has reached its entity limit. But HTTP 429 can be delivered by other means too, for instance if there are load balancers in the mix, or if sensu-go's backend starts using HTTP 429 to indicate that the service is oversubscribed.

Currently, sensu-agent is quite aggressive in its retries and we should use the 429 information to mellow it out somewhat, increasing the length of the retry time.

More generally, the agent should permit configuring backoff/retry parameters directly, so that users can configure agents to behave as desired in terms of reconnections.

**Comment by calebhailey** [comment]
@echlebek I understand that a PR may already be in progress for this issue, but could you comment on whether "increasing the length of the retry time" aligns with the following feedback: 

> can we solve this problem by an exponential backoff where the max_backoff is 1-2 minutes and we adjust the 'random' milliseconds also between 1-5sec after the initial failure? Something like:
> 
> 1. initial connect = 0 + random (0-1 sec)
> 2. next retry = 1 + random (0-1 sec)
> 3. next retry = 2 + random (0-5 sec) << note the increase of random
> 4. next retry 4 + random (0-5 sec)

If the new default doesn't work like this, what will the interface be for making it configurable? Would a user provide a list of retry intervals (e.g. `--reconnect-retries="1,2,5,10,15,30,60,90,120,300"`)?
