### ISSUE TITLE
Random checks are not getting executed

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4330]
I have more than 200 checks running on sensu 3 node cluster. Randomly some of the checks are not getting exeuted. 

![image](https://user-images.githubusercontent.com/31199957/123064795-381ce780-d42c-11eb-8b07-3cfd59ad3d09.png)

This check is scheduled to run every 5 minutes but the events showing that the check executed 2 hours ago which I ran executed manually from the UI.

Please help to fix the issue

**Comment by mcbsd** [comment]
How do you expect Sensu guys to help if you don't provide enough details?
You even did not follow the template where you find guidance what details to fill...

Anyway, we experienced this several times as well (no issue submitted from our side yet).

**Comment by calebhailey** [comment]
@raihanchdy we will need more information to determine if this is a bug or a simple configuration issue. Can you first of all check to see if there are any agent entities configured with the `roundrobin:worker` subscription? The following command should help: 

```shell
sensuctl entity list --field-selector='"roundrobin:worker" IN entity.subscriptions'
```

_NOTE: in Sensu Go it is no longer necessary to prefix subscriptions with `roundrobin:`, so your `roundrobin:worker` subscription is not being parsed or having any other special handling applied to it; I'll assume this is a vestige remaining after migrating configs from Sensu Core._

**Comment by raihanchdy** [comment]
@calebhailey 
Please find the output if the command 
    sensuctl entity list --field-selector='"roundrobin:worker" IN entity.subscriptions'
![image](https://user-images.githubusercontent.com/31199957/129549003-f9ae0af4-94c2-4ec7-b43f-7519f1b10c0d.png)

All of a sudden most of the proxyclient checks stopped execution
The check I shared was running but all of a sudden its not even executing
![image](https://user-images.githubusercontent.com/31199957/129549151-f904575d-843f-42d8-b836-366650c4ee4c.png)

![image](https://user-images.githubusercontent.com/31199957/129549202-bfe0bf22-1109-4fc9-bf03-1b567c083618.png)

**Comment by raihanchdy** [comment]
@calebhailey 
More Info:
A check is scheduled to execute every 2 hours but all of a sudden the check stopped execution. 

Workaround:
Changed the time interval to 2 minutes and recreated the check and then check started executing by sensu.

Not getting any idea, how this can be possible

**Comment by raihanchdy** [comment]
@calebhailey I installed sensu 6.4.0 and the issue still persists where checks are not executing at their specified interval. Sensu is mostly used for executing checks and if checks itself aren't executing then its a huge issue. My kind request is can you please look into it and let me know if you need more details.

**Comment by raihanchdy** [comment]
@calebhailey There is no such fix in the latest releases. I installed latest release and still the checks execution issue persists. Day by day sensu is going to be unusable. We use sensu mainly for scheduling checks and if checks are not getting executed then its of no use. I am asking again and again please do let me know for more details. I am running many checks and have many issues. However I don't see any response from your side

**Comment by raihanchdy** [comment]
@calebhailey The issue persists even in the latest release 6.4.2. Could you please let me know if this a bug and when the fix will come. With this issue, sensu has become unusable.

**Comment by mcbsd** [comment]
@raihanchdy I can't see definition entity attributes for proxy check. You are using proxy client, thus you have entity attributes defined in the check I assume. Can you share that?

**Comment by raihanchdy** [comment]
@mcbsd, please find the check definition

`{
  "api_version":"core/v2",
  "type":"Check",
  "metadata":{
    "namespace":"default",
    "name":"vm-diskusage-data-mnt-eslog",
    "labels":{},
    "annotations":{
      "sensu.io.json_attributes":"{\"type\":\"metric\"}"
    }
  },
  "spec":{
    "command":"/etc/sensu/plugins/metrics_disk.sh /data/elk",
    "subscriptions":[
      "es_kibana"
    ],
    "publish":true,
    "cron": "*/15 * * * *",
    "output_metric_format": "influxdb_line",
    "output_metric_handlers": [
        "infra-metrics-influxdb"
    ],
    "timeout":890
  }
}`

**Comment by raihanchdy** [comment]
@mcbsd please find the check definition
    {
      "api_version":"core/v2",
      "type":"Check",
      "metadata":{
        "namespace":"default",
    "name":"vm-diskusage-data-mnt-eslog",
    "labels":{},
    "annotations":{
      "sensu.io.json_attributes":"{\"type\":\"metric\"}"
    }
  },
  "spec":{
    "command":"/etc/sensu/plugins/metrics_disk.sh /data/elk",
    "subscriptions":[
      "es_kibana"
    ],
    "publish":true,
    "cron": "*/15 * * * *",
    "output_metric_format": "influxdb_line",
    "output_metric_handlers": [
        "infra-metrics-influxdb"
    ],
    "timeout":890
  }
}

**Comment by raihanchdy** [comment]
In sensu server log there is an entry with sending check request but the check is not executing on the agent

**Comment by mcbsd** [comment]
@raihanchdy I don't think this is Sensu issue. Seems like your check definition is incomplete. Proxy check needs to have entity attributes, for instane (including splay, optional):

...
 "entity_attributes": [
    "entity.entity_class == 'proxy'",
    "entity.name.indexOf('firewall') >= 0"
  ],
  "splay": true,
  "splay_coverage": 90``
...

I suggest to read this https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-schedule/checks/#use-a-proxy-check-to-monitor-multiple-proxy-entities
, and then think if what you have fits to the concept.

What is actually Sensu issue, that you can execute proxy checks on demand, that's real fail here, issue is opened for it, hopefully one day...

**Comment by asachs01** [comment]
@raihanchdy following up here since @mcbsd replied on the issue. If this is still happening on a recent Sensu release, let's move the conversation over to [Sensu Community Slack](https://sensucommunity.slack.com) or to the [Sensu Discourse Forums](https://discourse.sensu.io)
