### ISSUE TITLE
E: Unable to locate package sensu-go-agent on Ubuntu/hirsute (21.04)

### ISSUE THREAD

**Issue by sliide-jay** [sensu/sensu-go#4332]
following docs here: https://docs.sensu.io/sensu-go/6.1/operations/deploy-sensu/install-sensu/#install-sensu-agents
unable to install sensu-go-agent.

## Expected Behavior
sensu-go-agent installed

## Current Behavior
```
# curl -s https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh | sudo bash
Detected operating system as Ubuntu/hirsute.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/sensu_stable.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.

# sudo apt-get install sensu-go-agent
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package sensu-go-agent

```

## Steps to Reproduce (for bugs)

1. Spin up an ubuntu 21.04 instance in AWS
2. Run `curl -s https://packagecloud.io/install/repositories/sensu/stable/script.deb.sh | sudo bash`
3. Run `sudo apt-get install sensu-go-agent`

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by amdprophet** [comment]
The packages should become available in the hirsute repository with the upcoming release of Sensu. You should be able to use the focal repository for the time being by using `os=ubuntu dist=focal ./script.sh` with the full installer script: https://packagecloud.io/sensu/stable/install.

**Comment by sliide-jay** [comment]
Thanks for that i will try it out
