### ISSUE TITLE
sensu-agent 6.4 fails to connect with backend

### ISSUE THREAD

**Issue by elfranne** [sensu/sensu-go#4340]
### Initial bug report below, see first comment.

When using a backend build with go >1.15 you can run into issues with certificates

Some agents will not be able to connect to the backend and will log the following error:
```json
{"component":"agent","error":"x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0","level":"error","msg":"reconnection attempt failed","time":"2021-06-29T11:07:51+02:00"}
```
More info from Golang release notes: https://golang.google.cn/doc/go1.15#commonname

## Expected Behavior
sensu-agent should connect to the backend

## Current Behavior
sensu-agent cannot connect to the backend

## Possible Solution
As noted in the error you can set the environment variable on the **agent** and restarting the sensu agent process after setting the environment variable.

## Steps to Reproduce (for bugs)
The issue is only present on our Windows agent. I' ll be looking deeper on the certificates and how they were generated.

## Your Environment
sensu-backend running Ubuntu 18.04 with backend build yesterday ( https://github.com/sensu/sensu-go/tree/d1480a492024045acac62772f62666204ad7f93d ) 

sensu-agent 6.4.0.4826 on Windows 2012 (and most likely also 6.3 too)

**Comment by elfranne** [comment]
After some investigation it is not related to the backend but to agent trying to connect to the sensu backend where the cert has been issued by puppet (default behavior on the sensu-go puppet module) but does not include a SAN.

More info here: https://tickets.puppetlabs.com/browse/SERVER-2338

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/wss-connection-issues-on-sensu-deployed-by-puppet/2637/3

**Comment by echlebek** [comment]
Hi, while this is unfortunate, it seems out of our control for the reasons mentioned in the issue description. I believe steps to remedy the problem have already been linked above, so I'm closing this.
