### ISSUE TITLE
Process kill routine is started before process is

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4350]
In `command/command.go`, a timer is started which kills processes that have not exited before a timeout is defined, if any. However, this is declared before the process has started, which is subtly wrong. There is nothing ensuring than in a busy system, the process will have started before the kill routine executes.

This can produce a race condition or nil pointer dereference, so we should start the process kill routine only after the process has been successfully started.

**Comment by portertech** [comment]
This is resolved as of 6.4.
