### ISSUE TITLE
Periodic agent reconnection to balance load over time

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#4351]
## Feature Suggestion
Periodic agent reconnection to balance load over time

## Possible Implementation
Have an agent configuration (on by default, with a long default interval) which causes the agent to reconnect to the backend

## Context
When backends are restarted or temporarily stopped in environments with or without load balancers, agents may end up reconnecting to other backends before the restarted backend comes back online, meaning no agents will reconnect to the backend in question. This can result in a subset of a cluster taking a larger than ideal % of the load. By having the agents reestablish their connections periodically, it should help to re-balance the load.

**Comment by calebhailey** [comment]
A default interval of 24-48 hours seems reasonable for this. In a cluster with 10K agents that would be roughly 3-6 reconnections per minute.

**Comment by echlebek** [comment]
I think 24-48 hours is an order of magnitude too long for this, we should be able to tolerate frequent reconnections, and I think it needs to be a fundamental product capability, since we need to support users bringing down individual backends at any time.

**Comment by echlebek** [comment]
I'm going to close this issue in favour of #3329, as it's a duplicate, and 3329 is older.
