### ISSUE TITLE
Update embedded etcd default timeout values

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4368]
## Feature Suggestion

Increase the default `--etcd-election-timeout` from 100ms => 500ms, and `--etcd-heartbeat-interval` from 1000ms to 5000ms. 

NOTE: our customer reliability engineering team has been advising several customers to adjust these settings for several months, with good results. We're considering these to be safe defaults, and recommended settings for all new Sensu Go clusters (where external etcd is not possible). 

## Possible Implementation

Increase the default values as mentioned above. 

```yaml
etcd-election-timeout: 5000
etcd-heartbeat-interval: 500
```

We will highlight this change in the release notes and documentation, and customers can restore the old defaults with a simple configuration change (as needed). 

## Context

If the Etcd cluster is constantly having leader elections, it's always going to be overrun.

**Comment by portertech** [comment]
The "work" is done, however, before we can merge this, we must understand the effects of the change.

**Comment by c-kruse** [comment]
So far the only thing I've ran into that may be worth bringing up is that the minimum lease TTL is loosely tied to the etcd election timeout. This is what it looks like is causing integration tests to fail - the keepalived integration test is using a [keepalive timeout of 5s](https://github.com/sensu/sensu-go/blob/main/backend/keepalived/integration_test.go#L73) which is exactly the election timeout is set to.

etcd currently sets the minimum lease ttl to 1.5x election timeout https://github.com/etcd-io/etcd/blob/main/server/etcdserver/server.go#L343
