### ISSUE TITLE
Backend logging start, port binding

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#4390]
Presently, the backend doesn't explicitly log that it's started and everything is ready to process events (we just see events being processed) nor does it log once it binds to each port (and which port it binds to). Having these logs would make understanding what's happening in an environment where ports might not bind for some reason and also when a backend starts/restarts/is restarted.

**Comment by echlebek** [comment]
@agoddard what would the expected log level be for such logs? Info?

**Comment by echlebek** [comment]
He says warn level.
