### ISSUE TITLE
ETCD cluster is up but Sensu server not starting

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4397]
I have 3 node sensu cluster with version 3.16. I am not using embedded etcd. My etcd cluster is separate were I connect sensu-servers to etcd cluster.

I can see etcd cluster is healthy but sensu server throwing context deadline error.

![image](https://user-images.githubusercontent.com/31199957/130402100-8d9b2aef-76c1-44a1-904a-a6e294477f10.png)

![image](https://user-images.githubusercontent.com/31199957/130402112-262ec7fa-53ed-425f-b6dc-b39d6a8d93d6.png)

After restarting etcd cluster, sensu servers came up. Not sure why this is happening.

**Comment by asachs01** [comment]
@raihanchdy it's been some time since you opened the original issue--is it still occurring? If so, let's move troubleshooting over to the [Sensu Community Slack](https://sensucommunity.slack.com) or to the [Sensu Discourse Forums](https://discourse.sensu.io) to troubleshoot further.
