### ISSUE TITLE
Can't use custom asset with proxy entity

### ISSUE THREAD

**Issue by pandaatrail** [sensu/sensu-go#4438]
When using [custom asset](https://bonsai.sensu.io/assets/pandaatrail/sensu-check-ftp), I can't use it with proxy entities.
Yet, It works with agent entity.

So rather than a bug, I think it's something I do wrong, but can't find a way to do it correctly in the documentation.

## Expected Behavior

When I use an FTP check, the proxy entity supposed to subscribe to the check should be declared in Web UI.
While I can see the check in the check list of the namespace used, I can't see any events going to the web UI for the concerned proxy entities.

```ftp.yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  name: ftp
  namespace: e2p
spec:
  command: ftp -z {{ .labels.url }} -u {{ .labels.user }} -p {{ .labels.port }} -P {{ .labels.password }}
  handlers: []
  high_flap_threshold: 0
  interval: 20
  low_flap_threshold: 0
  proxy_requests:
    entity_attributes:
    - entity.entity_class == 'proxy'
    - entity.labels.check_ftp == 'needed'
  publish: true
  runtime_assets:
  - pandaatrail/sensu-check-ftp
  subscriptions:
  - ftp
 ```

```ftp_proxies.yaml
---
type: Entity
api_version: core/v2
metadata:
  created_by: jordan
  name: test 
  namespace: test 
  labels:
    check_ftp: needed
    environment: live
    password: TEST
    port: "21"
    url: test.mylittleponey.com
    user: test
spec:
  entity_class: proxy
```

## Current Behavior

No incoming event in the Web UI: the check is simply not triggered at all.

## Steps to Reproduce (for bugs)

1. Add the check to your sensu backend `sensuctl create --file ./ftp.yaml`
2. Add the entity to your sensu backend `sensuctl create --file ./ftp_proxies.yaml`
3. Go to the Web UI of the backend
4. Click on the "test" agent, and observe any FTP incoming event...

## Context

I **NEED** to use proxy entities to reproduce the FTP access some clients are using. So, I **MUST** be able to trigger these checks through FTP **PROXY** agents.

## Your Environment

Debian 10.10

`docker --version`: Docker version 20.10.8, build 3967b7d
`docker-compose --version`: docker-compose version 1.29.2, build 5becea4c
docker image used: image: sensu/sensu:6.3
`sensuctl version`: sensuctl version 6.3.0+ee, enterprise edition, build 46d3099d7218c1cd4b6f872d94f6348a69373052, built 2021-05-26T19:46:21Z, built with go1.13.15

Thank you very much for the help, and your time.

**Comment by echlebek** [comment]
Do you have a running agent with the "ftp" subscription?

**Comment by pandaatrail** [comment]
Hi @echlebek and thanks for your answer.

Sadly, as we were stuck with this error, managers have decided to stop using Sensu for monitoring, saying there was a poor support.
In the same time I quit, so I can't precisely answer your question as I can't take a look at the source code. 
But yes, from what I remember, I had an FTP agent with the "ftp" subscription.

Thanks again
