### ISSUE TITLE
Expose hostname and select environment variables to JS mutator eval env

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#4441]
## Feature Suggestion
To enable mutation of events using custom data, such as hostname, and other values passed in from the backend host, it would be great to pass the backend FQDN to the mutator VM as a $hostname variable, as well as specific keys specified in config to pull from environment variables. The user would configure specific environment variable names in the mutator config and the JS mutator would pass these variable names & values through to the JS eval environment. 

## Context
This will allow transformation of events with additional metadata from the sensu environment, which will be useful for downstream processing and filtering for users who are sending Sensu data to systems for further processing.

**Comment by echlebek** [comment]
It probably won't get you what you want, which is presumably the backend's hostname. The existing backend entity's name is a generated UUID and varies from run to run.

**Comment by echlebek** [comment]
No, it's a pretty specialized object right now, we'd have to improve it somewhat for it to be of use for users.
