### ISSUE TITLE
Add a "sensu-system" namespace

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4442]
## Feature Suggestion

All Sensu installs should have a reserved namespace for exposing observability data from the Sensu deployment. 

## Possible Implementation

Initialize new Sensu clusters with a `sensu-system` namespace, intended for cluster backend error reporting etc. Provide an upgrade "migration" to add the `sensu-system` namespace to existing clusters. Backends can assume the namespace exists when creating events. Only cluster admins have access to the namespace via existing RBAC policy. We can document possible RBAC policy for operators to grant standard users read-only access to the namespace (and entities/events within).

## Context

Carve out a space for making the Sensu deployment more observable (e.g. sensu-backend entities, sensu-backend events/metrics, etc).

**Comment by fguimond** [comment]
I believe having using the --system-namespace option when running `sensu-backend init` makes sense. However once created that namespace needs to be marked as `system` in the database.

# Initialization

Upon launching a backend for the first time or the first time after an upgrade the system namespace should be created if not already.

Proper RBAC access should also be set to limit access to the namespace.

Only read and update (rename) roles should be provided to that namespace.

The namespace should not be delete-able.

**Question**: What's the best way to mark the namespace as `system`?
* Add an extra key in the config store to identify the system namespace  (ex. `sensu.io/system-namespace = sensu-system`)
** When the namespace is renamed that key needs to be updated as well
* Add an extra property to the namespace that allows us to mark it as such. Ex:
** `system bool`
** `namespace_class string`
** other

**Comment by portertech** [comment]
Closing in favour of https://github.com/sensu/sensu-go/issues/4443
