### ISSUE TITLE
Remove support for embedded etcd

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4446]
## Feature Suggestion

Remove support for embedded etcd in Sensu Go 7. At minimum we should no longer support clustering with embedded Etcd. TBD if it's still valuable to support embedded etcd for standalone deployments (e.g. for local development, etc). 

## Possible Implementation

- [x] https://github.com/sensu/sensu-go/issues/4616

**Comment by portertech** [comment]
Closed by #4616
