### ISSUE TITLE
Sensu does not always shut down or restart cleanly

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4461]
## Expected Behavior
On demand, or after critical timeouts in internal components, Sensu should shut down or restart cleanly, in a timely fashion.

## Current Behavior
Sensu deadlocks and the process supervisor must use force to kill it.

## Possible Solution
* Refactor daemon.Daemon to support context.Context across all daemons.
* Review each daemon to ensure that it will shut down promptly.
* Fix bug in agentd sessions where sockets are held on to too long for "graceful shutdown"
* Fix bug in pipelined where worker goroutines can block forever while waiting for assets to download.
* Possibly other issues?

## Context
Observed in multiple customer deployments and observed in our own testing.

**Comment by portertech** [comment]
We've shipped a number of improvements in 6.6.3. We still want to make some changes to how internal daemons work, but considering this closed.
