### ISSUE TITLE
Support ordering predicates in the event store

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4485]
We'd like to modify the event store to support ordering, so that it's transparent to consumers in sensu-go. We plan to extend the store.SelectionPredicate to achieve this.

Add a field to `store.SelectionPredicate` that is `Ordering string`. Support some well-defined orderings as constants in the event store.

Detect the presence of a non-empty ordering field in the event store's selection predicate and parse in the event store when listing events. Sort the returned events according to the ordering.

The ordering field should play nicely with pagination. We will need to change how we deal with the continuation token in the event store.

**Comment by portertech** [comment]
"well-defined orderings" to come from the web ui.

**Comment by portertech** [comment]
continuation token will likely need to be an integer offset for the filtered and sorted result set.

**Comment by jamesdphillips** [comment]
Existing sorting can be found here: https://github.com/sensu/sensu-go/blob/main/api/core/v2/event.go#L227-L414

**Comment by portertech** [comment]
Shipped in 6.6
