### ISSUE TITLE
Support Azure ActiveDirectory OpenID Connect (AD OIDC)

### ISSUE THREAD

**Issue by hillaryfraley** [sensu/sensu-go#4495]
## Feature Suggestion
Add support for Azure ActiveDirectory OpenID Connect (AD OIDC).

## Context
A customer originally opened an issue in sensu-go, which we converted to a [sensu-docs issue](https://github.com/sensu/sensu-docs/issues/2968) because we first thought this was a problem with our OIDC documentation.

The customer later added a link to a [Discourse thread](https://discourse.sensu.io/t/using-azure-ad-openid-connect-oidc-for-authentication/1819), in which customers and dev advocates try to get Azure AD OIDC to work without success.

Issue in sensu-enterprise-go: https://github.com/sensu/sensu-enterprise-go/issues/1915

**Comment by calebhailey** [comment]
Closing in favor of https://github.com/sensu/sensu-enterprise-go/issues/1915
