### ISSUE TITLE
Bugfix for external etcds using username/password auth in `sensu-backend upgrade` command

### ISSUE THREAD

**Issue by atomicules** [sensu/sensu-go#4502]
I missed this change as part of these previous issues/PRs:

- https://github.com/sensu/sensu-go/issues/4316
- https://github.com/sensu/sensu-go/pull/4381

In accordance with the contributing guidelines I'm opening an issue before opening a PR.

## Expected Behavior

The `sensu-backend upgrade` command should work when an external etcd is being used with username/password authentication

## Current Behavior

The command produces this error:

```
$sensu-backend upgrade
    ? Do you really want to upgrade your Sensu 5.x database to 6.x? This operation cannot be undone; make sure you back up your database! Yes
    {"component":"etcd","level":"warning","logger":"etcd-client","caller":"v3@v3.5.0/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoin
    ts://0xc0003b3a40/#initially=[https://REDACTED;REDACTED]"
    ,"attempt":0,"error":"rpc error: code = InvalidArgument desc = etcdserver: user name is empty","time":"2021-11-18T10:33:19Z"}
    {"component":"backend","error":"can't migrate database: internal error: etcdserver: user name is empty","level":"fatal","msg":"error executing sensu-backend","time":"202
    1-11-18T10:33:19Z"}
```

## Possible Solution

I have a fix in this branch:

https://github.com/atomicules/sensu-go/tree/bugfix-etc-ext-auth-upgrade-cmd

Compare view:

https://github.com/sensu/sensu-go/compare/main...atomicules:bugfix-etc-ext-auth-upgrade-cmd

## Steps to Reproduce (for bugs)

1. Use Sensu Go 6.5.X with an external etcd using username/password auth
2. Try to run the `sensu-backend upgrade` command

## Context

We were still running a 6.3/6.4 version from a custom build from the earlier branch where I first added the support for external etcds with username/password support. It took us a bit to get around to switching back to building from sensu/sensu-go (instead of my fork) and upgrading to 6.5.X. After doing that I thought I best run the `sensu-backend upgrade` command just in case and that's when I discovered the issue.

I have tested the changes per [this branch](https://github.com/atomicules/sensu-go/tree/bugfix-etc-ext-auth-upgrade-cmd) and we didn't need to worry about running the upgrade command:

```
$sensu-backend upgrade
? Do you really want to upgrade your Sensu 5.x database to 6.x? This operation cannot be undone; make sure you back up your database! Yes
{"component":"store","database_version":2,"level":"info","msg":"database already up to date","time":"2021-11-18T12:19:26Z"}
{"component":"store","database_version":0,"level":"info","msg":"database already up to date","time":"2021-11-18T12:19:26Z"}
```

But I still feel like I should fix the issue since it's my fault.

## Your Environment

* Sensu Go 6.5.2
* Custom Chef cookbook 
* Ubuntu 16.04 LTS

**Comment by echlebek** [comment]
Thank you! I'll open a PR based on your branch.

**Comment by echlebek** [comment]
This was merged and released.

**Comment by atomicules** [comment]
Thanks!
