### ISSUE TITLE
Go version needed to compile Sensu Go

### ISSUE THREAD

**Issue by FlorinAndrei** [sensu/sensu-go#4514]
According to the README, the Go version needed to compile Sensu Go is 1.13.3

https://github.com/sensu/sensu-go/blob/01d13d84b253485c736049340dd3a2139653ca28/README.md?plain=1#L47

But that's a very old version. Are you sure that's not a typo?

**Comment by amdprophet** [comment]
This is a typo. The minimum version required is 1.13.
