### ISSUE TITLE
Clarify agent connection error messages during backend instability

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#4525]
## Expected Behavior

As an operator, I expect that I should be able to distinguish between error messages that arise as a result of backend instability. For example, when confronted with this message:

```
Sep 23 19:34:13 sensu-backend.example.com sensu-agent[187522]: {"component":"agent","error":"read tcp 192.168.1.2:35792-\u003e192.168.1.3:8081: read: connection reset by peer","level":"error","msg":"reconnection attempt failed","time":"2021-09-23T19:34:13-04:00"}
```

I should be able to determine if this is due to a potential network issue or that the backend itself is experiencing some other issue. 

## Current Behavior

As it stands, the messages here:

```
Sep 23 19:34:13 sensu-backend.example.com sensu-agent[187522]: {"component":"agent","error":"read tcp 192.168.1.2:35792-\u003e192.168.1.3:8081: read: connection reset by peer","level":"error","msg":"reconnection attempt failed","time":"2021-09-23T19:34:13-04:00"}

Sep 23 19:51:57 sensu-backend.example.com sensu-agent[187522]: {"component":"agent","error":"read tcp 192.168.1.2:35792-\u003e192.168.1.3:8081: i/o timeout","level":"error","msg":"reconnection attempt failed","time":"2021-09-23T19:51:57-04:00"}
```

Should provide additional context as to the cause, whether it be network instability (e.g., an unstable connection) or backend instability. 

## Context

See Sensu internal reference HS-27140 for additional context.

**Comment by echlebek** [comment]
It would be great if we could achieve this. I fear it might not be possible though.

Locally to the error, the information about why a connection was severed, or why a timeout occurred, is not available.

**Comment by asachs01** [comment]
:/ If that's not possible, I don't think that's a problem.

**Comment by asachs01** [comment]
@echlebek so in light of recent convos, it sounds like we should probably close this out as a wontfix?

**Comment by echlebek** [comment]
I think so. In cases where we can add context to errors to give hints to operators, we definitely should, but I don't think it's possible to directly point the finger at particular causes in these error messages. Closing.
