### ISSUE TITLE
Track etcd lease count in metrics

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#4526]
It would be helpful to add etcd lease count to backend metrics stats when using embedded etcd and (if possible) if we can fetch it from external etcd.

**Comment by calebhailey** [comment]
@agoddard is this issue to add https://github.com/sensu/sensu-go/pull/4478 metrics to the backend metrics stats file?

**Comment by portertech** [comment]
- Need to make an etcd request to get the current lease count (gauge)
- Justin concerned about the accuracy/correctness of this metric

**Comment by amdprophet** [comment]
## Notes
* Lease operation metrics tracked in sensu-backend are per-backend
* Lease operation metrics are reset when sensu-backend is restarted
  * Unable to calculate total leases as a result

1. We **can** add the lease operations to the metrics log.
2. We **can** add etcd lease metrics to the metrics log when using embedded etcd.
3. We **cannot** add etcd lease metrics to the metrics log when using external etcd without creating a method to pull metrics from external systems.

## Lease metrics - External Etcd
### Backend lease operation metrics after one restart
```
sensu_go_lease_ops{component="ring",op="grant",status="ok"} 1
sensu_go_lease_ops{component="ring",op="put",status="ok"} 1
sensu_go_lease_ops{component="sensu-etcd",op="grant",status="ok"} 1
sensu_go_lease_ops{component="sensu-etcd",op="keepalive",status="alive"} 7
sensu_go_lease_ops{component="sensu-etcd",op="keepalive",status="ok"} 1
sensu_go_lease_ops{component="sensu-etcd",op="put",status="ok"} 1
```

### Etcd lease metrics
```
etcd_debugging_lease_granted_total 6
etcd_debugging_lease_renewed_total 140
etcd_debugging_lease_revoked_total 3
etcd_debugging_lease_ttl_total_bucket{le="1"} 0
etcd_debugging_lease_ttl_total_bucket{le="2"} 0
etcd_debugging_lease_ttl_total_bucket{le="4"} 0
etcd_debugging_lease_ttl_total_bucket{le="8"} 0
etcd_debugging_lease_ttl_total_bucket{le="16"} 0
etcd_debugging_lease_ttl_total_bucket{le="32"} 0
etcd_debugging_lease_ttl_total_bucket{le="64"} 2
etcd_debugging_lease_ttl_total_bucket{le="128"} 2
etcd_debugging_lease_ttl_total_bucket{le="256"} 2
etcd_debugging_lease_ttl_total_bucket{le="512"} 2
etcd_debugging_lease_ttl_total_bucket{le="1024"} 4
etcd_debugging_lease_ttl_total_bucket{le="2048"} 6
etcd_debugging_lease_ttl_total_bucket{le="4096"} 6
etcd_debugging_lease_ttl_total_bucket{le="8192"} 6
etcd_debugging_lease_ttl_total_bucket{le="16384"} 6
etcd_debugging_lease_ttl_total_bucket{le="32768"} 6
etcd_debugging_lease_ttl_total_bucket{le="65536"} 6
etcd_debugging_lease_ttl_total_bucket{le="131072"} 6
etcd_debugging_lease_ttl_total_bucket{le="262144"} 6
etcd_debugging_lease_ttl_total_bucket{le="524288"} 6
etcd_debugging_lease_ttl_total_bucket{le="1.048576e+06"} 6
etcd_debugging_lease_ttl_total_bucket{le="2.097152e+06"} 6
etcd_debugging_lease_ttl_total_bucket{le="4.194304e+06"} 6
etcd_debugging_lease_ttl_total_bucket{le="8.388608e+06"} 6
etcd_debugging_lease_ttl_total_bucket{le="+Inf"} 6
etcd_debugging_lease_ttl_total_sum 5520
etcd_debugging_lease_ttl_total_count 6
etcd_debugging_server_lease_expired_total 2
```

## Lease metrics - Embedded Etcd
### Backend lease operation metrics after one restart 

```
sensu_go_lease_ops{component="ring",op="grant",status="ok"} 1
sensu_go_lease_ops{component="ring",op="put",status="ok"} 1
sensu_go_lease_ops{component="sensu-etcd",op="grant",status="ok"} 1
sensu_go_lease_ops{component="sensu-etcd",op="keepalive",status="alive"} 10
sensu_go_lease_ops{component="sensu-etcd",op="keepalive",status="ok"} 1
sensu_go_lease_ops{component="sensu-etcd",op="put",status="ok"} 1
```

### Etcd lease metrics
```
etcd_debugging_lease_granted_total 2
etcd_debugging_lease_renewed_total 11
etcd_debugging_lease_revoked_total 1
etcd_debugging_lease_ttl_total_bucket{le="1"} 0
etcd_debugging_lease_ttl_total_bucket{le="2"} 0
etcd_debugging_lease_ttl_total_bucket{le="4"} 0
etcd_debugging_lease_ttl_total_bucket{le="8"} 0
etcd_debugging_lease_ttl_total_bucket{le="16"} 0
etcd_debugging_lease_ttl_total_bucket{le="32"} 0
etcd_debugging_lease_ttl_total_bucket{le="64"} 1
etcd_debugging_lease_ttl_total_bucket{le="128"} 1
etcd_debugging_lease_ttl_total_bucket{le="256"} 1
etcd_debugging_lease_ttl_total_bucket{le="512"} 1
etcd_debugging_lease_ttl_total_bucket{le="1024"} 2
etcd_debugging_lease_ttl_total_bucket{le="2048"} 2
etcd_debugging_lease_ttl_total_bucket{le="4096"} 2
etcd_debugging_lease_ttl_total_bucket{le="8192"} 2
etcd_debugging_lease_ttl_total_bucket{le="16384"} 2
etcd_debugging_lease_ttl_total_bucket{le="32768"} 2
etcd_debugging_lease_ttl_total_bucket{le="65536"} 2
etcd_debugging_lease_ttl_total_bucket{le="131072"} 2
etcd_debugging_lease_ttl_total_bucket{le="262144"} 2
etcd_debugging_lease_ttl_total_bucket{le="524288"} 2
etcd_debugging_lease_ttl_total_bucket{le="1.048576e+06"} 2
etcd_debugging_lease_ttl_total_bucket{le="2.097152e+06"} 2
etcd_debugging_lease_ttl_total_bucket{le="4.194304e+06"} 2
etcd_debugging_lease_ttl_total_bucket{le="8.388608e+06"} 2
etcd_debugging_lease_ttl_total_bucket{le="+Inf"} 2
etcd_debugging_lease_ttl_total_sum 960
etcd_debugging_lease_ttl_total_count 2
etcd_debugging_server_lease_expired_total 1
```

**Comment by amdprophet** [comment]
The only accurate way to display the number of leases in Etcd will be to query Etcd itself. The Prometheus metrics for Etcd are reset when the Etcd cluster is restarted.

**Comment by c-kruse** [comment]
Pardon me while I snag this! Turning attention to a bug momentarily.

Only tidbit I have to add is that etcd's `etcd_debugging` namespace comes with a disclaimer that they can and often change it. IMHO It'd be ill advised to scrape an external etcd cluster's metrics endpoint for anything under that namespace. Example: etcd_debugging_lease* info was only added in 3.4 and we presumably could have users on 3.3.2+. If embedded etcd in sensu-go is long for this world, it may be worth some test coverage on the etcd_debugging_* metrics we are expecting it to produce just so that we're not shocked when they disappear after an etcd version bump.

**Comment by amdprophet** [comment]
@c-kruse sorry, I wasn't clear in my last comment. I was suggesting that we query etcd with etcdclient to determine the lease count, not the prometheus metrics endpoint.

**Comment by portertech** [comment]
We should reuse the existing enterprise metricsd daemon, https://github.com/sensu/sensu-enterprise-go/blob/main/backend/metricsd/metricsd.go

**Comment by c-kruse** [comment]
The enterprise metricsd daemon looks like an okay place for this, but is not a perfect conceptual match. The daemon is set up to schedule a set of metric "Suites" on a configurable interval on each backend using the ring pool, which is helpful. 
Where metricsd diverges from our needs is that each suite produces a slice of resources to be persisted in the store which can be queried later through the metricsd interface. Continuing this pattern would introduce a dependency on the enterprise metricsd interface from the OSS metrics bridge (responsible for the metrics stats file.)

## Approach Revised
Add a new metricsd suite in the enterprise product that registers a single prometheus gauge `sensu_go_etcd_leases`, and updates it with the lease count returned by [clientv3.Leases(ctx)](https://pkg.go.dev/go.etcd.io/etcd@v3.3.27+incompatible/clientv3#Lease).
