### ISSUE TITLE
Enable pipelines to be attached to keepalives

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#4589]
## Feature Suggestion

As a Sensu operator, I want to be able to have pipelines for handling keepalive events (internal ref HS-28121)

## Possible Implementation

As part of agent.yml config, users could specify pipelines in a similar fashion to other keepalive attributes.

**Comment by portertech** [comment]
We need to:
- Update agent configuration to support keepalive pipelines
- Update agent to include configured pipelines in keepalive events
- Update backend keepalive switchset to use optional agent specific pipelines
