### ISSUE TITLE
Create a store and store/v2 implementation for postgres

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4615]
Create implementations of the store, and the store/v2 API, for postgresql.

Alternatively, deprecate the store interface, use store/v2 throughout, and only create a store/v2 implementation.

We should discuss the pros and cons of each approach.

**Comment by c-kruse** [comment]
Work in progress document capturing some of the options here: https://docs.google.com/document/d/1OfT6fLIqKggGt0pKcFiBGa6Jb5KgygX7DpSy9Pt0XSo/edit?usp=sharing

**Comment by echlebek** [comment]
This is done as of #4915
