### ISSUE TITLE
Migrate core/v2 resources to store v2 interface

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-go#4632]
Move core/v2 resource storage to the store v2 layout and interface.

## Feature Suggestion

Move core/v2 resource storage to the store v2 layout and interface, and consider either deprecating the store interface or implementing shims for the store interface to use the v3 implementation like we have done for Entities.

I am sure there are far more details and reasons floating around @echlebek's head. 

## Possible Implementation

I'd need a hot minute to figure this all out, but to start we'd need to:
* create or generate core/v3 compatible resources from or based on the core/v2 api resources we wish to migrate.
* write migration for moving to the v2 store layout.
* ??? adopt the store v2 interface 600 different places

## Context

There are multiple ideas floating around that involve enhancements to our storage interface and it would be ideal to not duplicate efforts across multiple interfaces and implementations. Examples: ETag support, Better PUT behavior #4631, postgres store implementations

**Comment by echlebek** [comment]
We did it! As of #4195
