### ISSUE TITLE
Inconsistent and wrong arm_version on Rasberry Pi 3/4 devices

### ISSUE THREAD

**Issue by espenaf** [sensu/sensu-go#4636]
## Expected Behavior
sensu-agent property **arm_version** = 7. So when downloading assets, the correct ones are filtered and installed.

## Current Behavior
sensu-agent property arm_version might not be 6/7 on a freshly installed device, or changes over time. The following values have been observed:

* debian 10.11 / debian (Raspberry Pi 3): arm_version="1476395014"
* raspbian 10.11 / debian (Raspberry Pi 3): arm_version="1476395014"
* raspbian 11.2 / debian (Raspberry Pi 3): arm_version="-1476395001"
* raspbian 10.11 / debian (Raspberry Pi 4): arm_version="-1476395002"

On the raspbian 10.11 (Raspberry Pi 4) device, the arm_version changed after upgrading to sensu-agent 6.6.6, from "-1476395001" to "-1476395002".

This breaks download of assets using arm_version to filter.

## Possible Solution
Currently duplicating asset config with the following change to force a workaround:

`        - entity.system.arm_version == -1476395002`

## Steps to Reproduce (for bugs)
1. Download and install image from https://www.raspberrypi.com/software/operating-systems/ on a Raspberry Pi 3 or 4 
2. Install sensu-agent via either apt repo or via ansible with https://sensu.github.io/sensu-go-ansible/
3. Add agent to backend
4. View properties in Entities -> entity -> properties 

## Context
Have a consistent and working arm_version property that can be used for deploying assets on a broad set of Raspberry Pi devices and OS versions. Currently this needs several duplications builds in the asset config of all plugins used by the agent.

## Your Environment
Sensu Backend 6.6.6 with Sensu Agent 6.6.3 or 6.6.6. Tested on Raspberry Pi 3 and 4, running pure Debian 10 Buster, Raspbian 10 Buster and  Raspbian 11 Bullseye. All running 32 bit version of Debian/Raspbian.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/sensu-agent-arm-version-wrong-on-debian-buster-raspberry-pi/2729/3

**Comment by agm650** [comment]
Could it be that the resolution of the goarm variable is incorrect?
on a raspberry pi3 (11.2) I have 0x40000007 
So I have the version 7 defined somewhere 

In some other repository I found out that the arm version was stored in an int8.

In the original issue,
debian 10.11 / debian (Raspberry Pi 3): arm_version="1476395014" -> 0x58000006 => 6
raspbian 10.11 / debian (Raspberry Pi 3): arm_version="1476395014" ->  0x58000006 => 6
raspbian 11.2 / debian (Raspberry Pi 3): arm_version="-1476395001" -> 0xA8000007 => 7
raspbian 10.11 / debian (Raspberry Pi 4): arm_version="-1476395002" -> 0xA8000006 => 6

So I think the trick would be to do store the variable on int8.

I will try to open a pull request for this.

**Comment by agm650** [comment]
Yep it seems to do the trick :)
![Screenshot 2022-03-13 at 21 30 55](https://user-images.githubusercontent.com/45319401/158078087-a8a9ae16-1e32-4630-8756-88bdac3aad1c.png)

Ill try to see if I can tests it on various configuration.

**Comment by espenaf** [comment]
Great work 👍

**Comment by echlebek** [comment]
Thanks @agm650, this will be included in the 6.7.0 release.
