### ISSUE TITLE
[Feedback] :Commands should be available for restart, stop sensu-agent and sensu-backend

### ISSUE THREAD

**Issue by aaggarwal-sumo** [sensu/sensu-go#4646]
[Feedback] : Commands should be available for restart, stop sensu-agent and sensu-backend

Currently user can only start, view version of sensu-agent and sensu backend. If user wants to restart/stop  sensu-agent or sensu-backend user needs to user service command or need to stop process.

## Expected Behavior
As a User Experience user should be able to restart/stop sensu-agent and sensu-backend along with start.

## Current Behavior
Only start is supported using sensu-agent and sensu-backend.

## Possible Solution
Instead user using service command or killing process id to stop sensu-agent/sensu-backend for restarting or stopping the service sensu-agent/sensu-backend should have such options and user can directly use that. 

## Steps to Reproduce (for bugs)
sensu-agent/sensu-backend doesn't have restart/stop option.

## Context
So currently sensu-agent is setup on Mac Os Laptop and it doesn't have options to use service command which is causing issues to use sensu. 

## Your Environment
Sensuctl installed using docker package.
Sensu-agent installed on mac laptop with docker package.
Sensu-backend installed with docker image.

**Comment by aaggarwal-sumo** [comment]
@portertech Please let me know if anything is required.

**Comment by echlebek** [comment]
sensu-backend and sensu-agent are blocking processes. They rely on an external process supervisors to restart and stop, like systemd. These processes support standard unix signals for doing these actions.

We won't be developing our own service wrappers. Doing so would make sensu different than almost all other unix services and is not a recommended application development technique.

Mac OS is not a system that we have had much customer interest in beyond sensuctl, so we have not packaged sensu-agent for it.
