### ISSUE TITLE
sensu-go-cli does not appear to support annotations

### ISSUE THREAD

**Issue by zenmetsu** [sensu/sensu-go#4659]
In following the instructions for the sensu-remediation-handler plugin, i was unable to get any of the remediation measures to execute.  Upon further investigation, i discovered that when querying sensu via `sensuctl check info <checkname>` the annotations that were in my .yaml file were omitted.  The UI also failed to show annotations, so it appears that sensuctl also failed to import the annotations due to lack of support.

When an annotation was added via the UI, the UI showed the annotation, however sensuctl CLI command did not reflect the added annotation.

sensu-go-cli  v6.6.6+ee
sensu-go-backend v6.6.6+ee

**Comment by zenmetsu** [comment]
majormoses pointed me in the right direction, and i found out that via the UI, you can enter an array of objects containing key:value pairs for the value of the `io.sensu.remediation.config.actions` key...

you have to use yaml apparently and use something like this for the value
`      [
        {
          "description": "Perform this action once after Nginx has been down for 30 seconds.",
          "request": "systemd-start-nginx",
          "occurrences": [ 3 ],
          "severities": [ 1,2 ]
        },
        {
          "description": "Perform this action once after Nginx has been down for 120 seconds.",
          "request": "systemd-restart-nginx",
          "occurrences": [ 12 ],
          "severities": [ 1,2 ]
        }
      `

**Comment by calebhailey** [comment]
@zenmetsu hi there 👋 it sounds like you're on the right path now. A few additional comments here: 

* The default output (tabular format) for `sensuctl check info <checkname>` won't show you annotations, but if you view the output in YAML or JSON format you should see the annotations (e.g. `sensuctl check info <checkname> --format yaml`). 
* Annotations are always strings, not arrays. But the remediation handler (and some other handlers) employ escaped/stringified JSON annotations to consume complex handler configuration. This WIP branch of the remediation handler has some YAML/JSON examples: https://github.com/sensu/sensu-remediation-handler/tree/2.0-preview#remediation-action-specification 

I hope this helps!

**Comment by asachs01** [comment]
Hey there @zenmetsu, based on Caleb's last reply, it looks like this may be solved? If not, feel free to reopen.
