### ISSUE TITLE
Sensu agent reporting arm_version incorrectly on Raspbian

### ISSUE THREAD

**Issue by DJM0** [sensu/sensu-go#4670]
## Expected Behavior

Should report `arm_version == 7` as shown here: https://docs.sensu.io/sensu-go/latest/plugins/assets/#asset-example-multiple-builds

## Current Behavior

Reporting as `-1476395001`:

<img width="410" alt="Screenshot 2022-03-21 at 11 23 21" src="https://user-images.githubusercontent.com/1108606/159251455-df7e8228-0b42-40ec-8a1b-f16edf0d5f14.png">

## Steps to Reproduce (for bugs)

```
sensu-agent version
sensu-agent version 6.6.6+ee, enterprise edition, build adcbb0b56123cc13774cb951cd697efef636846b, built 2022-02-17T00:57:15Z, built with go1.17.1
```

```
cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3
...
```

```
cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.1
```

```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

Has also been replicated on a Raspberry Pi 3 Model B Rev 1.2 running Raspbian GNU/Linux 10 (buster).

## Context

Having to remove `arm_version` from the asset definitions as a work around to get the filters to work, otherwise it won't match.

## Your Environment

Backend is running `6.6.3` in Docker containers.

**Comment by agm650** [comment]
Hello.

It's an know issue. See this [pull request](https://github.com/sensu/sensu-go/pull/4661) / [issue](https://github.com/sensu/sensu-go/issues/4636)

There was a problem in the way the goarm was stored.

According to the comment on the pr it will be included in version 6.7.0
