### ISSUE TITLE
Implement store/v2 Configuration Store in Postgres

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-go#4737]
Design Spike doc: https://docs.google.com/document/d/1OfT6fLIqKggGt0pKcFiBGa6Jb5KgygX7DpSy9Pt0XSo/edit?usp=sharing

# Spec

## Add schema for Postgres configuration store
Based on the table described in the design spike document, add DDL and a migration for a configuration store table.

```
CREATE TABLE IF NOT EXISTS configuration (
    id                  bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_version         text NOT NULL,
    type                text NOT NULL,
    namespace           text NOT NULL,
    name                text NOT NULL,
    labels              jsonb NOT NULL,
    annotations         bytea NOT NULL,
    resource            jsonb   NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT NOW()
    updated_at       timestamptz NOT NULL DEFAULT NOW(),
    deleted_at        timestamptz,
    CONSTRAINT resource_unique UNIQUE(api_version, type, namespace, name)
);
```

Additional Criteria discovered in spike:
* Has created_at, updated_at and deleted_at `timestamp with time zone` columns in order to support the watcher pattern.
* A trigger automatically updates updated_at on row update - not the application.
*  Resource document is stored spec-only in a jsonb column. Type and object metadata fields are represented in distinct columns. (based off concern for future GIN index size).

## Implement store/v2 interface for configuration resources with postgres.

Note: It is being assumed that both Event and CheckConfig resources will require their own store implementations that accommodate their unique access patterns.

Additional Criteria:
* Delete is implemented as a soft delete, and other access methods respect the deleted_at flag.
    * Get/List/Exists do not return deleted records.
    * CreateOrUpdate NULLs out deleted_at on (re)Create.
    * UpdateIfExists, CreateIfNotExists respect deleted_at.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4737?planning-poker) with ZenHub @c-kruse @echlebek @ccressent @fguimond @amdprophet
