### ISSUE TITLE
Add Etcd store/v2 Watcher Implementation

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-go#4739]
Design Spike doc: https://docs.google.com/document/d/1OfT6fLIqKggGt0pKcFiBGa6Jb5KgygX7DpSy9Pt0XSo/edit?usp=sharing

When --config-store is etcd we will need to switch to a store/v2 Watcher interface common with the postgres implementation for the store/v2 backed resources.

## Interface
Reasoning for the interface detailed in https://github.com/sensu/sensu-go/issues/4721

// store/v2 interface similar to GetResourceV3Watcher
type Watcher interface {
    Watch(context.Context, ResourceRequest) <-chan WatchEvent
}

type WatchEvent struct {
    Action store.WatchActionType // or equiv storev2 replacement CREATE|UPDATE|DELETE|WatchError?
    Resource corev3.Resource
}

## Implementation
This should be a fairly straight-forward adaption of our existing watchers. Examples: https://github.com/sensu/sensu-go/blob/main/backend/store/etcd/watcher.go, https://github.com/sensu/sensu-go/blob/4e17edcbe360e48ee88e9af028ee00a88484c197/backend/store/etcd/watchers.go#L131

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4739?planning-poker) with ZenHub @ccressent @c-kruse @echlebek @amdprophet @fguimond
