### ISSUE TITLE
Postgres Configuration Store Metrics

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-go#4740]
With the addition of a postgres configuration store in 7.0 we need to continue publishing the Tessen metrics we do today, and potentially include postgres-specific operational metrics into the mix.

## Existing functionality

Today tessend has set of resource metrics that get published based off of a count of etcd keys with a given prefix: https://github.com/sensu/sensu-go/blob/b208e5e7adad0e53ec7ef6403236e69f48d03dee/backend/tessend/tessend.go#L663-L669

Moving configuration to postgres means that we need to consider reimplementing this feature to be config-store agnostic.

## New Metrics

**Soft Deleted Resource Count**
Discussion over https://github.com/sensu/sensu-go/issues/4737 brought up the need for a metric to track soft deleted configuration resources.

Either a simple counter for postgres config store delete operations, or a periodic poll for a gauge `WHERE deleted_at IS NOT NULL`, as configuration resources can be un-deleted. (pointless example: `sensuctl delete -f resources.yaml && sensuctl create -f resources.yaml`)

**Others?**

**Comment by fguimond** [comment]
Cyril's work on tessen takes care of that issue.
