### ISSUE TITLE
Implement store/v2 EntityConfig Store in Postgres

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#4744]
Design Spike doc: https://docs.google.com/document/d/1OfT6fLIqKggGt0pKcFiBGa6Jb5KgygX7DpSy9Pt0XSo/edit?usp=sharing
General configuration table vs. separate entity_configs table spike: #4719 

# Spec

## Add schema for Postgres configuration store
Based on the table described in the design spike document, add DDL and a migration for an entity_configs store table.

```
CREATE TABLE IF NOT EXISTS entity_configs (
    id                 bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    sensu_namespace    text NOT NULL,
    sensu_entity       text NOT NULL,
    entity_class       text NOT NULL,
    sensu_user         text NOT NULL,
    subscriptions      text[],
    deregister         boolean,
    deregistration     text,
    keepalive_handlers text[],
    redact             text[],
    created_at         timestamptz NOT NULL DEFAULT NOW()
    updated_at         timestamptz NOT NULL DEFAULT NOW(),
    deleted_at         timestamptz,
    CONSTRAINT resource_unique UNIQUE (sensu_namespace, sensu_entity)
);
```

Additional Criteria discovered in spike:
* Has created_at, updated_at and deleted_at `timestamp with time zone` columns in order to support the watcher pattern.
* A trigger automatically updates updated_at on row update - not the application.

## Implement store/v2 interface for entity_config resources with postgres.

Additional Criteria:
* Delete is implemented as a soft delete, and other access methods respect the deleted_at flag.
    * Get/List/Exists do not return deleted records.
    * CreateOrUpdate NULLs out deleted_at on (re)Create.
    * UpdateIfExists, CreateIfNotExists respect deleted_at.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4744?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
