### ISSUE TITLE
Manually created events not silenced.

### ISSUE THREAD

**Issue by jspaleta** [sensu/sensu-go#4755]
## Current Behavior
When creating ad-hoc events either using the backend events api or the agent's event api, its possible to craft an event payload with a check subscription that matches a silenced rule, and yet have the event not be silenced.

It seems to come down to whether or not the entity listed in the adhoc event has a matching subscription, and not just the check.

## Expected Behavior
Exepected adhoc created events with matching silenced check subscriptions to be silenced regardless of the event's entity subscriptions.  

## Steps to Reproduce (for bugs)
1. Setup sensu-go workshop environment with default settings
2. create a silenced resource (you'll need to update the begin and expire_at below):
```yaml
type: Silenced
api_version: core/v2
metadata:
  created_by: sensu
  name: mysql:*
  namespace: default
spec:
  begin: 1653340131
  creator: sensu
  expire: 10000
  expire_at: 1653350131
  expire_on_resolve: false
  reason: test
  subscription: mysql
```
3. ensure the silenced resource is active with `sensuctl silenced list`
4. ensure entity list doesn't include "test-server1"
5. create an ad-hoc event that references entity "test-server1" and a check with "mysql" subscription
```
$ curl -X POST -H "Authorization: Key $SENSU_API_KEY" -H 'Content-Type: application/json' -d '{"entity":{"entity_class":"proxy","metadata":{"name":"test-server1","namespace":"default"}},"check":{"output":"Server error","state":"failing","status":2,"interval":60,"subscriptions":["mysql"],"metadata":{"name":"manual-event"}},"pipelines":[{"api_version":"core/v2","type":"Pipeline","name":"incident_alerts"}]}' http://127.0.0.1:8080/api/core/v2/namespaces/default/events
```
6. observe that event is created but is not silenced 
```
$ sensuctl event list
     Entity          Check                                       Output                                   Status   Silenced             Timestamp                              UUID                  
───────────────── ────────────── ──────────────────────────────────────────────────────────────────────── ──────── ────────── ──────────────────────────────── ───────────────────────────────────────

test-server1     manual-event   Server error                                                                  2   false      2022-05-23 13:25:10 -0800 AKDT   886be85b-f8ac-485f-a2e5-a85d283631dc
```

7. add `mysql` to the `test-server1` entity's subscriptions
8. post ad-hoc event again, and it will have been silenced after modifying the test-server1 entity definition to include the `mysql` subscription

## Your Environment
Current sensu-go-workshop container environment running sensu 6.7.2

**Comment by amdprophet** [comment]
This is expected behaviour as subscription silencing only applies to entity subscriptions. From the Silence Reference page in Sensu Docs:

> Conversely, a silencing entry that [specifies only a subscription](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-process/silencing/#silence-all-checks-for-entities-with-a-specific-subscription) will have a name with an asterisk in the $CHECK position. This indicates that any event where the originating entities’ subscriptions match the subscription specified in the entry will be marked as silenced, regardless of the check name.
