### ISSUE TITLE
Use store/v2 exclusively in backend/api

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4757]
This is part of a larger issue to remove the use of the original store, and only use store/v2 in sensu-go.

Remove the use of the original store in backend/api. The backend/api package is used in apid and graphql to do CRUD operations on Sensu resources. We should replace all instances of the original store with store/v2.

After the changes, sensu-go will likely be broken or partially working. This is OK, as we'll be continuing working on removing the original store in other components.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4757?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
