### ISSUE TITLE
Use store/v2 exclusively in backend/apid

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4758]
Convert all instances of backend/store to backend/storev2 in apid.

As with other issues in the associated epic, sensu-go need not be fully working after the changes are made.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4758?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
