### ISSUE TITLE
Use store/v2 exclusively in backend/agentd

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4759]
Replace all usage of the store package with store/v2, including the entity watcher.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4759?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
