### ISSUE TITLE
Use store/v2 exclusively in schedulerd

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4760]
Remove all use of the store interface, and use only store/v2, including any watchers.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4760?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
