### ISSUE TITLE
Use store/v2 exclusively in eventd and keepalived

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4761]
Remove all instance of the store package and use only store/v2 in keepalived and eventd.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4761?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
