### ISSUE TITLE
Use store/v2 and backend/api in pipelined

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4762]
Remove all instances of the store package in pipelined, and use backend/api where needed.

**Comment by portertech** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sensu-Go-5ca3b7d249384649e4b7964e/issues/sensu/sensu-go/4762?planning-poker) with ZenHub @amdprophet @c-kruse @ccressent @echlebek @fguimond
