### ISSUE TITLE
Sensu Docker Desktop Extension

### ISSUE THREAD

**Issue by ajeetraina** [sensu/sensu-go#4775]
It would be great if we can have a Sensu Docker Desktop Extension. Extensions allows developers to seamlessly connect their favorite development tools to your application development and deployment workflows. Extensions open a realm of possibilities for developers by adding a variety of tools to your development workflows

## Possible Implementation

Here's the useful link to get started:

- [Introducing Docker Extension](https://www.youtube.com/watch?v=BClJ0i9lXIY) - YouTube
- [Introduction to Docker Extension](https://docs.docker.com/desktop/extensions/)
- [How to create your own Docker Extension](https://docs.docker.com/desktop/extensions-sdk/)
- [Create Your First Extension](https://docs.docker.com/desktop/extensions-sdk/tutorials/initialize/)
- [Minimal frontend extension tutorial](https://docs.docker.com/desktop/extensions-sdk/tutorials/minimal-frontend-extension/)

**Comment by echlebek** [comment]
Thanks for the suggestion, but it's not something we would add to this repository.
