### ISSUE TITLE
Replace etcd queue library with postgres queue library

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#4803]
We have a small queue library that runs on top of etcd. It should be replaced with one that works on postgres instead, whether off the shelf or one of our own creation.

See https://github.com/sensu/sensu-go/tree/main/backend/queue

**Comment by c-kruse** [comment]
@echlebek  it looks like our queue library is implemented as a pub/sub that relies on the backend id getter daemon for discovering subscribers/backends. It also appears to only be used for ad hoc scheduling of checks.

Maybe we don't actually need a replacement for a queue abstraction with a pub/sub implementation, but instead a different approach for ad hoc check scheduling. Perhaps instead we just persist AdhocRequests and have all backends watching for new entries to the store, and add some clean up method that deletes requests after some reasonable window.

**Comment by echlebek** [comment]
@c-kruse sure, I'd be fine with such an approach.
