### ISSUE TITLE
Reorganize TLS/SSL configuration flags

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4857]

**Comment by calebhailey** [comment]
TBD if these should still live in backend.yaml or a new `core/v3.SystemConfig` API. See: https://github.com/sensu/sensu-enterprise-go/issues/2460

**Comment by echlebek** [comment]
We don't have much of a description for this issue, and I strongly believe TLS options need to live in the backend configuration file / command line flags, so I'll have to close this one I'm afraid.
