### ISSUE TITLE
UI - When clicking back from an entity in the /entities/${server}/events UI shows events for the wrong server

### ISSUE THREAD

**Issue by lacho21** [sensu/sensu-go#4858]
## Expected Behavior
server 1 is a windows node -> with checks prefixed with windows-CPU
server 2 is a linux node -> with checks prefixed with linux-CPU
/entities/server1/events - shows events for server1 

## Current Behavior
/entities/server1/events - shows events for server2

## Steps to Reproduce (for bugs)

1a.UI to a servers events via entities
1b. Click back in browser or click the server name in the breadcrumb

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.8 backend/ctl, agent 6.4
* Installation method (packages, binaries, docker etc.): rpm
* Operating System and version (e.g. Ubuntu 14.04): Rhel 7.9

**Comment by asachs01** [comment]
@lacho21 this should be addressed as of 6.9.1. If you're still seeing the wrong events, please let us know.
