### ISSUE TITLE
Repo does not work on Ubuntu 22.04 ( Jammy )

### ISSUE THREAD

**Issue by icalvete** [sensu/sensu-go#4914]
I have this lists.

```bash
root@admin:/etc/apt/sources.list.d# ls -la
total 20
drwxr-xr-x 2 root root 4096 Oct 13 06:31 .
drwxr-xr-x 8 root root 4096 Oct 13 06:31 ..
-rw-r--r-- 1 root root  179 Oct 13 06:30 sensu.list
-rw-r--r-- 1 root root  195 Oct 13 06:31 sensu_community.list
```

```bash
root@admin:/etc/apt/sources.list.d# cat sensu*
# This file is managed by Puppet. DO NOT EDIT.
# sensu
deb https://packagecloud.io/sensu/stable/ubuntu/ jammy main
deb-src https://packagecloud.io/sensu/stable/ubuntu/ jammy main
# This file is managed by Puppet. DO NOT EDIT.
# sensu_community
deb https://packagecloud.io/sensu/community/ubuntu/ jammy main
deb-src https://packagecloud.io/sensu/community/ubuntu/ jammy main
```

If I run an apt-get update manually, I got...

```bash
Err:8 https://packagecloud.io/sensu/community/ubuntu jammy Release
  404  Not Found [IP: 54.219.218.99 443]
Hit:6 https://packagecloud.io/sensu/stable/ubuntu jammy InRelease
Reading package lists... Done
E: The repository 'https://packagecloud.io/sensu/community/ubuntu jammy Release' does not have a Release file.
```

packagecloud.io support told me that...

> Hi there, thanks for your patience.
> The reason why you're getting this error for the Jammy/community repo is because there are zero packages in that repo.

Are there no packages for Ubuntu 22.04 ( Jammy ) ?

Why?

Related with https://github.com/sensu/sensu-puppet/issues/1326

**Comment by pfak** [comment]
`jammy` was released in April 2022. Are there any plans to build packages for this LTS release of Ubuntu?

**Comment by asachs01** [comment]
Hi @pfak @icalvete 👋 can you elaborate on what you need from that specific repo? The `sensu/community` repo only provides a package (sensu-plugin) that is used for installing Sensu ruby-based plugins that don't have an analog on bonsai.sensu.io. If there's a plugin that you need that hasn't been packaged up as an asset, I'd direct you to [sensu/catalog](https://github.com/sensu/catalog) so that our team can create the plugin you need.

**Comment by icalvete** [comment]
Hi @pfak. All history starts with https://github.com/sensu/sensu-puppet/issues/1326. This repo it's a dependency of puppet module.

**Comment by asachs01** [comment]
@icalvete since this is really more of a puppet module issue, I'm going to reply there and close this out. There's a solution that I'll clarify there.

**Comment by icalvete** [comment]
@asachs01 . Yeah, thanks
