### ISSUE TITLE
Add option to disable color for sensuctl output

### ISSUE THREAD

**Issue by lspxxv** [sensu/sensu-go#4960]
## Feature Suggestion

A customer would like the option to disabled colorized output for sensuctl, this will allow for easier/more straightforward use of tabulated output in their external scripts.

## Context

ref == https://secure.helpscout.net/conversation/2164264872/30904?folderId=4465878

**Comment by ccressent** [comment]
Quick thought: it's more robust for scripts to consume the `sensuctl`'s JSON or YAML outputs in the first place.

Writing scripts against the "human" output is a source of pain for everyone involved:
- the user is never sure their parsing code won't randomly break if the output format changes even slightly
- the developers have to jump through hoops or are outright not able to change the "human" output, in fear of breaking user workflows

Please use the JSON or YAML output for scripts. Or use the API even. All of these are guaranteed a modicum of versioning and backwards compatibility.

**Comment by fguimond** [comment]
After further discussions with @asachs01 we are closing this issue as won't fix.
https://sumologic.slack.com/archives/C024XK35Z3Q/p1683833051903199

**Comment by echlebek** [comment]
@fguimond we should probably avoid referencing internal channels in the OSS repo :sweat_smile:

**Comment by fguimond** [comment]
> @fguimond we should probably avoid referencing internal channels in the OSS repo 😅

Good point, fixed!
