### ISSUE TITLE
Proposal to also add OK status to metric threshold annotations & Improvement threshold annotations format

### ISSUE THREAD

**Issue by jadiunr** [sensu/sensu-go#4987]
## Feature Suggestion

In the current Sensu Go (v6.9.2) , Annotations are added to Events when the metric thresholds set by output_metric_thresholds are exceeded.
However, they are only added when the status is Warning or Critical, and no annotations are added when the status is **OK**.

In some use cases, such as using the  [sensu-slack-handler](https://github.com/sensu/sensu-slack-handler) to notify metric threshold annotations, it is somewhat difficult to understand why the metric threshold alert is resolved because there are no annotations on the Resolved event when the metric threshold returns to normal.
(It can see what happened by looking at Critical events, though...)

![Screenshot_2023-04-08_03-37-06](https://user-images.githubusercontent.com/19828725/230661413-552d99c2-1e41-4f76-9134-a0deab28b628.png)

Based on the above, I suggest that annotations be added even when the threshold is within the normal range.

## Possible Implementation

PR: #5013 #5014

```json
  "metadata": {
    "namespace": "default",
    "annotations": {
      "sensu.io/notifications/ok": "The value of test_metric.value is within the configured threshold (max: 200, actual: 100).",
      "sensu.io/output_metric_thresholds/test_metric.value/max/ok": "The value of test_metric.value is within the configured threshold (max: 200, actual: 100)."
    }
  },
```

## Context

None in particular.
See above for details.

**Comment by c-kruse** [comment]
@jadiunr thank you for the proposal and the PRs! Everything looks sound to me.

Pinging @fguimond who is working on pulling things together for a 6.10.0 release early next week. Perhaps we can move forward with this for a 6.10.1 release?

**Comment by echlebek** [comment]
One of the biggest changes between sensu classic and sensu-go is that successful events now move all the way through the pipeline. (Previously only failing events did this.) I think this is a great enhancement because it reflects that same spirit of design for metrics thresholds. Thanks for the great issue and PRs.

**Comment by jadiunr** [comment]
Thank you for replying!

I am considering having multiple thresholds for annotations as a better improvement idea.

```json
"metadata": {
  "namespace": "default",
  "annotations": {
    "sensu.io/notifications/ok": "The value of test_metric.value is within the configured threshold (max: 200 (status: warning) 300 (status: critical), actual: 100).",
    "sensu.io/output_metric_thresholds/test_metric.value/max/ok": "The value of test_metric.value is within the configured threshold (max: 200 (status: warning) 300 (status: critical), actual: 100)."
  }
},
```

My current PR only shows a single threshold value in the annotations for successful events. (either warn or crit?)
In the [documentation](https://docs.sensu.io/sensu-go/6.9/observability-pipeline/observe-schedule/metrics/#add-event-annotations-based-on-metric-threshold-evaluation), the `null_status` annotation can be displayed multiple threshold values.

```json
{
  "annotations": {
    "sensu.io/output_metric_thresholds/system_host_processes/null": "WARNING: no metric matching \"system_host_processes\" (namespace=\"production\") was found; expected min: 5 - max: 50 (status: warning) min:2 - max: 75 (status: critical)"
  }
}
```

After submitting my PR, but if the work is not too complicated, I would like to make the above improvements.

**Comment by jadiunr** [comment]
Considering the various use cases for threshold monitoring, it seems that the above proposal is not as simple as it appears....

<details>
<summary>Spoiler</summary>

```yaml
---
type: CheckConfig
api_version: core/v2
metadata:
  name: test
spec:
  command: "echo \"test_metric value=250\""
  output_metric_format: influxdb_line
  output_metric_thresholds:
  - name: test_metric.value
    null_status: 2
    thresholds:
    - max: "200"
      min: "50"
      status: 1
    - max: "300"
      min: "25"
      status: 2
  subscriptions:
  - test
  interval: 15
  publish: true
```

- An example of a less appropriate output

```json
      "annotations": {
        "sensu.io/notifications/warning": "The value of test_metric.value is within the configured threshold (max: 200 (status: warning) 300 (status: critical), actual: 250).",
        "sensu.io/output_metric_thresholds/test_metric.value/max/ok": "The value of test_metric.value is within the configured threshold (max: 200 (status: warning) 300 (status: critical), actual: 250).",
        "sensu.io/output_metric_thresholds/test_metric.value/max/warning": "The value of test_metric.value exceeded the configured threshold (max: 200 (status: warning) 300 (status: critical), actual: 250).",
        "sensu.io/output_metric_thresholds/test_metric.value/min/ok": "The value of test_metric.value is within the configured threshold (min: 50 (status: warning) 25 (status: critical), actual: 250)."
      }
```

</details>

It may well require more deliberation, but for now, would it be worthwhile just to add to the annotation that the threshold monitoring is normal?

**Comment by jadiunr** [comment]
I have attempted to improve the output content of the threshold annotations.
(However I think this is a slight deviation from the purpose of the PR :disappointed_relieved: )
https://github.com/sensu/sensu-go/pull/5014/commits/fdfe002a4c62a0a3e8056129b855eea197aa863f

<details>
<summary>threshold annotations output</summary>

```
root@c3fa6e172611:/sensu-go# ./sensuctl event list --format wrapped-json | jq '.metadata.annotations'
null
{
  "sensu.io/notifications/critical": "The value of test_metric_for_status_max_crit.value exceeded the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 350",
  "sensu.io/output_metric_thresholds/test_metric_for_status_max_crit.value/critical": "The value of test_metric_for_status_max_crit.value exceeded the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 350"
}
{
  "sensu.io/notifications/warning": "The value of test_metric_for_status_max_warn.value is within the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 250",
  "sensu.io/output_metric_thresholds/test_metric_for_status_max_warn.value/warning": "The value of test_metric_for_status_max_warn.value exceeded the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 250"
}
{
  "sensu.io/notifications/critical": "The value of test_metric_for_status_min_crit.value exceeded the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 20",
  "sensu.io/output_metric_thresholds/test_metric_for_status_min_crit.value/critical": "The value of test_metric_for_status_min_crit.value exceeded the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 20"
}
{
  "sensu.io/notifications/warning": "The value of test_metric_for_status_min_warn.value is within the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 40",
  "sensu.io/output_metric_thresholds/test_metric_for_status_min_warn.value/warning": "The value of test_metric_for_status_min_warn.value exceeded the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 40"
}
{
  "sensu.io/notifications/critical": "CRITICAL : no metric matching \"test_metric_for_status_null.value\" was found; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical)",
  "sensu.io/output_metric_thresholds/test_metric_for_status_null.value/critical": "CRITICAL : no metric matching \"test_metric_for_status_null.value\" was found; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical)"
}
{
  "sensu.io/notifications/ok": "The value of test_metric_for_status_ok.value is within the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 100",
  "sensu.io/output_metric_thresholds/test_metric_for_status_ok.value/ok": "The value of test_metric_for_status_ok.value is within the configured threshold; expected min: 50 - max: 200 (status: warning); expected min: 25 - max: 300 (status: critical); actual: 100"
}
```

</details>

I would like to hear someone's opinion about this one.

**Comment by jadiunr** [comment]
@c-kruse @echlebek @fguimond Is there any progress on this matter?

**Comment by echlebek** [comment]
Hi @jadiunr, sorry for letting this lapse. I think we can accept the changes targeted at main, but not for 6.x as we have effectively frozen that branch now.

**Comment by jadiunr** [comment]
Understood.
Then I will withdraw the 6.x PR.

**Comment by jadiunr** [comment]
Oh, it was already all over.
Thank you for your response!

**Comment by echlebek** [comment]
We've accepted this proposal for the main branch, it will be a part of 7.x.
