### ISSUE TITLE
Add support escape special characters in InfluxDB Line

### ISSUE THREAD

**Issue by jadiunr** [sensu/sensu-go#5030]
## Feature Suggestion

Allowing special characters (space, comma, and equal) to be escaped when using InfluxDB Line format metrics will make InfluxDB Line more useful in Sensu Go.
Current implementation does not take special character escaping into account.

```
# Error "influxdb line format requires 2 arguments with a 3rd (optional) timestamp"
test_measurement,test_tag=foo\ bar value=1 1465839830100400200
```

## Possible Implementation

6.x https://github.com/sensu/sensu-go/pull/5031

## Context

None in particular.

**Comment by echlebek** [comment]
Merged, thank you for your contribution!

**Comment by jadiunr** [comment]
Oh, I see that you have already closed it, but what about changes to 7.x? @echlebek

**Comment by echlebek** [comment]
I can port the changes to the main branch

**Comment by jadiunr** [comment]
All right.
Then I will leave the porting to 7.x to Sensu Team.
