### ISSUE TITLE
Move default values closer to their corresponding types

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#519]
As we add additional ways of running CRUD operations (REST api, graphql, cli, internal) it's becoming apparent that we need a single place to define default values (e.g. entity KeepaliveTimeout, etc.).

**Comment by palourde** [comment]
I did a quick first pass to identify potentially duplicated default values:

https://github.com/sensu/sensu-go/blob/93b4c0d2f98c0bf51cddac77501f2fd095cda948/backend/keepalived/keepalived.go#L18
https://github.com/sensu/sensu-go/blob/93b4c0d2f98c0bf51cddac77501f2fd095cda948/backend/keepalived/keepalived.go#L22
https://github.com/sensu/sensu-go/blob/93b4c0d2f98c0bf51cddac77501f2fd095cda948/backend/pipelined/handle.go#L19

Additionally, we should probably also have constants for the default environment & organization.

These default values should live within the `type` package.

**Comment by annaplotkin** [comment]
We discussed this and it still has value, not a high priority at this time. 

Instead of the types package, this should now be in the core/v2 package.

**Comment by palourde** [comment]
Additionally, we should probably do some cleanup around how our config is declared; we currently have a `Config` struct in the `backend` package that basically interfaces the Viper config; we could use viper directly instead.

**Comment by echlebek** [comment]
@calebhailey I don't see this as a huge concern, and it's something an IC could address while doing routine work on the codebase. Closing, re-open if you disagree!
