### ISSUE TITLE
Sensu Resource Names

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#535]
GraphQL introduced globally unique identifiers to sensu resources. It occurs to us that some of our interfaces, our middleware, and our use of contexts could be simplified if we use SRNs to refer to all sensu resources internally.

I'd like us to have a good unerstanding of:

- How/where SRNs are exposed to the user
- The implications of SRNs on RBAC
- If the store's paths can be more easily determined based on SRNs
- How will our use of contexts change with the introduction of SRNs
- What changes to middleware will be made

And any other thoughts or questions people have about SRNs.

**Comment by echlebek** [comment]
I think we basically already have this, it's just not exposed to users. (etcd keys like /sensu.io/...)

Do we intend to pursue this as a first-class concept in Sensu?

**Comment by annaplotkin** [comment]
We've decided against doing this. Closing.
