### ISSUE TITLE
Integration tests for middleware

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#537]
We should more thoroughly exercise the middlewares interactions with the API and each other. Give queries, is the appropriate data actually making it through middleware?

**Comment by echlebek** [comment]
I think the issue needs more analysis and specification. Some questions:

* Which components are to be integrated in the tests?
* What about GraphQL?
* Go test framework or something else?
* For each middleware, a description of what things need to be tested for, would help clarify this issue and make it much easier to implement.

**Comment by grepory** [comment]
The middleware already has tests.
