### ISSUE TITLE
Re-think datatype update mechanisms

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#632]
When we process an HTTP PATCH request, we update part of an existing data structure according to some about which fields in the datastructure can be updated. Typically, things like IDs cannot be.

Right now, we have two update mechanisms. One which is generic and works with reflection and another for some datatypes that is statically defined. We should decide if we want to use one of these, or neither.

**Comment by annaplotkin** [comment]
This ticket is now obsolete. Closing.
