### ISSUE TITLE
Move to using no-network etcd client in backend

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#697]
We should move to using the in-memory client to the etcdserver instead of creating localhost connections to the embedded etcdserver.

https://godoc.org/github.com/coreos/etcd/etcdserver/api/v3client

**Comment by echlebek** [comment]
#1257 depends on this, moving this into "ready" and moving #1257 into "next".

**Comment by echlebek** [comment]
I used v3client to replace the regular client and it resulted in about 4 panics in the integration tests. I'll have to spend some time digging into what's going on there.

**Comment by echlebek** [comment]
It looks like there is a bug in etcd. I've filed https://github.com/coreos/etcd/issues/9621

**Comment by echlebek** [comment]
We aren't going to do this.

**Comment by echlebek** [comment]
We should totally do this.
