### ISSUE TITLE
Assets for Backend Event Mutators and Handlers

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#698]
As a user, I would like to register assets for my mutator and handler scripts. The Backend should be able to fetch them prior to command execution, just as the Agent does for Checks.

Requires https://github.com/sensu/sensu-go/issues/2038

**Comment by grepory** [comment]
Let's say this requires #2038 for now.

**Comment by jkerry** [comment]
This has become a pretty nasty roadblock for us. 👍 from NCR
