### ISSUE TITLE
Mutator Hooks

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#701]
Extend hook functionality to mutators! A mutator hook will respond to mutator results in the same way that a check hook responds to check results. Response codes (HookList type) can range from “1”-“255” or can fall under one of the following severities: "ok", "warning", "critical", "unknown", "non-zero”. The owner of this ticket can, and probably should, explode out the suggested subtasks.

- [ ] add a HookList to mutator.proto `repeated HookList mutator_hooks`
- [ ] regenerate protobufs with `scripts/genproto.sh`
- [ ] AddMutatorHook function in mutator backend
- [ ] add_hook command in mutator cli
- [ ] addMutatorHook route in mutator router
- [ ] RemoveMutatorHook function in mutator backend
- [ ] remove_hook command in mutator cli
- [ ] removeMutatorHook route in mutator router
- [ ] retrieve and store all Hooks associated with a mutator
- [ ] execute mutator hooks upon receiving mutator result
- [ ] implement the hook stdin at execution
- [ ] corresponding validators, tests, etc.

**Comment by grepory** [comment]
We can revisit this idea if it's asked for.
