### ISSUE TITLE
Handler Hooks

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#702]
Extend hook functionality to handlers! A handler hook will respond to handler results in the same way that a check hook responds to check results. Response codes (HookList type) can range from “1”-“255” or can fall under one of the following severities: "ok", "warning", "critical", "unknown", "non-zero”. The owner of this ticket can, and probably should, explode out the suggested subtasks.

- [ ] add a HookList to handler.proto `repeated HookList handler_hooks`
- [ ] regenerate protobufs with `scripts/genproto.sh`
- [ ] AddHandlerHook function in handler backend
- [ ] add_hook command in handler cli
- [ ] addHandlerHook route in handler router
- [ ] RemoveHandlerHook function in handler backend
- [ ] remove_hook command in handler cli
- [ ] removeHandlerHook route in handler router
- [ ] retrieve and store all Hooks associated with a handler
- [ ] execute handler hooks upon receiving handler result
- [ ] implement the hook stdin at execution
- [ ] corresponding validators, tests, etc.

**Comment by grepory** [comment]
We can revisit this if it's requested.

**Comment by majormoses** [comment]
I think handler hooks make a lot of sense, it allows you to deal with failure scenarios with handlers which often deal with external solutions. For example if a service such as pagerduty is down, hit a rate limit, or authentication issues I would like to be able to send something like a slack message to notify the operators.

**Comment by echlebek** [comment]
We haven't seen much demand or traction on this issue and it's getting quite old now. I'm going to close it. If we see revived interest, we can always file a new issue or open this one again.
