### ISSUE TITLE
Check output metric extraction

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#745]
As a user, I would like to extract metrics from my Check execution output, and have them added to the Event Metrics (using the [Sensu Metrics Format](https://github.com/sensu/proposal/blob/master/design/7-sensu-metric-format.md)).

In order to accomplish this, the user needs to be able to declare two things in Check configuration:

- [x] The expected Check output metric format (e.g. `metric_format: nagios_perfdata`)
- [x] The Event Handlers to use for the extracted metrics (e.g. `metric_handlers: [influxdb]`)

In order to support a separate set of Event Handlers for metrics, Event.Metrics must contain more than metric points, e.g. `Event.Metrics.Handlers=[]` and `Event.Metrics.Points=[]`. These values need to be set by the Sensu Agent after successful Check output metric extraction, e.g. `Event.Check.MetricHandlers` -> `Event.Metrics.Handlers`.

The Sensu Agent will need to understand metric formats commonly used in Sensu 1.x check output in order to transform them into the [Sensu Metrics Format](https://github.com/sensu/proposal/pull/10):

- [x] [Nagios PerfData](https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/3/en/perfdata.html)
- [x] [Graphite plaintext](http://graphite.readthedocs.io/en/latest/feeding-carbon.html#the-plaintext-protocol)
- [x] [OpenTSDB line](http://opentsdb.net/docs/build/html/user_guide/writing.html#data-specification)
- [x] [InfluxDB line](https://docs.influxdata.com/influxdb/v1.4/write_protocols/line_protocol_tutorial/#measurement)

Sensu Inc. engineers have access to the [Sensu Enterprise metric parsers](https://github.com/sensu/sensu-enterprise/blob/master/lib/sensu/enterprise/extensions/metric_parsers.rb), which can be used as implementation examples.

Check execution -> Check output -> Agent metric extractor -> Event Metrics -> Event -> Backend

## Acceptance Criteria

As a user, using a service check for metric collection:

- I must specify the output metric format and the metrics handlers of a check
- I can use one of the following metrics format
-- nagios_perfdata
-- graphite_plaintext
-- opentsdb_line
-- influxdb_line
- I can specify different handlers for Event incidents and metrics (`Event.Check.Handlers` vs `Event.Check.MetricHandlers`)

**Comment by portertech** [comment]
I am working on this issue this week. Needs clarity.

**Comment by palourde** [comment]
@portertech What's the status of that issue? Does it still need some grooming?

**Comment by portertech** [comment]
@palourde @nikkiattea let's discuss this in detail tomorrow afternoon (Tuesday).

**Comment by portertech** [comment]
An Agent data format "transformer" takes Event.Check.Output and creates Event.Metrics.Points (using the Sensu 2.x Metric Format).

We need tickets for:

- [ ] Support for Check `metric_format` and `metric_handlers` (Struct)
- [ ] Agent `nagios_perfdata` data format "transformer"
- [ ] Agent logic for `metric_format` (apply `nagios_perfdata` transformer)
- [ ] Agent `graphite_plaintext` transformer
- [ ] Agent `influxdb_line` transformer
- [ ] Agent `opentsdb_line` transformer

**Comment by nikkiki** [comment]
All subtasks of the epic have been completed! Closing this out 💪 🎉
