### ISSUE TITLE
Do not commit fileb0x output

### ISSUE THREAD

**Issue by jamesdphillips** [sensu/sensu-go#761]
- When we do releases `backend/dashboardd/ab0x.go` changes after the dashboard build is run.
- Ideally this file isn't committed at all; otherwise each time we make a even the simplest change to the dashboard we'll need to rebuild.
- Will have to find a way around `HTTP` handler not being present. (Possibly with build tag?)

**Comment by palourde** [comment]
I'm closing that since fileb0x will likely be replaced!
