### ISSUE TITLE
Agent StatsD listener

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#85]
The Sensu agent needs to accept Sensu events and telemetry data. 

Initial ideas include:

- HTTP /events (with basic authentication or full RBAC?)
- TCP line protocol (utilize the websocket protocol? Do we need this?)
- Statsd TCP/UDP listeners (the only protocol that doesn't use the Sensu event structure)

**Comment by portertech** [comment]
Atlassian has a open source Statsd server implementation library at https://github.com/atlassian/gostatsd The Sensu Agent listener can use https://github.com/atlassian/gostatsd/blob/master/pkg/statsd/statsd.go

**Comment by calebhailey** [comment]
Niiiiiiiice.

**Comment by portertech** [comment]
The proposal has been updated/improved and work has been spec'd out 🎉 

Closing in favour of:

https://github.com/sensu/sensu-go/issues/1123
https://github.com/sensu/sensu-go/issues/1124
https://github.com/sensu/sensu-go/issues/1126
https://github.com/sensu/sensu-go/issues/1127
https://github.com/sensu/sensu-go/issues/1128
