### ISSUE TITLE
Investigate alternatives to fileb0x

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#910]
Fileb0x generates some gnarly code, and we're not super thrilled with how it works wrt our build process. We'd like a saner approach to asset management. So we're going to investigate a couple of options:

- https://github.com/tv42/becky
  - example use: https://github.com/echlebek/erickson/tree/master/assets

and

- https://godoc.org/bitbucket.org/mjl/httpasset
  - an implementation of: https://godoc.org/golang.org/x/tools/godoc/vfs
  - which is used in godoc: https://github.com/golang/tools/blob/master/cmd/godoc/main.go

**Comment by echlebek** [comment]
I looked at using becky, but I think a vfs type thing might fit our existing usage patterns better. (read: would be less work)
