### ISSUE TITLE
[UX] Capitalization Convention

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#912]
## Context
After seeing Caleb interacting for the first time with Sensu 2 and our documentation, I realized we might have a problem around our naming convention, more precisely around the (missing?) capitalization convention in our UIs.

## Example
Using sensuctl, if I retrieve an entity encoded in JSON:

```
{
  "id": "scotch",
  "keepalive_timeout": 120,
  "system": {
    "hostname": "scotch.local"
  }
  [...]
}
```

We see that the attributes use the **underscore** convention (e.g. `keepalive_timeout`).

However, if I wanted to use that same attribute in a check (e.g. for token substitution), I would have to use `{{ .KeepaliveTimeout }}`, `{{  .ID }}` (uppercase for abbreviations) or `{{ .System.Hostname }}` (nested attribute).

I believe it will quickly lead to confusion and unnecessary friction for our users.

## Possible Solution
I can see few possible solutions, but I'm not sure if they are all be possible.

### Use Pascal Casing (`KeepaliveTimeout`)
Since all exported attributes in Go must follow this capitalization convention, that might be the most natural way codewise, since it wouldn't require much modifications except for the JSON field names. However, since users would have to strictly follow this convention, it might add some complexity and the JSON produced might not be totally _RESTful_. 

### Use Camel Casing (`keepaliveTimeout`)
That would definitively require refactoring work for some existing functionalities, which I'm not 100% sure they could support. However, the JSON produced might feel more natural for some and it would still require to update some JSON fields to remove any underscore.

### Make All Functionalities Case Insensitive 
I believe that would the best solution in terms of UX but it would involve refactoring of some functionalities and I don't think some of them could support it (Go templating? Govaluate?).

**Comment by palourde** [comment]
Random thoughts: Consul is using a function named `key` for accessing key values. We could totally do something similar and deal with the casing there.

https://github.com/hashicorp/consul-template#quick-example

**Comment by echlebek** [comment]
We brought this on ourselves by insisting to the Go json encoder that we wanted specific keys for JSON messages. (eg, `json:"keepalive_timeout"`)

JSON does not specify any preference for key format. Any preference is cultural.

If we instructed the protobuf compiler to not generate these json tags, then we would have a unified naming convention.
