### ISSUE TITLE
Add filtering to HTTP API

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#927]
As a user, I want to be able to filter the results of `sensuctl event list` by status, environment/org, tag values.

**Comment by grepory** [comment]
@annaplotkin Let's revisit this entirely and prioritize where filtering belongs. This has implications for both the webui and sensuctl.

**Comment by palourde** [comment]
Implemented in enterprise: https://docs.sensu.io/sensu-go/5.8/api/overview/#filtering
