### ISSUE TITLE
Consistent sensu <resource> import UX

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#943]
For all import commands, we want to import the configuration from a file or STDIN and output a config file and/or errors. Should we make this a "best effort" import, write what we can, and then emit errors for checks that cannot be imported to STDERR?

Alongside this, also add an optional flag for create that reads from a file (and supports the creation of multiple objects).

**Comment by echlebek** [comment]
We met about this issue, and discussed how the import should work. The conclusion we came to is that we should adopt a `sensuctl create -f` type command, and then make the import tool generate a file that we can use with this.

So this task is now blocked on #1056.

When implementing this work, we need to be able to traverse a Sensu 1.x resource directory, handling fragments the way that Sensu 1.x does.

Sensu 1.x can deep-merge resource fragments, and does so with this logic: https://github.com/sensu/sensu/blob/44dc4263021782728c0d12b24f57c4cefd8e9360/lib/sensu/utilities.rb#L33-L52

The logic is tested here https://github.com/sensu/sensu/blob/master/spec/utilities_spec.rb#L27-L64, and some larger-scale loader tests are here: https://github.com/sensu/sensu-settings/blob/master/spec/loader_spec.rb

It will take some careful work to correctly implement this merging in Go, but should largely be mechanical work, given that we implement the tests correctly. :smile:

**Comment by calebhailey** [comment]
> The conclusion we came to is that we should adopt a `sensuctl create -f` type command, and then make the import tool generate a file that we can use with this.

Love it!

**Comment by palourde** [comment]
Closing that in favour of https://github.com/sensu/sensu-go/issues/1056
