### ISSUE TITLE
show diff when updating objects

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#949]
Is it possible to show the delta between an existing object and an update when updating the object with the dashboard or sensuctl?

**Comment by echlebek** [comment]
It should be reasonably easy to respond to PUT requests with a total-context, unified diff of the changes that were made as a result of the operation. I imagine the default format would be json but we could consider other things like yaml.

However, correctly identifying the state of the object that was modified requires store support - we need to retrieve the current state of the object before modifying it, in a transaction. This would have a performance impact, and we would need to measure that impact and decide if it's acceptable as part of discovery.
