### ISSUE TITLE
Add ID to CheckRequest

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#979]
In Sensu 1.x, users could understand where check requests came from, since they were usually encapsulated by a RabbitMQ message. Users could observe check requests emanating from a backend, going into the queue, and then being delivered to one or more agents.

This means that in Sensu 1.x, check execution events had a strict weak ordering.

In Sensu 2.x, no such ordering exists. Check requests are sent via websocket to agents, and there is no specialized transport that introduces this concept of ordering. So, when an agent executes a check in Sensu 2.x, there is no way to know which round of scheduling triggered it.

This causes an issue when validating a feature like round robin scheduling. How do we know that if an agent executes a check, that it was because it was its turn to do so? How do we know that the check it executed was a different one than the one that was executed by the previous agent in the round robin?

Add a unique ID to CheckRequest and populate it with an ID that is unique within the cluster. Two backends must never select the same ID. Make sure the backend logs the ID when scheduling the check request, and agents log the ID when the execute check requests.

Improve the round robin scheduling end-to-end test to ensure that all events have a _unique_ check ID. Improve the check scheduling end-to-end test to ensure that all events in a scheduling round have the _same_ check ID.

**Comment by annaplotkin** [comment]
Not a concern right now, closing.
