### ISSUE TITLE
Implement delete command for assets in sensuctl

### ISSUE THREAD

**Issue by amdprophet** [sensu/sensu-go#988]
It looks like the "delete" functionality for assets is missing in sensuctl.

**Comment by grepory** [comment]
This is likely going to require some relational data between assets and checks, but we might want to do something like warn you if you're deleting an asset that's being used by checks, and then list which checks those are.

**Comment by avanier** [comment]
Hey, I'll bump this guy. Having it would be a cool feature.

**Comment by annaplotkin** [comment]
This requires some thought around how we want to expose dependencies for assets (checks that use them for instance).

**Comment by ninjasloth22** [comment]
Perhaps in the interim a force flag or something of the sorts could be provided? 
Until there is a more graceful method this would give users a way to remove assets once they have down their own sanity checking.

**Comment by nikkixdev** [comment]
MVP:
- delete `Asset` resource only
- tarball remains on disk (operator responsibility to clear the cache - DOCUMENT THIS)
- checks, mutators, handlers, filters and hooks will likely fail to run until `runtime_assets` are updated in their respective configs
- check/hook failures will be surfaced in event data
- mutator/handler/filter failures will only be surfaced in backend logs
- transparent documentation about the behavior
